### ISSUE TITLE
[prod-preview] Quickstarts failing

### ISSUE THREAD

**Issue by pbergene** [openshiftio/openshift.io#1513] opened 2017-12-06 13:50 UTC
Following the move to free-stg we are seeing an issue with quickstarts on prod-preview.

Fails with quickstart error: "The repository X already exists!"

Seeing the following on console:
POST https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/execute 500 (Internal Server Error)
POST https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/execute 412 (Precondition Failed)
POST https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/execute 412 (Precondition Failed)

The symptons match https://github.com/openshiftio/openshift.io/issues/1503 but a pod restart does not remedy it, I have not seen the inotify errors, but will grep through a downloaded log to be sure.

We have changed the openshift.api.url to point to free-stg.  keycloak.saas.url points to appsec, but it is my understanding that this is not in use.

@gastaldi is this something you can look at?

**Comment by gastaldi** [comment] 2017-12-06 14:00
Can we have access to this project in https://console.free-stg.openshift.com/console? Add @edewit 's user too

**Comment by pbergene** [comment] 2017-12-06 15:25
Should be ok now :)

**Comment by gastaldi** [comment] 2017-12-06 15:26
I see the following errors in the logs: 
```
Caused by: io.fabric8.forge.generator.keycloak.KeyCloakFailureException: KeyCloak failed to return a token for GitHub on https://auth.prod-preview.openshift.io/api/token?for=https://github.com
  | at io.fabric8.forge.generator.keycloak.KeycloakClient.getResponseBody(KeycloakClient.java:78)
  | at io.fabric8.forge.generator.keycloak.KeycloakClient.getTokenFor(KeycloakClient.java:48)
  | at io.fabric8.forge.generator.keycloak.TokenHelper.getMandatoryTokenFor(TokenHelper.java:68)
  | at io.fabric8.forge.generator.git.GitAccount.loadFromSaaS(GitAccount.java:73)
  | at io.fabric8.forge.generator.github.AbstractGitHubStep.createGitHubFacade(AbstractGitHubStep.java:56)
  | at io.fabric8.forge.generator.quickstart.Fabric8ProjectInfoStep.initializeUI(Fabric8ProjectInfoStep.java:104)
  | at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
  | at io.fabric8.forge.generator.quickstart.Fabric8ProjectInfoStep_$$_javassist_5340f0e7-d269-41a2-ab0b-de80c298c288.initializeUI(Fabric8ProjectInfoStep_$$_javassist_5340f0e7-d269-41a2-ab0b-de80c298c288.java)
  | at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.initialize(WizardCommandControllerImpl.java:121)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
  | ... 64 more
  | Caused by: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:199)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:473)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:165)
  | at io.fabric8.forge.generator.keycloak.KeycloakClient.getResponseBody(KeycloakClient.java:76)
 ```

Anything wrong with the auth service @alexeykazakov ?

**Comment by ldimaggi** [comment] 2017-12-06 19:48
https://github.com/openshiftio/openshift.io/issues/1514 is blocking me from even running a quickstart on prod-preview.

**Comment by alexeykazakov** [comment] 2017-12-06 23:22
I don't see any errors from Auth service for the last 12 hours for pbergene-osiotest1 user.
@gastaldi what user got this error? 401 from /api/token?for usually means there is a problem with the user access token or GitHub was not linked. I need username/id to provide more details.

**Comment by gastaldi** [comment] 2017-12-06 23:25
@pbergene what user did you use?

**Comment by pbergene** [comment] 2017-12-07 09:55
pbergene-osiotest1, but linked to gh pbergene it seems.  Having failed back again to free-int this may have been resolved, as @jfchevrette successfully ran a quickstart last night.

**Comment by gastaldi** [comment] 2017-12-07 16:40
It works in PROD for me.

**Comment by joshuawilson** [comment] 2017-12-07 16:47
The issue is that prod-preview will soon become prod and then break prod.

**Comment by gastaldi** [comment] 2017-12-07 17:20
I see the following error in the pod logs: 

```
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:209)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:473)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:165)
  | at io.fabric8.forge.generator.tenant.Tenants.loadTenant(Tenants.java:47)
  | at io.fabric8.forge.generator.tenant.Tenants.loadNamespaces(Tenants.java:56)
  | at io.fabric8.forge.generator.pipeline.ChoosePipelineStep.lambda$initializeUI$0(ChoosePipelineStep.java:150)
  | at org.infinispan.cache.impl.TypeConverterDelegatingAdvancedCache.lambda$convertFunction$1(TypeConverterDelegatingAdvancedCache.java:101)
  | at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
  | at org.infinispan.cache.impl.AbstractDelegatingCache.computeIfAbsent(AbstractDelegatingCache.java:343)
  | at org.infinispan.cache.impl.TypeConverterDelegatingAdvancedCache.computeIfAbsent(TypeConverterDelegatingAdvancedCache.java:157)
  | at io.fabric8.forge.generator.pipeline.ChoosePipelineStep.initializeUI(ChoosePipelineStep.java:150)
  | at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
  | at io.fabric8.forge.generator.pipeline.ChoosePipelineStep_$$_javassist_6e211274-1c72-42a3-8350-eec8e5eb8504.initializeUI(ChoosePipelineStep_$$_javassist_6e211274-1c72-42a3-8350-eec8e5eb8504.java)
  | at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:391)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
 ```

What is this Tenant service and why is it throwing 500?

**Comment by gastaldi** [comment] 2017-12-07 17:33
The following error appears if I CURL with my Authorization token: {"errors":[{"code":"internal_error","detail":"record not found","status":"500","title":"Internal error"}]}

**Comment by pbergene** [comment] 2017-12-08 13:55
I think I have an idea of what is going on - will detail on triage then update. here.

**Comment by mmclanerh** [comment] 2017-12-08 18:08
this is likely related to https://github.com/openshiftio/openshift.io/issues/1569 . needs a decision point on claiming bankruptcy in order to restore service for affected tenants.

**Comment by jfchevrette** [comment] 2017-12-08 20:19
I have done a full reset of the tenant database which has links to namespaces in the backing Openshift cluster. I have also done a full reset of the namespaces in the backing openshift cluster.

I believe this has resolved the quickstart issues as I have been unable to reproduce.

Lets wait for a few +1s before we mark this as resolved

**Comment by jfchevrette** [comment] 2017-12-08 20:29
I've just had a report from @gastaldi that it is still failing for him. Matching error on the generator-backend side is below. Need the feature team to look at this. From that stack trace alone I have no way to understand what failed.

```
2017-12-08 20:22:11,179 SEVERE [org.obsidiantoaster.generator.rest.ObsidianResource] (default task-9) Error while moving to the next wizard step: java.lang.IllegalStateException: Error while moving to the next wizard step
--
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:107)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.getWizardStepsMetadata(WizardCommandControllerImpl.java:485)
  | at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.getWizardStepsMetadata(NoUIWizardControllerDecorator.java:145)
  | at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
  | at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_b402caaf-a3b7-4fb5-a5ba-0b5b92c593a4.getWizardStepsMetadata(CommandController_$$_javassist_b402caaf-a3b7-4fb5-a5ba-0b5b92c593a4.java)
  | at org.jboss.forge.service.util.UICommandHelper.describeCurrentState(UICommandHelper.java:93)
  | at org.jboss.forge.service.util.UICommandHelper.describeController(UICommandHelper.java:76)
  | at org.obsidiantoaster.generator.rest.ObsidianResource.getCommandInfo(ObsidianResource.java:236)
  | at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.getCommandInfo(Unknown Source)
  | at sun.reflect.GeneratedMethodAccessor359.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
  | at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  | at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
  | at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  | at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  | at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
  | at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
  | at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
  | at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
  | at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
  | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
  | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:209)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:473)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:165)
  | at io.fabric8.forge.generator.tenant.Tenants.loadTenant(Tenants.java:47)
  | at io.fabric8.forge.generator.tenant.Tenants.loadNamespaces(Tenants.java:56)
  | at io.fabric8.forge.generator.pipeline.ChoosePipelineStep.lambda$initializeUI$0(ChoosePipelineStep.java:150)
  | at org.infinispan.cache.impl.TypeConverterDelegatingAdvancedCache.lambda$convertFunction$1(TypeConverterDelegatingAdvancedCache.java:101)
  | at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
  | at org.infinispan.cache.impl.AbstractDelegatingCache.computeIfAbsent(AbstractDelegatingCache.java:343)
  | at org.infinispan.cache.impl.TypeConverterDelegatingAdvancedCache.computeIfAbsent(TypeConverterDelegatingAdvancedCache.java:157)
  | at io.fabric8.forge.generator.pipeline.ChoosePipelineStep.initializeUI(ChoosePipelineStep.java:150)
  | at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
  | at io.fabric8.forge.generator.pipeline.ChoosePipelineStep_$$_javassist_6e211274-1c72-42a3-8350-eec8e5eb8504.initializeUI(ChoosePipelineStep_$$_javassist_6e211274-1c72-42a3-8350-eec8e5eb8504.java)
  | at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:391)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
  | ... 64 more


```

**Comment by jfchevrette** [comment] 2017-12-08 20:32
According to @gastaldi closing/reopening the browser allowed him to go through the quickstart w/o any errors. Looks like there may be a browser caching issue in here.

**Comment by mmclanerh** [comment] 2017-12-08 23:15
with https://github.com/openshiftio/openshift.io/issues/1569 action being done, this should be able to close out. @gastaldi @ldimaggi are you good with closing this issue?

**Comment by gastaldi** [comment] 2017-12-08 23:36
+1 to close this issue. Works for me

**Comment by mmclanerh** [comment] 2017-12-09 01:31
sound good. considering issue resolved at this time. thanks everyone!

this should mean that quickstarts are now functional across prod-preview. hooray!

**Closed by mmclanerh** 2017-12-09 01:31 UTC
Labels: area/app-wizard, area/quickstarts, SEV1-urgent, team/launcher, team/service-delivery, type/bug

**Comment by pbergene** [comment] 2017-12-11 09:31
+1 works for me this morning

**Comment by ldimaggi** [comment] 2017-12-11 15:21
+2 there are other issues - logged in separate bugs - but I was able to create a new app/quickstart on prod-preview.
