### ISSUE TITLE
Order of spaces is partially random in 'View all Spaces'

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#515] opened 2017-08-09 12:44 UTC
See the attached screenshot - the order in which the spaces are displayed is not alphabetic or chronological:

![screenshot 52](https://user-images.githubusercontent.com/642621/29122059-ee8a5a7e-7cde-11e7-8951-eb44666bf6ff.png)

**Comment by joshuawilson** [comment] 2017-08-13 02:45
Duplicate of https://github.com/fabric8-ui/fabric8-ui/issues/1626
Closing.

**Closed by joshuawilson** 2017-08-13 02:45 UTC
Labels: area/spaces, kind/bug
