### ISSUE TITLE
Idle icon for Che in OCIO status may confuse users

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#770] opened 2017-09-06 20:07 UTC
At present, if Che is idle, the OSIO status display looks like this:

![capture1](https://user-images.githubusercontent.com/642621/30131832-3b7e2efc-931c-11e7-8a39-72604a0eede3.PNG)

From a user's perspective, Che is up as it's possible to create a new codespace from within the OSIO UI without any manual restart/redeploy of Che. 

If the red status icons indicate a failure,
And the black icons indicate that the user must wait, 
And the green status icons indicate that all is well

Should the idle icon also be green?

**Comment by joshuawilson** [comment] 2017-09-06 21:14
@catrobson what do you think? 
I would say that a green "off" icon is not right.

**Comment by catrobson** [comment] 2017-09-06 23:05
We need these icons to update to reflect the new PatternFly status icons, and plan to do so in an upcoming sprint.  Regardless the Idle will not be green, we will leave this as gray because the idea is that it is not currently active as compared with other components that are active.  Long term we have also discussed getting rid of this whole concept in favor of just raising 'issues' in the notification drawer we will be introducing, so I also don't want to invest a lot of cycles into this :).

**Comment by joshuawilson** [comment] 2017-09-07 02:53
Additionally the new Che starter API update makes the idle status moot.

**Comment by qodfathr** [comment] 2018-01-19 16:49
Closing as dupe of #448, although good additional data here which I will xref in 448. Let's finish the discussion in the other issue.

**Closed by qodfathr** 2018-01-19 16:49 UTC
Labels: area/UX, area/status, team/platform, team/ux, type/question
