### ISSUE TITLE
Label selection dropdown has only one Label when switching contexts

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#3001] opened 2018-04-11 10:13 UTC
If I select "Label" from the filter dropdown, then switch sidebar context, then click on the value dropdown of the filter, the dropdown only contains a few or even no entries. I need to select the "Label" filter type from the left dropdown again to refresh the values dropdown.

**Comment by nimishamukherjee** [comment] 2018-04-13 06:46
@vikram-raj can you have a look.

**Comment by vikram-raj** [comment] 2018-04-13 07:17
@nimishamukherjee @michaelkleinhenz I am not able to reproduce this issue. Is only newly added label are not present in the dropdown or older labels as well?

**Comment by nimishamukherjee** [comment] 2018-04-30 09:56
@michaelkleinhenz closing this as we are not able to replicate the issue.
If you observe the issue, please re-open this issue.

**Closed by nimishamukherjee** 2018-04-30 09:56 UTC
Labels: SEV2-high, area/planner, team/planner, type/bug
