### ISSUE TITLE
In Planner, viewing text in a long description is not intuitive

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4262] opened 2018-08-28 14:30 UTC
##### Issue Overview
If user writes a long description in a workitem, the steps required to view the text is not intuitive. See the attached screenshot - the "see more" text is easily overlooked. I think that users would expect to see some means to scroll the text in the description with a scroll bar.

##### Steps To Reproduce
1. Create a workitem with a long description
2. Observe the "see more" text is the only indication that the text exceeds the description text box:
![screenshot from 2018-08-28 10-03-46](https://user-images.githubusercontent.com/642621/44729695-5b24c280-aaad-11e8-8053-60fbaa81fd65.png)

**Comment by stevengutz** [comment] 2018-08-29 11:14
@ldimaggi Is this really a bug.  Looks like a impediment/feature request to me.  The code is doing what it was designed to do

**Comment by michaelkleinhenz** [comment] 2018-08-29 11:25
Agree. This is a feature request. Also, a story describing a solution for this should include what to do with very long descriptions. Possibly, we just want to increase the default displayed text size so that it covers most of the standard use cases.

**Comment by michaelkleinhenz** [comment] 2018-08-29 12:29
See Planner userstory here: https://openshift.io/openshiftio/Openshift_io/plan/detail/399

**Comment by joshuawilson** [comment] 2018-10-30 15:46
Closing as this was moved to planner.

**Closed by joshuawilson** 2018-10-30 15:46 UTC
Labels: SEV3-medium, area/UX, area/planner, priority/P4, team/planner, type/feature-request
