### ISSUE TITLE
Incorrect details on Github's  PR Checks view

### ISSUE THREAD

**Issue by gorkem** [openshiftio/openshift.io#4544] opened 2018-11-14 19:02 UTC
##### Issue Overview
The details link on a PR check result created by Toolchain leads to an undefined URL. 

##### Expected Behaviour
The details url opens the results of the PR check build

##### Current Behaviour
The details view is populated with a URL similar to [1] 

[1] http://www.unconfigured-jenkins-location.com/job/gorkem/job/abootapp/job/PR-1/1/display/redirect

For instance, in this [PR](https://github.com/gorkem/abootapp/pull/1), it passes the checks correctly when I do a `Show all checks` and click the details link of the `continuous-integration/jenkins/pr-merge` it leads to a wrong URL.

**Comment by piyush-garg** [comment] 2018-11-15 05:52
Duplicate of #1259 that issue has more visibility. closing this.

**Closed by piyush-garg** 2018-11-15 05:52 UTC
Labels: SEV3-medium, area/jenkins, team/deploy, type/bug
