### ISSUE TITLE
Cannot remove space

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3669] opened 2018-05-29 12:52 UTC
1. go to "My Spaces" page
2. remove a space

result: 
* error is displayed, space is still in the list of spaces
* I have 4 spaces that cannot be deleted
```
Object { _body: "{\"errors\":[{\"code\":\"internal_error\",\"detail\":\"could not delete space\",\"status\":\"500\",\"title\":\"Internal error\"}]}\n", status: 500, ok: false, statusText: "Internal Server Error", headers: {…}, type: 2, url: "https://api.openshift.io/api/spaces/e682c19d-7160-43c0-9803-f0217a754c30" }
Object { _body: "{\"errors\":[{\"code\":\"internal_error\",\"detail\":\"could not delete space\",\"status\":\"500\",\"title\":\"Internal error\"}]}\n", status: 500, ok: false, statusText: "Internal Server Error", headers: {…}, type: 2, url: "https://api.openshift.io/api/spaces/4731167f-5c82-441e-a2c5-a5311161eea1" }
Object { _body: "{\"errors\":[{\"code\":\"internal_error\",\"detail\":\"could not delete space\",\"status\":\"500\",\"title\":\"Internal error\"}]}\n", status: 500, ok: false, statusText: "Internal Server Error", headers: {…}, type: 2, url: "https://api.openshift.io/api/spaces/814514f5-8d2b-48ac-8254-3a811217196f" }
Object { _body: "{\"errors\":[{\"code\":\"internal_error\",\"detail\":\"could not delete space\",\"status\":\"500\",\"title\":\"Internal error\"}]}\n", status: 500, ok: false, statusText: "Internal Server Error", headers: {…}, type: 2, url: "https://api.openshift.io/api/spaces/44796557-45c5-416a-93e1-c7de17835cfb" }
_scrollbars.less:6:2
```

![peek 2018-05-29 14-49](https://user-images.githubusercontent.com/445100/40659890-d65fa71c-634f-11e8-949e-2ed0fd89a043.gif)

**Comment by aptmac** [comment] 2018-05-29 14:02
Duplicate of: https://github.com/openshiftio/openshift.io/issues/3503

**Closed by aptmac** 2018-05-29 14:02 UTC
