### ISSUE TITLE
User should be warned in OSIO UI when OpenShift limits are reached

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#873] opened 2017-09-18 20:27 UTC
_From @ldimaggi on July 10, 2017 2:30_

In experimenting with a new (and empty) user account:

* I am seeing a predictable pattern in that a user can create 2 projects - depending on the characteristics of each project - for example - if a user creates a Vert.X project and a Spring Boot Healthcheck project. the stage and run resources look like this:
```
oc describe quota compute-resources -n osiotest3142-stage
Name:		compute-resources
Namespace:	osiotest3142-stage
Scopes:		NotTerminating
 * Matches all pods that do not have an active deadline.
Resource	Used	Hard
--------	----	----
limits.cpu	2	2
limits.memory	1Gi	1Gi
```

* If that user creates ONE Che workspace, however, the Che related workspaces reach the quota:

```
oc describe quota compute-resources -n osiotest3142-che
Name:		compute-resources
Namespace:	osiotest3142-che
Scopes:		NotTerminating
 * Matches all pods that do not have an active deadline.
Resource	Used	Hard
--------	----	----
limits.cpu	5859m	6
limits.memory	3000Mi	3Gi
```

* Warnings are made visible in OpenShift console - but not in the OSIO UI.

_Copied from original issue: fabric8-ui/fabric8-ui#1681_

**Comment by joshuawilson** [comment] 2017-09-18 20:27
_From @ldimaggi on July 10, 2017 2:30_

Related to:
https://github.com/openshiftio/openshift.io/issues/355

**Comment by joshuawilson** [comment] 2017-09-18 20:27
_From @ldimaggi on July 10, 2017 2:32_

Also note - if a user attempts to create a 2nd Che workspace, this error is logged in Che:

```
[ERROR] Pod with deployment name che-ws-q2jpva15vr6sho4t not found
[ERROR] Pod with deployment name che-ws-q2jpva15vr6sho4t not found
```

But - no error is displayed in the OSIO UI.

**Comment by joshuawilson** [comment] 2017-09-18 20:27
_From @ldimaggi on July 19, 2017 18:13_

Related to:

https://github.com/fabric8-ui/fabric8-ui/issues/1214

**Comment by qodfathr** [comment] 2018-01-19 19:25
@joshuawilson is this different than #874? Can we close one as a dupe of the other. As mentioned in #287, we need an entire epic devoted to quota.

**Comment by ldimaggi** [comment] 2018-01-19 20:24
Closing as duplicate of #874

**Closed by ldimaggi** 2018-01-19 20:24 UTC
Labels: SEV4-low, area/app-wizard, team/platform, type/bug
