### ISSUE TITLE
[Che-MT] Problems with deleting multiple workspaces at once.

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#1620] opened 2017-12-11 14:57 UTC
Steps to reproduce:
1) Have multiple workspaces created.
2) Using che.openshift.io dashboard, go to "Workspaces" -> Select all -> Delete.

che dashboard seems to succesfully delte workspaces, but looking into <user>-che project on oso, one can see lots of errors:
![image](https://user-images.githubusercontent.com/1215011/33837012-5b923304-de8b-11e7-94e2-96633805f40b.png)

These `delete-xxx` pods seems to be stuck (I've waited for quite some time, but none of them was succesfully created)

output of `oc get events`: https://pastebin.com/5h5gFyip

**Comment by ldimaggi** [comment] 2017-12-11 15:22
It looks like you are hitting:  https://github.com/openshiftio/openshift.io/issues/1607

Question - Is the Che pod up/running when you try to delete the workspaces?

**Comment by rhopp** [comment] 2017-12-11 15:29
Only one workspace pod can be running at time. So yes... one is running, but all the other ones are not (I'm deleting > 5 workspaces)

**Comment by ibuziuk** [comment] 2018-01-24 11:48
@rhopp is it still reproducible ?

**Comment by rhopp** [comment] 2018-01-24 13:02
Yes. Deleting multiple workspaces at once spawns multiple "delete-<wkspc-name>" pods and it seems like they are racing for mounting the same volume.
But it is more like a cosmetic thing... Given enough time, they all manage to succesfully mount the volume, do their thing and die ;-)

**Comment by ibuziuk** [comment] 2018-01-24 13:32
@rhopp ok, this looks like infra ebs thingy. Am I correct that this has no impact from the user-perspective ? if so, I would probably set it as low priority

**Comment by rhopp** [comment] 2018-01-24 13:52
The only scenario affecting user I could imagine is:
1) delete multiple workspaces
2) immediately start new workspace

In this case, I think, the workspace pod could enter the race for volume with those "delete-<name>" pods.
But this theory is not confirmed (I didn't try this).
Setting this issue to low priority is ok with me.

**Comment by ibuziuk** [comment] 2018-11-28 09:49
@rhopp wondering if you could confirm you theory if removal of multiple workspaces could prevent new workspace from startup. If this is the case we need to open an issue upstream.

**Comment by Katka92** [comment] 2018-11-28 11:17
Hi, I've tried it on production with 5 and 8 workspaces and works fine. "delete-" pods were started quickly and there was no problem with immediately starting new workspace. 

The flow was: 
* create 9 worksapces
* start one workspace
* delete 8 worksapce (including the running one)
* start remaining workspace

**Comment by Katka92** [comment] 2018-11-28 13:11
@ibuziuk I've tried to create and run 7 workspaces. Then I deleted them at once and immediately run another workspace. All workspaces were removed (including data on PVC) and workspace was started successfully. When I investigated events, sometimes I saw warning:
```
21m       21m       1         rm-workspace150yb5frg3mamx88.156b4a79b876e660                             Pod                                                       Warning   FailedCreatePodSandBox   kubelet, ip-172-31-69-99.us-east-2.compute.internal    Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c559af36a1110959ce1e1cebdfd4fb157c6c48504452d2290c3a3ec4ffa99619" network for pod "rm-workspace150yb5frg3mamx88": NetworkPlugin cni failed to set up pod "rm-workspace150yb5frg3mamx88_kkanova-che" network: CNI request failed with status 400: 'pods "rm-workspace150yb5frg3mamx88" not found
'
```
But it didn't show every time and it seems it is not strictly connected with removing more than one workspace. 
Hope this report helped.

**Comment by ibuziuk** [comment] 2018-11-28 14:11
Thanks, for investigation. According to your findings workspace removal works as expected. Closing.

**Closed by ibuziuk** 2018-11-28 14:11 UTC
Labels: SEV3-medium, area/che, area/workspaces, priority/P3, team/che/osio, type/bug
