### ISSUE TITLE
Doing an import codebase and selecting the default options seems to kick off master builds continually

### ISSUE THREAD

**Issue by pmuir** [openshiftio/openshift.io#113] opened 2017-04-29 18:46 UTC
It looks like this registers a webhook for all events on github, which in turn is kicking off a build for any change to the github repo, not just pushes to master.

Note that this wizard allows you to select CI as well as build master, which we ticked when importing this repo.

@jstrachan @rawlingsj ^^^

## Impacts
- [ ] #2085 Getting Started Quickly with a Framework - from Import, to IDE, to Deployment

**Comment by joshuawilson** [comment] 2017-05-22 02:59
This issue was moved to fabric8io/fabric8-ui#1362

**Comment by RanjithRV** [comment] 2018-01-08 19:13
@joshuawilson looks like this issue was moved to #1362 and that in turn was associated to https://github.com/openshiftio/openshift.io/issues/353 
353 was closed as it was determined to track issue individually based on the last comment. 

Since both the referencing tickets are closed can we close this one as well? Or is there work still to be done on this one?

**Comment by joshuawilson** [comment] 2018-01-08 19:37
Nothing has been done according to the comments. This should stay open until it can be verified.

**Comment by joshuawilson** [comment] 2018-01-08 19:40
If this is still happening it is important to fix. 
@chmouel @rupalibehera I do not know if this is a build issue, can you please take a look.

**Comment by rupalibehera** [comment] 2018-04-24 12:38
This issue is not reproducible now, and this was fixed long back https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/resources/jenkins-job-template.xml#L37,
The pipeline only kicks for master and PR builds

**Comment by rupalibehera** [comment] 2018-04-24 12:41
I am closing this issue now as it is not reproducible, please open it again if required.

**Closed by rupalibehera** 2018-04-24 12:41 UTC
Labels: SEV2-high, area/app-wizard, area/codebases, priority/P0, team/build-cd, team/che/platform, team/che/plugins, train/heather, type/bug
