### ISSUE TITLE
Getting Started Doc: Application Wizard window needs updating

### ISSUE THREAD

**Issue by petra-sargent** [openshiftio/openshift.io#2595] opened 2018-03-14 19:29 UTC
Section 4.2 Creating a new project 
Step 2c The screenshot has the organization field but that field is not available

**Comment by joshuawilson** [comment] 2018-03-15 04:01
cc @rkratky

**Comment by mishaone** [comment] 2018-03-22 03:18
Hi @petra-sargent, can you elaborate on what the issue is here? I interpreted this as that you can't use the drop down box for the organization field, which should be okay anyway since the instructions are to leave it as the default value. I tested this anyway to get an idea of the problem but it works fine for me:

![test](https://user-images.githubusercontent.com/926572/37749408-8290d64e-2dd3-11e8-9510-109e2958ebdc.png)

Can you give some more information on the issue?

**Comment by petra-sargent** [comment] 2018-03-22 20:49
@mishaone  The organization field was not available on the GUI when I was defining the project. The OpenShift Project, Group ID and Version were the only fields available on the GUI. Next time, I will take a screenshot!   It looks like the Organization field is available in the screenshot that you provided.

**Comment by mishaone** [comment] 2018-03-23 00:20
@petra-sargent do log in yourself and check it out. Maybe you were on the preview site with a particular build or something. I've never seen that particular field go away so far.

**Comment by mishaone** [comment] 2018-03-25 23:07
Closing for keeping things organized since there doesn't seem to be an issue anymore. Please reopen with details if the problem still exists.

**Closed by mishaone** 2018-03-25 23:07 UTC
Labels: area/docs, team/docs, type/bug
