### ISSUE TITLE
Selecting Execution level of Planner should expand through to Tasks

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#3474] opened 2018-05-06 02:13 UTC
Viewed a sprint; expansion stopped at Features. It should expand Features to show the Tasks.

![image](https://user-images.githubusercontent.com/16322190/39669141-778b78d4-50b1-11e8-80b6-0938766bb07a.png)
e.g., the child Tasks of 20 should be displayed automatically.

**Comment by nimishamukherjee** [comment] 2018-05-06 03:40
@qodfathr The planner shows exact matches. All features, bugs, and tasks that belong to an iteration are displayed.
If a task is in an iteration, the tree is expanded to display the task.
![execution](https://user-images.githubusercontent.com/1892722/39669571-1f29a614-510d-11e8-85f2-a566b7592746.png)

**Comment by michaelkleinhenz** [comment] 2018-05-06 07:09
@qodfathr auto-expansion always is based on the matching state. If the Feature has Tasks that are in the Iteration, then it expands.

This is a generic behaviour across all contexts: auto-expansion always stops at the lowest matching WI. Changing this behaviour for Execution would seriously break the genericness of the behaviour.

Also, having a Feature in an Iteration while it's tasks are not seem odd to me.

**Comment by maxandersen** [comment] 2018-05-06 08:16
> Also, having a Feature in an Iteration while it's tasks are not seems odd to me.

just want to comment that the above is not odd if the tasks are made before you 

a) fully define the tasks, or when you move the feature to another iteration

b) the tasks are in specific iterations where as feature is in a release train iteration.


for a) better support in UI to ask what user want to happen for children if they should move with the feature (and ui should let me map possible many iteration to many other iterations)

for b) this is where having a way to say you want iteration AND its children iteration show would help a lot imo.

**Comment by qodfathr** [comment] 2018-05-06 10:52
I just looked at the sprint on my phone, and the tasks are displaying. So it behaved differently on my laptop when I took the screenshot. I will recheck on my laptop.

**Comment by qodfathr** [comment] 2018-05-06 11:05
It's now rendering properly on my laptop. Do we have a theory as to why the tasks did not show the first time?

**Comment by michaelkleinhenz** [comment] 2018-05-06 12:26
@maxandersen I'd say a) is indeed happening if for example the Feature was not completed in an Iteration and is moved to a followup Iteration. Bit even then, I would find the behaviour correct as it shows what is actually in the Iteration and tries to only show context as it is needed to understand the state of the work.

b) on the other hand is a boundary case where the process might clash with the behaviour implemented. For example, we're currently treating all Features assigned to just "Iris" as uncommitted for Execution. So it is easy to see which Features are actually committed and which are planned for the train.

So for displaying the child's, this would make things more complicated to view for our current usage pattern. So I'd say this behaviour should be user-configurable.

**Comment by michaelkleinhenz** [comment] 2018-05-06 12:30
@qodfathr if you can reproduce the issue, please capture if the tasks in the non-auto-expanded child list are in bold font. 

I just checked on prod and it works for me. Auto-expand always expands down to the matching entries.

**Comment by nimishamukherjee** [comment] 2018-06-12 10:21
Closing as issue is not seen on prod

**Closed by nimishamukherjee** 2018-06-12 10:21 UTC
Labels: SEV3-medium, area/planner, team/planner, type/bug
