### ISSUE TITLE
health-check - Wildfly-swarm quickstart/booster fails to build - should be removed from OSIO until it builds

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3124] opened 2018-04-13 17:12 UTC
Steps to recreate:
* Create a new app in the laucnher, select mission = Health-check, runtime = WildFly-swarm
* Observe the build fail - error reported in the Jenkins build log:
java.io.IOException: Mount point not found

```
[0m[0m2018-04-13 16:24:36,214 INFO  [org.jboss.remoting] (MSC service thread 1-8) JBoss Remoting version 4.0.24.Final-redhat-1
[0m[31m2018-04-13 16:24:36,420 ERROR [stderr] (Controller Boot Thread) java.io.IOException: Mount point not found
[0m[31m2018-04-13 16:24:36,421 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
[0m[31m2018-04-13 16:24:36,421 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
[0m[31m2018-04-13 16:24:36,421 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
[0m[31m2018-04-13 16:24:36,421 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
[0m[31m2018-04-13 16:24:36,422 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
[0m[31m2018-04-13 16:24:36,422 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
[0m[31m2018-04-13 16:24:36,422 ERROR [stderr] (Controller Boot Thread) 	at java.nio.file.Files.getFileStore(Files.java:1461)
[0m[31m2018-04-13 16:24:36,422 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.getPosixAttributes(FilePersistenceUtils.java:129)
[0m[31m2018-04-13 16:24:36,422 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.createTempFileWithAttributes(FilePersistenceUtils.java:117)
[0m[31m2018-04-13 16:24:36,422 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.writeToTempFile(FilePersistenceUtils.java:104)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceResource.doCommit(FilePersistenceResource.java:51)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.commit(AbstractFilePersistenceResource.java:58)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.ModelControllerImpl$4.commit(ModelControllerImpl.java:791)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:743)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:680)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
[0m[31m2018-04-13 16:24:36,423 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1349)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:495)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:389)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:351)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.server.ServerService.boot(ServerService.java:402)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.server.ServerService.boot(ServerService.java:371)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:301)
[0m[31m2018-04-13 16:24:36,424 ERROR [stderr] (Controller Boot Thread) 	at java.lang.Thread.run(Thread.java:748)
[0m[0m2018-04-13 16:24:36,714 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
[0m[0m2018-04-13 16:24:36,716 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
[0m[0m2018-04-13 16:24:36,716 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.1.18.Final-redhat-1 "Kenny" started in 18002ms - Started 111 of 117 services (25 services are lazy, passive or on-demand)
[0m[31m2018-04-13 16:24:37,349 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:461)
[0m[31m2018-04-13 16:24:37,408 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:196)
[0m
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 570.04 s <<< FAILURE! - in io.openshift.boosters.GreetingServiceTest
[ERROR] io.openshift.boosters.GreetingServiceTest  Time elapsed: 570.039 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start

```

**Comment by ppitonak** [comment] 2018-04-16 13:51
Probably related to #2152

**Comment by gastaldi** [comment] 2018-04-23 11:58
@animuk this is not a bug in Launcher, but in the booster. Please assign this issue to the WF Swarm team

**Comment by gastaldi** [comment] 2018-04-24 16:36
This is tracked in https://issues.jboss.org/browse/SWARM-1701. 

@animuk Please check with the WF Swarm team (@kenfinnigan) to decide how/if this booster should be supported in OSIO

**Comment by animuk** [comment] 2018-04-26 05:33
hi @kenfinnigan , Please comment on the availability and supportibility of this booster in OSIO because this is in priority. I know, you already said that the this won't be fixed in WF Swarm product until 7.1.0 is released, which is likely some time in May. So, Should we park it for now ?

**Comment by kenfinnigan** [comment] 2018-04-26 12:19
@animuk, I'm not sure what you want to hear regarding availability and supportability. Until 7.1.0 is released, at the end of May, there's nothing that can be done

**Comment by qodfathr** [comment] 2018-04-26 14:35
@slemeur looks like we need to remove this booster from osio for now.

**Comment by ldimaggi** [comment] 2018-04-26 14:45
If this booster cannot be built - we have to remove it from OSIO.

**Comment by slemeur** [comment] 2018-04-30 16:28
+1 Let's remove it for now.

cc: @GeorgeActon + @animuk + @gastaldi

**Comment by nimishamukherjee** [comment] 2018-07-31 10:11
Closing this as Wildfly has been removed from the UI.
Work in progress for Wildfly - https://github.com/openshiftio/openshift.io/issues/3977

**Closed by nimishamukherjee** 2018-07-31 10:11 UTC
Labels: SEV2-high, area/launcher, area/quickstarts, team/launcher, type/bug

**Comment by ibuziuk** [comment] 2018-07-31 14:39
@nimishamukherjee am I correct that health-check  has been removed only today from osio ?
our build seems to start failing because of it and we probably need to also remove it on che-dockerfiles side [2] ?

[1] https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/335/consoleFull
[2] https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/dockerfiles/wildfly-swarm/Dockerfile#L64

**Comment by ibuziuk** [comment] 2018-07-31 15:37
ok, failures seem to be coupled with the runtime renaming to the `thorntail`

**Comment by bartoszmajsak** [comment] 2018-07-31 15:50
@ibuziuk does it mean we don't support Wildfly Swarm anymore as a name? I think there is no productized Thorntail yet. - Can we have both?

**Comment by ibuziuk** [comment] 2018-07-31 19:51
@bartoszmajsak I belive @nimishamukherjee @gastaldi or @kenfinnigan would be able to provide better input to this question. But as I can see on osio `thorntail` is already used in the app wizard:

![image](https://user-images.githubusercontent.com/1461122/43483285-7e451cb8-950b-11e8-8294-c83f4e132bac.png)

**Comment by kenfinnigan** [comment] 2018-07-31 19:54
There is currently no product for Thorntail.

There won't be one until later this year. In the interim there will be WF Swarm for product and Thorntail for community

**Comment by slemeur** [comment] 2018-07-31 21:42
Until now we were targeting only the productized versions of the runtimes. In this case, for now, we should keep WF Swarm versions into IO.

I'll start a conversation about enabling the community versions in OSIO separately.

Thanks.

**Comment by bartoszmajsak** [comment] 2018-08-01 06:40
> Until now we were targeting only the productized versions of the runtimes. In this case, for now, we should keep WF Swarm versions into IO.

@slemeur Not sure if that is the case for WF Swarm. We switched to the community, b/c productized versions were behind and were not working in our environment. And this is what we serve right now.

To give more context: this issue comes from the update of runtime name in global `metadata.yml`, where the catalog itself still has the product versions (Widlfly Swarm references) which we can use, but the global name is "Thorntail" and this results in problems like the one Che encountered.
