### ISSUE TITLE
Hiearchial parent/child navigation needs to work

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#256] opened 2017-06-19 05:12 UTC
Currently a work item list has two options: List vs hierarchal where the latter visualizes parent/child relationships between work items.

The hiearchy view has UI/UX glitches but is also not handling paging nor when the result has work items without "parents". These should be fixed.

**Comment by joshuawilson** [comment] 2017-06-19 19:58
This issue was moved to fabric8io/fabric8-planner#2013

**Comment by michaelkleinhenz** [comment] 2017-09-20 11:12
Dupe of #325. Will be in current sprint.

**Closed by michaelkleinhenz** 2017-09-20 11:12 UTC
Labels: area/planner, team/planner

**Comment by joshuawilson** [comment] 2017-09-21 03:09
Since #325 is the user-story, why not link to this as the task to cover that part of the user-story?
