### ISSUE TITLE
Rollout to Run in Jenkins is confusing

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#526] opened 2017-08-09 15:29 UTC
Once "Rollout to run" is done, it shows the link to the deployment

![bildschirmfoto 2017-08-09 um 17 26 18](https://user-images.githubusercontent.com/208246/29129682-e5085ade-7d27-11e7-8555-169afde54394.png)

Unfortunately it can sometimes take a loooong time until the app is really ready - even if the time says 0s or 1s.

It would be good, if some spinner could be shown that spins until the application is really live .

**Comment by rawlingsj** [comment] 2017-08-11 09:29
Agreed, it's been on the list for the pipeline to wait (for a time) until the readiness checks for the new version pass.

**Comment by aslakknutsen** [comment] 2017-08-12 00:58
Related https://github.com/openshiftio/openshift.io/issues/508

**Comment by qodfathr** [comment] 2018-01-17 18:31
Closing as dupe of #508, which now suggests a similar solution.

**Closed by qodfathr** 2018-01-17 18:31 UTC
Labels: area/UX, area/pipelines, team/build-cd, type/feature
