### ISSUE TITLE
Cannot import code in Firefox because patternfly blows up

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#1422] opened 2017-11-21 15:23 UTC
Importing code with the wizard fails on latest Firefox because of patternfly issues. Please see the screenshot for stack trace (I've no idea how I can copy paste it from the console).

![screenshot from 2017-11-21 14-52-52](https://user-images.githubusercontent.com/601714/33064519-f64ef6ea-cecb-11e7-82b1-cedfa2c42826.png)

**Comment by joshuawilson** [comment] 2017-11-21 19:06
What is your version of Firefox? Have you tried it on another browser?

**Comment by joshuawilson** [comment] 2017-11-21 19:16
We need to confirm the browser that was used and compare it against the supported list. https://github.com/openshiftio/openshift.io/wiki/Supported-Browsers

**Comment by jaseemabid** [comment] 2017-11-22 05:44
I'm using latest stable Firefox 58. `this.gui.inputs[3] === undefined` doesn't look like a browser incompat issue :/

**Comment by jaseemabid** [comment] 2017-11-22 06:38
This blows up on Chrome Version 62.0.3202.75 (Official Build) (64-bit) as well, but with a different issue. 

I'd like to say this bug prevents the user from using almost all of OSIO, hence should be considered critical.

![screenshot from 2017-11-22 12-06-06](https://user-images.githubusercontent.com/601714/33113283-9e7f3fa8-cf7d-11e7-9715-1e98c6ebd5e5.png)

**Comment by jaseemabid** [comment] 2017-11-22 06:40
PS: Why am I seeing stack traces pointing to CSS files? o_O

**Comment by joshuawilson** [comment] 2017-11-22 07:10
I just ran the import of code in Chrome in production and it worked with no errors.
Are you importing a known working repo? (one that you had previously made in OSIO)

**Comment by jaseemabid** [comment] 2017-11-22 07:18
This is what I installed with gofabric8. The deployed version seems to be `fabric8/fabric8-ui:v318d700`

**Comment by joshuawilson** [comment] 2017-11-22 07:31
Ah, that explains it. It helps to know that you are not on prod when you report a bug.

**Comment by jaseemabid** [comment] 2017-11-22 07:33
I'll try to be more precise next time.

**Comment by joshuawilson** [comment] 2017-11-22 23:08
Thanks. You may want to file an issue again gofabric8 since the issue is there. They won't see an issue for it here.

**Comment by jaseemabid** [comment] 2017-11-23 08:45
@joshuawilson This is clearly an issue with the UI and I don't see why this should be filed on gofabric8.

**Comment by edewit** [comment] 2017-11-23 09:25
@jaseemabid css are only for styling and the references you see are wrong. The first stack trace you posted is clear, the error that you get is that the backend is not returning a json result that the front-end expects.

**Comment by corinnekrych** [comment] 2017-12-07 14:27
@jaseemabid do you deploy with local dev as per https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md#local-development ?

it looks like the error is coming from:
https://github.com/fabric8-ui/fabric8-ui/blob/f51cbe359a898bfe971064c5f9ae1ee6b10ea113/src/app/space/forge-wizard/import-pages/step3/pipeline-step.component.ts#L22
BUT the latest version of forge backend should always returned an overrideJenkins input.
I suspect something in the minishift deployment is not set properly.

@jaseemabid one thing that worth trying is to replace https://github.com/fabric8io/fabric8-platform/blob/master/apps/forge/src/main/fabric8/deployment.yml#L11 next (which is the development branch for the quickstart) with v15 is it better?

**Comment by corinnekrych** [comment] 2017-12-08 10:17
I confirm that the issue is specific to [badger / fabric8-platform deployment]( https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md#local-development). Following[ local dev setup](https://github.com/fabric8-ui/fabric8-ui/wiki/How-to...#how-to-run-local-ui-with-local-forge) we got the proper output from Forge.

As a workaround we can check in the UI for undefined value to not blow the whole flow but we will miss the information about whether or not the jenkins file is overridden.

**Comment by corinnekrych** [comment] 2017-12-08 10:21
@gastaldi @edewit the root cause of the issue is in this [method](https://github.com/fabric8io/fabric8-generator/blob/21657e5020a92e6d68b9f14594eb047abedc1103/src/main/java/io/fabric8/forge/generator/pipeline/ChoosePipelineStep.java#L223-L229) where we check which flow we're in (import or quickstart) based on the presence of BoosterDTO class.

Any clue on what in the deployment config could make BoosterDTO loaded even on import flow?

**Comment by edewit** [comment] 2017-12-08 10:30
yes @corinnekrych I think it would be better if we had 2 commands instead of one with this check

**Comment by corinnekrych** [comment] 2017-12-08 17:21
The reason why prod-preview wizard ui fails is bc the Forge API response. 

* expected(PROD return): [k8s information](https://github.com/fabric8io/fabric8-test/blob/master/EE_API_automation/pyresttest/forge_wizard/import_wizard/step_3_1_output.json#L81-L110 (this is the API contract)

* actual(prod-preview): [prod-preview returns](https://gist.github.com/corinnekrych/0b8ab384115e3dc1a4f61f5b1f5dd82a#file-gistfile1-txt-L98)

In there this.inputs[3] is missing.

So I suspect this [code here](https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/pipeline/ChoosePipelineStep.java#L182-L188) is not set properly for some reason… 
@rawlingsj @edewit @gastaldi any idea?

**Comment by corinnekrych** [comment] 2017-12-11 09:37
I'm closing this issue.
Since tenant namespace reset was done on prod-preview, we don't get the issue any more

**Closed by corinnekrych** 2017-12-11 09:37 UTC
Labels: area/app-wizard, area/UI, SEV3-medium, team/analytics/wizard, team/launcher, type/bug
