### ISSUE TITLE
Description added in Forge Wizard doesn't add description on Analyze tab

### ISSUE THREAD

**Issue by Bob-Davis** [openshiftio/openshift.io#474] opened 2017-08-04 20:49 UTC
I added a description to the new space I created, and when I finished the wizard the description isn't there in the tab.
![screen shot 2017-08-04 at 3 48 52 pm](https://user-images.githubusercontent.com/19437701/28986409-7b5e57d6-792c-11e7-8c32-746dab9a2687.png)

**Comment by joshuawilson** [comment] 2017-08-04 20:52
Are you able to manually enter the description? 
Just confirming that the issue is in the wizard.

**Comment by Bob-Davis** [comment] 2017-08-04 21:07
Yes. 
![screen shot 2017-08-04 at 4 06 22 pm](https://user-images.githubusercontent.com/19437701/28986985-f6cff012-792e-11e7-9168-4fc2361739ac.png)

**Comment by Bob-Davis** [comment] 2017-08-04 21:08
When it didn't work the first time on Yavin, I tried to re-create it on Yavin1 & Yavin2. Same every time.

**Comment by Bob-Davis** [comment] 2017-08-04 21:35
Actually - it looks like it's the GitHub description - but it's confusing. Maybe the description here should be the same as the GitHub description? 
![screen shot 2017-08-04 at 4 32 51 pm](https://user-images.githubusercontent.com/19437701/28987872-d7bb99ac-7932-11e7-8945-7e5e7365c3d0.png)

![screen shot 2017-08-04 at 4 33 30 pm](https://user-images.githubusercontent.com/19437701/28987879-e18e5d7a-7932-11e7-9676-0f2590ca78ce.png)
![screen shot 2017-08-04 at 4 35 20 pm](https://user-images.githubusercontent.com/19437701/28987889-f1cfea82-7932-11e7-9960-bc5777d1264d.png)

**Comment by joshuawilson** [comment] 2017-08-05 00:56
The wizard is under a major design redo. Since this appears to work I'm closing this.

**Closed by joshuawilson** 2017-08-05 00:56 UTC
Labels: area/app-wizard, area/spaces, kind/bug, level/beginner, status/open-for-dev, team/platform
