### ISSUE TITLE
Planner: Add work items widget uses API that doesn't exist anymore

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3383] opened 2018-04-30 20:34 UTC
The planner `work-items.service.ts` provides function `getWorkItemTypes`. It makes a request to get workitemtypes, building the URL:

`this.workItemTypeUrl = this._currentSpace.links.self + '/workitemtypes';`

In production, requests to this endpoint are 404 Not Found for me. This affects the add work items widget in fabric8-ui. It displays a blank page.

Comments in this PR [1] suggest the URL should be built from the 'relationships' part of the space response.

![workitemtypes](https://user-images.githubusercontent.com/5430520/39448804-069dfb5e-4c94-11e8-87b2-a3908c418758.png)

[1] https://github.com/fabric8-services/fabric8-wit/pull/2073

Edit: Specifically, this service is used in `fabric8-ui:create-work-item-overlay.component.ts` via:

```
this.workItemTypes = this.workItemService.getWorkItemTypes();
```

Edit2:

It looks like there is another API that has been changed:

`https://api.openshift.io/api/namedspaces/<username>/prod-5/workitems/new?type=26787039-b68f-4e28-8814-c2f93be1ef4e`

Returns:
400 Bad Request: `{"errors":[{"code":"invalid_request","detail":"invalid value \"new\" for parameter \"wiNumber\", must be a integer","id":"YxQM4g7F","status":"400","title":"Bad Request"}]}`

This will need to be addressed as well to make the widget work.

[2] fabric8-ui/fabric8-ui#2843

**Comment by joshuawilson** [comment] 2018-04-30 21:02
@jiekang is this needed or blocking for an issue?

**Comment by jiekang** [comment] 2018-04-30 21:10
@joshuawilson
Users can't add work items via the widget in production; the feature is unusable. The PR https://github.com/fabric8-ui/fabric8-ui/pull/2794 addressing the P0 https://github.com/openshiftio/openshift.io/issues/3021 is for this same feature. I think if the above PR/Issue is a P0, this one is also definitely P0.

**Comment by jiekang** [comment] 2018-04-30 21:12
And conversely, if this isn't a P0, then #3021 should not be a P0 either.

Short description:
This bug makes the widget blank and unusable. The above bug makes the widget redirect to 404 and unusable.

**Comment by jiekang** [comment] 2018-04-30 21:15
Looking at Alex's work, he noted https://github.com/fabric8-ui/fabric8-planner/pull/2574/files which touches the area, but doesn't specifically touch the part used by this widget.

**Comment by jiekang** [comment] 2018-05-01 18:47
It looks like there is another API that is also incorrect. After a workaround on the ui-side [1], there is a 404 Not Found for example:

`https://api.openshift.io/api/namedspaces/<username>/prod-5/workitems/new?type=26787039-b68f-4e28-8814-c2f93be1ef4e`

This will need to be addressed as well to make the widget work.


[1] https://github.com/fabric8-ui/fabric8-ui/pull/2843

**Comment by sanbornsen** [comment] 2018-05-02 05:59
I have fixed the issue with work item type service, but the problem is we don't support non-contextual detail add from the planner, thus the next step in this flow is broken.

**Comment by nimishamukherjee** [comment] 2018-05-02 07:13
@qodfathr @joshuawilson @jiekang can we remove the Add work item work flow from the dash board.
We have removed **Detailed Work Item Creation** component and this workflow would not work.
Have a look at #2840

**Comment by jiekang** [comment] 2018-05-02 13:00
@joshuawilson It looks like the suggested action is to remove the add work item flow from the UI. That's relatively simple to do; I or Dan could take a look. Is that acceptable?

**Comment by michaelkleinhenz** [comment] 2018-05-02 13:38
We should remove it. This flow will not work anymore. And it also does not makes sense from a systematic perspective: even if it would work, it would promote creating top-level WIs, which is not desirable in most cases. New WIs certainly are childs and should be properly created using the contextual add.

We can get to a feature like that later when implementing the generic "issue" WIT.

**Comment by jiekang** [comment] 2018-05-02 13:52
Okay. I can look at providing a PR to remove the functionality completely.

**Comment by kwk** [comment] 2018-05-03 07:58
I'm for removing as well.

**Comment by jiekang** [comment] 2018-05-04 12:32
Fix has been merged upstream. I will track this and close it when it reaches Production.

**Comment by joshuawilson** [comment] 2018-05-04 16:44
Closing as this has been fixed and we don't want to work this way anymore.

**Closed by joshuawilson** 2018-05-04 16:44 UTC
Labels: SEV2-high, priority/P0, team/platform, type/bug
