### ISSUE TITLE
"Create new work item" page is opening scrolled down when in small viewport

### ISSUE THREAD

**Issue by camilamacedo86** [openshiftio/openshift.io#1830] opened 2018-01-10 12:32 UTC
# Problem Description
**WHAT:** Create new work item" page is opening with the scroll to end of the page which doesn't allow the user see the options
**WHERE:** `https://openshift.io/<user>/<space>/(action:add-work-item)` with the Chrome Version 63.0.3239.132 (Official Build) (64-bit) | https://openshift.io
**WHEN:** Click on the  "Create new work item" button
**BEHAVIOUR CHECKED AT:** 10/jan/2018

# Steps to reproduce:
1. Openshift.io home >> click on the drop-down in the left top >> Select a space 
2. Click on the  "Create new work item" button

# Result:

<img width="1287" alt="screen shot 2018-01-10 at 12 37 27 pm" src="https://user-images.githubusercontent.com/7708031/34773124-74488c7a-f602-11e7-8af2-f86b5aabd3c1.png">

# Expected Behaviour:

<img width="1279" alt="screen shot 2018-01-10 at 12 35 57 pm" src="https://user-images.githubusercontent.com/7708031/34773059-3eaafad0-f602-11e7-902d-ce37ed7cc4fb.png">

# Workaround: 

Identify that the page is scrolled to down and scroll it to up.

**Comment by michaelkleinhenz** [comment] 2018-01-10 14:38
I can't reproduce that on either prod or prod-preview. Can someone else check? @nimishamukherjee

**Comment by camilamacedo86** [comment] 2018-01-10 14:59
@michaelkleinhenz I am adding the Chrome version.

**Comment by joshuawilson** [comment] 2018-01-10 19:31
@camilamacedo86 how were you accessing the Planner? Do you have a link?

**Comment by camilamacedo86** [comment] 2018-01-10 19:39
@joshuawilson I didn't. I create a new space, go to the home of it, and click on in this button.

**Comment by joshuawilson** [comment] 2018-01-10 19:41
Were you in prod, prod-preview, a PR link?

**Comment by joshuawilson** [comment] 2018-01-10 19:43
https://openshift.io
https://prod-preview.openshift.io/
https://fabric8-ui-fabric8-ui-pr-2398-fabric8-planner.badger.fabric8.io/

**Comment by joshuawilson** [comment] 2018-01-10 19:45
Are you still able to reproduce it? I am not able to.

**Comment by camilamacedo86** [comment] 2018-01-10 19:48
@joshuawilson IN : https://openshift.io

**Comment by joshuawilson** [comment] 2018-01-10 20:04
@michaelkleinhenz I can reproduce this now. It is a styles issue. If you have the viewport small but not mobile sized it introduces a scroll bar and scrolls you down.

cc @mindreeper2420 @SMahil

**Comment by SMahil** [comment] 2018-01-11 06:45
@joshuawilson I am not able to reproduce it on openshift.io and prod-preview.openshift.io

**Comment by michaelkleinhenz** [comment] 2018-01-11 10:49
@joshuawilson @SMahil Ok, I can reproduce it now. @SMahil you need to get the viewport just below the firt breakpoint (when the boxes on the space home are breaking into vertical boxes, but the menu still stays  non-hamburger). If you then click on "Create Work Item", you get to the type selection and the scrollbar is not at the top.

In my case, the scrollbar hangs halfway down, so I can still see ~50% of the selection boxes. Example chrome window geometry when this happens: 883x1018.

**Comment by michaelkleinhenz** [comment] 2018-01-11 10:51
Good find by the way @camilamacedo86

**Comment by camilamacedo86** [comment] 2018-01-11 14:40
@michaelkleinhenz it is something really silly, just a CSS, just to render it on top. I am glad that I could help.

**Comment by nimishamukherjee** [comment] 2018-02-28 16:54
Closing this as we do not have detailed work item creation.

**Closed by nimishamukherjee** 2018-02-28 16:54 UTC
Labels: SEV3-medium, area/UI, area/planner, team/planner, type/bug

**Comment by camilamacedo86** [comment] 2018-02-28 18:43
@nimishamukherjee did you solve the issue or you could not reproduce it?

**Comment by joshuawilson** [comment] 2018-02-28 19:33
@camilamacedo86 the page has been removed, therefore there is nothing to fix.

**Comment by camilamacedo86** [comment] 2018-03-01 08:38
tks for the explanation :-)
