### ISSUE TITLE
Forge wizard is broken (no quickstarts available)

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#831] opened 2017-09-18 08:57 UTC
How to reproudce? 
Select "Create a new Quickstart project" when creating new space (or clicking "Add to space", when space is already created), click "Next". Now you should be able to select quickstart, but the combo box is empty and user is not able to proceed further.
Reproducible allways? Yes.

![image](https://user-images.githubusercontent.com/1215011/30534744-d3054d90-9c5f-11e7-872b-be4599361e63.png)

**Comment by rhopp** [comment] 2017-09-18 08:59
I've tried it with clean (reset) environment and @ljelinkova with fresh account (first time user)

**Comment by jstrachan** [comment] 2017-09-18 09:08
this was a regression caused by changes in the underlying RHOAR launchpad-addon. Now resolved in production

**Closed by jstrachan** 2017-09-18 09:08 UTC
