### ISSUE TITLE
Viewing the new analytic report can be disorienting 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#817] opened 2017-09-13 18:09 UTC
Viewing the new analytic report can be disorienting as the information in columns and rows "pops up" - see screencast:

https://www.dropbox.com/s/72f3x6wa3s54m7s/report_display.webm?dl=0

Can we add a mode where the information must be explicitly expanded or compressed?

**Comment by joshuawilson** [comment] 2017-09-13 18:18
This is very hard to look at.

**Comment by muruGanesan** [comment] 2017-09-14 14:35
I will look at this issue and fix

**Comment by samuzzal-choudhury** [comment] 2017-11-06 06:10
@ldimaggi  The UX revamp for stack report is in progress and current wireframe can be found here -  https://redhat.invisionapp.com/share/P5E5BDKQ3. We already have an in-progress work item for sprint 140 https://github.com/openshiftio/openshift.io/issues/1277 to work on this new UX and would like to track the progress with that.

Closing this issue as this is a duplicate of https://github.com/openshiftio/openshift.io/issues/1277.

**Closed by samuzzal-choudhury** 2017-11-06 06:10 UTC
Labels: area/analytics, area/UX, kind/bug, severity/P1, stream/analytics, team/analytics, team/ux
