### ISSUE TITLE
Analytics fails to find manifest files while using the osio pipeline library for building Java projects

### ISSUE THREAD

**Issue by fabric8cd** [openshiftio/openshift.io#4535] opened 2018-11-12 10:18 UTC
I am working on https://github.com/openshiftio/openshift.io/issues/4319 - which is Java support with the new [osio pipeline](https://github.com/fabric8io/osio-pipeline) library for existing boosters.
I came across this bug while testing one of the Java boosters.
Below are the logs : 
```
invoking bayesian analytics
[Pipeline] retry
[Pipeline] {
[Pipeline] bayesianAnalysis
No supported manifest files found, skipping.
[Pipeline] echo
Bayesian analysis failed com.redhat.jenkins.plugins.bayesian.BayesianStepResponse@1581084
``` 
Here is the complete build log - https://paste.fedoraproject.org/paste/dan8~RXaqQ3DrkXilQDboA

Steps to reproduce:
1. Please fork this repository https://github.com/rupalibehera/resthttpthorntaildeleit , because it has the changes required by the new pipeline, the PR is in progress hence not in production yet.
2. Go to OSIO -> create space-> create application -> import existing application ->  forked in step 1. resthttpthorntaildeleit.
3. You will have to update the Jenkinsfile to use the new pipeline library because in current scenario it will override the existing one. 
Below is the Jenkinsfile to be used
```
@Library('github.com/fabric8io/osio-pipeline@master') _

osio {

  config runtime: 'java', version: '1.8.1'

  ci {


    def resources = processTemplate(params: [
          release_version: "1.0.${env.BUILD_NUMBER}"
    ])

    build resources: resources

  }

  cd {
    echo "Running CD build.........."

    def resources = processTemplate(params: [
          release_version: "1.0.${env.BUILD_NUMBER}"
    ])

    build resources: resources
    deploy resources: resources, env: 'stage'
    deploy resources: resources, env: 'run', approval: 'manual'

  }
}
```

Please let me know if you have any questions or queries.
cc: @rupalibehera

**Comment by yzainee** [comment] 2018-11-20 06:15
@rupalibehera As we havnt added our support for the new pipeline for maven, it will not trigger the analytics as its not able to find the manifest files. As discusses in sprint demo and [https://chat.openshift.io/developers/pl/u34eh8o3wfyomksp77kjt4k3se] we will providing support for maven only in L train.
If its blocking your work, you can go ahead and merge this new pipeline, but the analytics wont be called. 
FYI @gorkem

**Comment by sivaavkd** [comment] 2018-12-06 13:20
Planner link: https://openshift.io/openshiftio/Openshift_io/plan/detail/1168

**Comment by yzainee** [comment] 2018-12-14 04:44
@chmouel AS mentioned earlier as well, i dont understand why is analytics stack report blocking any of this? You can go ahead and merge the changes for the new pipeline. The analytics part wont work but it wont affect the build pipeline. When we add the analytics support for maven, you will start seeing the stack report. I dont know how can this be blocking?

cc @sivaavkd

**Comment by sivaavkd** [comment] 2018-12-14 05:36
This has been discussed few times already - in MM, in sprint demos, SoS report email etc and this was not a blocker earlier. We have it as a user story/feature request in our sprint 159 plan and we are working on it.  It will take till end of the sprint to complete it.

@yzainee @GeetikaBatra  - I read the comments in #4547 and looks like the issue found in that can be fixed only by moving to new pipeline for Maven.  If they migrate to new pipeline, will it not be a Sev1/P1 regression for Analytics because stack report doesn't show up ?

cc @krishnapaparaju @gorkem

**Comment by gorkem** [comment] 2018-12-17 01:33
@sivaavkd @yzainee This is not a blocker for thorntail migration but this will quickly become a blocker when we decide to move rest of the boosters to the new pipeline library so treat it as such.

**Comment by yzainee** [comment] 2019-01-11 10:34
https://openshift.io/openshiftio/Openshift_io/plan/detail/1168
The changes from the analytics side are done and tested. 
Note: You need to change the generated jenkins file in order to invoke the new build pipeline

**Comment by yzainee** [comment] 2019-01-11 10:35
cc: @sivaavkd

**Closed by yzainee** 2019-01-11 10:35 UTC
Labels: SEV2-high, area/analytics, priority/P1, team/analytics, type/bug
