### ISSUE TITLE
Deployments page/applications widget doesn't work

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4634] opened 2018-12-11 10:42 UTC
##### Issue Overview

Account set to beta features: deployments page and applications widget in space dashboard don't work
Account set to released features: applications widget in space dashboard doesn't work

##### Expected Behaviour

it shows deployed applications

##### Current Behaviour

applications widget:
![osio_apps](https://user-images.githubusercontent.com/445100/49795017-3f31ed80-fd39-11e8-92ee-84c8029cdacc.png)

deployments page:
![osio_deployments](https://user-images.githubusercontent.com/445100/49795018-3f31ed80-fd39-11e8-96dd-9c4c59a5d6a3.png)

##### Steps To Reproduce

1. create a space and new app with longest pipeline
2. wait for pipeline to finish
3. go back to space dashboard

##### Additional Information

* Works fine with *experimental* feature level
* broken only in prod-preview
* HTTP response on deployments page contains `{"errors":[{"code":"unknown_error","detail":"failed to GET /api/user/services due to status code 401","status":"500","title":"Unknown error"}]}
`

**Comment by ppitonak** [comment] 2018-12-11 11:57
possibly duplicate of #4631

**Comment by sbose78** [comment] 2018-12-11 12:45
Why is this a sev1, which flow does this block ?

**Comment by joshuawilson** [comment] 2018-12-11 13:36
I would agree, this shouldn't be a SEV1. Even if this were in prod it does not block normal usage of the system. Deployments is in Beta. 

Also, I have confirmed that the latest UI runs fine against the prod server. So this is not caused by a change in the UI.

**Comment by ppitonak** [comment] 2018-12-11 13:45
Applications widget is in Released.

We don't know the root cause yet so it's should be our top priority to find out.

**Comment by joshuawilson** [comment] 2018-12-12 06:42
Since rolling back, the e2e tests pass. We have plan to deal with the issue. Is this a SEV1? Aside from tracking the removal of the Deployments page, should this even remain open?

**Comment by ppitonak** [comment] 2018-12-12 09:08
Closing this issue, the remaining work will be tracked in linked issues.

**Comment by ppitonak** [comment] 2018-12-17 15:09
Broken again in prod-preview.

**Comment by sbose78** [comment] 2018-12-17 15:19
Should be fine again.

**Comment by ibuziuk** [comment] 2018-12-17 15:55
@sbose78 would be great to understand what was done to fix it ;-) 
e2e tests have been failing for dozens of times

**Comment by sbose78** [comment] 2018-12-17 16:07
> would be great to understand what was done to fix it ;-)

@ibuziuk , WIT is on a deployment freeze till we drop a couple of features from the UI . One of the folks had updated it on prod-preview - I've reinforced the freeze by reverting it.

**Comment by joshuawilson** [comment] 2018-12-17 17:22
The Deployments widget and page is displaying in prod-preview. I'm closing this.

**Closed by joshuawilson** 2018-12-17 17:22 UTC
Labels: SEV1-urgent, area/dashboard, area/deployments, area/e2e-tests, area/spaces, priority/P1, team/ui, team/workitem-tracker, type/bug

**Comment by jarifibrahim** [comment] 2018-12-18 10:11
We will be investigating the failure which caused this SEV-1. This SEV-1 is expected to show up again while we are investigatin the failure. Please see https://github.com/openshiftio/openshift.io/issues/4631#issuecomment-448164687.
