### ISSUE TITLE
Investigate what is required to help fabric8-ui CI pipeline to get faster and better

### ISSUE THREAD

**Issue by rupalibehera** [openshiftio/openshift.io#1933] opened 2018-01-19 09:46 UTC
- The development time increases due to long running PR and not getting successful in multiple builds due to slave related issues or a genuine failure in the code or some other failure.

- It would be nice if we get the pipelines a bit faster so the feedback cycle is quick.

- CD team will need help from fabric8-ui team on this as none of us know or understand much of it.

- https://github.com/fabric8-ui/fabric8-ui/

- https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/

**Comment by ldimaggi** [comment] 2018-01-19 13:58
See related issues:
https://github.com/openshiftio/openshift.io/issues/1926
https://github.com/openshiftio/openshift.io/issues/1904

**Comment by michaelkleinhenz** [comment] 2018-01-24 14:16
Experiencing random failures on Planner UI builds as well. The failures come up in different stages.

Examples would be even before npm kicks in, while npm is running with either timeouts on resolving dependencies, getting timeouts on the functional tests (while interacting with the Chrome instance) or failures with no visible reason (the log just stops with no visible error or exit or even empty logs for the step).

**Comment by michaelkleinhenz** [comment] 2018-01-24 14:16
This looks familiar: https://github.com/npm/npm/issues/9884

**Comment by michaelkleinhenz** [comment] 2018-01-29 17:35
Example PR build fails:
https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-planner/detail/PR-2419/3/pipeline

**Comment by chmouel** [comment] 2018-01-30 09:22
If we have random failure, I think we need some kind of profiling : 

* How can we get those infos from  GKE
* How can we get that info from the application (i.e: profiling memory usage and cpu on intepreter)

**Comment by jarifibrahim** [comment] 2018-01-31 10:46
Npm install failed without any errors - https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2417/11/console

**Comment by michaelkleinhenz** [comment] 2018-02-02 09:17
This is now serious for us. We're blocked because builds are more failing than working. We need this infra to work reliably. A whole team wastes lot's of time hitting that rebuild button. **We need to solve this.**

**Comment by maxandersen** [comment] 2018-02-02 09:43
I'm upgrading this to sev1 as it does not really matter where the issue is rooted - several teams are affected by "random failures". 

If these issues are really caused by exhausted resources on the build server then lets get the resources increased to see if it gets better - that must be cheaper than getting stuck at this.

If it requires more investigation then lets please get it listed here and get it worked through.

**Comment by sbose78** [comment] 2018-02-02 10:54
@chmouel , I'm guessing it gets billed to the account automatically. 
Inform the planner team, so that they can quickly try things out after you make the change? @pranavgore09 @michaelkleinhenz  ?

**Comment by jarifibrahim** [comment] 2018-02-02 10:58
For purely experimentation purpose, I ran the first 3 stages (which includes building and testing) of `fabric8-planner` build on Travis-CI [[0]](https://travis-ci.org/jarifibrahim/fabric8-planner).
Here's what I found out -
1. The average running time (for the first 3 stages) is about **5 minutes on Travis-CI** and about **18 minutes on jenkins.cd.test.fabric8.io**
![download](https://user-images.githubusercontent.com/12949454/35729672-803ce5b8-0835-11e8-82a7-e153ef51fb9a.png) 
Picture 1 - Average Build time on jenkins.cd.test.fabric8.io
![download 1](https://user-images.githubusercontent.com/12949454/35729681-86796e24-0835-11e8-8e15-340c2479d96e.png) Picture 2 - Build time of planner on Tavis-CI
2. I ran 10 builds on Travis-CI and **none** of them failed. On the other hand, I have not yet been able to get 5 consecutive successful builds on jenkins.cd.test.fabric8.io

[0] - https://travis-ci.org/jarifibrahim/fabric8-planner (check only the travis-test branch. The other branch failed since it didn't have a .travis.yml.file)

**Comment by bartoszmajsak** [comment] 2018-02-02 11:18
Is this really a whole build of `fabric8-planner` and you [literally have 7 specs](https://travis-ci.org/jarifibrahim/fabric8-planner/jobs/335747004#L859)? Something is really odd here... also from the perspective of the tim needed to execute it (even on travis).

**Comment by rupalibehera** [comment] 2018-02-02 11:42
@chmouel , I am not sure if we can resize this same instance or we don't have enough privileges for that, should we ask @pbergene @jfchevrette they both have more access than us ?

**Comment by sthaha** [comment] 2018-02-02 11:51
@chmouel I am curious what we are resizing here - the jenkins master or the slave? isn't the job run in the slave? Can we get an measurement of the cpu and the memory utilisation of the slave when the job is run?

**Comment by rupalibehera** [comment] 2018-02-02 11:56
this is resizing of the complete cluster where other services also run `configmapcontroller, content-repository, elasticsearch, exposecontroller, fabric8-docker-registry, hubot-mattermost, jenkins, jenkins-slave-*, kibana, mattermost-db, mattermost, nexus`

**Comment by jarifibrahim** [comment] 2018-02-02 12:58
@bartoszmajsak 

> Is this really a whole build of fabric8-planner and you literally have 7 specs? Something is really odd here... also from the perspective of the time needed to execute it (even on travis).

Yes, these are the UI smoke tests. Since these tests perform actions such as clicking on a button it takes some time.

**Comment by chmouel** [comment] 2018-02-02 13:49
So after spending some times on it : 

* There is no memory limit on the containers it's literally be my guest mister container and use whatever you have memory available on the cluster,

* we have a total memory of 15GB on the cluster currently (as seen on the screenshot i sent earlier)

* We have peaks going on up to 15GB sometime on Job which I guess is one of your UI tests, consuming hips of memory : 

![image](https://user-images.githubusercontent.com/98980/35736234-9a8811f8-0827-11e8-84bb-0ada28d29722.png)

increasing the memory available on  the  cluster may help but if your job is taking a crazy amount of memory like insane (which we will track) then we will just add a limit on the containers run.

* In the meantime we need from you a memory trace and graph from the npm process before running the tests and make a comparaison of how much memory your jobs are consuming under travis, jenkins.cd and your machine).  We are running blind without it and we won't take care of that for you guys,

We will do the memory increase of the cluster later this afternoon (EU time)

Thanks,

**Comment by chmouel** [comment] 2018-02-02 14:07
I have just increased the memory/cpu available, let me know  if that make things better, we will montior the graphs as well : 

![image](https://user-images.githubusercontent.com/98980/35737097-a4a7a4c0-082a-11e8-93c1-4f5543afa816.png)

**Comment by mmclanerh** [comment] 2018-02-05 21:41
Following up on open SEV1 items.
- Is this still a SEV1?
- Has there been an improvement..? Should this move to SEV2? 

Thanks!

**Comment by rupalibehera** [comment] 2018-02-06 10:45
@mmclanerh , I guess we can remove the SEV1 label , after upgrade there is a lot of improvement in the success rate of the PR Jobs, we can make this SEV2 and keep it open for some monitoring from build team side.

cc @maxandersen @michaelkleinhenz

**Comment by rupalibehera** [comment] 2018-02-06 11:00
From some monitoring yesterday via GKE console I could see that UI pods were in error state below is the screenshot, due to high resource usage is my guess.
![ui-pod-slave](https://user-images.githubusercontent.com/4288561/35856100-36f823e2-0b35-11e8-9ed6-7084763e431f.jpg)

**Comment by pranavgore09** [comment] 2018-02-06 11:33
yes, can see improvements in builds at https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2426/   Rate of success for this build was much higher after the upgrade. few failures after build#36 are because of code change by me and were expected. 
But build passes through, sometimes I see that slaves are not available for ~15-20m.... but later it gets a chance to run and build continues. I could see one random failure for #40 https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2426/40/  but later worked well

**Comment by jarifibrahim** [comment] 2018-02-06 12:08
Planner builds are more stable now. The time taken to run the tests has reduced from  `~6 minutes` to `~3 minutes`

**Comment by rupalibehera** [comment] 2018-02-06 16:09
I was monitoring the Jenkins instance, I tried to reproduce the behavior which leads the slaves in error state. I triggered 5 different [fabric8-planner ui ](https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/view/change-requests/) PR builds simultaneously. 
My Observations below:
- The first and second PR CI build took much of the resources 
- The other 3 PR build could hardly acquire any resources
- After triggering all the builds simultaneously the build went really really slow it took more time from what it would taken in general.
- The first PR build pod was killed OOM error and later on all build pods went in to error state.
- Some pods were cleaned automatically and some did not I manually removed them from the cluster, which leads to fill up the container cap and we get such message in the logs `Total container cap of 5 reached, not provisioning: 5 running or errored in namespace c` even if only 3 builds pods are running as two pods are in error state.

From the above observation I can conclude that : 
- UI PR's are resource intensive 
- I think reducing the container cap from 5 to 3 which means only 3 builds will execute simultaneously 
- Increasing some more resources from 22 GB to 30 GB if that is possible ;)
- The slaves acquire resources dynamically

Below are some screen shots of above observations:
- First build https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2432/1/consoleFull and resource usage 
![first-ui-slave-resource-usage-latest](https://user-images.githubusercontent.com/4288561/35869551-9fb871a0-0b5f-11e8-866c-bbc66de18e40.png)
- When the first UI slave was in OOM state 
![first-ui-slave-oom-error](https://user-images.githubusercontent.com/4288561/35869596-be86aa48-0b5f-11e8-814a-282f8e158553.png)
- When all slaves went it to error state 
![all_failed_after_that](https://user-images.githubusercontent.com/4288561/35869729-184ced1c-0b60-11e8-8389-aef9aa4a836a.png)
- Second PR build which was provisioned 
![resource_usage_of_second_slave](https://user-images.githubusercontent.com/4288561/35869765-2f58901a-0b60-11e8-9514-ad82d7a51250.png)
- resource usage of remaining slaves 
![resource-usage-of-other-slaves](https://user-images.githubusercontent.com/4288561/35869786-46327bd4-0b60-11e8-89af-ba9f9da58b6d.png)
![resouce_usage_of_other_third_slave](https://user-images.githubusercontent.com/4288561/35869882-83058f38-0b60-11e8-9d62-ed164747ee0d.png)

cc: @pradeepto @chmouel @pranavgore09

**Comment by pradeepto** [comment] 2018-02-06 19:20
Thanks @rupalibehera for the detailed report. 

cc @jfchevrette @maxandersen

**Comment by joshuawilson** [comment] 2018-02-07 03:06
Thanks @rupalibehera that confirms what I have long suspected.

**Comment by pranavgore09** [comment] 2018-02-07 08:33
thanks @rupalibehera for finding this

**Comment by debloper** [comment] 2018-02-07 09:42
@rupalibehera nice and detailed observation. I'd like to amend some of the points you mentioned, to:

- UI PR's are VERY resource intensive (partially because of lack of optimizations)
- I think reducing the container cap from 5 to 1 which means only 1 build will execute at a time
- Increasing some more resources from 22 GB to 30 (3x10) GB if that is possible
- The slaves acquire resources dynamically, so split subtasks among them for each build to get faster

A host running 12 other critical services while also doing this isn't ideal at all. The spec mentioned is quite similar to our work laptop, but I'm not running 12 other live services on it, and I can't imagine how my system will handle it if I did so. Some sort of encapsulation/separation of concern has to be here, to not put all the eggs in one basket.

**Comment by joshuawilson** [comment] 2018-02-07 13:47
@dgutride and I are actively working on cleaning up and optimizing the UI build. Once we have that worked out in fabric8-UI we will provide those changes/fixes to the other UI repos.

**Comment by pbergene** [comment] 2018-02-07 14:29
Downgraded severity after no objections on triage.

**Comment by michaelkleinhenz** [comment] 2018-02-19 13:05
New behaviour: I have crashed builds when moving around files:

https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-planner/detail/PR-2419/32/pipeline

```
npm ERR! path /home/jenkins/workspace/-ui_fabric8-planner_PR-2419-J5GLLZH4I7563GRZMERRKYWFHX4MIY25QPQMODLQRAHYHVB5LMQA@2/dist/node_modules/angular-tree-component/node_modules/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/jenkins/workspace/-ui_fabric8-planner_PR-2419-J5GLLZH4I7563GRZMERRKYWFHX4MIY25QPQMODLQRAHYHVB5LMQA@2/dist/node_modules/angular-tree-component/node_modules/lodash' -> '/home/jenkins/workspace/-ui_fabric8-planner_PR-2419-J5GLLZH4I7563GRZMERRKYWFHX4MIY25QPQMODLQRAHYHVB5LMQA@2/dist/node_modules/angular-tree-component/node_modules/.lodash.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2018-02-19T12_43_00_159Z-debug.log
script returned exit code 254
```

I can't reproduce this on local.

**Comment by jarifibrahim** [comment] 2018-02-19 13:30
@michaelkleinhenz This is a known issue with `npm` https://github.com/npm/npm/issues/17444

**Comment by michaelkleinhenz** [comment] 2018-02-19 13:50
@jarifibrahim that thread says removing package-lock.json solves the issue. I just don't say anymore about all of this. It is just so sad.

**Comment by jarifibrahim** [comment] 2018-02-19 13:54
@michaelkleinhenz We should try Yarn https://yarnpkg.com/en/ for once.

**Comment by michaelkleinhenz** [comment] 2018-02-19 14:35
Update: the above issue has been fixed by removing an re-generating the lock files.

**Comment by michaelkleinhenz** [comment] 2018-02-22 09:13
New problem I encounter right now: 
```
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! unexpected end of file
```
..while installing deps.

See https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2419/39/console

**Comment by maxandersen** [comment] 2018-03-13 07:58
just to check - this error *only* occurs on GKE jenkins, correct ? 

its not happening when running locally nor when running builds in cico ?

**Comment by maxandersen** [comment] 2018-03-13 09:54
is this a duplicate of https://github.com/openshiftio/openshift.io/issues/2235 - can one be closed over the other ?

**Comment by sthaha** [comment] 2018-06-19 04:18
Since this issue seems to not occur anymore, I am going to close it . Please reopen it if that isn't the case.

**Closed by sthaha** 2018-06-19 04:18 UTC
Labels: SEV2-high, area/UI, area/jenkins, team/build-cd, team/platform, train/heather, type/task
