### ISSUE TITLE
Duplicated profile menu entry

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1562] opened 2017-12-08 14:26 UTC
When logged in, I see two drop-down menus in the top navigation. One on the left and one on the right. One seems to be linked to me project/workspace (left side) and one to me as user (right side).

![codebases](https://user-images.githubusercontent.com/296354/33769572-009833d4-dc2b-11e7-80de-286c1b0fcbec.png)

On the right-hand menu, I can select "Profile" which brings me to my profile page. I get that.

At the same time, there is a menu item on the left drop-down "hardyferentschik" which also seems to open the profile page. This is confusing. 

![profile](https://user-images.githubusercontent.com/296354/33769765-aa4f0588-dc2b-11e7-893b-1432edc02281.png)

It also makes the left drop-down contextual, changing what it contains.

On that note, I would expect "Account home" to be in the right menu toghether with profile, about, chat, ...

The left menu should just be about workspaces.

**Comment by joshuawilson** [comment] 2017-12-24 03:48
The navigation is going through a major redesign. 
cc @catrobson

**Comment by qodfathr** [comment] 2018-01-26 16:14
The left and right *are* different. The right is your profile, the left is showing recent places you have been, which can include your profile page (hence why it may look like a duplicate). In any event, the entire navigation is going to be updated.

Closing as By Design.

**Closed by qodfathr** 2018-01-26 16:14 UTC
Labels: area/UX, area/navigation, team/platform, team/ux, type/feature

**Comment by hferentschik** [comment] 2018-02-07 10:59
> The right is your profile, the left is showing recent places you have been, which can include your profile page

Why would my profile page appear in the list of recent places? If nothing else, this is extremely confusing and against expectations.

**Comment by joshuawilson** [comment] 2018-02-07 13:55
while I understand what it is doing, I would prefer to have @qodfathr and @catrobson respond

**Comment by qodfathr** [comment] 2018-02-12 16:26
@hferentschik recent places includes your visits to Spaces, Teams, and Accounts. (And possibly other places.) You are seeing it in both places because the one on the right is permanent (it's how you get to your profile) whereas the one of the left just means that you recently went to your profile. So, semantically, it's correct. I guess we could optimize that a visit to your own profile does not count as a 'recent place'.
