### ISSUE TITLE
Stop polling for stats after deleting a deployment

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2677] opened 2018-03-19 15:37 UTC
The deployments UI makes polling requests for stats for a deployment. If a deployment is deleted, these requests continue to occur and fail with 404 as the deployment no longer exists. There is no impact on user experience, but the requests should be stopped.

**Comment by joshuawilson** [comment] 2018-03-19 19:17
looks like it might be a duplicate of #2663

**Comment by andrewazores** [comment] 2018-03-19 19:19
You're right, it definitely is. I'll close this as a duplicate and assign myself on that one instead. Thanks.

**Closed by andrewazores** 2018-03-19 19:19 UTC
Labels: SEV4-low, area/deployments, team/platform, train/heather, type/bug
