### ISSUE TITLE
mvn build fails when following getting started guide

### ISSUE THREAD

**Issue by dkranz** [openshiftio/openshift.io#4139] opened 2018-08-07 18:27 UTC
I was following the guide. When I got to section 5.15 where you click the Run button in the new Che workspace I saw the following error:

scl enable rh-maven33 'mvn compile vertx:run -f -Dvertx.disableDnsResolver=true'https://routeyls1kykd-dkranz-che.9a6d.starter-us-east-1a.openshiftapps.com
Unable to parse command line options: Missing argument for option: f
 
usage: mvn [options] [<goal(s)>] [<phase(s)>]
 
Options:
 -am,--also-make                        If project list is specified, also
                                        build projects required by the
                                        list
 -amd,--also-make-dependents            If project list is specified, also
                                        build projects that depend on
                                        projects on the list
 -B,--batch-mode                        Run in non-interactive (batch)
                                        mode
 -b,--builder <arg>                     The id of the build strategy to
                                        use.
 -C,--strict-checksums                  Fail the build if checksums don't
                                        match
 -c,--lax-checksums                     Warn if checksums don't match
 -cpu,--check-plugin-updates            Ineffective, only kept for
                                        backward compatibility
 -D,--define <arg>                      Define a system property
 -e,--errors                            Produce execution error messages
 -emp,--encrypt-master-password <arg>   Encrypt master security password
 -ep,--encrypt-password <arg>           Encrypt server password
 -f,--file <arg>                        Force the use of an alternate POM
                                        file (or directory with pom.xml).
 -fae,--fail-at-end                     Only fail the build afterwards;
                                        allow all non-impacted builds to
                                        continue
 -ff,--fail-fast                        Stop at first failure in
                                        reactorized builds
 -fn,--fail-never                       NEVER fail the build, regardless
                                        of project result
 -gs,--global-settings <arg>            Alternate path for the global
                                        settings file
 -gt,--global-toolchains <arg>          Alternate path for the global
                                        toolchains file
 -h,--help                              Display help information
 -l,--log-file <arg>                    Log file where all build output
                                        will go.
 -llr,--legacy-local-repository         Use Maven 2 Legacy Local
                                        Repository behaviour, ie no use of
                                        _remote.repositories. Can also be
                                        activated by using
                                        -Dmaven.legacyLocalRepo=true
 -N,--non-recursive                     Do not recurse into sub-projects
 -npr,--no-plugin-registry              Ineffective, only kept for
                                        backward compatibility
 -npu,--no-plugin-updates               Ineffective, only kept for
                                        backward compatibility
 -nsu,--no-snapshot-updates             Suppress SNAPSHOT updates
 -o,--offline                           Work offline
 -P,--activate-profiles <arg>           Comma-delimited list of profiles
                                        to activate
 -pl,--projects <arg>                   Comma-delimited list of specified
                                        reactor projects to build instead
                                        of all projects. A project can be
                                        specified by [groupId]:artifactId
                                        or by its relative path.
 -q,--quiet                             Quiet output - only show errors
 -rf,--resume-from <arg>                Resume reactor from specified
                                        project
 -s,--settings <arg>                    Alternate path for the user
                                        settings file
 -T,--threads <arg>                     Thread count, for instance 2.0C
                                        where C is core multiplied
 -t,--toolchains <arg>                  Alternate path for the user
                                        toolchains file
 -U,--update-snapshots                  Forces a check for missing
                                        releases and updated snapshots on
                                        remote repositories
 -up,--update-plugins                   Ineffective, only kept for
                                        backward compatibility
 -V,--show-version                      Display version information
                                        WITHOUT stopping build
 -v,--version                           Display version information
 -X,--debug                             Produce execution debug output
[ERROR] Error executing Maven.
org.apache.commons.cli.MissingArgumentException: Missing argument for option: f
	at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
	at org.apache.commons.cli.Parser.processOption(Parser.java:393)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at org.apache.maven.cli.CLIManager.parse(CLIManager.java:159)
	at org.apache.maven.cli.MavenCli.cli(MavenCli.java:406)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:277)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by bartoszmajsak** [comment] 2018-08-07 18:30
Thanks for detailed report @dkranz! This seems to be a duplicate of https://github.com/openshiftio/openshift.io/issues/2152 - in such a case could you subscribe to that issue and close this one?

**Closed** 2018-08-07 18:33 UTC

**Comment by rhopp** [comment] 2018-08-08 04:41
@bartoszmajsak To me it seems more like duplicate of https://github.com/openshiftio/openshift.io/issues/2856 (the macro `${current.project.path}` sometimes returns empty string - and because of that the build fails... the option `-f` expects an argument)
This was also reported upstream (https://github.com/eclipse/che/issues/9321), but unfortunately it was closed, even though I provided steps to reproduce on latest upstream. I'll try to get in contact with che-qe guys to reopen it.

**Comment by bartoszmajsak** [comment] 2018-08-08 05:59
@rhopp Well, then we have two cases where `-f` is causing trouble. For Vertx and it's what you described, for WF Swarm/Thorntail it's https://issues.jboss.org/browse/THORN-2049

Would be good to understand what is this "sometimes" you mention :)

**Comment by rhopp** [comment] 2018-08-08 06:02
@bartoszmajsak One of the use-cases where it's 100% reproducible is described in this comment: https://github.com/eclipse/che/issues/9321#issuecomment-409487175 and the screencast of that is in the comment below that ;-)
