### ISSUE TITLE
Errors resulting from deployments that exceed a users quota are not trapped and reported to the user

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2270] opened 2018-02-14 20:01 UTC
Steps to recreate:
* Reset a user's env 
* Create (3) new quickstarts - do this serially - and permit each build pipeline to complete:

![screenshot from 2018-02-14 14-38-39](https://user-images.githubusercontent.com/642621/36225084-9182d808-1197-11e8-86cd-16b04f52d438.png)

Observe that while the 3rd quickstart is reported to be successfully deployed, neither the stage nor run endpoints are accessible.

Observe that the deployments page correctly reports the state of all the quickstarts:

![screenshot from 2018-02-14 14-39-15](https://user-images.githubusercontent.com/642621/36225162-c853f7b8-1197-11e8-8abe-5f7771f4c200.png)

**Comment by qodfathr** [comment] 2018-02-15 14:59
Closing as a dupe of #874 and #508.

The *deployment* was fine, so the pipeline should be Green. The issue is that the `Rollout to Run` link does not indicate that the app isn't *running*.

The Pipelines Screen is in need of an overhaul (and potentially merging into either Codebases or Deployments).

**Closed by qodfathr** 2018-02-15 14:59 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug
