### ISSUE TITLE
Space name showing up repeatedly at Pipelines screen

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1170] opened 2017-10-20 06:28 UTC
Under Pipelines screen, try to perform any operation on a Pipeline would show up the corresponding space name multiple times. Please check the screenshot
<img width="1424" alt="screen shot 2017-10-20 at 11 49 17 am" src="https://user-images.githubusercontent.com/15967765/31807769-ae1fa1e6-b58d-11e7-8adb-fa57592abe74.png">

**Comment by joshuawilson** [comment] 2017-10-20 14:12
@krishnapaparaju I'm not seeing this. Can you please specify the exact steps you followed so we can reproduce it.

**Comment by joshuawilson** [comment] 2017-11-19 05:37
@krishnapaparaju is this still an issue for you?

**Comment by qodfathr** [comment] 2018-01-22 20:53
No ones seems to be able to reproduce this, so closing. @krishnapaparaju please feel free to reopen if you see it again.

**Closed by qodfathr** 2018-01-22 20:53 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug
