### ISSUE TITLE
No indication that boxes are clickable in deploymenets page

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#2958] opened 2018-04-09 18:20 UTC
There are no visible indicators that the boxes on the deployments page are clickable. I happened to mis-click the 3 dot menu which caused the expansion of the box. Clickable areas should have some sort of hover treatment or indication that an action can be taken.

![deployments](https://user-images.githubusercontent.com/14068621/38514854-5cebe984-3c00-11e8-8a5e-2d0c3d919b10.gif)

**Comment by joshuawilson** [comment] 2018-04-09 18:48
duplicate of https://github.com/openshiftio/openshift.io/issues/2226

**Closed by joshuawilson** 2018-04-09 18:48 UTC
Labels: SEV4-low, area/deployments
