### ISSUE TITLE
Che pod can require ~10+ minutes to start after user resets environment in OSIO

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#666] opened 2017-08-27 03:30 UTC
To recreate:
* Clean/reset user account
* Observe Che pod events log - Error attaching EBS volume errors are logged

As are syncing errors and errors related to volume mounting:

Unable to mount volumes for pod "che-1-deploy_ldimaggi-osiotest1-che(cb6a1abe-8795-11e7-a062-0233cba325d9)": timeout expired waiting for volumes to attach/mount for pod "ldimaggi-osiotest1-che"/"che-1-deploy". list of unattached/unmounted volumes=[deployer-token-h2pgn]

See attached Event log.

**Comment by ldimaggi** [comment] 2017-08-27 03:41
[Che Events.pdf](https://github.com/openshiftio/openshift.io/files/1254125/Che.Events.pdf)

**Comment by ldimaggi** [comment] 2017-08-27 03:41
This error was seen all day on August 26 - it seems to have cleared up at about 23:00 Boston time - did something change?

**Comment by ldimaggi** [comment] 2017-08-27 03:43
Related to:
* https://github.com/openshiftio/openshift.io/issues/665
* https://github.com/openshiftio/openshift.io/issues/595

**Comment by joshuawilson** [comment] 2017-08-27 05:10
cc @kbsingh @jstrachan @aslakknutsen @rawlingsj

**Comment by aslakknutsen** [comment] 2017-08-27 17:16
@joshuawilson @kbsingh Has ops on it to diagnose.

**Comment by ldimaggi** [comment] 2017-08-28 13:00
Is this an issue of the pod, when dropped/created is moved to a new AWS volume?

**Comment by cctrieloff** [comment] 2017-08-30 18:14
2:07:18 PM	che-2-deploy	Pod	Warning	Failed mount 	Unable to mount volumes for pod "che-2-deploy_cctrieloff-che(bd4a55a1-8dad-11e7-b495-02d7377a4b17)": timeout expired waiting for volumes to attach/mount for pod "cctrieloff-che"/"che-2-deploy". list of unattached/unmounted volumes=[deployer-token-csq0k]

I'm getting a slightly different error, with pvc failures.

Carl.

**Comment by ldimaggi** [comment] 2017-08-30 18:36
https://bugzilla.redhat.com/show_bug.cgi?id=1486523

**Comment by ldimaggi** [comment] 2017-08-30 20:20
Similar issue seen for Jenkins - less severe as less memory is required?

**Comment by ldimaggi** [comment] 2017-08-30 20:31
Increased competition for 3GB for each user's Che service would lead to slower repsonse times under load by large numbers of users.

**Comment by joshuawilson** [comment] 2017-09-07 03:46
@kbsingh do you have an update on this?
@ldimaggi are you still seeing this?

**Comment by ldimaggi** [comment] 2017-09-07 13:05
Nothing seems to have changes in OSO - I am still seeing this issue - intermittently.

**Comment by kbsingh** [comment] 2017-09-08 23:03
Working with 4 teams on this, there are different factors that impact the overall result. Typically for accounts that get into a bad-state you would see the bringup time of about 12 minutes. At this point the fix is via : 
* networking team, is working on the endpoint latency issue ( this has improved from 2 min per endpoint to under 30 seconds, with some scope for further improvement ) 
* the storage team are working to better handle conditions when the deployments and the storage callout starts flapping.
* the che team is working to disagnose and stop the storage flapping being caused
* as of today, we have also discovered that the clean/update tenant process has actually made the process worse, we need to improve that, and better handle exceptions and errors from the api.

I am driving to get a bulk of this in place first half of the week starting 18th Sept. But its going to be grades of better, there is still quite a lot of work to be done to get to the under 1 minute bringup goal. Might not be realised till the multi-tenant is in place, and we are on ocp 3.7 ( end Oct '17 ).

**Comment by joshuawilson** [comment] 2017-09-09 02:06
Since this has been impacting the workshop and specifically Rafael, I'm adding it to the Workshop backlog. 
cc @burrsutter @bmicklea

**Comment by kbsingh** [comment] 2017-09-09 13:19
One thing I wanted to comment on was that we have no evidence at this point that there is a memory issue. With no over commit running at this point, there ahould be no contention at all.

**Comment by kbsingh** [comment] 2017-09-09 13:19
Did not mean to close this, fat fingered the button. Reopen.

**Comment by burrsutter** [comment] 2017-09-09 17:55
So the logic in "Reset Tenant" might have some bugs in it?  It took us over a month to get the current logic agreed to and coded.  With that said, I understand that it is a very, very tricky "feature" of the product since it touches on virtually everything.  Even when we have multi-tenant, we will still need a "reset" feature as there will still be "stuff in my tenant that needs to be cleaned".

**Comment by ldimaggi** [comment] 2017-09-15 15:34
This is an intermittent problem - but it is being seen repeatedly on Sept 15.

**Comment by ldimaggi** [comment] 2017-09-15 15:40
Events file - from 9 min Che start up sequence:

[9min-to-start-Che.pdf](https://github.com/openshiftio/openshift.io/files/1306846/9min-to-start-Che.pdf)

**Comment by ldimaggi** [comment] 2017-09-15 16:21
Is this an OpenShift issue?:

"Failed to attach volume. Volume is currently attached to an instance" issue. hat happens when we rollout a new instance of Che. OpenShift stops Che #1 first and detach all its PV. But apparently that takes a lot of time. So when Che #2 is started OpenShift fails to attach it to a persistent volume.

**Comment by l0rd** [comment] 2017-09-15 16:25
I'm trying to understand if this issue is really related to Che or not. To figure that out let me create a dumb deployment config yaml file with a couple of PVC and try to: start/idle/rollout. 

@ldimaggi by the way if we agree that this issue is not related to the memory I think we should rename it with "Failed to attach Che volume because already attached to an instance".

**Comment by l0rd** [comment] 2017-09-18 10:22
I've been able to reproduce the PV error using image `openshift/hello-openshift` (instead of Che):

```
Failed to attach volume "<pvc....>" on node "<hostname>" with: Error attaching EBS volume "<vol-...>" to instance "i-...": VolumeInUse: <vol-...> is already attached to an instance status code: 400, request id: <id>. The volume is currently attached to instance "<i-...>"
```

The error doesn't happen systematically. I'm writing a simple script that continuously create/delete deployment config with one pod and 2 PVC and logs when there are some volumes errors. I will let it run for one hour and will share results here.

**Comment by l0rd** [comment] 2017-09-19 02:01
![image](https://user-images.githubusercontent.com/606959/30572501-49cb70d8-9cee-11e7-9806-0d128d25b0b3.png)

I've been running a script that creates/starts/deletes a simple [OpenShift Hello World](https://github.com/openshift/origin/tree/master/examples/hello-openshift) application for about one hour on openshift.io. 

I've put the deployment yml file, the logs and the script to run the test in a [gist](https://gist.github.com/l0rd/041c319a2a80d059da60e68127d56fb1). 

**Results:**

- Starting the application can take between 30 seconds and 7 minutes.
- Sometimes the application is started and deleted without any error, sometimes there are many
- I've seen different kink of errors (full log is [here](https://gist.github.com/l0rd/041c319a2a80d059da60e68127d56fb1#file-helloworld-log)):
```
"Error syncing pod"
```

```
"Error: Couldn't find key workspaces-memory-limit in ConfigMap mloriedo-che/che"
```

```
"Failed to attach volume \"pvc-46ca797d-9cd5-11e7-a6ba-02d7377a4b17\" on node \"ip-172-31-69-112.us-east-2.compute.internal\" with: Error attaching EBS volume \"vol-002bd3cb1d1cd7bf0\" to instance \"i-0805ab691188b9db3\": IncorrectState: vol-002bd3cb1d1cd7bf0 is not 'available'.\n\tstatus code: 400, request id: 4fed43ad-1e8f-4da5-a31c-6278e08d1c3b"
```

```
"MountVolume.SetUp failed for volume \"kubernetes.io/secret/<id>-9cd4-11e7-8821-02e52a0be43d-deployer-token-vmkvr\" (spec.Name: \"deployer-token-vmkvr\") pod \"0a8563f7-9cd4-11e7-8821-02e52a0be43d\" (UID: \"0a8563f7-9cd4-11e7-8821-02e52a0be43d\") with: secret \"mloriedo-che\"/\"deployer-token-vmkvr\" not registered"
```

```
"SchedulerPredicates failed due to persistentvolumeclaim \"che-data-volume\" not found, which is unexpected. (repeated 153 times)"
```

```
"skip schedule deleting pod: mloriedo-che/che-1-ckkg9"
```

```
"Unable to mount volumes for pod \"che-1-deploy_mloriedo-che(<id>-9ccf-11e7-8821-02e52a0be43d)\": timeout expired waiting for volumes to attach/mount for pod \"mloriedo-che\"/\"che-1-deploy\". list of unattached/unmounted volumes=[deployer-token-vmkvr]"
```

```
"Unable to mount volumes for pod \"che-2-3wwk5_mloriedo-che(<id>-9cc2-11e7-8821-02e52a0be43d)\": timeout expired waiting for volumes to attach/mount for pod \"mloriedo-che\"/\"che-2-3wwk5\". list of unattached/unmounted volumes=[che-data-volume]"
```

```
"Unable to mount volumes for pod \"che-2-deploy_mloriedo-che(<id>-9cc2-11e7-8821-02e52a0be43d)\": timeout expired waiting for volumes to attach/mount for pod \"mloriedo-che\"/\"che-2-deploy\". list of unattached/unmounted volumes=[deployer-token-vmkvr]"
```

**Conclusions**

- Che java code is not the cause of this issue
- Che deployment yml file may be the cause but I cannot identify any issue with it (here is the [sample yml](https://gist.github.com/l0rd/041c319a2a80d059da60e68127d56fb1#file-helloworld-yml)) 
- Behaviours between one run and another are not consistent. Besides the workload of the cluster at a particular moment, another variable may be that pods get deployed on different nodes at every run. Maybe correlating the nodes with the kind of errors will help us understand what is happening and how to avoid it.
 
**Possible fixes Che side**

I have in mind some smalls improvements that may shorten Che server startup (but none of these will eliminate the PV related errors):
- [ ] Decrease `readinessProbe` initial delay
- [ ] Remove workspaces PVC from Che server deployment yml
- [ ] Use different names for Che server data PVC and PV 
- [ ] Use deployment instead of replicasets (#875)

**Comment by bmicklea** [comment] 2017-09-19 13:33
@slemeur @qodfathr  FYI - more information above on the reliability issues we've been seeing with Che on OSIO.

**Comment by l0rd** [comment] 2017-09-26 14:27
After yesterdey deployment I've repeated [the test](https://github.com/openshiftio/openshift.io/issues/666#issuecomment-330406166) I've done last week (deploying an helloworld application over and over for 1h) and results are encouraging: 

- Deployment never takes more than 52 seconds
- There are still some errors in OpenShift events but these don't affect performances and there are only 2 kind of errors:
  - `"Error syncing pod"`
  - `"Failed to attach volume \"pvc-5741ed2e-a2ab-11e7-ba7a-02e52a0be43d\" on node \"ip-172-31-79-58.us-east-2.compute.internal\" with: Error attaching EBS volume \"vol-0c8e316b27a9a6884\" to instance \"i-0f02b9085bb379d9d\": IncorrectState: vol-0c8e316b27a9a6884 is not 'available'.\n\tstatus code: 400, request id: ea5d107e-e379-42bf-b06b-0e5873adff9c"`

@ldimaggi please let me know if you experience the same improvements.

I've put the test logs in a [gist](https://gist.github.com/l0rd/041c319a2a80d059da60e68127d56fb1#file-helloworld20170926-log).

**Comment by ldimaggi** [comment] 2017-09-26 14:31
Thanks Mario - Che does seem quicker now. Let me check today - maybe we can close this issue now.

**Comment by kbsingh** [comment] 2017-09-26 18:16
This is in line with the perf improvement we have seen from service side as well. @l0rd we should still work on and get the potential fixes you outlined above.

**Comment by l0rd** [comment] 2017-09-26 18:43
@kbsingh here is a short update on the fixes outlined above:

- **Decrease readinessProbe initial delay**: PR opened https://github.com/fabric8-services/fabric8-tenant-che/pull/42 and when applied Che server will be ready ~45s earlier.
- **Remove workspaces PVC from Che server deployment yml**: That doesn't seems to work because `che` service account doesn't have the right to create PVC
- **Use different names for Che server data PVC and PV**: this doesn't improve perfs at all and, as a result, users will lose their workspaces. I would not implement it.
- **Use deployment instead of replicasets (#875)**: still need to work on this

**Comment by joshuawilson** [comment] 2017-09-27 05:09
Can we close this?

**Comment by l0rd** [comment] 2017-09-27 13:09
I am closing this issue. Only task "Use deployment instead of replicaset" need to be addressed but it's already tracked by [875](https://github.com/openshiftio/openshift.io/issues/875) and is losely related to this issue. @ldimaggi feel free to reopen if you can still reproduce.

**Closed by l0rd** 2017-09-27 13:09 UTC
Labels: area/che, kind/bug, severity/P1, team/service-delivery
