### ISSUE TITLE
Analytics reports on prod-preview show incorrect totals for unknown dependencies

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2883] opened 2018-04-04 15:21 UTC
Steps to recreate:
* Login to prod-preview
* Create a new quickstart - example, the Vert.x HTTP quickstart
* When the quickstart build pipeline completes, view the analytic report
* The report should show zero unknown dependencies for any of the OSIO quickstarts

For example, in production, the Vert.x quickstart analytic report shows:
![screenshot from 2018-04-04 09-00-24](https://user-images.githubusercontent.com/642621/38317037-21f96f68-37fa-11e8-9cf5-77056321dbe1.png)

On prod-preview, however, the report shows:

![screenshot from 2018-04-04 11-12-48](https://user-images.githubusercontent.com/642621/38317078-362705d6-37fa-11e8-9ec6-c6cf4080181b.png)

![screenshot from 2018-04-04 11-12-28](https://user-images.githubusercontent.com/642621/38317081-363798c4-37fa-11e8-8f47-0567ec11b138.png)

**Comment by ldimaggi** [comment] 2018-04-05 19:30
I just recreated the issue - see here:

[testforprodpreview-master.zip](https://github.com/openshiftio/openshift.io/files/1881470/testforprodpreview-master.zip)

**Comment by msrb** [comment] 2018-04-05 19:52
Thanks @ldimaggi. This is weird as the quickstart uses community artifacts and I can see the data in S3. Trying to re-analyze the packages, just to make sure it's not data related issue.

**Comment by miteshvp** [comment] 2018-04-17 06:17
@msrb - any updates here? Can we close this issue?

**Comment by sara-02** [comment] 2018-04-17 13:35
@ldimaggi Can you please provide any update on this issue?

**Comment by sara-02** [comment] 2018-04-17 14:17
@msrb ^^ :/

**Comment by msrb** [comment] 2018-04-17 18:47
Hmm, we will need to figure out how to keep data in staging up-to-date. We don't actively analyze new versions in prod-preview. This happened because dependencies in quickstarts got updated.

In any case, I can see the data on S3 and should be also in graph. We should be good (for now).

**Comment by miteshvp** [comment] 2018-04-18 05:26
@msrb - I confirmed the data is now available on stage. I still think we need to re-work on the success of stack reports. I feel checking unknown components may not be the right approach. Let's discuss this during our cabal. 
@ldimaggi - please reopen if you still see unknown deps on prod-preview.

**Comment by msrb** [comment] 2018-04-23 07:19
@ldimaggi is it the same Vert.x HTTP quickstart app?

**Comment by msrb** [comment] 2018-05-09 22:47
@ldimaggi I believe this should be fixed already. Please reopen if you are still able to reproduce this issue. Thanks :wink:

**Closed by msrb** 2018-05-09 22:47 UTC
Labels: SEV2-high, area/analytics, team/analytics, type/bug
