### ISSUE TITLE
Unable to scroll on a Space homepage

### ISSUE THREAD

**Issue by evanshortiss** [openshiftio/openshift.io#3104] opened 2018-04-12 20:00 UTC
If the homepage for a Space is run in a window that's less than approx 970px wide the lower tiles are pushed down (response design FTW), but it's not possible to scroll down and see them. 
![screen shot 2018-04-12 at 12 57 26](https://user-images.githubusercontent.com/1303687/38700800-18f6ac16-3e51-11e8-9825-26d1fd4793d5.png)

**Comment by aptmac** [comment] 2018-04-12 20:04
Related: https://github.com/openshiftio/openshift.io/issues/1443

**Comment by dlabrecq** [comment] 2018-04-16 17:13
I'm not able to reproduce the issue on either the new or old dashboard layouts. Tested the latest code from master using Firefox and Chrome.

Looking at the browser console errors in the snapshot, I see a routing error which could have been the underlying problem?

That error was fixed by: https://github.com/fabric8-ui/fabric8-ui/pull/2738

**Comment by joshuawilson** [comment] 2018-04-17 00:27
I can't reproduce this in the dashboards in prod. Closing.
@evanshortiss if you can provide steps to reproduce this, please reopen.

**Comment by jiekang** [comment] 2018-04-18 15:35
Yeah. I can reproduce as well; there is no scrollbar for any page after visiting the Planner

**Comment by joshuawilson** [comment] 2018-04-23 22:13
Nice work @aptmac. Very clearly presented. 

@michaelkleinhenz can you please make sure this gets reviewed and merged if possible.

**Comment by dlabrecq** [comment] 2018-04-24 03:08
Surprised to see DOM styles modified directly via JavaScript. Setting the body's overflow style should be done via CSS. Possibly by fabric8-ui itself when Planner is displayed? @mindreeper2420

**Comment by mindreeper2420** [comment] 2018-04-24 03:24
Ideally, Planner specific CSS would have a particular prefix (similar to launcher's use of `f8-launcher`) that would prevent any other aspects of the application from being affected by the types of interactions. This would be preferred over other types of manipulation.

Additionally, there are multiple pieces that appear to 'break' when navigating to other aspects of the site after first visiting Planner, not just the vertical scrollbars (though that is the most obvious). Encapsulating these specific styles would help to alleviate those issues as well.

**Comment by dlabrecq** [comment] 2018-04-24 04:01
To eliminate any CSS bleed into fabric8-ui, I'd like to see the top level Planner components (list, board) use ViewEncapsulation.Emulated. (Alternatively, we could wrap Planner with a component and add ViewEncapsulation.Emulated there?) Unfortunately, that wouldn't prevent Planner from using JavaScript to manipulate the fabric8-ui's body tag.

**Comment by SMahil** [comment] 2018-04-24 06:32
@aptmac This was done because of planner previous design where quick add was at bottom. Now its good to handle this via css. https://github.com/fabric8-ui/fabric8-planner/pull/2577 This PR fixes platform but not planner. I will raise the PR for planner

**Closed** 2018-04-24 08:33 UTC
Labels: SEV3-medium, area/UI, area/UX, team/planner, team/platform, team/ux, type/bug
