### ISSUE TITLE
Che "run" command not defined for imported projects

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2358] opened 2018-02-25 20:46 UTC
Steps to recreate:
* Create new quickstart in OSIO - make note of the github repo location
* Reset user env in OSIO
* Create a new project in OSIO 
* Import the github repo created earlier
* Create Che workspace
* Observe that the run command is not defined for the workspace

![screenshot from 2018-02-25 12-15-53](https://user-images.githubusercontent.com/642621/36646228-e5b83d1a-1a42-11e8-82db-d20c4607f8ad.png)

**Comment by rhopp** [comment] 2018-02-26 09:54
The run commands are defined in stack used by workspace.
Stacks used in rh-che (che on osio) are defined here: https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L467-L491 (selected lines define commands for vert.x stack for example)
You can also see what commands are configured for each stack by going to `che.openshift.io -> Stacks -> <select desired stack> -> Commands`
You can see what stack is used by which workpsace by going to `che.openshift.io -> workpaces`:
![image](https://user-images.githubusercontent.com/1215011/36663740-df2881bc-1ae2-11e8-997a-955b01aa5bc7.png)

As you can see on the screenshot above, the currently running workspace does not have any stack assigned (this one was created for imported project to osio)

@ibuziuk Don't you happen to know, whether is there any logic for deciding which stack should be used for a codebase?

**Comment by ibuziuk** [comment] 2018-02-26 10:04
@ldimaggi @rhopp by default java-centos [1] stack is used for projects that are imported (not created via quickstart). In this stack there is no run command since user could import any project and run command would vary. Other stacks like vertx are used only when the project is created via quickstart. So, absence of the "run" command is expected.

https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L400

**Comment by ibuziuk** [comment] 2018-02-26 13:16
Even though the absence of the  "run" command is expected always falling back on `java-centos` stack is wrong. For example, if user would try to import node.js project it will not be possible to run it. Basically, there should be some mechanism in place for specifying stack during project import to codebase @l0rd WDYT ?

**Comment by rhopp** [comment] 2018-02-26 13:18
This may be work for UX team, right?

**Comment by ldimaggi** [comment] 2018-02-26 14:35
Thanks - I’ll log a feature request for this today.


(Sent from my iPhone)



On Feb 26, 2018, at 8:20 AM, Ilya Buziuk <notifications@github.com> wrote:

@rhopp <https://github.com/rhopp> yes, and we need a separate issue IMO.
Once created this one could be closed

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/openshift.io/issues/2358#issuecomment-368501820>,
or mute the thread

**Comment by ibuziuk** [comment] 2018-02-26 14:47
@ldimaggi I have already created one https://github.com/openshiftio/openshift.io/issues/2361.
Closing

**Comment by l0rd** [comment] 2018-02-26 14:56
That's something that [CheStackDetector](https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/che/CheStackDetector.java) was doing (automatically identifying the stack from the dependencies in `pom.xml`). So this look like a bug/regression launcher side (not Che). 

Re-opening and adding label `team/launcher`.

**Comment by ibuziuk** [comment] 2018-02-26 15:01
@l0rd cool, didn't know about that. Do you know if this detector also kick in for `Add Codebase` flow from the "Codebases" page ?

**Comment by l0rd** [comment] 2018-02-26 17:42
@ibuziuk I have no idea is [CheStackDetector](https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/che/CheStackDetector.java) is ever used now. The fabric8-generator repository has been archived and I don't know where this code lives currently. Maybe @chmouel or @gastaldi have an idea?

**Comment by ldimaggi** [comment] 2018-02-26 17:49
Just to confirm - the detector should be running and users therefore should be provided with run and debug options? Thx!

**Comment by l0rd** [comment] 2018-02-26 17:56
@ldimaggi that's my understanding, but we would better to have a confirmation by the launcher team.

**Comment by gastaldi** [comment] 2018-02-26 18:00
@l0rd I think I have already mentioned in another issue that the code was moved to https://github.com/fabric8-launcher/launcher-backend/tree/master/addons/osio-addon

We kept the original behavior, are you sure that ever worked before?

**Comment by gastaldi** [comment] 2018-02-26 18:04
Ah as per https://github.com/openshiftio/openshift.io/issues/2358#issuecomment-368449832 comments this is a new feature.

**Comment by l0rd** [comment] 2018-02-26 18:08
@gastaldi thanks for the new repo link. I don't know if that ever worked. But if it never worked that would make it a bug rather then a regression but still something we may want to fix.

**Comment by gastaldi** [comment] 2018-02-26 19:01
We're rewriting the OSIO launcher backend addon, and the Import Wizard backend functionality is in a PR ( https://github.com/fabric8-launcher/launcher-backend/pull/95) The new OSIO backend addon is in https://github.com/fabric8-launcher/launcher-backend/tree/master/addons/new-osio-addon.

This bug/missing feature will need to be fixed in this new addon, as we don't want to maintain that legacy code anymore.

**Comment by sunilk747** [comment] 2018-04-02 16:10
Any updates on this issue? @l0rd @ibuziuk

**Comment by ibuziuk** [comment] 2018-04-04 10:06
@sunilk747 no update AFAIK.
@gastaldi am I correct that `new-osio-addon` still does not include stack detector functionality that was previously in `CheStackDetector` [1] and was deprecated ?

[1] https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/che/CheStackDetector.java

**Comment by gastaldi** [comment] 2018-04-04 11:49
@ibuziuk nope, you are wrong, :) Here it is: https://github.com/fabric8-launcher/launcher-backend/tree/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/che

**Comment by ibuziuk** [comment] 2018-04-04 12:07
@gastaldi that's quite strange than. When I try to add che-starter [1] to osio (spring-boot project) workspace is still created against default `java-centos` not `spring-boot` stack

[1] https://github.com/redhat-developer/che-starter

**Comment by gastaldi** [comment] 2018-04-04 12:16
@ibuziuk does this happen only in the Import flow? I think this may be caused by the `if` clause in https://github.com/fabric8-launcher/launcher-backend/blob/ce58b70927000d3c3e21595c312f00dfc76d6160/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java#L125-L128

**Comment by gastaldi** [comment] 2018-04-04 14:51
@ibuziuk I've opened https://github.com/fabric8-launcher/launcher-backend/issues/258 to fix, apparently we're not cloning the imported repository and applying the changes the legacy code used to do

**Comment by ibuziuk** [comment] 2018-04-04 18:53
@gastaldi yeah, this happens for me on osio during  both "Import" & "Add Codebase" (from "Codebases" tab)

**Comment by gastaldi** [comment] 2018-04-04 22:41
@ibuziuk @ldimaggi the https://github.com/fabric8-launcher/launcher-backend/issues/258 issue was fixed in https://github.com/fabric8-launcher/launcher-backend/commit/0a64a45fe446716ec4b7c2d11c916da5e5b599ea, can you test again, please?

**Comment by ibuziuk** [comment] 2018-04-05 08:47
@gastaldi hmmm... tested on preview and seems that importing che-starter to codebase still results in workspace creation against `java-centos`

**Comment by gastaldi** [comment] 2018-04-05 21:47
@ibuziuk I have just tested and I see the run command:

![screenshot from 2018-04-05 18-47-25](https://user-images.githubusercontent.com/54133/38393637-cf146d9e-3901-11e8-8397-2095c9d846a2.png)

**Comment by ibuziuk** [comment] 2018-04-10 09:40
@gastaldi I have just tested against che-starter [1] on prod - still `java-centos`, not `spring-boot` is used. 

[1] https://github.com/redhat-developer/che-starter

**Comment by mishaone** [comment] 2018-04-10 09:42
I'm facing this issue now in the import workflow, but not the create a quickstart workflow. Details in this issue: https://github.com/openshiftio/openshift.io/issues/2965

Please feel free to close the above if this is still addressing the same issue I've reported.

**Comment by gastaldi** [comment] 2018-04-10 13:28
@ibuziuk I don't think that is using the new UI. Can you try as in https://drive.google.com/open?id=1bfctUdczJtI7MRDPbj5-bvGtnj6GcymY?

**Comment by gastaldi** [comment] 2018-04-11 20:30
@ibuziuk I have forked the  https://github.com/redhat-developer/che-starter repository to my account and imported it and I can see the `run` menu item. I tested in prod-preview, but production should be the same: 

![screenshot from 2018-04-11 17-29-36](https://user-images.githubusercontent.com/54133/38641644-05f09fa8-3dae-11e8-8d0f-a9b0ed9fe380.png)

**Comment by ibuziuk** [comment] 2018-04-12 07:25
@gastaldi awesome, but IMO we should keep this open until osio will use new UI. WDYT ?

**Comment by bartoszmajsak** [comment] 2018-09-12 11:37
@ibuziuk @gastaldi I think we are using "new UI" right now, aren't we? This can be closed then if you can confirm.

**Comment by ibuziuk** [comment] 2018-09-13 06:52
Just tested on production and run command `mvn compile spring-boot:run` has been added by default. Closing

**Closed by ibuziuk** 2018-09-13 06:52 UTC
Labels: SEV2-high, area/che, priority/P4, team/launcher, type/bug
