### ISSUE TITLE
Git repo url overlaps relevant attributes in Application Wizard

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#2102] opened 2018-01-29 19:35 UTC
Steps to reproduce: Create a new space, create a new project, give it sufficiently long name that will be matched by corresponding github repo.

It seems there is overlap between the github URL and the project attributes in the final view of the Space Wizard.

![overlap-text](https://user-images.githubusercontent.com/17230733/35530226-79d67a04-0501-11e8-8db9-b1e64f644ddb.png)

**Comment by joshuawilson** [comment] 2018-01-30 04:08
This is a duplicate but I can't find the other one right now.

**Comment by qodfathr** [comment] 2018-01-31 13:36
You cannot find it because we closed as fixed. :) #1171. Perhaps there is a bug in the logic which determined when to show a truncated "..." version. Maybe it is basing the decision on the number of characters rather than the rendering length of the text. I'll close this as a dupe of #1171 and reopen that one.

**Closed by qodfathr** 2018-01-31 13:36 UTC
Labels: SEV3-medium, area/UI, area/app-wizard, team/analytics/wizard, team/launcher, type/bug
