### ISSUE TITLE
After user env reset - multiple errors seen in Jenkins log while loading Blue Ocean plugins

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4006] opened 2018-07-16 19:21 UTC
Steps to recreate:
* Reset user env in OSIO profile page
* Observe Jenkins pod log when pod starts:
```

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Jenkins Design Language v1.6.2 (jenkins-design-language)
java.io.IOException: Jenkins Design Language v1.6.2 failed to load.
 - You must update Jenkins from v2.93 to v2.107.2 or later to run this plugin.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Blue Ocean Core JS v1.6.2 (blueocean-core-js)
java.io.IOException: Blue Ocean Core JS v1.6.2 failed to load.
 - You must update Jenkins from v2.93 to v2.107.2 or later to run this plugin.
 - Jenkins Design Language v1.6.2 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Web for Blue Ocean v1.5.0 (blueocean-web)
java.io.IOException: Web for Blue Ocean v1.5.0 failed to load.
 - Blue Ocean Core JS v1.6.2 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin REST Implementation for Blue Ocean v1.5.0 (blueocean-rest-impl)
java.io.IOException: REST Implementation for Blue Ocean v1.5.0 failed to load.
 - Web for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline implementation for Blue Ocean v1.5.0 (blueocean-pipeline-api-impl)
java.io.IOException: Pipeline implementation for Blue Ocean v1.5.0 failed to load.
 - REST Implementation for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Bitbucket Pipeline for Blue Ocean v1.6.2 (blueocean-bitbucket-pipeline)
java.io.IOException: Bitbucket Pipeline for Blue Ocean v1.6.2 failed to load.
 - You must update Jenkins from v2.93 to v2.107.2 or later to run this plugin.
 - Pipeline implementation for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Config API for Blue Ocean v1.5.0 (blueocean-config)
java.io.IOException: Config API for Blue Ocean v1.5.0 failed to load.
 - Web for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Dashboard for Blue Ocean v1.5.0 (blueocean-dashboard)
java.io.IOException: Dashboard for Blue Ocean v1.5.0 failed to load.
 - Web for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Events API for Blue Ocean v1.5.0 (blueocean-events)
java.io.IOException: Events API for Blue Ocean v1.5.0 failed to load.
 - Pipeline implementation for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Git Pipeline for Blue Ocean v1.5.0 (blueocean-git-pipeline)
java.io.IOException: Git Pipeline for Blue Ocean v1.5.0 failed to load.
 - Pipeline implementation for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin GitHub Pipeline for Blue Ocean v1.5.0 (blueocean-github-pipeline)
java.io.IOException: GitHub Pipeline for Blue Ocean v1.5.0 failed to load.
 - Pipeline implementation for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin JIRA Integration for Blue Ocean v1.6.2 (blueocean-jira)
java.io.IOException: JIRA Integration for Blue Ocean v1.6.2 failed to load.
 - You must update Jenkins from v2.93 to v2.107.2 or later to run this plugin.
 - REST API for Blue Ocean v1.5.0 is older than required. To fix, install v1.6.2 or later.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Personalization for Blue Ocean v1.5.0 (blueocean-personalization)
java.io.IOException: Personalization for Blue Ocean v1.5.0 failed to load.
 - Dashboard for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Blue Ocean Pipeline Editor v1.5.0 (blueocean-pipeline-editor)
java.io.IOException: Blue Ocean Pipeline Editor v1.5.0 failed to load.
 - Dashboard for Blue Ocean v1.5.0 failed to load. Fix this plugin first.

Jul 16, 2018 5:11:59 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Blue Ocean v1.5.0 (blueocean)
java.io.IOException: Blue Ocean v1.5.0 failed to load.
 - Bitbucket Pipeline for Blue Ocean v1.6.2 failed to load. Fix this plugin first.

```

This is being seen on the starter-us-east-2, 2a, 1a, 1b clusters.

**Comment by lordofthejars** [comment] 2018-07-25 11:51
I have been investigating this issue, and there is something really weird that I cannot understand. 
I have entered to my Jenkins (jenkins.openshift.io) I entered to `Manage Jenkins`  and I have run next groovy script in console:

```
Jenkins.instance.pluginManager.plugins.each{
  plugin ->
    println ("${plugin.getShortName()}:${plugin.getVersion()}")
}
```
Which prints all plugins that are installed.
The result can be seen at: https://gist.github.com/lordofthejars/6a98a37814cb204c606a8df5617ad180#file-gistfile1-txt-L36

Then if you check the log error when Jenkins is starting, it complains about next plugin:

```
Blue Ocean Core JS v1.6.2
You must update Jenkins from v2.93 to v2.107.2 or later to run this plugin.
```
But this plugin according to previous list

**Comment by lordofthejars** [comment] 2018-07-26 09:04
@ldimaggi Do you have any idea when this log lines started to appear? It seems that 8 months ago we updated Jenkins to 2.93.1 so probably this is not the cause of this problem. But also I cannot understand why we get this 1.6.2 problem when the Blue Ocean that we have installed is 1.5.0.

**Comment by lordofthejars** [comment] 2018-07-31 10:32
I have tried this set of plugins in a Jenkins 2.93 locally and I get the same problem, now I am trying to figure out if the problem is in Blue Ocean plugin or in another transitive dependency. What I see is that a possible solution to this problem would be to update our base Jenkins image to jenkins-2.108-1.1 WDYT?

**Comment by rupalibehera** [comment] 2018-07-31 10:37
> I have tried this set of plugins in a Jenkins 2.93 locally and I get the same problem, now I am trying to figure out if the problem is in Blue Ocean plugin or in another transitive dependency. What I see is that a possible solution to this problem would be to update our base Jenkins image to jenkins-2.108-1.1 WDYT?

Jenkins 2.93 did you use the upstream image from the update center ?
If we have only choice of upgrading the image then we should try moving to the latest image.

**Comment by lordofthejars** [comment] 2018-07-31 10:38
I have downloaded the Jenkins from Jenkins site. Then I have taken our plugins.txt file and applied to that installation.

**Comment by rupalibehera** [comment] 2018-07-31 10:41
> I have downloaded the Jenkins from Jenkins site. Then I have taken our plugins.txt file and applied to that installation.

could you try this same thing with jenkins-2.108-1.1  and does it make difference ?

**Comment by lordofthejars** [comment] 2018-07-31 11:15
As I am investigating more I see that the requirement for Blue Ocean 1.6.2 comes from another plugin which requires transitively this version, because exploring Blue Ocean 1.5.0 pom (https://github.com/jenkinsci/blueocean-plugin/blob/blueocean-parent-1.5.0/pom.xml#L29) you can see that the minimum version is 2.73.3

**Comment by ldimaggi** [comment] 2018-08-06 14:49
These issue is still being seen in production:


```
Aug 06, 2018 2:25:55 PM jenkins.InitReactorRunner$1 onTaskFailed SEVERE: Failed Loading plugin Blue Ocean Core JS v1.7.1 (blueocean-core-js)
| java.io.IOException: Blue Ocean Core JS v1.7.1 failed to load.  - You must update Jenkins from v2.93 to v2.121.1 or later to run this plugin.
| - Jenkins Design Language v1.7.1 failed to load. Fix this plugin first.
```

**Comment by sthaha** [comment] 2018-08-06 23:28
@ldimaggi Although the issue has been fixed, it takes a while for the changes to be rolled out to prod. 
I see that you reopened the issue around the time we had updated the files related to tenant jenkins - https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/115 . The image that contains the fix is v54eaba6
I am going to close the issue, please reopen if you still see the bug in that image

@rupalibehera please correct me if I am wrong.

**Comment by ppitonak** [comment] 2018-08-07 11:26
@sthaha it will go to production with https://github.com/openshiftio/saas-openshiftio/pull/1013, won't it?

**Comment by piyush1594** [comment] 2018-08-07 11:40
@ppitonak It was an issue in jenkins image not proxy, i will be available in next jenkins tenant update.

**Comment by piyush1594** [comment] 2018-08-07 18:54
@ppitonak @ldimaggi This is in prod now, just update your tenant to Jenkins version 4.0.99

Closing this. Thanks

**Closed by piyush1594** 2018-08-07 18:54 UTC
Labels: SEV2-high, area/jenkins, priority/P3, team/service-delivery, type/bug

**Comment by ppitonak** [comment] 2018-08-08 12:14
Verified in prod
