### ISSUE TITLE
Iris view - is not showing up items attached to iterations within it

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#3651] opened 2018-05-25 11:49 UTC
Steps to reproduce:
1.  Click on Iris from left menu
2.  Planner items are now filtered - only items assigned to iteration "Iris" are shown.
3.  Please note that "Iteration 149", "iteration 150" are child items of "Iris".
4.  Planner items which are part of "Iteration 149" or "Iteration 150" are not shown in this view.

**Comment by nimishamukherjee** [comment] 2018-05-28 03:29
Removing bug label as the behaviour described by @sivaavkd is by design.
Let @Veethika from UX provide her feedback. We will proceed accordingly.

**Comment by sivaavkd** [comment] 2018-05-28 03:36
cc @qodfathr

**Comment by nimishamukherjee** [comment] 2018-05-28 13:06
Created an issue on OSIO - https://openshift.io/openshiftio/openshiftio/plan/detail/2452

**Comment by GeorgeActon** [comment] 2018-08-24 12:33
its actually a feature request

**Comment by GeorgeActon** [comment] 2018-08-24 12:35
Fixed in prod.

**Closed by GeorgeActon** 2018-08-24 12:35 UTC
Labels: area/planner, priority/P4, team/planner, team/pm, team/ux, type/feature-request
