### ISSUE TITLE
Add Codebase button should only visible to space owner

### ISSUE THREAD

**Issue by vikram-raj** [openshiftio/openshift.io#4211] opened 2018-08-20 07:41 UTC
##### Issue Overview

Add Codebase button on **Create > Codebases** page is always visible. If you try to add codebase then it will fail because only space owner can add codebase to space.

##### Expected Behaviour
Add Codebase button should only visible to space owner.

##### Current Behaviour
Add Codebase button is always visible on **Create > Codebase** page.
##### Steps To Reproduce

1. Go to space which is not own by you and then visit codebase page (```Create > Codebase```) then you will see ```Add codebase``` button.

**Comment by aptmac** [comment] 2018-08-20 14:26
Duplicate of https://github.com/openshiftio/openshift.io/issues/3634 ?

**Closed** 2018-10-30 04:59 UTC
Labels: SEV3-medium, area/codebases, priority/P4, team/platform, type/bug
