### ISSUE TITLE
Show Completed doesn't work for scrum template

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3439] opened 2018-05-03 16:30 UTC
Steps:

- Change Work Item State to Done(Show Completed Checked)
- Now Click Show Completed 
- Work Item with State Done should not be displayed

**Comment by jarifibrahim** [comment] 2018-05-14 06:34
Duplicate of https://github.com/openshiftio/openshift.io/issues/3486.

Closing this one.

**Closed by jarifibrahim** 2018-05-14 06:34 UTC
Labels: area/planner, team/planner, type/bug
