### ISSUE TITLE
Sort option on the Pipeline page is broken

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#520] opened 2017-08-09 13:22 UTC
The sorting option on the Pipeline page is broken and has no effect on the displayed results.

See attached video for reference.

https://drive.google.com/open?id=0BwLIZeed5jyKTGVtTEVKbnVUbWM

**Comment by rgarg1** [comment] 2017-08-09 13:27
Sorting is also broken on the 'Applications' page.

**Comment by joshuawilson** [comment] 2017-08-13 03:06
It is fake, there is no implementation yet.
Duplicate of #489
Closing.

**Closed by joshuawilson** 2017-08-13 03:06 UTC
