### ISSUE TITLE
Filter by Creator|Assignee cause Type error in Console and hang for ever

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1983] opened 2018-01-23 14:21 UTC
```javascript
ERROR TypeError: Cannot read property 'id' of undefined
    at SafeSubscriber._next (0.c5d616abcbeed23a35f5.chunk.js:1)
    at SafeSubscriber.__tryOrUnsub (patternfly-additions.min.css:1)
    at SafeSubscriber.next (patternfly-additions.min.css:1)
    at Subscriber._next (patternfly-additions.min.css:1)
    at Subscriber.next (patternfly-additions.min.css:1)
    at CombineLatestSubscriber.notifyNext (patternfly-additions.min.css:1)
    at InnerSubscriber._next (patternfly-additions.min.css:1)
    at InnerSubscriber.Subscriber.next (patternfly-additions.min.css:1)
    at SwitchMapSubscriber.notifyNext (patternfly-additions.min.css:1)
    at InnerSubscriber._next (patternfly-additions.min.css:1)
```

![screenshot from 2018-01-23 15-19-06](https://user-images.githubusercontent.com/132158/35280505-c50b5482-0050-11e8-9d95-3fb84c2be557.png)

## Impacts
- [ ] #2146 Planning Experience placeholder

**Comment by michaelkleinhenz** [comment] 2018-01-23 15:37
Works for me as well on prod and prod-preview. In which state did you encounter this? Were you logged in or logged out?

**Comment by qodfathr** [comment] 2018-01-23 17:41
I see this on prod.

**Comment by aslakknutsen** [comment] 2018-01-23 20:08
@michaelkleinhenz I see it in prod and preview. It's not in the openshiftio space, but it's on one of my own. Possible related; there is only 1 collaborator on my space, me.

**Comment by michaelkleinhenz** [comment] 2018-01-25 09:49
Still can not reproduce on one of your spaces or one of mine with only one contributor. Weird.

**Comment by michaelkleinhenz** [comment] 2018-01-25 09:50
@aslakknutsen on which space are you seeing this?

**Comment by aslakknutsen** [comment] 2018-01-25 13:27
@michaelkleinhenz Any space with only 1 user so far... But here is one https://openshift.io/aslak/test670/plan

**Comment by jarifibrahim** [comment] 2018-02-15 10:12
@michaelkleinhenz @aslakknutsen I see the same issue on prod/prod-preview. I'm the only collaborator in that space.

**Comment by debloper** [comment] 2018-02-22 13:11
Any reliable way to reproduce this?

**Comment by nimishamukherjee** [comment] 2018-02-22 16:18
@debloper 
1. Create a new space
2. Click on Assignee or Creator in the filter drop down.

This issue is seen on any space with a single user.

**Comment by nimishamukherjee** [comment] 2018-04-05 06:43
Fixed with ngrx.
@aslakknutsen please check on prod

**Closed** 2018-04-06 22:07 UTC
Labels: SEV2-high, area/planner, team/planner, train/heather, type/bug, verified-fix-in-prod
