### ISSUE TITLE
Broken page after filtering work items

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#3060] opened 2018-04-12 14:04 UTC
After filtering my work items by assignee (but having no result, if that matters), I can see that the `Add Work Item` text hovers the `Requirement` filter:

<img width="952" alt="screenshot 2018-04-12 15 57 58" src="https://user-images.githubusercontent.com/178502/38682350-27768210-3e6b-11e8-83d3-3d853f75bd08.png">

**Comment by Preeticp** [comment] 2018-04-12 14:09
Duplicate of #3042

**Closed** 2018-04-12 20:40 UTC
Labels: SEV2-high, area/planner, team/planner, type/bug
