### ISSUE TITLE
Http Error 500 when creating space on prod-preview

### ISSUE THREAD

**Issue by ia3andy** [openshiftio/openshift.io#3236] opened 2018-04-23 09:27 UTC
I think there is a bug on https://prod-preview.openshift.io/, it is not possible to create a space anymore.

I reproduced it from the website, and by calling the api endpoint as well.

```
{"errors":[{"code":"internal_error","detail":"pq: null value in column \"space_template_id\" violates not-null constraint","status":"500","title":"Internal error"}]}
```

```
curl 'https://api.prod-preview.openshift.io/api/spaces' -H 'Pragma: no-cache' -H 'Origin: https://prod-preview.openshift.io' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' -H 'Authorization: Bearer <token>' -H 'Content-Type: application/json' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36' -H 'Connection: keep-alive' -H 'Referer: https://prod-preview.openshift.io/_home' -H 'X-Request-Id: 3da301d4-4791-4bfc-b0c1-274f2c554f5f' --data-binary '{"data":{"name":"test-space","path":"","attributes":{"name":"test-space"},"type":"spaces","privateSpace":false,"relationships":{"areas":{"links":{"related":""}},"iterations":{"links":{"related":""}},"workitemtypegroups":{"links":{"related":""}},"owned-by":{"data":{"id":"66011e5d-ffe7-4e42-b792-62ef557900ef","type":"identities"}}}}}' --compressed
```

**Comment by ia3andy** [comment] 2018-04-23 09:28
maybe related to: https://github.com/openshiftio/openshift.io/issues/3191

**Comment by rgarg1** [comment] 2018-04-23 10:15
@ia3andy This is a backend issue and @kwk is working on this.

**Comment by ia3andy** [comment] 2018-04-23 12:54
@kwk it seems to be fixed on https://prod-preview.openshift.io/?

**Comment by kwk** [comment] 2018-04-23 14:33
> @kwk it seems to be fixed on https://prod-preview.openshift.io/?

@ia3andy as of https://github.com/fabric8-services/fabric8-wit/pull/2035 this should be fixed.

**Comment by rgarg1** [comment] 2018-04-24 06:28
@ia3andy The issue is fixed in prod-preview. Closing this.

**Closed by rgarg1** 2018-04-24 06:28 UTC
Labels: SEV2-high, area/planner, env/prod-preview, priority/P0, team/planner, type/bug
