### ISSUE TITLE
Deploy new version of tenant Jenkins

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#3753] opened 2018-06-08 18:10 UTC
Need to perform tenant wide Jenkins update

Jenkins version to update: 4.0.84

**Comment by joshuawilson** [comment] 2018-06-08 23:09
cc @aslakknutsen

**Comment by joshuawilson** [comment] 2018-06-08 23:10
duplicate of #3752

**Closed by joshuawilson** 2018-06-08 23:10 UTC
Labels: team/platform, type/task
