### ISSUE TITLE
Space dashboard - work items from different spaces are shown

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4381] opened 2018-10-03 13:27 UTC
##### Issue Overview

When I open space dashboard for any space, I can see all my assigned work items even from different spaces. 

##### Expected Behaviour
I should see only work items that are assigned to me AND belong to the current space. 
##### Current Behaviour
I can see also work items from different spaces. 
##### Steps To Reproduce

1. Create space A
2. Create work item A in space A
3. Create space B
4. Open space dashboard of space B
RESULT: You can see work item A

**Comment by aptmac** [comment] 2018-10-03 13:38
This appears to have been introduced in https://github.com/fabric8-ui/fabric8-ui/pull/3282, and is discussed a bit in a couple places [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/3282#issuecomment-416226814) [[1]](https://github.com/openshiftio/openshift.io/issues/4283#issuecomment-420698369)

[0] https://github.com/fabric8-ui/fabric8-ui/pull/3282#issuecomment-416226814
[1] https://github.com/openshiftio/openshift.io/issues/4283#issuecomment-420698369

**Comment by ljelinkova** [comment] 2018-10-04 08:48
Thanks, I've looked into the code and noticed that you filter closed work items on client side. Is that necessary?  Is it possible to retrieve only open issues from work item service?

**Comment by Veethika** [comment] 2018-10-08 06:35
@ljelinkova @nimishamukherjee @divyanshiGupta 
Users should only be able to see the work-items from the same space when they are on the dashboard of that particular work-item. Is this an implementation bug?
Removing area/UX tag from here.

**Comment by ppitonak** [comment] 2018-10-08 09:43
@Veethika would it be possible to keep `area/UX` label for future reporting?

**Comment by Veethika** [comment] 2018-10-08 09:49
@muruGanesan can you check the relevance of having a UX tag on this issue?

**Comment by ppitonak** [comment] 2018-10-08 10:11
@Veethika @muruGanesan I would like to know what is the meaning of this label? Is it "a usability issue" or "an issue that UX team needs to do something about"?

**Comment by Veethika** [comment] 2018-10-08 11:30
@ppitonak this means that the UX team is answerable to the resolution of this issue.
I'm trying to verify the same from @muruGanesan

**Comment by joshuawilson** [comment] 2018-10-08 20:38
`area/UX` = the bug is a design issue
`team/UX` = the UX team has responsiblity for the fix

If you are on the Account Home then you should see all your work items but if you are in a space then you should see only the work items in that space.

**Comment by joshuawilson** [comment] 2018-10-08 20:41
@ljelinkova how does this impact the e2e tests?

**Comment by muruGanesan** [comment] 2018-10-09 07:11
@joshuawilson, thanks! 
@ppitonak,  
This issue is an implementation issue rather UX  - that's the reason we asked to remove UX label.
Moreover, any defect that affects 'general flow or expected outcome' touches the end-user experience.

**Comment by ljelinkova** [comment] 2018-10-09 09:43
@joshuawilson The tests currently do not create any work items but they do check if the number of work items on the dashboard is 0. So if you ever run tests with user that has already any work item, the tests will fail. 

This is problem especially with combination with this other issue because the work items from removed spaces are not deleted and kept forever. 
https://github.com/openshiftio/openshift.io/issues/4382

**Comment by joshuawilson** [comment] 2018-10-09 14:03
If I have my feature flag setting at Released then the Space dashboard has NO workitem widget. There is only Pipelines, Codebases, Stack Report Recommendations, and Applications. 

However, if I am not on released then there is a summary workitems widgets on the space page but it only shows total numbers and a chart.

On the Account Home page there is a list of `My Work Items`. This list should show all of a users work items across all the spaces they have work items assigned to them. (note: there is currently a bug in this and it only shows the work items from the last space you visted)

**Comment by joshuawilson** [comment] 2018-10-09 14:14
Do the e2e tests fail on this when run by the server? I can see how they might if run locally by a dev that has some work items.

**Comment by aptmac** [comment] 2018-10-09 14:33
> If I have my feature flag setting at Released then the Space dashboard has NO workitem widget. There is only Pipelines, Codebases, Stack Report Recommendations, and Applications.

Ah, I believe this present at the `beta` level. The WI widget at the >`beta` level is what you describe as the summary of work items. 

> On the Account Home page there is a list of `My Work Items`. This list should show all of a users work items across all the spaces they have work items assigned to them. (note: there is currently a bug in this and it only shows the work items from the last space you visted)

I'm not sure this is a "bug", it's more of a side-effect (see discussion at [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/2966#discussion_r199374971)) .. in the sense that it may be unexpected behaviour but this is the way it's currently implemented. There was a lack of API to retrieve work items that belonged to a user, but the issue for that appears to have been completed `https://github.com/openshiftio/openshift.io/issues/3760`. Off the top of my head, I recall the implementation basically fetching the `recent` spaces from the `SpacesService`, and iterating until it finds a space with work items and then sets the widget to display that space's work items. 

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2966#discussion_r199374971
[1] https://github.com/openshiftio/openshift.io/issues/3760

**Comment by joshuawilson** [comment] 2018-10-09 19:41
Indeed, it is on `beta` but not `Experimental`, I did not realized that it was removed in the latest. (That is really rather odd that it was kept in `beta` while being removed in the latest.

As for the `Home` dashboard, so it is doing the best we can at the moment. Thanks for clearing that up.

**Comment by divyanshiGupta** [comment] 2018-10-10 08:48
@ljelinkova I cannot reproduce this issue in prod. I see a list of `My Work Items` on my space dashboard and I can filter the list by my spaces. Can you attach a gif of the steps that you mentioned above in the issue description? That might help me in reproducing the issue.

**Comment by ppitonak** [comment] 2018-10-10 09:48
@divyanshiGupta switch your account to Beta features

1. login
2. click top-right menu -> Settings -> Features Opt-in -> Beta
3. follow instruction in the original post

**Comment by divyanshiGupta** [comment] 2018-10-10 09:53
@ppitonak yes now the issue is reproducible, thanks.

**Comment by kwk** [comment] 2018-10-10 13:33
Is there someone from UI here that can tell me what call is being made to the backend in order to get the list of work items? Maybe the dashboard is just missing the space ID from filtering out the work items from other spaces.

I'm marking this as a P1 as discussed in today's integration Cabal.

**Comment by aptmac** [comment] 2018-10-10 15:13
> Is there someone from UI here that can tell me what call is being made to the backend in order to get the list of work items?

The work item components go through the `f8-planner`'s `work-item-service` [[0]](https://github.com/fabric8-ui/fabric8-planner/blob/master/src/app/services/work-item.service.ts) in tandem with the `filter-service` [[1]](https://github.com/fabric8-ui/fabric8-planner/blob/master/src/app/services/filter.service.ts). As previously mentioned, these issues started appearing after the upgrade to use the new `work-item-service` in [[2]](https://github.com/fabric8-ui/fabric8-ui/pull/3282).

> Maybe the dashboard is just missing the space ID from filtering out the work items from other spaces.

Correct, it appears that the spaces dashboard work item component is not using the space id in the filter, and this could be problematic. However, even in a component (profile) where a filter combines `assignee` and `space` queries the work items are not correctly displayed, see [[3]](https://github.com/openshiftio/openshift.io/issues/4273)

[0] https://github.com/fabric8-ui/fabric8-planner/blob/master/src/app/services/work-item.service.ts
[1] https://github.com/fabric8-ui/fabric8-planner/blob/master/src/app/services/filter.service.ts
[2] https://github.com/fabric8-ui/fabric8-ui/pull/3282
[3] https://github.com/openshiftio/openshift.io/issues/4273

**Comment by divyanshiGupta** [comment] 2018-10-10 15:29
@kwk @aptmac I am raising a PR to solve this issue. As pointed by @aptmac the query to get workitem was not including space id in it.

**Comment by joshuawilson** [comment] 2018-10-10 15:34
I would also like to know why this beta feature is not in experimental. @corinnekrych is this working correctly?

**Comment by aptmac** [comment] 2018-10-10 15:43
There's a bit of an explanation in an old issue regarding the work items component [[0]](https://github.com/openshiftio/openshift.io/issues/3398#issue-319310963):

> The "my work items" card is hidden when feature flags are set to production. This is because the work items card is tied to Planner, which is only shown with beta features.

Experimental uses the newer bar-chart-style component that was brought about with the dashboard revamp [[1]](https://github.com/fabric8-ui/fabric8-ui/pull/2740).

[0] https://github.com/openshiftio/openshift.io/issues/3398#issue-319310963
[1] https://github.com/fabric8-ui/fabric8-ui/pull/2740

**Comment by kwk** [comment] 2018-10-10 15:46
> Correct, it appears that the spaces dashboard work item component is not using the space id in the filter, and this could be problematic.

@aptmac I can see [this](https://github.com/fabric8-ui/fabric8-ui/pull/3282/files#diff-bd118359678af91fa2785b976c6e1932R83): 

```ts
        return this.workItemService.getWorkItems(
          100000, {expression: {'space': `${space.id}`}}
        );
```

Isn't that respecting the space id?

**Comment by divyanshiGupta** [comment] 2018-10-10 15:49
@kwk That is not the file actually. We have at least 4 work item widgets as far as i know in fabric8-ui. The correct one related to this issue is - https://github.com/fabric8-ui/fabric8-ui/pull/3282/files#diff-dfb7f05ddaac7e0dc9e6c3cd45914706R37

**Comment by aptmac** [comment] 2018-10-10 15:51
> > Correct, it appears that the spaces dashboard work item component is not using the space id in the filter, and this could be problematic.
> 
> @aptmac I can see [this](https://github.com/fabric8-ui/fabric8-ui/pull/3282/files#diff-bd118359678af91fa2785b976c6e1932R83):
> 
> ```ts
>         return this.workItemService.getWorkItems(
>           100000, {expression: {'space': `${space.id}`}}
>         );
> ```
> 
> Isn't that respecting the space id?

Yes, but that's for the component observed at the experimental level.

**Comment by kwk** [comment] 2018-10-10 15:51
@divyanshiGupta can you please boil down this whole typescript code into the HTTP call that is issued to the backend? I'm sure that we have working filtering capabilities in the backend and you're just not using it correctly.

**Comment by kwk** [comment] 2018-10-10 15:52
@divyanshiGupta the URL is enough for me, I don't need the headers and so forth.

**Comment by divyanshiGupta** [comment] 2018-10-10 16:00
@kwk Yes, we do have working filtering capabilities in the backend since other work item widgets in home and profile page which do filter work items based on space and user id. The issue here is UI was not sending space id in the query filter which is what i am adding in my PR.

This issue https://github.com/openshiftio/openshift.io/issues/4273 is different which we need to look at later.

**Comment by alexeykazakov** [comment] 2018-10-10 19:58
I've removed team/platform and added team/planner labels because the bug was introduced by Planner contribution and the planner team is working on fixing it. The platform team can help if needed.

**Closed** 2018-10-12 15:55 UTC
Labels: SEV3-medium, area/e2e-tests, area/planner, area/work-item-tracker, priority/P1, team/planner, type/bug
