### ISSUE TITLE
Unable to progress in the quickstart UI

### ISSUE THREAD

**Issue by rawlingsj** [openshiftio/openshift.io#1517] opened 2017-12-06 16:30 UTC
I don't seem to be able to create a quickstart, I'm stuck on the pipeline page.  There's am error in the java script console.
```
patternfly.min.css:1 ERROR TypeError: Cannot set property 'value' of undefined
    at PipelineQuickstartStepComponent.ngOnInit (fabric8-ui-global-overrides.less:2)
    at checkAndUpdateDirectiveInline (patternfly.min.css:1)
    at checkAndUpdateNodeInline (patternfly.min.css:1)
    at checkAndUpdateNode (patternfly.min.css:1)
    at prodCheckAndUpdateNode (patternfly.min.css:1)
    at Object.eval [as updateDirectives] (ForgeQuickstartComponent.ngfactory.js:62)
    at Object.updateDirectives (patternfly.min.css:1)
    at checkAndUpdateView (patternfly.min.css:1)
    at callViewAction (patternfly.min.css:1)
    at execEmbeddedViewsAction (patternfly.min.css:1)
defaultErrorLogger @ patternfly.min.css:1
patternfly.min.css:1 ERROR TypeError: Cannot set property 'label' of undefined
    at BuildConfigStepComponent.ngOnInit (fabric8-ui-global-overrides.less:2)
    at checkAndUpdateDirectiveInline (patternfly.min.css:1)
    at checkAndUpdateNodeInline (patternfly.min.css:1)
    at checkAndUpdateNode (patternfly.min.css:1)
    at prodCheckAndUpdateNode (patternfly.min.css:1)
    at Object.eval [as updateDirectives] (ForgeQuickstartComponent.ngfactory.js:75)
    at Object.updateDirectives (patternfly.min.css:1)
    at checkAndUpdateView (patternfly.min.css:1)
    at callViewAction (patternfly.min.css:1)
    at execEmbeddedViewsAction (patternfly.min.css:1)
defaultErrorLogger @ patternfly.min.css:1
patternfly.min.css:1 ERROR TypeError: Cannot read property 'disable' of undefined
    at SingleInputComponent.ngOnInit (fabric8-ui-global-overrides.less:2)
    at checkAndUpdateDirectiveInline (patternfly.min.css:1)
    at checkAndUpdateNodeInline (patternfly.min.css:1)
    at checkAndUpdateNode (patternfly.min.css:1)
    at prodCheckAndUpdateNode (patternfly.min.css:1)
    at Object.eval [as updateDirectives] (BuildConfigStepComponent.ngfactory.js:35)
    at Object.updateDirectives (patternfly.min.css:1)
    at checkAndUpdateView (patternfly.min.css:1)
    at callViewAction (patternfly.min.css:1)
    at execEmbeddedViewsAction (patternfly.min.css:1)
defaultErrorLogger @ patternfly.min.css:1
15patternfly.min.css:1 ERROR TypeError: Cannot read property 'valueType' of undefined
    at Object.View_SingleInputComponent_0._co [as updateDirectives] (SingleInputComponent.ngfactory.js:262)
    at Object.updateDirectives (patternfly.min.css:1)
    at checkAndUpdateView (patternfly.min.css:1)
    at callViewAction (patternfly.min.css:1)
    at execComponentViewsAction (patternfly.min.css:1)
    at checkAndUpdateView (patternfly.min.css:1)
    at callViewAction (patternfly.min.css:1)
    at execEmbeddedViewsAction (patternfly.min.css:1)
    at checkAndUpdateView (patternfly.min.css:1)
    at callViewAction (patternfly.min.css:1)
defaultErrorLogger @ patternfly.min.css:1

```

**Comment by rawlingsj** [comment] 2017-12-06 16:31
@corinnekrych @gastaldi does this mean anything to you two?

**Comment by gastaldi** [comment] 2017-12-06 16:32
Production or Staging?

**Comment by rawlingsj** [comment] 2017-12-06 16:32
Prod

**Comment by gastaldi** [comment] 2017-12-06 16:33
I see this error in the backend pod logs: 

```



Caused by: io.fabric8.forge.generator.keycloak.KeyCloakFailureException: KeyCloak returned an invalid token. Are you sure you are logged in?
  | at io.fabric8.forge.generator.git.GitAccount.loadFromSaaS(GitAccount.java:71)
  | at io.fabric8.forge.generator.github.AbstractGitHubStep.createGitHubFacade(AbstractGitHubStep.java:56)
  | at io.fabric8.forge.generator.quickstart.Fabric8ProjectInfoStep.initializeUI(Fabric8ProjectInfoStep.java:104)
  | at sun.reflect.GeneratedMethodAccessor423.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
  | at io.fabric8.forge.generator.quickstart.Fabric8ProjectInfoStep_$$_javassist_a4ed5aa4-f1f7-4e6a-b505-59c287b84a6e.initializeUI(Fabric8ProjectInfoStep_$$_javassist_a4ed5aa4-f1f7-4e6a-b505-59c287b84a6e.java)
  | at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.initialize(WizardCommandControllerImpl.java:121)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
  | ... 64 more
  | Caused by: com.auth0.jwt.exceptions.JWTDecodeException: The token was expected to have 3 parts, but got 1.
  | at com.auth0.jwt.TokenUtils.splitToken(TokenUtils.java:21)
  | at com.auth0.jwt.JWTDecoder.parseToken(JWTDecoder.java:33)
  | at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:29)
  | at com.auth0.jwt.JWT.decode(JWT.java:21)
  | at io.fabric8.forge.generator.git.GitAccount.loadFromSaaS(GitAccount.java:69)
 

```

**Comment by gastaldi** [comment] 2017-12-06 16:35
@alexeykazakov This seems related to https://github.com/openshiftio/openshift.io/issues/1513. Is there anything wrong with the auth service?

**Comment by joshuawilson** [comment] 2017-12-06 16:39
I just tried this and was able to build a new app. 
@rawlingsj did you change any of the defaults?

**Comment by rawlingsj** [comment] 2017-12-06 16:49
I had a custom jenkins tenant but this is before getting to any of that as this is in the wizard.  I've reset my environment just now and get the same error just for completeness.

**Comment by joshuawilson** [comment] 2017-12-06 18:29
I reset and it works. Can you please try incognito mode.

**Comment by ldimaggi** [comment] 2017-12-06 19:26
What's in the Jenkins pod log? Are there any errors?

**Comment by alexeykazakov** [comment] 2017-12-06 23:28
`Caused by: com.auth0.jwt.exceptions.JWTDecodeException: The token was expected to have 3 parts, but got 1.`
What token is it? Don't see any calls to Auth in this stack trace.

**Comment by qodfathr** [comment] 2018-01-22 15:18
@joshuawilson @alexeykazakov this seems okay to close, but want to get your opinions.

**Comment by ldimaggi** [comment] 2018-01-22 15:20
I'd vote to close this one - I am creating new apps/quickstarts every day without seeing this issue.

**Comment by gastaldi** [comment] 2018-01-22 15:21
Closing as requested.

**Closed by gastaldi** 2018-01-22 15:21 UTC
Labels: SEV2-high, area/app-wizard, status/info-needed, team/analytics/wizard, team/launcher, type/bug
