### ISSUE TITLE
[Planner]Drag'n'drop of a task from the list to the iteration list is creating a ghost "iteration"

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1208] opened 2017-10-24 17:27 UTC
![image](https://user-images.githubusercontent.com/1105127/31958233-6193e82a-b8f1-11e7-988f-47ab6932209e.png)

if DnD aaa on "First iteration":

![image](https://user-images.githubusercontent.com/1105127/31958228-5af1dee6-b8f1-11e7-9b4f-be6b6704ed0e.png)

https://drive.google.com/open?id=0B-rING_Zzzcea2RNcnZGb0h6TW8

**Comment by qodfathr** [comment] 2018-01-22 21:30
We've had to sacrifice drag-and-drop for the time being with the new design. Closing (since it's no longer reproducible as it is no longer even doable). If this returns when drag-and-drop returns, feel free to reopen or file a new issue.

**Closed by qodfathr** 2018-01-22 21:30 UTC
Labels: SEV3-medium, area/planner, team/planner, type/bug
