### ISSUE TITLE
Nothing shows in pipeline tab even though it's already created and executed in jenkins.

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#221] opened 2017-06-12 08:24 UTC
Nothing shows in pipeline tab even though I created pipeline during creating codebases and details codebases including jenkins pipeline configuration is here.
https://github.com/danieloh30/daniel-agile-project

![screenshot from 2017-06-12 17-24-29](https://user-images.githubusercontent.com/14066977/27025050-040aae76-4f94-11e7-91f6-3533fb4a444d.png)

**Comment by joshuawilson** [comment] 2017-06-12 21:00
@danieloh30 can you please walk through exactly what you did to try and create a pipeline.

**Comment by danieloh30** [comment] 2017-06-13 05:10
I tried to create a brand new space with vert.x codes via agile template then here is my choice for quick pipeline. Let me know more details how I create the space with codes, pipeline, etc.

![screenshot from 2017-06-13 14-08-46](https://user-images.githubusercontent.com/14066977/27066856-0125ecb2-5042-11e7-82a8-c0698b5e15bf.png)

**Comment by joshuawilson** [comment] 2017-06-13 14:48
There are several things to try. First let's update your tenant profile.
Go to the Profile page and select the "Update Profile" button, then at the bottom of the page select the "update tenant" button. Please note, the button does not yet provide feedback that it did anything. Wait about 2 minutes and try again.

**Comment by jstrachan** [comment] 2017-06-14 08:35
Pipelines are filtered by the space you are in. From the screenshots it looks like you have 2 spaces, `daniel-pipeline` space and `daniel-agile-project` space. 

My guess is that the pipeline got created in one space and you're viewing the pipelines from the other space .

Try viewing all your spaces and switching between them?

**Comment by danieloh30** [comment] 2017-06-14 08:45
I have no data of pipeline on both of spaces[1][2].

[1]daniel-pipelint
![screenshot from 2017-06-14 17-42-48](https://user-images.githubusercontent.com/14066977/27123530-1f2b0c3c-5129-11e7-8a81-59f76b145d10.png)

[2]daniel-agile-project
![screenshot from 2017-06-14 17-43-17](https://user-images.githubusercontent.com/14066977/27123563-3bd40514-5129-11e7-8737-32657e2e5407.png)

Any ideas?

**Comment by RanjithRV** [comment] 2018-01-10 06:37
@chmouel @pradeepto assigned this bug to build team. Not sure if this is still an issue so classified it as an Sev3. Please update as you see it appropriate

**Comment by piyush1594** [comment] 2018-06-21 06:48
@RanjithRV @joshuawilson @danieloh30 I think this is not an issue right now. Can you please confirm and close?

**Comment by joshuawilson** [comment] 2018-06-22 02:38
Closing as not reproducible.

**Closed by joshuawilson** 2018-06-22 02:38 UTC
Labels: SEV3-medium, team/build-cd, type/bug
