### ISSUE TITLE
Planner: Confirmation dialog is towards the top of page instead of page center

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1594] opened 2017-12-08 19:48 UTC
Type: Enhancement

The Confirmation dialog (eg. for delete comment) appears towards the top of the page. This can be moved to the marked area for better accessibility.
![planner-confirmationdialog-position](https://user-images.githubusercontent.com/6318164/33782455-d26abc26-dc7e-11e7-9c59-6c002dc87332.png)

Team: Planner, UX

**Comment by sbose78** [comment] 2017-12-11 07:35
Hi @nimishamukherjee @sanbornsen is this as per design , or should we have a UX review on this ?

**Comment by nimishamukherjee** [comment] 2017-12-11 08:38
@sbose78 @aditya-konarde we have used Patternfly modal - http://www.patternfly.org/pattern-library/widgets/#modal

This is as per design.

**Comment by qodfathr** [comment] 2018-01-26 16:40
Closing as By Design

**Closed by qodfathr** 2018-01-26 16:40 UTC
Labels: area/UX, area/planner, team/planner, team/ux, type/question
