### ISSUE TITLE
Bug: Stack reports are not accessible

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#377] opened 2017-07-20 09:05 UTC
Stack reports are not accessible. Neither from the build pipeline nor the dashboard.

<img width="1597" alt="screen shot 2017-07-20 at 11 02 44" src="https://user-images.githubusercontent.com/53055/28409581-54fc80c4-6d3b-11e7-8dba-9482bf11c442.png">
<img width="1597" alt="screen shot 2017-07-20 at 11 02 58" src="https://user-images.githubusercontent.com/53055/28409580-54fa58f8-6d3b-11e7-8139-0e7689500d4d.png">

**Comment by jyasveer** [comment] 2017-07-24 16:46
The issue is fixed now. 
![image](https://user-images.githubusercontent.com/5430080/28534252-ba487534-70bd-11e7-86c2-8366b59153bb.png)

**Closed** 2017-07-24 17:22 UTC
Labels: area/analytics, kind/bug, team/analytics
