### ISSUE TITLE
Spring-boot 1.5.8.RELEASE components are missing

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1896] opened 2018-01-17 06:55 UTC
The springboot 1.5.8.RELEASE was found to be missing from the production graph which resulted in empty analyzed_dependencies list for Spring Boot quick start applications on OSIO. Here is one example component -

```
{
    "result": [
        {
            "ecosystem": "maven",
            "name": "org.springframework.boot:spring-boot-starter-actuator",
            "version": "1.4.1.RELEASE"
        },
        {
            "ecosystem": "maven",
            "name": "org.springframework.boot:spring-boot-starter-actuator",
            "version": "1.5.1.RELEASE"
        },
        {
            "ecosystem": "maven",
            "name": "org.springframework.boot:spring-boot-starter-actuator",
            "version": "1.3.5.RELEASE"
        },
        {
            "ecosystem": "maven",
            "name": "org.springframework.boot:spring-boot-starter-actuator",
            "version": "1.5.0.RELEASE"
        },
        {
            "ecosystem": "maven",
            "name": "org.springframework.boot:spring-boot-starter-actuator",
            "version": "1.5.2.RELEASE"
        }
    ]
}
```

CC: @msrb @miteshvp

**Comment by msrb** [comment] 2018-01-17 08:07
I see following in the logs:

```
2018-01-17 07:56:40,698 [INFO] GraphImporterTask: Graph import succeeded with response: {
  "count_imported_EPVs": 1, 
  "epv": {
    "package_list": [
      {
        "ecosystem": "maven", 
        "name": "org.springframework.boot:spring-boot-starter-actuator", 
        "version": "1.5.8.RELEASE"
      }
    ], 
    "select_ingest": [
      "dependency_snapshot", 
      "metadata", 
      "security_issues", 
      "digests", 
      "keywords_tagging", 
      "source_licenses"
    ]
  }, 
  "message": "The import finished successfully!"
}
```
```
INFO in rest_api [/src/rest_api.py:88]:
{'epv': {u'select_ingest': [u'dependency_snapshot', u'metadata', u'security_issues', u'digests', u'keywords_tagging', u'source_licenses'], u'package_list': [{u'ecosystem': u'maven', u'version': u'1.5.8.RELEASE', u'name': u'org.springframework.boot:spring-boot-starter-actuator'}]}, 'message': 'The import finished successfully!', 'count_imported_EPVs': 1}
```

and:

```
2018-01-17 07:57:37,528 [INFO] GraphImporterTask: Graph import succeeded with response: {
  "count_imported_EPVs": 1, 
  "epv": {
    "package_list": [
      {
        "ecosystem": "maven", 
        "name": "org.springframework.boot:spring-boot-starter-actuator", 
        "version": ""
      }
    ], 
    "select_ingest": [
      "keywords_tagging", 
      "libraries_io"
    ]
  }, 
  "message": "The import finished successfully!"
}
```
```
INFO in rest_api [/src/rest_api.py:88]:
{'epv': {u'select_ingest': [u'keywords_tagging', u'libraries_io'], u'package_list': [{u'ecosystem': u'maven', u'version': '', u'name': u'org.springframework.boot:spring-boot-starter-actuator'}]}, 'message': 'The import finished successfully!', 'count_imported_EPVs': 1}
```

But API still thinks there is no data:
```
$ curl -H "Authorization: Bearer $OSIO_TOKEN" https://recommender.api.openshift.io/api/v1/component-analyses/maven/org.springframework.boot:spring-boot-starter-actuator/1.5.8.RELEASE
{
  "error": "No data found for maven package org.springframework.boot:spring-boot-starter-actuator/1.5.8.RELEASE"
}

```

Looks like Gremlin issue(?) cc @miteshvp

**Comment by miteshvp** [comment] 2018-01-17 09:19
I checked the entry in our graph and it looks perfectly ok there. Maybe, we need to debug `<component-analyses>` endpoint further.
cc @samuzzal-choudhury @msrb

**Comment by samuzzal-choudhury** [comment] 2018-01-17 09:37
@miteshvp the output pasted above is from `/component-search` endpoint.

**Comment by msrb** [comment] 2018-01-17 09:38
@samuzzal-choudhury but shouldn't `/component-analyses` endpoint return the data if they are in graph?

**Comment by samuzzal-choudhury** [comment] 2018-01-17 09:39
@msrb it should and it does :-) if we're not making a mistake. `component-search` was a subsequent verification for the existence of the component in graph.

**Comment by miteshvp** [comment] 2018-01-17 09:41
I guess, the edge from Package Node to Version Node is missing here
I am debugging the data importer further.

**Comment by samuzzal-choudhury** [comment] 2018-01-17 09:41
@miteshvp can you please share the output of your query on Mattermost?

**Comment by miteshvp** [comment] 2018-01-17 11:05
@samuzzal-choudhury - Please check now. I guess this was due to the fact that the latest changes of data-importer were not promoted to prod due to the Christmas holidays. My bad as it completely slipped out of my mind later. Please close this issue if you see the expected output now.

**Comment by miteshvp** [comment] 2018-01-23 03:45
@samuzzal-choudhury - FWIW, I am not able to reproduce this issue. Closing this. Please re-open if you see otherwise.
Corresponding PR which was raised https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/64 but promoted to prod a bit late https://github.com/openshiftio/saas-analytics/pull/201

**Closed** 2018-01-23 03:47 UTC
Labels: SEV2-high, team/analytics, type/bug
