### ISSUE TITLE
Che Workspace not starting

### ISSUE THREAD

**Issue by cctrieloff** [openshiftio/openshift.io#876] opened 2017-09-18 23:20 UTC
Could not start workspace test4-tlmdi. Reason: Start of environment 'default' failed. Error: Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/cctrieloff-che/deployments. Message: deployments.extensions "che-ws-1rkxmuhwcxi3uqor" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=che-ws-1rkxmuhwcxi3uqor, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions "che-ws-1rkxmuhwcxi3uqor" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).

**Comment by cctrieloff** [comment] 2017-09-18 23:24
Could not start workspace test4-tlmdi. Reason: Start of environment 'default' failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.

**Comment by cctrieloff** [comment] 2017-09-18 23:37
ok, maybe it's the same storage issue...

pods/che-2-deploy
Unable to mount volumes for pod "che-2-deploy_cctrieloff-che(5346fade-9cc9-11e7-8821-02e52a0be43d)": timeout expired waiting for volumes to attach/mount for pod "cctrieloff-che"/"che-2-deploy". list of unattached/unmounted volumes=[deployer-token-4pj3q]
2 minutes ago
Warning
Failed sync
pods/che-2-deploy
Error syncing pod

**Comment by cctrieloff** [comment] 2017-09-18 23:46
Always seems to come back to failed sync...


7:45:28 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Warning | Failed sync | Error syncing pod
-- | -- | -- | -- | -- | --
7:45:27 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Normal | Killing | Killing container with id docker://a1nrk4skyucylnwb-machinedi7afoklqadfp3ex-che-dev-machine:Need to kill Pod2 times in the last minute
7:45:25 PM | che-ws-a1nrk4skyucylnwb | Deployment | Normal | Scaling replica set | Scaled down replica set che-ws-a1nrk4skyucylnwb-1772696450 to 0
7:45:25 PM | che-ws-a1nrk4skyucylnwb-1772696450 | Replica Set | Normal | Successful delete | Deleted pod: che-ws-a1nrk4skyucylnwb-1772696450-s0l7l
7:42:04 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Normal | Created | Created container
7:42:04 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Normal | Started | Started container
7:42:03 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Normal | Pulled | Successfully pulled image "rhche/vertx@sha256:a9e1b050680dd1ead0a8b9ad6687cafcde65995958f0e90d132c180defbf1ff0"
7:41:31 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Normal | Pulling | pulling image "rhche/vertx@sha256:a9e1b050680dd1ead0a8b9ad6687cafcde65995958f0e90d132c180defbf1ff0"
7:41:11 PM | che-ws-a1nrk4skyucylnwb | Deployment | Normal | Scaling replica set | Scaled up replica set che-ws-a1nrk4skyucylnwb-1772696450 to 1
7:41:11 PM | che-ws-a1nrk4skyucylnwb-1772696450 | Replica Set | Normal | Successful create | Created pod: che-ws-a1nrk4skyucylnwb-1772696450-s0l7l
7:41:11 PM | che-ws-a1nrk4skyucylnwb-1772696450-s0l7l | Pod | Normal | Scheduled | Successfully assigned che-ws-a1nrk4skyucylnwb-1772696450-s0l7l to ip-172-31-77-122.us-east-2.compute.internal
7:38:16 PM | che-ws-a1nrk4skyucylnwb-3883151966-pc5v6 | Pod | Warning | Failed sync | Error syncing pod

**Comment by l0rd** [comment] 2017-09-19 02:06
Yes I think it's a duplicate of #501 and related to #666

**Comment by cctrieloff** [comment] 2017-09-19 12:48
I'll retest once we get the storage updates later this week,

**Comment by ldimaggi** [comment] 2017-09-19 20:42
This issue is a duplicate of:   https://github.com/openshiftio/openshift.io/issues/820

**Comment by ldimaggi** [comment] 2017-09-19 20:42
Yup! It's related to - https://github.com/openshiftio/openshift.io/issues/501

**Comment by jfchevrette** [comment] 2017-09-20 13:46
FWIW earlier this week I logged on to the console of my che server and a workspace that was starting up. I was able to validate that the network between the pods is working by running curl against eachother's endpoints. The pods were on different nodes, network between pods was working and the workspace still ended up returning the same errors as reported by OP

**Comment by jfchevrette** [comment] 2017-09-20 13:49
The error seem to indicate that it is trying to create a k8s resource that already exists. I have seen this error come up on a freshly created OSIO account, on the second workspace bringup and onward.

**Comment by joshuawilson** [comment] 2017-09-27 05:06
What is the status on this?

**Comment by l0rd** [comment] 2017-09-27 11:04
Che-server timed out waiting for Che servers to come up (wsagent, terminal and bayesian). From the errors in the OpenShift events it looks like is related to the OSO issues when starting pods attached to a PV (che server, che workspaces but an helloworld too). When these errors arise the pod may take more than 10 minutes to become available. That may explain why Che server times out.

**Comment by l0rd** [comment] 2017-09-27 13:00
I am closing this issue (c.f. previous comment). @cctrieloff feel free to reopen if you are still able to reproduce.

**Closed by l0rd** 2017-09-27 13:00 UTC
Labels: area/che, kind/bug, severity/P1, team/che
