### ISSUE TITLE
Intermittent issue - When viewing a user's profile, workitems and spaces displays are corrupted

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3933] opened 2018-07-06 14:05 UTC
I have not been able to reliable reproduce this issue, but have encountered an issue multiple times in the past few days where when viewing a user's profile, the display of workitems and spaces is corrupted:

![screenshot from 2018-07-05 10-09-44](https://user-images.githubusercontent.com/642621/42383018-040f61ee-8104-11e8-934a-75dc73fbbecb.png)

**Comment by andrewazores** [comment] 2018-07-09 12:49
Dupe of https://github.com/openshiftio/openshift.io/issues/3837 ?

**Comment by aptmac** [comment] 2018-07-09 14:36
The original issue in 3837 (broken components) was a duplicate of https://github.com/openshiftio/openshift.io/issues/3747, and was fixed in https://github.com/fabric8-ui/fabric8-ui/pull/3036. This issue may have a similar cause but *likely* not the same one.

@ldimaggi do you happen to have any more details regarding how you encountered this issue?

**Comment by ldimaggi** [comment] 2018-07-09 19:45
I wish I did - it seemed to be totally random.

**Comment by jiekang** [comment] 2018-07-10 13:22
In the issue screenshot there looks to be no space selected but work items are shown, I'm not sure if that's expected. @aptmac do you know?

**Comment by aptmac** [comment] 2018-07-10 13:41
@jiekang I don't recall having seen that behaviour when viewing my own profile, but perhaps it could be a side-effect of the behaviour displayed by the components in the issue. It is expected (but maybe not intended) that when viewing another user's profile that work items (that belong to you, not them) are shown, and no space is selected from the dropdown.

Example from viewing @jiekang's profile page:
![wi-component](https://user-images.githubusercontent.com/10425301/42513371-bfe88ad0-8424-11e8-8c34-3c8e47c0c55c.png)

**Comment by jiekang** [comment] 2018-07-10 15:12
Strange; I don't see that when viewing my own work items component...

**Comment by rohitkrai03** [comment] 2018-07-11 08:11
@jiekang The default work items that are shown currently are from recent space and the dropdown contains only the spaces created by the user, that may be the reason why there is no space selected in the dropdown when viewing work items from recent space which is not owned by the user.

**Comment by joshuawilson** [comment] 2018-10-30 05:09
It has been months since I've seen it. I'm closing it. Please reopen if you get this again.

**Closed by joshuawilson** 2018-10-30 05:09 UTC
Labels: SEV2-high, area/UI, area/user/profile, issue/intermittent, priority/P4, team/ui, type/bug
