### ISSUE TITLE
Deleted spaces appear in the recently used spaces list

### ISSUE THREAD

**Issue by ap1kenobi** [openshiftio/openshift.io#1280] opened 2017-11-02 20:23 UTC
![image](https://user-images.githubusercontent.com/1463555/32348428-186bb0ec-bfea-11e7-8fd3-0ee476a84b93.png)

**Comment by alexeykazakov** [comment] 2017-11-02 21:16
We need to update the list of recently used spaces when removing a space.

**Comment by joshuawilson** [comment] 2017-11-03 05:33
This is a duplicate of #879, closing.

**Closed by joshuawilson** 2017-11-03 05:33 UTC
Labels: kind/bug, team/platform
