### ISSUE TITLE
when trying to create link it says "null" in label

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3148] opened 2018-04-16 12:26 UTC
clicked create link on #2166 and typed in "status page" and on enter I got 'null -status page' in label.

![2018-04-16_14-25-08](https://user-images.githubusercontent.com/54129/38808890-00cf0a82-4182-11e8-9894-f541c7d06032.png)

**Comment by maxandersen** [comment] 2018-04-16 12:27
note, when doing it the opposite direction I get "undefined" instead.

![2018-04-16_14-27-37](https://user-images.githubusercontent.com/54129/38808993-52b8be10-4182-11e8-8628-15f49bad552e.png)

**Comment by debloper** [comment] 2018-04-18 08:49
Issue with the backend.

[Just verified](https://api.openshift.io/api/search?spaceID=020f756e-b51a-4b43-b113-45cec16b9ce9&q=remove), the response sent for the typeahead lookup does send the WI ID as null/undefined.

```
attributes: {
system.description: "...",
system.description.markup: "Markdown",
system.description.rendered: "...</p> ",
system.number: null, <--- THIS THING
system.order: 2453250,
system.remote_item_id: null, <--- AND THIS THING
system.state: "new",
system.title: "Threaded conversations for Workitem comments [8]",
system.updated_at: null,
version: 11,
},
id: "f74bc611-fd8e-4bc3-8fbe-9e1df5659adf",
```

**Comment by kwk** [comment] 2018-04-24 06:36
@debloper @maxandersen can you please see if the issue is fixed now? @baijum had worked on it.

**Comment by debloper** [comment] 2018-04-24 07:11
Presently don't have access to `prod-preview`. It will help if anyone can provide a link to a Space/WI on `prod-preview` so that I can verify it without having to log in.

**Comment by baijum** [comment] 2018-04-24 07:27
This was the fix: https://github.com/fabric8-services/fabric8-wit/pull/2009

**Comment by kwk** [comment] 2018-04-24 07:35
Closing because two people have verified the fix is working.

**Closed by kwk** 2018-04-24 07:35 UTC
Labels: area/planner, team/planner
