### ISSUE TITLE
Opt-in settings do NOT redirect you back to the last page

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#3296] opened 2018-04-25 02:17 UTC
When I opt-in, I am taken to the page to change my feature flag but I am left there. There is no Save button or option to complete the step. I do not get returned. 

As a new user may not know where they were when they clicked Opt-in, this could be very confusing. 

tracking at: https://openshift.io/openshiftio/Openshift_io/plan/detail/1110

**Comment by catrobson** [comment] 2018-04-25 13:43
@mceledonia can you take a look at this?

**Comment by joshuawilson** [comment] 2018-10-17 17:37
@serenamarie125 is this something that is being considered?

**Comment by muruGanesan** [comment] 2018-10-23 11:31
@joshuawilson, 

1) OSIO > User/profile settings
2) click on "Features Opt-in"
3) Select an option, the user gets a confirmation message about the update. 

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/26006817/47353210-4e9d9e80-d6d9-11e8-902d-398431373e1a.png">

If I understand correctly,
you are expecting to have a button like 'Save/Close/Back/Return" - am I right?

Need clarification on #2950:
I have gone through issue #2950 and I see a button "Return to Feature" 
<img width="782" alt="image" src="https://user-images.githubusercontent.com/26006817/47357461-5d3d8300-d6e4-11e8-8f0b-376be96abfee.png">

Could you please provide some more details on the expected behavior? So that I'll try my best to provide suggestion/recommendation for both the issues 3296 & 2950.

**Comment by joshuawilson** [comment] 2018-10-23 20:31
@muruGanesan try this:

1. set your feature flag setting to `released`
1. Go to the `Home` screen
1. go to a space, with an app, that you created or create a new one
1. go to the Plan page
1. since you are at `released` click the link/button that takes you to the settings and change it to `beta`
    1. [here is the problem, how do I get back to the planner]
1. via the context menu, go to the space you were in
1. go back to the planner

**Comment by serenamarie125** [comment] 2018-11-08 16:45
@Veethika please take this Issue - this is the one about utilizing a modal rather than navigating to view your opt in settings.

**Comment by muruGanesan** [comment] 2018-11-20 03:07
@christianvogt,
Here are my 2 cents:  
1) Loading Beta (unstable) application before 'opt-in' may break the experience 
(For e.g. planner takes a long time to load -or shows 404/500 error) on top, if we are showing 'full screen/modal' won't look nice. (I am looking at a '-ve scenario' where the Beta application fails to load)
It's my point of view, let us hear from Serena.

**Comment by Veethika** [comment] 2018-11-20 16:42
Proposed flow captured in this InVision doc: https://redhat.invisionapp.com/share/YRP2XB6GT23
(This hasn't been reviewed by a visual designer yet so there might be small little inconsistencies in the visual design)

**Comment by christianvogt** [comment] 2018-11-20 17:02
@Veethika this looks good. Your flow aligns with my comment above.

**Comment by christianvogt** [comment] 2018-11-21 15:47
The following was discussed in a call (using planner as an example):
* When the user visits the planner, the URL will update to the planner URL instead of the current beta feature url.
* The page will display an opt-in link and a link to the feature toggle page. Final UXD is still required.
* Clicking the back button at this point will simply return the user back to their previous page in browser history.
* Clicking the opt-in button will immediately enable the feature and the opt-in screen will disappear and the planner will load in place.
* Clicking the back button at this point will again return the user back to their previous page in browser history. Subsequently clicking the forward button will bring the user back to the planner which will be enabled since they chose to opt in.

**Comment by divyanshiGupta** [comment] 2018-11-22 09:08
@Veethika is this https://redhat.invisionapp.com/share/YRP2XB6GT23 the final design doc or some changes still need to be added?

**Comment by Veethika** [comment] 2018-11-26 06:29
@divyanshiGupta this doc doesn't have the final visual design. @sunilmalagi is taking this up and will post the VD doc here soon.

**Comment by divyanshiGupta** [comment] 2018-11-27 11:22
@christianvogt We cannot keep the planner URL when the page changes because when the path is resolved it checks if planner is under a feature flag in `FeatureFlagResolver` and it navigates to the warning page, if not under feature flag or the respective feature flag level is already selected it navigates to planner and the same happens for all the other menu tabs like analyze etc. What can be done is warning page can be modified according to the new design and when the user clicks on opt-in feature the feature level will get selected and the user will be redirected to planner.

**Comment by joshuawilson** [comment] 2018-11-28 15:41
I've added an work item for tracking the engineering work. 
https://openshift.io/openshiftio/Openshift_io/plan/detail/1110

**Comment by divyanshiGupta** [comment] 2018-11-28 15:55
@christianvogt The rendering of planner view happens in a way that when `/plan` is in the route the backlog view gets rendered where the `router-outlet` is placed in the main html file and the same thing happens for the other areas like analyze and create so how do we display the warning page without altering the route?

**Comment by christianvogt** [comment] 2018-11-28 18:51
@divyanshiGupta What I'd like to see is something like this:

```
```

**Comment by joshuawilson** [comment] 2018-11-29 02:01
When you hit the `plan` route it will fetch and load the code. I think that is fine since they wanted to see it anyway. If the user opts out, then they just have a bit of extra in their browser. But the load time happened when they were looking at the opt-in page. So it's fine.

The suggested implementation by @christianvogt fits with what I had in mind. Be aware that the accept button reveals the inner component regardless of what it is called. This needs to stay generic. And the cancel should be a `back` move not a "take me home move".

**Comment by divyanshiGupta** [comment] 2018-11-29 12:48
@christianvogt I tried what you are suggesting but we will have to change it everywhere from route level to component level. And feature-flags are mostly being resolved at a route level. If that sounds okay I can go ahead with this approach.

What I tried to do was to put `<f8-feature-toggle>` in planner list view and when the beta feature flag was not enabled it showed the warning page otherwise it showed planner list view. The problem is it only works when the route has `/plan` and not when the query params were added, once the params are added it shows the planner sub-menu and nothing else is displayed. This is happening because when the sub-menu is rendered at that time params are added in the URL and since the feature-flag is not enabled planner list view is not displayed and the warning page is on `/plan` route and hence it is also not displayed.

But I think we need a better approach so that the solution is generic. If we can somehow manipulate the browser history to remove the feature flag url once the user opts-in and gets redirected to planner, this way the browser history will not get polluted and it will be a one time learning for the user when they see the feature flag url that it is a warning page and they will be redirected back to the page they wish to visit.

**Comment by divyanshiGupta** [comment] 2018-12-10 15:30
@AshishDurgude @Veethika what is the status for the UX of warning page?

**Comment by christianvogt** [comment] 2018-12-10 15:38
@divyanshiGupta can you please post an update on your proposed strategy for addressing this issue now that you've had some time to investigate.

**Comment by divyanshiGupta** [comment] 2018-12-10 16:36
@christianvogt I am not yet 100% sure on any one approach yet since I am yet to find a good generic solution for the URL change problem. I would prefer a modal approach since that would be easier to just have a generic modal that can be accessed from any component @AshishDurgude ^^. I have tried a few things but they didn't turn out to be the best solution. I have a few other ideas that need to be discussed further with the team since it would require a lot of changes to be made specially in planner. I am on PTO most of this week so let's discuss this next week. I will setup a call.

**Comment by AshishDurgude** [comment] 2018-12-11 13:23
@christianvogt @divyanshiGupta @Veethika Here it the Invision link for this issue: https://redhat.invisionapp.com/share/82PBG5XN9S6

**Comment by joshuawilson** [comment] 2018-12-11 13:39
That doesn't have a flow that solves this issue @AshishDurgude. It is just a different page to opt-in. How do you get back after you opt-in?

**Comment by Veethika** [comment] 2018-12-11 13:47
@joshuawilson in the InVision doc @AshishDurgude , users would be able to change the opt-in feature without being redirected to another page. If they choose to go to the opt-in settings page using the secondary action, the flow for coming back would be the same as what we have now.

**Comment by joshuawilson** [comment] 2018-12-11 13:53
That flow is what I reported as the issue. As a new user, I opt-in for Planner (or anything else) and I end up in my profile without knowing how to get back. I then have to find my space and remember that I was trying to get into planner.

**Comment by divyanshiGupta** [comment] 2018-12-11 14:40
@Veethika but what exactly changed since the last Invision doc you posted? The flow Stated in the current doc is same as the previous one. And as @joshuawilson mentioned above, if the user goes to the settings page, and selects a feature flag, either he should be taken directly back to where he was or by clicking on some button like back button. And in above comments I have suggested that it should be a modal since it can be accessed and opened from anywhere and will not need to navigate to some other page.

**Comment by Veethika** [comment] 2018-12-11 14:51
@joshuawilson the major problem identified by us for this issue was - to simply change an opt-in setting to view a feature, the users are directed to the settings page from where it was difficult to navigate back. This solution is an attempt to avoid the redirection to the settings page at all, until necessary. The opt-in setting is space specific and not application specific, so retaining the  Analyze - Plan - Create on the top bar isn't as simple since the space name is selected in the top left dropdown, while in the settings page.
@divyanshiGupta there hasn't been a discussion around the use of modal with the UX team yet
@joshuawilson  @serenamarie125 @christianvogt let's discuss this in the stakeholder's meeting tomorrow

**Comment by joshuawilson** [comment] 2018-12-11 20:14
I didn't realize that you could click on the opt-in button on the design and that linked back to the planner.

**Comment by christianvogt** [comment] 2018-12-12 04:53
@divyanshiGupta earlier I proposed a solution to wrap the component with a feature flag instead of doing it at the route level. I still believe this is the best approach vs a modal. One side effect of this is that the sub nav links for `Backlog`, `Board`', and `Query` will always be visible when on the `plan` page. But I feel that this is an OK compromise (UX can chime in on this).
Keep in mind we're also going to be moving to a new vertical navigation layout soon.

**Comment by divyanshiGupta** [comment] 2019-01-16 06:06
Closing this issue as this is fixed in this PR - https://github.com/fabric8-ui/fabric8-ui/pull/3467

**Closed by divyanshiGupta** 2019-01-16 06:06 UTC
Labels: SEV3-medium, area/UX, area/feature flags, area/navigation, area/settings, priority/P2, team/ui, team/ux, type/bug
