### ISSUE TITLE
Importing existing codebase does not edit space label (I think it should)

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3734] opened 2018-06-04 14:47 UTC
When importing an existing codebase which has previously been imported, the space label is not adjusted leading to problems later down the road as the space does not match. E.g with deployments API we get `could not retrieve space arst: deployment config osio-prod-3 is part of space qwfp, expected space arst`

Steps to reproduce:

1. Create space. Add codebase (vertx booster).
2. Delete space or reset environment. (I reset environment, but in theory deleting the space should work too.
3. Create new space with different name. Import previously added codebase.
4. Wait for build to complete and observe error when visiting deployments page.

The following info is subject to expiry as the repository may not exist in the future:

You can see the commit being done here:

https://github.com/jiekang/osio-prod-3/commits/master

Specifically

https://github.com/jiekang/osio-prod-3/commit/03d0a96fa66971d6a1cd85a77f8a8c1c208b2b67

It looks like there is a mechanism to change the space label, as it was invoked in a previous commit https://github.com/jiekang/osio-prod-3/commit/3f0278c76fb8d065899b6412f0f4429f33262e10, but this mechanism is not triggered in the above scenario.

**Comment by jiekang** [comment] 2018-06-04 14:48
@joshuawilson could you triage this to the right team? Thanks so much!

**Comment by jiekang** [comment] 2018-06-04 14:50
@ebaron I think you investigated this from the Deployments API side before; any ideas?

**Comment by ebaron** [comment] 2018-06-04 15:08
@jiekang I think this is due to the project being initially created using the old launcher. As far as I know, the new launcher does not configure any labels in the project's POM. Because this old configuration is still present, new deployments will still get the label for the old space.

**Comment by jiekang** [comment] 2018-06-04 15:18
Ah okay. That makes sense then thanks! So the resolution sounds like: old launcher projects are incompatible with new launcher system and user needs to manually redo fiddle with his git repository to get it to work? At least for me I can just delete the old repository and create a new one. 

For a user who's not just creating dummy testing repositories, this sounds like quite a serious issue. As openshift.io continues to get used and continues to get updated, upgrade paths and backwards compatibility will **need** to be more seriously considered. I can definitely see issues that follow this same pattern recurring if we aren't vigilant or have systems in place to help us catch this.

**Comment by joshuawilson** [comment] 2018-06-04 19:33
I think there is another issue reporting this but can't find it.

**Comment by ebaron** [comment] 2018-06-04 19:38
This issue is similar: https://github.com/openshiftio/openshift.io/issues/2724

**Comment by animuk** [comment] 2018-06-05 07:42
@jiekang I have followed the steps you mentioned previously in the new app launcher. Could not able to reproduce the error. For me, after deleting space, I could able to import the existing repo in the new space.Deployment also completed without errors.
Like @ebaron mentioned, It might be due to arises from old launcher project.

**Comment by sunilk747** [comment] 2018-06-05 09:32
@animuk @jiekang I followed the above steps but I couldn't reproduce the issue. I guess as @ebaron said it's the problem with the old launcher.

**Comment by jiekang** [comment] 2018-06-05 13:39
For what it's worth, to reproduce you need to acquire a project created with an old launcher. One way is to fork the project I used, then try to reproduce.

https://github.com/jiekang/osio-prod-3

It's just an auto-created vertx booster so it should be safe. I understand if you'd rather not fork it though.

**Comment by jiekang** [comment] 2018-06-05 13:41
@ebaron do you think it makes sense for the new launcher or pipelines or whatever to ignore the space label then?

**Comment by ebaron** [comment] 2018-06-05 14:07
@jiekang We could reduce this to a warning in the deployments API, which where the error you're seeing comes from. How does that sound?

**Comment by ebaron** [comment] 2018-06-05 19:40
It should be fine to treat as a warning, as we have done with the case of a missing space label, at least until the situation involving space labels improves (#2360).

**Comment by jiekang** [comment] 2018-06-06 18:30
@ebaron did you want this issue to remain open for tracking purposes? I'm inclined to close this as it looks like there isn't really a fix for it.

**Comment by ebaron** [comment] 2018-06-06 19:56
@jiekang Let's keep it open, and close it once we change the error in question to a warning.

**Closed** 2018-06-15 20:15 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, status/in-progress, team/analytics, team/analytics/wizard, team/platform, type/bug
