### ISSUE TITLE
Component search does not work on production instance of fabric8-analytics

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1153] opened 2017-10-19 09:19 UTC
From the log it looks like the failure is caused by rejected connection to the DB:

```
[Thu Oct 19 08:58:49.412351 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] --------------------------------------------------------------------------------
[Thu Oct 19 08:58:49.412376 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] INFO in auth [/usr/lib/python3.4/site-packages/bayesian/auth.py:65]:
[Thu Oct 19 08:58:49.412380 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] Successfuly authenticated user None using JWT
[Thu Oct 19 08:58:49.412385 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] --------------------------------------------------------------------------------
[Thu Oct 19 08:58:49.412392 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] 
[Thu Oct 19 08:59:04.010859 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] mod_wsgi (pid=769): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:5000:1000090000/htdocs/api'.
[Thu Oct 19 08:59:04.010938 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] Traceback (most recent call last):
[Thu Oct 19 08:59:04.013300 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[Thu Oct 19 08:59:04.013317 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     chunked=chunked)
[Thu Oct 19 08:59:04.013390 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
[Thu Oct 19 08:59:04.013405 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     six.raise_from(e, None)
[Thu Oct 19 08:59:04.013429 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "<string>", line 2, in raise_from
[Thu Oct 19 08:59:04.013485 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request
[Thu Oct 19 08:59:04.013498 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     httplib_response = conn.getresponse()
[Thu Oct 19 08:59:04.015561 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/http/client.py", line 1227, in getresponse
[Thu Oct 19 08:59:04.015574 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     response.begin()
[Thu Oct 19 08:59:04.015623 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/http/client.py", line 386, in begin
[Thu Oct 19 08:59:04.015635 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     version, status, reason = self._read_status()
[Thu Oct 19 08:59:04.015674 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/http/client.py", line 356, in _read_status
[Thu Oct 19 08:59:04.015683 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise BadStatusLine(line)
[Thu Oct 19 08:59:04.015710 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] http.client.BadStatusLine: ''
[Thu Oct 19 08:59:04.015731 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] 
[Thu Oct 19 08:59:04.015738 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] During handling of the above exception, another exception occurred:
[Thu Oct 19 08:59:04.015740 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] 
[Thu Oct 19 08:59:04.015753 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] Traceback (most recent call last):
[Thu Oct 19 08:59:04.016892 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
[Thu Oct 19 08:59:04.016907 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     timeout=timeout
[Thu Oct 19 08:59:04.016963 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 649, in urlopen
[Thu Oct 19 08:59:04.016973 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     _stacktrace=sys.exc_info()[2])
[Thu Oct 19 08:59:04.017254 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/util/retry.py", line 357, in increment
[Thu Oct 19 08:59:04.017281 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise six.reraise(type(error), error, _stacktrace)
[Thu Oct 19 08:59:04.017780 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/packages/six.py", line 685, in reraise
[Thu Oct 19 08:59:04.017799 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise value.with_traceback(tb)
[Thu Oct 19 08:59:04.017874 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[Thu Oct 19 08:59:04.017883 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     chunked=chunked)
[Thu Oct 19 08:59:04.017929 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
[Thu Oct 19 08:59:04.017934 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     six.raise_from(e, None)
[Thu Oct 19 08:59:04.017952 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "<string>", line 2, in raise_from
[Thu Oct 19 08:59:04.017981 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request
[Thu Oct 19 08:59:04.017984 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     httplib_response = conn.getresponse()
[Thu Oct 19 08:59:04.018006 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/http/client.py", line 1227, in getresponse
[Thu Oct 19 08:59:04.018009 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     response.begin()
[Thu Oct 19 08:59:04.018030 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/http/client.py", line 386, in begin
[Thu Oct 19 08:59:04.018035 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     version, status, reason = self._read_status()
[Thu Oct 19 08:59:04.018057 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/http/client.py", line 356, in _read_status
[Thu Oct 19 08:59:04.018061 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise BadStatusLine(line)
[Thu Oct 19 08:59:04.018123 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
[Thu Oct 19 08:59:04.018137 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] 
[Thu Oct 19 08:59:04.018139 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] During handling of the above exception, another exception occurred:
[Thu Oct 19 08:59:04.018141 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] 
[Thu Oct 19 08:59:04.018147 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] Traceback (most recent call last):
[Thu Oct 19 08:59:04.021466 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/mod_wsgi/server/__init__.py", line 1484, in handle_request
[Thu Oct 19 08:59:04.021481 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return self.application(environ, start_response)
[Thu Oct 19 08:59:04.024851 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 2000, in __call__
[Thu Oct 19 08:59:04.024871 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return self.wsgi_app(environ, start_response)
[Thu Oct 19 08:59:04.024934 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
[Thu Oct 19 08:59:04.024947 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     response = self.make_response(self.handle_exception(e))
[Thu Oct 19 08:59:04.027851 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Oct 19 08:59:04.027868 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return original_handler(e)
[Thu Oct 19 08:59:04.027930 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
[Thu Oct 19 08:59:04.027942 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     reraise(exc_type, exc_value, tb)
[Thu Oct 19 08:59:04.028514 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 32, in reraise
[Thu Oct 19 08:59:04.028527 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise value.with_traceback(tb)
[Thu Oct 19 08:59:04.028570 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
[Thu Oct 19 08:59:04.028582 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     response = self.full_dispatch_request()
[Thu Oct 19 08:59:04.028622 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Thu Oct 19 08:59:04.028630 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     rv = self.handle_user_exception(e)
[Thu Oct 19 08:59:04.028658 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
[Thu Oct 19 08:59:04.028665 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return original_handler(e)
[Thu Oct 19 08:59:04.028690 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
[Thu Oct 19 08:59:04.028696 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     reraise(exc_type, exc_value, tb)
[Thu Oct 19 08:59:04.028720 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 32, in reraise
[Thu Oct 19 08:59:04.028727 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise value.with_traceback(tb)
[Thu Oct 19 08:59:04.028759 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Thu Oct 19 08:59:04.028769 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     rv = self.dispatch_request()
[Thu Oct 19 08:59:04.028815 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
[Thu Oct 19 08:59:04.028826 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Oct 19 08:59:04.028872 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
[Thu Oct 19 08:59:04.028884 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     resp = resource(*args, **kwargs)
[Thu Oct 19 08:59:04.029512 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask/views.py", line 84, in view
[Thu Oct 19 08:59:04.029525 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return self.dispatch_request(*args, **kwargs)
[Thu Oct 19 08:59:04.032136 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/bayesian/api_v1.py", line 206, in dispatch_request
[Thu Oct 19 08:59:04.032152 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     response = super().dispatch_request(*args, **kwargs)
[Thu Oct 19 08:59:04.032201 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
[Thu Oct 19 08:59:04.032213 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     resp = meth(*args, **kwargs)
[Thu Oct 19 08:59:04.032253 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/bayesian/auth.py", line 82, in wrapper
[Thu Oct 19 08:59:04.032261 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return view(*args, **kwargs)
[Thu Oct 19 08:59:04.032289 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/bayesian/api_v1.py", line 243, in get
[Thu Oct 19 08:59:04.032296 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     result = search_packages_from_graph(re.split('\\W+', package))
[Thu Oct 19 08:59:04.033109 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/bayesian/utils.py", line 199, in search_packages_from_graph
[Thu Oct 19 08:59:04.033126 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     response = post(url, data=json.dumps(payload))
[Thu Oct 19 08:59:04.033837 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/requests/api.py", line 112, in post
[Thu Oct 19 08:59:04.033846 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return request('post', url, data=data, json=json, **kwargs)
[Thu Oct 19 08:59:04.033888 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/requests/api.py", line 58, in request
[Thu Oct 19 08:59:04.033891 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     return session.request(method=method, url=url, **kwargs)
[Thu Oct 19 08:59:04.035551 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 502, in request
[Thu Oct 19 08:59:04.035569 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     resp = self.send(prep, **send_kwargs)
[Thu Oct 19 08:59:04.035632 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 612, in send
[Thu Oct 19 08:59:04.035644 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     r = adapter.send(request, **kwargs)
[Thu Oct 19 08:59:04.035692 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]   File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 490, in send
[Thu Oct 19 08:59:04.035704 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074]     raise ConnectionError(err, request=request)
[Thu Oct 19 08:59:04.035747 2017] [wsgi:error] [pid 769:tid 140083512473344] [remote 10.128.10.1:42074] requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
10.128.10.1 - - [19/Oct/2017:08:58:49 +0000] "GET /api/v1/component-search/foobar HTTP/1.1" 500 531 - "python-requests/2.18.4"
```

**Comment by samuzzal-choudhury** [comment] 2017-10-19 16:56
@tisnik I have tried out `/component-search` on prod which worked fine for me. Ex.
`https://recommender.api.openshift.io/api/v1/component-search/vertx-core`

Also, it is indicated that an entire module has failed if a bug is marked as `severity/blocker` which requires an immediate fix. This does not look to me to be case for this issue. Hence, changing the severity to `severity/P2`.

Please feel free to `severity/blocker` by mentioning the proper reason for that.

**Comment by tisnik** [comment] 2017-10-20 09:13
Thanks @samuzzal-choudhury . It seems that the component search started to work 'automagically' (at least from my POV). It would be nice to know the cause of that issue, so we will be able to monitor it.

**Comment by joshuawilson** [comment] 2017-10-20 14:53
There were several fixes that happened in the last 12. You will have to look at the commits to see what applies.

**Comment by samuzzal-choudhury** [comment] 2017-11-06 06:21
@joshuawilson no fixes have been done to address the component-search issue. Could not reproduce this issue on prod when I tried again. So, closing this. @tisnik please reopen if you think otherwise.

**Closed by samuzzal-choudhury** 2017-11-06 06:21 UTC
Labels: kind/bug, severity/P2, stream/core, stream/integration, team/analytics
