### ISSUE TITLE
Review and Confirm can't 'Confirm Subsciption'

### ISSUE THREAD

**Issue by austincunningham** [openshiftio/openshift.io#1211] opened 2017-10-24 23:01 UTC
Clicking on 'Confirm Subscription' renders the same page again

![image](https://user-images.githubusercontent.com/16667688/31971814-70c69940-b915-11e7-9db1-527f2a0b485a.png)

**Comment by alexeykazakov** [comment] 2017-10-24 23:09
It looks like your subscription has been confirmed successfully. What browser are you using? Does it help if you refresh the page?

**Comment by austincunningham** [comment] 2017-10-24 23:11
tried chrome and firefox

**Comment by austincunningham** [comment] 2017-10-24 23:21
The Early Access Program, may not be provisioned yet :)

**Comment by alexeykazakov** [comment] 2017-10-24 23:28
Your account has not been provisioned yet. You are in the waiting list. But you should see the following screen instead:
![oso](https://user-images.githubusercontent.com/620087/31972988-592f8234-b8d8-11e7-8fc9-1b588211f413.png)

Try open https://manage.openshift.com/account/index it should work.

**Comment by alexeykazakov** [comment] 2017-10-24 23:31
I can reproduce:
1. Sing up
2. Confirm subscription
3. Try to sign up again
4. The registration app redirects to the confirm subscription page instead of https://manage.openshift.com/account/index

**Comment by austincunningham** [comment] 2017-10-25 08:34
https://manage.openshift.com/account/index renders correctly

**Comment by pbergene** [comment] 2017-10-25 11:34
I got the welcome email myself for an account I signed up on my private email during summit.  Tried it and got the same result. Screen capture [here](https://sometimes.works/osio/new-user.ogv).  It's not the best user experience or first impression. The first instinct I would have after getting the welcome email from Todd would be to log in :)

**Comment by alexeykazakov** [comment] 2017-10-25 15:31
Fixed. Closing.

**Comment by alexeykazakov** [comment] 2017-10-25 15:36
@austincunningham btw thank you for reporting this issue! :)

**Comment by joshuawilson** [comment] 2017-10-25 17:09
@alexeykazakov is this done?

**Comment by alexeykazakov** [comment] 2017-10-25 17:32
yes.

**Closed by alexeykazakov** 2017-10-25 17:32 UTC
Labels: area/auth, kind/bug, severity/P1, team/auth
