### ISSUE TITLE
Slow mount of PVC for che workspaces - can prevent workspaces from starting.

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#4079] opened 2018-07-26 12:30 UTC
gitlab issue - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2169
Mounting PVC which has lots of files is very slow and it can even prevent che workspaces from starting.

To put it into perspective - It's enough to have 3 workspaces with Angular [1] example to get into the state, where workspaces fail to start.

Right now, this may not be such a big issue (but we had people in the past who were affected by this), but this won't scale in the future... Even if we raise the timeout for workspaces to start, it would be unbearalbe to wait for startup for ~10 minutes or more.

### Steps to reproduce
Basically fill up `claim-che-workspace` PVC with lots of files and try to start workspace - observe that it takes either too long, or fails after ~10 minutes.

OR use "more real world" approach:
- Create workspace from factory: https://che.openshift.io/f?id=factory3db802wkfbg8wox5
This link will spawn up workspace with Angular quickstart and immediately starts build - this generates (downloads) few thousands files.
- Stop that workspace
- Create new workspace with the same (or any other quickstart), do build (a.k.a. generate lots of files)
- Stop the second workspace
- Create third workspace - When I used 2 workspaces with Angular quickstart, this third one fails to start for me.

[1] - Created from factory - https://www.eclipse.org/che/getting-started/cloud-osio/

**Comment by rhopp** [comment] 2018-07-26 12:49
We've also created job, which is monitoring mount times of PVC. This PVC was pre-populated with filex equivalent to two built angular quickstarts (~20000 files if I remember that correctly). @ScrewTSW Could you please provide link to zabbix?

**Comment by ScrewTSW** [comment] 2018-07-26 14:02
Here are the job results with two angular projects installed.

![screenshot from 2018-07-26 15-46-09](https://user-images.githubusercontent.com/16451875/43267069-4446c0b0-90ed-11e8-9df2-f2387e921f9c.png)
![screenshot from 2018-07-26 15-55-59](https://user-images.githubusercontent.com/16451875/43267080-483475dc-90ed-11e8-8149-e88387470348.png)

https://zabbix.devshift.net:9443/zabbix/charts.php?ddreset=1

**Comment by rhopp** [comment] 2018-07-26 14:16
This have one more implication... 

Normally, when workspace is deleted, the `rm-<workspace-name>` pod is spawned. It's purpose is to delete workspace files from the PVC.

But when the PVC has lots of files, the mount fails (or takes longer, then is the timeout for startup of the `rm-` pod) and user is basically stuck in situation when he cannot start any workspace AND he is not able to remove the data from PVC (well.. technically he can deploy some own pod with mounted PVC and delete it manually from terminal, but this will be disabled, when we revoke admin rights from users `-che` namespaces)

WDYT @davidfestal ?

**Comment by slemeur** [comment] 2018-07-29 21:02
@rhopp : https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2169

**Comment by ibuziuk** [comment] 2018-07-30 08:03
@rhopp could you please test how it works on prod-preview where deployments are used instead of bare pods - https://github.com/eclipse/che/pull/10021#issuecomment-401833342  ?

**Comment by rhopp** [comment] 2018-07-30 09:19
@ibuziuk On prod-preview, when the failure happens, it happens with weird message (timeout 0 miliseconds, even though it fails after few minutes):
```
Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Timed out waiting for [0] milliseconds for [Deployment] with name:[workspaceekokh2u0tab43lgn.dockerimage] in namespace [rhopp-preview-che].
```

**Comment by slemeur** [comment] 2018-07-30 09:22
That's the one I hit last week indeed.

![screen shot 2018-07-23 at 13 28 09](https://user-images.githubusercontent.com/1636769/43388986-df9784fa-93ea-11e8-8a99-bdf1ecae12ce.png)

**Comment by sbose78** [comment] 2018-09-14 06:18
Could you please tell me if there's been progress on resolving this?

**Comment by ScrewTSW** [comment] 2018-10-05 13:40
@sbose78 Hello.
I've tested the new update on the free-stg cluster. I really tried to break it, but I was unable to :D
I've mounted a simple pod with the PVC attached, created 30 000 artificial files + 6 large ones besides those that already existed from the workspaces previously run with that account (around 8000 more real files)
I tried mounting the volume and creating new workspaces back and forth and I didn't see any issues with mount or increase in the time it took to mount the volume and start the pod/workspace
The cluster seems to be stable. :+1: for promoting to prod-preview

**Comment by sbose78** [comment] 2018-10-05 14:12
@ScrewTSW Fantastic! Thank you.

> The build is where the factory failed, but that's already a known bug.

yeah, this should be OK.

**Comment by ibuziuk** [comment] 2018-11-05 13:05
@ScrewTSW could you please verify and close this issue if all the starter clusters have been updated and the issue is not reproducible anymore ?

**Comment by ibuziuk** [comment] 2018-11-09 08:30
All starter clusters have been updated this week to openshift 3.11. However, yet another requirement for fixing this slow volume mount issue is having  gluster-subvol driver fix [1] deployed to the prod clusters. I will provide an update here when the fix would be available on prod clusters and qa verification could be done.

[1] https://github.com/gluster/gluster-subvol/pull/24

**Comment by ibuziuk** [comment] 2018-12-12 18:16
@rhopp @ScrewTSW @Katka92 the gluster subvol fix is applied on 1a cluster. Will you be able to verify that volume mount problem is not  reproducible there ?

**Comment by ppitonak** [comment] 2018-12-13 09:21
I  can confirm that e2e tests started passing on this cluster. 12 of 12 runs successful so far.

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-released/
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/

**Comment by ibuziuk** [comment] 2018-12-13 09:47
@ppitonak are we positive that the fact that tests started to pass related to the gluster subvol fix (are those were failing due to slow volume mount) and not fix for https://github.com/openshiftio/openshift.io/issues/4626 ?

**Comment by ppitonak** [comment] 2018-12-13 10:58
I'm not sure but

you commented in this issue on Dec 12, 18:16 UTC
fix for #4626 got into production on Dec 12, 19:13 UTC
first successful build started on Dec 12 18:35 UTC

**Comment by ibuziuk** [comment] 2018-12-13 11:04
@rhopp could someone from QA team with the account provisioned against `1a` make sure that it is not possible to reproduce the problem by following the `steps to reproduce` from the description ?

**Comment by rhopp** [comment] 2018-12-13 16:21
PVC mount issue seems to be fixed on `1a` cluster. Workspace container starts quickly even with lots of files inside.

I've encountered another (not so critical issue) while testing that... I'll report that as separate issue.

**Comment by ibuziuk** [comment] 2018-12-14 14:53
@rhopp closing this issue

**Closed by ibuziuk** 2018-12-14 14:53 UTC
Labels: SEV2-high, area/che, priority/P1, status/pending-qa-verification, team/che/osio, team/service-delivery, type/bug
