### ISSUE TITLE
Confidence score is missing for companion dependency in Stack report UI

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#2167] opened 2018-02-02 13:54 UTC
This is the sample response for two manifest files which have confidence score and also the reasoning.  The issue here is we see the confidence score displayed for one and not for the other manifest file.

Sample response :- https://gist.github.com/spicemit/808df74c2634474afdb180878e9653ec

Also here are the screenshots
<img width="1440" alt="screen shot 2018-02-02 at 7 22 23 pm" src="https://user-images.githubusercontent.com/5430080/35736553-75f875ea-084e-11e8-90f7-db4494129c41.png">
<img width="1440" alt="screen shot 2018-02-02 at 7 22 32 pm" src="https://user-images.githubusercontent.com/5430080/35736555-7628161a-084e-11e8-906f-a29c8b107047.png">

**Comment by jyasveer** [comment] 2018-02-02 13:55
Also we should handle the security card content section, in the case of no data.

**Comment by sara-02** [comment] 2018-02-02 14:08
@jyasveer can you share the effective pom for this request.

**Comment by GeorgeActon** [comment] 2018-02-09 16:35
@sivaavkd  I have assigned a severity for this issue. Review please

**Comment by sivaavkd** [comment] 2018-02-09 19:04
thanks @GeorgeActon 
@jyasveer - can you share eff pom with @sara-02 ?

**Comment by sara-02** [comment] 2018-02-10 08:54
@sivaavkd the Effective Pom has been provided, I am trying to replicate the issue on dev-cluster with additional logs in place, but I am blocked by this issue on Gitlab https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1151, will have to resolve this kronos issue first.

**Comment by miteshvp** [comment] 2018-02-12 02:46
@sara-02 I guess you need to try different strategy rather than being blocked just because your kronos service is not coming up

**Comment by sara-02** [comment] 2018-02-14 15:37
@jyasveer For the same effective pom, I tried running the stack analyses, and it seems to be giving the result as expected.
Stack ID on prod: `35dc6c22d02e4366b22067b289d5abf6`
Result: https://gist.github.com/sara-02/aadf22e9eb460a41bec65848c3ca4bb7

**Comment by sara-02** [comment] 2018-02-14 18:13
Also, I have added a minor fix, to capture this error if it occurs in the future.
https://github.com/fabric8-analytics/fabric8-analytics-server/pull/258

**Comment by jyasveer** [comment] 2018-02-14 18:14
@sara-02 what i remember is , the property `confidence_reason` was missing in one of the companion recommendation dependency object. That is why UI was not showing the confidence score. What i see is we have two fields in the object, one is `confidence_reason` and the other is `cooccurrence_probability`. could you please confirm, which is the right one to use for confidence score display

**Comment by sara-02** [comment] 2018-02-14 18:20
@jyasveer For the confidence score we use `confidence_reason`, the reason statement is generated used the `coccurrence probability`. For now the reason is simplly the number hence both parameters reflect save value, in future if we change the statement, then it will reflect `confidence_reason` field which is shown on the UI. So logically `cooccurrence_probability and `confidence_reason` should have same value, and in case if one is missing, other should be `None` too

**Comment by sara-02** [comment] 2018-02-15 04:27
@jyasveer As I was unable to reproduce it and track the issue, I am closing it. Please reopen if the problem surfaces.

**Closed** 2018-02-15 04:27 UTC
Labels: SEV2-high, area/analytics, team/analytics, type/bug
