### ISSUE TITLE
URL decoding of the content does not seem to be done correctly

### ISSUE THREAD

**Issue by surajssd** [openshiftio/openshift.io#3835] opened 2018-06-20 07:26 UTC
I did a comment on planner with three back ticks and some json content, it does not render as it does on github

here is the screenshot:

![screenshot from 2018-06-20 11-56-58](https://user-images.githubusercontent.com/5815795/41643563-2693555e-7489-11e8-9322-8fb429a4bfa6.png)

And the link to the issue is here: https://openshift.io/openshiftio/openshiftio/plan/detail/2083

**Comment by michaelkleinhenz** [comment] 2018-06-20 10:47
Could be a double encoding on the HTTP encapsulation.

**Comment by jarifibrahim** [comment] 2018-08-18 06:14
Duplicate of https://github.com/openshiftio/openshift.io/issues/4132
Closing since the actual issue has been fixed in https://github.com/openshiftio/openshift.io/issues/4132

**Closed by jarifibrahim** 2018-08-18 06:14 UTC
Labels: SEV2-high, area/planner, priority/P4, team/planner, type/bug

**Comment by surajssd** [comment] 2018-08-20 13:49
@jarifibrahim probably https://github.com/openshiftio/openshift.io/issues/4132 was duplicate of this issue :wink:  It's nice it's fixed :+1:
