### ISSUE TITLE
Error when displaying Deployments tab due to missing space label

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#2360] opened 2018-02-26 13:47 UTC
When I click Deployments tab, I get the following error:

Request failed: 500 (Internal Server Error) {"errors":[{"code":"internal_error","detail":"could not retrieve space My_space: space label missing from deployment config myspace2","status":"500","title":"Internal error"}]} 

Also, the bar saying that I am using experimental feature keeps adding when I change tab and click Deployments again (see the screenshot). 

![screenshot from 2018-02-26 14-38-35](https://user-images.githubusercontent.com/2078072/36673464-2d087f52-1b03-11e8-8f7f-95c6d83a7435.png)

Steps:
- Create new space
- Create and run quickstart (I used Spring Boot HTTP Example)
- Go to Deployments

**Comment by joshuawilson** [comment] 2018-02-26 14:04
I can not reproduce this. Can you log out and log in again, then try the page.

**Comment by ljelinkova** [comment] 2018-02-26 14:13
I tried to log out and in (even different browser) and I am still getting the same error.

**Comment by aptmac** [comment] 2018-02-26 14:41
It looks like this is similar to https://github.com/openshiftio/openshift.io/issues/2268 [0]. @ljelinkova if this is still happening, if you could try to get some more information by following these instructions [1] it would be greatly appreciated: 

From ebaron [1]: If anyone can reproduce this again, could you verify that the DeploymentConfig is missing the space label? You can do this by running `oc -n <namespace> get dc/<app name> -o json`. The space label should be under metadata/labels.

[0] https://github.com/openshiftio/openshift.io/issues/2268
[1] https://github.com/openshiftio/openshift.io/issues/2268#issuecomment-366015065

**Comment by ljelinkova** [comment] 2018-02-26 15:04
This is the content of my metadata/labels

"labels": {
            "app": "myspace2",
            "group": "io.openshift.booster",
            "provider": "fabric8",
            "version": "1.0.1"
        },

**Comment by jiekang** [comment] 2018-02-26 16:28
Thanks for that. It looks like the service that created your application did not apply the right labels to associate it with a space. @joshuawilson any ideas who might know more about this?

**Comment by jiekang** [comment] 2018-02-26 16:30
@ebaron does my explanation make sense to you? Is there anymore info you think would be useful to verify this?

**Comment by jiekang** [comment] 2018-02-26 17:42
@ldimaggi it seems like it. Every so often, an application is created with no 'space' label in Openshift. A working set of labels looks like:
```
        "labels": {
            "app": "prod1",
            "group": "io.openshift.booster",
            "provider": "fabric8",
            "space": "Space1",
            "version": "1.0.1"
        },
```

I say 'working' instead of 'correct' because I don't know if there was any change in how this was done, though I doubt it.

I was able to reproduce this after resetting my environment, creating a new space and using the wizard to create a new Spring Boot - HTTP Example booster.

**Comment by ldimaggi** [comment] 2018-02-26 17:50
Are any errors logged? In the Jenkins build log or Jenkins pod log? Thx!

**Comment by joshuawilson** [comment] 2018-02-26 19:38
cc @gastaldi @l0rd @ibuziuk 
Do you guys know anything about this?

**Comment by gastaldi** [comment] 2018-02-26 19:54
No idea, seems to be something wrong in the tenant space?

**Comment by joshuawilson** [comment] 2018-02-26 19:58
maybe @aslakknutsen or @jfchevrette knows

**Comment by jfchevrette** [comment] 2018-02-26 20:31
Whats responsible for setting the space label on the deployment? My first instinct would be jenkins since it does the deployment to stage/run.

**Comment by jiekang** [comment] 2018-02-26 20:37
@ldimaggi for the Jenkins build/pod I don't see any errors.

However on the successful build it has:

```
Applying DeploymentConfig name: DeploymentConfig data: [...]
labels={app=zxcvrstawft, provider=fabric8, version=1.0.1, group=io.openshift.booster}
```

This suggests the logic is not applying the `space` label. After I reset my environment earlier today, this happens to every application I build.

**Comment by ebaron** [comment] 2018-02-26 20:38
It appears this label is added by fabric8-maven-plugin, whose configuration is modified in GitHub when creating a new OSIO project:  https://github.com/ebaron/myspringboot/commit/230c82431b78b20ce15e06e76be93168c2152ceb

It looks like the code responsible for this is:
https://github.com/fabric8-launcher/launcher-backend/blob/83892044dceea275603fdb882a4b4043761faf9d/addons/osio-addon/src/main/java/io/fabric8/forge/generator/pipeline/ChoosePipelineStep.java#L534

**Comment by ebaron** [comment] 2018-02-26 21:12
Perhaps the label is not being set because the Spring Boot HTTP booster moved the fabric8-maven-plugin configuration to the parent "io.openshift.booster:spring-boot-booster-parent". When the above launcher code tries to edit fabric8-maven-plugin in the POM file, there is nothing to edit.

Compare an old and a new project, both created with the Spring Boot HTTP booster:
Old: https://github.com/ebaron/myspringboot/blob/230c82431b78b20ce15e06e76be93168c2152ceb/pom.xml
New: https://github.com/ebaron/myotherspace/blob/f9b7934e96c5f9de6d21575a1baee61e87b947c0/pom.xml

**Comment by gastaldi** [comment] 2018-02-26 21:19
@ebaron that makes sense. This is the issue to remove the parent POM from the boosters: https://github.com/fabric8-launcher/launcher-planning/issues/10, we need to bring that discussion again with the runtime owners. 

Is there any other way to set that information without using the fabric8-maven-plugin?

**Comment by jiekang** [comment] 2018-02-26 21:21
In the discussion to resolve this it would be nice to consider automated tests that verify these generated files have certain expected values. I suppose this is a cross-team item.

**Comment by gastaldi** [comment] 2018-02-26 21:28
I created a forum topic to discuss about the parent pom.xml structure here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/fabric8-launcher/NTsE8JBzHGw

**Comment by andrewazores** [comment] 2018-02-27 15:27
As a short-term solution, yesterday we discussed having the DeploymentsService continue to log and notify on errors but to then swallow them, rather than re-throw. This would prevent uncaught errors in subscriptions from breaking the page at least. In the future we should continue adding proper specific error handling for various consumers in the Deployments page for various types of errors. Once all code paths have error handlers the DeploymentsService can go back to rethrowing encountered HTTP errors.

@joshuawilson does this sound reasonable? I will prepare a patch if so.

**Comment by joshuawilson** [comment] 2018-02-27 15:36
@andrewazores as long as the error are sent to the global ErrorHandler.

**Comment by ebaron** [comment] 2018-02-27 22:06
@gastaldi Thanks for revisiting the discussion.

This is beyond my expertise, but perhaps a better way to handle the space label would be for the Jenkins pipeline to read the label from its own Build Config and somehow set that on objects it creates.

**Comment by ebaron** [comment] 2018-02-27 22:46
@jiekang @andrewazores If necessary, I can remove the space label check, at least temporarily. What we do right now to get data for a space is:
1. Get all Build Configs with matching space label.
2. For each matching Build Config, check each environment for a Deployment Config with the same name as the Build Config.
3. Test whether the Deployment Config also has the expected space label.

**Comment by ebaron** [comment] 2018-03-07 20:24
@gastaldi Sorry to bother you. Do you know if any decision has been made yet on whether to move the fabric8-maven-plugin invocation from the parent POM back to the boosters themselves?

**Comment by gastaldi** [comment] 2018-03-07 20:34
@ebaron nothing has been discussed so far. Do you mind bumping the thread in https://groups.google.com/forum/#!topic/fabric8-launcher/NTsE8JBzHGw?

**Comment by mishaone** [comment] 2018-03-22 03:55
I saw this today and it baffled me so posting here in case this is related to this issue:
![error](https://user-images.githubusercontent.com/926572/37750402-8229d34a-2dd8-11e8-8aa1-64f8ccf1e369.png)

When I saw this, I was creating three quickstarts using the wizard, each using a different pipeline build option and after the third (which happened to be the springboot HTTP quickstart, if it matters), I started seeing this everytime I loaded the dashboard view or pipelines view.

**Comment by andrewazores** [comment] 2018-03-22 13:45
@mishaone please see https://github.com/openshiftio/openshift.io/issues/2360

**Comment by ppitonak** [comment] 2018-03-22 13:51
@andrewazores maybe you wanted to reference a different issue?

**Comment by andrewazores** [comment] 2018-03-22 13:53
ha, yes, I was looking at the wrong tab. Sorry.

**Comment by ebaron** [comment] 2018-03-23 20:32
I have added a workaround in the Deployments API to log a warning if the space label is missing, instead of returning an error. This should allow the deployments in question to appear as normal in the Deployments page. There is however a small chance that deployments will appear in the wrong space due to this workaround. 

Work on a proper solution involving setting the space label without modifying the user's GitHub repository is ongoing. (see: https://github.com/fabric8io/fabric8-pipeline-library/pull/390)

**Comment by joshuawilson** [comment] 2018-04-24 17:01
@ebaron It looks like you have a fix in place that is more temporary and a permanent one in the works. 

I'm going to reduce this to a SEV3 or you can close it and make a task for the permanent fix. If I misread and there is not temp fix in place, please set back to a SEV2 P0.

**Comment by ebaron** [comment] 2018-04-24 19:12
The temporary fix, which is already in prod, is to treat a missing space label as a warning instead of an error. The worst that can happen with this workaround is we show a deployment belonging to one of the user's other spaces. This could happen in the unlikely scenario that the user has:
* a Build Config named _X_, part of space _A_, in environment _E_, and
* a Deployment Config named _X_, part of space _B_, in environment _E_

**Comment by joshuawilson** [comment] 2018-05-01 12:49
I'm still seeing the 500 errors when I make a new application.

**Comment by ldimaggi** [comment] 2018-05-01 12:57
I'm seeing the 500 error too:

![capture](https://user-images.githubusercontent.com/642621/39473618-ba681d8e-4d1d-11e8-852f-62e80e3a77ba.PNG)

**Comment by ebaron** [comment] 2018-05-01 13:47
@joshuawilson was the error you were seeing the same as @ldimaggi? This is caused by an outage with the Hawkular metrics server. We have an issue open to improve the error message reported when this occurs: https://github.com/openshiftio/openshift.io/issues/2754

**Comment by joshuawilson** [comment] 2018-05-07 15:38
I think it was the same. I'll have to test it again.

**Comment by ebaron** [comment] 2018-06-12 21:17
The proper fix for this bug involves the following PRs:

- [ ] fabric8io/fabric8-pipeline-library#390: Adds capability to mavenCanaryRelease to read the space label from the Build object corresponding to the running job and pass to FMP. (Needs updating once below FMP PR is present in a released version)
- [ ] fabric8io/fabric8-maven-plugin#1252: Adds a new enricher (and OSIO profile) that applies the provided space label to generated OpenShift resources.
- [ ] fabric8-services/fabric8-tenant-jenkins#79: Whitelists a new method used by fabric8io/fabric8-pipeline-library#390

**Comment by sthaha** [comment] 2018-07-17 23:51
@ebaron Are we good to close this issue?

**Comment by ebaron** [comment] 2018-07-18 14:16
@sthaha Yes, this seems to be good now that the remaining PRs have been merged. We will have to revisit this as we add support for additional languages.

**Closed by ebaron** 2018-07-18 14:16 UTC
Labels: SEV3-medium, area/deployments, area/pipelines, area/spaces, sprint/current, team/build-cd, team/platform, type/bug
