### ISSUE TITLE
The getting started guide for openshift.io is not available

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshiftio/openshift.io#1054] opened 2017-10-04 13:51 UTC
The getting started guide for openshift.io is not available , It is giving me a 404 not found error https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide

I was at i.e. https://openshift.io/_home and then clicked on the link  in : Learn how to get [started in the document](https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide).

**Comment by joshuawilson** [comment] 2017-10-11 03:21
Closing as it is a duplicate of #313

**Closed by joshuawilson** 2017-10-11 03:21 UTC
Labels: area/UI, team/docs
