### ISSUE TITLE
initial build is not started

### ISSUE THREAD

**Issue by gorkem** [openshiftio/openshift.io#4534] opened 2018-11-12 03:15 UTC
##### Issue Overview
When a new application is created the initial build is not started, Toolchain UI looks like there is a
build going on but a jenkins build is not really started.

##### Expected Behaviour
A build is started right after the new application wizard is completed. 

##### Steps To Reproduce

1. Create a new space and a new application. I have use Spring Boot with Rest mission
2. Check to see if the build #1 is started.

**Comment by gorkem** [comment] 2018-11-12 20:04
@sunilk747 Did you have time to verify if this is a real issue?

**Comment by piyush-garg** [comment] 2018-11-13 12:57
Closing this issue as we are not able to reproduce this. Please reopen if you see it again. Thanks

cc @sthaha @gorkem

**Closed by piyush-garg** 2018-11-13 12:57 UTC
Labels: SEV2-high, area/pipelines, priority/P2, team/build-cd, type/bug
