### ISSUE TITLE
The notification bubble is not rednered properly.

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#1829] opened 2018-01-10 12:31 UTC
![image](https://user-images.githubusercontent.com/3263627/34773046-8f61cf14-f60a-11e7-80d5-7d17e9b0fac3.png)

## Impacts
- [ ] #2164 Platform Rendering Issues for Heather

**Comment by pmacik** [comment] 2018-01-10 12:40
![image](https://user-images.githubusercontent.com/3263627/34773384-c1454032-f60b-11e7-98bb-af6846ef7b3b.png)

**Comment by ldimaggi** [comment] 2018-01-10 13:14
Pavel - can you confirm that:
* You saw this on https://openshift.io
* And - can you list the precise steps that you took to recreate the problem? Thx!

**Comment by pmacik** [comment] 2018-01-10 13:40
* I saw it in the PR build and prod-preview, not in prod (openshift.io)
 * The steps are:
    * Open Planner
    * Click on Scenarios
    * Fill in new scenario name and click Add
    * Once created a new scenario, the notification is displayed.

**Comment by joshuawilson** [comment] 2018-01-11 04:11
This sounds like an issue with the styles in planner and how they are effecting the notification.
What do you think @mindreeper2420?

**Comment by mindreeper2420** [comment] 2018-01-12 13:03
@joshuawilson looks like there is definitely a conflict between styles. Is Planner pulled in with all of the CSS already compiled, or is it built by the Platform? If there are any overrides in the Planner code, then those will always override Platform, unless specificity is exact.

**Comment by mindreeper2420** [comment] 2018-01-28 16:13
@SMahil you are working on this issue, correct?

**Comment by SMahil** [comment] 2018-01-28 18:15
Yes Adam

**Comment by aptmac** [comment] 2018-02-08 20:11
I think this issue is a duplicate of https://github.com/openshiftio/openshift.io/issues/1798, which was addressed in https://github.com/fabric8-ui/fabric8-ui/pull/2445.

The notification correctly renders when adding a scenario:
![2018-02-08-150831_1581x292_scrot](https://user-images.githubusercontent.com/10425301/35995616-f10d714e-0ce1-11e8-973f-1d5081dacd13.png)

**Comment by ppitonak** [comment] 2018-02-16 12:13
I cannot reproduce it.

**Comment by nimishamukherjee** [comment] 2018-02-28 16:26
Closing issue as it has been resolved.

**Closed by nimishamukherjee** 2018-02-28 16:26 UTC
Labels: SEV3-medium, area/UI, area/notifications, area/planner, team/planner, train/heather, type/bug
