### ISSUE TITLE
Search for my spaces issue

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3857] opened 2018-06-26 04:12 UTC
Steps:
Select My spaces from dropdown

1) Search by space name  'Agile' works
![screenshot from 2018-06-26 09-39-16](https://user-images.githubusercontent.com/34271052/41888810-d6d2c02c-7924-11e8-9930-dd1f465ec5db.png)

2) Search by space name 'new' works
![screenshot from 2018-06-26 09-40-02](https://user-images.githubusercontent.com/34271052/41888829-f9bb3024-7924-11e8-9525-8f22434954c4.png)

3) But if we search by 'Agile' and then "new" 
It shows 0 results 
![screenshot from 2018-06-26 09-41-28](https://user-images.githubusercontent.com/34271052/41888868-2937f1a2-7925-11e8-9350-c7d8c8596fa4.png)

It should show both the results for Agile and new

**Comment by aptmac** [comment] 2018-06-26 13:57
Looking at the Patternfly design explanations for the [Filter [0]](http://www.patternfly.org/pattern-library/forms-and-controls/filter/#design), it looks like this was intentional; the attribute categories aren't being correctly used here. Take a look at the heading "Filter Behavior", the screenshots above correspond to example 1 [0], which details: "Filters between attribute categories should be combined with a boolean AND operator". The filtering being done in the example above isn't `new || agile` (which is what is expected), it's looking for `new && agile`, which correctly returns nothing.

[0] http://www.patternfly.org/pattern-library/forms-and-controls/filter/#design

**Comment by joshuawilson** [comment] 2018-07-10 18:58
might be a Duplicate of #3655

**Comment by aptmac** [comment] 2018-07-10 19:42
@joshuawilson No this one should be different, the wording of the title may be misleading. This particular issue is concerning the way filters are applied when making a search for spaces. Furthermore the behaviour shown in this issue is intentional as implemented in pfng and not a bug [0], but I've re-purposed the PR [1] to ease the strictness of the filters with regards to case sensitivity. 

[0] https://github.com/fabric8-ui/fabric8-ui/pull/3077#issuecomment-401649719
[1] https://github.com/fabric8-ui/fabric8-ui/pull/3077

**Closed** 2018-07-12 20:51 UTC
Labels: SEV3-medium, area/spaces, team/platform, type/bug
