### ISSUE TITLE
Unit tests for the fabric8-analytics-worker repo should be run on CI for each PR

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#2061] opened 2018-01-25 18:03 UTC
ATM only two CI jobs are run for each PR:

1) Pylint
2) docker image build

It would be helpful to run unit tests as well (we already have bunch of them).

@msrb @jpopelka @pkajaba  WDYT?

**Comment by msrb** [comment] 2018-01-29 14:16
Not a bug, we are running the tests in CI. Closing 😉

**Closed by msrb** 2018-01-29 14:16 UTC
Labels: area/analytics, area/architecture/build, area/tests, status/open-for-dev, team/analytics/core, type/task
