### ISSUE TITLE
Huge number of requests to https://recommender.api.openshift.io/api/v1/stack-analyses/<id>

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3380] opened 2018-04-30 15:53 UTC
See image below. This is on visiting a space on production and seen on production feature toggle and internal feature toggle (which actually doesn't currently make a difference because a number of components intended to be seen under a feature toggle are still actually loaded, even if not in the DOM, https://github.com/openshiftio/openshift.io/issues/2908)

![stack-error](https://user-images.githubusercontent.com/5430520/39436692-ba7b6d78-4c6c-11e8-9335-1712da429f14.png)

**Comment by jiekang** [comment] 2018-04-30 15:54
@joshuawilson when you have time, could you triage this to the right team?

**Comment by aptmac** [comment] 2018-05-02 19:52
When running locally, it's also printing to the console[0] every time, and takes about 10 seconds to complete.

![console-flood](https://user-images.githubusercontent.com/10425301/39545708-09b4f0f8-4e20-11e8-9a67-7109a083d234.gif)

[0] https://github.com/fabric8-ui/fabric8-recommender/blob/aa11ad3b23916bd6b2c95b088d36117b75a947db/src/app/stack/pipeline-insights/pipeline-insights.component.ts#L87

**Comment by miteshvp** [comment] 2018-05-03 05:08
@jyasveer @arunkumars08 - PTAL here

**Comment by arunkumars08** [comment] 2018-05-03 08:00
I have tested this scenario in local environment pointing to production with internal features turned on.
Yes, it happens and I think I have narrowed down the root cause to be this:

1. https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/applications-widget/applications-list-item/applications-list-item.component.html#L73

https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/applications-widget/applications-list-item/applications-list-item.component.html#L34-L44

It keeps calling the stack-report NPM. Removing this seemed to work fine.

I understand this is something as per design, but we can decide on whether we need to show the stack report again in the applications section as we already show in a separate **Stack Report Recommendation** section with the option to choose all the available pipelines.

@joshuawilson Please let me know about the thought process.

Also, sometimes I have seen it happening even after switching the flag to production. Even there commenting out that above line of code seems to work fine.

**Comment by jiekang** [comment] 2018-05-03 12:39
Isn't there an issue somewhere within that code that's calling the same HTTP request repeatedly? Removing the whole component would work but it sounds like it wouldn't fix the issue within the component.

@dlabrecq Any ideas regarding what might be occurring inside ApplicationsStackReportComponent? Is it coming from some component in fabric8-stack-analysis-ui that is being used there?

**Comment by dlabrecq** [comment] 2018-05-03 14:03
When the pipelines observable is updated, this will rerender the stack report. I added code to the applications-details component to only update when the pipeline's statusPhase changes. That code should prevent the stack report component from being updated unnecessarily.

There are a few requests at first, after the application has been initially created, but it seems to settle down quickly.

That said, if this is a problem, we could remove the stack report considering the user has access to the stack report widget in the same page.

cc @mceledonia

**Comment by jiekang** [comment] 2018-05-03 14:06
Maybe the stack report component could be reworked? In my screenshot the http requests are all the same and the response contents are the same as well. It doesn't really make sense.

**Comment by dlabrecq** [comment] 2018-05-03 14:07
Yes, that would be ideal.

**Comment by arunkumars08** [comment] 2018-05-03 14:11
@dlabrecq Yes Dan. Also, there is one thing to note here, stack report gets called on loading itself as there are some preliminary checks that will happen to show CVEs and other information up front. That being said, we can discuss about keeping it as we already have the stack report dedicated card.

**Comment by dlabrecq** [comment] 2018-05-03 18:17
I spoke with @mceledonia and UXD is okay with removing it since there is a stack report widget in the page already.

**Comment by arunkumars08** [comment] 2018-05-04 18:10
Changes are merged in prod-preview. Please feel free to reopen it if you feel the issue is still persisting.

**Closed by arunkumars08** 2018-05-04 18:10 UTC
Labels: SEV2-high, area/analytics, team/analytics, team/analytics/integration, type/bug
