### ISSUE TITLE
OSIO (prod) seems to be broken on multiple places today.

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#2895] opened 2018-04-05 08:59 UTC
Creating only one issue, as the failures could have common cause.
Note, that the list of issues described here could be incomplete (I didn't go through whole osio experience)
All of these errors were experienced by multiple people today. Most (if not all of those users) are provisioned on starter-us-east-2. I'll try to reproduce it with account provisioned on different cluster.
Also note, that prod-preview seems to be ok.

What does not work:
##  Reset environment
Tenant cleanup fails with this error in browser console:
```
DELETE https://api.openshift.io/api/user/services 504 (Gateway Time-out)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
ZoneDelegate.scheduleTask @ zone.js:405
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
o.(anonymous function) @ zone.js:1366
(anonymous) @ _scrollbars.less:6
(anonymous) @ _overrides.less:6
Observable._trySubscribe @ patternfly.min.css:1
Observable.subscribe @ patternfly.min.css:1
MapOperator.call @ patternfly.min.css:1
Observable.subscribe @ patternfly.min.css:1
CatchOperator.call @ patternfly.min.css:1
Observable.subscribe @ patternfly.min.css:1
CatchOperator.call @ patternfly.min.css:1
Observable.subscribe @ patternfly.min.css:1
subscribeToResult @ patternfly.min.css:1
ForkJoinSubscriber @ patternfly.min.css:1
ForkJoinObservable._subscribe @ patternfly.min.css:1
Observable._trySubscribe @ patternfly.min.css:1
Observable.subscribe @ patternfly.min.css:1
CleanupComponent.confirm @ cleanup.component.ts:124
(anonymous) @ CleanupComponent.ngfactory.js:341
_ @ patternfly.min.css:1
handleEvent @ patternfly.min.css:1
dispatchEvent @ patternfly.min.css:1
(anonymous) @ patternfly.min.css:1
(anonymous) @ patternfly.min.css:1
wrapped @ _scrollbars.less:6
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ patternfly.min.css:1
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
p @ zone.js:1540
h @ zone.js:1566
_cleanup:1 Failed to load https://api.openshift.io/api/user/services: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.
```
## Startup of che workspace
Here, we are seeing multiple different (but similar) errors:
```
Failed to start Kubernetes runtime of workspace workspaceiqldykd8d2kcaoom. Cause: Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/kkanova-osiotest1-che/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims "claim-che-workspace" is forbidden: maximum storage usage per PersistentVolumeClaim is 1Gi, but request is 10Gi.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
```
```
Runtime exception caught in thread RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-878. Message: Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/rhopp-che/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "delete-wksp-g65e" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=488m, used: limits.cpu=4, limited: limits.cpu=4.
```

## Creation of new space
Right after creating space (right after first step of the wizard), this popup pops up:
![image](https://user-images.githubusercontent.com/1215011/38356430-03ab9e34-38c0-11e8-90a5-0e19a0a88357.png)

**Comment by ppalaga** [comment] 2018-04-05 09:04
Perhaps related from today: I cannot open a Che workspace getting "Could not start workspace ld0ne. Reason: Start of environment 'default' failed. Error: Image registry.devshift.net/che/centos_jdk8:latest not found."

**Comment by ibuziuk** [comment] 2018-04-05 09:08
Does not seem to be reproducible on prod-preview

**Comment by miteshvp** [comment] 2018-04-05 10:46
@pbergene seeing following errors. Is there any relation to what others are seeing?
<img width="604" alt="image" src="https://user-images.githubusercontent.com/17736013/38361888-8ba29c94-38ec-11e8-9ff8-fa5e4213fb99.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/17736013/38361870-7dab9384-38ec-11e8-9200-6d3817378b4d.png">

<img width="872" alt="image" src="https://user-images.githubusercontent.com/17736013/38361902-9b626056-38ec-11e8-9874-602a2ae5c546.png">

**Comment by pbergene** [comment] 2018-04-05 10:48
@miteshvp thanks.  I've encountered the same - I have a few suspicions and have reached out to ops on the openshift side. It looks like there are multiple issues going on this morning.

**Comment by sbose78** [comment] 2018-04-05 11:01
Could folks update this thread if the error notification after creation of space still shows up? No service should be talking to KC directly to fetch the openshift token.

**Comment by miteshvp** [comment] 2018-04-05 11:58
@sbose78 - still getting the error while creating a space
```
Responseheaders: Headers {_headers: Map(1), _normalizedNames: Map(1)}ok: falsestatus: 401statusText: "Unauthorized"type: 2url: "https://api.openshift.io/api/deployments/spaces/baf92dd2-e0eb-473e-a487-2b339ce9f904"_body: "{"errors":[{"code":"unauthorized_error","detail":"openshift token","status":"401","title":"Unauthorized error"}]}↵"__proto__: Body
```

**Comment by pbergene** [comment] 2018-04-05 12:00
There has been a few findings around problems on atomic-openshift-master-controllers, working with #libra-ops.

**Comment by pbergene** [comment] 2018-04-05 12:42
The issue is progressing and identified and has now moved from openshift ops to engineering to get this sorted.

**Comment by sbose78** [comment] 2018-04-05 12:42
@miteshvp yeah, saw it too.

The only 401 I could see in the network console , during the error while creating a space is 

```
Request URL:https://api.openshift.io/api/deployments/spaces/b0ca72d0-ca0a-47e0-b15c-21a98d6d8109
Request Method:GET
Status Code:401 Unauthorized
```

**Comment by ibuziuk** [comment] 2018-04-05 12:46
still can not do a reset environment:

`DELETE https://api.openshift.io/api/user/services 504 (Gateway Time-out) Failed to load https://api.openshift.io/api/user/services: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.`

**Comment by pbergene** [comment] 2018-04-06 07:41
East-2 was recovered ~16 hours ago, expecting most of the issues here to have cleared up.  As we have already been tracking two different issues with two different root causes here I am closing this and we can open any new ones to address any problems that may still persist.

**Closed by pbergene** 2018-04-06 07:41 UTC
Labels: SEV1-urgent, env/prod, team/service-delivery

**Comment by pbergene** [comment] 2018-04-06 09:35
https://github.com/openshiftio/openshift.io/issues/2917
