### ISSUE TITLE
Cannot create new quickstart on https://openshift.io

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1863] opened 2018-01-11 11:46 UTC
This error is seen - is this the CORS issue again?

![screenshot from 2018-01-11 06-44-30](https://user-images.githubusercontent.com/642621/34824083-0a09ca7e-f69b-11e7-9149-c7f408174d66.png)

**Comment by pbergene** [comment] 2018-01-11 11:58
Generator backend crashing heavily.  @gastaldi

**Comment by gastaldi** [comment] 2018-01-11 12:07
Having a look

**Comment by gastaldi** [comment] 2018-01-11 12:19
It works for me. What steps did you follow to reproduce that?

**Comment by sbose78** [comment] 2018-01-11 12:30
Worked for me.

**Comment by gastaldi** [comment] 2018-01-11 12:36
Removing the SEV-1 label, as it is working and apparently it doesn't for @ldimaggi's user only

**Comment by gastaldi** [comment] 2018-01-11 12:38
Closing as it is not reproducible. Reopen if the problem persists

**Closed by gastaldi** 2018-01-11 12:38 UTC
Labels: SEV3-medium, area/app-wizard, status/info-needed, team/service-delivery, type/bug

**Comment by ldimaggi** [comment] 2018-01-11 13:05
Whatever the problem was - it's gone now - was failing repeatedly early this morning. Thx!

**Comment by ldimaggi** [comment] 2018-02-01 20:15
Issue found/encountered by EE tests.
