### ISSUE TITLE
Intermittent issue - Creating Che workspace fails - configured service account doesn't  have access

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3893] opened 2018-07-03 17:11 UTC
Seeing this problem intermittently when creating a new workspace. Performing an env reset and then retrying seems to resolve this. 

Steps to recreate issue:
* Create new OSIO space
* Create new Che workspace

![bd259c291e4d7197d0033214220e8c66](https://user-images.githubusercontent.com/642621/42234345-437c4688-7ec2-11e8-92b2-1c8c6fc0b671.png)

**Comment by ldimaggi** [comment] 2018-07-03 17:12
From the Che log:

```

{"@timestamp":"2018-06-29T09:08:32.059+00:00","@version":1,"message":"Workspace 'osio-ci-e2e-003/pe0lg' with id 'workspace5ezp96l3cpgs5lnh' created by user 'osio-ci-e2e-003'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-4","level":"INFO","level_value":20000,"req_id":"773154fe-afd9-429d-9ef2-a9022c580710","identity_id":"ba633042-0043-408c-ac62-f8cc8255b194"}
{"@timestamp":"2018-06-29T09:08:39.612+00:00","@version":1,"message":"Starting workspace 'osio-ci-e2e-003/pe0lg' with id 'workspace5ezp96l3cpgs5lnh' by user 'osio-ci-e2e-003'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-8","level":"INFO","level_value":20000,"identity_id":"ba633042-0043-408c-ac62-f8cc8255b194"}
{"@timestamp":"2018-06-29T09:09:07.244+00:00","@version":1,"message":"Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`ba633042-0043-408c-ac62-f8cc8255b194` env=`default` workspace=`workspace5ezp96l3cpgs5lnh` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-06-29T09:09:07.24020338Z`","logger_name":"org.eclipse.che.api.logger.ErrorInstallerLogEventLogger","thread_name":"ServerSideRequestProcessor","level":"ERROR","level_value":40000}
{"@timestamp":"2018-06-29T09:09:25.418+00:00","@version":1,"message":"Workspace 'osio-ci-e2e-003:pe0lg' with id 'workspace5ezp96l3cpgs5lnh' started by user 'osio-ci-e2e-003'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"WorkspaceSharedPool-4","level":"INFO","level_value":20000,"identity_id":"ba633042-0043-408c-ac62-f8cc8255b194"}
{"@timestamp":"2018-06-29T09:15:39.009+00:00","@version":1,"message":"Workspace 'osio-ci-e2e-003/pe0lg' with id 'workspace5ezp96l3cpgs5lnh' is being stopped by user 'osio-ci-e2e-003'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-4","level":"INFO","level_value":20000,"req_id":"ao5wi9XfJp-22434","identity_id":"ba633042-0043-408c-ac62-f8cc8255b194"}
{"@timestamp":"2018-06-29T09:15:39.428+00:00","@version":1,"message":"Workspace 'osio-ci-e2e-003/pe0lg' with id 'workspace5ezp96l3cpgs5lnh' stopped by user 'osio-ci-e2e-003'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"WorkspaceSharedPool-7","level":"INFO","level_value":20000,"req_id":"ao5wi9XfJp-22434","identity_id":"ba633042-0043-408c-ac62-f8cc8255b194"}
{"@timestamp":"2018-06-29T09:15:39.683+00:00","@version":1,"message":"Workspace 'workspace5ezp96l3cpgs5lnh' removed by user 'osio-ci-e2e-003'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-7","level":"INFO","level_value":20000,"req_id":"ao5wi9XfJp-22434","identity_id":"ba633042-0043-408c-ac62-f8cc8255b194"}
{"@timestamp":"2018-06-29T09:20:51.778+00:00","@version":1,"message":"Workspace 'ibuziuk@redhat.com/jbosstools-sim-nypyb' with id 'workspace8mvvmzzkcdshhr31' created by user 
```

**Comment by rhopp** [comment] 2018-07-04 08:52
This seems, like that account does not have admin access to `-che` namespace (as requested in HK issue 2082), but feature toggle for this to work (on che side) was probably not set for those accounts (cc @ibuziuk )
But even if the toggle would be active for your account, you would encounter different issue: https://github.com/openshiftio/openshift.io/issues/3884

**Comment by ibuziuk** [comment] 2018-07-04 09:00
@rhopp for me it sounds like a duplicate of https://github.com/openshiftio/openshift.io/issues/3884
original reported had exactly the same problem and was not in the toggle

**Comment by rhopp** [comment] 2018-07-04 09:02
@ibuziuk The error messages are slightly different in these two issues ,that's why I thought this one is a bit different issue.

**Comment by ibuziuk** [comment] 2018-07-04 09:04
ah, right in the original issue it was about `pvc` not `svc`

**Comment by ibuziuk** [comment] 2018-08-19 17:08
@ldimaggi @rhopp similar issue #3884 has been closed. Is it still reproducible or we can also close this one ?

**Comment by rhopp** [comment] 2018-08-20 06:02
I didn't see this issue in the first place. @ldimaggi Have you seen this one since reporting it?

**Comment by ibuziuk** [comment] 2018-08-21 06:33
@ldimaggi closing. feel free to reopen in case you still can reproduce

**Closed by ibuziuk** 2018-08-21 06:33 UTC
Labels: SEV2-high, area/che, issue/intermittent, priority/P4, status/pending-qa-verification, team/che/osio, type/bug
