### ISSUE TITLE
occasionally edit profile and profile page load together in one page

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2001] opened 2018-01-24 04:14 UTC
I keep seeing this periodically, possibly due to resetting my environment a lot for testing and retesting. I go to the Profile page, then click Update profile. The update profile page loads, but the main profile page loads just under it. See screenshots for the whole page:

![profilepage1](https://user-images.githubusercontent.com/926572/35314272-c458c2c0-0110-11e8-9268-ab465c0d57ac.png)

## Impacts
- [ ] #2139

**Comment by mishaone** [comment] 2018-01-24 04:42
And again just now when I was updating my experimental features settings to production only (ignore the second green profile updated thing, this is a composite of two images because I have to scroll down in my browser):

![1](https://user-images.githubusercontent.com/926572/35314888-d9585f88-0114-11e8-8971-a2798fb2cbc7.png)

**Comment by joshuawilson** [comment] 2018-01-24 06:30
I've seen this kind of duplication of the UI components under the Create tab but never on Profile. 

Do you have a reliable way to reproduce it?

**Comment by mishaone** [comment] 2018-01-24 06:33
Not really. It seems to come up now and then if I'm resetting the environment and then creating a space and then quickstart again a few times. Maybe the stress of resetting several times over a period of a few hours makes it happen? I'll try and post here if I see it again and what specific circumstances prompted it this time.

**Comment by mishaone** [comment] 2018-01-25 00:09
Another similar thing when I refreshed my pipeline builds page:
![duplicate_rendering](https://user-images.githubusercontent.com/926572/35363824-c57c4990-01b7-11e8-9452-e9297be6067c.png)

**Comment by qodfathr** [comment] 2018-01-26 15:42
Potentially related: #1975

**Comment by jiekang** [comment] 2018-02-05 22:44
The next time this occurs can you check the browser console to see if there are any error outputs and post them here if there are?

**Comment by mishaone** [comment] 2018-02-06 00:19
@jiekang will do. I'll try to replicate this today.

**Comment by corinnekrych** [comment] 2018-03-30 07:24
closing as duplicate of https://github.com/openshiftio/openshift.io/issues/2339

**Closed by corinnekrych** 2018-03-30 07:24 UTC
Labels: SEV2-high, area/UI, area/user/profile, team/platform, train/heather, type/bug
