### ISSUE TITLE
Unable to mount volumes on both clusters 2 and 2a

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4422] opened 2018-10-15 09:43 UTC
Created a new quickstart project after `reset environment`
Jenkins takes a lot of time to start and when it does openshift doesn't get a view logs link

The issue was experienced on prod-preview and seems consistent as I faced the same problem consecutively on doing the above exercise.
Same was seen on prod, consistentlly.

Going through `monitoring`, I see the following errors

```
Unable to mount volumes for pod "jenkins-1-ntvfl_ksagathi-preview-jenkins(56f94d91-d05b-11e8-91f8-02074d91bc8a)": timeout expired waiting for volumes to attach/mount for pod "ksagathi-preview-jenkins"/"jenkins-1-ntvfl". list of unattached/unmounted volumes=[jenkins-home]
```
Saw this some 10 times
```
Error creating: pods "jenkins-1-7jrlm" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
```
```
Readiness probe failed: HTTP probe failed with statuscode: 503
```

more into this conversation https://chat.openshift.io/developers/pl/n1u6k954dp8n9g7n497x8skoxh

All event logs here [events.log](https://github.com/openshiftio/openshift.io/files/2478233/events.log)

**Comment by chmouel** [comment] 2018-10-15 09:49
note: The issue is about gluster volumes not mounting properly not about quota,

**Comment by kishansagathiya** [comment] 2018-10-15 11:06
This definitely consistent. Happens every time. 
Because of this issue, I can't trigger any builds on prod-preview, stopping me from whatever manual testing I use prod-preview for

**Comment by kishansagathiya** [comment] 2018-10-16 04:17
I saw this on prod just now
my prod-preview is on cluster 2a
prod on cluster 2
```
[kishansagathiya@localhost ~]$ oc get events
LASTSEEN   FIRSTSEEN   COUNT     NAME              KIND                    SUBOBJECT                  TYPE      REASON                        SOURCE                                                 MESSAGE
6m         6m          1         jenkins-1-dqkk7   Pod                                                Normal    Scheduled                     default-scheduler                                      Successfully assigned jenkins-1-dqkk7 to ip-172-31-68-153.us-east-2.compute.internal
3m         3m          1         jenkins-1-dqkk7   Pod                                                Warning   FailedMount                   kubelet, ip-172-31-68-153.us-east-2.compute.internal   Unable to mount volumes for pod "jenkins-1-dqkk7_ksagathi-jenkins(59fc646d-d0f9-11e8-867f-02d7377a4b17)": timeout expired waiting for volumes to attach or mount for pod "ksagathi-jenkins"/"jenkins-1-dqkk7". list of unmounted volumes=[jenkins-home]. list of unattached volumes=[jenkins-home jenkins-config jenkins-token-0v1jr]
3m         3m          1         jenkins-1-dqkk7   Pod                     spec.containers{jenkins}   Normal    Pulling                       kubelet, ip-172-31-68-153.us-east-2.compute.internal   pulling image "fabric8/jenkins-openshift:v7e8de2d"
3m         3m          1         jenkins-1-dqkk7   Pod                     spec.containers{jenkins}   Normal    Pulled                        kubelet, ip-172-31-68-153.us-east-2.compute.internal   Successfully pulled image "fabric8/jenkins-openshift:v7e8de2d"
3m         3m          1         jenkins-1-dqkk7   Pod                     spec.containers{jenkins}   Normal    Created                       kubelet, ip-172-31-68-153.us-east-2.compute.internal   Created container
3m         3m          1         jenkins-1-dqkk7   Pod                     spec.containers{jenkins}   Normal    Started                       kubelet, ip-172-31-68-153.us-east-2.compute.internal   Started container
6m         6m          1         jenkins-1         ReplicationController                              Normal    SuccessfulCreate              replication-controller                                 Created pod: jenkins-1-dqkk7
6m         3d          42        jenkins           DeploymentConfig                                   Normal    ReplicationControllerScaled   deploymentconfig-controller                            Scaled replication controller "jenkins-1" from 0 to 1
```

**Comment by kishansagathiya** [comment] 2018-10-16 05:06
prod logs
[events_prod.log](https://github.com/openshiftio/openshift.io/files/2481502/events_prod.log)

**Comment by pbergene** [comment] 2018-10-16 08:36
There are a couple of hundred jenkins in a bad state (idler/proxy related) that are presumed to be causing the stress on the PV mounts.

**Comment by kishansagathiya** [comment] 2018-10-17 09:45
> With lowered filesystem operations pressure does mount problem gone?

I think so. I was not able to start my Jenkins. Now I am.

**Comment by pmacik** [comment] 2018-10-17 13:00
> commit/jenkins.openshift.io does not start jenkins, not sure if everyone is facing this

I see it too, after reset environment (2a cluster user), no jenkins is deployed:

![image](https://user-images.githubusercontent.com/3263627/47087792-33d0b300-d21d-11e8-8fe7-ddf09a664879.png)

**Comment by sthaha** [comment] 2018-10-18 04:42
I am going to close this issue as deployment of new idler seems to have fixed the issue. Please try resetting the environment before reopening

**Closed by sthaha** 2018-10-18 04:42 UTC
Labels: SEV1-urgent, area/e2e-tests, area/jenkins, priority/P1, team/build-cd, team/service-delivery, type/bug
