### ISSUE TITLE
Failures in staging should prevent deployment to run - but they aren't

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#877] opened 2017-09-19 03:25 UTC
_From @ldimaggi on July 7, 2017 19:1_

See attached screenshot - creating a new (Vert.x - CRUD) quickstart failed in staging. (A separate issue will be logged for this failure.)

The failure in staging did not prevent the app from being promoted to run. Shouldn't a failure to stage always abort the build pipeline? 

![screenshot from 2017-07-07 14-56-48](https://user-images.githubusercontent.com/642621/27972649-18527d4c-6325-11e7-88fd-d7540928d191.png)

_Copied from original issue: fabric8-ui/fabric8-ui#1666_

**Comment by joshuawilson** [comment] 2017-09-19 03:25
@jstrachan here is another for you.

**Comment by joshuawilson** [comment] 2017-09-19 03:25
@rawlingsj do you know why this staging failure doesn't block the build?

**Comment by qodfathr** [comment] 2018-01-19 19:32
@joshuawilson @ldimaggi I'm wondering if we can create a Space, create a QuickStart, and then modify the Jenkinsfile and insert into it a forced failure as a way to (1) create a failure on Rollout to Stage and (2) as a way to see if this problem is fixed.

**Comment by joshuawilson** [comment] 2018-01-19 21:05
I've moved this to the Build/CD team.

**Comment by piyush1594** [comment] 2018-06-25 07:41
@joshuawilson It happened something like this for me now

![test-fail](https://user-images.githubusercontent.com/19270240/41836717-399c5e72-7879-11e8-80c3-fd3f7637c4ff.png)


Seems like the issue is not there now.

**Comment by piyush1594** [comment] 2018-06-25 11:35
@ldimaggi @joshuawilson I happened because of some failure from maven-central pulling.

**Comment by piyush1594** [comment] 2018-06-29 16:59
@joshuawilson @ldimaggi Happened once for me. Everything working fine.

![fail](https://user-images.githubusercontent.com/19270240/42104860-d9440572-7beb-11e8-8404-b37f72d3452b.png)


We are good to close this issue.

**Comment by sthaha** [comment] 2018-07-30 06:29
Closing this issue based on https://github.com/openshiftio/openshift.io/issues/877#issuecomment-401414194 please reopen if the issue isn't fixed.

**Closed by sthaha** 2018-07-30 06:29 UTC
Labels: SEV3-medium, area/app-wizard, area/pipelines, priority/P3, team/build-cd, type/bug
