### ISSUE TITLE
On prod-preview, new space wizard fails to create a new app

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3607] opened 2018-05-22 12:38 UTC
This problem is being seen on prod-preview and not on production.

Steps to recreate:

* Create a new space:
![screenshot from 2018-05-22 08-28-34](https://user-images.githubusercontent.com/642621/40362647-2603f1fc-5d9b-11e8-9824-2b295bc2c143.png)

* Then, without leaving the new space wizard, attempt to create a new app:
![screenshot from 2018-05-22 08-29-31](https://user-images.githubusercontent.com/642621/40362692-4833f628-5d9b-11e8-8109-7b27cb3cf226.png)

* Observe that the new app wizard exits without creating a new app:
![screenshot from 2018-05-22 08-31-14](https://user-images.githubusercontent.com/642621/40362720-5abb66dc-5d9b-11e8-9384-a50292959c32.png)

**Comment by joshuawilson** [comment] 2018-05-22 13:28
@jyasveer @animuk @arunkumars08 @invincibleJai please take a look. There are changes in prod-preview that I have yet to merge to prod.

**Comment by joshuawilson** [comment] 2018-05-22 21:55
I confirmed this in prod-preview

**Comment by joshuawilson** [comment] 2018-05-23 02:16
Now I can't reproduce it. I'm concerned about pushing this to prod.

**Comment by ldimaggi** [comment] 2018-05-23 02:37
I just saw it in prod-preview.

**Comment by jyasveer** [comment] 2018-05-23 05:29
I have assigned to myself. I am checkin it now

**Comment by jyasveer** [comment] 2018-05-23 05:34
I also can't reproduce this. I don't find any errors here.
@joshuawilson @ldimaggi please confirm ?

**Comment by ppitonak** [comment] 2018-05-23 06:30
I cannot reproduce.

**Comment by ppitonak** [comment] 2018-05-23 06:59
I'm not sure if it's related but I can reproduce something similar:

1. delete all spaces on "My spaces" page
2. go to "Account home" page
3. I see 2 running (in fact not started) builds - openshift.io link is broken but I can see in OpenShift console that they still exist
4. click "Create space" in top-left menu
5. name it like on of these running pipelines
6. on "Create an Application" leave name as is, select "Create a new codebase", click "Continue"

result:
* new space is created
* space homepage is displayd
* create new app wizard NOT displayed

**Comment by jyasveer** [comment] 2018-05-23 07:50
@joshuawilson @ldimaggi 
This is not a blocker for now. This happens in a particular scenario where we propose the default application name as `app-test-1` and this application name is already used in the current space and we click on `Continue` button.
However if we modify the application name to a unique one and then click on the `Continue` button we are good.

Solution for this:
At present i validate the applicate name on `keyup` event in the application name input box. Now I will also validate the application name upfront i.e. on page load and display the warning message if required and also disable the continue button.
cc @animuk

**Comment by ppitonak** [comment] 2018-05-23 08:04
@jyasveer we are creating a **new app** in a **new space**, how could be this name already used?

**Comment by jyasveer** [comment] 2018-05-23 18:58
@ppitonak the default application name what we are proposing could have already been used by the user for the space.

**Comment by jyasveer** [comment] 2018-05-24 03:45
This isssue is dependent on https://github.com/openshiftio/openshift.io/issues/3626
cc @joshuawilson @animuk

**Comment by jyasveer** [comment] 2018-05-24 11:15
closing this.

**Closed by jyasveer** 2018-05-24 11:15 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, env/prod-preview, status/completed, team/analytics, team/analytics/wizard, type/bug

**Comment by joshuawilson** [comment] 2018-05-25 16:12
@ldimaggi can you confirm this is fixed?

**Comment by ldimaggi** [comment] 2018-05-25 17:19
Confirmed - this is fixed.
