### ISSUE TITLE
Che "Download outputs" creates a file with "null" content

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#593] opened 2017-08-16 17:20 UTC
When Che 286 is starting, and you click in the link "Download outputs", it creates a file with a string "null".

![screenshot 2017-08-16 13 18 56](https://user-images.githubusercontent.com/30131/29376147-9ddff528-8285-11e7-8717-6e385819e741.png)

**Comment by l0rd** [comment] 2017-09-27 16:31
Duplicate of #513

**Closed by l0rd** 2017-09-27 16:31 UTC
Labels: kind/bug, team/che
