### ISSUE TITLE
Quickstart/app Deployment errors not accurately reported to users in build pipeline window

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1895] opened 2018-01-17 00:38 UTC
Followup to: https://github.com/openshiftio/openshift.io/issues/395

In this case, the application was deployed, but errors blocked the stage and run pods from starting. The deployments were reported as successful to the user in the OSIO UI.

**Comment by ldimaggi** [comment] 2018-01-17 12:16
The UI indicated that the deployment to stage and run were successful - but after the deployment, the deployed pods failed to start:

The quickstart builds - but when it is deployed to stage, the stage pod fails to start and repeatedly fails with this error:

```
2018-01-16 20:53:08.784 ERROR 1 --- [           
main] o.s.boot.SpringApplication               : Application startup failed
--
  |  
  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name
 'entityManagerFactory' defined in class path resource
 [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: 
Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: 
Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]


```

**Comment by ldimaggi** [comment] 2018-01-17 12:17
See log:  https://github.com/openshiftio/openshift.io/files/1636764/testtodd2-1-dprgd.log

**Comment by qodfathr** [comment] 2018-01-17 13:04
As commented in #395, the CRUD QuickStart is not OSIO compatible today and will be removed. We'll reconsider it post launch. I recommend closing, but if you'd like to wait until the quickstart is no longer available, @ldimaggi , that's okay with me.

**Comment by ldimaggi** [comment] 2018-01-17 13:07
The quickstart was already removed - so #395 can be safely closed. 

However - if a similar pod starting issue happens, the user will not be alerted through the build pipeline window.

**Comment by ldimaggi** [comment] 2018-06-07 13:11
The root cause is still present - if the pod starting issue happens, the user will not be alerted through the build pipeline window.

**Comment by miteshvp** [comment] 2018-08-17 06:50
Assigning it to the right team owners.

**Comment by joshuawilson** [comment] 2018-10-30 03:32
@bartoszmajsak @sthaha is this a known issue? Do you know the cause. 
@ldimaggi can you reliably reproduce it?

**Comment by joshuawilson** [comment] 2018-10-30 03:33
@openshiftio/uxd-team it looks like we might need some form of notification in the UI when this happens.

**Comment by hrishin** [comment] 2018-11-05 18:49
@ldimaggi this issue has been discussed recently by @pmacik. I guess its duplicate of #4009. If that makes sense, shall we close this issue?

Essentially build pipeline fails to acknowledge if an application get up and running after deploying it. This is taken care in `osio-pieline` library. Hopefully, we will roll out this soon for Java quickstarts.

**Comment by hrishin** [comment] 2018-11-08 05:55
closing this in regards #4009

**Closed by hrishin** 2018-11-08 05:55 UTC
Labels: SEV3-medium, area/UX, area/pipelines, area/quickstarts, priority/P4, sprint/tbd, team/app-creation, team/build-cd, team/launcher, team/ui, team/ux, type/bug
