### ISSUE TITLE
PR builds on boosters do not pass

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#763] opened 2017-09-06 13:29 UTC
https://gist.github.com/anonymous/7c1c32ad5e8b8ca1ba398074575f2fd9

**Comment by rawlingsj** [comment] 2017-09-06 14:09
that looks like the integration test.. is that right?  If so can you check the resources in the environment that it is running in, I think now that should be your users home namespace.

The error looks like the pod didn't start in time during the integration test but I could be wrong.  A bit more info is needed.

**Comment by sbose78** [comment] 2017-09-06 15:46
Thanks @rawlingsj for looking into this - 
In https://console.starter-us-east-2.openshift.com/console/project/shbose/quota
Resource usage is at 50% for cpu and memory, with 2 out of 5 services.

You are correct, that's the integration test:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UseParallelGC                                 -XX:MinHeapFreeRatio=20                                 -XX:MaxHeapFreeRatio=40                                 -XX:GCTimeRatio=4                                 -XX:AdaptiveSizePolicyWeight=90                                 -Xmx256m
Running io.openshift.booster.OpenShiftIT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
application deployed, 3 object(s) created.
Route url: http://booster-rest-http-vertx-shbose.8a09.starter-us-east-2.openshiftapps.com
Deleting application : DeploymentConfig
Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 306.268 sec <<< FAILURE! - in io.openshift.booster.OpenShiftIT
testThatWeAreReady(io.openshift.booster.OpenShiftIT)  Time elapsed: 300.032 sec  <<< ERROR!
com.jayway.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.openshift.booster.test.OpenShiftTestAssistant was not fulfilled within 5 minutes.
	at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:122)
	at com.jayway.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at com.jayway.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:764)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:741)
	at io.openshift.booster.test.OpenShiftTestAssistant.awaitApplicationReadinessOrFail(OpenShiftTestAssistant.java:141)
	at io.openshift.booster.OpenShiftIT.testThatWeAreReady(OpenShiftIT.java:39)

testThatWeServeAsExpected(io.openshift.booster.OpenShiftIT)  Time elapsed: 2.838 sec  <<< FAILURE!
```

**Comment by bartoszmajsak** [comment] 2018-02-15 16:01
This might be fixed with https://github.com/fabric8io/fabric8-pipeline-library/pull/381

@sbose78 give it a spin or use `@Library('github.com/bartoszmajsak/fabric8-pipeline-library@cube-properties')` as that's what this PR brings.

**Comment by piyush1594** [comment] 2018-06-21 06:53
@sbose78 Is this still happening? Can you confirm please?

**Comment by hrishin** [comment] 2018-07-06 05:17
PR build is failing for Integration Tests

1) vertex app build logs:
https://pastebin.com/N2X5YMEF

2) Springboot app build logs:
https://pastebin.com/sD7TPwfZ

**Comment by piyush1594** [comment] 2018-07-30 08:41
@sthaha This is an issue which is reproducible in the current state also.

**Comment by bartoszmajsak** [comment] 2018-08-01 19:44
Another issue leading to that problem (reproducible if you have Configmap booster imported) https://github.com/openshiftio/openshift.io/issues/3134#issuecomment-409694091

**Comment by bartoszmajsak** [comment] 2018-08-01 20:30
I managed to fix my other issue. For this one - do we have a reproducer?

**Comment by piyush1594** [comment] 2018-09-12 16:03
Fixed with https://github.com/fabric8io/fabric8-jenkinsfile-library/pull/37

**Closed by piyush1594** 2018-09-12 16:03 UTC
Labels: SEV3-medium, priority/P2, sprint/current, team/build-cd, type/bug

**Comment by bartoszmajsak** [comment] 2018-09-13 11:12
@piyush1594 did we run PR builds to verify that? Can you point me to the booster repos?

**Comment by piyush1594** [comment] 2018-09-13 11:29
@bartoszmajsak I tested @hrishin PR https://github.com/fabric8io/fabric8-jenkinsfile-library/pull/36 using my repo https://github.com/piyush1594/test-ci-maven
