### ISSUE TITLE
rest-http - wildfly-swarm Booster/Quickstart fails to run in Che in OpenShift

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3123] opened 2018-04-13 15:55 UTC
Steps to recreate:
* Create a new app, Mission = REST, Runtime = Wildfly 
* Observe the build pipeline run through to successful completion
* Create a Che workspace
* In Che, execute the maven command documented in the README: mvn wildfly-swarm:run
* Observe this error:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.openshift.booster.GreetingServiceTest
Resolving 0 out of 720 artifacts
Fri Apr 13 15:47:10 UTC 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.469 s <<< FAILURE! - in io.openshift.booster.GreetingServiceTest
[ERROR] io.openshift.booster.GreetingServiceTest  Time elapsed: 10.469 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
Caused by: org.jboss.arquillian.container.spi.client.container.DeploymentException: Process failed to start
```

Note - running these commands outside of Che are successful:
* git clone git@github.com:username/reponame
* cd reponame
* mvn wildfly-swarm:run

```
2018-04-13 11:55:28,850 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 8) WFLYUT0021: Registered web context: /
2018-04-13 11:55:28,887 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "app-test-1-1.0.0.war" (runtime-name : "app-test-1-1.0.0.war")
2018-04-13 11:55:28,894 INFO  [org.wildfly.swarm] (main) WFSWARM99999: WildFly Swarm is Ready
```

**Comment by l0rd** [comment] 2018-04-25 12:31
@ldimaggi looks like a duplicate of #2152. Please re-open if it makes sense to have 2 distinct issues.

**Closed by l0rd** 2018-04-25 12:31 UTC
Labels: SEV2-high, area/che, priority/P0, team/che/IDE, type/bug
