### ISSUE TITLE
Jenkins pipeline progress is not propagated into openshift.io

### ISSUE THREAD

**Issue by odockal** [openshiftio/openshift.io#657] opened 2017-08-24 14:52 UTC
I was pushing some commits in che intho github that start pipeline build process. But the fact that jenkins pipeline is running and build of each phases was done (until production build that requires promoting) was not reflected into openshift.io - myspace - pipelines dashboard. Build #3 is the one.

![openshift-io-pipelines](https://user-images.githubusercontent.com/19164299/29672358-4a8ab562-88ec-11e7-93e0-e81202c16ec7.png)

Yet, jenkins pipeline was doing well:

Stashed 11 file(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] node
Running on master in /var/lib/jenkins/jobs/dockalondrej/jobs/myspace/branches/master/workspace
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Approve)
[Pipeline] hubotApprove
Hubot sending to room fabric8_default => Would you like to promote version 1.0.3 to the next environment?
   to Proceed reply:  fabric8 jenkins proceed job dockalondrej/myspace/master build 3
   to Abort reply:    fabric8 jenkins abort job dockalondrej/myspace/master build 3
No service hubot  is running!!!
No service found!
[Pipeline] approveRequestedEvent
[Pipeline] timeout
Timeout set to expire in 1 day 0 hr
[Pipeline] {
[Pipeline] input

Would you like to promote version 1.0.3 to the next environment?

Proceed or Abort
[Pipeline] }
[Pipeline] // timeout

Jenkins was waiting for user interaction and timed out...

I started pipeline again and it went fine, as can be seen in the pic.

**Comment by l0rd** [comment] 2017-08-25 15:41
@joshuawilson I've removed `area/che` label since it doesn't seem to be related.

**Comment by joshuawilson** [comment] 2017-08-25 15:47
@odockal can you please clarify. Is this issue because you started in Che? Or is it not related?

**Comment by chmouel** [comment] 2018-01-18 16:43
jenkins pipelines seems to do well here as reported, should we just move this to the f8-ui backlog instead of ours?

**Comment by joshuawilson** [comment] 2018-01-18 20:08
We do not track anything in fabric8-ui repo. Do you mean move it to `team/platform`?

I am wondering if this is a duplicate of #508

**Comment by qodfathr** [comment] 2018-01-18 20:59
Fixed, although there are related issues of interest in #508.

**Closed by qodfathr** 2018-01-18 20:59 UTC
Labels: area/pipelines, team/build-cd
