### ISSUE TITLE
Chrome pop-up blocking can lead to bad experience with OSIO

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#3852] opened 2018-06-25 22:04 UTC
**Problem**: When using OSIO the first time it's easy to miss the Chrome notification about allowing popups. If you do you're likely to get an unhelpful error and the impression that Che won't start.

**Environment**: Production

**Feature Flag Level**: Any

Ideally we'd find some way to avoid needing popups, but alternatively perhaps we can find some way to help avoid a situation in which the user's Chrome popup settings prevent them from having a good experience on OSIO.

**Comment by joshuawilson** [comment] 2018-06-26 02:06
Duplicate of #3565 
Fix is being worked in https://github.com/fabric8-ui/fabric8-ui/pull/2972

**Closed by joshuawilson** 2018-06-26 02:06 UTC
Labels: SEV3-medium, env/prod, team/platform
