### ISSUE TITLE
Launcher: A text field validation fails when name is pasted using mouse middle-click

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#3227] opened 2018-04-20 12:51 UTC
1) Start with `Authorize Git Provider` section:
![image](https://user-images.githubusercontent.com/3263627/39051653-a13e8856-44a9-11e8-9559-4879f14f781e.png)
2) Paste repository name with middle-click:
![image](https://user-images.githubusercontent.com/3263627/39051669-b3da5f3a-44a9-11e8-9f5a-421fa8e56090.png)
The `Continue` button is not enabled.
3) Update the repository name using keyboard:
![image](https://user-images.githubusercontent.com/3263627/39051711-dd2413ea-44a9-11e8-9873-f08809965f5d.png)
![image](https://user-images.githubusercontent.com/3263627/39051719-e35e3fc4-44a9-11e8-893a-6411713ecdf4.png)
Now, the `Continue` button is enabled.
4) Clean the text field:
![image](https://user-images.githubusercontent.com/3263627/39051756-fb7e8f14-44a9-11e8-8657-42ec5537670b.png)
![image](https://user-images.githubusercontent.com/3263627/39051763-00de5638-44aa-11e8-9729-4b064f7da5aa.png)
Now, the failed validation is triggered:
5) Paste the name again with the middle-click:
![image](https://user-images.githubusercontent.com/3263627/39051788-1295c06e-44aa-11e8-8f3a-e18b41a02008.png)
Now, the failed validation is kept triggered and can be confusing.

**Comment by pmacik** [comment] 2018-04-20 12:54
Using a Chrome browser.

**Comment by vikram-raj** [comment] 2018-08-06 05:49
@pmacik I am not able to reproduce this issue. Can you please verify.

**Comment by sanketpathak** [comment] 2018-08-09 09:43
@vikram-raj @pmacik I also am not able to reproduce the issue

**Comment by vikram-raj** [comment] 2018-08-09 10:06
Closing this as it is not reproducible. Feel free to open this if you find it again.

**Closed by vikram-raj** 2018-08-09 10:06 UTC
Labels: SEV3-medium, area/UI, area/UX, area/app-wizard, area/launcher, priority/P4, team/app-creation, type/bug
