### ISSUE TITLE
Powerbutton icons are confusing

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#481] opened 2017-08-08 14:13 UTC
See attached screenshot - if the Jenkins/Che pods are down, this icon is displayed:

![screenshot from 2017-08-08 10-09-05](https://user-images.githubusercontent.com/642621/29075975-1498382a-7c22-11e7-90a7-129c5a0ba03e.png)

Can we change this to better indicate that something is wrong? Suggestion - an icon that indicates an error such as a red "X" and tooltip text to give the user some guidance? Thx!

**Comment by burrsutter** [comment] 2017-08-08 14:15
We at least need an explanation as to what the power icons represent. One of our testers ran into this today.

**Comment by joshuawilson** [comment] 2017-08-09 16:42
duplicate of https://github.com/openshiftio/openshift.io/issues/448
closing

**Closed by joshuawilson** 2017-08-09 16:42 UTC
Labels: area/status, kind/bug
