### ISSUE TITLE
OpenShift Project 'xxxxxx-jenkins' cannot be found

### ISSUE THREAD

**Issue by leospol** [openshiftio/openshift.io#3076] opened 2018-04-12 14:45 UTC
I've followed OSIO Click Party steps and my pipeline got stucked in Approve state. XHR calling [1] returns 500 Internal Server Error. Here are headers and payload:

**Request:**
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: /snip/
Connection: keep-alive
Content-Length: 0
Host: forge.api.openshift.io
Origin: https://openshift.io
Referer: https://openshift.io/leospol/SuperNewSpace/create/pipelines
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Response:**
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://openshift.io
Access-Control-Expose-Headers: Content-Disposition
Content-Length: 67
Content-Type: application/json
Date: Thu, 12 Apr 2018 14:22:48 GMT
Set-Cookie: /snip/; path=/; HttpOnly; Secure

**Payload:**
[{message: "OpenShift Project 'leospol-jenkins' cannot be found"}]

**Application name:** app-test-1
**Source repo:** https://github.com/leospol/openshift.io_click_party.git

[1] https://forge.api.openshift.io/api/openshift/services/jenkins/leospol-jenkins/job/leospol/job/openshift.io_click_party/job/master/1/input/Proceed/proceedEmpty

**Comment by lordofthejars** [comment] 2018-04-25 14:31
I think this is a duplicate of https://github.com/openshiftio/openshift.io/issues/3026 

cc/ @kishansagathiya

**Comment by kishansagathiya** [comment] 2018-04-25 16:52
@lordofthejars I don't see a similar message(OpenShift Project 'leospol-jenkins' cannot be found) on #3026 
We can wait and try to get some logs for this if possible

**Comment by ldimaggi** [comment] 2018-04-25 17:10
Are you able to recreate this issue now? Can you try also try this in incognito mode?

**Comment by gastaldi** [comment] 2018-04-26 04:56
This error is thrown here: https://github.com/fabric8-launcher/launcher-backend/blob/master/web/src/main/java/io/fabric8/launcher/web/api/OpenShiftResource.java#L162 (which may need to be reviewed by the build team if that changed recently)

I have opened https://github.com/openshiftio/openshift.io/issues/2093 a long time ago asking to move that code to the Build team ownership and if requires changes, please provide a PR and I'll be happy to merge

**Comment by gastaldi** [comment] 2018-04-27 04:54
It seems this is caused because the `leospol-jenkins` doesn't exist. @leospol can you confirm that?

**Comment by leospol** [comment] 2018-04-27 09:28
@gastaldi yes, based on returned message it seems you're right.

**Comment by aslakknutsen** [comment] 2018-04-28 00:29
The view role issue on cluster 2a should now be resolved. Please retest.

**Comment by pbergene** [comment] 2018-04-30 12:50
Closing, please let us know if this is still a problem.

**Closed by pbergene** 2018-04-30 12:50 UTC
Labels: SEV1-urgent, area/jenkins, area/pipelines, priority/P0, team/build-cd, type/bug
