### ISSUE TITLE
"Force Active" is inherited from parent iteration on "Create child"

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1982] opened 2018-01-23 14:15 UTC
![screenshot from 2018-01-23 15-14-28](https://user-images.githubusercontent.com/132158/35280328-236e7e2e-0050-11e8-9d3b-c8e4e8cb8eca.png)
![screenshot from 2018-01-23 15-14-13](https://user-images.githubusercontent.com/132158/35280329-2389f820-0050-11e8-871d-ae2a8b0df2ef.png)

**Comment by michaelkleinhenz** [comment] 2018-01-23 15:43
We discussed that in the planning and we think this is an intended behaviour. While iterations are independent on the active state, creating a new iteration sets some meaningful default values. And in the case the parent is already active, this meaningful state would be that the child may in most cases also be active (especially for new iterations, matching a workflow of a team).

Anyway, this is not a technical bug, but more like a PM question or a possible requirements change.

**Comment by qodfathr** [comment] 2018-01-23 18:14
Reopening as a question. The original plan was for only 1 active iteration per Team -- this is particularly important for running reports, setting reasonable defaults on new work items, etc. But maybe there is a model whereby there can be more than one active iteration.

I'll own this and work on a plan with UXD.

**Comment by nimishamukherjee** [comment] 2018-10-25 08:59
Closing this issue based on @michaelkleinhenz 's comment.

**Closed by nimishamukherjee** 2018-10-25 08:59 UTC
Labels: area/planner, type/question
