### ISSUE TITLE
OpenShift.io header image in email notifications not appearing

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3898] opened 2018-07-05 02:15 UTC
In the OpenShift.io notification emails, the header only shows a broken image, due to the file not being found at the URL given.

It appears, from local testing and multiple variations of the URLs in question, that this is due to the additional hashes that are added to image URLs when in production (see lines [345](https://github.com/fabric8-ui/fabric8-ui/blob/a848b211c1af302448c13b49a42da78a18cd29e7/config/webpack.common.js#L345) and [359](https://github.com/fabric8-ui/fabric8-ui/blob/a848b211c1af302448c13b49a42da78a18cd29e7/config/webpack.common.js#L359) of the build configuration). When viewing the repo, the image in question does actually exist. Other images have also been tested, and the problem exists for those as well.

Images that are not included in the build (and thus do not have the hashes) appear as expected (such as the user profile images from Gravatar).

In the templates, the URL that is being used is `https://openshift.io/_openshiftio/assets/images/openshift_logo_black.png`.

Before the hashing was added to the builds, the images appeared as expected in the email notifications.

<img width="817" alt="screen shot 2018-07-04 at 10 13 00 pm" src="https://user-images.githubusercontent.com/4032718/42299118-7342ae00-7fd7-11e8-87cf-f6e617725055.png">

**Comment by aptmac** [comment] 2018-07-09 14:22
Is this not a duplicate of https://github.com/openshiftio/openshift.io/issues/1375 and/or https://github.com/openshiftio/openshift.io/issues/2623?

**Comment by aslakknutsen** [comment] 2018-08-28 14:27
Duplicate https://github.com/openshiftio/openshift.io/issues/1375

**Closed by aslakknutsen** 2018-08-28 14:27 UTC
Labels: SEV2-high, priority/P4, team/platform, type/bug
