### ISSUE TITLE
Jenkins sometimes fail to scan for new space when unidled

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#1626] opened 2017-12-11 20:37 UTC
In some cases Jenkins does not start properly (see the attached log) and does not scan for new pipelines.

Same issue on Jenkins JIRA: https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-47505?filter=allissues
Logs: [jenkins-1-4dbcz.log](https://github.com/openshiftio/openshift.io/files/1549274/jenkins-1-4dbcz.log)

**Comment by qodfathr** [comment] 2018-01-26 16:59
@vpavlin @joshuawilson do we feel this is still an issue?

**Comment by kishansagathiya** [comment] 2018-04-24 12:24
If I go to the upstream issue, it is created 35 minutes ago from now on (weird! How?)
@rupalibehera Do we know how frequent is this issue?

**Comment by rupalibehera** [comment] 2018-04-24 13:14
@kishansagathiya , I have never seen this issue we need to check if we could reproduce this one

**Comment by vpavlin** [comment] 2018-04-30 10:32
IMO the issue is/was because sometimes Jenkins termination takes longer and the container is killed with timeout, which might result in some data corruption. Sadly, I don't have a clear reproducer.

**Comment by kishansagathiya** [comment] 2018-04-30 10:48
Thanks a lot @vpavlin 

@qodfathr 
The response from @vpavlin and @rupalibehera and the little traction that this issue has created, I think this issue either doesn't occur or occurs very rarely for us to give it any attention. I think it would be safe to close this, WDYT?

**Comment by qodfathr** [comment] 2018-04-30 12:25
I'm not sure we should close this -- it sounds like it's still an issue. But, if we do feel it is very rare, I'm happy removing the p0. Once we feel this is truly eliminated, we can close.

**Comment by kishansagathiya** [comment] 2018-04-30 12:40
@qodfathr The code would have changed a lot since the time this issue was originally created. ATM this is not reproducible. It doesn't seem to me a SEV2 or P0. IMO I would just close it for it is too outdated. If we see this again we can always reopen or create a new one. But I could be wrong, I am pretty new ;) @vpavlin @rupalibehera WDYT?

**Comment by qodfathr** [comment] 2018-04-30 15:09
If others vote to close, I'm okay with closing.

**Comment by ldimaggi** [comment] 2018-04-30 17:31
+1 to closing this issue - I am not seeing IllegalStateExceptions at startup in Jenkins logs.

**Comment by bmicklea** [comment] 2018-04-30 21:05
Closing as fixed. If we find it re-appears we can reopen or create a new (updated) issue.

**Closed by bmicklea** 2018-04-30 21:05 UTC
Labels: SEV2-high, area/jenkins, issue/intermittent, priority/P0, team/build-cd, type/bug
