### ISSUE TITLE
Wrong committer of initial import of quickstart

### ISSUE THREAD

**Issue by ljelinkova-openshift-io** [openshiftio/openshift.io#832] opened 2017-09-18 10:47 UTC
I tried openshift.io for the first time today. The quickstart generated the code and pushed it to my Git repository. Only that the commiter is not me (ljelinkova-openshift-io) but some other user (p-meier). Is this intended? Because when my colleague tried the same thing he was correctly mentioned as commiter. 

https://github.com/ljelinkova-openshift-io/myfirstspace
https://github.com/rhopp/asdfadf

**Comment by rawlingsj** [comment] 2017-09-18 10:53
closing as a duplicate of https://github.com/openshiftio/openshift.io/issues/777

**Closed by rawlingsj** 2017-09-18 10:53 UTC
