### ISSUE TITLE
Unable to create a quickstart in prod-preview.

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#2672] opened 2018-03-19 11:34 UTC
I am using my newly provisioned prod-preview account  to create quick start application in new workspace, and getting the following error after step 1A of the quickstart-wizard.
![screenshot from 2018-03-19 16-44-50](https://user-images.githubusercontent.com/7047079/37593263-5abc8e6c-2b97-11e8-9c6a-915464559bf7.png)

**Comment by sbose78** [comment] 2018-03-19 11:38
This user uses the starter-2a cluster https://auth.prod-preview.openshift.io/api/users/97b6a467-0601-4193-8625-fc5b53b1524c

**Comment by sbose78** [comment] 2018-03-19 11:41
Hi @krishnapaparaju could you please take a look ?

**Comment by sara-02** [comment] 2018-03-19 11:47
Re-tried creating a quickstart and now it is stuck on the step 1B, since last 5-10 mins
![screenshot from 2018-03-19 17-16-43](https://user-images.githubusercontent.com/7047079/37593807-4fa5aea8-2b99-11e8-88dd-b826a866de25.png)

**Comment by sbose78** [comment] 2018-03-19 14:14
@pbergene to update configmaps with the name of the 2a cluster

**Comment by gastaldi** [comment] 2018-03-19 14:26
Can you check if the Github credentials are connected in your Openshift.io account?

**Comment by pbergene** [comment] 2018-03-19 14:26
Checked with @gastaldi, the cms in question are  not used for OSIO

**Comment by ldimaggi** [comment] 2018-03-21 14:01
I am not seeing this problem on prod-preview - but - my account on prod-preview is on free-stg and not 2a.

**Comment by ppitonak** [comment] 2018-03-22 07:29
I can reproduce with my new account on prod-preview.

![osio_preview](https://user-images.githubusercontent.com/445100/37756802-1cc9fb24-2dab-11e8-9d89-b311f4b5642a.png)

**Comment by gastaldi** [comment] 2018-03-22 12:21
@ppitonak I see this error in the logs:

```
2018-03-22 09:34:20,758 SEVERE [org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator] (default task-55) Error while navigating to next step: io.fabric8.forge.generator.keycloak.KeyCloakFailureException: KeyCloak failed to return a token for GitHub on https://auth.prod-preview.openshift.io/api/token?for=https://github.com
```

Have you connected your account with Github before starting this wizard?

**Comment by ppitonak** [comment] 2018-03-22 13:29
Yes, I confirmed now that my GitHub account is linked to my prod-preview account and I can still reproduce. I see following errors in browser console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://forge.api.prod-preview.openshift.io/api/launchpad/commands/fabric8-import-git. (Reason: missing token ‘authorization’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).
```

**Comment by ldimaggi** [comment] 2018-03-22 16:24
I am not able to recreate this error with a newly created user account on prod-preview - the account is provisioned on starter-us-east-2a and not free-stg:

![screenshot from 2018-03-22 12-22-52](https://user-images.githubusercontent.com/642621/37783452-ef281450-2dcb-11e8-8f24-03dc43d06ad9.png)

Is this error unique to only some user accounts on starter-us-east-2a?

**Comment by krishnapaparaju** [comment] 2018-03-22 17:54
@gastaldi any recent changes causing this issue ? Its blocking couple of other teams.

**Comment by gastaldi** [comment] 2018-03-22 17:59
@krishnapaparaju no, no changes were introduced in the legacy-osio-addon.

**Comment by ppitonak** [comment] 2018-03-23 11:03
@ldimaggi @gastaldi @krishnapaparaju  can somebody confirm that only Firefox is affected?

**Comment by sara-02** [comment] 2018-03-23 12:13
@ldimaggi I use Chrome to run OSIO, so I guess it not just a browser issue

**Comment by krishnapaparaju** [comment] 2018-03-24 17:09
Have tested again today, not seeing this issue any more. Strange ..

**Comment by gastaldi** [comment] 2018-03-24 17:35
@ppitonak is right. I see this issue in Firefox only. The CORS headers are the problem, I'll have a look at it on Monday

**Comment by gastaldi** [comment] 2018-03-25 02:55
I am seeing a lot of these errors in the log: 
```
WARN  [io.fabric8.forge.generator.keycloak.ProfileSettings] (default task-12) Could not find the user settings at https://api.prod-preview.openshift.io/api/user due to: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
```

Did something change recently in the Profile service?

**Comment by gastaldi** [comment] 2018-03-25 03:13
CORS headers fixed in prod-preview and prod. @ppitonak can you check if Firefox works now?

**Comment by invincibleJai** [comment] 2018-04-09 18:05
Looks like it has been fixed, hence closing it.

**Closed by invincibleJai** 2018-04-09 18:05 UTC
Labels: SEV2-high, area/app-wizard, area/quickstarts, env/prod-preview, team/analytics/wizard, type/bug
