### ISSUE TITLE
Rolling to stage envrionment is failing for booster created from OSIO Launcher

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2833] opened 2018-03-30 08:14 UTC
Please see the attached logs:

1) Rolling to stage environment is failing:  https://gist.github.com/krishnapaparaju/4b84af55eb8ad9c4e991c3f7226f746b

2) FMP timeout error: https://gist.github.com/krishnapaparaju/97b2e98dddc4c6a691eeb49083f1cb3f

DO NOT see the problem with quick-starts created from current OSIO wizard.

cc @GeorgeActon @hrishin @miteshvp @invincibleJai

**Comment by miteshvp** [comment] 2018-04-02 06:40
I too am able to reproduce this error.

**Comment by miteshvp** [comment] 2018-04-02 07:37
#### Possible Resolution
Setting `Maven Artifact` with a `hyphen -` instead of a `dot .` should solve this. See below snaphsot
<img width="468" alt="image" src="https://user-images.githubusercontent.com/17736013/38187679-533fb9ae-3676-11e8-954b-de2b5add5afc.png">

**Comment by invincibleJai** [comment] 2018-04-02 07:40
Thanks @miteshvp will put the fix for it. @edewit @animuk what would be the default value for above which should come from UI?

**Comment by animuk** [comment] 2018-04-02 07:54
@invincibleJai as discussed, we can use the format as per legacy structure and in artifact, can use -. It should work

**Comment by hrishin** [comment] 2018-04-02 12:58
> FMP timeout error

Weare figuring out this issue. Just wondering if its an issue with FMP HTTP java client or its OSO issue https://github.com/openshiftio/openshift.io/issues/2729

**Comment by invincibleJai** [comment] 2018-04-02 13:00
@hrishin this issue is related to new launcher flow in OSIO which is internal feature as of now. It was caused due to bad value of maven artifact. Have put the fix, once PR gets merged should be resolved

**Comment by invincibleJai** [comment] 2018-04-02 18:55
@hrishin sorry FMP timeout error you can track

**Comment by invincibleJai** [comment] 2018-04-13 08:14
>Rolling to stage environment is failing: https://gist.github.com/krishnapaparaju/4b84af55eb8ad9c4e991c3f7226f746b

This has been fixed

**Comment by rohanKanojia** [comment] 2018-04-24 12:03
Hi @animuk, you can track this `SocketTimeoutException` issue on #3058 . That being said I strongly feel that it's not related to fmp. Although I'm trying to reproduce it and see if I get that stack trace.

**Comment by pradeepto** [comment] 2018-04-25 13:15
@animuk @sivaavkd Please above comment from @rohanKanojia

**Comment by maxandersen** [comment] 2018-05-01 07:05
closing this as it looks as a true duplicate of https://github.com/openshiftio/openshift.io/issues/3058

**Closed by maxandersen** 2018-05-01 07:05 UTC
Labels: SEV2-high, area/launcher, priority/P0, team/build-cd, type/bug
