### ISSUE TITLE
Che workspace fails to start due to 'Unauthorized!' error

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#4622] opened 2018-12-07 13:36 UTC
##### Issue Overview

When creating a new application via the launcher and trying to create and open the Che workspace,
it cannot be started and the following Error dialog is shown:

![image](https://user-images.githubusercontent.com/3263627/49650596-09d18b00-fa2d-11e8-8a03-fb424ebaeb55.png)

The Error message is:
```
Could not start Workspace test123-wkkyw. Reason: Failure executing: GET at: 
https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/osio-ci-ee8-che/persistentvolumeclaims. 
Message: Unauthorized! Configured service account doesn't have access. Service account may
have been revoked.. The error may be caused by an expired token or changed password.
Update Che server deployment with a new token or password.
```

##### Additional Information
Cluster: `starter-us-east-2a`

**Comment by ibuziuk** [comment] 2018-12-07 13:58
@pmacik please, provide info about your user / `identity_id`

**Comment by pmacik** [comment] 2018-12-07 14:09
> @pmacik please, provide info about your user / `identity_id`

I have several accounts for testing and I tried this with `osio-ci-ee8` and `osio-ci-ee9`. It happens in both cases.

**Comment by ljelinkova** [comment] 2018-12-07 14:11
It happened for my ljelinko-preview account as well.

**Comment by ibuziuk** [comment] 2018-12-07 14:15
cc: @alexeykazakov @nurali-techie similar problem I had on prod-preview with my user (`a04ab657-b7ca-408a-9243-da60057e719d / ibuziuk@redhat.com) provisioned against `free-stg`. Could the root case be the same as in https://github.com/fabric8-services/fabric8-tenant/issues/697

**Comment by pmacik** [comment] 2018-12-07 14:16
> Will check the other accounts...

It happens on `osio-ci-ee1`, too.

I also tried account on `starter-us-east-2` (`pmacik@redhat.com`), and it did not happen.

**Comment by ppitonak** [comment] 2018-12-07 14:16
Probably just a different symptom of the same root cause (expired access token), related to #4598

**Comment by ibuziuk** [comment] 2018-12-07 14:22
@nurali-techie @alexeykazakov I'm going to switch all prod users back to usage of OSIO user token (on prod-preview  Che would still be using Che SA Token for communications with oso-proxy, so that we could continue investigation). Let me know if this works for you ?

**Comment by ibuziuk** [comment] 2018-12-07 14:33
@ppitonak @pmacik @ljelinkova it seems to be problem related to token for particular clusters. For example all seem to work fine for users provisioned against `us-east-2`
I suspect QA team has test users on every single starter cluster. Could you please provide info on which clusters workspace startup works fine and on which it fails ? It would be super helpful for further investigation

**Comment by pmacik** [comment] 2018-12-07 14:35
> Could you please provide info on which clusters workspace startup works fine and on which it fails ? It would be super helpful for further investigation

For me, the problem happens on `starter-us-east-2a` and do not happen on `starter-us-east-2`.

**Comment by ppitonak** [comment] 2018-12-07 15:40
I can confirm that from e2e tests PoV, only `starter-us-east-2a` is affected.

**Comment by alexeykazakov** [comment] 2018-12-07 16:06
Yes, cluster tokens got invalidated. The SD team is working on updating them.

**Comment by alexeykazakov** [comment] 2018-12-07 19:10
This should be fixed by now. Please reopen if it still doesn't work.

**Comment by pmacik** [comment] 2018-12-10 09:01
> This should be fixed by now. Please reopen if it still doesn't work.

@alexeykazakov It still does not work:
![image](https://user-images.githubusercontent.com/3263627/49720642-a2038600-fc60-11e8-8f39-473374828ff3.png)

Checked with accounts on the `us-east-2a` cluster where id does not work:
* `osio-ci-boost1`
* `osio-ci-boost2`
* `osio-ci-boost3`
* `osio-ci-ee9`

The account on the `us-east-2` cluster works fine:
* `pmacik@redhat.com`

**Comment by ljelinkova** [comment] 2018-12-10 09:32
Added SEV1 and P1 since this affects all users provisioned on 2a clusters + all e2e jobs running with 2a cluster users (including PR checks to SAAS and fabric8-ui repository).

**Comment by ibuziuk** [comment] 2018-12-10 09:37
@alexeykazakov I have switched all the prod users to use OSIO user token instead of Che SA token for communications with oso-proxy by changing `che.serviceaccount.lockdown` strategy from `default` to `userWithId` on prod (on prod-preview still `default` strategy & Che SA token for communications with oso-proxy are used). 

@ljelinkova @pmacik please re-test workspace creation against problematic accounts now

**Comment by nurali-techie** [comment] 2018-12-10 09:43
I checked oso-proxy logs and I can see the issue (401 Unauthorized) happening with `api.starter-us-east-2a.openshift.com` from `2018-12-10T03:14:27Z`.

```
time="2018-12-10T03:14:27Z" level=error msg="Cache resolve failed, Call to 'https://api.starter-us-east-2a.openshift.com/api/v1/namespaces/osio-ci-e2e-001-preview-che/serviceaccounts/che' failed with status '401 Unauthorized'"
```
kibana logs: [link](https://logs.dsaas-stg.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-08T21:30:00.000Z',mode:absolute,to:'2018-12-09T04:30:00.000Z'))&_a=(columns:!(_source),index:'project.dsaas-preview.6e520a9f-d097-11e8-9fb7-121499db9246.*',interval:auto,query:(query_string:(query:'kubernetes.labels.deploymentconfig:%22f8osoproxy%22%20AND%20%22api.starter-us-east-2a.openshift.com%22%20AND%20%22serviceaccounts%2Fche%22')),sort:!('@timestamp',desc)))
query: `kubernetes.labels.deploymentconfig:"f8osoproxy" AND "api.starter-us-east-2a.openshift.com" AND "serviceaccounts/che"`

**Comment by ljelinkova** [comment] 2018-12-10 09:59
I tried with user ```osio-ci-e2e-007``` and it still does not work (the same error).

**Comment by pmacik** [comment] 2018-12-10 10:03
> @ljelinkova @pmacik please re-test workspace creation against problematic accounts now

Tried with `osio-ci-ee9` and it still does not work, too.

**Comment by ibuziuk** [comment] 2018-12-10 11:09
> I checked oso-proxy logs and I can see the issue (401 Unauthorized) happening with api.starter-us-east-2a.openshift.com

Any ideas why does it happen ? It looks like it the token used does not really mater and it is reproducible against both Che SA token and OSIO user token

@pmacik @ljelinkova `osio-ci-e2e-007` / `osio-ci-ee9` those are prod accounts, right ? Also does `2a` cluster is the only one that is affected ? Could QA provide information about all other starter clusters:

- 1a
- 1b
- 2 
- 2a 
- free-stg 
- etc.

**Comment by nurali-techie** [comment] 2018-12-10 11:17
@ibuziuk we have restarted oso-proxy service (for safer side) and I tired to start_che_workspace for my user (nvirani-preview) on prod-preview.  It gives `HTTP 404 - Not found`.

I am investigating on the same.

**Comment by ljelinkova** [comment] 2018-12-10 11:51
@ibuziuk Yes, the 2a cluster was the only one affected - no other jobs failed with this issue.

**Comment by pmacik** [comment] 2018-12-10 11:59
`osio-ci-ee9` is prod account on `2a`.

**Comment by ibuziuk** [comment] 2018-12-10 12:39
@ljelinkova could you confirm that `free-stg` is not affected ?

**Comment by ljelinkova** [comment] 2018-12-10 12:41
@ibuziuk I am sorry we do not have any user accounts on free-stg.

**Comment by ibuziuk** [comment] 2018-12-10 12:43
@ljelinkova ok, which clusters are covered by test users ?

**Comment by nurali-techie** [comment] 2018-12-10 12:53
@ibuziuk @pmacik we have fix some issue on our side.  Now, I am able to start_che_ws for my user which is hosted on `api.starter-us-east-2a.openshift.com`.  Can you plz check now start_che_ws for your users ??

**Comment by jarifibrahim** [comment] 2018-12-10 13:01
I was facing this issue but I see a different failure now. See https://github.com/openshiftio/openshift.io/issues/4627

**Comment by ljelinkova** [comment] 2018-12-10 13:02
@ibuziuk Tests cover users on 1, 1a, 2 and 2a (prod + prod-preview). They do not cover free-stg.

**Comment by ibuziuk** [comment] 2018-12-10 13:03
>  we have fix some issue on our side

were the fixes applied on both prod & prod-preview ?

**Comment by nurali-techie** [comment] 2018-12-10 13:08
@ibuziuk till now I was investigated start_che_ws issue on prod-preview only.  So now, start_che_ws should work on prod-preview.
Let me also check what's going on `prod` now.  Can you plz point me to user and cluster for which start_che_ws issue is encountered ??

**Comment by ibuziuk** [comment] 2018-12-10 13:13
@nurali-techie I believe those are `osio-ci-e2e-007 / osio-ci-ee9`. I will switch all prod users back for usage of the Che SA token.

**Comment by ljelinkova** [comment] 2018-12-10 14:31
@pmacik I think that is different issue because it occurs on all clusters. I've reported it here

https://github.com/openshiftio/openshift.io/issues/4626

**Comment by ibuziuk** [comment] 2018-12-10 14:31
@pmacik this seems to be a different () error - https://github.com/openshiftio/openshift.io/issues/4627 not related to SA token.

**Comment by pmacik** [comment] 2018-12-10 14:34
@ljelinkova @ibuziuk Got it, thanks.

**Comment by nurali-techie** [comment] 2018-12-10 14:36
@ibuziuk @pmacik yes, it's unrelated error.  Kindly confirm if `401` is solved which I assume as with `osio-ci-ee9` user on `prod` not getting `401` anymore .. right ??
If so then would you fine to close this issue and create new for new error ??

**Comment by pmacik** [comment] 2018-12-10 14:40
@nurali-techie Yes, I don't see the `401` anymore, so I assume this issue can be closed.
The other issue is already covered by https://github.com/openshiftio/openshift.io/issues/4626

**Closed** 2018-12-10 14:43 UTC
Labels: SEV1-urgent, area/che, area/multi-cluster, area/workspaces, env/prod, env/prod-preview, priority/P1, team/che/osio, team/platform, type/bug, type/incident-report

**Comment by xcoulon** [comment] 2018-12-10 14:47
@pmacik can you confirm it's also good for you on production ? (I'm not sure to which env the `osio-ci-ee9` account is associated)

**Comment by ppitonak** [comment] 2018-12-10 15:44
I can confirm that `osio-ci-e2e-007`is OK (prod env).
