### ISSUE TITLE
Che - Run throws error when multiple Run tabs are launched

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1610] opened 2017-12-11 07:12 UTC
Not sure if this is a valid scenario but filing the issue anyway.

1. Launch Che
2. Make changes to code
3. Click on Run. 
4. Deployment successful. Preview URL works.
![runworks](https://user-images.githubusercontent.com/1892722/33819367-00e4b2b8-de42-11e7-9e1a-27c56d7e69ad.png)

5. I click on Run again. I get the below error
![runerror](https://user-images.githubusercontent.com/1892722/33819410-34912fb0-de42-11e7-84a2-6707bc6d7080.png)

**Comment by sbose78** [comment] 2017-12-11 07:18
Thanks @nimishamukherjee  !

I just went through the error message and it says "Address already in use" which is probably because you were already running it ( and the same port is already in use ) ?

**Comment by nimishamukherjee** [comment] 2017-12-11 07:56
@sbose78 I guess so. In that case the Run tab could be disabled?

**Comment by slemeur** [comment] 2017-12-11 10:37
When you hit the button run, it starts a new process in your workspace. Until this process is running, you have a dedicated tab to see how this process is behaving (in some case you can interact with it too) and access the logs/outputs. 
We can't dismiss the process tab until the process is still running. 

I believe, you have been trapped because, you wanted to re-execute the "run" command. Also, please note, that you have live "hot deploy" in this booster which automatically updates the application - so you don't need to re-execute the "run" command.

In some cases, it could make sense to have an option in the command's settings to allow stoping previous execution of the command. This way, if the "run" button is clicked a second time, it will stop the currently running process and start a new one.

**Comment by ibuziuk** [comment] 2017-12-20 17:51
@nimishamukherjee closing, since this is considered to be expected behavior (while using desktop IDE like Eclipse / InteliJ you would get the very same UX). Please, feel free to open new issue against https://github.com/eclipse/che if you think that having preferences for disabling subsequent run commands should be in place

**Closed by ibuziuk** 2017-12-20 17:51 UTC
Labels: area/che, type/question
