### ISSUE TITLE
Planner - Description section becomes blank on editing any other property 

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#3114] opened 2018-04-13 05:01 UTC
In Planner while editing any other property of a work-item makes the description details disappear.

Steps to reproduce
1. Click on any existing work-item having description details filled in.
2. Edit any other property like title/area/iteration/labels. 
3. On save, the description details just disappears.

**Comment by miteshvp** [comment] 2018-04-13 05:02
I am not an expert, but is it a side-effect of the fix for https://github.com/fabric8-ui/fabric8-planner/pull/2509

**Comment by nimishamukherjee** [comment] 2018-04-13 05:15
Assigned Sev3 as the content is not lost. If you navigate back to the work item, the description shows up.

**Comment by miteshvp** [comment] 2018-04-13 05:36
@nimishamukherjee - yes that's correct. Content is not lost, but seeing the description went blank, if a user tries to add some details, and save them, original content gets lost. As a first-time user, it was a natural instinct to type those details again.

**Comment by vikram-raj** [comment] 2018-04-13 05:45
Duplicate #3000

**Comment by samuzzal-choudhury** [comment] 2018-07-26 04:37
I replicated this issue today. My descriptions disappeared from the planner. Here is a screenshot

![image](https://user-images.githubusercontent.com/17740190/43241952-a26d4ef2-90bb-11e8-942b-1fe46ef36f60.png)

cc: @miteshvp @GeorgeActon

**Comment by samuzzal-choudhury** [comment] 2018-07-26 05:13
FYI - I had to rewrite the description in the work item to make it appear again.

**Comment by rgarg1** [comment] 2018-07-26 05:55
@samuzzal-choudhury Could you pls list some steps to reproduce this problem. I'm unable to reproduce this. We recently fixed a similar issue: https://github.com/openshiftio/openshift.io/issues/3842

**Comment by joshuawilson** [comment] 2018-10-31 00:02
Closing. If you can provide steps to reproduce it then please reopen.

**Closed by joshuawilson** 2018-10-31 00:02 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
