### ISSUE TITLE
Launcher: npm link not working for ngx-forge to fabric8-ui

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#3886] opened 2018-07-02 10:48 UTC
- at present npm link from ngx-launcher to fabric8-ui is not working.

**Comment by GeorgeActon** [comment] 2018-07-06 18:52
@jyasveer @animuk please set type, and if bug set severity

**Comment by GeorgeActon** [comment] 2018-07-26 09:46
@jyasveer label this correctly & set Severity

**Comment by bartoszmajsak** [comment] 2018-07-26 11:04
@GeorgeActon is your team going to work on it this sprint? @vikram-raj stumbled upon the same issue and might help to sort this out. 

See #4078

**Comment by jyasveer** [comment] 2018-07-26 12:43
@GeorgeActon i have updated the labels now

**Comment by GeorgeActon** [comment] 2018-07-26 12:47
@bartoszmajsak that explains Anindya's comment that Vikram was goig to work on this.

@animuk  if this is a duplicate of the one that @vikram-raj then one of these should be closed as a duplicate. Coordinate with Vikram

**Comment by bartoszmajsak** [comment] 2018-08-11 09:30
I don't see it as a user facing bug, it's engineering tooling problem. Shall we keep it as bug for your aggregation @stevengutz @GeorgeActon?

**Comment by invincibleJai** [comment] 2018-08-13 07:28
it's a duplicate of https://github.com/openshiftio/openshift.io/issues/4078 , and @vikram-raj was looking into it. I think this can be cosed.

**Comment by animuk** [comment] 2018-08-13 07:32
Closing as it is duplicate of #4078

**Closed by animuk** 2018-08-13 07:32 UTC
Labels: SEV3-medium, area/launcher, priority/P4, team/analytics/wizard, type/bug
