### ISSUE TITLE
[Create Space] button on _myspaces page opens obsolete legacy wizard

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#3597] opened 2018-05-21 14:48 UTC
![image](https://user-images.githubusercontent.com/3263627/40313739-b906f560-5d16-11e8-92d8-3f34dff81b2e.png)
![image](https://user-images.githubusercontent.com/3263627/40313754-c0fac2ec-5d16-11e8-944a-bf547008901b.png)

**Comment by pmacik** [comment] 2018-05-21 14:50
Happens to a user with all feature levels.

**Comment by andrewazores** [comment] 2018-05-23 17:43
Duplicate of https://github.com/openshiftio/openshift.io/issues/3576

**Closed by andrewazores** 2018-05-23 17:43 UTC
Labels: SEV2-high, area/space-wizard, area/spaces, env/prod, team/analytics/wizard, team/platform, type/bug
