### ISSUE TITLE
Performance is slow in OSIO workflow (in places)

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#1570] opened 2017-12-08 16:32 UTC
During a time of high activity (the December mass-test effort) the following performance issues were noted during an OSIO 'Getting Started Guide' walkthrough:

Che workspace was slow to start (~ 1 minute)
Pipeline was slow to start after a push (~ 1 minute)

I'm not sure what we consider acceptable wait times, these may be ok (or not).

**Comment by ibuziuk** [comment] 2018-01-03 16:42
@slemeur in terms of Che startup time - it would be significantly improved in Che6. Also, could we change it to SEV3 ?

**Comment by ldimaggi** [comment] 2018-01-03 18:31
Rick - are you seeing this?   https://github.com/openshiftio/openshift.io/issues/1731

**Comment by RickJWagner** [comment] 2018-01-03 19:11
Hi @ldimaggi,
I've just started a new project (after resetting environment, to be sure I've got a good start).  3 minutes have passed, the build is static and reports status as "not started".
I believe I am seeing the problem.

**Comment by RickJWagner** [comment] 2018-01-03 19:17
Some things that may be of interest:
- Signing on via CLI, switching to project 'rhn-support-rick-jenkins', then using oc get events, we find:
-   Readiness probe failed: Get http://10.129.105.157:8080/login: net/http: request canceled
- A few other lines that don't seem 'normal'....
---------------------------------------------------------- Events from list ------------------------------------
LASTSEEN   FIRSTSEEN   COUNT     NAME                          KIND                    SUBOBJECT                             TYPE      REASON                        SOURCE                                                  MESSAGE
5m         5m          1         content-repository-1-deploy   Pod                                                           Normal    Scheduled                     {default-scheduler }                                    Successfully assigned content-repository-1-deploy to ip-172-31-67-217.us-east-2.compute.internal
5m         5m          1         content-repository-1-deploy   Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-67-217.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "deployer-token-wlg4v" 
5m         5m          1         content-repository-1-deploy   Pod                     spec.containers{deployment}           Normal    Pulling                       {kubelet ip-172-31-67-217.us-east-2.compute.internal}   pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.7.9"
5m         5m          1         content-repository-1-deploy   Pod                     spec.containers{deployment}           Normal    Pulled                        {kubelet ip-172-31-67-217.us-east-2.compute.internal}   Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.7.9"
5m         5m          1         content-repository-1-deploy   Pod                     spec.containers{deployment}           Normal    Created                       {kubelet ip-172-31-67-217.us-east-2.compute.internal}   Created container
5m         5m          1         content-repository-1-deploy   Pod                     spec.containers{deployment}           Normal    Started                       {kubelet ip-172-31-67-217.us-east-2.compute.internal}   Started container
5m         5m          1         content-repository-1-deploy   Pod                     spec.containers{deployment}           Normal    Killing                       {kubelet ip-172-31-67-217.us-east-2.compute.internal}   Killing container with id docker://deployment:Need to kill Pod
5m         5m          1         content-repository-1-wm5bc    Pod                                                           Normal    Scheduled                     {default-scheduler }                                    Successfully assigned content-repository-1-wm5bc to ip-172-31-68-183.us-east-2.compute.internal
5m         5m          1         content-repository-1-wm5bc    Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-68-183.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "default-token-xx333" 
5m         5m          1         content-repository-1-wm5bc    Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-68-183.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "pvc-5d20ecdf-f0b9-11e7-a7ca-0233cba325d9" 
5m         5m          1         content-repository-1-wm5bc    Pod                     spec.containers{content-repository}   Normal    Pulling                       {kubelet ip-172-31-68-183.us-east-2.compute.internal}   pulling image "fabric8/caddy-server:v9274a15"
5m         5m          1         content-repository-1-wm5bc    Pod                     spec.containers{content-repository}   Normal    Pulled                        {kubelet ip-172-31-68-183.us-east-2.compute.internal}   Successfully pulled image "fabric8/caddy-server:v9274a15"
5m         5m          1         content-repository-1-wm5bc    Pod                     spec.containers{content-repository}   Normal    Created                       {kubelet ip-172-31-68-183.us-east-2.compute.internal}   Created container
5m         5m          1         content-repository-1-wm5bc    Pod                     spec.containers{content-repository}   Normal    Started                       {kubelet ip-172-31-68-183.us-east-2.compute.internal}   Started container
5m         5m          1         content-repository-1          ReplicationController                                         Normal    SuccessfulCreate              {replication-controller }                               Created pod: content-repository-1-wm5bc
5m         5m          1         content-repository-3-wbp9v    Pod                     spec.containers{content-repository}   Normal    Killing                       {kubelet ip-172-31-65-222.us-east-2.compute.internal}   Killing container with id docker://content-repository:Need to kill Pod
5m         5m          1         content-repository-3          ReplicationController                                         Normal    SuccessfulDelete              {replication-controller }                               Deleted pod: content-repository-3-wbp9v
5m         5m          1         content-repository            DeploymentConfig                                              Normal    ReplicationControllerScaled   {deploymentconfig-controller }                          Scaled replication controller "content-repository-3" from 1 to 0
5m         5m          1         content-repository            DeploymentConfig                                              Normal    DeploymentCreated             {deploymentconfig-controller }                          Created new replication controller "content-repository-1" for version 1
5m         5m          1         content-repository            PersistentVolumeClaim                                         Normal    ProvisioningSucceeded         {persistentvolume-controller }                          Successfully provisioned volume pvc-5d20ecdf-f0b9-11e7-a7ca-0233cba325d9 using kubernetes.io/aws-ebs
5m         5m          1         jenkins-1-c6w64               Pod                                                           Normal    Scheduled                     {default-scheduler }                                    Successfully assigned jenkins-1-c6w64 to ip-172-31-68-153.us-east-2.compute.internal
5m         5m          1         jenkins-1-c6w64               Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-68-153.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "jenkins-token-88q77" 
5m         5m          1         jenkins-1-c6w64               Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-68-153.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "jenkins-config" 
5m         5m          1         jenkins-1-c6w64               Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-68-153.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "pvc-5d29ec95-f0b9-11e7-a7ca-0233cba325d9" 
5m         5m          1         jenkins-1-c6w64               Pod                     spec.containers{jenkins}              Normal    Pulling                       {kubelet ip-172-31-68-153.us-east-2.compute.internal}   pulling image "fabric8/jenkins-openshift:v1106381"
5m         5m          1         jenkins-1-c6w64               Pod                     spec.containers{jenkins}              Normal    Pulled                        {kubelet ip-172-31-68-153.us-east-2.compute.internal}   Successfully pulled image "fabric8/jenkins-openshift:v1106381"
5m         5m          1         jenkins-1-c6w64               Pod                     spec.containers{jenkins}              Normal    Created                       {kubelet ip-172-31-68-153.us-east-2.compute.internal}   Created container
5m         5m          1         jenkins-1-c6w64               Pod                     spec.containers{jenkins}              Normal    Started                       {kubelet ip-172-31-68-153.us-east-2.compute.internal}   Started container
3m         4m          10        jenkins-1-c6w64               Pod                     spec.containers{jenkins}              Warning   Unhealthy                     {kubelet ip-172-31-68-153.us-east-2.compute.internal}   Readiness probe failed: HTTP probe failed with statuscode: 503
2m         4m          3         jenkins-1-c6w64               Pod                     spec.containers{jenkins}              Warning   Unhealthy                     {kubelet ip-172-31-68-153.us-east-2.compute.internal}   Readiness probe failed: Get http://10.129.105.157:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
5m         5m          1         jenkins-1-deploy              Pod                                                           Normal    Scheduled                     {default-scheduler }                                    Successfully assigned jenkins-1-deploy to ip-172-31-68-243.us-east-2.compute.internal
5m         5m          1         jenkins-1-deploy              Pod                                                           Normal    SuccessfulMountVolume         {kubelet ip-172-31-68-243.us-east-2.compute.internal}   MountVolume.SetUp succeeded for volume "deployer-token-wlg4v" 
5m         5m          1         jenkins-1-deploy              Pod                     spec.containers{deployment}           Normal    Pulling                       {kubelet ip-172-31-68-243.us-east-2.compute.internal}   pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.7.9"
5m         5m          1         jenkins-1-deploy              Pod                     spec.containers{deployment}           Normal    Pulled                        {kubelet ip-172-31-68-243.us-east-2.compute.internal}   Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.7.9"
5m         5m          1         jenkins-1-deploy              Pod                     spec.containers{deployment}           Normal    Created                       {kubelet ip-172-31-68-243.us-east-2.compute.internal}   Created container
5m         5m          1         jenkins-1-deploy              Pod                     spec.containers{deployment}           Normal    Started                       {kubelet ip-172-31-68-243.us-east-2.compute.internal}   Started container
5m         5m          1         jenkins-1                     ReplicationController                                         Normal    SuccessfulCreate              {replication-controller }                               Created pod: jenkins-1-c6w64
5m         5m          1         jenkins-3-bglhz               Pod                     spec.containers{jenkins}              Normal    Killing                       {kubelet ip-172-31-67-217.us-east-2.compute.internal}   Killing container with id docker://jenkins:Need to kill Pod
5m         5m          1         jenkins-3                     ReplicationController                                         Normal    SuccessfulDelete              {replication-controller }                               Deleted pod: jenkins-3-bglhz
5m         5m          1         jenkins-home                  PersistentVolumeClaim                                         Normal    ProvisioningSucceeded         {persistentvolume-controller }                          Successfully provisioned volume pvc-5d29ec95-f0b9-11e7-a7ca-0233cba325d9 using kubernetes.io/aws-ebs
5m         5m          1         jenkins-mvn-local-repo        PersistentVolumeClaim                                         Normal    ProvisioningSucceeded         {persistentvolume-controller }                          Successfully provisioned volume pvc-5d31e43b-f0b9-11e7-a7ca-0233cba325d9 using kubernetes.io/aws-ebs
5m         5m          1         jenkins                       DeploymentConfig                                              Normal    ReplicationControllerScaled   {deploymentconfig-controller }                          Scaled replication controller "jenkins-3" from 1 to 0
5m         5m          1         jenkins                       DeploymentConfig                                              Normal    DeploymentCreated             {deploymentconfig-controller }                          Created new replication controller "jenkins-1" for version 1

**Comment by krishnapaparaju** [comment] 2018-03-23 10:34
@RickJWagner are you still able to reproduce this problem ?
Closing this issue as I could not reproduce this issue.  Please feel free to reopen if you come across this issue.

**Closed by krishnapaparaju** 2018-03-23 10:34 UTC
Labels: SEV2-high, area/architecture/performance, area/che, area/pipelines, team/build-cd, team/che, type/bug

**Comment by bartoszmajsak** [comment] 2018-03-23 19:42
@krishnapaparaju what were the steps you took in order to reproduce it? I can try to confirm that on my side too.

Also curious what was the output of `oc get events` on your side?

**Comment by joshuawilson** [comment] 2018-03-23 19:43
@krishnapaparaju this effected 2 features and was approved by PM. Why did you close it?
