### ISSUE TITLE
Analytics report not generated after a successful build

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3744] opened 2018-06-06 09:23 UTC
The E2E tests encountered this issue when the stack report is not generated even when the build was successful. 

You can see the screenshot here:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/79/e2e-0605-230714_7.png

Probably the same issue as here (I do not have right to re-open): https://github.com/openshiftio/openshift.io/issues/2694

If you need some OC logs we can add retrieving of them to our E2E tests.

**Comment by miteshvp** [comment] 2018-06-06 11:39
@ljelinkova - it will be great if you could share some logs as well. Thanks.

**Comment by ljelinkova** [comment] 2018-06-06 11:43
Please specify what you mean by 'logs'. We run the following script when the pipeline is finished - we could put there whatever you like. 

https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/oc-get-jenkins-logs.sh

This is the report from the build when analyses failed. 

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/79/oc-logs-output.txt

**Comment by joshuawilson** [comment] 2018-06-06 12:03
Please add labels.

**Comment by miteshvp** [comment] 2018-06-06 12:27
@ljelinkova - please provide jenkins logs for which the test resulted into failure. Also, if you have any web console logs, e.g. when you get an empty stack report even though build succeeds.

**Comment by ljelinkova** [comment] 2018-06-06 12:34
This is the Jenkins log
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/79/pipelines-log.html

I am afraid we do not have any web console logs. As I said before - we can query oc using command line but need to know what you need.

**Comment by miteshvp** [comment] 2018-06-06 12:45
@invincibleJai @arunkumars08 @jyasveer - this looks to me like an issue with dashboard somewhere. Stack id for this build is `3b4e6263a05e42feb17cf65fee7138f4` and report seems to be generated properly. Can one of you please look into this issue.
cc @animuk

**Comment by arunkumars08** [comment] 2018-06-07 05:28
@miteshvp Looking into it. 
@ljelinkova Is this happening always during End to end tests? or is it random?
Also, could you, just to make sure, check the create -> pipelines tab and see if the stack report is not appearing there as well against the builds?

**Comment by arunkumars08** [comment] 2018-06-07 05:38
@ljelinkova Just one more thing I would like you to verify.

Steps:

1. Open the network tab (Filter by XHR) - Also in the filter-text box place this '**build**'
2. Reload the page
3. Ideally, you should see 2 builds and 2 buildconfigs shown
4. Click on the Second **builds**
5. On the right side, expand the response
6. Expand items
7. find the application name that you have given while creating the quick starts under **metadata** -> **name**
8. Open the **annotations** for that found **metadata**
9. Do you find this key present **fabric8.io/bayesian.analysisUrl** with some value assigned to it?

Thanks for your patience in trying out a lot of steps.

PFA, the image to help you understand better.


Please let me know in case of any problems in following the steps.

<img width="1274" alt="screen shot 2018-06-07 at 11 04 16 am" src="https://user-images.githubusercontent.com/7880465/41080223-0d8f6d72-6a43-11e8-817e-754dcd755ff8.png">

**Comment by ljelinkova** [comment] 2018-06-27 12:50
Sorry it took me so long, I've completely forgotten about this issue. But it has occurred today again so I was able to run through your steps. It seems that the `fabric8.io/bayesian.analysisUrl` key is not present.

![analytics](https://user-images.githubusercontent.com/2078072/41974854-66758986-7a19-11e8-87f6-757c0504471c.png)

**Comment by ppitonak** [comment] 2018-06-28 12:43
I managed to reproduce couple of minutes ago

```
"fabric8.io/bayesian.analysisUrl": "https://recommender.api.openshift.io/api/v1/stack-analyses/c0f13bedf49c4410bd479bde4ab6b055",
```

**Comment by ljelinkova** [comment] 2018-07-16 12:29
Any updates on this issue?

**Comment by miteshvp** [comment] 2018-07-16 13:50
@invincibleJai or @jyasveer - can one of you take this over. 
There are two issues it seems.
For stack-id `c0f13bedf49c4410bd479bde4ab6b055` that Pavel P has got, uses unknown dependencies. Could it be the case of not showing stack report if we do not get any known dependencies?
For stack-id `3b4e6263a05e42feb17cf65fee7138f4` , everything looks perfect from backend. Was it because stack report may not have been generated within certain time? What are those conditions to display a stack report on dashboard page? How many times do we poll and what happens in case of failures?

**Comment by invincibleJai** [comment] 2018-07-16 13:51
@jyasveer needed your help here.

**Comment by jyasveer** [comment] 2018-07-16 16:47
@invincibleJai @miteshvp @ppitonak let me have a look

**Comment by ppitonak** [comment] 2018-07-25 11:21
Happened again on prod-preview with account `osio-ci-e2e-002-preview`, space `e2e-0725-044225`

**Comment by invincibleJai** [comment] 2018-07-25 11:45
@ppitonak thanks @jyasveer is looking into this what we have observed is if `fabric8.io/bayesian.analysisUrl` annotation is not present, so stack-report link din't appear and did you get the chance to look at 

```
"fabric8.io/bayesian.analysisUrl": "https://recommender.api.openshift.io/api/v1/stack-analyses/*",
```

was above key present?

even jenkins log would be of help if you can share, log should have : 

`
[Pipeline] echo
Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/XXXX' to Build XXXX
`

**Comment by ldimaggi** [comment] 2018-07-25 12:41
Seeing the same issue here too:

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/376/

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/

**Comment by jyasveer** [comment] 2018-07-25 13:20
@ljelinkova @ppitonak @ldimaggi 
One question to clarify. Do you people see the stack report link on the pipeline page ?
cc @invincibleJai

**Comment by ppitonak** [comment] 2018-07-25 13:29
This one was prod

**Comment by ppitonak** [comment] 2018-07-25 13:36
We discussed two examples today:

prod:
* account osio-ci-e2e-003
* space e2e-0725-100622
* Jenkins log snippet: Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/878236943d0045258e8e85f38957938e' to Build e2e-0725-100622-1
* pipeline screenshot http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/376/05-02-afterEach.png
* dashboard screenshot http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/376/07-01-afterEach.png

prod-preview:
* account osio-ci-e2e-002-preview
* space e2e-0725-044225
* Jenkins log snippet: Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.prod-preview.openshift.io/api/v1/stack-analyses/49fb31aba99d46699f0761f9debb2c25' to Build e2e-0725-044225-1
* pipeline screenshot http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/1047/05-02-afterEach.png
* dashboard screenshot http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/1047/07-01-afterEach.png

**Comment by jyasveer** [comment] 2018-07-25 13:40
If the annotation is getting created, we should see the stack report link. Have to dig into the code and check. Thanks for all your inputs

**Comment by jyasveer** [comment] 2018-07-25 14:09
I just executed 2 builds in my space. I am not able to reproduce the issue. Let me try out some more times and see if I can reproduce the error

**Comment by ljelinkova** [comment] 2018-08-01 07:32
This has started to happen 100% times on prod-preview. Could you have a look?

@jyasveer

**Comment by jyasveer** [comment] 2018-08-01 12:14
@ljelinkova let me try it out and see if i can reproduce the issue.

**Comment by jyasveer** [comment] 2018-08-01 15:54
@ljelinkova i tried to create a space and a app with Rest and Vertx and it worked totally fine for me in the prod preview.

**Comment by bartoszmajsak** [comment] 2018-08-01 16:00
What about Throntail + any existing mission?

**Comment by ldimaggi** [comment] 2018-08-01 16:32
@bartoszmajsak 
Two separate issues - If there are problems related to Thorntail and builds, analytic reports, etc., we should log those problems in separate github issues.

The problem described in #3744 is that historically we have seen random/intermittent instances of analytics reports not being generated. What changed on August 1 is that for several hours no analytics reports were generated on prod-preview.

**Comment by bartoszmajsak** [comment] 2018-08-01 17:07
But those reports are generated for given stacks. Having a rename in mind I was wondering if that could be the problem of that re-occurring right now.

**Comment by ldimaggi** [comment] 2018-08-01 17:09
@bartoszmajsak 
Ah - now I see your point - unfortunately, that bug is back into hiding - I was just able to create an analytcis report (REST/Thorntail) on prod-preview.

**Comment by jyasveer** [comment] 2018-08-23 11:47
As I had already said in my previous comments, this is working as expected. I am closing it for now. Please reopen if you see this again. Thanks

**Comment by ppitonak** [comment] 2018-09-03 08:17
It appeared again 4 hours ago on prod-preview
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/2006/

**Comment by jyasveer** [comment] 2018-09-10 09:10
@ppitonak 
Once  build is successful 10 seconds should be good to receive annotations from build which will have Stack-ID, then a GET call is made to stack-analysis (analytics Service) which ideally won't take more then couple of seconds.

It takes more is dependencies are more to be analyzed @Mitesh can add more detail here. So overall i feel 15-20 seconds should be good enough.

On diff note if some API calls fails due to `ERR: cert invalid or 500` , is it being captured somewhere ? As at times this also may be a possibility as in https://github.com/openshiftio/openshift.io/issues/2755.
which would make E2E fail.
cc @miteshvp @invincibleJai

**Comment by ppitonak** [comment] 2018-09-12 12:09
I changed the test but it failed for me once when running tests locally.

Jenkins log contains `Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/8f0b00fc7c9849029d868ca5ef8442cb' to Build e2e-0912-1331-914-1`

I tried to refresh space dashboard multiple times but the analytics report is not available even after 25 minutes. The only error/warning in the browser console is this one:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.openshift.io/api/token?for=https%3A%2F%2Fgithub.com. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by invincibleJai** [comment] 2018-10-04 15:44
These failures were due to a diff issue as a result 401s were observed in prod-preview, which has been taken care of now.

**Comment by invincibleJai** [comment] 2018-10-04 15:50
@yzainee yousuf can you pls help with this. Needed your build expertise ;)

**Comment by yzainee** [comment] 2018-10-05 04:54
@ppitonak @invincibleJai I need the jenkins logs. Please share the link if you have them

**Comment by invincibleJai** [comment] 2018-10-05 06:10
@yzainee logs can be seen here https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/Jenkinsfile#L45,  in build logs annotations are being set but doesn't appear in WS call for build-config. it's intermittent and observed in e2e, can it be due to sync plugin?

**Comment by yzainee** [comment] 2018-10-05 06:31
@invincibleJai I dont see any logs link

**Comment by yzainee** [comment] 2018-10-05 06:42
@invincibleJai http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/282/05-01-jenkins-log.html in this, you can see that the fabric8.io/bayesian.analysisUrl is successfully added, but while creating the deployment config, i see this annotation missing and this is what i feel is causing the problem. 
@hrishin Can you please have a look at it

**Comment by miteshvp** [comment] 2018-10-10 13:35
@hrishin - can you please provide your expert advise on this issue?

**Comment by hrishin** [comment] 2018-10-11 07:29
@yzainee @miteshvp recently we have changed the stage name for Java maven. That migt be regression issue. Otherwise nothing is changed as such from build.
https://github.com/fabric8io/fabric8-jenkinsfile-library/pull/39

I guess @invincibleJai got the hunch of this issue.

**Comment by invincibleJai** [comment] 2018-10-11 07:34
@hrishin stage name was recent change i think and i was not aware of it, have raised a fix for it https://github.com/fabric8-ui/fabric8-ui/pull/3366. 

But the problem here is different, it's a very old issue observed intermittently in e2e. What i have observed while debugging it with @ppitonak as per Jenkins logs annotations are being added 

```
Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/8f0b00fc7c9849029d868ca5ef8442cb' to Build e2e-0912-1331-914-1
```

in socket calls (WS) annotations are not seen which led stack-report link not to appear. Details https://github.com/openshiftio/openshift.io/issues/3744#issuecomment-421255695  
Can it be due to sync plugin?

**Comment by hrishin** [comment] 2018-10-11 07:52
>  Can it be due to sync plugin

I could be but don't think becuase build annotation are directly getting added to openshift [build](https://github.com/hrishin/fabric8-pipeline-library/blob/master/src/io/fabric8/Utils.groovy#L301) resource; not through sync plugin.

**Comment by hrishin** [comment] 2018-10-18 09:27
@invincibleJai @yzainee @miteshvp I tried to investigate from build side if anything causing an issue, but I don't think so.

Could you try to log the response or query the `build` OpenShift as soon as it adds an annotation?

**Comment by invincibleJai** [comment] 2018-10-22 06:49
Thanks @hrishin for debugging.

@yzainee as @hrishin suggested can you pls add logs https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/bayesianScanner.groovy#L25, it would help us to debug it further.

**Comment by invincibleJai** [comment] 2018-10-22 06:51
thanks @hrishin for debugging.

@yzainee needed your help here, can we add log in https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/bayesianScanner.groovy#L25 to fetch added annotations, as suggested by @hrishin .

**Comment by GeorgeActon** [comment] 2018-10-24 13:09
@invincibleJai I assigned you since you are driving this from analytic so prspective

@yzainee there’s is an action request for you above

**Comment by yzainee** [comment] 2018-10-25 06:33
@hrishin In the log that you have shared, this is what i see
[Pipeline] echo
Looking for matching Build e2e-0605-230714-1
[Pipeline] echo
Adding annotation 'fabric8.io/bayesian.analysisUrl: https://recommender.api.openshift.io/api/v1/stack-analyses/3b4e6263a05e42feb17cf65fee7138f4' to Build e2e-0605-230714-1
[Pipeline] echo
looking for e2e-0605-230714-1 in namespace osio-ci-e2e-007

**Comment by yzainee** [comment] 2018-10-25 09:06
@hrishin Just wondering.. whats the problem out here? I see the annotation getting set, but not in the deployment config..

**Comment by hrishin** [comment] 2018-10-25 10:39
> just wondering.. whats the problem out here?

One way to get more info about this issue is to retrive `build` annotation after pipeline set it to `Build` as [mentioned](https://github.com/openshiftio/openshift.io/issues/3744#issuecomment-431753633) above.  As this is happening mostly in e2e test envirionment.

>  I see the annotation getting set, but not in the deployment config..

Do you mean `BuildConfig`? Could you please confirm with the team whether this annotation needs in `Build`, `BuildConfig` or `DeploymentConfig` (I believe it should be in `Build`).


@yzainee

**Comment by ppitonak** [comment] 2018-10-25 13:09
Just give us an `oc` command that will retrieve the information that you need and we will add it to our script and will be gathering it during every test run.

**Comment by ljelinkova** [comment] 2018-11-02 07:58
I've noticed that there has been UI change in the space dashboard regarding analyses - there is a progress bar now. But when I see progress bar even after the build finishes - is that only another visual representation of this issue? Or is the analyses independent from build now and we should wait for the results?

![dashboard-analyses](https://user-images.githubusercontent.com/2078072/47900467-54377900-de7d-11e8-9376-442149844031.png)

**Comment by hrishin** [comment] 2018-11-03 00:45
@ppitonak could you try this?

```sh
buildName=$(oc get builds -n hshinde -l buildconfig=<bc-name> | sort --reverse --key 1 --numeric | head -1 | awk '{print $1}')
oc get build/$buildName -n <user-namespace> -o yaml | grep "fabric8.io/bayesian.analysisUrl"
```

**Comment by ppitonak** [comment] 2018-11-05 13:55
@hrishin I added this command to our script. Can you please answer Lucia's question?

**Comment by invincibleJai** [comment] 2018-11-08 07:55
> But when I see progress bar even after the build finishes - is that only another visual representation of this issue?

@ljelinkova no it's not something newly added to UI , it's observed in scenarios where Annotations are fetched in UI from build and UI makes call to analytics service with stackID and even analytics service takes some time to process the stack. So it's different from earlier comments in this thread , earlier even progress was not shown as annotations were not fetched in UI.

> is the analyses independent from build now and we should wait for the results?

@hrishin @yzainee can update here.

PS: this progress is not shown usually as Analytics process the stack in a couple of secs.

**Comment by miteshvp** [comment] 2018-11-08 08:45
@ljelinkova @ppitonak @ldimaggi 
The original issue was due to the lack of annotations getting created from build. Since then, there has been couple other occasions where stack report is not generated
To list stack report not being generated 
1. Due to failure of adding annotations from build side
2. Due to time taken to generate a stack report in a timely manner (we are seeing some load after release of VsCode extensions)
3. Due to failure of analytics services to generate a report (infra issue - should be rare)

I think this issue should be closed for now and we should open a new issue based on any of the above conditions reoccurring. 
cc @invincibleJai @yzainee

**Comment by miteshvp** [comment] 2018-11-08 09:41
SLA for stack report is 30 minutes

**Closed** 2018-11-09 13:00 UTC
Labels: SEV2-high, area/analytics, area/dashboard, area/e2e-tests, priority/P1, status/in-progress, team/analytics, team/analytics/wizard, type/bug
