### ISSUE TITLE
OSIO UI tabs keep getting added for every click

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2339] opened 2018-02-22 14:46 UTC
Please check the screenshot: 
<img width="1087" alt="screen shot 2018-02-22 at 8 15 34 pm" src="https://user-images.githubusercontent.com/15967765/36544759-3dd5225c-180d-11e8-9be1-74c00cb00919.png">

**Comment by joshuawilson** [comment] 2018-02-22 15:19
how do you reproduce that?

**Comment by andrewazores** [comment] 2018-03-27 16:29
#1975

**Comment by corinnekrych** [comment] 2018-03-29 15:43
After several hours investigating the issue with duplicate menus when an error occurs somewhere in a service, component, I've found the root cause: this is a well-know issue in angular 4.4 https://github.com/angular/angular/issues/19093

### Steps to reproduce the issue
* Simulate an error: go to any service. For ex [DeploymentsService]() and add `throw new Error();` at the end of the constructor
* start fabric-ui: `npm start`
* navigate to: http://localhost:3000/yourname/yourspace/create
* go to `Deployments` submenu: observe the error in dev tools: 
```
console.js:32 ERROR Error
    at new DeploymentsService (deployments.service.ts:225)
    at createClass (core.es5.js:10922)
```
* go to http://localhost:3000/yourname/yourspace/plan and observe the duplicate menu: the app is not usable.

### Steps to remove the duplicate error
Remove `BrowserAnimationsModule` from the list of import in [AppModule]( https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/app.module.ts#L141)

BUT planner is using animations in [4 different places](https://github.com/fabric8-ui/fabric8-planner/blob/b5bdd76a81f800b58495775a98a9fb8f27a42aa2/src/app/widgets/planner-layout/planner-layout.component.ts#L22), removing `BrowserAnimationsModule` romove the animation effect on folding/unfolding.

### Moving forward
* either migrate to 5.x and see if it fixes the issue. @joshuawilson do we have an issue for migrating to 5.X we could link to?
* or is it possible for Planner to leave without `BrowserAnimationsModule`? use plain css / js animations? @sanbornsen do you know if possible?
* last, we leave with a broken menu when service throw error and make sure we deal with error in a more RxJs way (ie: swallow).

**Comment by jiekang** [comment] 2018-03-29 15:54
Can we see if the scope of the bug can be reduced to just the Planner module by having Planner import BrowserAnimationsModule themselves and not having it in the main AppModule? If other pages can be left unaffected, it would still be an improvement.

**Comment by jiekang** [comment] 2018-03-29 17:12
Disregard my previous comment. Upon further research, the BrowserAnimationsModule is designed such that it can only be imported at the root level of an application.

**Comment by joshuawilson** [comment] 2018-04-24 14:08
How do we reproduce this? I have not seen this in months. I'm going to downgrade it to a SEV3 unless someone can provide repeatable steps to get to this condition.

**Comment by jiekang** [comment] 2018-06-20 16:39
Does this issue still have value?  think developers are aware how this state can be triggered, and many fixes have been put into place. I think this issue can be closed. @joshuawilson Thoughts?

**Comment by joshuawilson** [comment] 2018-06-21 02:44
I'm fine to close this. It can be reopened if someone can reproduce it.

**Closed by joshuawilson** 2018-06-21 02:44 UTC
Labels: SEV3-medium, area/UI, area/navigation, team/platform, type/bug
