### ISSUE TITLE
Pipelines - Confusing switches between Build 1 and Build 2 without notifying the user

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1543] opened 2017-12-08 09:26 UTC
Two builds are triggered without the user's knowledge.

Build 2 is shown before Build 1

![nobuild1](https://user-images.githubusercontent.com/1892722/33759175-45796cd4-dbf9-11e7-8251-a861ab4b25f5.png)

After approving Build 2, the UI switches to Build 1 without notifying the user
![wheredidbuild2go](https://user-images.githubusercontent.com/1892722/33759155-3500e0da-dbf9-11e7-9b60-5430dd78d4a8.png)

After approving Build 1, the UI switches to Build 2 without notifying the user
![finallybuild2isshown](https://user-images.githubusercontent.com/1892722/33759222-75dc407c-dbf9-11e7-8b30-e438579f162b.png)

Also note, on the console, two builds are triggered by default:
![twobuildonconsole](https://user-images.githubusercontent.com/1892722/33759327-d16fd2a0-dbf9-11e7-9a7a-ef2f246aec68.png)

**Comment by sbose78** [comment] 2017-12-08 12:53
@nimishamukherjee for jenkins/Che related issues, could you please specify the version your account is running ? You will find it on the top status bar.

**Comment by nimishamukherjee** [comment] 2017-12-08 12:59
@sbose78 Jenkins is 4.0.18. Che does not show up for me.
As per https://openshift.io/osiogettingstarted.pdf Page 15, it is ok if Che version number does not show up.

![status](https://user-images.githubusercontent.com/1892722/33766912-7f0ff198-dc17-11e7-8ec6-f932ac96d21b.png)

**Comment by sbose78** [comment] 2017-12-08 13:03
Thanks.
Could you please do an `update tenant`. 

Jenkins should be at https://github.com/fabric8-services/fabric8-tenant/blob/master/JENKINS_VERSION#L1

Che should be at https://github.com/fabric8-services/fabric8-tenant/blob/master/CHE_VERSION#L1

**Comment by nimishamukherjee** [comment] 2017-12-08 14:12
@sbose78 after update tenant I get only a single build - Build 1
Problem faced now:
Rollout to stage and rollout to run display 
> Application is not available 
It has been an hour since the build was triggered

Stage - http://myvertxhello1-nmukherj-stage.8a09.starter-us-east-2.openshiftapps.com/
Run - http://myvertxhello1-nmukherj-run.8a09.starter-us-east-2.openshiftapps.com/

**Comment by sbose78** [comment] 2017-12-08 15:35
Since you didn't do a `reset environment`, makes me wonder if there's something's amiss on the openshift online side. ( service quotas etc ).

**Comment by bartoszmajsak** [comment] 2017-12-19 11:45
Mother of all issues: https://github.com/openshiftio/openshift.io/issues/592

**Comment by qodfathr** [comment] 2018-01-17 21:57
Closing as (effectively a) dupe of #592.

**Closed by qodfathr** 2018-01-17 21:57 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug
