### ISSUE TITLE
Old pipeline runs have Latest App links for Stage and Run

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1593] opened 2017-12-08 19:45 UTC
On the pipelines page, old pipelines will point to the latest stage/run deployments. 

Action: Either remove the links for older pipeline runs, or allow users to start pods for older pipeline snapshots.[needs discussion]

![pipelines-samelink](https://user-images.githubusercontent.com/6318164/33782352-6ed810aa-dc7e-11e7-8f27-405f2c304b38.png)

**Comment by rupalibehera** [comment] 2018-07-28 20:21
Need to verify if this is still the case

**Comment by piyush1594** [comment] 2018-07-30 08:39
@rupalibehera @aditya-konarde I tried to reproduce. This is still happening. We need to fix this.

**Comment by joshuawilson** [comment] 2018-10-29 21:00
Duplicate of #4009

**Closed by joshuawilson** 2018-10-29 21:00 UTC
Labels: SEV3-medium, area/UX, area/pipelines, priority/P3, sprint/tbd, team/build-cd, team/ux, type/bug
