### ISSUE TITLE
Usability: Mouse hover a WI icon should display its type as tool tip

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#969] opened 2017-09-20 12:40 UTC
Its difficult for a user to remember all the icons. The tool tip would give him a quick reference anywhere on any page.

Also, we should figure out a way to educate users on the meaning of various WITs.

**Comment by michaelkleinhenz** [comment] 2017-09-20 13:47
Dupe of #804.

**Closed by michaelkleinhenz** 2017-09-20 13:47 UTC
Labels: area/planner, kind/bug, team/planner
