### ISSUE TITLE
Pipeline Build Failing for Wildfly healthcheck boosters

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#2930] opened 2018-04-09 07:12 UTC
In the new experience Getting Started Flow, Pipeline build is failing for Wildfly healthcheck boosters,
Please see the below failed log - 
https://gist.github.com/ravsa/b022b71bee5fda1f5dc5436b61c09609

**Comment by ravsa** [comment] 2018-04-10 11:17
related issue: https://github.com/fabric8-launcher/launcher-booster-catalog/issues/189

**Comment by animuk** [comment] 2018-04-26 07:27
closing this because it is tracked in https://issues.jboss.org/browse/SWARM-1701

**Comment by ldimaggi** [comment] 2018-04-26 12:25
Duplicate of:  https://github.com/openshiftio/openshift.io/issues//3134

**Closed** 2018-04-26 12:26 UTC
