### ISSUE TITLE
Che connection problems

### ISSUE THREAD

**Issue by johnshen44** [openshiftio/openshift.io#4773] opened 2019-03-23 02:55 UTC
runing diagnostics on brand new account and (old account) both show/confirm same type connection issues:

==============================================================
Test connection from browser to workspace agent with websocket
No reply of websocket test after 5 seconds. Websocket is failing to connect to wss://routei8s57hkj-jonmelbdev-che.9a6d.starter-us-east-1a.openshiftapps.com/wsagent?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlbjFwe...
==============================================================

==============================================================
Test connection from browser to workspace agent with websocket

No reply of websocket test after 5 seconds. Websocket is failing to connect to wss://routea2b1nx0r-jondev-che.4e1e.starter-us-east-1b.openshiftapps.com/wsagent?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2Vu

==============================================================

Create Workspace
The workspace started, but Eclipse Che <--> Workspace connection not established
Hint: The workspace agent has started in the workspace, but the Eclipse Che server cannot verify this. There is a failure for Eclipse Che server to connect to your workspace's agent. Either your firewall is blocking essential ports or you can change CHE_DOCKER_IP and DOCKER_HOST to values specific to your environment. See the `che.env` file for specifics.

The workspace started, but Eclipse Che <--> Workspace connection not established
 --- FAILURE
The workspace agent has started in the workspace, but the Eclipse Che server cannot verify this. There is a failure for Eclipse Che server to connect to your workspace's agent. Either your firewall is blocking essential ports or you can change CHE_DOCKER_IP and DOCKER_HOST to values specific to your environment. See the `che.env` file for specifics.
The workspace started, but Eclipse Che <--> Workspace connection not established
 --- FAILURE
The workspace agent has started in the workspace, but the Eclipse Che server cannot verify this. There is a failure for Eclipse Che server to connect to your workspace's agent. Either your firewall is blocking essential ports or you can change CHE_DOCKER_IP and DOCKER_HOST to values specific to your environment. See the `che.env` file for specifics.
Test limit is for up to 5minutes. Time has exceed.
 --- ERROR

**Comment by ibuziuk** [comment] 2019-03-23 16:50
closing as a duplicate of https://github.com/openshiftio/openshift.io/issues/4769

**Closed by ibuziuk** 2019-03-23 16:50 UTC
