### ISSUE TITLE
New launcher Experience : css issue in select template

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3341] opened 2018-04-27 12:20 UTC
![cssissue](https://user-images.githubusercontent.com/34271052/39362154-f23f5606-4a42-11e8-995e-a735451698b1.gif)

**Comment by dlabrecq** [comment] 2018-05-07 17:10
This looks ok to me on prod, using Firefox and Chrome. Can you please confirm this is still an issue? And what browser are you using?

![screen shot 2018-05-07 at 1 09 00 pm](https://user-images.githubusercontent.com/17481322/39714405-f7eb8234-51f7-11e8-8d9b-f5f8c3ad841d.png)

**Comment by dlabrecq** [comment] 2018-05-07 17:11
Safari looks ok, too.
![screen shot 2018-05-07 at 1 11 04 pm](https://user-images.githubusercontent.com/17481322/39714466-27f4dd54-51f8-11e8-9107-709763df637f.png)

**Comment by dlabrecq** [comment] 2018-05-07 17:15
prod-preview also looks good on Firefox and Chrome

**Comment by Raunak1203** [comment] 2018-05-07 17:16
@dlabrecq could you please check in fedora ?
I'm facing issue in fedora chrome-browser

**Comment by catrobson** [comment] 2018-05-07 18:47
Also a problem on Windows 10 + Chrome that Todd has experienced.

**Comment by bmicklea** [comment] 2018-05-07 18:50
Thanks for confirming - this is blocking the demo. Please treat it as a priority.

**Comment by dlabrecq** [comment] 2018-05-07 19:40
Using Browser Stack to run Windows 11/10. OSIO (prod) won't run at all and keeps landing to the 404 error page.

I don't have the ability to run Fedora.

**Comment by aptmac** [comment] 2018-05-07 19:48
I made a small PR [0] to change the stylesheet and fill the text in black. It looks as intended in Chrome for me now, and looks as it did before (no-change) in Firefox. I don't have access to Windows/Mac, so if it could be verified that it works there too it'd be appreciated.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2890

**Comment by dlabrecq** [comment] 2018-05-07 20:01
I don't see any change on Mac using Chrome, so the change seems ok to me.

**Comment by joshuawilson** [comment] 2018-05-08 05:31
This fix has been pushed to prod. Closing. If there is still an issue, please reopen.

**Closed by joshuawilson** 2018-05-08 05:31 UTC
Labels: SEV2-high, area/UI, area/space-wizard, priority/P0, team/platform, type/bug
