### ISSUE TITLE
Che cannot create new workspaces (due to slow routes) on https://openshift.io - "Unable to Initialize IDE" - "Workspace agent is no longer responding"

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1304] opened 2017-11-07 22:29 UTC
Steps to recreate:
* Create new space
* Create new project - quickstart
* Create codebase

Observe this error in the Che IDE:
```
Workspace agent is no longer responding. To fix the problem, verify you have a good network connection and restart the workspace.
```
![screenshot from 2017-11-07 16-25-14](https://user-images.githubusercontent.com/642621/32521344-21774c0a-c3e1-11e7-8d3a-5af1322a1053.png)

**Comment by ldimaggi** [comment] 2017-11-07 22:30
No error is written to the Che pod log:

```

2017-11-07 21:24:26,859[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspace0aode27ytiiv4vrp
2017-11-07 21:24:34,257[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspace0aode27ytiiv4vrp
2017-11-07 21:24:41,675[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspace0aode27ytiiv4vrp
2017-11-07 21:24:54,815[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'com.redhat.bayesian.lsp' agent at workspace workspace0aode27ytiiv4vrp
2017-11-07 21:24:57,538[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 658]    - Workspace 'che/nov7001-z4oty' with id 'workspace0aode27ytiiv4vrp' started by user 'che'
```

**Comment by joshuawilson** [comment] 2017-11-08 03:03
I wonder if this has to do with the throttle of OS that was reported earlier today.

**Comment by ibuziuk** [comment] 2017-11-08 06:52
@ldimaggi can not reproduce. Could you please provide the browser logs ?

**Comment by ldimaggi** [comment] 2017-11-08 21:45
Closing - not reproducible - thx!

**Comment by ldimaggi** [comment] 2017-11-08 22:33
Looks like it is intermittent - the EE tests are seeing this - and I just saw it once in 3 tries.

Seeing this in the log:

```
2017-11-08 21:48:22,064[nio-8080-exec-9]  [ERROR] [.k.t.p.u.KeycloakUserValidator 227]  - Exception while getting OpenShift token. keycloakToken: Bearer, Exception: {}
java.io.IOException: Failed access: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token, method: GET, response code: 500, message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">;
```

**Comment by ibuziuk** [comment] 2017-11-09 08:02
@ldimaggi but it is another issue with a blank token and I would not mixed them together since those are completely different - https://github.com/openshiftio/openshift.io/issues/1238

**Comment by ldimaggi** [comment] 2017-11-09 13:23
The interesting thing is that the 500 server error was written to the log when the "Workspace agent is no longer responding. To fix the problem, verify you have a good network connection and restart the workspace" error was displayed to the user. Maybe it was just a coincidence?

Either way - I have been seeing this network connection problem intermittently  for the past couple of days - both in manual and automated testing. Thx!

**Comment by ibuziuk** [comment] 2017-11-09 13:29
@ldimaggi well, as I understand this particular issue was related to IDE - "unable to initialize IDE" (pop-up on the screenshot) that is why I was wondering what were the browser logs. On the other hand blank token is another issue - https://github.com/openshiftio/openshift.io/issues/1304#issuecomment-342983742

So, just do not want to mix everything together

**Comment by ldimaggi** [comment] 2017-11-09 13:38
+1 I will update the blank token separately. Thx!

**Comment by jerboaa** [comment] 2017-11-09 18:07
For what it's worth, I've seen only this issue on my end. It was never working today for me :(

**Comment by jerboaa** [comment] 2017-11-09 18:16
Seems to be caused by:

    https://wsagent-kn4qaavpbnoc36hw-sgehwolf-che.8a09.starter-us-east-2.openshiftapps.com/api/ 

returning 503. That's what the developer console tells me.

**Comment by jerboaa** [comment] 2017-11-09 18:19
Then I see:

     Failed to load https://wsagent-kn4qaavpbnoc36hw-sgehwolf-che.8a09.starter-us-east-2.openshiftapps.com/api/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://che-sgehwolf-che.8a09.starter-us-east-2.openshiftapps.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by jerboaa** [comment] 2017-11-09 18:28
On the CHE server logs has only this:

    2017-11-09 18:14:18,607[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspacekn4qaavpbnoc36hw
    Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.createStatus(OperationSupport.java:275)
            at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.onFailure(ExecWebSocketListener.java:166)
            at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
            at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:203)
            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

**Comment by ibuziuk** [comment] 2017-11-09 18:39
![image](https://user-images.githubusercontent.com/1461122/32623170-80996ca4-c585-11e7-9325-89573aa77322.png)
There is no error logs in che-server for me, but I can reproduce

`Failed to load https://wsagent-o5fd8qzwq6pfskck-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com/api/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://che-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com' is therefore not allowed access. The response had HTTP status code 503.`

**Comment by jerboaa** [comment] 2017-11-09 18:40
Same what I've posted above.

**Comment by ibuziuk** [comment] 2017-11-09 18:42
@alexeykazakov there are quite a few 403s in the networking - could this be related to keycloak somehow ?

**Comment by jerboaa** [comment] 2017-11-09 19:09
Interesting. This seems to be easier to reproduce if using the ***vert.x http booster***. Using the ***spring boot http booster*** and creating the workspace *worked* for me.

This time I see:

    _app-0.js:16215 ERROR   
       (org.eclipse.che.plugin.languageserver.ide.LanguageServerFileTypeRegister): 
       java.lang.Exception: 
	at Unknown.Nn(Throwable.java:74)
	at Unknown.Vn(Exception.java:33)
	at Unknown.dxk(LanguageServerFileTypeRegister.java:135)
	at Unknown.fxk(LanguageServerFileTypeRegister.java:134)
	at Unknown.rIe(JsPromise.java:39)
	at Unknown.anonymous(JsPromise.java:170)
    Caused by: org.eclipse.che.ide.commons.exception.ServerDisconnectedException: undefined
	at Unknown.Tn(Throwable.java:61)
	at Unknown.Xxg(ServerDisconnectedException.java:21)
	at Unknown.vOh(AsyncRequestCallback.java:201)
	at Unknown.COh(AsyncRequestCallback.java:93)
	at Unknown.kA(Request.java:250)
	at Unknown.DA(RequestBuilder.java:412)
	at Unknown.anonymous(XMLHttpRequest.java:329)
	at Unknown.Oo(Impl.java:239)
	at Unknown.Ro(Impl.java:291)
	at Unknown.anonymous(Impl.java:77)

**Comment by jerboaa** [comment] 2017-11-09 19:09
![screenshot from 2017-11-09 20-07-18](https://user-images.githubusercontent.com/357222/32624554-dfdcb776-c589-11e7-81f7-c1836d5bd603.png)

**Comment by jerboaa** [comment] 2017-11-09 19:35
> @alexeykazakov there are quite a few 403s in the networking - could this be related to keycloak somehow ?

FWIW, I've seen the same for a working workspace. It was spring boot, though.

**Comment by ibuziuk** [comment] 2017-11-09 20:00
Do not know what is exactly going on but the workaround would be navigating to the dashboard after failure and reopening workpace from there - https://youtu.be/sXKpMp1LcO4

403s error does not seem to be related to the problem (still see them when opening workspace from dashboard but those do not cause any problems). The real issue seems to be 

Failed to load https://wsagent-jc5d4votwarp33rn-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com/api/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://che-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by ibuziuk** [comment] 2017-11-09 20:43
Strange... the issue is still reproducible for me with disabled keycloak:
![image](https://user-images.githubusercontent.com/1461122/32628688-ff4e4c8e-c596-11e7-89ef-60962735053a.png)

**Comment by ibuziuk** [comment] 2017-11-09 21:55
this issue seems to be related to the fact that wsagent route is not accessible for some time after creation - 503 in response. Not sure what exactly causes this delay but it looks like it started to happen after cluster update when we were forced not to set host explicitly [1] (weird those that it started to be reproducible for everyone only today)

[1] https://github.com/eclipse/che/commit/05a91350191fc7edc463fc2f3cbcca9da75e38a2

**Comment by davidfestal** [comment] 2017-11-09 22:12
The cause of the problem seems the 503 error returned when trying to access the wsagent api endpoint.
When trying on my own account I also get these error messages in the browser console:
```
wsagent-yd74syqa0rsh0jhf-dfestal-che.8a09.starter-us-east-2.openshiftapps.com/api/ Failed to load resource: the server responded with a status of 503 (Service Unavailable)
wsagent-yd74syqa0rsh0jhf-dfestal-che.8a09.starter-us-east-2.openshiftapps.com/api/ Failed to load resource: the server responded with a status of 503 (Service Unavailable) 
```
And when looking into all the wsagent logs, it seems the wsagent server is correcly started, no error is shown, even in the access log.

Another point is that, when having the error, a simple refresh of the workspace browser tab is sufficient to have it work.

It might be related to the fact that the wsagent route is not fully available at the time the wsmaster redirects the application to the wsagent. This is consistent with the fact that, in upstream che and in `rh-che` single tenant, the `WsAgentPingRequestFactory` (that pings the wsagent to see if it is available) uses the internal address of the wsagent and not the external one (which is the route url).
So it is theorically possible that the wsagent would be successfully pinged by the wsmaster though still not fully accessible through the Openshift route, which might bring this error the first time the wsagent api endpont is accessed from the user browser.

In the last commits made on upstream for multi-tenancy, we have introduced a new option that allows using the external URL for the wsagent ping request. That might help but is currently not available for the `rh-che` single tenant build due the the upstream che release it uses. However it should be possible to backport some useful commits if necessary.

**Comment by ibuziuk** [comment] 2017-11-10 07:26
> Another point is that, when having the error, a simple refresh of the workspace browser tab is sufficient to have it work.

yeah, I confirm page refresh also helps
But definitely smth. weird is going on with route accessibility - for example che host route is accessible only in ~ 1 min after the pod is running (workaround for this problem [1] is in che-starter for quite a while) and now we start getting similar things for wsagent

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1481603
[2] https://github.com/openshiftio/openshift.io/issues/579

**Comment by ibuziuk** [comment] 2017-11-10 09:10
@rhopp @ldimaggi @Katka92 could you please confirm that this issue is prod specific and not reproducible on prod-preview ?

I have done a few tests and workspace creation works just fine for me against prod-preview oso [1]

[1] https://console.free-int.openshift.com/console/

**Comment by ibuziuk** [comment] 2017-11-10 09:42
also not reproducible on minishift for me `minishift v1.7.0+1549135`

**Comment by jerboaa** [comment] 2017-11-10 09:45
FWIW, page refresh does not necessarily work the first time around. I had to refresh twice for it to work.

**Comment by ibuziuk** [comment] 2017-11-10 09:49
@jerboaa yeah, because on the first refresh wsagent route was still not accessible and more time was required to make it available (~1 min after creation)
@kbsingh it looks like there is a regression or smth. similar to  https://bugzilla.redhat.com/show_bug.cgi?id=1481603 has been introduced on the prod

**Comment by jerboaa** [comment] 2017-11-10 09:52
> @jerboaa yeah, because on the first refresh wsagent route was still not accessible and more time was required to make it available (~1 min after creation)

Yes, makes sense.

**Comment by pbergene** [comment] 2017-11-10 11:23
Running https://paste.fedoraproject.org/paste/B41q-i9dOj8QOKxMTZGH5w to make sure it's a route creation issue rather than an intermittent one.  Right now it looks like the former - sometimes routes will come up immediately and others they will 503 a few times, then some 403s in between until it seems to stabilize on 403.  Can try supplying the token too. 

It doesn't look exactly like  https://bugzilla.redhat.com/show_bug.cgi?id=1481603 as it doesn't always seem to happen, but could be related.

Just started this run which looks interesting.. 

`[paul@leda starter-us-east-2]$ ./getResponse 
route "wsagent-4l0arz8xbxgo8dtj" deleted
route "wsagent-4l0arz8xbxgo8dtj" created
403 403 503 403 403 503 503 403 403 503 503 403 403 503 403 403 503 503 403 403 503 503 403 403 503 503 403 403 503 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403 403`

**Comment by l0rd** [comment] 2017-11-10 13:29
@pbergene from what I understand there is not much we can do Che side. I am removing label `team/che`. Let us know if we can help somehow.

**Comment by kbsingh** [comment] 2017-11-15 11:17
if che is down, its a che-team responsibility to bring it back up.

**Comment by mishaone** [comment] 2017-11-16 02:47
If it's useful in terms of troubleshooting, I can report that I've had this blocking my OSIO use consistently since yesterday. 

![workstation_fail](https://user-images.githubusercontent.com/926572/32871322-1392a476-cacc-11e7-9503-2cdf63846c59.png)

In an email thread with the team, I was advised that refreshing the tab usually fixes the problem. This does not work for me, so still blocked. This is what appears when I refresh:

![refresh](https://user-images.githubusercontent.com/926572/32871336-2c6c4f24-cacc-11e7-81db-e48344eea848.png)

Since yesterday, I've done an environment reset a few times, manually removed OpenShift Online projects and objects, but no joy. If sending logs or something helps, please let me know.

**Comment by ldimaggi** [comment] 2017-11-16 12:41
Example of this issue encountered by the automated EE tests:  https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-openshift.io-chequickstartTest/1731/console

**Comment by joshuawilson** [comment] 2017-11-16 21:18
This is supposedly a fix for this, we are just waiting for it to hit prod, this issue is blocking users.

**Comment by pbergene** [comment] 2017-11-17 08:41
@joshuawilson What is the fix? Is there something that can be done on our side?

**Comment by l0rd** [comment] 2017-11-17 12:00
@pbergene I think there was a misunderstanding. Last week, when the issue first arose, we thought that we could somehow mitigate that with a fix Che side. But after some testing we could verified that unfortunately the problem was still there even after applying the fix.

**Comment by pbergene** [comment] 2017-11-17 12:01
@mario Thanks, just making sure I didn't miss anything here.

**Comment by mishaone** [comment] 2017-11-20 03:39
Since the last time I reported constantly encountering this issue (see earlier comment 4 days ago), I have now managed to get the workspace to load so possibly whatever the fix was has worked to some extent.

**Comment by jfchevrette** [comment] 2017-11-20 15:23
The routers were restarted on Friday and this appear to have cleared an issue. Unfortunately that also means we have no way to debug the issue further at the moment until the routers get in this state again.

**Comment by pbergene** [comment] 2017-11-20 15:35
Is anyone still seeing this? @mishaone Can you elaborate around  "some extent" - is it still occurring to your workspace?

**Comment by jerboaa** [comment] 2017-11-20 15:51
FWIW, I've seen it a couple of times today.

**Comment by ldimaggi** [comment] 2017-11-20 16:06
The EE tests are still seeing this error:

https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-openshift.io-chequickstartTest/1807/console

**Comment by jfchevrette** [comment] 2017-11-20 18:07
What I am seeing when launching a workspace is that while the wsagent container service is becoming active, it's route is still in the process of being created on the OpenShift side when the "Unable to initialize IDE" message appears. The route becomes active ~ 15 seconds after this.

1) I am still working with upstream to make sure there was no recent performance regression on the routers which would make them take ~60sec to create a route.
2) Meanwhile is there a way we can tweak or increase the timeout on che workspace so that it waits a little bit longer for the wsagent route to become active? Not a perfect solution but this would allow the workspace to start even if would take longer than before

**Comment by jfchevrette** [comment] 2017-11-20 20:22
The workaround implemented in fabric8-services/fabric8-tenant-che#72 allows the workspace to start. I am still investigating the possibility of a performance issue on the openshift routers

**Comment by mishaone** [comment] 2017-11-21 02:49
@pbergene - yes, back to the same issue as before today. I can add screenshots of the error and logs if that helps.

**Comment by l0rd** [comment] 2017-11-21 07:25
@mishaone have you updated you tenant this morning? The latest Che version (2.0.60) has a workaround that mitigates the routes issues: a change in the [server evaluation strategy](https://github.com/fabric8-services/fabric8-tenant-che/pull/72). That is something we tested without success last week. But this weekend something has changed in the routes configuration and, associated with our workaround, solves the problem now.

**Comment by jerboaa** [comment] 2017-11-21 11:35
It's looking good so far on my end (version 2.0.60). It did load the workspace correctly on first attempt. I'll report back should I see the issue again.

**Comment by jerboaa** [comment] 2017-11-21 15:36
From where I'm standing this issue can be closed as fixed.

**Comment by ibuziuk** [comment] 2017-11-21 17:47
@ldimaggi could you please verify ?

**Comment by joshuawilson** [comment] 2017-11-21 18:29
The only issue is that we have now introduced a 60 sec delay to overcome an unknown issue. That unknown issue may grow and then we would need more then 60 sec. Plus, this is not good for the user experience. 
If we close this, can we open a new one to address these new issues?

**Comment by ibuziuk** [comment] 2017-11-21 18:33
@joshuawilson we could create a new one for SD team (which would be resolved after 3.7 update)

**Comment by mishaone** [comment] 2017-11-22 03:50
+1 now works for me with updated che.

**Comment by jerboaa** [comment] 2017-11-22 09:33
@joshuawilson FWIW, I'd track this as a separate issue and link it here.

**Comment by mishaone** [comment] 2017-11-24 05:45
FYI - loading a previously created workspace is now down to about 50% change of fail for me. Usually this for ages:
![ws_not_running](https://user-images.githubusercontent.com/926572/33196881-9bae1a40-d12d-11e7-9054-b63515d04cdc.png)

At one point today, when left inactive for a half hour, the workspace indicated that it needed to restart (with a restart button, from memory), then the above for 10 minutes or so at a time till I would lose patience and reload it.

**Comment by ldimaggi** [comment] 2017-11-27 16:32
Just saw this error again:
https://ci.centos.org/view/Devtools/job/devtools-test-end-to-end-openshift.io-chequickstartTest/1945/console

**Comment by jerboaa** [comment] 2017-11-27 17:06
Yes, I've seen it too on Friday :(

**Comment by l0rd** [comment] 2017-11-27 18:16
This looks like a new problem always related to routes but the endpoint that does return **503** is `/api/languageserver/supported`.

![image](https://user-images.githubusercontent.com/606959/33281969-5978835a-d3a7-11e7-84e9-39d10754aa2c.png)

Looking at it

**Comment by kbsingh** [comment] 2017-11-28 15:53
I dont see the timeout issue being addressed in 3.7 either. @ibuziuk did you mean some other issue ?

**Comment by ibuziuk** [comment] 2017-12-01 10:29
@kbsingh I was not able to reproduce this problem on prod-prevew so far

**Comment by adisakala** [comment] 2017-12-05 03:24
@ibuziuk @l0rd is this still an open issue on Prod?

**Comment by ldimaggi** [comment] 2017-12-05 03:50
+1    I saw this today (December 4)

**Comment by l0rd** [comment] 2017-12-05 17:59
I have tried with the wsagent route create as the last route amongst the 9 workspaces routes but that didn't help. The only solution I see is to add some kind of ping timeout mechanism (the one that is [used by the wsagent](https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/java/org/eclipse/che/api/agent/WsAgentLauncher.java#L124)) on the bayesian language server agent too.

**Comment by ldimaggi** [comment] 2017-12-05 18:38
I just tried (10) manual tests - where each test created a new quickstart/app and then attempted to create a Che workspace. All (10) attempts failed.

The majority of the failures showed bug #1304, but there were some others too:

#1 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#2 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#3 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#4 - Fail, "workspace is not running"
#5 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#6 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#7 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#8 - Fail, https://github.com/openshiftio/openshift.io/issues/1304
#9, Fail, https://github.com/openshiftio/openshift.io/issues/1510
#10, https://github.com/openshiftio/openshift.io/issues/1304

I did not see anything in the Che pod logs. These tests were all conducted on https://openshift.io

**Comment by l0rd** [comment] 2017-12-06 12:35
It looks like there is kind of route dance here: when, after one minute or so, the route becomes available (HTTP code 200) it becomes unavailable again after a few ms. This continues for at least 20 seconds during which Che is unusable.

There is not much we can do here Che side. If the routes are available and then becomes unavailable the client part of Che running in the browser won't work properly.

![output](https://user-images.githubusercontent.com/606959/33661511-906fc6f6-da88-11e7-8fc9-bf55ea9707c3.gif)

This is the script I used to ping the route https://gist.github.com/l0rd/0dbf37dd3138592820b808c0f6a1a275

**Comment by maxandersen** [comment] 2017-12-06 12:45
thats just weird and can't be right.

Any chance you can reproduce this in a simpler examle and we can raise to openshift team ?
 @kbsingh comments ?

**Comment by maxandersen** [comment] 2017-12-06 13:38
related issue tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1519918

**Comment by jfchevrette** [comment] 2017-12-06 13:52
We're seeing two issues:
- Route endpoint flapping between HTTP 503 and 200: https://bugzilla.redhat.com/show_bug.cgi?id=1522812
- Routers take ~1min to reload and activate a route: https://bugzilla.redhat.com/show_bug.cgi?id=1519918

We will be able to tune down the router reload timers when the cluster is upgraded to 3.7 in the coming weeks.

**Comment by jfchevrette** [comment] 2017-12-06 15:03
It looks like getting the routers to reload in sync is a complex problem. From what I understand there is no quick fix upstream to address this. This is also something that users normally don't see as the time it takes for all the routers to reload (usually 15-20sec after the initial HTTP 200) is short enough that by the time the users try to access the endpoint from his browser the routers are reloaded.

This is however a concern when (micro)services themselves try to access the endpoint every second until a HTTP 200 is seen - as is the case with the che agent. At that point assuming that all routers had a chance to reload at that very same second is a bit optimistic.

Until there are mechanisms in place at the router level to make sure they all reload (or enable a route) at exactly the same second we will have to find ways to make the services more accommodating to the delay it takes for routes to reload. 

One solution I would like to propose is to let the service retry a few time instead of failing at the first non-200 HTTP code it sees.

Another possible solution would be to have the service wait for the endpoint to return X consecutive HTTP 200 before assuming the endpoint is up. This is much similar to the way Kubernetes/OpenShift readinessCheck probes work: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes

**Comment by ldimaggi** [comment] 2017-12-06 15:08
Are you sure that (human) users will not see this issue? I was unable to get Che to create a workspace on December 5 ten out of ten tries - all done manually in the ISIO UI. Thx!

**Comment by ibuziuk** [comment] 2017-12-06 15:12
> One solution I would like to propose is to let the service retry a few time instead of failing at the first non-200 HTTP code it sees.

@jfchevrette so, what you are proposing is to have this mechanism in place for *every* call to *every* endpoint exposed from console.starter-us-east-2.openshift.com ?

**Comment by jfchevrette** [comment] 2017-12-06 15:14
@ldimaggi I meant outside of the context of OSIO. The error we're seeing is coming from Che assuming the router endpoints all have reloaded at the same excact second which as I describe above is very optimistic. My comment around (human) users not seeing this is more in the context of a casual user trying to run a web application on OpenShift Online (not OSIO). 

By the time the user's app is up and running and the user goes to it in his browser the routers have probable had time to reload. Moreover most of the time a route is created once and active from that point on. This is very different from OSIO/Che where we create/delete routes all the time.

**Comment by jfchevrette** [comment] 2017-12-06 15:18
@ibuziuk software break, infrastructure break. if your service isn't designed to fail and retry gracefully I can guarantee that it will break at some point.

When I loose network connectivity on my phone, I don't get 10s application crashing on me. They retry in the background and eventually succeed in reconnecting to the service. Of course this is not a great comparison but this sort of graceful failing/retrying also has to be done at the service level too.

**Comment by l0rd** [comment] 2017-12-06 16:39
@jfchevrette @kbsingh The two problems with routes (timeout and flapping) are clearly regressions. Everything worked fine 30 days ago. In the past we had similar [issues](https://github.com/redhat-developer/rh-che/issues/115) with [routes](https://gist.github.com/l0rd/12a6f7fc6397b4156eb24e9a6d21d886#file-503-issues-we-had-before-summit-md) that got solved. So the question are:

- Can't we just rollback OSO starter cluster to it's 30 days ago state?
- When are we going to do some infrastructure testing ourself? In particular routes and PV should be stress tested aggressively before any updated is introduced in OSO starter cluster (cc @ldimaggi). Testing our applications is good but we should test we rely on too.

In the meantime you are asking to make Che as resilient as possible and we understand that. We may build a new version of Che to runs fine when a user is in the subway, or in a car going through some tunnel. But that's not a fix that takes one day or two. That is an effort that would involve every Che team and that should be thought carefully and prioritized (cc @gorkem @slemeur @bmicklea).

What we can do now is continue adding another hack (waiting for 5 seconds of reliable communications before considering that `wsagent` is available). That will work today but won't be sufficient with next OSO cluster regression...

**Comment by l0rd** [comment] 2017-12-06 16:46
> This is much similar to the way Kubernetes/OpenShift readinessCheck probes work: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes

What do you think would be a reasonable `successTreshold` in our case?

**Comment by jfchevrette** [comment] 2017-12-06 18:19
@l0rd I realize the tone of my comments may sound like I'm throwing this problem at the che team. I am definitely not and we are actively engaging with upstream to figure out whats the best way to address this. On the other hand we have a service that is failing so lets try to find appropriate solutions to get us going in the right direction.

From what I have seen it can take from a few seconds up to 60 seconds for all the routers config to be in sync.

**Comment by l0rd** [comment] 2017-12-07 17:01
Hopefully [PR](https://github.com/eclipse/che/pull/7766) should fix this. It introduces a successful ping threshold that needs to be met before considering that the wsagent is really available. After some tests I've set the threshold to 10 successful ping. The value is in a [config map](https://github.com/fabric8-services/fabric8-tenant-che/blob/master/apps/che/src/main/fabric8/cm.yml#L33) and can be modified if things get better/worst.

To promote the fix in production we still need to:
- release upstream Che `v5.21.1` (please @riuvshin comment here as soon as we have the release)
- merge this [rh-che PR](https://github.com/redhat-developer/rh-che/pull/476)
- wait that `rh-che`, `fabric8-tenant-che` and `fabric8-tenant` CI build completes
- promote fabric8-tenant to prod (manually?)

**Comment by l0rd** [comment] 2017-12-07 22:13
The fix is now available in production (users need to update their tenant) and it looks like it works:

![output](https://user-images.githubusercontent.com/606959/33741247-e6be854e-dba3-11e7-94d3-3ff6144b5f08.gif)

**Comment by kbsingh** [comment] 2017-12-07 23:26
thanks everyone for coming together and getting this fixed rapidly.

**Closed by kbsingh** 2017-12-07 23:26 UTC
Labels: area/che, SEV1-urgent, team/che, type/bug
