### ISSUE TITLE
can't open blueocean UI 

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2120] opened 2018-01-31 09:11 UTC
I'm not sure if this issue caused/related to idler or "just" a jenkins issue; but here is what I did:

goto jenkins.openshift.io
click the "Goto blueocean" (https://jenkins.openshift.io/blue/organizations/jenkins)
Sees that it ends up at https://jenkins-manderse-jenkins.8a09.starter-us-east-2.openshiftapps.com/login?from=%2Fblue%2Forganizations%2Fjenkins%2F
and shows me username/password and i'm logged out.

I tried to log in using my developers credentials but nothing seem to work.

@vpavlin @hferentschik @chmouel  ^^

**Comment by vpavlin** [comment] 2018-02-01 13:43
The problem is that the url does not have `/` at the end

https://jenkins.openshift.io/blue/organizations/jenkins

vs. 

https://jenkins.openshift.io/blue/organizations/jenkins/

The missing slash triggers 302 redirection in Jenkins web server and returns the OSO Jenkins URL

Not sure how to solve this - the only thing that comes to my mind is to inspect headers in proxy on 302 redirect and check if the redirect URL points to proxy host

**Comment by kishansagathiya** [comment] 2018-07-27 07:18
None of the above two links worked from me, both gave `Not Found`

**Comment by lordofthejars** [comment] 2018-07-27 07:23
@kishansagathiya maybe in your case is because of https://github.com/openshiftio/openshift.io/issues/4006

**Comment by kishansagathiya** [comment] 2018-07-27 07:30
> maybe in your case is because of #4006

@lordofthejars Yes, I thought the same. Have seen those links multiple times. From what I know, we are not using BlueOcean UI and thus it doesn't affect us. But this is certainly not a desirable and should be fixed keeping in mind the efforts required.
May @rupalibehera or @hrishin would have a better sense how important this issue is

**Comment by hrishin** [comment] 2018-11-05 18:16
Recently we have updated blue ocean UI plugins. Right now the user is able to access the BO UI.
![image](https://user-images.githubusercontent.com/28615674/48017646-cd242280-e154-11e8-97e5-8ef55791b351.png)


It's better to close this issue. Let's file another issue if we face it again.

**Closed by hrishin** 2018-11-05 18:16 UTC
Labels: SEV3-medium, priority/P4, sprint/tbd, team/build-cd, type/bug
