### ISSUE TITLE
Min 150 MB for pods so we can’t even reduce quickstarts to get more ‘room’

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#495] opened 2017-08-08 20:34 UTC
Our OSO instance currently requires 250Mi as the lowest possible memory setting.  Vert.x can go lower.  Ideally move this down to 150Mi

**Comment by kbsingh** [comment] 2017-08-14 17:08
I would recommend dropping the P1 severity and bringing the conversation into a service architecture piece. Its not something we are going to be able to execute in the short to immediate term.

**Comment by burrsutter** [comment] 2017-08-28 21:41
I chatted with Clayton about this, it is apparently a setting on OSO that could be changed.

**Comment by joshuawilson** [comment] 2017-09-07 04:13
@burrsutter were you able to work around this? Can we close it? 
@kbsingh were you able to work this out and find a solution?
Is this still an issue? Can we close it?

**Comment by bmicklea** [comment] 2017-09-10 23:46
Retagging as enhancement - my understanding is that this is an OSO limitation for now.

**Comment by qodfathr** [comment] 2018-01-17 17:01
Closing by design. We can revisit post launch.

**Closed by qodfathr** 2018-01-17 17:01 UTC
Labels: area/architecture/performance, team/service-delivery, type/feature
