### ISSUE TITLE
Nothing happens when delete a pod from the Deployments page

### ISSUE THREAD

**Issue by SkorikSergey** [openshiftio/openshift.io#2648] opened 2018-03-16 13:21 UTC
**Steps to reproduce:**

1. Create any **Quickstart** project by the **Application Wizard**.
2. Wait until a pipeline finished.
2. Open the **Deployments** page and try to delete a pod.

**Expected result:**
The pod is deleted.

**Actual result:**
Nothing changed.

**Screencast:**
![deployments-delete-pod](https://user-images.githubusercontent.com/7760565/37522497-c394735e-292c-11e8-955f-28f6d553586c.gif)

**Comment by aptmac** [comment] 2018-03-16 13:29
Duplicate of https://github.com/openshiftio/openshift.io/issues/2633

**Closed** 2018-03-16 13:36 UTC
