### ISSUE TITLE
New launcher allows application to be created twice

### ISSUE THREAD

**Issue by ebaron** [openshiftio/openshift.io#3399] opened 2018-05-01 21:53 UTC
Using the new launcher, I am able to create an application using the same name as an existing application. There is no indication to the user that an application with the given name already exists.

Steps to reproduce:
1. Use wizard to create application _X_ with codebase _Y_
![screenshot from 2018-05-01 16-14-56](https://user-images.githubusercontent.com/4326090/39495145-1f9fb1fa-4d67-11e8-8607-901fdfc72224.png)
![screenshot from 2018-05-01 16-49-59](https://user-images.githubusercontent.com/4326090/39495161-3498b886-4d67-11e8-94f2-efc58f7173d0.png)
2. Use wizard again to create application _X_ with codebase _Z_, completes successfully without warnings/errors
![screenshot from 2018-05-01 16-51-41](https://user-images.githubusercontent.com/4326090/39495216-6c5203e0-4d67-11e8-982c-1d9739971e20.png)
![screenshot from 2018-05-01 17-01-54](https://user-images.githubusercontent.com/4326090/39495222-7b59f596-4d67-11e8-918f-d61b711abaf3.png)
3. Observe application _X_ is still using codebase _Y_ after rebuilding
![screenshot from 2018-05-01 17-02-14](https://user-images.githubusercontent.com/4326090/39495291-b69ff29a-4d67-11e8-8770-b70be96a8fce.png)

We may want to disallow the user to create an application using the name of an application that already exists, or at least inform them of the name conflict. In the current situation, if the user didn't realize they already had an application named _X_, and recreated the application with a different codebase, they would not expect it to be rebuilt and deployed using the old codebase.

**Comment by animuk** [comment] 2018-05-02 06:16
This is not a bug. But, yes, this is good to inform user if the application name already exists in the pipeline.
@joshuawilson do we have any platform API which we can use to get the list of application metadata in the OSIO.

**Comment by ebaron** [comment] 2018-05-02 14:35
@animuk There is `/deployments/spaces/{spaceID}`, which returns all applications within a space. This also queries a bunch of additional information about the applications from OpenShift (e.g. deployments, pod status), so it may be too much overhead for your purposes. We might be able to add a modified version of this API to only query and return the application names, or you could just query OpenShift directly for Build Configs with label selector "space=_spaceName_".

**Comment by jyasveer** [comment] 2018-05-11 06:26
@ebaron Thanks for the information.

**Comment by jyasveer** [comment] 2018-05-11 18:36
thanks @ebaron for the reply. I will have a look and work on it.

**Comment by jyasveer** [comment] 2018-05-14 06:50
This issue is fixed here https://github.com/fabric8-ui/fabric8-ui/pull/2902

**Comment by jyasveer** [comment] 2018-05-18 05:04
this issue is fixed now

**Closed by jyasveer** 2018-05-18 05:04 UTC
Labels: SEV3-medium, area/app-wizard, area/launcher, status/completed, team/analytics/wizard, team/launcher
