### ISSUE TITLE
It can appear as though incorrect totals shown in Planner Backlog Display

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4373] opened 2018-10-01 15:22 UTC
##### Issue Overview

The totals displayed for woriktems in queries are incorrect in the Planner. To illustrate:

![screenshot from 2018-10-01 11-16-58](https://user-images.githubusercontent.com/642621/46298097-3ae49980-c56c-11e8-8ee5-cb5ccfa1b42d.png)

The expected results are for the totals to match the query results.

**Comment by sahil143** [comment] 2018-10-08 10:11
@ldimaggi The total number of work items shown in the given screenshot is correct. We only count the work items which are matching the applied filter. In this case, filters are `area: Getting Started, iteration: Sprint 156` that's why the count is seven. Work item number 723 is not considered in the count because it belongs to sprint 156 but does not belong to `area: Getting started`.

**Comment by jarifibrahim** [comment] 2018-10-08 11:59
This is the expected behaviour. I'll let @ldimaggi close the issue.
Thanks @sahil143

**Comment by ldimaggi** [comment] 2018-10-08 12:36
Ah - thanks - that makes sense.

But - from a user's perspective - this is confusing. The query returns a certain number, but the total number of elements displayed is different (larger) than that number due to how the parent/tree elements are also displayed.

I think that we have to provide the users with an explanation and will transfer this issue to the doc team. Thanks!

**Comment by joshuawilson** [comment] 2018-10-19 19:35
cc @rkratky @Preeticp

**Comment by Preeticp** [comment] 2018-10-22 05:16
[WIP](https://github.com/fabric8io/fabric8-online-docs/projects/1), entire Planner section is being reviewed and updated, I will add a note on this along with it @joshuawilson.

**Comment by Preeticp** [comment] 2018-11-23 08:58
This has been fixed by: https://github.com/fabric8io/fabric8-online-docs/pull/445

**Closed by Preeticp** 2018-11-23 08:58 UTC
Labels: SEV3-medium, area/docs, priority/P3, team/docs, type/bug
