### ISSUE TITLE
Can not create app with new launcher based on vert.x "REST API Level 0" quickstart

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#3421] opened 2018-05-02 16:44 UTC
![image](https://user-images.githubusercontent.com/1461122/39536989-7c6c4e3a-4e38-11e8-8f3a-343e5ffa9db6.png)

After pressing "Set up Application" button nothing happens and there is the following error in browser console:

```
POST https://forge.api.openshift.io/api/osio/launch 400 (Bad Request)
_scrollbars.less:6 400 - Bad Request [{"message":"java.lang.IllegalStateException: Error while preparing projectile"}]
```

**Comment by ibuziuk** [comment] 2018-05-02 16:45
@gastaldi could you please take a look ?

**Comment by ibuziuk** [comment] 2018-05-02 16:45
@ldimaggi are you able to repro ?

**Comment by gastaldi** [comment] 2018-05-02 16:52
@ibuziuk it appears that we are not logging errors when preparing the projectile. I just pushed https://github.com/fabric8-launcher/launcher-backend/commit/970a5ac5e4bfb3fba5b8d562bd3e0179ce1f5535 which may show what's going on. I'll update production and ask you to try again

**Comment by gastaldi** [comment] 2018-05-02 17:01
@ibuziuk production updated, can you reproduce that error again?

**Comment by ibuziuk** [comment] 2018-05-02 17:04
![image](https://user-images.githubusercontent.com/1461122/39538011-9b8ead8c-4e3b-11e8-965f-32de3042259d.png)


```
Failed to load resource: the server responded with a status of 400 (Bad Request)
_scrollbars.less:6 400 - Bad Request [{"message":"java.lang.IllegalStateException: Error while preparing projectile: Booster not found in catalog: Mission [id=rest-http, name=REST API Level 0, description=The REST API Level 0 mission shows how to map business operations to a remote procedure call endpoint over HTTP using a REST framework. This corresponds to Level 0 in the Richardson Maturity Model. Creating an HTTP endpoint using REST and its underlying principles to define your API lets you quickly prototype and design the API flexibly., metadata={level=foundational}]-Runtime [id=vert.x, name=Eclipse Vert.x, description=A tool-kit for building reactive applications on the JVM., metadata={pipelinePlatform=maven}]-Version [id=current-redhat, name=current-redhat, description=null, metadata={}] "}]
```

**Comment by gastaldi** [comment] 2018-05-02 17:16
I see the error in the logs now: 

```

2018-05-02 17:03:13,679 WARNING [MissionControlImpl] (default task-17) Error while preparing projectile: Booster not found in catalog: Mission [id=rest-http, name=REST API Level 0, description=The REST API Level 0 mission shows how to map business operations to a remote procedure call endpoint over HTTP using a REST framework. This corresponds to Level 0 in the Richardson Maturity Model. Creating an HTTP endpoint using REST and its underlying principles to define your API lets you quickly prototype and design the API flexibly., metadata={level=foundational}]-Runtime [id=vert.x, name=Eclipse Vert.x, description=A tool-kit for building reactive applications on the JVM., metadata={pipelinePlatform=maven}]-Version [id=current-redhat, name=current-redhat, description=null, metadata={}] : java.lang.IllegalArgumentException: Booster not found in catalog: Mission [id=rest-http, name=REST API Level 0, description=The REST API Level 0 mission shows how to map business operations to a remote procedure call endpoint over HTTP using a REST framework. This corresponds to Level 0 in the Richardson Maturity Model. Creating an HTTP endpoint using REST and its underlying principles to define your API lets you quickly prototype and design the API flexibly., metadata={level=foundational}]-Runtime [id=vert.x, name=Eclipse Vert.x, description=A tool-kit for building reactive applications on the JVM., metadata={pipelinePlatform=maven}]-Version [id=current-redhat, name=current-redhat, description=null, metadata={}]
  | at io.fabric8.launcher.core.impl.MissionControlImpl.lambda$prepare$0(MissionControlImpl.java:80)
  | at java.util.Optional.orElseThrow(Optional.java:290)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.prepare(MissionControlImpl.java:80)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.prepare(MissionControlImpl.java:41)
  | at io.fabric8.launcher.osio.OsioMissionControl.prepare(OsioMissionControl.java:72)
  | at io.fabric8.launcher.osio.web.endpoints.OsioEndpoint.launch(OsioEndpoint.java:56)
  | at io.fabric8.launcher.osio.web.endpoints.OsioEndpoint$Proxy$_$$_WeldSubclass.launch$$super(Unknown Source)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
  | at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
  | at org.hibernate.validator.internal.cdi.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
  | at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
  | at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
  | at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
  | at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
  | at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
  | at io.fabric8.launcher.osio.web.endpoints.OsioEndpoint$Proxy$_$$_WeldSubclass.launch(Unknown Source)
  | at io.fabric8.launcher.osio.web.endpoints.OsioEndpoint$Proxy$_$$_WeldClientProxy.launch(Unknown Source)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
  | at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  | at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
  | at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:130)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.fabric8.launcher.web.providers.CorsFilter.doFilter(CorsFilter.java:63)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.fabric8.launcher.web.providers.gzip.GZipFilter.doFilter(GZipFilter.java:39)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
  | at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  | at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  | at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
  | at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
  | at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
  | at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
  | at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
  | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
  | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
  | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
 

``` 

I'll investigate

**Comment by ldimaggi** [comment] 2018-05-02 17:28
This is a duplicate of:  https://github.com/openshiftio/openshift.io/issues/3418

**Comment by gastaldi** [comment] 2018-05-02 17:28
@ibuziuk the `runtimeVersion` is wrong. It should be `redhat` not `current-redhat`. The latter is the version used in Spring Boot and the same doesn't apply to Vert.x. 

@invincibleJai this is a UI bug, can you check?

**Comment by gastaldi** [comment] 2018-05-02 17:36
I think this issue can be closed in favor of the duplicate issue above

**Comment by invincibleJai** [comment] 2018-05-02 17:39
@gastaldi yes it's an issue from UI, we will put a fix for this soon. Closing it as duplicate of https://github.com/openshiftio/openshift.io/issues/3418

**Closed by invincibleJai** 2018-05-02 17:39 UTC
Labels: area/launcher, team/analytics/wizard, type/bug
