### ISSUE TITLE
Missing scroll in dialogs

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1155] opened 2017-10-19 13:10 UTC
![image](https://user-images.githubusercontent.com/1105127/31772322-99d940e2-b4df-11e7-95a1-9c85c7d0ca48.png)

there is also a display glitch with the bottom square elements which is drawing outside of the dialog

**Comment by apupier** [comment] 2017-10-19 13:18
it is on all dialogs:
![image](https://user-images.githubusercontent.com/1105127/31772677-bf2175c6-b4e0-11e7-98d8-de54e8803a33.png)

**Comment by corinnekrych** [comment] 2017-10-19 13:28
@joshuawilson we need to push to PROD 318d700917e020103847a02a00523d300e81283c of fabric8-ui to fix it

**Comment by alexeykazakov** [comment] 2017-10-19 14:56
Duplicates https://github.com/openshiftio/openshift.io/issues/1138 (not closing because it's not in prod yet)

**Comment by joshuawilson** [comment] 2017-10-19 18:15
Please verify, the fix should be in prod.

**Comment by joshuawilson** [comment] 2017-11-08 21:22
I confirm this is not fixed. @mindreeper2420 can you please take a look. Both the left and right sides extend past the modal.

**Comment by corinnekrych** [comment] 2017-11-09 07:09
@joshuawilson @mindreeper2420 I've just tested it on PROD:
![screenshot 2017-11-09 08 08 19_preview](https://user-images.githubusercontent.com/1395710/32592701-45fbd830-c525-11e7-8061-2cd3551adfbb.png)

and I see it fixed...
#puzzled
@joshuawilson how do you reproduce the problem?

**Comment by mindreeper2420** [comment] 2017-11-09 13:52
@joshuawilson @corinnekrych The scrolling is present for me in production. I'm not seeing any issues.

**Comment by corinnekrych** [comment] 2017-11-09 15:19
@mindreeper2420 @joshuawilson I'm closing the issue as fixed then.

**Comment by joshuawilson** [comment] 2017-11-09 19:55
If you reduce the size of viewport the inner views extend beyond the modal.

**Comment by mindreeper2420** [comment] 2017-11-10 00:10
@joshuawilson do you have an idea as to the resolution you see that at?

**Comment by joshuawilson** [comment] 2017-11-10 07:43
I can't get to it right now due to a bug but I just kept shrinking the screen until it happened.

**Comment by joshuawilson** [comment] 2017-11-10 15:09
@mindreeper2420 if you make the screen smaller then the modal then you have to scroll down to see the bottom of the model you can see things extending below the edge. The smaller the screen the more that sticks out.

**Comment by joshuawilson** [comment] 2017-11-19 05:39
@mindreeper2420 are you able to reproduce it?

**Comment by corinnekrych** [comment] 2017-12-06 14:51
@joshuawilson @mindreeper2420 sorry but i can reproduce it :/
https://www.dropbox.com/s/khxfs7i7goj4v1d/Screenshot%202017-12-06%2015.49.38.png?dl=0

**Closed** 2017-12-07 15:45 UTC
Labels: area/app-wizard, area/UI, SEV2-high, team/platform, type/bug
