### ISSUE TITLE
Labels for work items can not really removed.

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1836] opened 2018-01-10 12:49 UTC
Create some work items, and add labels for them. Then try to remove the labels. They seems to be removed. But when you click "Add label", the labels are still there.

**Comment by liangxia** [comment] 2018-01-10 12:50
![screenshot from 2018-01-10 20-47-02](https://user-images.githubusercontent.com/4716987/34773774-d92f6740-f647-11e7-89af-71296acc2155.png)
![screenshot from 2018-01-10 20-47-23](https://user-images.githubusercontent.com/4716987/34773784-e17bff1c-f647-11e7-881a-8395129eeec1.png)
![screenshot from 2018-01-10 20-47-36](https://user-images.githubusercontent.com/4716987/34773787-e3c51150-f647-11e7-811e-0b098449c85c.png)

**Comment by michaelkleinhenz** [comment] 2018-01-10 14:48
The dropdown only contains all available labels, not the assigned ones. But I think this is two bugs overlaying. I can confirm issues with the labels dropdown on prod-preview.

**Comment by nimishamukherjee** [comment] 2018-01-25 07:12
@michaelkleinhenz when we use the drop down, we are associating / disassociating or assigning/unassigning labels with a work item. This experience is similar to Assign User, with the added functionality of "Creating Label".

We can rename the action as Assign Label, keeping it consistent with users. Or we could use Git like phrase "Apply Label"

**Comment by divyanshiGupta** [comment] 2018-01-25 09:03
Yes I agree with @nimishamukherjee and we should have a separate functionality for deleting labels. Or we can have both the things create label and delete label at one place rather than in the label-selector dropdown.

**Comment by qodfathr** [comment] 2018-01-27 20:10
@michaelkleinhenz it sounds like the plan is to change the words on the screen, but, otherwise, **this** issue can be closed as working as designed. Agreed? (If yes, feel free to close.)

**Comment by debloper** [comment] 2018-02-22 13:17
Should be closed as `(unassigning a label from a work item !== deleting the label itself)` so it's working as intended. Further changes/updates to label management can have their own stories/issues.

**Closed** 2018-04-08 12:10 UTC
Labels: SEV2-high, area/planner, team/planner, type/bug
