### ISSUE TITLE
Build URL not set correctly on GitHub commit

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4119] opened 2018-08-02 09:58 UTC
![screenshot from 2018-08-02 15-20-11](https://user-images.githubusercontent.com/10185999/43576808-da8e6bca-9667-11e8-8de5-42ae138c04a7.png)

The tick mark sign should take me to build logs. It does not because the url set is wrong.
I see a URL something like this http://www.unconfigured-jenkins-location.com/job/kishansagathiya/job/app-test-1/job/master/9/display/redirect

http://www.unconfigured-jenkins-location.com should be changed to https://jenkins.openshift.io
Again in general I see logs that are publicly available and here we have to login, so I don't know how well the whole thing would work. 

It is clearly a bug, but it is not something that would halt developers in anyway. However, this is really desirable from users' perspective.

**Comment by piyush1594** [comment] 2018-08-02 10:04
Duplicate of #1259

**Closed by piyush1594** 2018-08-02 10:04 UTC
Labels: SEV2-high, team/build-cd, type/bug
