### ISSUE TITLE
A new user creating a new project fails to create the project's build pipeline

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#361] opened 2017-07-12 15:56 UTC
This is a new issue - first started being seen on July 12.

Steps to recreate:
* Using a user account that is "clean" (in other words, the user has zero github repos defined, zero Che workspaces, and no resources such as builds configs, image streams, etc. defined in OpenShift)
* Create a new space
* Create a new project from the Vert.X quickstart - accept all defaults in the project creation dialog
* Observe the pipeline page for the project - the build pipeline are not created:

![screenshot from 2017-07-12 11-39-33](https://user-images.githubusercontent.com/642621/28126910-e2effd64-66f8-11e7-9e13-d4eb58db0fc6.png)

Note that the duplicated definitions are due this existing bug - https://github.com/fabric8-ui/fabric8-ui/issues/1707

No logs are created for the username-stage and username-run projects.

**Comment by ldimaggi** [comment] 2017-07-12 15:58
Also note that when the token is refreshed, additional duplicate entries are created:

![screenshot from 2017-07-12 11-57-20](https://user-images.githubusercontent.com/642621/28127039-47c7ab56-66f9-11e7-924f-eeeb45e9b561.png)

**Comment by ldimaggi** [comment] 2017-07-12 16:12
Just noticed - the user account contained undeleted routes in the *-run project - this seems to be the cause of the problem. But - why would this cause the replicated creation of incomplete pipelines?

**Comment by ldimaggi** [comment] 2017-07-12 17:24
Cleaned up the issue with pipelines not being create by deletig unused routes in project-*run

Then reset and started over. Now seeing duplicates being created:

![screenshot from 2017-07-12 13-23-06](https://user-images.githubusercontent.com/642621/28130618-5e725f66-6705-11e7-86cf-0030982e9331.png)

**Comment by ldimaggi** [comment] 2017-07-12 17:45
Screencast:
https://drive.google.com/open?id=0B1s-ZoxD8FjUa2FMd2N4NVRESUU

**Comment by jstrachan** [comment] 2017-07-13 15:31
I can't reproduce; just created a project on prod and it created the pipeline too.

Though there's this issue that various pipelines are triggered too https://github.com/openshiftio/openshift.io/issues/360

**Comment by maxandersen** [comment] 2017-07-13 15:34
I can't reproduce either, but retrying now with a fully blank account to see if its a "new user" only issue.

**Comment by maxandersen** [comment] 2017-07-13 15:39
okey, so I can't reproduce the missing pipelines, but I do now have duplicate entries (two per codespace)

**Comment by maxandersen** [comment] 2017-07-13 19:54
Okey - just reproduced this on a brand newly created user (maxosiotest1@xam.dk).

A new user does not get a working pipeline created AND get double listing of the repos.

This means new users wont be able to use the system thus this is now on kill list.

**Comment by aslakknutsen** [comment] 2017-07-13 21:44
This is in the Jenkins log for that user:

```
INFO: timed out accessing https://api.github.com/repos/maxosiotest1/wonka2/contents/?ref=refs%2Fheads%2Fmaster; will try 2 more time(s)
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:592)
	at org.kohsuke.github.Requester.parse(Requester.java:584)
	at org.kohsuke.github.Requester._to(Requester.java:264)
	at org.kohsuke.github.Requester.to(Requester.java:226)
	at org.kohsuke.github.GHRepository.getDirectoryContent(GHRepository.java:1299)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.stat(GitHubSCMProbe.java:131)
	at org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory$1.isHead(WorkflowBranchProjectFactory.java:74)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.doRetrieve(GitHubSCMSource.java:812)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:479)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:300)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:210)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:630)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:266)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:162)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:969)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 29 more

Jul 13, 2017 7:51:15 PM org.kohsuke.github.Requester parse
INFO: timed out accessing https://api.github.com/repos/maxosiotest1/wonka2/contents/?ref=refs%2Fheads%2Fmaster; will try 1 more time(s)
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:592)
	at org.kohsuke.github.Requester.parse(Requester.java:584)
	at org.kohsuke.github.Requester._to(Requester.java:264)
	at org.kohsuke.github.Requester.to(Requester.java:226)
	at org.kohsuke.github.GHRepository.getDirectoryContent(GHRepository.java:1299)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.stat(GitHubSCMProbe.java:131)
	at org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory$1.isHead(WorkflowBranchProjectFactory.java:74)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.doRetrieve(GitHubSCMSource.java:812)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:479)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:300)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:210)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:630)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:266)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:162)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:969)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 29 more

Jul 13, 2017 7:51:15 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: maxosiotest1/wonka2 #20170713.195105 branch indexing action completed: FAILURE in 10 sec

```

**Comment by rawlingsj** [comment] 2017-07-14 08:27
Are these the same errors in the logs for @ldimaggi issue?  @ldimaggi can you include the jenkins logs please?

**Comment by maxandersen** [comment] 2017-07-14 09:29
> Are these the same errors in the logs for @ldimaggi issue? @ldimaggi can you include the jenkins logs please?

@rawlingsj @ldimaggi is on vacation so if we need these  we'll need to lookup in  dsaas logs like I believe @aslakknutsen  just did for my test user.

**Comment by sbose78** [comment] 2017-07-14 10:16
I see this which looks like jenkins pod wasn't in good shape .. not sure what the status of @maxandersen 's issue is at the moment.

```
INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-62) Response from https://jenkins-maxosiotest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=maxosiotest1 is 503 Service Unavailable
```

**Comment by jstrachan** [comment] 2017-07-14 10:21
I'm just trying to grok what the issue really is.

So this issue is that the BuildConfig and Jenkins job do get created for new users - its just that the job isn't automatically triggered right?

**Comment by jstrachan** [comment] 2017-07-14 10:23
there's a separate issue for duplicates appearing: https://github.com/fabric8-ui/fabric8-ui/issues/1707

**Comment by maxandersen** [comment] 2017-07-14 11:13
> If you manually trigger the build via the kebab menu's Start Pipeline does it work?

let me try that. I did try creating multiple projects and same error - but didn't try manual kick off.

**Comment by maxandersen** [comment] 2017-07-14 11:21
Using the kebab menu I get this: 

![banners_and_alerts_and_pipelines_-_openshift_io](https://user-images.githubusercontent.com/54129/28210218-9f649880-6896-11e7-86d7-c0d977e554eb.png)

I then for reasons unknown to me got a frozen browser. After restart I now have this:

![banners_and_alerts_and_pipelines_-_openshift_io](https://user-images.githubusercontent.com/54129/28210350-37e6d762-6897-11e7-867d-8d91d06837f0.png)

notice it now says "5 minutes" so it does not seem to help using the kebab.

Any specific oc resources I could take a look for ?

**Comment by jstrachan** [comment] 2017-07-14 11:23
so - builds can be triggered manually; there's a duplicate rendering issue which is known - then its just a case of waiting for kubernetes to provision a build slave. Am assuming there's no quota issues in your openshift console right? Any issues in the main Jenkins log?

**Comment by jstrachan** [comment] 2017-07-14 11:25
Note that if there is a pending build, triggering a new build won't show up on the Pipelines page until that new build starts. If you look in the jenkins console you'll see pending builds etc

**Comment by maxandersen** [comment] 2017-07-14 11:29
13 minutes later - nothing there and no resources issues listed afaics.

But I spotted this on https://status.starter.openshift.com/ 

```
Investigating - We are investigating issues related to build failures in starter-us-east-1. Details are here: https://bugzilla.redhat.com/show_bug.cgi?id=1462542

The issue can be worked around by using 'oc start-build' to trigger a second build, which should succeed when the first build fails. 
```

**Comment by maxandersen** [comment] 2017-07-14 11:31
> Note that if there is a pending build, triggering a new build won't show up on the Pipelines page until that new build starts. If you look in the jenkins console you'll see pending builds etc

When I go to https://jenkins-maxosiotest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/blue/organizations/jenkins/maxosiotest1%2Fwonka2/branches/ there is nothing there afaics. 

![jenkins___wonka2](https://user-images.githubusercontent.com/54129/28210637-ac53e13e-6898-11e7-8369-2aa786784340.png)

**Comment by jstrachan** [comment] 2017-07-14 11:34
you can't find any jenkins jobs and there are no pending jobs at all in jenkins? could you post a screenshot of https://jenkins-maxosiotest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/

**Comment by maxandersen** [comment] 2017-07-14 11:34
and btw. nothing is showing up  in any of the users projects Builds on https://console.starter-us-east-2.openshift.com/console/project/maxosiotest1/browse/builds either.

**Comment by maxandersen** [comment] 2017-07-14 11:36
> you can't find any jenkins jobs and there are no pending jobs at all in jenkins? could you post a screenshot of https://jenkins-maxosiotest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/

<img width="1341" alt="menubar_and_dashboard__jenkins_" src="https://user-images.githubusercontent.com/54129/28210756-4cc640f8-6899-11e7-8226-18db6513b146.png">

and when I click that I get this:

![default__maxosiotest1___jenkins_](https://user-images.githubusercontent.com/54129/28210762-583689ac-6899-11e7-80be-cf6d90bfa233.png)

and following that here: 

![banners_and_alerts_and_welcome__jenkins_](https://user-images.githubusercontent.com/54129/28210780-72cd8f04-6899-11e7-8be1-0e7654021a4c.png)

So yeah, looks pretty darn empty :/

**Comment by rawlingsj** [comment] 2017-07-14 11:55
The logs show a timeout when jenkins first did the org scan to create the jobs, this meant they weren't generated correctly.  I manually re-ran the scan via jenkins and it completed successfully + automatically triggered the pipelines

![screenshot 2017-07-14 12 47 03](https://user-images.githubusercontent.com/1457180/28211263-9cf43d6a-6893-11e7-9198-f1b050570a49.png)

My guess is this isn't the same problem as Len but we'll see from the logs...

**Comment by ldimaggi** [comment] 2017-07-16 16:18
Sorry to be late to the thread - I cannot recreate the problem of the build pipelines not being created - the problem of the duplicate build pipelines IS still present and is logged here: https://github.com/fabric8-ui/fabric8-ui/issues/1707

**Comment by ldimaggi** [comment] 2017-07-16 16:21
Closing in favor of fabric8-ui/fabric8-ui#1707

**Comment by joshuawilson** [comment] 2017-07-17 01:46
@ldimaggi why close this if there is such a good conversation happening here?

**Comment by maxandersen** [comment] 2017-07-17 10:30
@ldimaggi I've reproduced the issue of build pipelines not being created twice - only happens for new users.

Thus reopening this until verified it is not happening for new users this week :)

**Comment by ldimaggi** [comment] 2017-07-17 12:40
Sorry Josh - I thought that this was a dup of: https://github.com/fabric8-ui/fabric8-ui/issues/1707

**Comment by bmicklea** [comment] 2017-07-18 11:19
My understanding is that this issue is a blocker for us to start bringing external users into the IO preview. Is there a status on this issue?  Do we know the root cause and is someone working on the fix?

**Comment by jstrachan** [comment] 2017-07-18 11:43
we are working on a workaround; its basically due to Jenkins not being up for new users when they try to create a new app.

The fix we're working on is to startup the tenant services faster and to avoid requiring the Jenkins master to be up in the new app wizard

**Comment by jstrachan** [comment] 2017-07-18 11:44
see these comments which are related https://github.com/openshiftio/openshift.io/issues/366#issuecomment-316011160

**Comment by bmicklea** [comment] 2017-07-18 11:45
Thanks for the additional context and link James - makes sense.

**Comment by jstrachan** [comment] 2017-07-19 14:01
this is now fixed in production; for existing users, [update your tenant](https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-update-my-tenant-) - otherwise for new users this should now be resolved.

**Comment by ldimaggi** [comment] 2017-07-20 14:30
Tested this on July 20 - verified fix in production - steps performed:
* Created a 100% new user account (osiotest3141@yahoo.com) in github, and OSIO
* Logged into OSIO
* Created new space
* Created new project - from Vert.X basic quickstart - accepted all defaults in project creation wizard
* Verified that build pipeline was created
* Verified that bug of multiple pipelines created is still present - https://github.com/fabric8-ui/fabric8-ui/issues/1707
* Verified operation of app deployed to stage
* Verified operation of app deployed to run
* Created new Che workspace 
* Executed junit tests for project in Che
* Verified that this error is still present after executing junit tests in Che - https://github.com/fabric8-ui/fabric8-ui/issues/1694

Screencast files are here:
https://drive.google.com/open?id=0B1s-ZoxD8FjUazZ3amw0bjdYa0E

**Comment by joshuawilson** [comment] 2017-07-20 15:06
@maxandersen can we close this?

**Comment by ldimaggi** [comment] 2017-07-20 15:16
It worked for me - with a new user account - Max - you also saw this - is the fix working for you too?

**Comment by maxandersen** [comment] 2017-07-21 13:25
I wont be able to verify this before stopping today but I would do the same test you already did thus trusting your verification. Closing here.

**Closed by maxandersen** 2017-07-21 13:25 UTC
Labels: area/app-wizard, kind/bug, severity/blocker, team/platform
