### ISSUE TITLE
Profile Work ItemsComponent displays logged in user's work items when viewing other user's profile pages

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#3837] opened 2018-06-20 17:33 UTC
Viewing the profile page of another user can result in a `TypeError` which can cause duplicate and broken components to be displayed on the screen.

The console is complaining about an undefined value in the work-items component at line 42 [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.html#L42). This is likely because `loggedInUser`is will not be defined in `ngOnInit()` when I'm not viewing my own space [[1]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L64
). Here's a screenshot of the console logged error:
![error](https://user-images.githubusercontent.com/10425301/41673857-3cafc8b0-748c-11e8-8796-a21c8abcc0d1.png)

Furthermore, `fetchWorkItemsBySpace` [[2]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L116) and the getter method for `space` [[3]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L90) retrieve values for the `loggedInUser`, which doesn't quite make sense if I'm not viewing my own profile page. In the screenshots below it looks like the widget is trying to load my work items into the work item component, but will not succeed because `loggedInUser` will not have a value. I've been able to view other user's profiles before without issues (that I'm aware of), perhaps having work-items in the current logged in users recent spaces may be a trigger condition for this bug. 

Clicking on 'X\'s Spaces' will cause the page to display broken and duplicate components.

Here's what I see when I view my profile:
![my-profile](https://user-images.githubusercontent.com/10425301/41673734-cfc4e0b4-748b-11e8-9d30-ba95ab63a9a6.png)

Here's what I see when I view profiles of other users:
![chris-profile](https://user-images.githubusercontent.com/10425301/41673735-d1660650-748b-11e8-8ed5-e0dec5882e22.png)
![jie-profile](https://user-images.githubusercontent.com/10425301/41673736-d317a68e-748b-11e8-96c6-1154839a2e2c.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.html#L42
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L64
[2] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L116
[3] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L90

**Comment by andrewazores** [comment] 2018-06-21 18:33
@openshiftio/uxd-team what should this widget display when viewing another user's profile?

**Comment by andrewazores** [comment] 2018-06-21 18:52
Related, more general issue: https://github.com/openshiftio/openshift.io/issues/3635

**Comment by aptmac** [comment] 2018-06-21 19:08
I don't think #3635 should be relevant after the overhaul to the profile page; the user controls are hidden behind `ngIf="viewingOwnAccount"`

**Comment by aptmac** [comment] 2018-06-25 16:17
@openshift/uxd-team

**Comment by joshuawilson** [comment] 2018-06-26 02:11
@openshiftio/uxd-team

**Comment by aptmac** [comment] 2018-06-26 16:10
https://github.com/fabric8-ui/fabric8-ui/pull/3036 has been merged which solved the initial issue here; the undefined loggedInUser value.

However, loggedInUser is still used in several parts of the component [0][1][2][3] which cause the logged in user to see their recent work items in the work-item-component of other user's profile. For example, I have a work item, that I see on my profile, but I also see it when I view other user's profile pages.
![loggedInUserProfile](https://user-images.githubusercontent.com/10425301/41924906-2c57d47e-7939-11e8-9be8-a8293416a32f.png)
![anotherUserProfile](https://user-images.githubusercontent.com/10425301/41924908-2c693020-7939-11e8-959e-fef1f5280c6b.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L64
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L65
[2] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L90
[3] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.ts#L116

**Comment by muruGanesan** [comment] 2018-06-28 14:16
@joshuawilson, it looks like more of an implementation issue. 
Please let us know if any UX solution or recommendation is needed for this issue

**Comment by joshuawilson** [comment] 2018-06-28 16:29
@muruGanesan this is not an issue for UX but a question was raised above for you. 

"What should this widget display when viewing another user's profile?"

**Comment by mceledonia** [comment] 2018-07-02 14:19
@aptmac @andrewazores @joshuawilson 

I might be misunderstanding the issue but the screenshots seem to be correct (other than the broken components), the tabs of "My work items" and "My spaces" should indeed change to "[User's] work items" and "[User's] spaces" with both lists showing public items in both of those lists. The tabs and lists should function the same as if viewing your own profile. The screenshots above show that correctly, it's just the list components below that look incorrect as you've said.

**Comment by andrewazores** [comment] 2018-07-10 17:52
@aptmac what was the last status of this? @mceledonia confirmed above that when viewing the profile page of another user, the widgets should indeed list the workitems owned by that user and the spaces they are a member of. As far as I can tell the current state of the widgets on prod is that the Spaces widget correctly displays the list of spaces that the viewed user belongs to, but the workitems widget incorrectly displays a list of work items assigned to the *viewing* user.

**Comment by aptmac** [comment] 2018-07-10 19:37
Currently, the work-items component on the profile page will display the work-items from recent spaces that belong to the current logged in user. As a result, if I have work-items in my recent spaces I will see them in the component when viewing someone else's profile. So the component needs to be updated to display the work-items of the currently viewed user.

Additionally, the spaces/work-items displayed may be incorrect. If the profile work-item component is supposed to be similar to the one on the home page, we'd want to display the work items of the spaces the user owns, plus the spaces they are a collaborator on [0]. However, this API doesn't yet exist [1], and the collaborator API is being deprecated so it doesn't seem to be a high priority at the moment. In the mean time, it looks like we can simply display the work-items that belong to the spaces the user owns [2].

Also, I had also mistakenly looked at the profile and home work-item components as being the same, but they seem to have distinct differences. For example, on the home page the widget is coupled with widgets for displaying "recent" data, but the work item component itself doesn't mention that [3]. Because it uses the `spacesService.recent` it can contain spaces that the user does not own, but may be a collaborator on. 
However, the profile work items component doesn't mention "recent" and is coupled with a spaces component that displays all spaces; perhaps it should show all work-items? The issue here is the current setup iterates through the set of spaces and makes an API call for each space, and this can be potentially costly and time consuming.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2966#issuecomment-396257894
[1] https://github.com/openshiftio/openshift.io/issues/3760
[2] https://github.com/fabric8-ui/fabric8-ui/pull/2966#issuecomment-396277602
[3] https://github.com/fabric8-ui/fabric8-ui/pull/2966#discussion_r199374971

**Comment by jiekang** [comment] 2018-07-16 13:52
To clarify some of the conversation above. The plan of action should be to update both components to show "[username]'s spaces/work items" and the work item widget should be fixed to actually show that user's work items. The spaces widget is already correct in that regard. 

Does that sound right? @aptmac @andrewazores

**Comment by aptmac** [comment] 2018-07-16 13:56
@jiekang Yeah that sounds right to me.

**Comment by andrewazores** [comment] 2018-07-16 14:14
@jiekang correct

**Comment by jiekang** [comment] 2018-07-26 14:46
Closing as PR addressing this is merged.

**Closed by jiekang** 2018-07-26 14:46 UTC
Labels: SEV2-high, area/UX, area/user/profile, team/platform, team/ux, type/bug
