### ISSUE TITLE
Pipeline display disappears when user loads different tabbed pages

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#431] opened 2017-07-27 03:56 UTC
To recreate:
* Create a new project - observe the pipeline:
![screenshot from 2017-07-26 23-53-19](https://user-images.githubusercontent.com/642621/28653829-dc66beae-725d-11e7-9fb8-b0e320d369b8.png)
![screenshot from 2017-07-26 23-53-35](https://user-images.githubusercontent.com/642621/28653834-e35cb5ba-725d-11e7-93e7-66f984ca2ba0.png)

* Move to the Applications page and then return to the Pipelines page:
![screenshot from 2017-07-26 23-53-51](https://user-images.githubusercontent.com/642621/28653850-f95514f2-725d-11e7-8976-8161a33bbecb.png)

And the pipeline is gone

**Comment by jstrachan** [comment] 2017-07-27 11:20
cant reproduce

this sounds like some kind of JavaScript / network issue. The next time you can reproduce this any chance you could:
* open the `JavaScript console`, anything recent in Red? You could try navigate to the `Codebases` page, clear the log and go back to the `Pipelines` page - anything  red? Maybe attach the entire JavaScript console log from loading the `Pipelines` page to see if we can find anything?
* open the` Networks` tab, again go to `Codebases`, clear the network log, then go back to `Pipelines`. Any requests red? Also can you filter by `builds` and `buildconfigs` in the filter box on the `Network` tab and look at the last GET request for those 2 resources; what was the status code and what was the `Response`? Seeing those might help us figure out why, sometimes, for some users, things stop working 

I'm guessing this is some temporary network glitch where your browser gets back garbage?

**Comment by jstrachan** [comment] 2017-07-27 11:20
sounds like a dupe of #429

**Comment by qodfathr** [comment] 2018-01-17 13:32
Closing as dupe of #429.

**Closed by qodfathr** 2018-01-17 13:32 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug
