### ISSUE TITLE
Multiple tooltips remain open simultaneously

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#3359] opened 2018-04-30 09:06 UTC
![opentooltips](https://user-images.githubusercontent.com/1892722/39420830-d640517e-4c83-11e8-958f-545048da71cb.png)

**Comment by kwk** [comment] 2018-04-30 21:25
I don't know if this shall be considered an error.

**Comment by joshuawilson** [comment] 2018-04-30 21:27
Maybe not a bug, but only bugs get severity.
@nimishamukherjee if not a bug, please set the `type`
Might be a UX issue.

**Comment by divyanshiGupta** [comment] 2018-05-04 05:01
@nimishamukherjee do we need to have a discussion on this? Or should I implement close popover on outside click?

**Comment by rgarg1** [comment] 2018-05-04 05:11
UX can take the final call, but IMHO we can leave the closing of the info-tips part to the user.

**Comment by rgarg1** [comment] 2018-05-04 05:16
I see two issues with the current implementation:
1) The info-tips overlap with each other, and clicking on the lower info-tip does not bring it to the foreground. This makes it difficult for the user to read it
2) Clicking the info-tip for Experiences also results in a click on the Experiences. The same behavior was experienced with all other info-tips too. 

@nimishamukherjee Should I track these separately in a defect?

**Comment by divyanshiGupta** [comment] 2018-05-04 05:37
@rgarg1 for the 2 issue that you mentioned, I have handled the click propagation to parent on the infotip icon and the close pop-over icon. Are you clicking on the pop-over itself?

**Comment by divyanshiGupta** [comment] 2018-05-04 05:41
And for the 1st issue if close pop-over on outside click is implemented then it will take care of multiple tooltips remaining open simultaneously and overlapping issue.

**Comment by divyanshiGupta** [comment] 2018-05-04 05:56
![Uploading New GIF.gif…]()

**Comment by divyanshiGupta** [comment] 2018-05-04 06:01
![new gif](https://user-images.githubusercontent.com/20724543/39614567-85582bf2-4f8e-11e8-8cdc-f92b4681d75b.gif)

**Comment by divyanshiGupta** [comment] 2018-05-04 06:01
I couldnt reproduce 2nd issue.

**Comment by rgarg1** [comment] 2018-05-04 06:01
@divyanshiGupta Yes, I'm clicking on the pop-over. This click should not propagate down but instead should only bring the clicked pop-over to the foreground.

**Comment by rgarg1** [comment] 2018-05-04 06:04
for the second issue, the following Gif would help you:

![infotips](https://user-images.githubusercontent.com/28748448/39614656-258d84e6-4f8f-11e8-89d2-b83f260d9b67.gif)

**Comment by divyanshiGupta** [comment] 2018-05-04 06:05
@rgarg1 Got it :+1: . So if outside click is in place all of the above-mentioned issues will be resolved. 
@nimishamukherjee should I start implementing it?

**Comment by rgarg1** [comment] 2018-05-04 06:05
I'm not sure if outside click should be implemented at all.

**Comment by divyanshiGupta** [comment] 2018-05-04 06:06
Should we wait for the UX to look at it?

**Comment by rgarg1** [comment] 2018-05-04 06:07
Issue # 3

The info-tips always stack-up in a particular order (Scenario > Exp > Reqs), but not in the order they were opened.

**Comment by rgarg1** [comment] 2018-05-04 06:08
Cc @sunilmalagi @Veethika

**Comment by sunilmalagi** [comment] 2018-05-07 06:14
@nimishamukherjee @rgarg1 @divyanshiGupta @Veethika 
UX Solution:
When the user clicks on another tool tip, while one is still open, the previous tooltip should automatically get closed, since the primary function of the tooltip is to provide quick information about something.

**Comment by divyanshiGupta** [comment] 2018-05-07 09:26
@sunilmalagi The desired behavior that I am suggesting here is that any outside click to a popover will close it which inherently also handles the use case you mentioned.

**Comment by divyanshiGupta** [comment] 2018-05-08 10:19
@sunilmalagi ^^

**Comment by sunilmalagi** [comment] 2018-05-08 10:32
@divyanshiGupta Agree with you Divyanshi...

**Comment by Veethika** [comment] 2018-06-27 11:39
@nimishamukherjee  @divyanshiGupta @sunilmalagi this problem seems to persist.
<img width="596" alt="screen shot 2018-06-27 at 5 07 37 pm" src="https://user-images.githubusercontent.com/35127763/41971608-aa5b5d8e-7a2c-11e8-898e-99ad972587b8.png">
Could we implement the following solution and close this?

UX Solution:
The moment a user click anywhere outside the tooltip(including another tooltip trigger) it should close.

**Comment by rgarg1** [comment] 2018-06-27 11:57
@Veethika The PR that fixes it is still open.

**Closed** 2018-07-09 06:58 UTC
Labels: SEV3-medium, area/UX, area/planner, team/planner, team/ux, type/bug
