### ISSUE TITLE
Display reasoning for Alternative and Companion components

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#748] opened 2017-09-04 09:58 UTC
### Description
End user should be shown the reason behind alternate and companion components

#### Acceptance Criteria
- Alternate components are recommended with reasoning about the outliers (usage based or license based)
- Companion components are recommended with reasoning about the confidence of co-occurrence with other stack components 

##### Tasks
- [x] https://github.com/openshiftio/openshift.io/issues/984

**Comment by krishnapaparaju** [comment] 2017-09-05 13:56
Would need to work backwards: Baseline the reason that would be shown on UI before planning the implementation.

@samuzzal-choudhury

**Comment by sara-02** [comment] 2017-09-13 12:49
@miteshvp This looks like a duplicate of #771

**Comment by miteshvp** [comment] 2017-09-14 03:11
@sara-02 thanks. I have added the link in the description now.

**Comment by miteshvp** [comment] 2017-09-14 03:11
@harjinder-hari maybe, you may want to improve the description with more details https://github.com/openshiftio/openshift.io/issues/771

**Comment by krishnapaparaju** [comment] 2017-10-21 06:41
@miteshvp @saara-02 what are the possible reasons OSIO user get to see for recommended alternative components ?

**Comment by sara-02** [comment] 2017-10-23 07:19
@krishnapaparaju Alternate recommendation shown if the component is either a PGM outlier or a license outlier.

**Comment by miteshvp** [comment] 2017-11-03 07:01
Current implementaion recommends an alternate packages if they are usage based outliers or license based outliers. Reasoning is only implemented for Usage based.

**Closed** 2017-11-03 07:00 UTC
Labels: area/analytics, kind/task, stream/analytics, team/analytics
