### ISSUE TITLE
Bug: API stack-analysis is not working

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#378] opened 2017-07-20 09:20 UTC
API call:
``` 
$ curl -sH "Authorization: Bearer $OSIO_TOKEN" -F "manifest[]=@./pom.xml" https://recommender.api.openshift.io/api/v1/stack-analyses
````

Result:
````
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
````

**Comment by samuzzal-choudhury** [comment] 2017-07-23 17:27
@luebken The multiple manifest file support for /stack-analyses requires a new parameter `filePath[]` to be added along with `manifest[]` mandatorily.

`curl -sH "Authorization: Bearer $OSIO_TOKEN"  -F "manifest[]=@./pom.xml" -F "filePath[]=/home/JohnDoe" https://recommender.api.openshift.io/api/v1/stack-analyses`

Please check the [WIP cookbook](https://docs.google.com/document/d/1pDPrKebOTBoAQJoze8SBztKMe1rJuIlBJ-bAL1tlkV4/edit#) for more details.

@joshuawilson could you please close this issue. @luebken please feel free to reopen if you think that the issue is not resolved.

**Comment by luebken** [comment] 2017-07-24 12:58
API call with the additional parameter seems to work. Thanks @samuzzal-choudhury 

Although I don't understand why there was a breaking change introduced with no update in the API version. Especially since this could have been easily solved by using defaults (current working directory).

@joshuawilson feel free to close.

**Comment by adisakala** [comment] 2017-07-24 13:15
Closing per @luebken comments

**Closed by adisakala** 2017-07-24 13:15 UTC
Labels: area/analytics, kind/bug, team/analytics
