### ISSUE TITLE
Tenant Jenkins builds do not timeout

### ISSUE THREAD

**Issue by vpavlin** [openshiftio/openshift.io#1376] opened 2017-11-16 10:47 UTC
According to information from @kbsingh, Jenkins jobs should terminate with timeout after 30 minutes, but they do not.

Here is a screenshot of job running for 15 hours:

![screenshot from 2017-11-16 11-43-54](https://user-images.githubusercontent.com/4759808/32887256-9504e842-cac3-11e7-99ef-2bd0e691525d.png)

This is problematic (not only) because Idler will not idle Jenkins with running jobs and if a user starts a build and walks away for a weekend, Jenkins will run waiting for input.

**Comment by maxandersen** [comment] 2017-11-22 09:08
@rawlingsj any idea on this ? are these jobs stuck on approval stage or how ?

**Comment by rawlingsj** [comment] 2017-11-22 09:26
I'm not sure what feature times jenkins jobs out, TBH it's the first I've heard of a jenkins job only being able to run for 30 mins - I'd say if that's the case then there's a usability issue here as pipeline jobs are expected to be long running especially with approval steps involved. 

@kbsingh can you provide more information around this feature that @vpavlin is referring to please?  

@maxandersen @qodfathr are you aware of this 30 min timeout too?  Is this a requirement?  We can build that into the pipelines easy enough using a `timeout` step but I'd say that has a significant pipeline usability impact.
```
timeout(time: 1, unit: 'HOURS') {
   ...
}
```
We use this in the UI pipelines https://github.com/fabric8-ui/fabric8-ui/blob/master/Jenkinsfile#L15

**Comment by maxandersen** [comment] 2017-11-22 12:51
The 30 min could be another value, but we've had requirement from day one that we can't keep having jenkins running "forever" as it takes alot of resources. @vpavlin is working on the idler that is being made to make it so we can idle jenkins when its either not doing anything, taking too long or just sitting around waiting for approval.

For jobs that are taking too long we can just kill the process - but we do want to make sure approval steps are handled well. Our understanding is that jenkins has all state on disk thus it should be possible for us to kill jenkins even with approval states as it would at startup end up back in the same approval state.

Is that a wrong assumption about Jenkins pipelines ? 

My understanding was that if the approval step is on the master (not in a node) then this should work - but looking at https://github.com/maxandersen/test/blob/master/Jenkinsfile#L38 I see that `approve` which in the end calls `input` is always in the node which could explain why jenkins reports it has jobs running for hours ?

**Comment by rawlingsj** [comment] 2017-11-22 13:13
>The 30 min could be another value, but we've had requirement from day one that we can't keep having jenkins running "forever" as it takes alot of resources. @vpavlin is working on the idler that is being made to make it so we can idle jenkins when its either not doing anything, taking too long or just sitting around waiting for approval.

Ok fair enough - that's an idling requirement which as @vpavlin from the SD team mentioned he's working on so I think we can remove the **bug** and **cd team** labels?

For jobs that are taking too long we can just kill the process - but we do want to make sure approval steps are handled well. Our understanding is that jenkins has all state on disk thus it should be possible for us to kill jenkins even with approval states as it would at startup end up back in the same approval state.

> Is that a wrong assumption about Jenkins pipelines ?

Your assumption is correct.

> My understanding was that if the approval step is on the master (not in a node) then this should work - but looking at https://github.com/maxandersen/test/blob/master/Jenkinsfile#L38 I see that approve which in the end calls input is always in the node which could explain why jenkins reports it has jobs running for hours ?

The `node{..}` is run on the master and anything in a build pod block i.e. `maven{...}` https://github.com/maxandersen/test/blob/master/Jenkinsfile#L9 is run in a build pod so the Jenkinsfile is correct as the wait for approval is outside this block and the build pod has terminated already.

Mind you @maxandersen I think you're talking about build pods sticking around but the issue is about jenkins jobs terminating after 30 mins.

**Comment by maxandersen** [comment] 2017-11-22 13:34
> The 30 min could be another value, but we've had requirement from day one that we can't keep having jenkins running "forever" as it takes alot of resources. @vpavlin is working on the idler that is being made to make it so we can idle jenkins when its either not doing anything, taking too long or just sitting around waiting for approval.
> Ok fair enough - that's an idling requirement which as @vpavlin from the SD team mentioned he's working on so I think we can remove the bug and cd team labels?

I think this issue was @vpavlin's ask to get help from cd-team to figure out why there was this long running jenkins job as assumption was jobs were setup to stop sooner.

> For jobs that are taking too long we can just kill the process - but we do want to make sure approval steps are handled well. Our understanding is that jenkins has all state on disk thus it should be possible for us to kill jenkins even with approval states as it would at startup end up back in the same approval state.
> 
> Is that a wrong assumption about Jenkins pipelines ?
> Your assumption is correct.
> 
> My understanding was that if the approval step is on the master (not in a node) then this should work - but looking at https://github.com/maxandersen/test/blob/master/Jenkinsfile#L38 I see that approve which in the end calls input is always in the node which could explain why jenkins reports it has jobs running for hours ?
> The node{..} is run on the master and anything in a build pod block i.e. maven{...} https://github.com/maxandersen/test/blob/master/Jenkinsfile#L9 is run in a build pod so the Jenkinsfile is correct as the wait for approval is outside this block and the build pod has terminated already.

okey, thought there was another state where node{} does create an agent or similar that prevents shutting down jenkins. if not the case that is irrelevant.

> Mind you @maxandersen I think you're talking about build pods sticking around but the issue is  about jenkins jobs terminating after 30 mins.

Its a mix i reckon, if you are saying when a jenkins job is waiting for input the idler can stop jenkins then we just need to identify how that would happen and then the idler can simply do the idling and we shouldn't need to add explicit timeouts to our pipelines - right ?

**Comment by rawlingsj** [comment] 2017-11-22 13:40
> I think this issue was @vpavlin's ask to get help from cd-team to figure out why there was this long running jenkins job as assumption was jobs were setup to stop sooner.

Ok - it didn't sound like that but yeah if a pipeline (a type of jenkins job) is waiting for approval then yes the job stays running.

> okey, thought there was another state where node{} does create an agent or similar that prevents shutting down jenkins. if not the case that is irrelevant.

not AFAIK

> Its a mix i reckon, if you are saying when a jenkins job is waiting for input the idler can stop jenkins then we just need to identify how that would happen and then the idler can simply do the idling and we shouldn't need to add explicit timeouts to our pipelines - right ?

Correct - I would definitely prefer to avoid timeouts in the Jenkinsfile.  So yes I agree the idler should stop jenkins and idle it.

**Comment by rawlingsj** [comment] 2017-11-22 14:32
After an internal discussion it seems the original comment from KB..

> According to information from @kbsingh, Jenkins jobs should terminate with timeout after 30 minutes, but they do not.

Was actually referring to build pods and not jenkins jobs.  The build pod is an openshift timebound pod which uses separate quota, this build pod is terminated after the maven build but the jenkins job continues to run and uses an executor on the master while waiting for approval.

AFAICT this is working as expected and not an issue.  Closing but please reopen if there's something I've missed.

**Closed by rawlingsj** 2017-11-22 14:32 UTC
Labels: area/pipelines, SEV3-medium, team/service-delivery
