### ISSUE TITLE
User shall be informed in case apod is not deployed on Stage or Run environment

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#3071] opened 2018-04-12 14:26 UTC
Scenario:

1) I commited and pushed a repo update
2) corresponding pipeline build was executed and Rollout to Stage and Rollout to Run become Green
3) when I clicked on the pod / microservice link right to "Rollout to Stage/Run" it was not accessible
4) OSO Jenkins showed that the build was successful, but pod deployment for cancelled

Expected scenario: User shall be notified and the link not present, in case a pod is not deployed.

![pipelines](https://user-images.githubusercontent.com/26871874/38683534-0027fb50-3e6e-11e8-9a40-bf95ed33d8b2.png)
![pod](https://user-images.githubusercontent.com/26871874/38683538-04d14ee0-3e6e-11e8-85b9-558432ffe76b.png)
![oso jenkins](https://user-images.githubusercontent.com/26871874/38683550-0a590542-3e6e-11e8-9316-f5c4c5256792.png)
![oso build view](https://user-images.githubusercontent.com/26871874/38683558-0d418c02-3e6e-11e8-9bbd-318ee996ee8d.png)

**Comment by joshuawilson** [comment] 2018-04-12 20:31
duplicate of #2629

**Closed by joshuawilson** 2018-04-12 20:31 UTC
Labels: type/bug
