### ISSUE TITLE
'Update Tentant' button does not give any feedback on whether something is happening

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1575] opened 2017-12-08 16:59 UTC
When clicking on the 'Update Tenant' button there is no indication whether something is happening. There is no message telling me whether the update was successful or not. I am not even sure whether any action was executed.

**Comment by joshuawilson** [comment] 2017-12-24 02:22
Closing, duplicate of https://github.com/openshiftio/openshift.io/issues/1566

**Closed by joshuawilson** 2017-12-24 02:22 UTC
