### ISSUE TITLE
CHE Issue. Can't start it: Workspace agent is no longer responding.

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1367] opened 2017-11-15 15:18 UTC
Once I create the CHE 2.0.55 workspace I see the following message.

![screenshot 2017-11-15 13 15 16](https://user-images.githubusercontent.com/30131/32843657-69d430ea-ca07-11e7-971a-be30be2b34ea.png)

When I click "Restart". The message changes to "Workspace is not running".

**Comment by ldimaggi** [comment] 2017-11-15 15:31
Duplicate of:  https://github.com/openshiftio/openshift.io/issues/1304

**Comment by ldimaggi** [comment] 2017-11-15 15:31
Did you only just start seeing this today?

**Comment by rafabene** [comment] 2017-11-15 16:06
@ldimaggi Last week I didn't run OSIO as I was in a conference.

**Closed** 2017-11-15 16:06 UTC
