### ISSUE TITLE
Failed to login to Jenkins

### ISSUE THREAD

**Issue by ashmitha7** [openshiftio/openshift.io#3034] opened 2018-04-12 06:37 UTC
![screenshot from 2018-04-12 11-49-55](https://user-images.githubusercontent.com/28265276/38660183-fcdb1406-3e49-11e8-93da-7349edc7e02d.png)

My build was released and 'roll out to stage' took 10 sec after this in the 'approve' state, I clicked on 'Input required' and the 'promote' option would not work. Eventually, the screenshot is the error I received when trying this twice.

**Comment by ldimaggi** [comment] 2018-04-12 18:00
Is this problem reproducible now?

**Comment by rohanKanojia** [comment] 2018-04-24 13:50
Possible duplicate of #3026

**Comment by joshuawilson** [comment] 2018-04-25 02:05
closing duplicate

**Closed by joshuawilson** 2018-04-25 02:05 UTC
Labels: SEV2-high, area/auth, area/jenkins, area/pipelines, priority/P0, team/build-cd, type/bug
