### ISSUE TITLE
Problems with Iteration Hierarchy

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#4076] opened 2018-07-25 12:14 UTC
Iteration Hierarchy more than level 4 is not supported.

Iteration at 5th level appears at the 2nd level.

Refer:
https://youtu.be/lt9C3IDfc-Q

**Comment by nimishamukherjee** [comment] 2018-07-26 16:23
@DhritiShikhar refer to https://github.com/openshiftio/openshift.io/issues/2046
This is the intended behaviour.

**Comment by joshuawilson** [comment] 2018-10-31 16:24
closing since it works as designed

**Closed by joshuawilson** 2018-10-31 16:24 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
