### ISSUE TITLE
two vertical scrollbars when stack report modal is opened

### ISSUE THREAD

**Issue by SMahil** [openshiftio/openshift.io#2272] opened 2018-02-15 10:48 UTC
Two scrollbars are coming when stack report modal is opened. The content behind the modal should not be scrollable when modal is opened.
<img width="1440" alt="screen shot 2018-02-15 at 4 15 54 pm" src="https://user-images.githubusercontent.com/10396359/36252868-05f0b424-126c-11e8-88ab-9187926e7361.png">

**Comment by jyasveer** [comment] 2018-02-15 17:48
@SMahil i see only one scrollbar behind the modal. Could you please help me understand more ?

**Comment by SMahil** [comment] 2018-02-16 03:25
@jyasveer those are two scrollbars overlapping each other. try scrolling down the page when content is lengthy.
I have attached the video link:
https://drive.google.com/open?id=1HAkRUEDwKRWDiC9kns7KAyP9Lbmjno42

**Comment by GeorgeActon** [comment] 2018-02-20 02:34
@sivaavkd this is a sev3 but looks very bad. Needs to be fixed

**Comment by jyasveer** [comment] 2018-02-21 14:22
@SMahil Thanks for the clarification. This will be fixed

**Comment by jyasveer** [comment] 2018-03-27 08:39
I am unable to reproduce this. So closing this. Will raise a issue if I see this again.

**Closed by jyasveer** 2018-03-27 08:39 UTC
Labels: SEV3-medium, area/UI, area/analytics, team/analytics, team/analytics/integration, type/bug
