### ISSUE TITLE
Can't remove jenkins project via Online console

### ISSUE THREAD

**Issue by danieloh30** [openshiftio/openshift.io#252] opened 2017-06-18 03:11 UTC
When a space is deleted at OSIO, a relevant repository in github and all relevant projects like jenkins, pipeline at OpenShift Online should be removed as well. But repos and some projects don't. So I try deleting a project like doh-jenkins via OpenShift Online web console, I got a error like as below:

Project 'doh-jenkins'' could not be deleted.User "doh@redhat.com" cannot delete projects in project "doh-jenkins"

Is this a known issue or a bug?

Also I keep having a problem to create a new quick project related to jenkins as below:

Error! Something went wrong while attempting to perform this operation ...
ExecuteForgeCommandError
The forge-quick-start :: execute :: 2 command failed or only partially succeeded

name = ForgeApiServerError
origin = Fabric8ForgeService
message = An unexpected server side forge api error occurred
inner = 
   httpError = 
      status = 500
      statusText = Internal Server Error
      url = https://forge.api.openshift.io/forge/commands/fabric8-new-project/execute
      body = 
         results =  [             
             { 
               status = SUCCESS
             } ,            
             { 
               message = Added Jenkinsfile to project
               status = SUCCESS
             } ,            
             { 
               message = Created git repository: https://github.com/danieloh30/daniel-sapce-vertx
               status = SUCCESS
             } ,            
             { 
               message = Failed to create Jenkins Organisation job:: java.lang.IllegalStateException: Failed to create the GitHub Org Job at https://jenkins-doh-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=danieloh30. javax.ws.rs.WebApplicationException: Failed to process https://jenkins-doh-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=danieloh30 and got status: 503 Service Unavailable
               status = FAILED
             } ,            
             { 
               message = Already created BuildConfig doh-jenkins/daniel-sapce-vertx
               status = SUCCESS
             }  ]

**Comment by qodfathr** [comment] 2017-06-18 14:33
Some of that requires fixing. But we absolutely do not want to automatically delete github repos. Counter example is that I make a space, import an existing repo, later decide I don't want the space (or I want to switch to another space template). Deleting that repo would be a Very Bad Thing. another example is that I can import a repo into multiple spaces - deleting one of those spaces should not effect the others. 

Fair to say that there are a lot of complex use cases here, and we need to analyze all of them before determining behavior. For now, we are super conservative and don't delete anything outside of OSIO.

**Comment by danieloh30** [comment] 2017-06-18 14:38
@qodfathr, thanks for the response and I also agree the conservative way at this moment. Like you said, is that working to fix a bug which I can't remove some project on OpenShift Online? If so, is there any workaround to clean up or just need to wait for the release?

**Comment by qodfathr** [comment] 2018-01-12 17:55
Closing, as the inability to remove the various tenant projects created in OSO is behavior by design.

**Closed by qodfathr** 2018-01-12 17:55 UTC
Labels: SEV2-high, area/spaces, team/platform, type/bug
