### ISSUE TITLE
After a tenant reset, UI would get stuck

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3821] opened 2018-06-19 08:12 UTC
after resetting my tenant : 

![image](https://user-images.githubusercontent.com/98980/41584886-c473e70c-73a8-11e8-8af2-0e4ce124ccbe.png)

I go back to my Dashboard home and I am getting a spinner with a `Please wait while we load your recent spaces` 

![image](https://user-images.githubusercontent.com/98980/41584921-e173cb38-73a8-11e8-9f5d-13b5acc8d9f0.png)

This is the XHR requests I am getting while its waiting : 

![image](https://user-images.githubusercontent.com/98980/41585035-26dce8f8-73a9-11e8-9846-f0f8c0ad6dd8.png)

**Comment by chmouel** [comment] 2018-06-19 10:32
it seems consistent, as 2h later it still loops indefinitely with the same "please wait" message

**Comment by bmicklea** [comment] 2018-06-19 14:55
Strange, I can't reproduce it... @ldimaggi would you mind trying?

**Comment by joshuawilson** [comment] 2018-06-19 15:05
by consistent, we are asking if you can reproduce this?

**Comment by chmouel** [comment] 2018-06-19 15:14
Yes I can reproduce it, (and I have done this a few times before logging into this bug), went again to https://openshift.io/cboudjna/_cleanup got another message that says my tenant has been cleaned up : 

![image](https://user-images.githubusercontent.com/98980/41606489-1384e4d2-73e4-11e8-8c4e-7640d2d65c9e.png)

and still get this "Please wait while we load your recent spaces" showing instead of humm creating a new space or other,

checked my openshift account via command line too and it's empty,

**Comment by jiekang** [comment] 2018-06-20 15:23
I think this is a duplicate of https://github.com/openshiftio/openshift.io/issues/3705

@dlabrecq knows more.

**Comment by dlabrecq** [comment] 2018-06-20 17:40
Yes, this is a duplicate of #3705. Instead of a spinner, you should expect to see an empty state.

**Closed** 2018-06-21 02:09 UTC
Labels: SEV2-high, area/user/tenant, team/platform, type/bug
