### ISSUE TITLE
Work items in the "closed" should be easily differentiable from items in any other state in planner

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3962] opened 2018-07-12 06:23 UTC
There is no point to having a 'resolved' status if both cannot be easily differentiated from each other in the overview by any means other than the "type" column. A basic workaround to it is to make them appear greyed out or put a "closed" icon or notification next to them.

**Comment by rootAvish** [comment] 2018-07-12 06:46
Relates to https://github.com/openshiftio/openshift.io/issues/3943

**Comment by joshuawilson** [comment] 2018-11-01 02:01
Duplicate of #4480

**Closed by joshuawilson** 2018-11-01 02:01 UTC
Labels: area/UX, area/planner, team/planner, type/feature-request
