### ISSUE TITLE
Pods take long time to start

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#786] opened 2017-09-08 16:30 UTC
CHE and Jenkins Pod take more than five minutes to start due to the following error:

(combined from similar events): Failed to attach volume "pvc-fead7e2a-94b1-11e7-b67b-02d7377a4b17" on node "ip-172-31-77-149.us-east-2.compute.internal" with: Error attaching EBS volume "vol-0b7b688836391fab9" to instance "i-07064ee1905629e90": VolumeInUse: vol-0b7b688836391fab9 is already attached to an instance status code: 400, request id: a0adac08-ab01-4581-a52b-3d998bc32a21. The volume is currently attached to instance "i-0cf895d46d9eb1869"

**Comment by kbsingh** [comment] 2017-09-08 17:40
this looks like the storage backing the che service, did you have a problem with jenkins as well ?

**Comment by rafabene** [comment] 2017-09-08 21:46
Yes. The same happens to Jenkins

**Comment by ldimaggi** [comment] 2017-09-10 03:16
This looks like the same (EBS) problem as:
https://github.com/openshiftio/openshift.io/issues/666

**Comment by bmicklea** [comment] 2017-09-11 00:02
Closing as dupe of #666

**Closed by bmicklea** 2017-09-11 00:02 UTC
Labels: area/status, kind/bug, team/service-delivery
