### ISSUE TITLE
The URL to jenkins job posted on Github in response to a PR is invalid

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#2504] opened 2018-03-08 04:57 UTC
### Steps
1. create quickstart project
2. create a pull-request to the project on GitHub
3. wait for the CI to trigger
4. Look at the `Details` link see: ![ci-run-link](https://user-images.githubusercontent.com/3005132/37133707-b43ebc68-22e0-11e8-8fb0-0ddd8a722397.png)

### Expected
Must point to actual jenkins job console

### Actual 
Points to `http://unconfigured-jenkins-location/job/{user}/job/{repo}/job/{branch}/1/display/redirect`

**Comment by sbose78** [comment] 2018-03-09 03:08
This looks pretty severe to me :(

**Comment by sthaha** [comment] 2018-03-09 07:22
@sbose78 do you know if this is a regression?

**Comment by sbose78** [comment] 2018-03-11 10:14
Yeah looks like since this used to work pretty well before.

**Comment by bartoszmajsak** [comment] 2018-03-11 13:11
It's not a regression, it's been like that for a long time. Duplicate of https://github.com/openshiftio/openshift.io/issues/1259

**Closed** 2018-03-11 13:11 UTC
Labels: SEV2-high, area/analytics/core-api, area/jenkins, team/build-cd, type/bug
