### ISSUE TITLE
Sometimes the UI manages to include multiple 'page' components into one page

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1975] opened 2018-01-23 13:03 UTC
![screencapture-openshift-io-aslak-test670-1516712110688](https://user-images.githubusercontent.com/132158/35277142-f8f22d6c-0045-11e8-8725-1d85a3dfc75a.png)

**Comment by catrobson** [comment] 2018-03-14 14:54
This issue is no longer occurring in OSIO today.  

It is possible for this issue to come back up based on how developers write code into the UI.  We still need to address this so that the issue will not reoccur in the future.

**Comment by joshuawilson** [comment] 2018-03-14 15:34
@dgutride once we get the Observables fixes so that others can't break the UI then we can close this.

**Comment by corinnekrych** [comment] 2018-03-30 07:25
closing as duplicate of https://github.com/openshiftio/openshift.io/issues/2339

**Closed by corinnekrych** 2018-03-30 07:25 UTC
Labels: SEV2-high, area/UI, area/architecture, issue/intermittent, team/platform, train/heather, type/bug
