### ISSUE TITLE
In promoting project to run, timing delays may cause user confusion as links are displayed before the corresponding assets are ready

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#884] opened 2017-09-19 03:32 UTC
_From @ldimaggi on June 30, 2017 15:39_

I just saw the following situation:
* User creates new project, pipeline reports success
* But - if the user attempts to access the staged app before promoting it to run - this error is seen:

![screenshot from 2017-06-30 11-01-52](https://user-images.githubusercontent.com/642621/27742862-32b00c88-5d88-11e7-8d18-a4ea2af1c296.png)

The problem is a matter of timing. The app requires (how long?) to be deployed to either stage or run.

We should:
1) Not display any link to a deployed app until the app is reachable
2) Display some form of counter or "working..." icon while app is being deployed but is not reachable.

_Copied from original issue: fabric8-ui/fabric8-ui#1619_

**Comment by qodfathr** [comment] 2018-01-19 19:43
Effectively a dupe of #508.

**Closed by qodfathr** 2018-01-19 19:43 UTC
Labels: SEV3-medium, area/app-wizard, team/platform, type/bug
