### ISSUE TITLE
Jenkins pod doesn't come up

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4096] opened 2018-07-31 12:20 UTC
Jenkins pod continuously fails the readiness check and doesn't come up(unidle).
Adding deployment logs here
[jenkins-2.log](https://github.com/openshiftio/openshift.io/files/2245194/jenkins-2.log)

**Comment by sthaha** [comment] 2018-07-31 12:45
Closing this as duplicate of #3956

**Closed by sthaha** 2018-07-31 12:45 UTC
Labels: team/build-cd, type/bug
