### ISSUE TITLE
Challenges with parallel OSIO builds 

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2057] opened 2018-01-25 13:58 UTC
I ran thru these steps with two builds in parallel triggered on two OSIO quick start applications:

1) Create a space A , trigger a build after selecting a quick-start  'Q1' 
2) While build for 'Q1' is under progress, create a space 'B', trigger a build after selecting a quick-start 'Q2'
3) Build for 'Q1' fails with an error [1] , build for 'Q2' succeeds
4) Click on 'Promote to next environment' (UI button) for Q2 has NO impact, nothing would happen
5) Link for Q2 at staging environment would result in error, not deployed [2]
6) Erase my tenant
7) Create space 'C', trigger a build after selecting a quick-start 'Q3'
8) Build  start for Q3, Can see application at staging,  and Pipelines screen is all messed up [3]
9) Click on 'Promote to next environment' (UI button) for Q2 has NO impact, nothing would happen. Instead Promoting thru Jenkins console [4] would promote the changes to the next environment.

[1]  https://drive.google.com/open?id=11i_BcL6qpV2GMeHQ00RcbUIIQF8D0GF2

[2]  https://drive.google.com/open?id=1Y6-Fw8SqajFK6bCA7ryICAU6zA24VYwa

[3]  https://drive.google.com/open?id=1gStsGfRJEa60On2NarrPSy0ekWbpkJVl

[4] https://drive.google.com/open?id=1aP-w3Nzml6uP3_TeUmuut49lGhkw7ZE0

## Impacts
- [ ] #2155 CI Experience placeholder

**Comment by chmouel** [comment] 2018-01-25 14:15
This is not something we have at this time,

**Comment by ldimaggi** [comment] 2018-01-25 14:54
I think that this is the reason that you did not see anything happen when you pressed the "Promote" button:  https://github.com/openshiftio/openshift.io/issues/2034

**Comment by qodfathr** [comment] 2018-01-25 21:58
Parallel builds are not permitted in free usage of OpenShift.io. Regardless, there is a bug here.

**Comment by kbsingh** [comment] 2018-01-27 03:02
can we do something simple like set workers to be max limited to 1 ? that way while the triggers can come through, they just get queued.

the way our resourcing model works in the free setup, only 1 build should run at a time.

**Comment by qodfathr** [comment] 2018-01-29 00:57
@kbsingh I think that's how it is working. I think @ldimaggi is right, the bug is #2034.

I'd like to propose closing this as:

1. a feature request that conflicts with the intended design (i.e. wanting parallel builds in free OSIO tier)
and
2. a reported bug. which is a dupe of #2034.

@krishnapaparaju , if you are okay with that, please close this issue. Thanks!

**Comment by ldimaggi** [comment] 2018-01-29 03:07
Bug #2034 refers to the 'promote' button not working - for a single build. It is not related to 2 builds colliding.

**Comment by qodfathr** [comment] 2018-02-01 17:12
Okay, here's my proposal.

The failure of the first build is the context of **this** issue. (We need to keep issues to single bugs.)
The failure of the promote button is #2034.
The messed up pipelines screen is related to / a dupe of #1975 
The failure of the 2nd promote button is probably also #2034 

@ldimaggi thoughts?

**Comment by sthaha** [comment] 2018-07-31 13:15
Closing this. Please open an EPIC in Planner instead

**Closed by sthaha** 2018-07-31 13:15 UTC
Labels: SEV4-low, team/build-cd, type/bug
