### ISSUE TITLE
Might impact on-boarding process: Forget password is not working

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1021] opened 2017-09-25 19:13 UTC
When I received an email with the reset password link, the URL gave me: 

> {"errors":[{"code":"unauthorized","detail":"user 'rafabene' is not approved","id":"4f0CRF5l","status":"401","title":"Unauthorized"}]}​

The workaround was to reset the password through developer.redhat.com

**Comment by alexeykazakov** [comment] 2017-09-25 19:23
We do not reset passwords in OSIO at all. What did you do? :)
Note, if you reset password via RHD and then try to login to OSIO without being approved you will get the same error as above. Could you give us more details of what you actually did.

**Comment by rafabene** [comment] 2017-09-25 20:08
I've registered a new account and the link gave me a similar message:

> {"errors":[{"code":"unauthorized","detail":"user 'benevides-osio' is not approved","id":"0KLD595y","status":"401","title":"Unauthorized"}]}

**Comment by alexeykazakov** [comment] 2017-09-25 20:48
It's not a bug if you trying to login using unapproved account. We should show a better message though. See https://github.com/openshiftio/openshift.io/issues/1023

**Comment by alexeykazakov** [comment] 2017-09-26 20:11
Closing. Let's track it in https://github.com/openshiftio/openshift.io/issues/1023

**Closed by alexeykazakov** 2017-09-26 20:11 UTC
Labels: area/auth, team/auth
