### ISSUE TITLE
Recommended License modal overlay remain open even after closing the modal.

### ISSUE THREAD

**Issue by vikram-raj** [openshiftio/openshift.io#3310] opened 2018-04-25 15:39 UTC
![screencast from 04-25-2018 09_05_34 pm](https://user-images.githubusercontent.com/2561818/39256577-de88234e-48cc-11e8-8c23-7ce46ff52d9d.gif)

**Comment by aptmac** [comment] 2018-04-25 15:40
Duplicate of https://github.com/openshiftio/openshift.io/issues/2328

**Closed by aptmac** 2018-04-25 15:40 UTC
