### ISSUE TITLE
Feature opt-ins are not in sync on prod and prod-preview

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3756] opened 2018-06-11 12:59 UTC
Since prod-preview is the base for testing if something can be pushed to production, I assume the feature opt-ins should be the same on both systems.

**Comment by joshuawilson** [comment] 2018-06-11 13:05
Can you please list or specify what you are seeing.

**Comment by ljelinkova** [comment] 2018-06-12 06:46
This is screenshot from production Feature opt-ins page
![production](https://user-images.githubusercontent.com/2078072/41274130-a1aec2d2-6e1c-11e8-9cd7-17f9a011f439.png)

And this is screenshot from prod-preview Feature opt-ins page
![preview](https://user-images.githubusercontent.com/2078072/41274143-b0231728-6e1c-11e8-9d45-74fbe4bfcd51.png)

For example Deployments is in Beta on production but only on Experimental in prod preview. I believe these should be the same so that the new code is tested on prod preview with the same configuration that will be used on production.

**Comment by joshuawilson** [comment] 2018-06-12 07:01
cc @corinnekrych

**Comment by ppitonak** [comment] 2018-06-12 07:04
@joshuawilson to be more specific, we need `beta` and `released` feature flags to be set the same in prod-preview and prod

**Comment by ppitonak** [comment] 2018-06-12 08:41
@corinnekrych could you write a test that would periodically verify that these two are in sync?

**Comment by corinnekrych** [comment] 2018-06-13 07:14
At the moment we haven't worked for sync between the two. This is 2 separate DBs / server.
Most of the time the 2 are not in sync. 
No need for a test but if/when we need sync we need to add a US and work on it.
cc @xcoulon

**Comment by ljelinkova** [comment] 2018-06-13 07:29
@corinnekrych Why cannot both (prod-preview, production) use the same DB/server? Why is it separated? Is there any use case where we want different configuration between those two?

**Comment by xcoulon** [comment] 2018-06-13 10:21
@ljelinkova prod and pre-prod are on different clusters, so we can't share the same DB.

**Comment by ljelinkova** [comment] 2018-06-13 11:55
Maybe I should explain in more detail why this is so important for us, QA and our E2E tests. 

Our understanding of the process (based on this readme https://github.com/openshiftio/saasherder) was that when code is pushed into repository, it is installed automatically to prod-preview. Several different commits from different developers can be installed there and at some point, somebody, let's say Joshua, says prod-preview looks ok, takes the last commit's hash and updates e.g. fabric8-ui.yaml with that hash. This causes that all changes up to this commit (including) are promoted to production.

So my understanding of prod-preview is not of some playground but that it is proof that the code works and can be pushed to production. We would like to run our tests on prod-preview so that we can detect bugs before they get to the production (and of course to ensure that there are no UI changes that will break them). To ensure this, we need to have those feature levels synchronized.

If I understand the process wrong, please explain it to me.

**Comment by joshuawilson** [comment] 2018-06-13 15:32
This makes sense to me. 
@corinnekrych @xcoulon do you think it is better to use the same db or to manually keep them in sync?

**Comment by sbose78** [comment] 2018-06-14 02:04
Thanks @ljelinkova  I see the requirement for tests it to have the same feature 'levels'.
@corinnekrych  @xcoulon  @joshuawilson , we should be manually keeping them in sync instead of a common db because user management is done separately for prod and prod-preview. ( ie, prod is unaware of users in prod-preview )

**Comment by ppitonak** [comment] 2018-06-14 06:35
In that case, can you create a test/script that will regularly verify that they are in sync?

**Comment by corinnekrych** [comment] 2018-06-14 14:17
This is certainly not a bug. Let's tag it user-story for future implementation.
we brainstorm with @xcoulon @aslakknutsen around the question: How do we make sure prod-preview / prod are in sync for feature flag?

We came up with 3 options:
* Diff tool between pro-preview / prod to help the manual sync
this is still manual process and prod
* Sync tools, potentially automatic with k8s watcher
how to handle sync conflicts?
  * Preview can contain Toggles not in prod yet
  * Preview might want to override a group on prod, but should at least be at prod level?
  * Prod can contain Toggles removed from preview
* 2 services, one unleash serveur / one DB 
a solution would be to have 1 fabric8-toggles service per env, but use different strategies (i.e, different names) for the environments. Eg: enableOnProdByLevels vs enableOnPreprodByLevels. So, it may be easier to manage: need to declare the feature once, and with all on the same UI, it could be easier to compare the levels.
Each env needs its own `toggles-service` because the latter also connects to the `auth` service which depends on the environment.
Impact on all other service accessing => need to open unleash server API (behind traefik atm)

To be decided which path is preferred.

**Comment by ppitonak** [comment] 2018-06-14 14:35
> Preview can contain Toggles not in prod yet
> Prod can contain Toggles removed from preview

From testing POV, if a toggle is in preview in beta/released, it has to be in prod as well (in the same level), we don't care much about toggles in Internal/Experimental.

From overall maintenance POV, in my opinion it's much easier to keep them in sync all the time. My proposal for the development process would be something like this:
1. introduce a new toggle in both prod and preview (in internal/experimental level)
2. introduce new code using new toggle to preview
3. if no fatal errors are discovered, introduce new code to prod
4. repeat 2 & 3 as long as necessary
5. when ready to promote a feature to beta, make sure that correct version is in prod and promote to beta on both clusters
6. repeat 2 & 3 as long as necessary
7. when ready to release a feature, make sure that correct version is in prod and update feature toggles on both clusters
8. when ready, remove old code
9. when old code is no longer in prod, remove a feature toggle on both prod and preview

**Comment by ljelinkova** [comment] 2018-06-19 08:01
@corinnekrych @xcoulon Before implementing proper solution, could you please manually change the following feature levels on prod-preview to Beta so that we can run our tests there? Thanks. 

- Deployments
- MyWorkItemsCard
- Planner

**Comment by xcoulon** [comment] 2018-06-19 13:23
@ljelinkova I just updated the 3 features you mentioned above to the requested `beta` level. Please let me know if it's ok for you or if you have any issue.

**Comment by ljelinkova** [comment] 2018-06-19 13:54
It works, thanks :-)

**Comment by ppitonak** [comment] 2019-01-11 13:21
Closing this issue because it's outdated.

**Closed by ppitonak** 2019-01-11 13:21 UTC
Labels: area/feature flags, team/platform, type/user-story
