### ISSUE TITLE
Could not start workspace. Dev-machine not available. 

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4415] opened 2018-10-12 09:56 UTC
##### Issue Overview
When running E2E tests we found the following error when starting che

![04-01-aftereach](https://user-images.githubusercontent.com/2078072/46862602-883af380-ce15-11e8-8acb-f31c7c7d58e6.png)

This was logged in che-server (thanks @rhopp) 
```
Failed to start Kubernetes runtime of workspace workspaceo955ha57hqojm0g3. Cause: Server 'wsagent/http' in machine 'dev-machine' not available.
```

**Comment by rhopp** [comment] 2018-10-12 10:06
This is link to logs in kibana from the timeframe from start of that workspace to it's failure:
https://logs.dsaas.openshift.com/goto/0ee0f03cb4b21148a72e48ecfdb87720
(I've filtered some messages, as they were clogging the output)

**Comment by rhopp** [comment] 2018-10-12 12:17
It almost seem to me, that we have some networking problem and this could be one aspect of it. 
Today I'm randomly encountering (fairly often) `504 - Gateway Time-out` on various places, when working with che.
For example, right now, I got 504 when trying to stop workspace using dashboard:
![image](https://user-images.githubusercontent.com/1215011/46868712-8549fe00-ce29-11e8-97d7-fb32243defef.png)
The workspace was stopped, but dashboard reported error, because of the timeout.

**Comment by ljelinkova** [comment] 2018-10-12 12:52
I've found one job that failed to load Jenkins log due to Gateway timeout 
Screenshot: http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/848/05-03-jenkins-log-failed.png

Jenkins log contains quite o lot of errors (not sure if related)
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/848/oc-logs-output.txt

**Comment by rhopp** [comment] 2018-10-12 12:53
For analysis of the original issue (dev-machine not available).
I've just attempted to start workspace and it failed with exactly same message as in this issue description.
This is browser console output:
<details>

```
/_app/keycloak/RhCheKeycloak.js:391 originalKeycloakScript =  https://che.openshift.io/_app/keycloak/OIDCKeycloak.js
/_app/keycloak/RhCheKeycloak.js:392 OSIO provisioning page =  https://che.openshift.io/_app/keycloak/provision.html
RhCheKeycloak.js:402 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ RhCheKeycloak.js:402
(unknown) [KEYCLOAK] Estimated time difference between browser and server is 0 seconds
/_app/IDE.css:1 Failed to load resource: the server responded with a status of 404 ()
/_app/IDE.css:1 Failed to load resource: the server responded with a status of 404 ()
VM1292:1 GET https://che.openshift.io/api/workspace/workspace9k6sxuexz0gbqpi4 504 (Gateway Time-out)
(anonymous) @ VM1292:1
AG @ _app-0.js:933
BG @ _app-0.js:934
q5j @ _app-0.js:16065
p5j @ _app-0.js:16064
F2k @ _app-0.js:18005
z2k @ _app-0.js:18001
B2k @ _app-0.js:18003
(anonymous) @ _app-0.js:5201
Promise.then (async)
N4e @ _app-0.js:5201
u2k @ _app-0.js:17999
x2k @ _app-0.js:18001
B5j @ _app-0.js:16070
z4e @ _app-0.js:5190
(anonymous) @ _app-0.js:5193
x4e @ _app-0.js:5188
H2k @ _app-0.js:18006
z2k @ _app-0.js:18001
B2k @ _app-0.js:18003
(anonymous) @ _app-0.js:5201
Promise.then (async)
N4e @ _app-0.js:5201
u2k @ _app-0.js:17999
y2k @ _app-0.js:18001
K_k @ _app-0.js:17894
_9i @ _app-0.js:13994
laj @ _app-0.js:14004
_Yk @ _app-0.js:17781
c7d @ _app-0.js:128
Jg @ _app-0.js:168
ZYk @ _app-0.js:17780
OZk.onopen @ _app-0.js:17818
_app-0.js:5206 Uncaught (in promise) Error: 504 Gateway Time-out https://che.openshift.io
    at S4e (_app-0.js:5206)
    at A4e (_app-0.js:5190)
    at C5j.D5j [as er] (_app-0.js:16071)
    at kwi (_app-0.js:12501)
    at owi (_app-0.js:12505)
    at C5j.vwi [as Qo] (_app-0.js:12511)
    at qG (_app-0.js:928)
    at IG.JG [as Oo] (_app-0.js:942)
    at XMLHttpRequest.eval (_app-0.js:3268)
    at Qu (_app-0.js:518)
    at Tu (_app-0.js:521)
    at XMLHttpRequest.eval (_app-0.js:520)
S4e @ _app-0.js:5206
A4e @ _app-0.js:5190
D5j @ _app-0.js:16071
kwi @ _app-0.js:12501
owi @ _app-0.js:12505
vwi @ _app-0.js:12511
qG @ _app-0.js:928
JG @ _app-0.js:942
(anonymous) @ _app-0.js:3268
Qu @ _app-0.js:518
Tu @ _app-0.js:521
(anonymous) @ _app-0.js:520
Promise.then (async)
K4e @ _app-0.js:5198
_9i @ _app-0.js:13994
laj @ _app-0.js:14004
_Yk @ _app-0.js:17781
c7d @ _app-0.js:128
Jg @ _app-0.js:168
ZYk @ _app-0.js:17780
OZk.onopen @ _app-0.js:17818
VM1292:1 GET https://che.openshift.io/api/workspace/workspace9k6sxuexz0gbqpi4 504 (Gateway Time-out)
(anonymous) @ VM1292:1
AG @ _app-0.js:933
BG @ _app-0.js:934
q5j @ _app-0.js:16065
p5j @ _app-0.js:16064
F2k @ _app-0.js:18005
z2k @ _app-0.js:18001
B2k @ _app-0.js:18003
(anonymous) @ _app-0.js:5201
Promise.then (async)
N4e @ _app-0.js:5201
u2k @ _app-0.js:17999
x2k @ _app-0.js:18001
B5j @ _app-0.js:16070
z4e @ _app-0.js:5190
(anonymous) @ _app-0.js:5193
x4e @ _app-0.js:5188
H2k @ _app-0.js:18006
z2k @ _app-0.js:18001
B2k @ _app-0.js:18003
(anonymous) @ _app-0.js:5201
Promise.then (async)
N4e @ _app-0.js:5201
u2k @ _app-0.js:17999
y2k @ _app-0.js:18001
K_k @ _app-0.js:17894
v1k @ _app-0.js:17954
z1k @ _app-0.js:17958
wse @ _app-0.js:4049
Vre @ _app-0.js:4030
Nre @ _app-0.js:4023
lre @ _app-0.js:4000
H8i @ _app-0.js:13936
mre @ _app-0.js:4001
FZk @ _app-0.js:17809
YYk @ _app-0.js:17780
OZk.onmessage @ _app-0.js:17818
_app-0.js:5206 Uncaught (in promise) Error: 504 Gateway Time-out https://che.openshift.io
    at S4e (_app-0.js:5206)
    at A4e (_app-0.js:5190)
    at C5j.D5j [as er] (_app-0.js:16071)
    at kwi (_app-0.js:12501)
    at owi (_app-0.js:12505)
    at C5j.vwi [as Qo] (_app-0.js:12511)
    at qG (_app-0.js:928)
    at IG.JG [as Oo] (_app-0.js:942)
    at XMLHttpRequest.eval (_app-0.js:3268)
    at Qu (_app-0.js:518)
    at Tu (_app-0.js:521)
    at XMLHttpRequest.eval (_app-0.js:520)
S4e @ _app-0.js:5206
A4e @ _app-0.js:5190
D5j @ _app-0.js:16071
kwi @ _app-0.js:12501
owi @ _app-0.js:12505
vwi @ _app-0.js:12511
qG @ _app-0.js:928
JG @ _app-0.js:942
(anonymous) @ _app-0.js:3268
Qu @ _app-0.js:518
Tu @ _app-0.js:521
(anonymous) @ _app-0.js:520
Promise.then (async)
K4e @ _app-0.js:5198
v1k @ _app-0.js:17954
z1k @ _app-0.js:17958
wse @ _app-0.js:4049
Vre @ _app-0.js:4030
Nre @ _app-0.js:4023
lre @ _app-0.js:4000
H8i @ _app-0.js:13936
mre @ _app-0.js:4001
FZk @ _app-0.js:17809
YYk @ _app-0.js:17780
OZk.onmessage @ _app-0.js:17818
_app-0.js:17772 WebSocket is already in CLOSING or CLOSED state.
OYk @ _app-0.js:17772
Ebk @ _app-0.js:16295
LGj @ _app-0.js:15116
RHj @ _app-0.js:15163
Zxg @ _app-0.js:7952
WF @ _app-0.js:912
D1k @ _app-0.js:17960
I1k @ _app-0.js:17964
(anonymous) @ _app-0.js:5198
Promise.then (async)
K4e @ _app-0.js:5198
C1k @ _app-0.js:17959
G1k @ _app-0.js:17963
wse @ _app-0.js:4049
Vre @ _app-0.js:4030
Nre @ _app-0.js:4023
lre @ _app-0.js:4000
H8i @ _app-0.js:13936
mre @ _app-0.js:4001
FZk @ _app-0.js:17809
YYk @ _app-0.js:17780
OZk.onmessage @ _app-0.js:17818
```

</details>

**Comment by garagatyi** [comment] 2018-10-12 13:20
Since there are 504s checks of the workspace agent can easily fail and then workspace would be treated as unhealthy. 
Since we also have 504s in other parts of the system such as 
```
[18:09:28.030] SEVERE https://openshift.io/api/codebases/8eeb84a4-6cb1-40ae-8018-7f34e5024c2e/create - Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
```
I would want to remove label area/che as Che wouldn't be able to work properly with a faulty networking.
@rhopp WDYT?

**Comment by garagatyi** [comment] 2018-10-12 15:04
I just started my workspace without any error

**Comment by garagatyi** [comment] 2018-10-14 16:52
@ljelinkova can you reproduce the issue now?

**Comment by rhopp** [comment] 2018-10-15 08:27
The 504's disappeared and the original error happened only twice through the weekend:
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/856/
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/866/

**Comment by garagatyi** [comment] 2018-10-15 08:49
@rhopp I don't know how to reproduce it. For me, workspaces start just fine.

**Comment by rhopp** [comment] 2018-10-15 12:17
@garagatyi I too fail to reproduce this issue (trying since morning). 
After further investigation of the existing failures, in both recent cases (linked in my previous comment) there were 503 responses to web socker connection in browser console:
```
[11:11:18.117] SEVERE _app-0.js 17817 WebSocket connection to 'wss://routeqp3elh4h-osio-ci-e2e-007-che.b542.starter-us-east-2a.openshiftapps.com/connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNleG82djIzbzI4ZHRqN2xldSJ9.eyJ3c2lkIjoid29ya3NwYWNleG82djIzbzI4ZHRqN2xldSIsInVpZCI6ImZhMDExZGUxLWI1OGQtNDlkNy04MGJiLWUwMTE4ODhlMDU2ZCIsImF1ZCI6IndvcmtzcGFjZXhvNnYyM28yOGR0ajdsZXUiLCJuYmYiOi0xLCJ1bmFtZSI6Im9zaW8tY2ktZTJlLTAwNyIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNTcwOTY0ODQ4LCJpYXQiOjE1Mzk0Mjg4NDgsImp0aSI6IjIyMTNiYmZjLWI1NDItNGYzNi04NzZjLTViYjFiZjk3NTI5YiJ9.GhEqwozjU23PrLxy2tkAPBlHSSJloDNzKRwScR4UpxXg_MuZ2hjS2ErzjUd2PO6xJ35bt2AoqYdlaKoVScA_NSzH3MK1gWZB1bt-Aap8nd_J6qNgmG3izG4Ksg-54ChzHLomGNkL8LiIAH-1bDWQ9nDlPot9nq_hQKhEGB07kpdTAmSIkA_00IoUGNJAWKMj27ur6KZCLcGK6M1CCsC6QQLD8qdqV0cFSuTshY8HvV9G28zs4oSiCvBegUEZtFfOxEutng7EhAFAdJVYTW8LEpWSRR4hzgYZdoozD_TEVD4N7Z8kAuPNzC4naz4S7byEib65pawjhFLJBC7USLNLSA' failed: Error during WebSocket handshake: Unexpected response code: 503
```
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2a-released/856/04-01-afterEach.log
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/866/04-01-afterEach.log

Do you have any idea what more info can we gather to help us resolve this/find out what's causing this? To me it seems like exec agent is not running. Does exec agent has any logs? Where can be accessed?

**Comment by garagatyi** [comment] 2018-10-15 12:54
@rhopp the error from the description says that the problem is the unavailability of wsagent, not terminal. But both could be unhealthy back then. When Che can't reach wsagent for some time it thinks that workspace is unhealthy. Especially at workspace start where we check whether everything started as expected by pinging wsagent by HTTP. Since routes worked improperly back then it is expected that workspaces would fail to start if a route can't proxy a request to a wsagent.

**Comment by ibuziuk** [comment] 2018-10-23 12:15
@ljelinkova @rhopp is this issue still reproducible ? Gateway timeouts is an infrastructure problem and according to the comments [1] not only che but also other OSIO components where affected by those networking issues.  

[1] https://github.com/openshiftio/openshift.io/issues/4415#issuecomment-429315118

**Comment by rhopp** [comment] 2018-10-23 13:02
Lately, E2E tests didn't fail with this message. I've discussed this with @ljelinkova and we think it's ok to close this issue.
She will reopen if she sees that again.

**Closed by rhopp** 2018-10-23 13:02 UTC
Labels: area/che, area/e2e-tests, priority/P1, team/service-delivery
