### ISSUE TITLE
Intermittent issue in Che - run operation fails with error: Unable to parse command line

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2856] opened 2018-04-03 12:34 UTC
Upstream issue - https://github.com/eclipse/che/issues/9321
Started seeing this over the weekend - no pattern seen yet - failing about 5-10% of the time.

Steps to recreate:
* Create a new quickstart
* Create a Che workspace for the quickstart
* In the quickstart - attempt to execute run - from the run pull-down button - this error is seen intermittently: Unable to parse command line - missing option -f

![screenshot from 2018-04-02 17-29-26](https://user-images.githubusercontent.com/642621/38249179-cb713d4c-3718-11e8-8134-359175e3d0e3.png)

The only successful workaround seems to be to create a new workspace.

**Comment by rhopp** [comment] 2018-04-03 15:17
I've never seen this. It seems, that the `${current.project.path}` macro resolves into empty string. Not sure how this could have happened. I wasn't able to find any issue upstream describing such behavior.

Here are logs from the time when this happens: https://logs.dsaas.openshift.com/goto/9158317fff15ec1795cbe229cc02ebf6
(@ldimaggi Could you please add the logs when you are creating issues?)

**Comment by rhopp** [comment] 2018-04-04 12:14
Issue opened in upstream Che: https://github.com/eclipse/che/issues/9321

**Comment by rhopp** [comment] 2018-04-12 07:59
@ibuziuk No idea. I've never seen this behavior (on 5 nor on 6)

**Comment by ibuziuk** [comment] 2018-04-12 08:02
I definitely saw in on Che 5, but looks like Che 6 is also affected according to the eclipse/che#9321

**Comment by rhopp** [comment] 2018-04-12 08:14
@ibuziuk I've discussed this issue with Igor Ohrimenko (che qe) and he just created that issue. I'm not sure he was able to reproduce it anywhere. This is what he wrote to me:
> I registered the issue https://github.com/eclipse/che/issues/9321 (I will supplement it with the results of the investigation)
and also I have discussed this problem with @vitalii_parfonov , he will check macross  functionality.

**Comment by ibuziuk** [comment] 2018-04-24 15:25
@rhopp @ldimaggi do we happen to have some integration tests for reproducing this problem on che 6 ?

The upstream issue says:

> In rare cases, on the OCP platform, we have a situation when after command start, output of the macros is not displayed.

I believe if it's not reproducible against che 6 label should be changed to SEV3 and P0 should be removed. WDYT ?

**Comment by ldimaggi** [comment] 2018-04-24 18:28
I have not seen this since we upgraded to Che6 - downgrading to SEV3 and will close if I do not see this issue again this week. Removing the P0 label too.

**Comment by mvulavak** [comment] 2018-08-01 06:56
@ldimaggi Can this issue be closed?

**Comment by rhopp** [comment] 2018-08-01 07:59
@mvulavak I think not. I reserved some time today to look at this issue and I think I found a reliable way how to reproduce this issue. I'll reopen the upstream one and comment the steps there.

**Comment by ibuziuk** [comment] 2018-11-22 12:43
upstream issues have been and I can not reproduce this problem anymore. Closing

**Closed by ibuziuk** 2018-11-22 12:43 UTC
Labels: SEV3-medium, area/che, issue/intermittent, priority/P4, team/che/osio, type/bug

**Comment by rhopp** [comment] 2018-11-22 13:44
Confirmed... Cannot reproduce that either.
