### ISSUE TITLE
'Select a pipeline' drop-down is empty even when pipelines exist

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#538] opened 2017-08-10 07:25 UTC
The 'Select a pipeline' drop-down menu on the Space dashboard is showing empty, but you can see that a Pipeline is showing in the Pipelines section of the dashboard. The drop-down seems to be ina broken state.

**Comment by rgarg1** [comment] 2017-08-10 07:25
![select a pipeline menu is empty](https://user-images.githubusercontent.com/28748448/29159173-1d858c54-7d9d-11e7-9d99-e7a70221410e.png)

**Comment by sara-02** [comment] 2017-08-10 07:27
+1 same for me. It is a bit deceiving.

**Comment by joshuawilson** [comment] 2017-08-14 01:35
Duplicate of https://github.com/openshiftio/openshift.io/issues/528, closing. Please provide updates there.

**Closed by joshuawilson** 2017-08-14 01:35 UTC
