### ISSUE TITLE
Booster configmaps should be applied automatically as part of deployment

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2564] opened 2018-03-14 08:00 UTC
Affected Boosters:
- [ ] Vertx ConfigMap
- [ ] Springboot ConfigMap
- [ ] WF Swarm ConfigMap

When trying to access a deployed configmap booster, it shows following error
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/17736013/37389808-b2e3dd44-278b-11e8-9ca6-20919e156c0d.png">

Further debugging shows no configmaps applied in the stage and run environment.

**Comment by slemeur** [comment] 2018-04-12 08:48
Duplicate of : https://github.com/openshiftio/openshift.io/issues/2988

Should be fixed by: https://github.com/fabric8-launcher/launcher-backend/pull/216

**Closed** 2018-07-05 11:19 UTC
Labels: SEV3-medium, area/app-wizard, team/analytics, team/analytics/wizard, type/bug
