### ISSUE TITLE
After env reset, attempt to create new application fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3658] opened 2018-05-25 17:33 UTC
Steps to recreate:
* Log in to https://openshift.io
* Reset user env
* Create a new space
* After the space is created. the user is placed on the 'Create an Application' page:
![screenshot from 2018-05-25 11-17-40](https://user-images.githubusercontent.com/642621/40552316-536500e0-600d-11e8-8a98-15e4594733c1.png)

* After entering a name for the new app, tt this point, the create, import, and continue buttons do not respond.

![myimage](https://user-images.githubusercontent.com/642621/40557636-c6663d32-601e-11e8-874a-9ca2aa5239c1.gif)

* If the user tries a 2nd time - the app can be created.

**Comment by ldimaggi** [comment] 2018-05-25 17:35
Related to #3657

**Comment by joshuawilson** [comment] 2018-05-25 23:10
duplicate of #3657
closing

**Closed by joshuawilson** 2018-05-25 23:10 UTC
Labels: SEV2-high, area/launcher, team/launcher, type/bug
