### ISSUE TITLE
Builds info appears even after deleting the space

### ISSUE THREAD

**Issue by Veethika** [openshiftio/openshift.io#2807] opened 2018-03-28 09:17 UTC
Even after deleting the spaces, few of the corresponding builds information is still visible.
Till resolved, the troubleshooting should provide the alternate method of clearing the data.
Steps: 
1) Log In
2) Go to 'View All Spaces' using top left dropdown menu
3) Delete all the spaces
4) Go to Account Home page
**Issue:** 1) Few of the builds from deleted spaces still appear in the Pipelines section. 
2)Click on the build, the same page gets reloaded with an error message

<img width="1680" alt="p2" src="https://user-images.githubusercontent.com/35127763/38019363-fb99d91c-3294-11e8-8032-a69999c5170a.png">

Proposed UX suggestion:
1) Provide a warning to convey the critical consequences when the user attempts at deleting any space with projects within
2) To clear the dashboard, provide an alternate solution in the documentation till the problem gets resolved:
Go to Profile>> Update Profile>>Reset Environment

<img width="1680" alt="screen shot 2018-03-28 at 2 23 56 pm" src="https://user-images.githubusercontent.com/35127763/38019684-e1d737da-3295-11e8-81b4-e617e657c295.png">

**Comment by mishaone** [comment] 2018-05-25 05:31
Documented as a known issue: https://github.com/fabric8io/fabric8-online-docs/pull/364

**Comment by piyush1594** [comment] 2018-06-20 04:07
@Veethika @mishaone Seems like a UX change and UI issue. Is there anything `build-cd` team needs to do with it. If that is the case, can you please drop the label? Thanks cc @sthaha

**Comment by piyush1594** [comment] 2018-06-21 05:59
Duplicate of #3802 closing this.

**Closed by piyush1594** 2018-06-21 05:59 UTC
Labels: SEV2-high, area/docs, area/jenkins, area/pipelines, team/build-cd, team/docs, type/bug
