### ISSUE TITLE
dropdown Alignment issue in the home page

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3621] opened 2018-05-23 09:06 UTC
![screenshot from 2018-05-23 14-33-57](https://user-images.githubusercontent.com/34271052/40414724-aba16b5e-5e96-11e8-9faa-1d4f96e4dd78.png)

**Comment by joshuawilson** [comment] 2018-05-23 13:53
What are you seeing? vs What do you expect?
Please add labels.

**Comment by aptmac** [comment] 2018-05-28 16:54
@Raunak1203 What is the bug you're seeing?

**Comment by Raunak1203** [comment] 2018-05-28 17:19
@aptmac if the space name is long, My workitem dropdown is not shown properly.
Please see the above screenshot(right -> we can see the dropdown select a space to work with)

**Comment by aptmac** [comment] 2018-05-28 20:59
Or if it's about the dropdown not displaying all of the spaces, it's because it's only retrieving the "recent" spaces. This is pretty confusing though (this also happens for the profile work items component).

[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/work-item-widget/work-item-widget.component.ts#L32

**Comment by Raunak1203** [comment] 2018-05-29 03:31
Ok @aptmac it can be fix with #1886 
Yes it's only retrieving recent spaces.

**Comment by aptmac** [comment] 2018-08-20 16:18
duplicate of https://github.com/openshiftio/openshift.io/issues/3621

**Closed by aptmac** 2018-08-20 16:18 UTC
Labels: SEV3-medium, priority/P4, team/platform, type/bug
