### ISSUE TITLE
New users unable to connect accounts

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#1316] opened 2017-11-09 18:09 UTC
- login to OpenShift.io
- On the "getting started" page, "login in" shows up on top right.
- The "Connect Accounts" button doesn't work"

In the console:

there is 400 for https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token
and 401 for https://auth.openshift.io/api/token?for=https://github.com

**Comment by alexeykazakov** [comment] 2017-11-09 18:24
Reproducible only for new users who never connected GitHub before.

Auth service returns 401 with WWW-Authenticate header if GitHub is not connected to the OSIO account.
That 401 wrongly broadcasts authenticationError in UI and UI logs out the user.

**Workaround**: Click on the login button on the getting started page (top right corner) and try to connect the accounts before UI kicks you out again.

**Comment by joshuawilson** [comment] 2017-11-09 18:41
To reproduce run the following command, getting the auth_token from the browser application tab local storage
`curl -i  -H "Authorization: Bearer $AUTH_TOKEN" -X DELETE  https://auth.openshift.io/api/token?for=https://github.com`

**Comment by sbose78** [comment] 2017-11-09 20:28
Re-opening , will ensure it works in Prod before we close this.

**Comment by joshuawilson** [comment] 2017-11-09 20:53
This is still not fixed because the build is stuck and we can't get it to master. 

@rajdavies @rawlingsj @jstrachan I think GKE may be down or something but the build is stuck and this fix if a broken production. Please help move this forward.
`All nodes of label ‘uingx_login_client_25’ are offline`
https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/ngx-login-client/job/master/25/console

**Comment by joshuawilson** [comment] 2017-11-10 13:56
in prod now, closing

**Closed by joshuawilson** 2017-11-10 13:56 UTC
Labels: area/auth, kind/bug, severity/blocker, team/auth, team/platform
