### ISSUE TITLE
Features Opt-in description

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3297] opened 2018-04-25 08:13 UTC
There is a bug in the description, where Production and Experimental features have the same description

_This is the default and current release version of the product._

![feature-opts](https://user-images.githubusercontent.com/2078072/39233545-ed9e9522-4870-11e8-88fa-9f9ed5532cda.png)

Also, the wording is a bit inconsistent - the production and internal start with "this / these version/feature" but the beta starts with verb "Experience features".

**Comment by corinnekrych** [comment] 2018-04-25 08:15
duplicate of https://github.com/openshiftio/openshift.io/issues/3254

**Closed by corinnekrych** 2018-04-25 08:15 UTC
