### ISSUE TITLE
Failed to schedule pod on free-stg due to "0/10 nodes are available: 1 Insufficient cpu"

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#2273] opened 2018-02-15 11:01 UTC
Starting che workspace on prod-preview fails.

Che server log:

```
{"@timestamp":"2018-02-15T10:52:19.272+00:00","@version":1,"message":"Failed to get the ID of the container running in the OpenShift pod","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"WorkspaceSharedPool-2","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)\n\tat org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)\n\tat org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)\n\t... 11 common frames
--
  | omitted\nCaused by: org.eclipse.che.plugin.openshift.client.exception.OpenShiftException: Failed to get the ID of the container running in the OpenShift pod\n\tat org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:706)\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:648)\n\tat org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:357)\n\t... 13 common frames omitted\n"}
```
Events on free-stg:

![image](https://user-images.githubusercontent.com/1215011/36253391-b5c22a60-1247-11e8-9c4f-9cfc7aad130d.png)

**Comment by rhopp** [comment] 2018-02-15 11:10
This is affecting not only che, but all OSIO on prod-preview. 
For example, when doing account reset, jenkins pod is not started, because of this same error.
This may also interest @ldimaggi ;-)

**Comment by rhopp** [comment] 2018-02-15 14:10
@pbergene You idled the jenkins pods, thus prod-preview is operational again. Feel free to close this issue

**Comment by pbergene** [comment] 2018-02-15 16:08
Ah yes - meant to comment on here.  Happy to hear that worked.  Sadly it looks like it's back.  Could be bad neighbours..

**Comment by pbergene** [comment] 2018-02-16 07:30
Ah yes - meant to comment on here.  Happy to hear that worked.  Sadly it looks like it's back.  Could be bad neighbours.. 

Found this comment written, but not posted in my browser 16 hours later.  What is it looking like now?

**Comment by ibuziuk** [comment] 2018-02-16 09:59
@pbergene currently prod-preview is unusable

![image](https://user-images.githubusercontent.com/1461122/36302368-7e0eef06-1308-11e8-9b6a-ac95828c53dd.png)

**Comment by pbergene** [comment] 2018-02-16 11:49
Ack. The idling of jenkins was short lived, I'll see what we have consuming resources and investigate usage quotas.

**Comment by jfchevrette** [comment] 2018-02-16 20:23
A bunch of stray infra pods were cleaned up by the ops team and this should now allow us to provision new pods again.

**Comment by davidfestal** [comment] 2018-02-19 10:52
It's broken again right now. I has been working this morning though.

**Comment by ibuziuk** [comment] 2018-02-20 15:09
currently prod-preview console is not available https://console.free-stg.openshift.com/console

**Comment by mmclanerh** [comment] 2018-02-21 16:07
see hk 1336 re: prod-preview console.  currently still an upstream issue -- that is separate from pod scheduling, however.

**Comment by mmclanerh** [comment] 2018-02-21 16:14
for reference: see hk 1349 covering multiple issues for prod-preview

**Comment by jfchevrette** [comment] 2018-02-22 20:46
I have been trying to reproduce this for the past hour or so. All my test pods are starting fine at the moment. The underlying problem may have cleared.

If anyone sees this again please make sure you mention your namespace, pod name and UTC time when this happened.

**Comment by ibuziuk** [comment] 2018-03-09 13:09
just faced it again:
- `ibuziuk-che` namespace
- `workspace-data-migration-workspaceab5a16ylegdqys9r` pod

events:

![image](https://user-images.githubusercontent.com/1461122/37208862-3c029738-23a3-11e8-9f13-6843bcf417b4.png)

**Comment by ibuziuk** [comment] 2018-03-09 14:21
facing it also during workspace creation 
- `ibuziuk-che` namespace 
- `workspace29ocjjnk7q7imapa.dockerimage` pod
- UTC time: 2:19:39 PM, March 9, 2018

![image](https://user-images.githubusercontent.com/1461122/37211839-919dbb46-23ad-11e8-8771-24d4d3d36fdb.png)

**Comment by garagatyi** [comment] 2018-03-12 08:45
Just faced it
- `ogaragat1` namespace
- `workspacequu7g93ghqzmgpif.dockerimage` image
- UTC time: 08:40:10 AM, March 12

`0/10 nodes are available: 1 Insufficient cpu, 3 PodToleratesNodeTaints, 6 MatchNodeSelector.`

**Comment by pbergene** [comment] 2018-03-23 15:53
Closing after change in preview tenant spaces and de provisioning on free-stg

**Closed by pbergene** 2018-03-23 15:53 UTC
Labels: SEV2-high, env/prod-preview, team/service-delivery, type/bug
