### ISSUE TITLE
tenant jenkins does not ask 'Login with Red Hat'

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#1525] opened 2017-12-07 04:22 UTC
1. Did a reset environment today  ( and have jenkins 4.0.44 )
2. Created a quickstart project.
3. Opened the pipelines page and clicked 'view logs' https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/sbose78/job/testafterdowntime01/job/master/1/console

![screenshot from 2017-12-07 09-35-19](https://user-images.githubusercontent.com/545280/33698682-1c47de56-db34-11e7-8c5c-4d7ea18d6f34.png)

**Comment by sbose78** [comment] 2017-12-07 04:40
Had to click on the top right to be able to reach the sso login - nevertheless it's a slightly confusing user experience. The previous experience was really nice :)

**Comment by sbose78** [comment] 2017-12-07 04:50
Re-opened because this new experience is confusing - I was used to seeing the RHD login page directly.

**Comment by maxandersen** [comment] 2017-12-07 05:00
I agree what @sbose78 are seeing definitely are not expected, for what it is worth when I reset my environment and I get jenkins 4.0.44 then I do get the normal RHD login directly - not what @sbose78 is seeing here.

**Comment by pbergene** [comment] 2017-12-07 19:17
I'm seeing this too on jenkins 4.0.45 - this does not match the onboarding doc, so we'll need to try to fix this.

**Comment by joshuawilson** [comment] 2017-12-07 19:28
I can confirm, I'm seeing this too.

@qodfathr this is may be a change to the onboarding doc.

**Comment by kbsingh** [comment] 2017-12-07 21:58
Just to be clear, this is not a feature piece we need fixing in the service, but a documentation issue that needs to be fixed for the onboarding doc ? if so, I dont think we need to mark this as SEV1, and would encourage the team to re-consider that position.

**Comment by mmclanerh** [comment] 2017-12-07 22:06
sgtm, re this not being a sev1 outage/blocking item.  i'm going to change back to sev2-high, unless there is dissent.

can we confirm if this is an intended change? it sounds like the prior experience was quite different: https://github.com/openshiftio/openshift.io/issues/1525#issuecomment-349863497

**Comment by alexeykazakov** [comment] 2017-12-07 22:11
I believe it's a bug in OSIO. It's a regression in tenant Jenkins. It's very confusing to see this useless User/Password dialog. If it's hard to fix and it take a while then we could update our docs to warn users and help them to work it around. But adding a workaround to our docs for a regression bug is not a long term solution.

**Comment by mmclanerh** [comment] 2017-12-07 22:42
i may have over-stepped in changing the severity here.  i'll put this back and let team/build-cd sort out an appropriate urgency.   sorry about that.

**Comment by kbsingh** [comment] 2017-12-07 23:25
offline conversation result: this needs fixing in the jenkins side of things to restore functionality.

**Comment by pbergene** [comment] 2017-12-08 08:28
@kbsingh I am under the impression from conversation with @qodfathr  that anything not matching the onboarding doc is a blocker for onboarding and considered a SEV1.

**Comment by maxandersen** [comment] 2017-12-08 11:02
@rajdavies @rawlingsj any chance one of you could help identify the cause of this change ?

@alexeykazakov any chance this can be happening because of changes on auth/kc side ?

**Comment by maxandersen** [comment] 2017-12-08 11:05
msg from @rajdavies that @rupalibehera is looking into this.

**Comment by sbose78** [comment] 2017-12-08 12:43
> @alexeykazakov any chance this can be happening because of changes on auth/kc side ?

@maxandersen , Nope.

**Comment by pbergene** [comment] 2017-12-08 14:09
Working on unblocking @rupalibehera

**Comment by aditya-konarde** [comment] 2017-12-08 14:59
Looks like its solved for me. I got the log in with openshift button.

**Comment by mmclanerh** [comment] 2017-12-08 19:29
@rupalibehera are you still blocked here?

**Comment by mmclanerh** [comment] 2017-12-08 20:36
@rupalibehera  reported now to be unblocked and able to proceeed.

**Comment by rupalibehera** [comment] 2017-12-08 20:42
@mmclanerh , thanks for the help.

**Comment by rupalibehera** [comment] 2017-12-08 20:48
@sbose78 , I am not able to reproduce this issue anymore with Jenkins Version 4.0.45 , could you please do a `Update Tenant` and check if the Jenkins Version is `4.0.45` and see if you are able to reproduce this issue anymore.
Link to my Jenkins in my account,  https://jenkins-rbehera-1-jenkins.8a09.starter-us-east-2.openshiftapps.com/securityRealm/commenceLogin?from=%2Fjob%2Frupalibehera%2Fjob%2Ffoooobaaaartest123%2Fjob%2Fmaster%2F1%2Fconsole

**Comment by mmclanerh** [comment] 2017-12-08 22:56
while i don't see a reference to what updates were deployed in this issue (sounds like jenkins had an fix pushed out), testing is no longer able to reproduce this issue.   closing this item unless there are further reports of a regression wrt passing auth into jenkins.

**Closed by mmclanerh** 2017-12-08 22:56 UTC
Labels: area/pipelines, SEV1-urgent, team/build-cd, type/bug

**Comment by rupalibehera** [comment] 2017-12-12 14:22
@maxandersen @pbergene 

The above issue was introduced to when we updated all the plugins to latest versions [here](https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/775172b5fa3d4f43b2eca193a2a67a563bba1820), in which the [openshift-login plugin](https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/775172b5fa3d4f43b2eca193a2a67a563bba1820#diff-881c0fd517d14a5de30243602e8b3f7eR90)  was also updated and we suspected that it might be the issue. 
But the issue got resolved when we updated to latest k8's plugin https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/72871095fb0e8642bb521bf7de8c688ed261a833. This is generated from this https://github.com/jenkinsci/kubernetes-pipeline-plugin (we need build this and [copy](https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/copy-latest-build-jars.sh) to [plugins](https://github.com/fabric8io/openshift-jenkins-s2i-config/tree/master/plugins) directory  ).

Below are details of Job links and PR:
v4.0.44
https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/775172b5fa3d4f43b2eca193a2a67a563bba1820
https://github.com/fabric8-services/fabric8-tenant-jenkins/commit/3d52de4bf0c0b88f6697499f3972b26b57ecafdf
https://jenkins.cd.test.fabric8.io/job/fabric8-services/job/fabric8-tenant-jenkins/job/master/41/consoleFull



v4.0.45
https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/72871095fb0e8642bb521bf7de8c688ed261a833
https://github.com/fabric8-services/fabric8-tenant-jenkins/commit/3603794100389ca7b83611467cf4afb10ad1a884
https://jenkins.cd.test.fabric8.io/job/fabric8-services/job/fabric8-tenant-jenkins/job/master/43/consoleFull
