### ISSUE TITLE
Webhook from github to jenkins fails with 500 status code

### ISSUE THREAD

**Issue by jarifibrahim** [openshiftio/openshift.io#4600] opened 2018-11-29 13:52 UTC
##### Issue Overview
I am trying to build a nodejs app (https://github.com/nodeshift-starters/nodejs-rest-http-crud) on OSIO pipeline. The build works fine but I cannot trigger builds via code commits. The webhook from github to jenkins always fails with `500 status code`

Tell us briefly what the problem is about.

##### Expected Behaviour
Commits to the source code should retrigger new builds

##### Current Behaviour
Commits to the source code do not trigger new builds

##### Steps To Reproduce

1. Import https://github.com/nodeshift-starters/nodejs-rest-http-crud (or any other project)
2. Replace existing Jenkinsfile with  https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/node/ReleaseStageApproveAndPromote/Jenkinsfile (or some other jenkins file)
3. Make code changes on github
4. Check jenkins webhook on github. It should've failed with 500 error

##### Additional Information
This issue might not be reproducible. I had used the same repository to create multiple apps and builds. Only the first attempt was successful.
I have tried 
- clearing the OSIO environment
- deleting the repository and forking a new one.

The following was the request sent from github
```json
Request URL: https://jenkins.prod-preview.openshift.io/github-webhook/
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/f79ac2f
X-GitHub-Delivery: 6771d1a0-f3db-11e8-990d-15484ee5e6f9
X-GitHub-Event: ping
X-Hub-Signature: sha1=189acdc114f7a210eab92e826e3c30be826b1a30
```
with payload
```json
{
  "zen": "Approachable is better than simple.",
  "hook_id": 66299202,
  "hook": {
    "type": "Repository",
    "id": 66299202,
    "name": "web",
    "active": true,
    "events": [
      "issue_comment",
      "pull_request",
      "push"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "1",
      "secret": "********",
      "url": "https://jenkins.prod-preview.openshift.io/github-webhook/"
    },
    "updated_at": "2018-11-29T13:33:49Z",
    "created_at": "2018-11-29T13:33:49Z",
    "url": "https://api.github.com/repos/jarifibrahim/nodejs-rest-http-crud/hooks/66299202",
    "test_url": "https://api.github.com/repos/jarifibrahim/nodejs-rest-http-crud/hooks/66299202/test",
    "ping_url": "https://api.github.com/repos/jarifibrahim/nodejs-rest-http-crud/hooks/66299202/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 159670922,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNTk2NzA5MjI=",
    "name": "nodejs-rest-http-crud",
    "full_name": "jarifibrahim/nodejs-rest-http-crud",
    "private": false,
    "owner": {
      "login": "jarifibrahim",
      "id": 12949454,
      "node_id": "MDQ6VXNlcjEyOTQ5NDU0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/12949454?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jarifibrahim",
      "html_url": "https://github.com/jarifibrahim",
      //   ...
      "received_events_url": "https://api.github.com/users/jarifibrahim/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/jarifibrahim/nodejs-rest-http-crud",
    "description": "Example CRUD for nodejs",
    "fork": true,
    "url": "https://api.github.com/repos/jarifibrahim/nodejs-rest-http-crud",
    // ...
    "deployments_url": "https://api.github.com/repos/jarifibrahim/nodejs-rest-http-crud/deployments",
    "created_at": "2018-11-29T13:30:40Z",
    "updated_at": "2018-11-29T13:30:42Z",
    "pushed_at": "2018-11-29T13:33:48Z",
    "git_url": "git://github.com/jarifibrahim/nodejs-rest-http-crud.git",
    "ssh_url": "git@github.com:jarifibrahim/nodejs-rest-http-crud.git",
    "clone_url": "https://github.com/jarifibrahim/nodejs-rest-http-crud.git",
    "svn_url": "https://github.com/jarifibrahim/nodejs-rest-http-crud",
    "homepage": null,
    "size": 753,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "jarifibrahim",
    "id": 12949454,
    "node_id": "MDQ6VXNlcjEyOTQ5NDU0",
    "avatar_url": "https://avatars3.githubusercontent.com/u/12949454?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jarifibrahim",
    // ...
    "received_events_url": "https://api.github.com/users/jarifibrahim/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

with response
```json
Content-Length: 200
Content-Type: text/plain; charset=utf-8
Date: Thu, 29 Nov 2018 13:33:50 GMT
Set-Cookie: 4663a78dab...9ae9aa26ea; path=/; HttpOnly; Secure

Body
{
    "Errors": [
        {
            "code": "500",
            "detail": "2: openshift client error: got status 404 Not Found (404) from https://api.starter-us-east-2a.openshift.com/oapi/v1/namespaces/-jenkins/deploymentconfigs/jenkins"
        }
    ]
}
```

**Comment by corinnekrych** [comment] 2018-11-29 16:23
- I've reproduced the issue with app creation of a vertx booster.
- I've noticed that the webhook error only occurs on prod-preview see [webhook error on prod preview](https://github.com/corinnekrych/tooooooo/settings/hooks/66307222), prod is ok.
- As @jarifibrahim noticed:
it's failing because the usename is missing. The error was
```
"detail": "2: openshift client error: got status 404 Not Found (404) from https://api.starter-us-east-2a.openshift.com/oapi/v1/namespaces/-jenkins/deploymentconfigs/jenkins"
```
it should be namespaces/$username-jenkins/deploymentconfigs/...

@gastaldi do you know where this username is coming from?

**Comment by gastaldi** [comment] 2018-11-29 16:33
Not sure this is a Launcher bug, as it seems to be a bug in the Jenkins side. Launcher only adds the webhook

**Comment by chmouel** [comment] 2018-11-29 16:40
```
            "detail": "2: openshift client error: got status 404 Not Found (404) from https://api.starter-us-east-2a.openshift.com/oapi/v1/namespaces/-jenkins/deploymentconfigs/jenkins"
```

weird it seems that it can't get the username here, it seems that it occurs since we merged kishan's commit : 

https://github.com/fabric8-services/fabric8-jenkins-proxy/commit/d3a8164fe54989d3c5bc23e4e75fb0ac96e59ee8


@khrm can you please revert this commit and take this forward to test if the bug is in that patch ?

**Comment by kishansagathiya** [comment] 2018-12-03 05:34
Looking into this
This is exactly where it is happening

https://github.com/fabric8-services/fabric8-jenkins-idler/blob/ebf73b784db1341c44307c8424eb51ac1f679769/internal/api/api.go#L202

looking if proxy is sending an empty namespace

**Comment by kishansagathiya** [comment] 2018-12-03 05:58
The error is happening because of 
https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/140b669a04d1a98a9c75d3161f3822fa34a88f83/internal/proxy/github.go#L64

`ns` is an empty string here. Will be pushing a fix soon.

**Closed** 2018-12-05 03:35 UTC
Labels: SEV2-high, area/jenkins-proxy, priority/P3, team/app-creation, team/build-cd, type/bug

**Comment by piyush-garg** [comment] 2018-12-05 03:59
This has been fixed with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/342 and new proxy deployed on prod-preview today morning.
