### ISSUE TITLE
Jenkins fails to come up on the new 2a cluster

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#2748] opened 2018-03-23 11:03 UTC
The logs end with a bazillion Java exceptions and eventually the Jenkins process stops.  Attaching the full logs along. 

[jenkins.log](https://github.com/openshiftio/openshift.io/files/1841243/jenkins.log)

```
Mar 23, 2018 10:54:36 AM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins
Mar 23, 2018 10:54:36 AM jenkins.model.Jenkins$19 onAttained
INFO: Started termination
Mar 23, 2018 10:54:36 AM jenkins.model.Jenkins$19 onAttained
INFO: Completed termination
Mar 23, 2018 10:54:36 AM jenkins.model.Jenkins _cleanUpDisconnectComputers
INFO: Starting node disconnection
Mar 23, 2018 10:54:36 AM jenkins.model.Jenkins _cleanUpShutdownPluginManager
INFO: Stopping plugin manager
Mar 23, 2018 10:54:36 AM jenkins.model.Jenkins _cleanUpPersistQueue
INFO: Persisting build queue
Mar 23, 2018 10:54:37 AM jenkins.model.Jenkins cleanUp
INFO: Jenkins stopped
```

**Comment by jaseemabid** [comment] 2018-03-23 11:32
@pbergene  Prod + 2a. I'm looking at the logs, but there is so much noise to pinpoint into something.

**Comment by ldimaggi** [comment] 2018-03-23 12:26
Are you still able to recreate this issue? I am not able to recreate it. I just did a user env reset - with a user account provisioned on the starter-us-east-2a cluster - and Jenkins started up cleanly.

![screenshot from 2018-03-23 08-26-27](https://user-images.githubusercontent.com/642621/37829045-e825c9ba-2e73-11e8-9d50-0216de256ad3.png)

**Comment by chmouel** [comment] 2018-03-23 12:43
I can't reproduce this as well, I did a `oc idle jenkins` manually and went back to `jenkins.openshift.io` and I have my jenkins coming alive after a little while, although I am seeing this Red Only filesystem error too 

![image](https://user-images.githubusercontent.com/98980/37829611-f931ce1c-2e9f-11e8-858c-607e38ffdf3a.png)

**Comment by jfchevrette** [comment] 2018-03-23 12:48
I can't reproduce either.

Looks like your jenkins may be missing some plugins?
```
Mar 23, 2018 10:54:25 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Branch API Plugin v2.0.16 (branch-api)
java.io.IOException: Branch API Plugin v2.0.16 failed to load.
 - cloudbees-folder v6.1.0 is missing. To fix, install v6.1.0 or later.
 - scm-api v2.2.3 is missing. To fix, install v2.2.3 or later.
 - structs v1.9 is missing. To fix, install v1.9 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Mar 23, 2018 10:54:25 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Autofavorite for Blue Ocean v1.2.1 (blueocean-autofavorite)
java.io.IOException: Autofavorite for Blue Ocean v1.2.1 failed to load.
 - workflow-api v2.22 is missing. To fix, install v2.22 or later.
 - workflow-job v2.14.1 is missing. To fix, install v2.14.1 or later.
 - Branch API Plugin v2.0.16 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Mar 23, 2018 10:54:25 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline: SCM Step v2.6 (workflow-scm-step)
java.io.IOException: Pipeline: SCM Step v2.6 failed to load.
 - Pipeline: Step API v2.14 failed to load. Fix this plugin first.
```

**Comment by chmouel** [comment] 2018-03-23 12:50
Yeah right @jaseemabid are you testing a PR of a new unreleased jenkins image? It should be vd9a0b29

**Comment by jaseemabid** [comment] 2018-03-23 13:17
I'm using the released version and did a reset before this. Redeploying twice made it work, so I'm making it a sev2. Will go through the logs again and try to find the root cause.

**Comment by piyush1594** [comment] 2018-06-20 04:00
@jaseemabid I think this is very old and not the case right now. Can we close this? cc @sthaha

**Comment by sthaha** [comment] 2018-06-20 04:03
@piyush1594 2a seems to work just fine based on my experience with prod-preview. Going to close this.

@jaseemabid  Please reopen if can reproduce this.

**Closed by sthaha** 2018-06-20 04:03 UTC
Labels: SEV2-high, team/build-cd, type/bug
