### ISSUE TITLE
App deployments fail silently after quota is exhaused.

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#2897] opened 2018-04-05 10:17 UTC
I've an openshift account that has already exhausted its quota and there are a few apps running in stage/prod envs. I can start a new build to deploy an app and Jenkins reports that the app deployment went fine while it failed with quota errors behind the scene. There are no errors in Jenkins logs. OSIO does not report any errors either. Openshift thankfully sheds light into the problem with the following error. 

```
Error creating: pods "vertx1-5-" is forbidden: exceeded quota: compute-resources, requested: 
limits.cpu=1,limits.memory=512Mi, used: limits.cpu=2,limits.memory=1Gi, limited: 
limits.cpu=2,limits.memory=1Gi
27 times in the last 2 hours
```

We should either prevent the build from starting or report an error in the build that quota is exhausted. Also tell people what to do at that point. 

This bug is related, but it talks more about the parallelism aspect rather than resource exhaustion. https://github.com/openshiftio/openshift.io/issues/2729

**Comment by catrobson** [comment] 2018-04-05 23:03
Designs are not final, but in progress designs can be seen here: https://redhat.invisionapp.com/share/BHGPNUXCR9A#/screens/287414528

**Comment by piyush1594** [comment] 2018-06-21 06:09
Duplicate of #3346 Can we close this? @jaseemabid

**Closed** 2018-06-21 07:35 UTC
Labels: SEV3-medium, area/jenkins, area/pipelines, team/build-cd, type/bug
