### ISSUE TITLE
New GS workflow has UI bugs

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2821] opened 2018-03-29 04:27 UTC
Two UI bugs when using the new getting started flow at the `Select Mission & Runtime` step:

1. Clicking `More` to see the details for either REST API Level 0 or Health Check missions displays the text about them but the text is cut off at the end of the box instead of soft wrapping around. This hides everything but the first ~28 words.

2. The `Select Runtime` box shifts to the right out of the screen view when we expand the mission text. We can still access the radio buttons but can no longer read what they are or anything about them. There is no horizontal scroll bar so we can't view the rest at all unless we use `Less` to reduce the text for both the Mission options. The text should soft wrap, not shift the rest of the UI elements off the screen.

Screenshot to illustrate both these issues:
![screenshot](https://user-images.githubusercontent.com/926572/38070051-25a038dc-335d-11e8-80cd-9ed3f3325445.png)

3. The next steps are also centered oddly as a result of the above. See an example of pipeline step:
![2](https://user-images.githubusercontent.com/926572/38070326-c0a2c38a-335e-11e8-94af-d32d62bc2826.png)

**Comment by invincibleJai** [comment] 2018-04-09 18:10
Thanks @mishaone looks like it's intermittent. Are you able to reproduce it?

**Comment by mishaone** [comment] 2018-04-10 00:29
Hi @invincibleJai - Yes, I can reproduce this 100% of the time. Please see steps below:

1. Using the new workflow, if we try to create a quickstart, in the first step where we are to select a mission, click `expand` to read the explanations for the options. There is no `less` link anymore so expanding is an irreversable option. The next step (Select a runtime) is now impossible to read.

![select_mission](https://user-images.githubusercontent.com/926572/38529570-e1a428fa-3ca8-11e8-98be-0b94626bb6d7.png)

2. Now, if we use the manual browser scroll bar to scroll to the next step, it renders correctly:

![manual_scroll](https://user-images.githubusercontent.com/926572/38529584-fd2c3f0e-3ca8-11e8-81e9-37227a72f7bb.png)

3. However, this is not the correct workflow since we did not choose a runtime in the previous step. Scroll back up manually and it still renders that weird way as before. Select any runtime option and click the double arrow at the bottom of the page to go to the next step according to the correct workflow:

![select_options](https://user-images.githubusercontent.com/926572/38529609-3445963e-3ca9-11e8-8f06-7a14e46ca761.png)

4. You are now taken to the next step but the page is centered or something so the pipeline options display in a way where it is impossibe to select any option. 

![pipeline_again](https://user-images.githubusercontent.com/926572/38529627-55169c8c-3ca9-11e8-9faf-4a96f80778dc.png)

5. So now I'm stuck in this loop. I can manually use the browser scroll to go up and down to the various steps but they are all oddly centered. There is no horizontal scroll bar for the browser on this page so I can't scroll left or right. just up and down. The only way to work around this is to quit and return to the space page and try afresh. 

I hope this helps reproduce the issue.

**Comment by invincibleJai** [comment] 2018-04-11 13:42
@mishaone changes are in prod now, pls let us know if you still experience this issue.

**Comment by invincibleJai** [comment] 2018-04-13 08:13
Closing this as it has been fixed, feel free to reopen if you still see it.

**Closed by invincibleJai** 2018-04-13 08:13 UTC
Labels: SEV2-high, area/UI, area/app-wizard, issue/intermittent, team/analytics, team/analytics/wizard, team/launcher, type/bug
