### ISSUE TITLE
Multiple jenkins instances not idling after many days

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#3758] opened 2018-06-11 13:47 UTC
```
# starter-us-east-2
luebken-jenkins               jenkins-11-9qzkg  1/1  Running  0  12d
mperezco-jenkins              jenkins-5-jrqvv   1/1  Running  0  12d
mario-loriedo-jenkins         jenkins-2-cphwd   1/1  Running  0  12d
christian-koeberl-jenkins     jenkins-7-nhvv7   1/1  Running  0  12d
rhn-support-rpuccini-jenkins  jenkins-6-5clvr   1/1  Running  0  12d
chart-jenkins                 jenkins-9-cmgm5   1/1  Running  0  12d
dneelagiri-jenkins            jenkins-5-jxwzm   1/1  Running  0  12d
velias-jenkins                jenkins-5-pxfrk   1/1  Running  0  12d
mmorhun-jenkins               jenkins-5-292ff   1/1  Running  0  12d
mspisiak-osio-jenkins         jenkins-5-dj6gh   1/1  Running  0  12d
yasun-113-jenkins             jenkins-5-smvjl   1/1  Running  0  12d
rhn-gps-anz-noconnor-jenkins  jenkins-8-9zm5v   1/1  Running  0  12d
rhn-support-kgresch-jenkins   jenkins-5-j525m   1/1  Running  0  12d
agajdosi-jenkins              jenkins-1-2wmd2   1/1  Running  0  12d

# starter-us-east-2a
info-jenkins                      jenkins-5-69fhh  1/1  Running  0  10d
michael-dias-jenkins              jenkins-4-p85l6  1/1  Running  0  10d
ppitonak-preview-jenkins          jenkins-1-rk4v8  1/1  Running  0  10d
dth-jenkins                       jenkins-2-z8rk4  1/1  Running  0  10d
```

All have zero Builds or Buildconfigs. I've also tried to check the `/api/idler/info/NAMESPACE` endpoint as explained in the readme but that endpoint doesn't work (returns 404)

I've restarted the idler service so that it regenerate it's initial state/cache and then look for the above namespaces in the logs and I could not find them at all. I wonder if those are not tracked by the idler for some reason?

**Comment by ppitonak** [comment] 2018-06-13 11:53
Since one of them is mine, can I help you somehow?

**Comment by piyush1594** [comment] 2018-07-30 07:08
@lordofthejars Can we close this as a duplicate of #2418 WDYT @jfchevrette

**Comment by piyush-garg** [comment] 2018-12-20 14:17
Closing this as it is a very old one and also we are currently working on #4658 

cc @sthaha @hrishin @pradeepto

**Closed by piyush-garg** 2018-12-20 14:17 UTC
Labels: SEV4-low, area/jenkins, priority/P4, sprint/tbd, team/build-cd, type/bug
