### ISSUE TITLE
Are username's based on UID's or actual strings of the username

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1334] opened 2017-11-13 20:10 UTC
It looks to me that the key for my username is an actual string of my username which transports me around.

Usually, in a widely deployed application with tons of users. This might not be desired since it requires unique usernames all over. Instead of just basing it all on a UID which just publishes a username. 

Probably by design, but something I feel worth raising since if there are to be several groups, authentication sources etc there's a chance of colliding users. Is it first come first serve then?

**Comment by joshuawilson** [comment] 2017-11-13 20:14
@aslakknutsen do know the answer?

**Comment by alexeykazakov** [comment] 2017-11-13 20:24
Right now we use usernames (must be unique) which are visible to users because they are used in URL (e.g. https://openshift.io/alkazako ), OpenShift Online project names, etc.
We also use UUIDs internally.

**Comment by Rydekull** [comment] 2017-11-13 23:01
Sure, but if you look at the number of account options that exist when you try to login. There is a good chance someone on one service is using the same username as someone else at another service. Which means there will be a collision.

**Comment by alexeykazakov** [comment] 2017-11-13 23:10
Not sure I'm following... My user OSIO name is alkazako. What other services do you mean? You mean not-OSIO services? Why should we care? What collisions we may get?

**Comment by Rydekull** [comment] 2017-11-13 23:19
Well, let's say... I have a github account, authorizing with: mycoolusername
I sign up to OpenShift.io, using the login page that exists. 

Later, another person using mycoolusername on twitter, decides to sign up.
Will they now see that mycoolusername which they auth with is already taken as username?

Basically, will it cause an issue/collision?

**Comment by alexeykazakov** [comment] 2017-11-13 23:25
Oh, you are referring to social login in developers.redhat.com (we use developers.redhat.com to login to openshift.io). We are working on removing this option for now until it works well. To be clear. You wont be allowed to create a user with a username if it's already taken but it's not recommended to use social login because of different issues.
Right now usernames are auto-generated but we plan to allow new users to pick up his/her own unique username during registration.

**Comment by Rydekull** [comment] 2017-11-13 23:26
Actually, that just made me realize there is a problem.

So in OpenShift.io I login, and I can see my accountname in the URL (basically my email).

Whereas when I go to OpenShift online, the projects created are half my username, namely, the part before @, which means if two usernames are in different domains there will be a problem.

**Comment by alexeykazakov** [comment] 2017-11-13 23:58
Yeah... it's not ideal right now. We don't use your email as a username actually. It just happened that developers.redhat.com created a username == your email. This is one of the reason why we want developers.redhat.com allow user to pick a username instead of auto-generate it.
OpenShift Online doesn't allow to use @ in usernames. So it's trimmed. We are going to refactor it at some point.

**Comment by Rydekull** [comment] 2017-11-14 07:04
Well, in a way it makes more sense to have it done with the full username using an email, it makes it unique.
The only way I could notice these issues is the fact that so many "old" users didn't follow the same theme. 

With or without having a full email, I do not think using that as part of URL etc is good (unless its unique).
But even if it is unique, if its in my URL, sharing a link, writing documentation etc just gets a pain since you have to have people adjusting the link. Much better to just do that in the background without exposing it in the URL itself.

**Comment by joshuawilson** [comment] 2017-11-14 18:56
While it may make documenting action more difficult, it should make getting work done easier.

The intent is to share your link, like a github URL, with others and have them see your work. This is made easy by using your username in the URL.

It was designed this way intentionally. But we are open to hearing your concerns.

**Comment by alexeykazakov** [comment] 2018-01-12 22:20
All the questions here were answered I hope. I'm closing this issue.

**Closed by alexeykazakov** 2018-01-12 22:20 UTC
Labels: area/auth, team/auth, type/question
