### ISSUE TITLE
Che stuck in 'starting workspace' state

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1573] opened 2017-12-08 16:48 UTC
Opening Che is a bit of a lottery. Often I end up with being stuck in "opening workspace" state:

![stuck](https://user-images.githubusercontent.com/296354/33775527-f8b1bdc0-dc3e-11e7-82ad-ea9b16bf9de5.png)

There is no indication or pointer what the problem is. It might be I am running out of resources, but that is a guess at this stage.

It seems it is generally quite easy to get out of sync in terms of the overall pieces playing together. I am wondering whether there is a component which watches the overall state and health of a given tenant.

**Comment by hferentschik** [comment] 2017-12-08 16:50
After some time I am getting this error message:

![error](https://user-images.githubusercontent.com/296354/33775964-46a052ac-dc40-11e7-9f2d-2a8af9e1d342.png)

I would have loved to just cut&paste the error message, but that does not seem possible :-(

**Comment by slemeur** [comment] 2017-12-11 09:24
I just faced the same issue. My account has switched to che multi-tenant.

**Comment by slemeur** [comment] 2017-12-11 09:34
Doing a refresh of the browser tab did the workaround for the issue.

**Comment by l0rd** [comment] 2017-12-11 10:00
That's related to #1589 and #1585. That's the same root cause (openshift route on starter cluster taking minutes to be available, and when available don't behave consistently for the first ~30 seconds) and will be addressed in the same way.

**Comment by ibuziuk** [comment] 2017-12-21 15:25
@ldimaggi @rhopp this one should be fixed - could you please verify ?

**Comment by ibuziuk** [comment] 2018-01-03 19:23
@ldimaggi @rhopp closing. Feel free to reopen if needed

**Closed by ibuziuk** 2018-01-03 19:23 UTC
Labels: area/che, SEV2-high, team/che/osio, type/bug
