### ISSUE TITLE
First build/application version created is 1.0.1 - why not 1.0.0

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#485] opened 2017-08-08 15:08 UTC
Small point, but the first build/application version created is assigned a version number of 1.0.1

Why isn't this 1.0.0?

![screenshot from 2017-08-08 11-06-33](https://user-images.githubusercontent.com/642621/29078975-e619f1e8-7c29-11e7-93eb-841e03e7fb7e.png)

**Comment by joshuawilson** [comment] 2017-08-09 16:53
@jstrachan @rawlingsj any ideas?

**Comment by qodfathr** [comment] 2018-01-17 16:59
Closing by design. As you said in the title, it's the *first* build, and first == 1. :)

Yes, that's a lame answer, but it will be sufficient for now.

**Closed by qodfathr** 2018-01-17 16:59 UTC
Labels: SEV3-medium, area/applications, area/deployments, team/build-cd, team/platform, type/bug

**Comment by joshuawilson** [comment] 2018-01-18 03:44
It is designed to be `1.0.1` for the first version instead of `1.0.0`?
