### ISSUE TITLE
[MT-Che] "Cound not retrieve OSO token from Keycloak token" when deleting workspaces

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#1649] opened 2017-12-13 13:10 UTC
I had multiple workspaces on openshift.io. When I deleted them using dashboard che.openshift.io, the currently running workspace pod on OSO was not deleted, nor the "delete" pods for cleaning PVC were created.

che pod log from dsaas: https://pastebin.com/KHLX4gax

**Comment by rhopp** [comment] 2017-12-13 13:11
Not sure it's related, but when the che-server pod started, there was this error right after catalina start:
```
2017-12-13 12:23:43,672[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 10586 ms
  | 2017-12-13 12:24:06,691[nio-8080-exec-5]  [ERROR] [o.a.c.c.C.[.[.[.[default] 236]       - Servlet.service() for servlet [default] in context with path [/wsmaster] threw exception [Cannot find user by machine token.] with root cause
  | javax.servlet.ServletException: Cannot find user by machine token.
  | at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:70)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
 ```
I'm not sure I've seen this error before.

**Comment by rhopp** [comment] 2017-12-13 13:48
Just confirmed that the error from my previous comment has nothing to do with this issue. I was able to reproduce this issue even after the pod was restarted and it started succesfully without the `Cannot find user by machine token.` error

**Comment by davidfestal** [comment] 2017-12-13 14:00
yes, I can confirm that it's not caused by the `cannot find user from machine token` error.
It is related to the fact that the keycloak token has been invalidated after being stored into the wsmaster.
Could you provide more details on the scenario you use to produce this error and the Keycloak user that is used ?

**Comment by rhopp** [comment] 2017-12-13 14:03
My scenario is basically just starting workspaces using che-started and deleting them using che dashboard with occasional openshift.io environment reset ;-)
The user I'm seeing this with is rhopp@redhat.com. I'm gonna try another user and see if I can reproduce that.

**Comment by alexeykazakov** [comment] 2017-12-13 18:20
Make sure you didn't logout (in another browser tab?). It invalidates KC token.

**Comment by ibuziuk** [comment] 2018-08-31 15:00
@rhopp I believe we could close this one, since the issue with workspace deletion should not be reproducible anymore.

**Closed by ibuziuk** 2018-08-31 15:00 UTC
Labels: SEV3-medium, area/auth, area/che, priority/P4, status/analyzing, team/che/osio, type/bug
