### ISSUE TITLE
Intermittent issue seen randomly when creating new app

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3612] opened 2018-05-23 00:45 UTC
When creating a new app, the summary screen is sometimes shown as follows:

![screenshot from 2018-05-22 17-10-43](https://user-images.githubusercontent.com/642621/40397453-db3d9e50-5e00-11e8-9ee9-fdbc4e35b622.png)

The app's build pipeline is created correctly. I have not been able to seen any pattern for this issue - nothing is written to the browser console or logs.

**Comment by animuk** [comment] 2018-06-12 11:19
@gastaldi Can you check this ? I remember that you were planning to implement some Queue for the websocket call. what is the current update

**Comment by gastaldi** [comment] 2018-06-12 11:56
@animuk Is this caused by having multiple replicas? 

Yes, the backend supports that but the JMS service (Artemis) is not installed in the dsaas cluster (that's why it is running in 1 replica only).

**Comment by animuk** [comment] 2018-07-24 05:35
this issue is not observed now. So, closing this

**Closed by animuk** 2018-07-24 05:35 UTC
Labels: SEV3-medium, area/launcher, issue/intermittent, team/analytics, team/analytics/wizard, team/launcher, type/bug
