### ISSUE TITLE
Tenant cannot reset environment if there are many spaces to scroll down

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3269] opened 2018-04-24 07:30 UTC
_Fedore+Chrome_
The button to reset environment cannot be reached if the user has many spaces. On the reset env page, vertical scrolling doesn't work and the button at the bottom of the page cannot be reached. 

See here:

![cant scroll reset env page](https://user-images.githubusercontent.com/28748448/39172435-5af26c5a-47bf-11e8-9bf3-abbb183f8665.png)

**Comment by aptmac** [comment] 2018-04-26 15:53
@rgarg1 are you able to reproduce this currently? Had you recently visited the Planner page in OSIO? It tends to eat the vertical scroll bars and could the culprit here.

**Comment by rgarg1** [comment] 2018-04-27 08:14
@aptmac Yeah I can see what you are implying. So I logged into OSIO and went straight to the reset env page, I was able to see all spaces and was able to scroll. However, the second time I went to the planner page before coming back to the reset page, this time the vertical scroll vanished.

Cc @nimishamukherjee

**Comment by aptmac** [comment] 2018-04-27 13:44
Great, thanks for confirming. I'll close this particular issue then because it's been noted and documented elsewhere [0], and there's a small fix that currently works in local builds but hasn't made it's way to production I believe [1].

[0] https://github.com/openshiftio/openshift.io/issues/3104#issuecomment-383684018
[1] https://github.com/fabric8-ui/fabric8-planner/pull/2577

**Closed by aptmac** 2018-04-27 13:44 UTC
Labels: SEV3-medium, area/UI, area/user/profile, team/platform, type/bug
