### ISSUE TITLE
Maven run command not configured as per section 4.12 of Getting Started Guide

### ISSUE THREAD

**Issue by brizrobbo** [openshiftio/openshift.io#2611] opened 2018-03-15 01:19 UTC
_[Was previously an issue in [fabric8io/fabric8-online-docs](https://github.com/fabric8io/fabric8-online-docs/issues/204), but now migrated to product]_

In [Section 4.12. Configuring your Che workspace](https://docs.openshift.io/getting-started-guide.html#configuring_your_che_workspace-hello-world) of the [OpenShift.io Getting Started Guide](https://docs.openshift.io/getting-started-guide.html#creating_che_workspace-hello-world), point 2 (d) shows:

d. Click the *run* option from the Run button (tri-run-image) ....

When I ran it, it did not give me any options to 'run' as shown in the tri-run-image. The sub option for me when I hit run was "Create run command". I had to manually go an create my own run command to get it to work.

This could have been because my Che environment was not setup correctly, but I did follow the previous steps in 2. a) - c).

**Comment by joshuawilson** [comment] 2018-03-15 01:22
cc @gorkem @l0rd

**Comment by ldimaggi** [comment] 2018-03-15 01:44
Criag - did you see this after importing a repo into OSIO?

**Comment by brizrobbo** [comment] 2018-03-15 01:57
@ldimaggi Yes. I originally created the helloworldvertx repo as per the guide, but was having some issues with Jenkins. To resolve the Jenkins issues, I reset my environment. The second time around, as the helloworldvertx repo was already created, I just imported instead of creating a new one.

**Comment by l0rd** [comment] 2018-03-15 08:14
@brizrobbo if I understand your scenario this is a duplicate of https://github.com/openshiftio/openshift.io/issues/2358. Unfortunately we don't pre-configure commands when you import an existing github repo yet.

**Comment by stevengutz** [comment] 2018-09-24 10:43
@l0rd Since this is a duplicate and #2358 is closed, can't this be closed?

**Closed** 2018-09-24 16:21 UTC
Labels: SEV2-high, area/che, priority/P4, team/che, team/che/ide1, type/bug
