### ISSUE TITLE
Menu disappear when user tries to use a beta feature

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3765] opened 2018-06-12 11:02 UTC
1. set your account to released features
2. create a space and navigate to space dashboard
3. click `Plan` or `Create -> Deployments` in top menu (both are beta features at the moment)

result:
* warning saying that this is a beta feature is displayed - this is expected
* top menu disappears so it's not possible to navigate back to space dashboard

![peek 2018-06-12 13-02](https://user-images.githubusercontent.com/445100/41286745-d7e6b7fa-6e40-11e8-9a88-338fb05bcef1.gif)

**Comment by joshuawilson** [comment] 2018-06-12 19:02
@openshiftio/uxd-team I would agree, it makes it hard to go back when you loose your menus if you don't want to opt-in.

**Comment by mindreeper2420** [comment] 2018-06-12 20:04
@corinnekrych are the feature toggles wrapping the navigation, or just only showing items when pages appear? Ideally, the Feature State should just block the content, not the navigation items.

**Comment by joshuawilson** [comment] 2018-06-20 13:36
@muruGanesan since what we have is in production, we need UX to confirm exactly what we need to change it to. The invision design has several differences. The navigation is present. The cover is transparent. 

Do we should a navigation item if the whole page is not available? If not, then what does it look like when you click a link to get there?

**Comment by joshuawilson** [comment] 2018-06-20 14:17
This isn't a SEV2 since it doesn't keep you from using things, it is more just annoying.

**Comment by catrobson** [comment] 2018-10-22 13:05
@serenamarie125 FYI

The menu should not change when we show the Beta screen.  The beta screen should be an overwrite of the page within the menu area.  We don't have any situations in OpenShift.io where we want to hide the navigation to a page because it is not GA, we always show all the navigation and then only hide the content unless they opt into that section/area of the UI.

**Comment by muruGanesan** [comment] 2018-10-23 09:40
Please find the UX recommendation for this issue:
https://redhat.invisionapp.com/share/HBOQ1IK7VMF#/327116757_3765_Beta_information
Please review the same and provide your feedback if any.

CC: @serenamarie125, @catrobson

**Comment by ppitonak** [comment] 2018-10-24 11:15
Joshua correctly pointed out that your design only solves part of the problem but IMHO that is exactly what this issue is about. We should probably create new issue for navigating from features page back to origin page.

**Comment by serenamarie125** [comment] 2018-11-08 16:46
Need to review with UI Dev

**Comment by christianvogt** [comment] 2018-11-19 17:19
@serenamarie125 I completely agree that the nav menu should be present at all times. I will update issue #3296 with my comments regarding the user flow.

**Comment by muruGanesan** [comment] 2018-12-06 06:32
@ppitonak, @joshuawilson, @christianvogt 
Please close this issue if it is captured and monitored by engineering team.

**Comment by ppitonak** [comment] 2018-12-06 10:47
@muruGanesan I agree with removing `team/UX` label but don't see a reason to close it until it's implemented and in production.

**Comment by joshuawilson** [comment] 2018-12-06 17:46
I'm going to close this as a duplicate of #3296 since the designs and work is being tracked there.

**Closed by joshuawilson** 2018-12-06 17:46 UTC
Labels: SEV3-medium, area/UX, area/feature flags, area/navigation, priority/P2, status/open-for-dev, team/ui, type/bug
