### ISSUE TITLE
Jenkins pods in terminating state for days

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4668] opened 2019-01-02 14:13 UTC
I've noticed that we have at least 3 user accounts with Jenkins stuck in terminating state for 19 - 20 days even thought the accounts are frequently reset. 

1. Can I delete those pods with my average user rights? If not, can anybody delete them?
2. Can we monitor all Jenkins pods in case they are in "bad" state? 

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2052/oc-jenkins-logs-before-all.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/4919/oc-jenkins-logs-before-all.txt
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/4917/oc-jenkins-logs-before-all.txt

**Comment by ppitonak** [comment] 2019-01-02 14:17
@aditya-konarde does your team monitor pods in terminating state? If not, would it make sense to start doing it?

**Comment by ljelinkova** [comment] 2019-01-07 13:10
Our E2E tests are failing constantly for user osio-ci-e2e-005 and the reset of environment does not help. I am changing to SEV1

```
---------- List all resources ----------------------
oc get all
NAME                  READY     STATUS        RESTARTS   AGE
pod/jenkins-1-hxng2   0/1       Terminating   1          3d
pod/jenkins-1-vsc6j   1/1       Running       0          20m

``` ---------- Get events ---------------
oc get events --sort-by='.lastTimestamp'
LAST SEEN   FIRST SEEN   COUNT     NAME                                                   KIND                    SUBOBJECT                                TYPE      REASON              SOURCE                                                 MESSAGE
1h          1h           1         jenkins-1.15778d476b798422                             ReplicationController                                            Normal    SuccessfulDelete    replication-controller                                 Deleted pod: jenkins-1-qqzls
1h          1h           1         jenkins-1-qqzls.15778d482d580378                       Pod                     spec.containers{jenkins}                 Normal    Killing             kubelet, ip-172-31-64-146.us-east-2.compute.internal   Killing container with id docker://jenkins:Need to kill Pod
1h          1h           1         jenkins.15778d48a6d0266b                               DeploymentConfig                                                 Normal    DeploymentCreated   deploymentconfig-controller                            Created new replication controller "jenkins-1" for version 1
1h          1h           1         jenkins-1-deploy.15778d48ac8184fd                      Pod                                                              Normal    Scheduled           default-scheduler                                      Successfully assigned osio-ci-e2e-005-jenkins/jenkins-1-deploy to ip-172-31-64-11.us-east-2.compute.internal
1h          1h           1         jenkins-1-deploy.15778d494708eac5                      Pod                     spec.containers{deployment}              Normal    Pulling             kubelet, ip-172-31-64-11.us-east-2.compute.internal    pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.11.43"
1h          1h           1         jenkins-1-deploy.15778d4b156eb03d                      Pod                     spec.containers{deployment}              Normal    Created             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Created container
1h          1h           1         jenkins-1-deploy.15778d4b0d1b13d8                      Pod                     spec.containers{deployment}              Normal    Pulled              kubelet, ip-172-31-64-11.us-east-2.compute.internal    Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.11.43"
1h          1h           1         jenkins-1.15778d4b453e1134                             ReplicationController                                            Normal    SuccessfulCreate    replication-controller                                 Created pod: jenkins-1-nnfgw
1h          1h           1         jenkins-1-nnfgw.15778d4b4574c810                       Pod                                                              Normal    Scheduled           default-scheduler                                      Successfully assigned osio-ci-e2e-005-jenkins/jenkins-1-nnfgw to ip-172-31-64-146.us-east-2.compute.internal
1h          1h           1         jenkins-1-deploy.15778d4b2ecb59b9                      Pod                     spec.containers{deployment}              Normal    Started             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Started container
1h          1h           1         jenkins-1-nnfgw.15778d4c21e99868                       Pod                     spec.containers{jenkins}                 Normal    Pulling             kubelet, ip-172-31-64-146.us-east-2.compute.internal   pulling image "fabric8/jenkins-openshift:vb355188"
1h          1h           1         jenkins-1-nnfgw.15778d4caefaaf76                       Pod                     spec.containers{jenkins}                 Normal    Created             kubelet, ip-172-31-64-146.us-east-2.compute.internal   Created container
1h          1h           1         jenkins-1-nnfgw.15778d4ca817347d                       Pod                     spec.containers{jenkins}                 Normal    Pulled              kubelet, ip-172-31-64-146.us-east-2.compute.internal   Successfully pulled image "fabric8/jenkins-openshift:vb355188"
1h          1h           1         jenkins-1-nnfgw.15778d4cc3bc0b37                       Pod                     spec.containers{jenkins}                 Normal    Started             kubelet, ip-172-31-64-146.us-east-2.compute.internal   Started container
1h          1h           2         jenkins-1-nnfgw.15778d565aadfbb3                       Pod                     spec.containers{jenkins}                 Warning   Unhealthy           kubelet, ip-172-31-64-146.us-east-2.compute.internal   Readiness probe failed: Get http://10.130.105.21:8080/login: dial tcp 10.130.105.21:8080: connect: connection refused
1h          1h           5         jenkins-1-nnfgw.15778d5de7c13368                       Pod                     spec.containers{jenkins}                 Warning   Unhealthy           kubelet, ip-172-31-64-146.us-east-2.compute.internal   Readiness probe failed: HTTP probe failed with statuscode: 503
1h          1h           1         jenkins-1-deploy.15778d6f4dabb8c1                      Pod                     spec.containers{deployment}              Normal    Killing             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Killing container with id docker://deployment:Need to kill Pod
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4a97825c84             Pod                                                              Normal    Scheduled           default-scheduler                                      Successfully assigned osio-ci-e2e-005-jenkins/jenkins-slave-zfcs5-t74qb to ip-172-31-67-104.us-east-2.compute.internal
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4b0b21c628             Pod                     spec.containers{maven}                   Normal    Pulling             kubelet, ip-172-31-67-104.us-east-2.compute.internal   pulling image "openshift/jenkins-slave-maven-centos7:v4.0"
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4ba8188517             Pod                     spec.containers{jnlp}                    Normal    Pulling             kubelet, ip-172-31-67-104.us-east-2.compute.internal   pulling image "openshift/jenkins-slave-base-centos7:v4.0"
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4b98b91dd9             Pod                     spec.containers{maven}                   Normal    Created             kubelet, ip-172-31-67-104.us-east-2.compute.internal   Created container
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4b93e7fbf1             Pod                     spec.containers{maven}                   Normal    Pulled              kubelet, ip-172-31-67-104.us-east-2.compute.internal   Successfully pulled image "openshift/jenkins-slave-maven-centos7:v4.0"
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4ba7ca0183             Pod                     spec.containers{maven}                   Normal    Started             kubelet, ip-172-31-67-104.us-east-2.compute.internal   Started container
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4c7421a92d             Pod                     spec.containers{jnlp}                    Normal    Pulled              kubelet, ip-172-31-67-104.us-east-2.compute.internal   Successfully pulled image "openshift/jenkins-slave-base-centos7:v4.0"
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4c8661b8a2             Pod                     spec.containers{jnlp}                    Normal    Started             kubelet, ip-172-31-67-104.us-east-2.compute.internal   Started container
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e4c7a115185             Pod                     spec.containers{jnlp}                    Normal    Created             kubelet, ip-172-31-67-104.us-east-2.compute.internal   Created container
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e79b9506802   Pod                                                              Normal    Scheduled           default-scheduler                                      Successfully assigned osio-ci-e2e-005-jenkins/booster-mission-runtime-s2i-1-build to ip-172-31-64-11.us-east-2.compute.internal
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7a4b116aa1   Pod                     spec.initContainers{git-clone}           Normal    Pulling             kubelet, ip-172-31-64-11.us-east-2.compute.internal    pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-docker-builder:v3.11.43"
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7a666b9e23   Pod                     spec.initContainers{git-clone}           Normal    Created             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Created container
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7a6164aa2b   Pod                     spec.initContainers{git-clone}           Normal    Pulled              kubelet, ip-172-31-64-11.us-east-2.compute.internal    Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-docker-builder:v3.11.43"
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7a74b395c1   Pod                     spec.initContainers{git-clone}           Normal    Started             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Started container
1h          1h           1         booster-mission-runtime-s2i-1.15778e7aa077bf4a         Build                                                            Normal    BuildStarted        build-controller                                       Build osio-ci-e2e-005-jenkins/booster-mission-runtime-s2i-1 is now running
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7b2e1b8779   Pod                     spec.initContainers{manage-dockerfile}   Normal    Pulling             kubelet, ip-172-31-64-11.us-east-2.compute.internal    pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-docker-builder:v3.11.43"
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7b900d2588   Pod                     spec.initContainers{manage-dockerfile}   Normal    Pulled              kubelet, ip-172-31-64-11.us-east-2.compute.internal    Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-docker-builder:v3.11.43"
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7ba2659dfa   Pod                     spec.initContainers{manage-dockerfile}   Normal    Started             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Started container
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7b955bbc0e   Pod                     spec.initContainers{manage-dockerfile}   Normal    Created             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Created container
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7bea96992f   Pod                     spec.containers{sti-build}               Normal    Pulling             kubelet, ip-172-31-64-11.us-east-2.compute.internal    pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-docker-builder:v3.11.43"
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7c0fe21a91   Pod                     spec.containers{sti-build}               Normal    Started             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Started container
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7c02c47231   Pod                     spec.containers{sti-build}               Normal    Created             kubelet, ip-172-31-64-11.us-east-2.compute.internal    Created container
1h          1h           1         booster-mission-runtime-s2i-1-build.15778e7bfea6341f   Pod                     spec.containers{sti-build}               Normal    Pulled              kubelet, ip-172-31-64-11.us-east-2.compute.internal    Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-docker-builder:v3.11.43"
1h          1h           1         booster-mission-runtime-s2i-1.15778e8e5ee9313b         Build                                                            Normal    BuildFailed         build-controller                                       Build osio-ci-e2e-005-jenkins/booster-mission-runtime-s2i-1 failed
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e933de5ab2c             Pod                     spec.containers{jnlp}                    Normal    Killing             kubelet, ip-172-31-67-104.us-east-2.compute.internal   Killing container with id docker://jnlp:Need to kill Pod
1h          1h           1         jenkins-slave-zfcs5-t74qb.15778e9a27190f71             Pod                     spec.containers{maven}                   Normal    Killing             kubelet, ip-172-31-67-104.us-east-2.compute.internal   Killing container with id docker://maven:Need to kill Pod
20m         20m          1         jenkins-1.1577910e5ba3fd22                             ReplicationController                                            Normal    SuccessfulDelete    replication-controller                                 Deleted pod: jenkins-1-nnfgw
20m         20m          1         jenkins-1-nnfgw.1577910ec0446367                       Pod                     spec.containers{jenkins}                 Normal    Killing             kubelet, ip-172-31-64-146.us-east-2.compute.internal   Killing container with id docker://jenkins:Need to kill Pod
20m         20m          1         jenkins.1577910fadc958c5                               DeploymentConfig                                                 Normal    DeploymentCreated   deploymentconfig-controller                            Created new replication controller "jenkins-1" for version 1
20m         20m          1         jenkins-1-deploy.1577910fb343e3eb                      Pod                                                              Normal    Scheduled           default-scheduler                                      Successfully assigned osio-ci-e2e-005-jenkins/jenkins-1-deploy to ip-172-31-66-255.us-east-2.compute.internal
20m         20m          1         jenkins-1-deploy.15779110611cdddf                      Pod                     spec.containers{deployment}              Normal    Created             kubelet, ip-172-31-66-255.us-east-2.compute.internal   Created container
20m         20m          1         jenkins-1-deploy.157791105ad4b3bd                      Pod                     spec.containers{deployment}              Normal    Pulled              kubelet, ip-172-31-66-255.us-east-2.compute.internal   Successfully pulled image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.11.43"
20m         20m          1         jenkins-1-deploy.157791106e96c2d1                      Pod                     spec.containers{deployment}              Normal    Started             kubelet, ip-172-31-66-255.us-east-2.compute.internal   Started container
20m         20m          1         jenkins-1-deploy.1577911043c7ac7f                      Pod                     spec.containers{deployment}              Normal    Pulling             kubelet, ip-172-31-66-255.us-east-2.compute.internal   pulling image "registry.reg-aws.openshift.com:443/openshift3/ose-deployer:v3.11.43"
20m         20m          1         jenkins-1.157791109d978695                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-rnpfq" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.15779110b34cd969                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-lbmvt" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.157791108f2b2229                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-dr8p8" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.157791108807c5d3                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-zmf4h" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.1577911083aa386c                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-m96mz" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.1577911091d72772                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-rcpm6" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.157791108a6a394d                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-wrc9t" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.157791108d19c019                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-lq7hp" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.15779110dba63228                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 Error creating: pods "jenkins-1-h84hg" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1.157791112a04c519                             ReplicationController                                            Warning   FailedCreate        replication-controller                                 (combined from similar events): Error creating: pods "jenkins-1-xw62x" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
20m         20m          1         jenkins-1-vsc6j.15779111c67e23f0                       Pod                                                              Normal    Scheduled           default-scheduler                                      Successfully assigned osio-ci-e2e-005-jenkins/jenkins-1-vsc6j to ip-172-31-64-146.us-east-2.compute.internal
20m         20m          1         jenkins-1.15779111c60e1609                             ReplicationController                                            Normal    SuccessfulCreate    replication-controller                                 Created pod: jenkins-1-vsc6j
20m         20m          1         jenkins-1-vsc6j.15779112466f7bee                       Pod                     spec.containers{jenkins}                 Normal    Pulling             kubelet, ip-172-31-64-146.us-east-2.compute.internal   pulling image "fabric8/jenkins-openshift:vb355188"
19m         19m          1         jenkins-1-vsc6j.15779112c7c2bc06                       Pod                     spec.containers{jenkins}                 Normal    Created             kubelet, ip-172-31-64-146.us-east-2.compute.internal   Created container
19m         19m          1         jenkins-1-vsc6j.15779112c1a823a4                       Pod                     spec.containers{jenkins}                 Normal    Pulled              kubelet, ip-172-31-64-146.us-east-2.compute.internal   Successfully pulled image "fabric8/jenkins-openshift:vb355188"
19m         19m          1         jenkins-1-vsc6j.15779112d51e44ed                       Pod                     spec.containers{jenkins}                 Normal    Started             kubelet, ip-172-31-64-146.us-east-2.compute.internal   Started container
19m         19m          1         jenkins-1-vsc6j.1577911de78ade65                       Pod                     spec.containers{jenkins}                 Warning   Unhealthy           kubelet, ip-172-31-64-146.us-east-2.compute.internal   Readiness probe failed: Get http://10.130.105.38:8080/login: dial tcp 10.130.105.38:8080: connect: connection refused
17m         18m          5         jenkins-1-vsc6j.15779121e71d1b35                       Pod                     spec.containers{jenkins}                 Warning   Unhealthy           kubelet, ip-172-31-64-146.us-east-2.compute.internal   Readiness probe failed: HTTP probe failed with statuscode: 503
17m         17m          1         jenkins.157791330e4faebb                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-wrc9t" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.157791330953c437                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-zmf4h" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.1577913314b641b6                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       (combined from similar events): Error creating: pods "jenkins-1-xw62x" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.1577913310d57761                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-lq7hp" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.157791331133c520                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-dr8p8" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.1577913311a54aae                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-rcpm6" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.15779133122c4a5a                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-rnpfq" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.1577913313da2bd3                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-lbmvt" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.15779133144d7a22                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-h84hg" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
17m         17m          1         jenkins.1577913305fce6c7                               DeploymentConfig                                                 Warning   FailedCreate        jenkins-1-deploy                                       Error creating: pods "jenkins-1-m96mz" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2,limits.memory=1Gi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi
```
</details>

**Comment by aditya-konarde** [comment] 2019-01-07 13:38
@ppitonak we currently do not monitor the pods in 'terminating' state. But we've agreed to implement this check asap. I'll take a look at this tomorrow.

For the terminating pods: Jenkins idler can force delete them as noted in https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2495

@ljelinkova as a band-aid, I can manually force-delete the pods in the e2e test namespaces, but I think its a good idea to fix the root cause instead.

**Comment by aditya-konarde** [comment] 2019-01-07 13:38
I'll leave it upto you guys to decide, since development of the feature for idler to correctly terminate pods might take time.

**Comment by aditya-konarde** [comment] 2019-01-07 13:39
Related: https://github.com/fabric8-services/fabric8-jenkins-idler/issues/315

**Comment by ljelinkova** [comment] 2019-01-08 05:54
@aditya-konarde Please delete those pods manually. Do you need the list of users or can you find all pods for users starting osio-ci-e2e?

**Comment by jmelis** [comment] 2019-01-08 11:05
We have compiled the list of stuck pods, and raised to issue to ops. We have also let them know that those that are in e2e are very urgent.

**Comment by pbergene** [comment] 2019-01-10 09:44
This has been raised again and we were told someone would be looking at this shortly.

**Comment by ljelinkova** [comment] 2019-01-15 07:01
It seems that the pods are deleted, at least for out e2e accounts.

**Comment by GeorgeActon** [comment] 2019-01-15 13:39
@ljelinkova @pbergene If the pods are deleted should this be closed?

**Comment by ljelinkova** [comment] 2019-01-15 13:43
Could anybody from SD team (@riuvshin)  confirm if all affected pods have been deleted or only the e2e accounts?

Also, it would be also good to know why this "urgent" ops issue took 7 days.

**Comment by riuvshin** [comment] 2019-01-15 16:39
this seems can be closed as pods are removed.

**Closed by riuvshin** 2019-01-15 16:39 UTC
Labels: SEV1-urgent, area/e2e-tests, area/jenkins, priority/P1, team/service-delivery
