### ISSUE TITLE
Incorrect data on user profile page

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2280] opened 2018-02-16 09:52 UTC
Current logged in user - Raunak Bajpai
Profile page user - Pavel Macik
Github account linked to user - Raunak Bajpai
Openshift account linked to user - Pavel Macik

![screenshot from 2018-02-16 15-17-15](https://user-images.githubusercontent.com/34271052/36301974-bf8bf388-132c-11e8-8292-16987362bd99.png)

**Comment by joshuawilson** [comment] 2018-02-16 18:44
How do I reproduce that? I have only my info.

**Comment by alexeykazakov** [comment] 2018-02-16 22:56
Hm... Looks like some UI glitch.. Can you try hard refresh?

This is what I see when opening Pavel's profile page:

![scr](https://user-images.githubusercontent.com/620087/36332687-15487bf2-1328-11e8-810e-780b78b38d9e.png)

**Comment by Raunak1203** [comment] 2018-02-19 10:48
@alexeykazakov i tried hard refresh and now i cant see his profile but still i can see space which he created.
![screenshot from 2018-02-19 16-17-25](https://user-images.githubusercontent.com/34271052/36374168-6d9e1aea-1590-11e8-8a53-75cf785f7d16.png)

**Comment by alexeykazakov** [comment] 2018-02-19 19:05
That's OK. You are supposed to see spaces. All spaces in OSIO are currently public. You should not see some links/buttons/menu for spaces (at least where you are not a collaborator) like "add to space" or "import codebase" but it's another issue.

**Comment by joshuawilson** [comment] 2018-03-27 16:36
@rohitkrai03 is this fixed with the work you did?

**Comment by rohitkrai03** [comment] 2018-03-27 16:39
@joshuawilson Yes, this is fixed.

**Closed** 2018-03-27 18:22 UTC
Labels: SEV2-high, area/user/profile, team/platform, type/bug
