### ISSUE TITLE
Lower the memory limits for the workshop quickstarts

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#441] opened 2017-07-31 14:15 UTC
Lower the memory limit of Vert.x Basic and Healthcheck projects from 512MB to under 300MB. Lower the memory limit of Spring Boot Basic and Healthcheck projects from 512MB to under 300MB.   The goal is to allow end-users to run up to 3 pods (3 applications/3 codebases) in -stage and/or -run and still allow for rolling updates against any one of those 3 pods.

related to #442

**Comment by joshuawilson** [comment] 2017-07-31 19:51
According to @kbsingh, 256MiB is the min limit for ram per pod.

**Comment by burrsutter** [comment] 2017-08-03 15:01
Current theory on how to lower the memory limit on a per project basis.  Add a deployment.yaml with the following contents
https://gist.github.com/jstrachan/cf78febd625853b74bed2972e6f22fae

**Comment by burrsutter** [comment] 2017-08-03 15:11
I changed it to 268Mi based on the pod failing to start with this error
SEVERE: Unexpected exception in route
io.vertx.core.impl.NoStackTraceThrowable: Channel Unavailable
not sure if they were related but thought another test would at least cause a new deployment.
https://screencast.com/t/wxzcpV1XGT

**Comment by joshuawilson** [comment] 2017-08-03 15:47
Once we find the "right" limit, the goal is to apply it everyone, right?

**Comment by burrsutter** [comment] 2017-08-03 21:25
This seems to be working OK
https://github.com/burrsitis/hothvertxbasic1/blob/master/src/main/fabric8/deployment.yaml
https://github.com/burrsitis/hothspringbasic1/blob/master/src/main/fabric8/deployment.yml
https://github.com/burrsitis/hothvertxhealth1/blob/master/src/main/fabric8/deployment.yml

**Comment by burrsutter** [comment] 2017-08-03 23:59
More testing, I was able to squeeze 3 pods into a single -stage or -run based on this deployment.yml
https://github.com/burrsitis/hothspringbasic1/edit/master/src/main/fabric8/deployment.yml

For a single pod, here is the quota BEFORE the change
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  scopes:
  - NotTerminating
status:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  used:
    limits.cpu: "1"
    limits.memory: 512Mi

and the quota AFTER the change
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  scopes:
  - NotTerminating
status:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  used:
    limits.cpu: 500m
    limits.memory: 256Mi

**Comment by burrsutter** [comment] 2017-08-04 00:37
And DURING a deployment, you can see the used CPU and Memory for the Deployer pod
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  scopes:
  - NotTerminating
status:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  used:
    limits.cpu: 1500m
    limits.memory: 768Mi

**Comment by burrsutter** [comment] 2017-08-04 01:12
and it seems 250 is as low as you can go

``
spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            limits:
              memory: '250Mi'

**Comment by maxandersen** [comment] 2017-08-04 12:29
> and I do not know how to express yaml in this tool so it just looks oddly below

its markdown so you just add ``` before and after to allow quote. I've edited your comment so you can see.

**Comment by kbsingh** [comment] 2017-08-14 17:08
is #495 a dupe of this issue ?

**Comment by joshuawilson** [comment] 2017-08-15 02:27
@kbsingh this one is a request to lower the QS memory, whereas #495 wants to lower the available minimum so that this one can go that low.

**Comment by rawlingsj** [comment] 2017-08-25 08:54
I had two PRs merged https://github.com/snowdrop/spring-boot-http-booster/pull/56 https://github.com/openshiftio-vertx-boosters/vertx-http-booster/pull/15 and as far as I'm aware we're waiting for new tags to be created by the runtime teams so we can update our booster catalogue https://github.com/openshiftio/booster-catalog/tree/osio

**Comment by burrsutter** [comment] 2017-08-28 21:41
@rawlingsj if you see this "go in", please let me know so we can update the Workshop documentation accordingly.

**Comment by joshuawilson** [comment] 2017-09-07 04:14
@burrsutter @rawlingsj has this been done? Can we close this?

**Comment by bmicklea** [comment] 2017-09-10 23:47
@rawlingsj - is this now in prod?

**Comment by rawlingsj** [comment] 2017-09-11 10:33
I just tried a new vertx app and the old limits are still used.  Looking at the booster catalogue I guess we need to use the git tag 11 for vertx.  Not sure about the spring quickstart though as it looks like they've not released my change yet.  I'll raise an issue to see if we can move that along.  
My assumption is once we have the new tag I can PR the osio branch of the catalogue https://github.com/openshiftio/booster-catalog/blob/osio/rest-http/vert.x/vertx-http-booster.yaml and forge will pickup the new versions.. is that right @gastaldi?

**Comment by rawlingsj** [comment] 2017-09-11 10:35
issue requesting new spring boot quickstart release https://github.com/openshiftio/openshift.io/issues/441

**Comment by gastaldi** [comment] 2017-09-11 10:46
@rawlingsj yes, that's right

**Comment by rawlingsj** [comment] 2017-09-11 10:47
great, thanks @gastaldi

**Comment by gastaldi** [comment] 2017-09-13 13:46
Why is this issue assigned to me? I thought @rawlingsj was going to provide the PR for the osio branch?

**Comment by maxandersen** [comment] 2017-09-13 18:36
sorry - I understood from @rawlingsj he had opened te PR.. @rawlingsj did I hear it wrong today ?

**Comment by rawlingsj** [comment] 2017-09-13 20:13
@maxandersen as I said on the call this is waiting for the spring boot quickstart release as per the last comment I added to this issue https://github.com/openshiftio/openshift.io/issues/441#issuecomment-328490645

I said it's not for @gastaldi but for the person that looks after the spring boot quickstarts I don't know who that is and nobody is replying to that issue so not sure it's being maintained.

**Comment by gastaldi** [comment] 2017-09-13 20:43
You need the Snowdrop team (Charles Moulliard, Gytis, etc). Ping them in
the obsidian-toaster.slack.com, #2-springboot channel

Best Regards,



George Gastaldi

Principal Software Engineer

Red Hat <https://www.redhat.com>

Remote

Joinville - Santa Catarina

ggastald@redhat.com    M: +55-47-99711-1000
<https://red.ht/sig>
TRIED. TESTED. TRUSTED. <https://redhat.com/trusted>
@redhatnews <https://twitter.com/redhatnews>   Red Hat
<https://www.linkedin.com/company/red-hat>   Red Hat
<https://www.facebook.com/RedHatInc>

**Comment by rafabene** [comment] 2017-09-14 16:43
Following as this impact the workshop time....

**Comment by joshuawilson** [comment] 2017-09-27 05:10
What is the status on this?

**Comment by rawlingsj** [comment] 2017-09-27 11:32
Waiting for a tag of the springboot quickstart https://github.com/snowdrop/spring-boot-http-booster/issues/59#issuecomment-332492237 then we can add it to our catalogue https://github.com/openshiftio/booster-catalog/tree/osio

**Comment by joshuawilson** [comment] 2017-10-11 06:16
Were you able to get what you needed?

**Comment by rafabene** [comment] 2017-11-29 15:13
I don't see it in production yet. Shouldn't it be closed only when it lands on production a be verified?

**Comment by joshuawilson** [comment] 2017-12-07 02:51
Reopening until proven fixed.

**Comment by joshuawilson** [comment] 2017-12-07 02:52
Who is working this and what is the status?

**Comment by gastaldi** [comment] 2017-12-07 04:02
I don't understand why the `launchpad.backend.catalog.git.ref` is set to `devtools-saas`. That branch does not exist in the booster catalog, unless there is some magic going on. Can you clarify @jstrachan?

**Comment by gastaldi** [comment] 2017-12-07 04:08
Unless the gitRef information is being sent from the UI as a HTTP Header parameter. Is that the case @edewit @corinnekrych?

**Comment by maxandersen** [comment] 2017-12-07 05:43
> I don't understand why the launchpad.backend.catalog.git.ref is set to devtools-saas. That branch does not exist in the booster catalog, unless there is some magic going on. Can you clarify @jstrachan?

where are you looking and seeing this ref set @gastaldi ?

**Comment by edewit** [comment] 2017-12-07 08:19
gitRef is not added as http parameter by the frond-end

**Comment by corinnekrych** [comment] 2017-12-07 09:02
@gastaldi @edewit i think it is set as env variable here: https://github.com/fabric8io/generator-backend/blob/master/run.sh#L2

**Comment by gastaldi** [comment] 2017-12-07 11:32
@maxandersen I am seeing in the generator-backend configmap in the openshift console.

@corinnekrych that makes sense. The latest version is v15, I'll provide a PR changing that

**Comment by qodfathr** [comment] 2018-01-17 13:37
Lots of associated issues have been closed. May this be closed? cc: @maxandersen @joshuawilson @gastaldi @corinnekrych

**Comment by gastaldi** [comment] 2018-01-17 13:40
Closing issue. Reopen if the problem persists

**Closed by gastaldi** 2018-01-17 13:40 UTC
Labels: area/quickstarts, team/build-cd, team/launcher, team/service-delivery, type/feature
