### ISSUE TITLE
Overlapping text in Che editor

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#503] opened 2017-08-09 05:34 UTC
Observed overlapping text in Che editor when the workspace was loaded. Notice the red X icon on the vertx project, indicating https://github.com/redhat-developer/rh-che/issues/230:

https://drive.google.com/open?id=0BwLIZeed5jyKQzg1WmRKWThtTUk

This issue is intermittent in nature and cannot be reproduced at will, at least as of now.

**Comment by l0rd** [comment] 2017-08-25 16:44
@eivantsov are you aware of any issue of this kind?

**Comment by eivantsov** [comment] 2017-08-27 15:06
@l0rd it looks like the file was opened twice somehow. This is a similar issue in Che and I have reopened it https://github.com/eclipse/che/issues/4952

**Comment by l0rd** [comment] 2017-09-27 17:25
@eivantsov @rgarg1 does this issue still exist? If yes how can we reproduce it?

**Comment by l0rd** [comment] 2017-09-28 08:51
@l0rd <https://github.com/l0rd> yes, it can be reproduced in Che

How? :-)

**Comment by eivantsov** [comment] 2017-09-28 09:07
https://github.com/eclipse/che/issues/4952 when trying to open the same file twice

**Comment by eivantsov** [comment] 2017-10-04 08:19
Should be fixed by https://github.com/eclipse/che/pull/6478

**Comment by joshuawilson** [comment] 2017-10-11 03:15
Can we close this?

**Comment by eivantsov** [comment] 2017-10-11 04:15
I think so. The issue's fixed in the upstream.

**Closed** 2017-10-11 04:47 UTC
Labels: area/che, team/che
