### ISSUE TITLE
Editing comment in Planner resulted in screen corruption

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3688] opened 2018-05-30 18:15 UTC
Steps to recreate:
* I added a comment to https://openshift.io/openshiftio/openshiftio/plan/detail/2112
* After saving the comment, clicking on the edit/cancel button produced this display:
![screenshot from 2018-05-30 13-54-54](https://user-images.githubusercontent.com/642621/40739215-897a95d2-6413-11e8-8548-bc53b721e165.png)

I have not been able to recreate this issue with other workitems. In further editing of https://openshift.io/openshiftio/openshiftio/plan/detail/2112, I have also seen this:

![screenshot from 2018-05-30 14-14-02](https://user-images.githubusercontent.com/642621/40739266-b9ca402a-6413-11e8-8398-6db023777fea.png)

**Comment by nimishamukherjee** [comment] 2018-06-07 05:46
@rgarg1 can you replicate this issue?

**Comment by rgarg1** [comment] 2018-06-07 09:48
@nimishamukherjee I cannot reproduce this issue. Looks like a corner case for which, we don't know the trigger.

**Comment by nimishamukherjee** [comment] 2018-11-21 16:55
Closing as the issue is not reproducible.
@ldimaggi please re-open if you face this issue again.

**Closed by nimishamukherjee** 2018-11-21 16:55 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
