### ISSUE TITLE
WebHook: new build is not showing on pipeline screen.

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3047] opened 2018-04-12 10:48 UTC
Merge to master is triggering the build. In the background, Jenkins is running and deployed the modified application but I'm not able to see the latest build on pipeline screen.

![screen1](https://user-images.githubusercontent.com/11839674/38672690-927752f0-3e6c-11e8-8735-5046b4b2ef42.png)
![screen2](https://user-images.githubusercontent.com/11839674/38672709-a3a912a2-3e6c-11e8-81c5-68285e88f2b6.png)

**Comment by ravsa** [comment] 2018-05-07 07:29
This issue is dependent on the resolution of https://github.com/openshiftio/openshift.io/issues/3095 and will be fixed once the duplicate pipeline issue will be fixed.

**Comment by sunilk747** [comment] 2018-05-28 10:15
With the fix for duplicate pipeline issue this issue is resolved also. I couldn't reproduced this issue. Hence, closing it.

**Closed by sunilk747** 2018-05-28 10:15 UTC
Labels: SEV3-medium, area/app-wizard, area/launcher, team/analytics/wizard, type/bug
