### ISSUE TITLE
Space Creation - No indication when we create a duplicate space

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1541] opened 2017-12-08 08:52 UTC
![duplicatespace](https://user-images.githubusercontent.com/1892722/33757989-5e592992-dbf4-11e7-9f4c-b568f3d33eba.gif)

When I create a duplicate space name, there is no visual indicator that I have created a duplicate space.
We only get a toast notification stating failed to create space and the option to proceed with the regular flow.

**Comment by joshuawilson** [comment] 2017-12-08 15:11
I don't see this issue, it keeps me from creating one that I have. Can you please confirm that you are creating a space that already exists on your account. Do you have a `My_Test_Space` space? I wonder if it failed for another reason.

**Comment by adisakala** [comment] 2017-12-09 19:14
@joshuawilson try creating a space with spaces in the name. Eg: My Test Space
you will reproduce it.

**Comment by alexeykazakov** [comment] 2017-12-09 20:16
I can't reproduce it.
I already have "mywork" space. And I can't create another "mywork" space. The wizard doesn't allow me to do so.
But I can create "my work" space which is created as "my_work". And if I try to create "my work" space or "my_work" again the wizard doesn't allow me because I already have one.
Then I successfully created "my work space" space which was created as "my_work_space"

Could you please provide exact steps to reproduce the problem? In your video/gif it's not clear if you are creating a duplicate space or a different one and if failed for another reason.

**Comment by nimishamukherjee** [comment] 2017-12-11 05:32
![duplicatespace](https://user-images.githubusercontent.com/1892722/33816789-76af291a-de33-11e7-841f-4a934078d735.gif)

@joshuawilson @alexeykazakov I notice a different behaviour today.

I have two spaces 
Test Space
Test Space Nimisha

1. Click on + to create a new space
2. Enter Test Space as the space name
3. I get a "Duplicate Name" error message
4. I enter the space name as Test Space Nimisha
5. Create button gets enabled
6. Click on Create
7. Failed to create space error message is displayed.


The error messaging system needs to be consistent.
From an experience perspective, the duplicate name error message makes sense.

The original intent of this issue was to make the Failed toast notification more informative by letting the user know that he had created a duplicate space.

**Comment by ppitonak** [comment] 2017-12-11 12:41
I can reproduce this issue, too. It seems that two spaces cause the issue.

**Comment by ldimaggi** [comment] 2017-12-11 12:44
Pavol - is the issue related to having one or more space characters in the OSIO space name?

**Comment by ppitonak** [comment] 2017-12-11 12:52
It doesn't matter if you create "Test Space X" (word, space, word, space, word) or "Test  Space" (word, space, space, word) - both are broken.

**Comment by alexeykazakov** [comment] 2017-12-11 19:58
OK, I was able to reproduce it too now. The wizard validation is not working well with spaces with names with spaces.
It works fine for me if there is one space in the name and doesn't work if there are two space characters in the name and there is a space with the same name already.

**Comment by andrewazores** [comment] 2018-05-24 14:09
Is this still valid? I think this wizard is being (has been?) phased out.

**Comment by joshuawilson** [comment] 2018-05-24 15:07
this is fixed in the new wizard, closing

**Closed by joshuawilson** 2018-05-24 15:07 UTC
Labels: SEV3-medium, area/space-wizard, area/spaces, team/platform, type/bug
