### ISSUE TITLE
'Add codebase' button become inactive

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#3080] opened 2018-04-12 14:57 UTC
'Add codebase' button become inactive, see the picture below. The rest of UI is active, for instance I can add a pipeline, etc...

![addcodebase](https://user-images.githubusercontent.com/26871874/38685573-80288b68-3e72-11e8-9c9f-08ccf64a0271.png)

**Comment by corinnekrych** [comment] 2018-04-12 17:12
duplicate of https://github.com/openshiftio/openshift.io/issues/3100

**Closed by corinnekrych** 2018-04-12 17:12 UTC
Labels: team/platform
