### ISSUE TITLE
Unable to create a new quickstart project 

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#1504] opened 2017-12-05 06:01 UTC
On  openshift.io when I try to create a new space and then a new quickstart project I get an error as follows 

![quickstart-wizard-failed2017-12-05 15-19-49](https://user-images.githubusercontent.com/3005132/33592059-afe3d996-d9d4-11e7-9b6a-05772cf93f57.png)

Further inspection revealed that the following http request failed 
https://forge.api.openshift.io/forge/commands/fabric8-new-project/execute with headers set to 
```
POST /forge/commands/fabric8-new-project/execute HTTP/1.1
Host: forge.api.openshift.io
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: https://openshift.io
Authorization: Bearer ....... 
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
content-type: application/json
DNT: 1
Referer: https://openshift.io/sunil.thaha/testDec0501
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
```

failed with the following error

```json
{
  "type": "java.lang.IllegalStateException",
  "message": "Could not register resource monitor",
  "localizedMessage": "Could not register resource monitor",
  "forgeVersion": "3.6.1.Final",
  "stackTrace": [
    {
      "line": 107,
      "class": "org.jboss.forge.addon.resource.monitor.FileMonitor",
      "file": "FileMonitor.java",
      "method": "registerMonitor"
    },
    {
      "line": -1,
      "class": "sun.reflect.GeneratedMethodAccessor437",
      "method": "invoke"
    },
    {
      "line": 43,
      "class": "sun.reflect.DelegatingMethodAccessorImpl",
      "file": "DelegatingMethodAccessorImpl.java",
      "method": "invoke"
    },
    ....
    ]
  }
}
```

after which https://forge.api.openshift.io/forge/commands/fabric8-new-project/execute fails with

```
HTTP/1.1 412 Precondition Failed
```
and the response body is 
```
{"messages":[{"description":"The repository testdec0501 already exists!","severity":"ERROR","input":"named"}]}
```

**Comment by aditya-konarde** [comment] 2017-12-05 11:53
In addition to this, a repository is actually created on the GitHub account.

**Comment by ldimaggi** [comment] 2017-12-05 12:15
Already reported here:  https://github.com/openshiftio/openshift.io/issues/1503

**Comment by maxandersen** [comment] 2017-12-05 12:18
closing as a duplicate of #1503

**Closed by maxandersen** 2017-12-05 12:18 UTC
Labels: SEV1-urgent
