### ISSUE TITLE
Jenkins.openshift.io is not accessible

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#4736] opened 2019-01-28 10:47 UTC
Jenkins proxy is keep thowing 
```
"{"Errors":[{"code":"500","detail":"Error when logging into jenkins: Get https://jenkins-pradkuma-preview2-jenkins.b542.starter-us-east-2a.openshiftapps.com/securityRealm/commenceLogin?from=%2F: EOF"}]}"
```
```
{"cluster":"https://api.starter-us-east-2a.openshift.com/","component":"proxy","error":"Error when logging into jenkins: Get https://jenkins-kbaig-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/securityRealm/commenceLogin?from=%2F: EOF","level":"error","location":" github.com/fabric8-services/fabric8-jenkins-proxy/internal/proxy.(*Proxy).handleJenkinsUIRequest[/root/go/src/github.com/fabric8-services/fabric8-jenkins-proxy/internal/proxy/ui_requests.go:94]","msg":"Error Handling proxy request request.","ns":"kbaig-preview-jenkins","part":"token_json","request-hash":2176181442,"time":"2019-01-28T07:31:42Z"}
```
May be this on is related https://github.com/openshiftio/openshift.io/issues/4735

**Comment by pbergene** [comment] 2019-01-28 11:12
Looks to possible be a result of #4735 #4738

**Comment by piyush-garg** [comment] 2019-01-28 12:59
Closing this as the duplicate of #4735 Will repone if that does not resolve this.

**Closed by piyush-garg** 2019-01-28 12:59 UTC
Labels: SEV1-urgent, priority/P1, team/build-cd, team/platform, type/bug

**Comment by piyush-garg** [comment] 2019-01-29 10:57
This has been resolved for cluster 2 with https://github.com/openshiftio/openshift.io/issues/4739#issuecomment-458496671 and for cluster 2a they are already working on #4735
