### ISSUE TITLE
Link to Recent Active Pipeline does not work

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3866] opened 2018-06-26 11:24 UTC
When you go to Account home and click some of the recent pipelines, you get _404: You've found something, but not the page you're looking for._ It seems that the linked URL contains the space twice.

`https://openshift.io/ljelinko@redhat.com/My_space/My_space/create/pipelines`

When I manually change the link to the following it works

`https://openshift.io/ljelinko@redhat.com/My_space/create/pipelines`

**Comment by jiekang** [comment] 2018-06-26 12:46
Possible duplicate of: https://github.com/openshiftio/openshift.io/issues/3841

See also: https://github.com/fabric8-ui/fabric8-ui/pull/3071

**Comment by piyush1594** [comment] 2018-06-27 07:14
@jiekang Can we close this as other issue is closed

**Closed as completed** 2018-06-27 13:27 UTC
Labels: type/bug, area/dashboard
