### ISSUE TITLE
Delete option is present in Applications view - but it fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#486] opened 2017-08-08 15:20 UTC
See attached screenshot - the user has access to a delete option in the Applications view:

![screenshot from 2017-08-08 11-18-45](https://user-images.githubusercontent.com/642621/29079510-5d8f1afe-7c2b-11e7-86b1-d72e250b7ca2.png)

Attempting to delete a deployment fails with this error:

```
patternfly.min.css:1 ERROR SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at CatchSubscriber.selector (main.0c8809c….bundle.js:1)
    at CatchSubscriber.error (patternfly.min.css:1)
    at MapSubscriber.Subscriber._error (patternfly.min.css:1)
    at MapSubscriber.Subscriber.error (patternfly.min.css:1)
    at MapSubscriber.Subscriber._error (patternfly.min.css:1)
    at MapSubscriber.Subscriber.error (patternfly.min.css:1)
    at XMLHttpRequest.a (main.0c8809c….bundle.js:1)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Object.onInvokeTask (patternfly.min.css:1)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Zone.runTask (polyfills.f49acb8….bundle.js:1)
    at XMLHttpRequest.ZoneTask.invoke (polyfills.f49acb8….bundle.js:1)
```

We should remove this from the UI until it works. Thx!

**Comment by joshuawilson** [comment] 2017-08-09 16:59
We have several stories related to deleting. This will get picked up in one of those.

**Comment by jiekang** [comment] 2017-11-21 17:18
I tested this today and this functionality works for me on OSIO Production with space name 'arst' and application named 'osio-vertx'. I also verified through OSO that the deployment configurations are actually deleted and through OSIO that running the pipeline again successfully recreates the expected deployments.

Closing as fixed. If this issue can be reproduced, feel free to reopen with more details.

**Closed by jiekang** 2017-11-21 17:18 UTC
Labels: area/applications, area/deployments, kind/bug, SEV2-high, team/build-cd

**Comment by jiekang** [comment] 2017-12-11 21:53
Under: #287
