### ISSUE TITLE
Cannot promote application on cluster 2

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4739] opened 2019-01-28 11:29 UTC
When e2e tests try to promote application, the Promote button is not enabled (wait time is 10 minutes)

![Pipelines screenshot](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1496/05-04-pipeline-failed.png)

I can see many SEVERE logs in browser log

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1496/05-04-pipeline-failed.log

Here are oc logs
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1496/oc-jenkins-logs.txt

**Comment by piyush-garg** [comment] 2019-01-28 11:30
#4737 is also because of same issue

**Comment by piyush-garg** [comment] 2019-01-28 13:01
Even GitHub webhook events are also not working on prod cluster 2. That issue has also been reported which is #4737 I am closing that as a duplicate of this.

**Comment by piyush-garg** [comment] 2019-01-29 10:54
This seems to be like an issue happened because of token expiry. We have redeployed the idler in prod and updated the proxy in prod because it caches the token and uses same till restart. It seems working fine now, I checked with my account also. I am closing this issue, please reopen if it still happens for you.

Thanks, @alexeykazakov @hrishin for the help.

**Closed by piyush-garg** 2019-01-29 10:54 UTC
Labels: SEV1-urgent, area/e2e-tests, area/pipelines, priority/P1, team/build-cd, type/bug

**Comment by pbergene** [comment] 2019-01-29 10:56
I don't think the token was ever actually cycled?

**Comment by piyush-garg** [comment] 2019-01-29 11:01
@pbergene As per comment https://github.com/openshiftio/openshift.io/issues/4708#issuecomment-454334473, the token was updated 14 days back, and idler instance was restarted 19 days back. we have concluded the same and asked for a restart. cc @hrishin @alexeykazakov

**Comment by ljelinkova** [comment] 2019-01-29 12:10
I tried manually and the promote worked on cluster 2.
