### ISSUE TITLE
Overpopulated title field in detailed view can prohibit viewing the work item

### ISSUE THREAD

**Issue by tinakurian** [openshiftio/openshift.io#4058] opened 2018-07-24 04:08 UTC
The title field does not appear to have any cap on the amount of text which can be entered. If large amounts of text are entered, no scroll bar appears and the user is unable to see the rest of the work item. 

Ideally, the title field should be capped in size. Titles shouldn't contain large paragraphs of text. 

![titleoverpopulated](https://user-images.githubusercontent.com/40298444/43116621-aba3f048-8ed6-11e8-9228-34f11ce47046.png)

**Comment by kwk** [comment] 2018-07-25 13:42
@nimishamukherjee @tisnik for the title in particular I think we could do it similar to github does it when you create PR. 

When you create a PR with a very long title and some text in the description field:

This is the title of the commit:

> Before the title was called "Debugging" and I think this was a leftover from a previous of this document. Let's see how Github converts this message from a very long title line into a short PR title with the rest stored in the description even if the description already contained some text.

![bildschirmfoto von 2018-07-25 15-37-02](https://user-images.githubusercontent.com/193408/43204255-ae1ce82a-9020-11e8-96df-3ba707d7a2a4.png)

Your PR will have a shorter title, namely

> Before the title was called "Debugging" and I think this was a leftov…

 and the rest of it is put in the beginning of the description:

> …er from a previous of this document. Let's see how Github converts this message from a very long title line into a short PR title with the rest stored in the description even if the description already contained some text.

![bildschirmfoto von 2018-07-25 15-37-17](https://user-images.githubusercontent.com/193408/43204302-cdaf2068-9020-11e8-8595-4e66ac5c2f54.png)

**Comment by joshuawilson** [comment] 2018-10-31 16:53
Duplicate of #1595

**Comment by nimishamukherjee** [comment] 2018-11-09 07:50
Closing this as it is a duplicate. Referenced this issue in #1595 to retain the recommendations.

**Closed by nimishamukherjee** 2018-11-09 07:50 UTC
Labels: SEV3-medium, area/planner, area/planner/item-details, priority/P3, team/planner, team/ui, type/bug
