### ISSUE TITLE
Unable to check all available repos to add codebase

### ISSUE THREAD

**Issue by camilamacedo86** [openshiftio/openshift.io#1848] opened 2018-01-10 13:32 UTC
# Problem Description
**WHAT:** Unable to check all available repos to select 
**WHERE:** Add new code base popup  
**WHEN:** Try to add/import new code base to a space
**BEHAVIOUR CHECKED AT:** 10/jan/2018

# Steps to reproduce:
1. Openshift.io home >> click on the drop-down in the left top >> Create space >> And create a new space
2. Go to the home space via  
    2.1 click on the drop-down inot the left top
    2.2 select the space 
3. Click on the button "Add codebases"

# Result:
<img width="1266" alt="screen shot 2018-01-10 at 1 35 38 pm" src="https://user-images.githubusercontent.com/7708031/34775307-95801b26-f60a-11e7-9615-dda19228755a.png">

# Expected Behaviour:

<img width="911" alt="screen shot 2018-01-10 at 12 12 40 pm" src="https://user-images.githubusercontent.com/7708031/34775322-a96b14b0-f60a-11e7-8f0d-236b9228f771.png">

This area should use the same component of the Wizard.

**Comment by qodfathr** [comment] 2018-01-27 20:22
Thanks, @camilamacedo86. I agree that this is messy. I'm going to change to `type/feature`, simply because it is working as designed (even if the design is bad), so it's technically not a bug. That being said, there is an active discussion to address this. (e.g. see here: https://github.com/openshiftio/openshift.io/issues/1707#issuecomment-360993231 and #1576 .)

Moving to `team/platform` as the issue is with the Codebases screen, not the App Wizard.

**Comment by jiekang** [comment] 2018-06-20 16:29
This add codebase feature no longer exists. Closing.

**Closed by jiekang** 2018-06-20 16:29 UTC
Labels: area/app-wizard, team/platform, type/SDD-feature
