### ISSUE TITLE
Intermittent, but frequent (~30% of the time) failure to generate a post build Analytics report

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2323] opened 2018-02-21 19:05 UTC
Seeing this with both manual and automated tests - after the successful conclusion of a build pipeline, an Analytics report fails to be generated about 30% of the the time. 

Steps to recreate:
* Create a new space and new quickstart
* Observe the quickstart's build pipeline complete successfully
* Observe that an Analytics report is not generated:

![screenshot from 2018-02-21 12-16-46](https://user-images.githubusercontent.com/642621/36499704-1e0f42b6-1710-11e8-9548-2f4b07bd607a.png)

Seeing this in production - https://openshift.io

**Comment by ldimaggi** [comment] 2018-02-21 20:27
No errors are displayed to the user. How can we debug this?

**Comment by tisnik** [comment] 2018-02-22 09:15
Hi @ldimaggi. This seems to be related to https://github.com/openshiftio/openshift.io/issues/2330

**Comment by tisnik** [comment] 2018-02-22 10:02
@samuzzal-choudhury FYI: ^

**Comment by krishnapaparaju** [comment] 2018-02-22 12:40
This is caused by CORS support 'not working consistently'  at recommender API. CORS support (a separate Flask module for CORS is not consistent). In the instances where CORS module is not working as expected, required HTTP response headers would not contain 'Access-Control-Allow-Origin' to let APIs at 'recommender.api.openshifio.*' be called from OSIO space dashboard 'https://openshift.io'. 

This is sample HTTP 504 error code causing this issue: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.



This is fixed with removing CORS module of Flask application and explicitly setting the required HTTP response headers for enabling CORS support.

After this fix, 20 * 100 = 2000 new stack analysis requests been initiated along with 3000 GETs on existing stack analysis reports (used from space dashboard, pipelines screens), results look satisfactory with NO single 504 error been observed.  All these changes promoted to production...

**Closed by krishnapaparaju** 2018-02-22 12:40 UTC
Labels: SEV2-high, area/analytics, team/analytics, type/bug

**Comment by miteshvp** [comment] 2018-02-23 12:33
@krishnapaparaju - Just an update, even with reversal of CORS module, we did not observe  504 error codes till the wsgi process was killed and restarted. 
AJAX calls generate a preflight message to contact the server. Chances are during one of those preflight messages, process went down resulting in the response seen 
`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.`

Having said that, two observations are noteworthy though
1. With removal of CORS module and setting required headers explicitly resulted in faster response times (Maybe use of CORS module adds some overhead)
2. Wsgi process getting killed and restarted (maybe under load) was double while using CORS module

**Comment by ldimaggi** [comment] 2018-02-23 16:06
I can't verify that this bug is fixed until this blocking bug is also fixed - https://github.com/openshiftio/openshift.io/issues/2341

**Comment by ldimaggi** [comment] 2018-02-27 13:03
Issue found/encountered by EE tests.
