### ISSUE TITLE
Unable to delete pipelines

### ISSUE THREAD

**Issue by debianmaster** [openshiftio/openshift.io#307] opened 2017-06-29 23:17 UTC
How to replicate:
Create -> Pipelines ->  Select pipeline -> Select `Delete` from Popup
EX:- https://openshift.io/cjonagam-io/test/create/pipelines 

Expected:
Pipeline should be deleted

Actual result:
Pipeline is not getting deleted nor any showing any acknowledgement.

**Comment by debianmaster** [comment] 2017-06-29 23:19
This may be because of stale records.   should order of deleting of objection matter?

**Comment by joshuawilson** [comment] 2017-07-04 02:08
The feature, to delete, has not be implemented yet.

**Comment by joshuawilson** [comment] 2017-07-04 02:10
This issue was moved to fabric8-services/fabric8-wit#1464

**Comment by joshuawilson** [comment] 2017-07-04 02:12
Duplicate of https://github.com/fabric8-ui/fabric8-ui/issues/1355

**Closed** 2018-01-12 21:14 UTC
Labels: area/pipelines, team/platform, type/bug
