### ISSUE TITLE
Too much whitespaces in the Planner views

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2413] opened 2018-03-02 08:06 UTC
The Planner views have too much of the whitespace all around, and the view could be further condensed to pack more information on the screen. This is just an observation; final decision lies with UX.

![backlog view](https://user-images.githubusercontent.com/28748448/36889158-b060896c-1e1e-11e8-93f0-9fde7327a7a8.png)

**Comment by joshuawilson** [comment] 2018-03-02 14:19
@rgarg1 if you know the issue is UX related then you need to use the correct labels. You may also want to cc @muruGanesan

**Comment by muruGanesan** [comment] 2018-03-03 16:51
@rgarg1, I am planning to review planner UI and flow for optimizing the notifications.  
 we will review these points and come up with some general rules.

**Comment by muruGanesan** [comment] 2018-03-06 08:29
@rgarg1, I reviewed the planner with proper data in each column... it doesn't appear with a lot of whitespaces. Please refer the screen-shot; Close this issue if you agree.


<img width="1680" alt="image" src="https://user-images.githubusercontent.com/26006817/37021661-4b7da324-2146-11e8-89f9-e65de9e8eb7c.png">

**Closed** 2018-03-08 10:47 UTC
Labels: area/UX, area/planner, team/planner, team/ux, type/bug
