### ISSUE TITLE
Create work item in Stack report gets a 404 error 

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#2706] opened 2018-03-21 06:23 UTC
@jyasveer, @sivaavkd please note.
Expected behavior: Once my stack report is generated, I should be able to create a work item in Planner and view it.
Current behavior: I get confirmation, that a work item has been created, in the stack report but when I click view here to see the work item, I hit a 404 error.
![screenshot from 2018-03-20 19-03-40](https://user-images.githubusercontent.com/16647625/37696576-bc4ef9dc-2cfd-11e8-8f14-73e1337af067.png)
![screenshot from 2018-03-20 19-03-53](https://user-images.githubusercontent.com/16647625/37696583-d07323a2-2cfd-11e8-9d55-4d971a01e7ee.png)

**Comment by rgarg1** [comment] 2018-03-21 09:38
@Preeticp The issue here is the workitem URL that is being formed. Here is the URL that is formed:

https://openshift.io/pchandra@redhat.com/Plnr_Anltcs%20doc%20tests/plan/detail/13

Observe that the spaces in the space name have been escaped. Instead, the spaces should have been replaced by "_".

Actual Space name: Plnr Anltcs doc tests
Current and wrong space name in URL: Plnr_Anltcs%20doc%20tests
Expected space name: Plnr_Anltcs_doc_tests

**Comment by Preeticp** [comment] 2018-03-27 05:47
@jyasveer please take a look at @rgarg1 comments above.

**Comment by miteshvp** [comment] 2018-04-25 14:37
@Preeticp - am not able to reproduce this issue. Can you please try again?

**Comment by Preeticp** [comment] 2018-04-25 16:11
@mitesh, this issue, as explained by @rgarg1 above, occurs when there are spaces in the name of the space you create. 
As he points out: the spaces in the space name have been escaped. Instead, the spaces should have been replaced by "_".
Actual Space name: Plnr Anltcs doc tests
Current and wrong space name in URL: Plnr_Anltcs%20doc%20tests
Expected space name: Plnr_Anltcs_doc_tests

I tried again here are the screenshots for the Space I created and the errors thrown when I create a WI through the companion dependency page using 'view here' or 'view work item' in the toast notification:

![screenshot from 2018-04-25 21-31-45](https://user-images.githubusercontent.com/16647625/39258097-be11a352-48d0-11e8-84cc-2e608eb8da35.png)

![screenshot from 2018-04-25 21-30-25](https://user-images.githubusercontent.com/16647625/39258121-cf7a0058-48d0-11e8-9cd8-227533c191c6.png)

![screenshot from 2018-04-25 21-30-09](https://user-images.githubusercontent.com/16647625/39258146-da74c9ac-48d0-11e8-80b6-591c34e159ad.png)

**Comment by sanbornsen** [comment] 2018-04-26 05:04
@joshuawilson due to the guided type work item creation, we don't allow creating work items out of planner. That non-contextual add work item dialog is legacy and doesn't work.

**Comment by arunkumars08** [comment] 2018-04-26 06:02
@sanbornsen @joshuawilson Yesterday I raised a PR with respect to addressing dynamic space templates - https://github.com/openshiftio/openshift.io/issues/3304

Will this not help?
Or is this something entirely different?

@kwk

**Comment by jyasveer** [comment] 2018-04-26 06:25
@Preeticp What i remember we had addressed this scenario. however we will see to it again. Thanks

**Comment by kwk** [comment] 2018-04-26 07:45
> @sanbornsen so you can't file a bug from stack analytics?

@joshuawilson you can file a bug but you MUST use REST and be mindful about what work item type to pick. That's why @arunkumars08 has created #3304 to choose a type named "Bug". Before the ID of this type was hard-coded into analytics and now the ID is fetched by inspecting the types for the space at hand.

**Comment by arunkumars08** [comment] 2018-04-30 12:11
Closing this as the changes are already in prod and the issue seems to have been fixed. Please open if you feel otherwise.

**Closed by arunkumars08** 2018-04-30 12:11 UTC
Labels: SEV2-high, area/analytics, area/planner, priority/P0, team/analytics, type/bug
