### ISSUE TITLE
Iterations loading issues - data appears to vanish

### ISSUE THREAD

**Issue by psrna** [openshiftio/openshift.io#3074] opened 2018-04-12 14:39 UTC
I played a bit with planner, created several iterations, but then they disappeared. Actually I could see them on the 'Board' tab but not on the 'Backlog' tab.

screenshots:
https://www.dropbox.com/s/uw6zwsmabb7hldw/Screenshot%202018-04-12%2016.35.27.png?dl=0
https://www.dropbox.com/s/z63trutagmhqjm8/Screenshot%202018-04-12%2016.35.42.png?dl=0

After a bit more playing I managed to crash the planner:
https://www.dropbox.com/s/bwua307y2ki01qp/Screenshot%202018-04-12%2016.41.31.png?dl=0
https://www.dropbox.com/s/6bs3zmukxblvdsw/Screenshot%202018-04-12%2016.40.01.png?dl=0

**Comment by nimishamukherjee** [comment] 2018-04-13 05:46
@vikram-raj can you replicate the issue?

**Comment by vikram-raj** [comment] 2018-04-16 05:48
@psrna I am not able to reproduce this issue. Can you please provide the steps to reproduce this?

**Comment by psrna** [comment] 2018-04-16 09:14
I cannot reproduce Today, but it was a terrible experience during Thursday's click party. May be worth checking if there were some issues with service delivery during that time.

**Comment by rgarg1** [comment] 2018-04-24 10:42
I was able to reproduce the hung planner issue. Steps I took:

1) Go to Planner list view and ensure that you've got a few work items and data to load
2) Now go to the Board view tab and create a new work item
3) Drag and drop that workitem to another column
4) return to list view and you should see the hang. If not, repeat steps 1 through 4

![planner hung](https://user-images.githubusercontent.com/28748448/39182335-39c043fc-47da-11e8-965a-0120c75f02f2.png)
[openshift.io-consolelog.log](https://github.com/openshiftio/openshift.io/files/1942347/openshift.io-consolelog.log)

**Comment by rgarg1** [comment] 2018-04-26 07:03
@vikram-raj The issue was observed on the list view and not on the board view. Only the steps to reproduce involved board view, so I'll try to reproduce it once the board is removed and I hope we don't see it anymore.

**Comment by nimishamukherjee** [comment] 2018-04-30 07:49
@rgarg1 board view has been removed. Please let us know if you can replicate this issue.

**Comment by rgarg1** [comment] 2018-04-30 08:01
With the board view gone, I cannot reproduce this issue.

**Comment by nimishamukherjee** [comment] 2018-04-30 08:27
Closing this issue. If anyone finds this issue on prod, please re-open this issue.

**Closed by nimishamukherjee** 2018-04-30 08:27 UTC
Labels: SEV2-high, area/planner, priority/P0, team/planner, type/bug
