### ISSUE TITLE
Ghost deployment preventing starting of workspaces

### ISSUE THREAD

**Issue by scela** [openshiftio/openshift.io#4379] opened 2018-10-02 11:59 UTC
Today I had an apparently unsuccessful start of a workspace and it was showing as red in my workspaces list.

After that I was unable to start any other workspaces. Upon further investigations it turned out that a full clearing 'oc delete all' style was needed for my account to get back in shape.

I didn't have anything useful but one would think this is overkill to restore usability of the account if people have real projects on it.

**Comment by amisevsk** [comment] 2018-10-02 21:11
Potentially related to https://github.com/eclipse/che/issues/11447 or (more likely) https://github.com/eclipse/che/issues/11445 + an issue retrieving userId on restart.

### Background:
Around the time this happened in @scela's namespace, the Che server hit an OOM error which caused it to restart. Due to the issues above, the running workspace either could not be recovered, or recovery was prevented by https://github.com/eclipse/che/issues/11445. This could result in untracked deployments that Che is unable to clean up.

Ping me for the logs from the event, if necessary.

PR https://github.com/eclipse/che/pull/11446 is open in upstream Che which should fix the more likely issue.

**Comment by ibuziuk** [comment] 2018-10-03 15:53
Current workaround is manual cleanup of the *-che namespace via `oc delete all -l che.workspace_id` command

**Comment by amisevsk** [comment] 2018-10-22 18:49
Going forward this issue should be solved, now that fixes for https://github.com/eclipse/che/issues/11445 and https://github.com/redhat-developer/rh-che/issues/971 are available on prod.

**Comment by ibuziuk** [comment] 2018-10-23 14:29
@amisevsk could we close this issue now since the fixes are now available on prod? Also could you please clarify what would be the expected behavior when user starts a workspace with untracked deployment in the *-che namespace ?

**Comment by amisevsk** [comment] 2018-10-24 04:54
@ibuziuk I agree that this issue should be closed now.

Regarding untracked deployments, as far as I know, all of those were due to the recovery bugs that are now fixed, so there *shouldn't* be any more untracked deployments. 

Could you clarify what you mean in expected behaviour? There are a few aspects to this:
- If Che loses track of a workspace, and there are untracked deployment resources on a user's *-che namespace, then Che will fail to start a new workspace, likely with a somewhat cryptic message (e.g. "timeout waiting for pod to start"). I'm not sure there's much we can do to improve the error message, as this would require Che knowing what it doesn't know. 
   - if the user tries to start the same workspace that is currently untracked, Che will hit a resource already exists error and clean up the untracked workspace, bringing the namespace back into a consistent state.
- Some of the specific issues faced by users (e.g. "workspace is already running") should be gone now, as they were a symptom of inconsistency between the server and its DB. 
- Additionally, we've fixed the bug where additional failed-to-start workspaces would pollute the user's namespace with waiting-to-scale-to-1 deployments, which, while not directly related to the issue above, certainly contributed to how opaque it was from the user's perspective.

**Comment by ibuziuk** [comment] 2018-10-29 07:30
Going to close the issue after 6.13.0 update on prod which contains some important fixes from upstream

**Closed** 2018-10-30 09:11 UTC
Labels: SEV2-high, area/che, priority/P3, team/che/osio, type/bug
