### ISSUE TITLE
openshift resources  don't have the space label/selector, when new launcher used

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#3549] opened 2018-05-14 07:46 UTC
When I create an app with the new launcher and do a 
```
$ oc project <username>-stage
$ oc get all --selector space=space1-may
```
On doing so, the resources relevant to the app created using the launcher **does not** show up.

However the BCs and the Builds in the user namespace have the correct `space` label
```
$ oc project <username>
$ oc get all --selector space=space1-may
NAME                   TYPE              FROM         LATEST
bc/app-test-1-space1   JenkinsPipeline   Git@master   1
bc/space1-may          JenkinsPipeline   Git@master   1
```

This has been observed with the new launcher. I've verified that the on using the old launcher/wizard, the `space` label shows up in -stage and -run .

**Comment by jiekang** [comment] 2018-05-14 12:10
This is a more apt description but probably duplicate of https://github.com/openshiftio/openshift.io/issues/2360

**Comment by animuk** [comment] 2018-05-15 06:36
@ebaron Can I close this if this is a duplicate of #2360

**Comment by joshuawilson** [comment] 2018-05-15 15:02
Closing. Duplicates: #2360

**Closed by joshuawilson** 2018-05-15 15:02 UTC
Labels: SEV2-high, area/launcher, team/launcher, type/bug
