### ISSUE TITLE
Can't import repository to the new space

### ISSUE THREAD

**Issue by kadel** [openshiftio/openshift.io#1300] opened 2017-11-07 14:32 UTC
I've created new space and imported codebase from GitHub repository.
Then I have deleted the whole space and created the new one with different name.

If I try to import the same repository to the new space I get the following error:

```
The repository golang-example has already a build config, please select another repo. 
```

**Comment by corinnekrych** [comment] 2017-11-09 08:31
@joshuawilson this is not a bug, more an enhancement on fabric8-generator addon to add ability to override of buildconfig.
@kadel have you use the `Reset environment` in the profile page to clean?

**Comment by kadel** [comment] 2017-11-09 13:30
> @kadel have you use the Reset environment in the profile page to clean?

Yes, I did that. That is the only way to around that issue that I know.

**Comment by joshuawilson** [comment] 2018-01-19 04:21
this was fixed with a reset, closing

**Closed by joshuawilson** 2018-01-19 04:21 UTC
Labels: area/app-wizard, team/launcher, team/platform, type/feature

**Comment by kadel** [comment] 2018-04-03 05:42
Resetting environment no longer works as a workaround for this.
I'm unable to import repository that I've imported and deleted before :-(
