### ISSUE TITLE
OpenShift (not openshift.io) shows and have duplicated pipelines when app and repo name are different

### ISSUE THREAD

**Issue by mrizzi** [openshiftio/openshift.io#3095] opened 2018-04-12 15:32 UTC
I created an application named `app-test-1` (the default value in wizard) and then used a different name (`click-party`) for the [repository](https://github.com/mrizzi/click-party) .
This produces 2 different pipelines (`app-test-1` and `click-party`) in the openshift.com UI (Screenshot-0) but only `app-test-1` pipeline is in openshift.io (Screenshot-1).

**Screenshot-0**
![screenshot-0](https://user-images.githubusercontent.com/7288588/38687601-60ff2a9e-3e77-11e8-84e0-b74e2ebf40eb.png)

**Screenshot-1**
![screenshot-1](https://user-images.githubusercontent.com/7288588/38687615-679da5f6-3e77-11e8-8be0-296b46727505.png)

Then, after i [merged a PR](https://github.com/mrizzi/click-party/pull/1) in the GitHub repository, a third pipeline, named `click-party.pr-1`, appeared in openshift.com (Screenshot-0). Is this third pipeline supposed to appear? Even if it never builds?

**Comment by trepel** [comment] 2018-04-13 08:48
Hi there, I just wanted to say I observed very same behaviour during Apr 12, 2018 click party.

In my case no stages had started for app-test-1 pipeline when suddenly the new pipeline (named after the actual name of my github repo) appeared and this pipeline finished before the app-test-1 pipeline. I was also not able to see this pipeline in openshift.io as described.

It happened before I created my Che workspace so it should be unrelated to that.

**Comment by ravsa** [comment] 2018-04-20 13:57
I found that this block of code https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java#L93-L97 is causing this problem.
@gastaldi do you have any idea what could be the problem?
I have noticed the same behavior in legacy flow also.

**Comment by gastaldi** [comment] 2018-04-20 14:53
@ravsa no idea, but that code was copied from the legacy flow, so it makes sense to see this behavior in both flows if that is the cause.

**Comment by piyush1594** [comment] 2018-04-24 13:55
@ravsa @gastaldi Is build team need to do something for this.

**Comment by ravsa** [comment] 2018-04-24 19:45
@piyush1594 this issue occurs when `application name` and GitHub `repository name` is different.
and I found that the configMap is pretty much same for both cases (`applicationName==repoName` and `applicationName != repoName`)  in launcher-backend and these are the changes we are making in configMap https://github.com/fabric8-launcher/launcher-backend/blob/dfa6e6cc3e8e6c2d1992ce386a02d487876ca346/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java#L85-L92.
So I think there are possibilities that this bug could exist in build pipeline, not completely sure but we should check there also.

**Comment by pradeepto** [comment] 2018-04-25 13:14
@animuk @sivaavkd I had spoken about this with @piyush1594 couple of hours back and he had told me that @ravsa is working on it (at least that is what he had told @piyush1594 around the same time) Can you ACK @piyush1594 @ravsa ?

**Comment by ravsa** [comment] 2018-04-25 13:16
@pradeepto I've checked in launcher code and found nothing. It seems like it's a bug into build pipeline.

**Comment by ravsa** [comment] 2018-04-25 13:25
cc @piyush1594 @animuk

**Comment by piyush1594** [comment] 2018-04-26 06:32
I tried to reproduce this with the help of @ravsa and it is reproducible.

**Comment by ravsa** [comment] 2018-04-27 08:00
@piyush1594 If both the names `projectName` and `repoName` are the same in that case also it creates two builds first one with the `projectName` and the second one with `(githubUsername/githubOrgnization).githubRepositoryName` even in the legacy flow but this issue does not occur everytime.

**Comment by piyush1594** [comment] 2018-04-27 08:05
@ravsa  What I noticed is this happens in new UI for me, never happened in Legacy UI

**Comment by krishnapaparaju** [comment] 2018-04-30 07:54
@animuk @ravsa @gastaldi current Build application  would not work for 'Application name' being different from 'repo name'. We need to rework thru this flexibility (Application name can be different from Repo name). @animuk please call out when the fix is migrated to production for testing.

cc @GeorgeActon @catrobson

**Comment by animuk** [comment] 2018-04-30 08:07
@krishnapaparaju even in the legacy also, if user choose different git org from the legacy launcher, pipeline duplication happens in the openshift and according to our findings, issue is originating in build side.

**Comment by krishnapaparaju** [comment] 2018-05-01 07:44
@slemeur +1 on this is needs to be fixed on the build side.
weighing on two options with respect to timelines: (a) Fix on the build side, not sure about the effort at this time (b) Align application name and repo. name on the Launcher side, effort would be less.

**Comment by piyush1594** [comment] 2018-05-01 08:03
According to info I received from @ravsa 

This is also affecting other issues like 
1. che recompile won't work
2. user can't see updated code
3. user is not able to see updated code

**Comment by jaseemabid** [comment] 2018-05-02 14:10
I worked with @piyush1594 and we could reproduce this issue. 

The root cause of this bug could be anywhere in launcher, build code or one of the plugins we ship. I'll admit that I don't even know all the components that are involved in the whole process of setting up a build and we have zero docs to go read. None from build team have worked on the launcher code before and we wont be able to go through all that and safely update the code now. Since the pipeline created in Jenkins is named after the github repo (and not build), I'm wondering if its started by the organization plugin instead. Is sync plugin involved? I don't know.  

I think the best thing we could do right now (**3 working days to summit**) is to disable the UI feature allowing different names for the repo and pipeline. _Its a potentially risky idea to keep changing things now_.

cc: @qodfathr @pradeepto @krishnapaparaju @maxandersen

**Comment by maxandersen** [comment] 2018-05-03 07:08
After conversation this morning it became clear this is old issue that just never was exposed because old launcher kept app and repo was kept in sync.

Breaking that sync in UI was done with good intentions but should not have happened as somewhere in openshift sync plugin and how jenkins org sync plugin works by using git repo as the key.

Proposal for this week is:
1) launcher ui team makes a PR to push to prod-preview for testing which keeps app name and git repo in sync. This will make it so the happy path wher users change app name or git repo name to avoid duplicates don't trigger this bug.
2) build team will investigate where in the layers below there are assumptoins about which name is being used as key to handle the sync - based on that we can work on plan to properly fix this.

/cc @slemeur

**Comment by piyush1594** [comment] 2018-05-03 10:54
Hey,

We little looked into the code and tried to find out the reason. We don't have a concrete answer for this and neither a perfect reason but go some pointers that may be the probable reason.

I had three accounts out of which issue is reproducible in one account and not reproducible in other 2 accounts. We further analyzed the configMap and found out the difference there and also the difference in the version of the plugins shipped with them.

ConfigMap data of the account from which it is reproducible
```
<?xml version="1.0" encoding="UTF-8"?><jenkins.branch.OrganizationFolder plugin="branch-api@2.0.16">
  <actions/>
  <description/>
  <properties>
    <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.2.5">
      <dockerLabel/>
      <registry plugin="docker-commons@1.9"/>
    </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
    <jenkins.branch.NoTriggerOrganizationFolderProperty>
      <branches>.*</branches>
    </jenkins.branch.NoTriggerOrganizationFolderProperty>
  </properties>
  <folderViews class="jenkins.branch.OrganizationFolderViewHolder">
    <owner reference="../.."/>
  </folderViews>
  <healthMetrics>
    <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.2.1">
      <nonRecursive>false</nonRecursive>
    </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
  </healthMetrics>
  <icon class="jenkins.branch.MetadataActionFolderIcon">
    <owner class="jenkins.branch.OrganizationFolder" reference="../.."/>
  </icon>
  <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.2.1">
    <pruneDeadBranches>true</pruneDeadBranches>
    <daysToKeep>-1</daysToKeep>
    <numToKeep>-1</numToKeep>
  </orphanedItemStrategy>
  <triggers/>
  <disabled>false</disabled>
  <navigators>
    <org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator plugin="github-branch-source@2.3.1">
      <repoOwner>surajnarwade</repoOwner>
      <credentialsId>cd-github</credentialsId>
      <traits>
        <org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
          <strategyId>3</strategyId>
        </org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
        <org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
          <strategyId>1</strategyId>
        </org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
        <org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
          <strategyId>1</strategyId>
          <trust class="org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustContributors"/>
        </org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
        <jenkins.scm.impl.trait.WildcardSCMHeadFilterTrait plugin="scm-api@2.2.5">
          <includes>master | PR-*</includes>
          <excludes/>
        </jenkins.scm.impl.trait.WildcardSCMHeadFilterTrait>
        <jenkins.scm.impl.trait.RegexSCMSourceFilterTrait plugin="scm-api@2.2.5">
          <regex>app-test-1-2|app-test-dd|app-test-dknmckdwn|app-test-ddd-dup</regex>
        </jenkins.scm.impl.trait.RegexSCMSourceFilterTrait>
      </traits>
      <includes>master | PR-*</includes>
    </org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator>
  </navigators>
  <projectFactories>
    <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory plugin="workflow-multibranch@2.16">
      <scriptPath>Jenkinsfile</scriptPath>
    </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory>
  </projectFactories>
  <buildStrategies/>
</jenkins.branch.OrganizationFolder>
```

ConfigMap data of the account from which issue is not reproducible
```
<?xml version="1.0" encoding="UTF-8"?><jenkins.branch.OrganizationFolder plugin="branch-api@2.0.7">
  <actions/>
  <description/>
  <properties>
    <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.0.2">
      <dockerLabel/>
      <registry plugin="docker-commons@1.6"/>
    </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
    <jenkins.branch.NoTriggerOrganizationFolderProperty>
      <branches>.*</branches>
    </jenkins.branch.NoTriggerOrganizationFolderProperty>
  </properties>
  <folderViews class="jenkins.branch.OrganizationFolderViewHolder">
    <owner reference="../.."/>
  </folderViews>
  <healthMetrics>
    <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@5.18">
      <nonRecursive>false</nonRecursive>
    </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
  </healthMetrics>
  <icon class="jenkins.branch.MetadataActionFolderIcon">
    <owner class="jenkins.branch.OrganizationFolder" reference="../.."/>
  </icon>
  <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@5.18">
    <pruneDeadBranches>true</pruneDeadBranches>
    <daysToKeep>0</daysToKeep>
    <numToKeep>0</numToKeep>
  </orphanedItemStrategy>
  <triggers/>
  <navigators>
    <org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator plugin="github-branch-source@2.0.3">
      <repoOwner>piyush1594</repoOwner>
      <scanCredentialsId>cd-github</scanCredentialsId>
      <checkoutCredentialsId>SAME</checkoutCredentialsId>
      <pattern>gamma-again</pattern>
      <includes>master | PR-*</includes>
      <buildOriginBranch>true</buildOriginBranch>
      <buildOriginBranchWithPR>true</buildOriginBranchWithPR>
      <buildOriginPRMerge>true</buildOriginPRMerge>
      <buildOriginPRHead>false</buildOriginPRHead>
      <buildForkPRMerge>true</buildForkPRMerge>
      <buildForkPRHead>false</buildForkPRHead>
    </org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator>
  </navigators>
  <projectFactories>
    <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory plugin="workflow-multibranch@2.12"/>
  </projectFactories>
</jenkins.branch.OrganizationFolder>
```

Here is the link to the diff https://www.diffchecker.com/WCLfby4S but may expire. ConfigMap data of two accounts which are not able to reproduce the issue are same. For the prefect concrete answer, need to dig more.

cc @maxandersen @jaseemabid @rupalibehera @hrishin @krishnapaparaju @pradeepto @ravsa @animuk

**Comment by jaseemabid** [comment] 2018-05-03 10:59
Pasting the diff here inline. 

```patch
1c1
< <?xml version="1.0" encoding="UTF-8"?><jenkins.branch.OrganizationFolder plugin="branch-api@2.0.16">
---
> <?xml version="1.0" encoding="UTF-8"?><jenkins.branch.OrganizationFolder plugin="branch-api@2.0.7">
5c5
<     <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.2.5">
---
>     <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.0.2">
7c7
<       <registry plugin="docker-commons@1.9"/>
---
>       <registry plugin="docker-commons@1.6"/>
17c17
<     <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.2.1">
---
>     <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@5.18">
24c24
<   <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.2.1">
---
>   <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@5.18">
26,27c26,27
<     <daysToKeep>-1</daysToKeep>
<     <numToKeep>-1</numToKeep>
---
>     <daysToKeep>0</daysToKeep>
>     <numToKeep>0</numToKeep>
30d29
<   <disabled>false</disabled>
32,53c31,35
<     <org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator plugin="github-branch-source@2.3.1">
<       <repoOwner>surajnarwade</repoOwner>
<       <credentialsId>cd-github</credentialsId>
<       <traits>
<         <org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
<           <strategyId>3</strategyId>
<         </org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
<         <org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
<           <strategyId>1</strategyId>
<         </org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
<         <org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
<           <strategyId>1</strategyId>
<           <trust class="org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustContributors"/>
<         </org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
<         <jenkins.scm.impl.trait.WildcardSCMHeadFilterTrait plugin="scm-api@2.2.5">
<           <includes>master | PR-*</includes>
<           <excludes/>
<         </jenkins.scm.impl.trait.WildcardSCMHeadFilterTrait>
<         <jenkins.scm.impl.trait.RegexSCMSourceFilterTrait plugin="scm-api@2.2.5">
<           <regex>app-test-1-2|app-test-dd|app-test-dknmckdwn|app-test-ddd-dup</regex>
<         </jenkins.scm.impl.trait.RegexSCMSourceFilterTrait>
<       </traits>
---
>     <org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator plugin="github-branch-source@2.0.3">
>       <repoOwner>piyush1594</repoOwner>
>       <scanCredentialsId>cd-github</scanCredentialsId>
>       <checkoutCredentialsId>SAME</checkoutCredentialsId>
>       <pattern>gamma-again</pattern>
54a37,42
>       <buildOriginBranch>true</buildOriginBranch>
>       <buildOriginBranchWithPR>true</buildOriginBranchWithPR>
>       <buildOriginPRMerge>true</buildOriginPRMerge>
>       <buildOriginPRHead>false</buildOriginPRHead>
>       <buildForkPRMerge>true</buildForkPRMerge>
>       <buildForkPRHead>false</buildForkPRHead>
58,60c46
<     <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory plugin="workflow-multibranch@2.16">
<       <scriptPath>Jenkinsfile</scriptPath>
<     </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory>
---
>     <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory plugin="workflow-multibranch@2.12"/>
62d47
<   <buildStrategies/>

```

**Comment by animuk** [comment] 2018-05-07 06:49
As discussed with @maxandersen  and @slemeur ,From the launcher perspective, we have handled application name and repo name same  in the osio as a two-way binding for both new application and import flow. This way, possibility of landing this issue is substantially reduced now. 
But, still build team needs to check from their side about the root cause and fix this while user changes the git organization other than its own space.

**Comment by piyush1594** [comment] 2018-05-16 16:07
Regarding this issue, 

PR on launcher-backend is merged https://github.com/fabric8-launcher/launcher-backend/pull/401 and https://github.com/fabric8-launcher/launcher-backend/pull/402

Changes in launcher-side are in Prod by https://github.com/openshiftio/saas-launchpad/pull/132

Need the changes to sync plugin which is still in the review process https://github.com/fabric8io/jenkins-sync-plugin/pull/28

Thanks

**Comment by piyush1594** [comment] 2018-05-17 21:45
Update

One more PR on launcher backend, that is merged https://github.com/fabric8-launcher/launcher-backend/pull/404

It is in prod by https://github.com/openshiftio/saas-launchpad/pull/134

Changes requested on Jenkins sync plugin are addressed https://github.com/fabric8io/jenkins-sync-plugin/pull/28

PR raised on jenkins-s2i-config with latest binary(jpi) https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/170

I tested the changes locally for 4 cases and it worked fine for me all:
1. app == repo and user's space
2. app != repo and user's space
3. app == repo and different org
4. app != repo and different org

Looking for testers to confirm, all set from my side, ready to merge.

**Comment by piyush1594** [comment] 2018-05-18 12:42
Update

Testing done by @hrishin and @rupalibehera, all worked fine.

PR on sync plugin is merged https://github.com/fabric8io/jenkins-sync-plugin/pull/28

PR on jenkins-s2i-config with latest binary(jpi) https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/170 is there, we will merge it on Monday and will do the tenant wise update. After that you can do the respective changes in launcher-ui.

cc @krishnapaparaju @pradeepto @maxandersen 

Thanks

**Comment by piyush1594** [comment] 2018-05-30 03:02
Can we close this issue as #3663 will address the UI changes? @krishnapaparaju

**Comment by slemeur** [comment] 2018-05-30 17:30
Yes. closing in favor of #3662 for a proper fix

**Closed by slemeur** 2018-05-30 17:30 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, area/pipelines, team/build-cd, type/bug
