### ISSUE TITLE
Login - question - how long does the user remain logged in ?

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#1565] opened 2017-12-08 14:41 UTC
I was logged out after two hours - is this expected?
I opened Che editor made a commit and then when I viewed the pipeline it showed me as logged out.

**Comment by alexeykazakov** [comment] 2017-12-08 16:17
It’s not expected. If you don’t close your browser you should stay logged in forever. If you close it then you will need to re login in 30 days.

**Comment by alexeykazakov** [comment] 2017-12-11 21:16
If UI gets 401 response for some requests to backend then UI forces logout. We should improve this approach because not all 401 should be followed by logout.

**Comment by joshuawilson** [comment] 2017-12-21 17:28
@nimishamukherjee is this reproducible?

**Comment by alexeykazakov** [comment] 2018-01-12 22:15
The question is answered. @nimishamukherjee if we see any problems with login please give some details and open an issue. Closing this one.

**Closed by alexeykazakov** 2018-01-12 22:15 UTC
Labels: SEV3-medium, area/auth, team/auth, team/platform, type/bug
