### ISSUE TITLE
Clicking Promote or Abort button results in 404 error, but operation succeeds

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3425] opened 2018-05-03 07:23 UTC
Clicking Promote or Abort button results in 404 error in the API call, however, the operation succeeds in OSIO. See this snapshot:
![abort](https://user-images.githubusercontent.com/28748448/39564216-f4200492-4ed0-11e8-96e7-1b8741fd491c.png)

**Comment by piyush1594** [comment] 2018-06-23 08:57
@rgarg1 I tried to reproduce this. This is not the case right now. Can you please check and confirm? Thanks

**Comment by hrishin** [comment] 2018-07-30 05:03
@rgarg1 not able to reproduce it. Could you please give it a try otherwise its good to close it.

![image](https://user-images.githubusercontent.com/28615674/43378325-cd9ea1b8-93e3-11e8-80e4-ea23240de7d7.png)

**Comment by hrishin** [comment] 2018-07-30 12:34
It good to close now. If persists feel free to reopen or file a new one.

**Closed by hrishin** 2018-07-30 12:34 UTC
Labels: SEV3-medium, area/pipelines, team/build-cd, type/bug
