### ISSUE TITLE
Running the Forge Wizard 3 times in a space results in zombie pipeline runs/builds

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#447] opened 2017-07-31 23:45 UTC
https://www.screencast.com/t/XwqOMpunceBb

We have seen this bug in a few different iterations.  In this specific case, in a single Space, run the Wizard 3 times.  On the 2nd wizard execution, go have lunch, then Promote any outstanding pipelines that are hanging about.  Wait a moment, make sure it does not "come back to life" on its own.  
On the 3rd wizard run, you should see all 3 pipelines running when only the last one should be running

**Comment by burrsutter** [comment] 2017-08-01 17:22
A different account, same problem 
https://screencast.com/t/ivIbQryxDP1

**Comment by rgarg1** [comment] 2017-08-03 08:37
I've experienced a weirder problem. Running forge wizard twice in a space, first with quick-start, second with import-existing, brought back to life even deleted pipelines!! So a delete from OSO UI actually is not a delete.

**Comment by joshuawilson** [comment] 2017-08-03 15:39
@rgarg1 that is correct, we have issues and stories about how we need to implement deleting.

**Comment by jstrachan** [comment] 2017-08-09 14:18
think this is essentially a duplicate of #342

**Comment by rawlingsj** [comment] 2017-08-11 10:01
This should be fixed with Jenkins 3.0.81 https://github.com/fabric8io/jenkins-sync-plugin/commit/db03e025f3519b6ad8dd75c7ed05d03847f920fd please reopen if not.

**Closed by rawlingsj** 2017-08-11 10:01 UTC
Labels: area/pipelines, kind/bug, severity/P1, team/build-cd
