### ISSUE TITLE
If no is iteration assigned, don't show N/A

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2411] opened 2018-03-02 07:53 UTC
Planner today in the __Backlog__ view, displays __N/A__ for all workitems that are not assigned to any particular iteration. In other words, workitems in _root_ iteration are displayed as such.

Expected: Name of the root iteration should be displayed in place of N/A.

![na](https://user-images.githubusercontent.com/28748448/36888723-cde6257a-1e1c-11e8-9271-4c053419813a.png)

**Comment by nimishamukherjee** [comment] 2018-11-20 13:08
@openshiftio/uxd-team please comment.

Do note that the notion of root iteration is not exposed to the end user.

**Comment by christianvogt** [comment] 2018-12-11 22:03
Closing as duplicate of https://github.com/openshiftio/openshift.io/issues/2997

**Closed by christianvogt** 2018-12-11 22:03 UTC
Labels: SEV3-medium, area/UX, area/planner, area/planner/tree, priority/P4, team/ui, team/ux, type/bug
