### ISSUE TITLE
Missing Jenkins project for user accounts on 2a cluster

### ISSUE THREAD

**Issue by quintesse** [openshiftio/openshift.io#3322] opened 2018-04-26 11:29 UTC
I was getting errors while trying to connect to Jenkins as mentioned here: https://github.com/openshiftio/openshift.io/issues/3176#issuecomment-383064410

But after a BJN session with @ldimaggi today it turns out that the problem is most likely related to the fact that I don't have a Jenkins project in my openshift account as you can see here:

![image](https://user-images.githubusercontent.com/778793/39303165-6eb4158a-4955-11e8-959f-20383521d359.png)

Resetting the environment does not fix this issue.

**Comment by quintesse** [comment] 2018-04-26 11:29
Is this something you can look at @alexeykazakov ?

**Comment by ldimaggi** [comment] 2018-04-26 11:53
This issue seems to be unique to Tako's user account.

**Comment by maxandersen** [comment] 2018-04-26 13:41
I have same issue in #3026 - what happens if you go to jenkins.prod-preview.openshift.io ?

**Comment by quintesse** [comment] 2018-04-26 14:36
I get:

```
{"errors":[{"code":"unauthorized_error","detail":"unknown state: oauth state reference with id 'fe044e92-1b75-4523-a864-b4f3f8addbfa' not found","status":"401","title":"Unauthorized error"}]}
```

But that might very well be because I'm in a anonymous browser window where just opening a page and navigating to a URL probably doesn't use the same login info. And OSIO is currently broken and doesn't actually create any applications.

**Comment by quintesse** [comment] 2018-04-26 16:12
I can't right now, both environments don't allow me to create applications today.

**Comment by maxandersen** [comment] 2018-04-26 21:01
just go to jenkins.prod-preivew.openshift.io and log in or log in before.

**Comment by quintesse** [comment] 2018-04-27 00:27
(from chat)

> are you 100% yuo are actually logged in when trying to access jenkins?

No, I'm pretty sure I'm not, but it's you that tells me to just go to jenkins.prod-preview.openshift.io :)
But if I go there I'm not logged in and it doesn't let me log in either, it just immediately gives me that error.

**Comment by joshuawilson** [comment] 2018-04-27 02:11
@maxandersen are you still seeing this? Are you missing your `-jenkins`? If only 2 people can reproduce it, is it really a SEV1?

**Comment by gastaldi** [comment] 2018-04-27 04:52
This seems to be the cause why https://github.com/openshiftio/openshift.io/issues/3076 happened

**Comment by joshuawilson** [comment] 2018-04-27 06:13
ok, so maybe more then 2

**Comment by aslakknutsen** [comment] 2018-04-27 06:57
@joshuawilson This effects 'an unknown larger number' of users on Cluster 2a. 2a is used for preview and prod. Sev-1 is appropriate.

**Comment by kishansagathiya** [comment] 2018-04-27 11:50
I am also one of the victims here :grinning:

**Comment by InfoSec812** [comment] 2018-04-27 12:15
Adding a note here after the OSIO click-party this morning to say that I am also having this issue.

**Comment by InfoSec812** [comment] 2018-04-27 12:57
I also tried resetting my entire environment and this did not help resolve the issue.

**Comment by ptoal** [comment] 2018-04-27 13:13
I experienced this issue this morning as well.  Selecting "View Log" from the Pipelines->Build Status in Openshift Console gave me: {"Errors":[{"code":"500","detail":"could not login to Jenkins in ptoal-jenkins namespace"}]}  Followed by HTML and a base64 blob, ending with: 
Authentication required


</body></html>      

Prior to this, I reset my environment, because I had a Build that I waited for > 35 minutes and it didn't start.  This build ran fine, but I could not log into Jenkins.  When I clicked on the "Input Required" link to promote the build, It took me to a regular jenkins login page.  I left UserID, and PW blank, and clicked Login.  It then took me to the "Log in with OpenShift" page.  When I clicked the Log In with OpenShift button, I got the following error: 
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"ZDFhMjJiZDYtZTViNi00"}

**Comment by maxandersen** [comment] 2018-04-27 21:36
fyi, what happened is that on cluster 2a we lost ability to setup rolebindings properly - thats now fixed and if you have had the issue you can go to profile, update settings and update profile. 

Then you should again see jenkins.

work is being done to get this autoupdated across the cluster for all users affected.

**Comment by aslakknutsen** [comment] 2018-04-28 00:25
Cluster update complete. This should now be resolved for all users. Please let me know if this is still an issue.

**Closed** 2018-04-30 09:28 UTC
Labels: SEV1-urgent, area/jenkins, area/user/tenant, env/prod, env/prod-preview, team/platform, type/bug
