### ISSUE TITLE
Scale Jenkins proxy with more replicas

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#3467] opened 2018-05-05 05:02 UTC
Currently only one replica is being used to serve OSIO user traffic, this is single point of entry for the entire traffic. Scaling (3 replicas can be minimum), testing Jenkins Proxy is critical to scale Build platform for higher number of concurrent OSIO users.

**Comment by jaseemabid** [comment] 2018-05-07 09:15
Scaling Idler and Proxy are similar and my comments are here on the Idler issue. https://github.com/openshiftio/openshift.io/issues/3468#issuecomment-387006568

**Comment by sthaha** [comment] 2018-05-08 00:09
Assigning it to @krishnapaparaju so that we don't forget to remove P0 and to save others from having to go through the issue again.

**Comment by chmouel** [comment] 2018-05-14 12:10
Here is how to scale the proxy, i haven't tested it : 

```diff
diff --git i/openshift/jenkins-proxy.app.yaml w/openshift/jenkins-proxy.app.yaml
index ba4a1cc..6547570 100644
--- i/openshift/jenkins-proxy.app.yaml
+++ w/openshift/jenkins-proxy.app.yaml
@@ -10,7 +10,7 @@ objects:
   metadata:
     name: jenkins-proxy
   spec:
-    replicas: 1
+    replicas: 3
     selector:
       service: jenkins-proxy
     strategy:
```

**Comment by jfchevrette** [comment] 2018-05-24 13:58
jenkins-proxy has been running with 3 replicas in staging for 2 weeks. are we OK to deploy the change to production?

**Comment by chmouel** [comment] 2018-05-24 14:34
I had an issue reported by @sthaha which I wasn't able to reproduce correctly, will deploy ASAP and will see how it goes,

**Comment by jfchevrette** [comment] 2018-06-04 14:21
@chmouel any update on this?

**Comment by sthaha** [comment] 2018-09-24 12:28
I am going to close this since it isn't a bug rather a feature request. Lets open up a story in planner instead when we find a need for it.

**Closed by sthaha** 2018-09-24 12:28 UTC
Labels: SEV2-high, area/jenkins, priority/P4, sprint/tbd, team/build-cd, type/bug
