### ISSUE TITLE
Accessing jenkins.openshift.io fails with auth errors

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/openshift.io#2534] opened 2018-03-12 08:51 UTC
Its partly html and partly json. I'll rather have this page redirect me to auth and take me back.

```
{"Errors":[{"code":"500","detail":"could not login to Jenkins in jabid5-jenkins namespace"}]}
<a href="https://auth.openshift.io/api/login?redirect=https:%2F%2Fjenkins.openshift.io%2F">Moved Permanently</a>.
```
This could be auth, idler, platform or some other piece I don't know yet.

**Comment by jaseemabid** [comment] 2018-03-12 09:09
Idled or not, I usually try to get to my Jenkins instance directly through the jenkins.openshift.io url. 

Right now, I am authenticated on openshift.io but that seems to be not making any difference. 

Doing this in an incognito window takes me to https://developers.redhat.com and when I come back after authentication, I get the same error.

**Comment by hferentschik** [comment] 2018-03-12 09:23
jenkins.openshift.io is the Jenkins Proxy. Let's open an issue there and let's have the discussion there https://github.com/fabric8-services/fabric8-jenkins-proxy/issues

**Comment by alexeykazakov** [comment] 2018-03-12 17:16
Removed team/auth and added team/platform for investigation.

**Comment by jaseemabid** [comment] 2018-03-13 06:33
Update: Works on the old 2 cluster, not on the newer 2a cluster.

**Comment by stevengutz** [comment] 2018-03-19 10:21
If this is critical how come no one seems to be working on it?

**Comment by jaseemabid** [comment] 2018-03-19 13:02
@stevengutz This is an issue with the Proxy and as of now only @kishansagathiya is working on it since  @hferentschik left.

**Comment by kishansagathiya** [comment] 2018-03-19 14:22
@jaseemabid I cannot reproduce this issue even when jenkins is idled. Please put a comment on how you faced this, as in put steps to reproduce this. Also has anyone else faced this issue?
If anyone else has faced this as well, feel free to put steps here.

**Comment by kishansagathiya** [comment] 2018-03-19 15:43
So I went through the messages from last week. Most of the last week's complains were regarding, not being able to unidle jenkins when they access openshift.io. Which is different than this issue. I have created a new issue with steps to reproduce that(https://github.com/openshiftio/openshift.io/issues/2678). and will take up this if someone faces this.

**Comment by kishansagathiya** [comment] 2018-03-23 11:53
I have still not faced this issue, but I have come accross few other auth related scenarios in jenkins.
https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/205 and https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/203 are worth looking at.

**Comment by jaseemabid** [comment] 2018-03-27 15:17
@kishansagathiya I reproduced this again today and got this error. 

```json
{"errors":[{"code":"unauthorized_error","detail":"oauth2: cannot fetch token: 500 Internal Server Error\nResponse: \u003chtml\u003e\u003chead\u003e\u003ctitle\u003eError\u003c/title\u003e\u003c/head\u003e\u003cbody\u003eInternal Server Error\u003c/body\u003e\u003c/html\u003e","status":"401","title":"Unauthorized error"}]}
```

I had jenkins.osio left open for long and reloaded the page after it idled to get here.

**Comment by ldimaggi** [comment] 2018-03-27 15:52
Is this issue 100% reproducible? Or - is it hit-or-miss?

**Comment by jaseemabid** [comment] 2018-03-27 17:25
@ldimaggi Happens once in a while for me. I'm sure we can dig into the code of proxy and find the root cause.

**Comment by mattd72** [comment] 2018-04-12 13:50
Same issue during 4/12 click party.  Following guide: https://docs.google.com/document/d/1KDx05WAk5omKXi7OosRfDTMRDorOt1k6iJrozWWRKZ4/edit

{"Errors":[{"code":"500","detail":"could not login to Jenkins in madavis-jenkins namespace"}]}.  
....
Authentication required


</body></html

**Comment by kishansagathiya** [comment] 2018-04-24 11:33
https://github.com/openshiftio/openshift.io/issues/2534#issuecomment-376564075 was seen while we moves prod-preview accounts to username-preview. Apart from that this is duplicate of https://github.com/openshiftio/openshift.io/issues/3026. This should be close since the other one has more info and visibility.

**Comment by joshuawilson** [comment] 2018-04-25 02:48
closing duplicate

**Closed by joshuawilson** 2018-04-25 02:48 UTC
Labels: SEV2-high, area/jenkins, issue/crucial-dep, issue/intermittent, priority/P0, team/build-cd, type/bug
