### ISSUE TITLE
New Che Workspace requests login (even though I'm already in)

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#2587] opened 2018-03-14 18:04 UTC
Starting OSIO Test day scenario:
1)  New project 
2)  Pick a template (Springboot / HTTP)
3)  From project front-page, navigate to 'Create' and choose to make a new workspace. 
>>>> Unintuitively, I was asked to sign in again.
(Result, after signing in again:  All seems normal, Che project looks good.)

![image](https://user-images.githubusercontent.com/524520/37421888-3172bbc0-2788-11e8-8365-ee739e49bf24.png)

**Comment by ldimaggi** [comment] 2018-03-14 19:01
Rick - are you able to recreate this issue? Can you confirm that you were logged in at the start of the sequence? I cannot recreate this problem myself. Thx!

**Comment by RickJWagner** [comment] 2018-03-15 18:35
Hi Len,
Yes, I was just able to recreate this issue.
- I was logged in at the start, and even went through an 'environment reset' to start
- Then made a new project, used Spring Boot again, after the workspace was created went immediately to the 'create' tab and choose to create a Che workspace.  I got the login page again.
(If someone is log spelunking, this all happened about 13:35 Central time)

**Comment by stevengutz** [comment] 2018-09-24 10:41
Lowering to SEV3 since it's more of annoyance than an critical failure

**Comment by ibuziuk** [comment] 2018-11-19 08:16
Similar issue [1] has been closed as not reproducible. Closing this one also. Feel free to reopen with more details.


[1] https://github.com/openshiftio/openshift.io/issues/4545

**Closed by ibuziuk** 2018-11-19 08:16 UTC
Labels: SEV3-medium, area/che, priority/P4, team/che/osio, type/bug
