### ISSUE TITLE
Button for 'Promote to next environment' is not working

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2119] opened 2018-01-31 06:09 UTC
<img width="576" alt="screen shot 2018-01-31 at 11 37 14 am" src="https://user-images.githubusercontent.com/15967765/35607679-59af5162-067b-11e8-89dd-d8f90a2a2088.png">
Clicking on buttons to 'promote to next environment' (at OSIO UI) not doing anything. However promoting (to the next environment) directly from Jenkins console is 'promoting' a quick start application to the next environment.
<img width="455" alt="screen shot 2018-01-31 at 11 35 23 am" src="https://user-images.githubusercontent.com/15967765/35607667-51a3e708-067b-11e8-93de-f5ad7bf8bb76.png">

**Comment by alexeykazakov** [comment] 2018-01-31 06:15
A dupe of https://github.com/openshiftio/openshift.io/issues/2034

**Closed by alexeykazakov** 2018-01-31 06:15 UTC
Labels: SEV2-high, team/platform, type/bug
