### ISSUE TITLE
Deleting a space doesn't delete associated pipelines

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#132] opened 2017-05-02 15:22 UTC
After deleting a space, I still have a zombie pipeline still trying to build. It's possible the pipeline state is in a borked state that prevents it from being deleted, I have no idea, but in that case the deletion process should be more robust.

**Comment by joshuawilson** [comment] 2017-05-22 01:56
This issue was moved to fabric8io/fabric8-ui#1344

**Comment by RanjithRV** [comment] 2018-01-10 06:47
@chmouel @pradeepto made this issue Sev3 as it has been hanging around since May 2017. Please update if needed.

**Comment by qodfathr** [comment] 2018-01-12 17:11
@catrobson Is this something for which UXD has a plan? Or is this one of the open issues around Space deletion?

**Comment by catrobson** [comment] 2018-01-13 00:34
Yes, this is one of the open issues around space deletion.

**Comment by piyush1594** [comment] 2018-06-21 06:11
Duplicate of #3802 Can we close this.

**Closed** 2018-06-22 02:39 UTC
Labels: SEV3-medium, team/build-cd, type/bug
