### ISSUE TITLE
No Feedback in Pipeline view of the current state of the pipeline

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3054] opened 2018-04-12 13:44 UTC
I had spinning cursor for a long time and went to the OpenShift web console directly.

The build had started but there was no feedback in openshift.io UI:
![nofeedbackinopenshiftiothatbuildreleasestarted](https://user-images.githubusercontent.com/1105127/38681116-44b4353c-3e68-11e8-9d81-ee214d5ac5bd.png)

The build has even failed and there was still no feedback, still a spinning monitor:
![nofeedbackinopenshiftiothatonbuildstateatallitseems](https://user-images.githubusercontent.com/1105127/38681140-4ec9868a-3e68-11e8-9198-e63f0bc828db.png)

I tried to reload the page and it was still the same

**Comment by ldimaggi** [comment] 2018-04-12 17:55
The build failure should have been reported back to the user in the OSIO UI. I have seen this reported in the past.

**Comment by andrewazores** [comment] 2018-04-27 16:34
The build failure reporting sounds like it could tie into the same concept being tracked in this issue: https://github.com/openshiftio/openshift.io/issues/2629 . That's more generic and talks about having notifications displayed for the user regardless of where they are in the application.

The Pipelines view not reflecting the correct status as seen in OSO, failure or in progress or whatever state, is interesting. Does anyone know a way to reproduce this?

**Comment by pradeepto** [comment] 2018-05-01 07:04
Don't think we can't fit this by GA timeframe. And it seems like it needs UX help.

cc @krishnapaparaju @maxandersen @qodfathr @bmicklea @catrobson

**Comment by bmicklea** [comment] 2018-05-01 11:02
It does seem like it would be covered by #2629. That issue seemed to be targeted for fix before Summit so if this can be rolled into that issue then we should close this and drive for completion on #2629.

**Comment by muruGanesan** [comment] 2018-05-01 13:46
@ldimaggi, @lordofthejars, @joshuawilson, @mishaone, @qodfathr, @maxandersen, @catrobson, @pradeepto, @bdellasc 
Ref: #945 
Please find the temporary UX proposal. i.e. provide feedback to the user [about the system's status]

![osio-945_proposal-03](https://user-images.githubusercontent.com/26006817/39474990-08e6ecd2-4d74-11e8-8620-400e3f72fe59.jpg)

**Comment by andrewazores** [comment] 2018-05-01 14:05
@bmicklea the parts of #2629 that might be relevant here, ie the OSO event notifications, will not be happening before Summit unfortunately.

**Comment by ebaron** [comment] 2018-05-01 16:43
This seems related to https://github.com/openshiftio/openshift.io/issues/3095, which creates extra pipelines that are not part of any space. Notice the build is happening in the `arepositoryforclickpartyopenshift.io` build config and not `app-test-1`. Once this issue is resolved, builds should consolidated under one pipeline that belongs to the user's space.

**Comment by jiekang** [comment] 2018-05-01 19:43
Agree with @ebaron . The builds in OSO shown here have strange names. It would not be caught by Pipelines code. Was this from the new wizard? This was reported 19 days ago and I think the wizard may have changed so this can't occur anymore.

**Comment by jiekang** [comment] 2018-05-01 19:44
Highly likely to be a duplicate of #3095 actually.

**Comment by bmicklea** [comment] 2018-05-01 23:32
If this is a super let's close it and reference that issue so we have a cleaner backlog.

**Comment by muruGanesan** [comment] 2018-05-07 16:47
@bdellasc, if it is related to #945, please close this issue too.

**Comment by krishnapaparaju** [comment] 2018-05-29 12:34
@invincibleJai can you please update current status of this issue.. thanks..

**Comment by invincibleJai** [comment] 2018-06-08 04:43
@krishnapaparaju looks like it's related #945 ( https://github.com/openshiftio/openshift.io/issues/3054#issuecomment-385674173) it has been fixed as suggested by @muruGanesan and changes are in prod.

**Comment by piyush1594** [comment] 2018-06-08 13:12
Yaa it seems like this has happened because of duplicate pipeline issue because, in OSIO, we always show sync the pipeline which is by the app name and here openShift and Jenkins are in sync in the other pipeline that got created by repo name and nothing happens in OSIO pipeline. We already fix the issue of two pipelines getting created in #3095 and also about the feedback in #945 

I think we can close this @invincibleJai @krishnapaparaju

**Comment by invincibleJai** [comment] 2018-06-11 06:11
Thanks @piyush1594 , closing it.

**Closed by invincibleJai** 2018-06-11 06:11 UTC
Labels: SEV2-high, area/UX, team/build-cd, team/ux, type/bug
