### ISSUE TITLE
run macro must be configured + no preview link

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2965] opened 2018-04-10 02:05 UTC
Not sure if this is by design so I'm logging an issue.

I created a quickstart in OSIO, created a workspace, everything works okay. I click the *run* option and it runs the following command via the preconfigured macro:

`scl enable rh-maven33 'mvn compile vertx:run -f ${current.project.path}'`

Next, I import an existing project to OSIO and create a workspace for that. When I try to run the same macro, there is none. Instead, I see:

![create_run_command](https://user-images.githubusercontent.com/926572/38532157-d3cc7332-3cb6-11e8-86be-e3ad1fecdb2d.png)

So I create the command, add the above command to a new macro, save and run it. I got the command from the preconfigured macro in my new quickstart workspace, so it should just work.

![add_details_run_command](https://user-images.githubusercontent.com/926572/38532175-ea72be84-3cb6-11e8-9a2e-e8dc46702ee1.png)

It runs okay, but there is no blue preview link where there should be on top of the terminal. This is what I see:

![no_link](https://user-images.githubusercontent.com/926572/38532199-0d5f80b2-3cb7-11e8-8b53-3420c9e6deab.png)

What I expect to see is something like this so I can preview my app:

![sb_preview_link](https://user-images.githubusercontent.com/926572/38532244-3d634672-3cb7-11e8-8d5e-29c16d55bfef.png)

So I have the wrong command, or is this deliberate, or a bug?

**Comment by mishaone** [comment] 2018-04-10 02:32
Tagging @joshuawilson to ensure I've assigned the correct team to this.

**Comment by joshuawilson** [comment] 2018-04-10 05:30
@l0rd can you please pass this on.

**Comment by ibuziuk** [comment] 2018-04-10 09:12
@mishaone well, but looks like there is no preview url defined in your new command

**Comment by mishaone** [comment] 2018-04-10 09:14
@ibuziuk 1) is manually adding a macro for the run command if we ad an existing codebase by design? It seems odd if it is since this macro is predefined for quickstart templates. 2) if this is the intended behavior, can you define what the command should be to include a preview url? I copied the command from the predefined macro and pasted in the one that didn't have it.

**Comment by ibuziuk** [comment] 2018-04-10 09:33
![image](https://user-images.githubusercontent.com/1461122/38548466-2cce03ec-3cb2-11e8-8d74-17f2e7a33896.png)

@mishaone there is no preview url defined in your command that's why no preview url is shown. When you import existing project `java-centos` stack is used and no run command is defined

> I created a quickstart in OSIO, created a workspace, everything works okay. I click the run option and it runs the following command via the preconfigured macro:

just copy preview url from ^ to your command for existing projects

**Comment by mishaone** [comment] 2018-04-10 09:37
Thanks @ibuziuk

Just to confirm, this problem does not happen when creating a quickstart, it happens when you import an existing codebase into OSIO and then create a workspace. Is this a bug or the intended workflow? Since it is preconfigured for a quickstart template, as you said, the fact that it doesn't happen for an imported codebase seems odd to me.

**Comment by ibuziuk** [comment] 2018-04-10 09:39
yes, you are right - there is a separate issue for launcher not to use `java-centos` stack for all manually imported projects, but rather guess project type (spring-boot / swarm etc) and use appropriate stack for it - https://github.com/openshiftio/openshift.io/issues/2358 
Could you please comment about your problem in this issue ^

**Comment by l0rd** [comment] 2018-04-10 16:09
@mishaone this is a duplicate of #2358 right? If this is case can you please close it?

**Closed** 2018-04-10 23:35 UTC
Labels: area/che, team/che, type/bug, type/question
