### ISSUE TITLE
Add and open does not open

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2995] opened 2018-04-11 06:12 UTC
Clicking Add and Open on workitems via quick add does not actually open the workitem.

It does add and I think I've seen it eventually open the workitem once or twice but it took a few seconds but here today it does not open within the first 5-10 seconds.

**Comment by nimishamukherjee** [comment] 2018-04-13 11:36
Duplicate of #2567

**Comment by sahil143** [comment] 2018-04-24 08:48
Not Duplicate of #2567

**Comment by nimishamukherjee** [comment] 2018-04-30 09:52
Fix on production. Add and open UI functionality has been fixed. 
Firefox issue is being addressed in #2285

**Closed by nimishamukherjee** 2018-04-30 09:52 UTC
Labels: SEV2-high, area/planner, team/planner
