### ISSUE TITLE
UX Enhancement: tenant indicator should be green or red

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1363] opened 2017-11-15 04:34 UTC
Every time I reset my environment, I have to wait for the tenant services to refresh. While I'm waiting, I see a white check button:

![check_icon](https://user-images.githubusercontent.com/926572/32818898-dfeedbea-ca11-11e7-80ff-b83c3bcefea3.png)

When the tenant service refresh (or some part of it) fails, the button remains white.
![status_error](https://user-images.githubusercontent.com/926572/32819965-becac4f0-ca17-11e7-9dd6-4f73e322fd33.png)

When the tenant services are successfully refreshed, this mark remains white so I have no indicator without opening it up to see each service. Example:

![check2](https://user-images.githubusercontent.com/926572/32818913-fadc34f2-ca11-11e7-9ef2-d6b69fa76346.png)

For a better UX, I would suggest that the check mark should be red when services are not ready and green when they are. This provides an easy way to see when the services are not ready (and to know that we should not be doing anything in OSIO). A green or red indicator would stand out on the interface ad immediately alert new and old users that something is wrong (red) or all is well (green).

**Comment by joshuawilson** [comment] 2017-11-15 06:15
duplicate of #674 but since it has more detail I'm keeping it open

**Comment by chrislessard** [comment] 2017-11-17 18:36
Does this mean abandoning the white icon entirely ? If not, in a situation where all the services are available and the icon is green, would it then be appropriate to change it back to white once the user has clicked on the button and seen that everything is ready ?

**Comment by joshuawilson** [comment] 2017-11-17 18:39
I think the white button should be the color and icon of the worst state. If all is green then it should be green too. 

We should confirm with @catrobson and team.

**Comment by catrobson** [comment] 2017-11-17 19:07
Unfortunately green and red icon are too thin for the color and don't show up on the dark black header, which is why it is white.  I'll talk to the team about whether we can put a indicator on the icon that there is a problem in the problem state, or at least turn the icon to the proper icon (x) if there is a problem.

**Comment by kbsingh** [comment] 2017-11-24 12:01
If its just a case of 'waiting', can we have the summary icon be the watch icon ? atleast something that isnt Tick ?

Another option might be to use an exclamation mark as a way to get the users attention.

**Comment by bdellasc** [comment] 2017-11-30 18:05
I posted a visual design proposal for this issue on [InVision](https://redhat.invisionapp.com/share/ZFEP5QKXA).

Please feel free to comment on the on the InVision project or on [visual design story](https://github.com/fabric8-ui/fabric8-ux/issues/748).

**Comment by joshuawilson** [comment] 2017-12-07 01:15
@c-koehler can you take this on as your next task

**Comment by jiekang** [comment] 2018-06-20 16:11
This feature no longer exists. Closing this issue.

**Closed by jiekang** 2018-06-20 16:11 UTC
Labels: area/status, level/beginner, status/open-for-dev, team/platform, type/SDD-feature
