### ISSUE TITLE
Intermittent/recurring issue - Workspace pod fails to start due to volume mount failures

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#2154] opened 2018-02-01 15:27 UTC
Original issue: https://github.com/redhat-developer/rh-che/issues/467
Workspace pod sometimes fails to start because "Failed Mount":
![failed](https://user-images.githubusercontent.com/1215011/35686418-83033ed8-076c-11e8-924c-b34659ebf0b3.png)
And this exception in che-server logs:
```
{"@timestamp":"2018-02-01T14:56:20.083+00:00","@version":1,"message":"Failed to get the ID of the container running in the OpenShift pod","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"WorkspaceSharedPool-5","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod
	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)
	... 11 common frames omitted
Caused by: org.eclipse.che.plugin.openshift.client.exception.OpenShiftException: Failed to get the ID of the container running in the OpenShift pod
	at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:706)
	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:648)
	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:357)
	... 13 common frames omitted
"}
```

**Comment by ibuziuk** [comment] 2018-02-01 19:27
There is not much che team can do about this problem since it is infrastructure related

**Comment by mmclanerh** [comment] 2018-02-01 19:37
@rhopp can you provide which environment you're seeing this on (prod? starter-us-east-2? starter-us-east-2a?) and a relative day/timezone+time/tenant id?

@jfchevrette can you review?

**Comment by rhopp** [comment] 2018-02-02 06:29
@mmclanerh I'm seeing this on prod (starter-us-east-2) and prod preview (free-stg).
Kibana searches for this error, where you can see the times of occurences:
Prod: https://logs.dsaas.openshift.com/goto/ce0f1dd614d4a674322616f30f5ae73a
Prod-preview: https://logs.rh-idev.openshift.com/goto/749adcbe504f0f1546fc66be3cdd68c7

I'm not sure what do you mean by tenant id. We used few accounts, for example kkanova+osiotest1 (prod&prod-preview), rhopp+osiotest1(prod), ...

**Comment by ldimaggi** [comment] 2018-03-07 04:03
I started seeing this about 80% of the time - for several hours - on March 6 - is anyone else seeing this at a greater frequency too?

**Comment by ldimaggi** [comment] 2018-03-07 04:03
Why is this a SEV3? It should be at least a SEV2.

**Comment by ldimaggi** [comment] 2018-03-09 01:58
Interesting characteristic of this problem - I've noticed a repeating pattern - after 19:00 Boston time, the problem morphs from intermittent to happening 90% of the time. I have observed this for the past few days and the pattern is consistent.

**Comment by ldimaggi** [comment] 2018-03-24 03:00
A manual test for this issue was conducted on March 23.

The test started at 22:30 (10:30PM)  Boston/EDT - 02:30 UTC (March 24).

The results were as expected:
![screenshot from 2018-03-23 22-56-42](https://user-images.githubusercontent.com/642621/37859675-ca190d40-2eed-11e8-99f5-d50d049f4f57.png)

The Che log is here:

https://console.dsaas.openshift.com/console/project/dsaas-production/browse/rc/che-16?tab=logs

The first log messages that reference the test are:
```
{"@timestamp":"2018-03-24T02:31:58.709+00:00","@version":1,"message":"Workspace
 'ldimaggi@redhat.com/march24-3js6d' with id 'workspaceoso0b9m15rh6up3u' created by user
 'ldimaggi@redhat.com'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager"
,"thread_name":"http-nio-8080-exec-4","level":"INFO","level_value":20000,"req_id":"7e7235b8-9d1c
-4c06-9ed6-edbd35e40a2e","identity_id":"20ddc23a-bb62-4834-9130-9af2f54e85b1"}
```

**Comment by ldimaggi** [comment] 2018-03-25 03:54
It looks like a consistent pattern - the problem starts at midnight UTC and lasts 3 hours.

**Comment by pbergene** [comment] 2018-03-26 07:14
@ldimaggi did you see the events related to ebs attach issues?

**Comment by ldimaggi** [comment] 2018-03-26 12:03
![screenshot from 2018-03-26 08-02-18](https://user-images.githubusercontent.com/642621/37905221-2751d3ea-30cc-11e8-8284-7fffc01ab0ed.png)

I will watch again tonight...

**Comment by ibuziuk** [comment] 2018-04-03 12:28
@rhopp were you able to reproduce this issue against che 6 ?

**Comment by maxandersen** [comment] 2018-04-04 07:40
upgrading to SEV-1 based on infom from @rhopp

**Comment by pbergene** [comment] 2018-04-04 07:55
There has been some previous efforts to reproduce / quantify / log this issue.  What I know that it is not only seen by che, but other components and that mount errors have not always been observed as events.  

Thanks @rhopp for creating a reproducer / quantification here.  Are all the errors on the spreadsheet caused by mount errors or is this unknown?  What cluster are they run against (only 2?) The reason I ask is because I am wondering if this can be isolated to EBS PVs - and not a general increase in API errors.

It is interesting that we may be seeing an increase in EBS issues at a given time and if that is the case we can inquire if there is anything known related to EBS volumes going on that can be tweaked (openshift ops or aws side),  but in that case the 'real fix' would be to move to a more reliable storage backend along with the other clusters.

**Comment by rhopp** [comment] 2018-04-04 08:13
> Thanks @rhopp for creating a reproducer / quantification here. Are all the errors on the spreadsheet caused by mount errors or is this unknown?

Not all errors in the spreadsheet are caused by the mount failure, but AFAIK all errors in the "red zone" (midnight to 3AM) are.

> What cluster are they run against (only 2?)

Yes. I can create second job to run against 2a.

**Comment by jfchevrette** [comment] 2018-04-05 20:00
The cluster is scheduled to be upgraded to Openshift 3.9 next week and Openshift engineers believe some changes in 3.9 will alleviate and possibly solve this completely. Lets test again and validate once the upgrade is done.

**Comment by kbsingh** [comment] 2018-04-06 10:58
are we keeping this as SEV1 pending for this time while we wait on oso upgrade ?

**Comment by pbergene** [comment] 2018-04-06 11:03
That's a good question. It is a matter of process we should give some thought.  It *is* impacting the service and as such a correct metric.  It is however not prompting a 'drop everything you are doing' as the upgrade window is set.

**Comment by pbergene** [comment] 2018-04-06 11:10
That's a good question. It is a matter of process we should give some thought.  It *is* impacting the service and as such a correct metric.  It is however not prompting a 'drop everything you are doing' as the upgrade window is set.

**Comment by mmclanerh** [comment] 2018-04-06 16:43
fine to leave as sev1 as this is a real/impacting ongoing problem. we should at least check in daily that we're still on track for fix expectations (which will be early next week at this time).

**Comment by pbergene** [comment] 2018-04-09 07:34
Sleep duration between snapshots tweaked from 0->2 which should relieve the API servers. Can we confirm if this has had an impact?

**Comment by ldimaggi** [comment] 2018-04-10 02:46
The situation is better - I have seen the problem occur 2 time in 5 tries tonight.

**Comment by jfchevrette** [comment] 2018-04-10 04:16
The cluster upgrade finished about midnight UTC so we should observe the next couple of days to see if this is fixed

**Comment by rhopp** [comment] 2018-04-10 08:11
The job with simple pod and mount volume is still running. Here is the data for last few days:
https://docs.google.com/spreadsheets/d/1TZQhz8vcWZnAtRpo5HKc4lKi44y8L0DXPe1PgddysfE/edit?usp=sharing

**Comment by l0rd** [comment] 2018-04-25 10:57
Apparently this issue has been found on cluster `2a` too https://github.com/openshiftio/openshift.io/issues/2154

**Comment by l0rd** [comment] 2018-04-25 17:56
@ldimaggi not more than the details that are described in #2154. But we should probably run @rhopp script against cluster `2a` too.

**Comment by ldimaggi** [comment] 2018-04-26 03:37
And - against all the additional clusters too.

**Comment by ldimaggi** [comment] 2018-07-03 19:17
Closing as no longer reproducible.

**Closed by ldimaggi** 2018-07-03 19:17 UTC
Labels: SEV2-high, area/che, issue/intermittent, team/service-delivery, type/bug
