### ISSUE TITLE
Changes to Planner shortcut bar truncate iteration title display

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2111] opened 2018-01-30 15:22 UTC
See attached screenshot - the iteration title strings are truncated - and since the user cannot resize the shortcut panel, the full text of the titles cannot be viewed. 

![screenshot from 2018-01-30 08-16-46](https://user-images.githubusercontent.com/642621/35574241-41eb56ea-05a7-11e8-8735-0036c968411e.png)

![screenshot from 2018-01-30 08-16-31](https://user-images.githubusercontent.com/642621/35574242-42003718-05a7-11e8-989a-3a48a15ad453.png)

**Comment by ldimaggi** [comment] 2018-01-30 15:36
Also, if the first 13 characters of 2 iterations titles are identical, and the iterations are both at the same level in the hierarchy, then both identical title sub-strings are displayed.

**Comment by qodfathr** [comment] 2018-01-31 14:09
@sdash-redhat is this a bug or working as designed?

**Comment by sdash-redhat** [comment] 2018-01-31 14:35
@qodfathr I do not remember that as a part of the original design last I contributed. At the first glance, to me it looks like a cosmetic issue not addressed and thought through -- for example even if the truncation happens, it should not happen this way, rather it should be explored inline with some high-level pointers mentioned here.  
Will check with Sunil and update if that is based on some design need or requirement as per some user story.

**Comment by qodfathr** [comment] 2018-02-01 18:37
Personally, I'm okay with the current implementation.

@ldimaggi this feels like a NPTF (no plan to fix) in terms of the truncation. Feel free to open a feature request for a resizable side bar, if you feel strongly about that. Does that work for you?

**Comment by ldimaggi** [comment] 2018-02-01 18:38
OK - that's fine. Thx!

**Comment by qodfathr** [comment] 2018-02-01 19:13
Closing as NPTF

**Closed by qodfathr** 2018-02-01 19:13 UTC
Labels: SEV3-medium, area/UX, area/planner, team/planner, type/bug
