### ISSUE TITLE
Intermittent build failures - s2i EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3178] opened 2018-04-18 03:46 UTC
For about 7 hours on April 17, users provisioned on starter-us-east-2 saw a consistent pattern of failed builds:  Caused by: java.net.SocketTimeoutException: timeout

The problem seemed to resolve at about 23:00 April 17 (Boston time zone).

I don't have any pod logs or events from this time period - was any maintenance being performed at this time?

```
EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:48 min
[INFO] Finished at: 2018-04-17T19:26:54+00:00
[INFO] Final Memory: 37M/72M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project testapr171523992455741: Failed to execute the build: Unable to build the image using the OpenShift build service: An error has occurred. timeout: Socket closed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project testapr171523992455741: Failed to execute the build
.
.
.
Caused by: java.net.SocketTimeoutException: timeout

***********************************************************************

EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16:43 min
[INFO] Finished at: 2018-04-17T19:04:44+00:00
[INFO] Final Memory: 36M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project testapr171523990556032: Failed to execute the build: Unable to build the image using the OpenShift build service: An error has occurred. timeout: Socket closed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project testapr171523990556032: Failed to execute the build
.
.
.
Caused by: java.net.SocketTimeoutException: timeout

***********************************************************************

EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:29 min
[INFO] Finished at: 2018-04-18T02:47:32+00:00
[INFO] Final Memory: 41M/61M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project testapr171524018349785: Failed to execute the build: Unable to build the image using the OpenShift build service: An error has occurred. timeout: Read timed out -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project testapr171524018349785: Failed to execute the build
.
.
.
Caused by: java.net.SocketTimeoutException: timeout

```

**Comment by ppitonak** [comment] 2018-04-18 12:35
I could reproduce on the first try.

**Comment by ldimaggi** [comment] 2018-04-18 17:01
Are all users on the cluster affected?

**Comment by mishaone** [comment] 2018-04-19 02:16
Update, tested due to len's request. I'm on east-2 and it works.

**Comment by ldimaggi** [comment] 2018-04-19 11:59
https://github.com/fabric8io/fabric8-test/pull/612

**Comment by ldimaggi** [comment] 2018-04-19 16:02
Seeing this on prod-preview too:

![screenshot from 2018-04-19 12-01-36](https://user-images.githubusercontent.com/642621/39003755-89b022b6-43c9-11e8-8f86-91226b5620db.png)

**Comment by ldimaggi** [comment] 2018-04-19 16:14
The pattern is consistent - the error is:
```
[INFO] F8: Adding to ImageStream app-test-1
[INFO] F8: Starting Build app-test-1-s2i
EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
```

**Comment by Katka92** [comment] 2018-04-20 07:33
I've seen this today on openshift.io too.

**Comment by ldimaggi** [comment] 2018-04-20 14:12
Seeing it today too - it was not happening late last night - perhaps tied to system load?

```
[INFO] F8: Creating BuildServiceConfig app-test-1-s2i for Source build
[INFO] F8: Creating ImageStream app-test-1
[INFO] F8: Starting Build app-test-1-s2i
EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
```

**Comment by rohanKanojia** [comment] 2018-04-25 15:41
Duplicate of #3058

**Comment by rohanKanojia** [comment] 2018-04-25 15:44
Closing as duplicate

**Closed by rohanKanojia** 2018-04-25 15:44 UTC
Labels: SEV2-high, area/quickstarts, priority/P0, type/bug
