### ISSUE TITLE
  Deployments -> POD the collapsing feature may be  not clear for some users (improvent)

### ISSUE THREAD

**Issue by musienko-maxim** [openshiftio/openshift.io#2658] opened 2018-03-16 15:06 UTC
![selection_006](https://user-images.githubusercontent.com/1640058/37528096-621c82f0-293c-11e8-912a-c04c9a7ef4a9.png)

**Comment by aptmac** [comment] 2018-03-16 15:10
Related to: https://github.com/openshiftio/openshift.io/issues/2226

**Comment by andrewazores** [comment] 2018-03-20 18:02
Closing as duplicate of #2226 .

**Closed by andrewazores** 2018-03-20 18:02 UTC
Labels: area/deployments, team/platform, type/feature-request
