### ISSUE TITLE
Forge wizard: pipeline selection page UI is broken in narrow window

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#540] opened 2017-08-10 10:27 UTC
Wizard is too narrow, so pipeline selection section over is overflowing. See screenshot:
![image](https://user-images.githubusercontent.com/1215011/29166571-3e68cbb4-7dc7-11e7-9912-2259272834d0.png)
Browser is Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by rhopp** [comment] 2017-08-10 10:28
I probably started the wizard, when I had browser on my rotated display (90 degrees, so it is long and narrow)

**Comment by joshuawilson** [comment] 2017-08-14 01:41
@mindreeper2420 can you please take a look at this.

**Comment by mindreeper2420** [comment] 2017-08-16 17:14
@joshuawilson this is most likely caused by the pipeline section being a fixed width and static assets and the modal is fluid by nature. It was never intended for screens taller than they are wide, so all of those pieces should be taken into account when the wizard is refreshed.

**Comment by corinnekrych** [comment] 2017-10-11 13:31
fixed in https://github.com/openshiftio/openshift.io/issues/966

**Closed by corinnekrych** 2017-10-11 13:31 UTC
Labels: area/app-wizard, area/UX, kind/bug, team/platform
