### ISSUE TITLE
In production, after env reset, infinite loop of websocket errors seen - quickstart pipeline creation fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2200] opened 2018-02-07 20:52 UTC
Steps to recreate:
* Reset user env
* Observe Chrome browser log for repeated series of these errors:
```
WebSocket connection to 'wss://openshift.io/oapi/v1/namespaces/ldimaggi/builds?watch=true
&access_token=.......................................token removed before this issue is logged..................' 
failed: Error during WebSocket handshake: Unexpected response code: 200
```
Impact to user - if a new quickstart is then created, the pipeline for the quickstart is not created. This error is written to the browser console log:

```
_formulas.less:2 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.Body.json (_formulas.less:2)
    at MapSubscriber.project (_formulas.less:2)
    at MapSubscriber._next (patternfly.min.css:1)
    at MapSubscriber.Subscriber.next (patternfly.min.css:1)
    at XMLHttpRequest.a (_formulas.less:2)
    at XMLHttpRequest.wrapped (_formulas.less:2)
    at ZoneDelegate.invokeTask (polyfills.68242bc73dcace7ef76e.bundle.js:1)
    at Object.onInvokeTask (patternfly.min.css:1)
    at ZoneDelegate.invokeTask (polyfills.68242bc73dcace7ef76e.bundle.js:1)
    at Zone.runTask (polyfills.68242bc73dcace7ef76e.bundle.js:1)
    at ZoneTask.invokeTask [as invoke] (polyfills.68242bc73dcace7ef76e.bundle.js:1)
    at p (polyfills.68242bc73dcace7ef76e.bundle.js:1)
    at XMLHttpRequest.h (polyfills.68242bc73dcace7ef76e.bundle.js:1)
```

**Comment by ldimaggi** [comment] 2018-02-07 21:05
Issue found/encountered by EE tests.

**Comment by aslakknutsen** [comment] 2018-02-07 22:22
This has been observed unrelated to env reset

**Comment by ldimaggi** [comment] 2018-02-07 23:10
Have you seen this only in the past 2-3 days? Or at other times?

**Comment by ldimaggi** [comment] 2018-02-08 02:42
Verified that this is fixed in production. Closing.

**Comment by aslakknutsen** [comment] 2018-02-08 15:02
@joshuawilson It's the UI using some 'random' URL for some reason. Wondering if this could somehow be related to the init order issue @dgutride was talking about. 'Sometimes' some component come up before the URL env is loaded and ends up using a wrong url?

**Comment by ldimaggi** [comment] 2018-02-08 15:07
It looks like tis problem is resolved - or is that only the impression that I am getting? Is this a random issue that I have simply not seen in the past 10 hours?

**Comment by joshuawilson** [comment] 2018-02-08 15:31
@aslakknutsen we need to dig into it. we put a hack in place to fix it, but I want to get it done right.

**Comment by aslakknutsen** [comment] 2018-02-08 18:21
@joshuawilson @ldimaggi Ok, if there is a hack in place it might have fixed it

**Comment by aslakknutsen** [comment] 2018-02-14 20:22
Similar seen yesterday

```
VM374:164 WebSocket connection to 'wss://openshift.io/oapi/v1/projects?watch=true&access_token=xxx' failed: Error during WebSocket handshake: Unexpected response code: 200
WrappedWebSocket	@	VM374:164
$WebSocket.connect	@	_scrollbars.less:6
$WebSocket	@	_scrollbars.less:6
Watcher.lazyCreateWebSocket	@	_scrollbars.less:6
Watcher	@	_scrollbars.less:6
WatcherFactory.newInstance	@	_scrollbars.less:6
KubernetesService.watch	@	_scrollbars.less:6
KubernetesResourceStore.doLoadAll	@	_scrollbars.less:6
KubernetesResourceStore.loadAll	@	_scrollbars.less:6
SpaceStore.doLoad	@	_scrollbars.less:6
SpaceStore.load	@	_scrollbars.less:6
(anonymous)	@	environment-widget.component.ts:59
SafeSubscriber.__tryOrSetError	@	patternfly.min.css:1
SafeSubscriber.next	@	patternfly.min.css:1
Subscriber._next	@	patternfly.min.css:1
Subscriber.next	@	patternfly.min.css:1
ReplaySubject._subscribe	@	patternfly.min.css:1
Observable._trySubscribe	@	patternfly.min.css:1
Subject._trySubscribe	@	patternfly.min.css:1
Observable.subscribe	@	patternfly.min.css:1
EnvironmentWidgetComponent.ngOnInit	@	environment-widget.component.ts:53
```

**Comment by joshuawilson** [comment] 2018-02-14 20:31
hmm, is it still a SEV1?
how did you reproduce it? just make a new app from a quickstart?

**Comment by aslakknutsen** [comment] 2018-02-16 15:33
Refresh a few times. You can also see that links from pipeline view points to openshift.io from time to time instead of oso.

Is it a sev1 that the UI is completely off every n request.. :man_shrugging:

**Comment by pbergene** [comment] 2018-02-19 12:41
Looks like sev-1 label was from before it was re-opened.  This obviously should be fixed, for the sake of the experience, but also having our tests succeed..   I don't consider it a complete blocker as there is a workaround, so not really a sev-1.   On the last call we agreed to see if this was caught in error tracking and if that could give us some idea on the frequency this is occurring.  Will bring it up on the sev-1 triage to further assess the impact, but reducing to sev-2 and will increase back to sev-1 if we're seeing it more often than not.

**Comment by ldimaggi** [comment] 2018-02-25 15:15
Have not seen this for several days - is this a coincidence or did we address the issue?

**Comment by joshuawilson** [comment] 2018-02-25 21:30
we did not fix this, it is a race condition so you need to refresh multiple times to see it

**Comment by jiekang** [comment] 2018-04-03 21:00
Has anyone seen similar recently?

The most recent logs from Aslak are now invalid as the EnvironmentsWidget no longer uses the a-runtime-console work to acquire data. Instead it uses the DeploymentsService work.

**Comment by joshuawilson** [comment] 2018-04-04 02:24
I believe this is caused by a race condition described above. Until we resolve the cache issues this will still exist.

**Comment by jiekang** [comment] 2018-04-09 14:01
Just saw this today on production:

```
VM36:164 WebSocket connection to 'wss://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/oapi/v1/namespaces/jkang/builds?watch=true&access_token=<token>' failed: Received a broken close frame containing a reserved status code.

```

![close-websocket](https://user-images.githubusercontent.com/5430520/38502016-5582346a-3bdc-11e8-98f1-72a77fabd440.png)

Might be worth a new issue though...

**Comment by jiekang** [comment] 2018-04-09 14:27
Race condition found in `oauth-config-store.ts`:

```
  load() {
    // we only need to load once really on startup
    if (_startedLoadingOAuthConfig) {
      return;
    }
    _startedLoadingOAuthConfig = true;
    let configUri = '/_config/oauth.json';
    this.http.get(configUri)
      .subscribe(
        (res) => {
          let data = res.json();
          for (let key in data) {
            let value = data[key];
            if (value === 'undefined') {
              data[key] = '';
            }
          }
          _latestOAuthConfig = new OAuthConfig(data);
          if (this.userService.currentLoggedInUser.attributes) {
            let cluster = this.userService.currentLoggedInUser.attributes.cluster;
            let console = cluster.replace('api', 'console');
            _latestOAuthConfig.openshiftConsoleUrl = console + 'console';
          }
          _currentOAuthConfig.next(_latestOAuthConfig);
          _loadingOAuthConfig.next(false);
        },
        (error) => {
          console.log('Could not find OAuth configuration at " + configUri + ": ' + error);
          _currentOAuthConfig.next(_latestOAuthConfig);
          _loadingOAuthConfig.next(false);
        });
  }
```

The OAuthConfig is loaded via above function. The `http.get` call is asynchronous. The latest oauthconfig is valid after ` _latestOAuthConfig = new OAuthConfig(data);`

The race condition can be forced by adding a `delay` call to `http.get`. Ie.

`http.get(...).delay(10000).subscribe(...)`

I think the person who wrote the design intended users to wait for loading to be complete before using _latestOAuthConfig but it looks like either the design is not functioning as intended, or there are certain users not subscribed and waiting for the `_loadingOAuthConfig.next(false);` event before continuing.

**Comment by jiekang** [comment] 2018-04-09 14:30
Looks like many users are directly accessing `_latestOAuthConfig` via the exported function
```
export function currentOAuthConfig() {
  return _latestOAuthConfig;
}
```

instead of the

```
let _currentOAuthConfig: BehaviorSubject<OAuthConfig> = new BehaviorSubject(_latestOAuthConfig);
let _loadingOAuthConfig: BehaviorSubject<boolean> = new BehaviorSubject(true);
```

system. Nice.

**Comment by jiekang** [comment] 2018-04-26 14:45
@aslakknutsen 

I think this was changed to sev1 because of https://github.com/openshiftio/openshift.io/issues/3315 but my analysis of 3315 shows it's actually a different issue in the same area. Fixing this race issue 2200 will not affect 3315. I think this is actually sev2. Thoughts?

**Comment by pbergene** [comment] 2018-04-27 12:55
Automatically closed, not fixed on prod.

**Comment by jiekang** [comment] 2018-04-30 14:26
@joshuawilson do you know if production has been updated? I think this can be closed.

**Comment by joshuawilson** [comment] 2018-04-30 14:40
@jiekang production has been updated, can you verify this is fixed.

**Comment by joshuawilson** [comment] 2018-04-30 14:42
This code has been merged, closing. If you see it again, please reopen.

**Closed by joshuawilson** 2018-04-30 14:42 UTC
Labels: SEV1-urgent, area/pipelines, priority/P0, team/platform, type/bug
