### ISSUE TITLE
fabric8-analytics API server uses half a CPU core even though there is no traffic [prod-preview]

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1463] opened 2017-11-27 12:51 UTC
Originally reported by @jfchevrette on the ML (thanks 😉 )

bayesian-api pod running on rh-idev uses half a CPU core while doing nothing:

![bayesian-cpu](https://user-images.githubusercontent.com/3759039/33267279-21169372-d379-11e7-8501-ea476632a1b2.png)
![bayesian-cpu-graph](https://user-images.githubusercontent.com/3759039/33267282-23df4482-d379-11e7-8731-07f08241052e.png)

Both prod and prod-preview are running the same image: `registry.devshift.net/bayesian/bayesian-api:34382bc`.

prod is not affected, from some reason.

**Comment by msrb** [comment] 2017-11-27 12:51
cc @samuzzal-choudhury

**Comment by krishnapaparaju** [comment] 2018-01-04 04:22
@pkajaba please update this issue with your thoughts..

**Comment by pkajaba** [comment] 2018-01-04 08:32
@krishnapaparaju I was looking into it before the holidays and seems to be stabilized. It's using just about 0.18 core.

**Comment by msrb** [comment] 2018-01-04 09:45
It would be great to have at least some idea what may have caused this. But if it's not reproducible any more, it won't be trivial. I know this is long time ago, but are we sure we weren't just doing some stress testing at the time? Maybe @samuzzal-choudhury or @tisnik could know (?).

**Comment by krishnapaparaju** [comment] 2018-01-12 06:32
Closing this issue as its not been reproducible..

**Closed by krishnapaparaju** 2018-01-12 06:32 UTC
Labels: SEV2-high, status/open-for-dev, team/analytics, team/analytics/core, team/analytics/integration, type/bug
