### ISSUE TITLE
Incorrect link to a Jenkins service in a commit status

### ISSUE THREAD

**Issue by garagatyi** [openshiftio/openshift.io#3030] opened 2018-04-12 06:28 UTC
When I push commits in Che I see that there is a commit status badge on Github which means that it is configured to show a status of a build on Jenkins. But the link is broken - looks like Jenkins integration is not fully configured.

BTW triggering of a build by webhook from Github doesn't work also.

Here is my git repo https://github.com/garagatyi/clicktest
Webhook URL is https://jenkins.openshift.io/github-webhook/
On the Github repo webhook page, I see that webhook notifications for all my commits were successfully delivered. Their IDs (if it is somewhat helpful for investigating):
95e577a2-3e15-11e8-9444-057fc5e475f8
e9453daa-3e16-11e8-9576-f758991ee8d9

![image](https://user-images.githubusercontent.com/1851863/38659238-515fd19c-3e31-11e8-8868-fb5cb5697970.png)

**Comment by piyush1594** [comment] 2018-06-20 04:18
Duplicate of #1259 Can we close this issue? @sthaha @garagatyi

**Comment by piyush1594** [comment] 2018-06-20 12:57
Closing this.

**Closed by piyush1594** 2018-06-20 12:57 UTC
Labels: SEV2-high, area/jenkins, area/pipelines, team/build-cd, type/bug
