### ISSUE TITLE
404 on 'Space' view when side panel is open

### ISSUE THREAD

**Issue by TimMoran** [openshiftio/openshift.io#1480] opened 2017-11-29 18:39 UTC
If you're on a space (ex. https://openshift.io/timoran/Tim-Demo) and you click on the codebase + symbol to open the side panel.. if you try to click "my work items" with the panel open it will throw a 404

**Comment by TimMoran** [comment] 2017-11-29 19:04
I can't add labels it seems:

team/platfrom area/dashboard

**Comment by c-koehler** [comment] 2017-12-07 13:10
@joshuawilson @dgutride If you guys have any input on the following it would be great:

This can be easily fixed by changing the **(+)** button on the analyze page to use:
`... [routerLink]="[contextPath, 'create', { outlets: { action: 'add-codebase' } }]" ..."`
instead of
`...[routerLink]="[{ outlets: { action: 'add-codebase' } }]" ...`
as this will take you to the codebases page and open up the action outlet as the user would want to do.


However, I'm not sure if there's a better way... which I want to discuss:

After a discussion with @joshuawilson I was directed to understanding both the router in depth and lazy loading, and subsequently a bunch of research believe I found out what the issue is.

When we open the action auxiliary to have the codebase, my guess was that the addition of this to the URL was bad and causing the issues. After reading a post by the [creator of Angular in response to a bug](https://github.com/angular/angular/issues/9957), the links the routerLink provides us _should_ work, but they don't...

After visiting the create/codebases page, all the links on that page end up working properly and you can change between pages with the slider panel being present without any issues. Further, the navigation bar (the black one at the top, or insert proper name for this here) is also fine.

To keep it brief, it looks like the routerLink only adds the action link to paths that match the path it was invoked from, and since on the analyze page it's coming from `localhost:3000/chkoehle/testspace/` then any link that has this as a base will be mutated with the action. Unfortunately this affects every link on the page, if you add any link in that deviates from the base of that (ex: `localhost:3000/chkoehle/someOtherSpace/`, a github link, etc) then it will not be touched. This causes it to affect the buttons at the top, which isn't great, as they all share the entity space in the URL. This did not affect the create/codebases pages because the URL is `localhost:3000/chkoehle/testspace/create`, which does not match up with any of the URLs on the page (and therefore the links are normal).

As to what is causing the issue, my best guess is that due to lazy loading and having auxiliary routes... we're getting [this unfixed bug](https://github.com/angular/angular/issues/9957) (happens to be the same as the link before), which in short occurs in a situation where you lazy load modules and try doing auxiliary paths when you have blank paths in your routing hierarchy. This appears to not be fixed even in angular 5, and I have no idea if the developers will ever fix it.

Is there something obvious that I'm missing?

I just want to make sure I've not skipped over something obvious and go further down this path. I have no issue trying to explore the idea of ripping apart the router and trying to fix it based on whatever people posted in that issue... this is assuming that I am correct and having missed something obvious.

**Comment by joshuawilson** [comment] 2017-12-07 18:46
@c-koehler your observations make sense. I would need to spend the time digging into it to find anything else. Does your purposed fix work?

**Comment by c-koehler** [comment] 2017-12-07 19:30
@joshuawilson yes it will redirect you to the codebases page and bring out the slider correctly.

**Comment by joshuawilson** [comment] 2018-01-12 04:08
@c-koehler what is the status on this?

**Comment by c-koehler** [comment] 2018-01-12 14:24
@joshuawilson I can make this into a PR. I'm not sure if you found anything from digging around, if not I can make a PR with the fix if that's okay with you.

**Closed** 2018-01-18 02:01 UTC
Labels: SEV2-high, area/dashboard, level/beginner, status/open-for-dev, team/platform, type/bug
