### ISSUE TITLE
Intermittent issue - user provisioned on starter-us-east-2  - Che workspace does not start automatically

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3135] opened 2018-04-15 02:48 UTC
Probably related to https://github.com/redhat-developer/rh-che/issues/629

This might be related to #2154 - have not yet observed an identifiable pattern - but seeing this late in the evening on April 14.

Steos to recreate:
* Create a new quickstart/app
* Attempt to create a new Che workspace
* Observe the workspace is not created - "Workspace is not running"

![screenshot from 2018-04-14 22-21-52](https://user-images.githubusercontent.com/642621/38774302-d489c574-4033-11e8-8ffd-74093a7cb2bf.png)

After the user presses the "start" button - the workspace starts.

From the Che log:
```
{"@timestamp":"2018-04-15T02:18:54.327+00:00","@version":1,"message":"Workspace
 'ldimaggi@redhat.com/april15-pxnkx' with id 'workspace62oml6oku6ou5a7u' created by user
 'ldimaggi@redhat.com'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager",
"thread_name":"http-nio-8080-exec-8","level":"INFO","level_value":20000,"req_id":
"97189ea5-df44-475a-acde-5ca5834b3345","identity_id":"20ddc23a-bb62-4834-9130-9af2f54e85b1"}
```

#

**Comment by ibuziuk** [comment] 2018-04-16 09:00
@ldimaggi could you provide openshift events ? Does pressing start button starts the workspace ?

**Comment by ibuziuk** [comment] 2018-04-16 13:29
@ldimaggi could we close it as a duplicate of https://github.com/openshiftio/openshift.io/issues/3103 ?
Those two seems to be identical

**Comment by ldimaggi** [comment] 2018-04-16 23:27
The problem shows the same dialog as #3103 to the user - but - unlike #3103, this errors occurs when there are no/few active users.

**Comment by ibuziuk** [comment] 2018-04-19 09:13
@ldimaggi in this case, could you please provide openshift events?

**Comment by ldimaggi** [comment] 2018-04-20 15:48
Looking for the issue now - this has not been seen for a few days.

**Comment by ibuziuk** [comment] 2018-04-30 09:38
@rhopp PR with removal startup logic is available on prod-preview / workspace auto start is also set to true on prod-preview osd. Could you please verify ?

**Comment by rhopp** [comment] 2018-04-30 13:32
Had a short glimpse (because some networking issues we had here) at this and so far so good. If needed, I can do some more heavy-duty testing on wednesday. Otherwise you have my +1.

**Comment by ibuziuk** [comment] 2018-05-01 13:31
@l0rd this would require updating `rhche` cm (enabling auto-start), we could probably request updating cm right now (but not restarting deployment) and do rhche update once applying  https://github.com/openshiftio/openshift.io/issues/1614 (will need to do che-starter & rhche update simultaneously though) WDYT ?

**Comment by l0rd** [comment] 2018-05-01 20:05
@ibuziuk makes sense. Let's update cm in prod right away and then redeploy when #1614 is ready (we could also do tomorrow).

**Comment by ibuziuk** [comment] 2018-05-04 15:57
@ldimaggi @rhopp @ScrewTSW fixed on prod - could you please verify & close

**Comment by ScrewTSW** [comment] 2018-05-04 16:54
@ibuziuk @ldimaggi @l0rd Confirmed working on prod now as well 👍

**Closed** 2018-05-04 16:55 UTC
Labels: SEV2-high, area/che, priority/P0, team/che/osio, type/bug
