### ISSUE TITLE
Analytics API responds with HTTP error 500 for unauthorized requests

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4372] opened 2018-10-01 12:49 UTC
##### Issue Overview
When analytics API endpoint `/stack-analyses` or `component-analyses` is called with an invalid OSIO token, the API responds with HTTP 500 (Internal Server Error) instead of the expected response code 401 (Unauthorized)

This inconsistent behaviour affects the user experience of the consumers of this service and requires immediate rectification.

cc: @miteshvp @sivaavkd

**Comment by sivaavkd** [comment] 2018-10-01 12:52
Hi @humaton , based on my discussion with Sam, this is very critical and hence appreciate working on this asap cc @GeorgeActon

**Comment by humaton** [comment] 2018-10-01 13:41
This is a problem in handling Exceptions on the side of API server. I am working on a fix.

**Comment by humaton** [comment] 2018-10-01 13:58
I am not able to reproduce it on prod-preview. 
All I get is correct error message: { "error": "Authentication failed - could not decode JWT token"}

**Comment by humaton** [comment] 2018-10-02 09:38
hotfix https://github.com/fabric8-analytics/fabric8-analytics-server/pull/387

**Comment by humaton** [comment] 2018-10-09 07:50
This should be fixed.

**Closed by humaton** 2018-10-09 07:50 UTC
Labels: SEV2-high, area/analytics, priority/P2, team/analytics, type/bug
