### ISSUE TITLE
Multiple home UIs rendered vertically

### ISSUE THREAD

**Issue by lstant** [openshiftio/openshift.io#3153] opened 2018-04-16 14:10 UTC
I'm not sure how I got into this state. I had just created a new space, imported code and was waiting for a Che workspace to start. I went back to the home view and tried to create a new space. Instead of seeing a dialog appear, I just saw the modal backdrop show up, preventing interaction with the UI. I think I tried refreshing the UI and the vertical rendering occurred multiple times but the backdrop never left.

![screenshot from 2018-04-16 08-50-50](https://user-images.githubusercontent.com/15789686/38813701-4e0dfbbe-4155-11e8-9813-e9d3e3d310bf.png)

**Comment by joshuawilson** [comment] 2018-04-17 00:33
I can't reproduce it using the steps you listed. Are you able to?

**Comment by christianvogt** [comment] 2018-06-20 14:23
Closing unreproducible. Feel free to reopen / raise a new issue if it happens again.

**Closed by christianvogt** 2018-06-20 14:23 UTC
Labels: SEV3-medium, area/dashboard, area/navigation, team/platform, type/bug
