### ISSUE TITLE
Build is not working while creating a quickstart in an organization

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#3319] opened 2018-04-26 10:20 UTC
While creating a quickstart I found that build is not working when we use a git organization though it's working when we select the github username.
![s](https://user-images.githubusercontent.com/7105965/39300431-46eeed86-4969-11e8-811c-b664a1b51d28.png)

**Comment by ldimaggi** [comment] 2018-04-26 13:46
It sounds like you are also seeing this issue - https://github.com/openshiftio/openshift.io/issues/3315

If this is the case - can you close #3319 as a duplicate of #3315?  Thx!

**Closed** 2018-04-27 11:42 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, team/analytics/wizard
