### ISSUE TITLE
Error marks are shown in Che editor and slow to be resolved 

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#3336] opened 2018-04-27 07:07 UTC
## Description
Che editor is showing error marks in the gutter while the project build and run properly. 
Even after doing a Maven > Reimport, the errors are still displayed. 

![screen shot 2018-04-26 at 14 59 44](https://user-images.githubusercontent.com/1636769/39349184-54837106-49fa-11e8-8f58-8a4dc0284f13.png)

Eventually, but this does not work all the time:
- after closing and reopening the file, the errors are gone
- after opening the `pom.xml` errors are gone

### Steps to reproduce
1. Create a new space and a new application
2. Select Vert.X runtime and any of the booster
3. Go on codebase, open the workspace
4. After the workspace is started, open one of the java file
5. See the error marks displayed in the left gutter of the editor
6. Even if you wait, close-reopen the file, the errors are still displayed.

**Comment by ldimaggi** [comment] 2018-04-27 11:09
I have also seen this at least once - but have not been able to reproduce it too.

**Comment by ibuziuk** [comment] 2018-04-27 15:02
Still able to repro after update from `6.3.0` to `6.4.1` on prod, the issue disappears after 10-20 seconds, it looks like it takes some time for compiling & AST generation. Need to check if the same is reproducible on minishift with the project. Potentially adding more ram to wsagent could improve the situation

**Comment by ibuziuk** [comment] 2018-04-27 16:06
Was able to reproduce the same behaviour with single-tenant upstream che deployed on dev cluster

**Comment by slemeur** [comment] 2018-04-30 16:33
@ibuziuk Do you have an update on this issue ?

**Comment by ibuziuk** [comment] 2018-05-01 13:13
@slemeur I am able to reproduce the very same problem on minishift against latest che-server image. tuning  `workspaces-memory-limit / workspaces-memory-request / che-workspaces-java-opts` does not seem to help so far. Going to open an issue upstream since we need someone from IDE team to give us a hand with this problem.

**Comment by ibuziuk** [comment] 2018-05-02 07:56
@slemeur upstream issue created - https://github.com/eclipse/che/issues/9581
btw, could we reword the title `s/never resolved/resolved after sometime` ?

**Comment by ibuziuk** [comment] 2018-05-02 09:58
@slemeur it looks like you have already created vertx workpace with all dependencies already downloaded in local m2. but for newly created workspace there should be the same issue.
Basically, it looks like the booster versions we build in our recipes is obsolete [1]. 

The version of quickstart we are using  is https://raw.githubusercontent.com/openshiftio/booster-catalog/v10/rest-http/vert.x/vertx-http-booster.yaml  Basically, what we need is reference to repo & tag / branch and I there is such kind of file with metadata  in https://github.com/fabric8-launcher/launcher-booster-catalog

[1] https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/vertx/init-maven.sh#L36

**Comment by ldimaggi** [comment] 2018-05-03 17:59
Looks like it has been fixed - cannot recreate the problem.

**Comment by ldimaggi** [comment] 2018-05-07 03:16
Seeing this again tonight:

![screenshot from 2018-05-06 23-13-23](https://user-images.githubusercontent.com/642621/39683438-772547a8-5183-11e8-9759-364325011b40.png)

**Comment by ibuziuk** [comment] 2018-06-07 13:28
@ldimaggi are you sure it is still reproducible? If yes, please, provide detailed steps to reproduce

**Comment by ibuziuk** [comment] 2018-08-21 06:16
@ldimaggi @rhopp closing this one since https://github.com/redhat-developer/rh-che/issues/670 is resolved and up-to-date version of images with quickstarts is build as part of https://ci.centos.org/job/devtools-eclipse-che-build-dockerfiles/
Also there is a separate issue for QA team for adding tests related to this issue - https://github.com/redhat-developer/che-functional-tests/issues/269

**Closed by ibuziuk** 2018-08-21 06:16 UTC
Labels: SEV3-medium, area/che, issue/intermittent, priority/P4, status/pending-qa-verification, team/che/ide1, type/bug
