### ISSUE TITLE
Should .vertx folder be handled differently in Che?

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1294] opened 2017-11-06 17:56 UTC
In Che, after you run an Eclipse Vert.x app generated by the Quickstart, a .vertx folder is created and it's not controlled by git. It appears in the Projects Explorer with a red X -- which appears to the casual observer to be some sort of error which should be addressed:
![image](https://user-images.githubusercontent.com/16322190/32455794-600afa84-c2f1-11e7-9f75-931e239c37bf.png)
Not sure what the right solution is. Is there a meaningful reason for this folder to be displayed at all? If not, does .gitignore or some other Che-specific file help to hide it? If .gitignore is the answer, is this an issue for upstream RHOAR?

**Comment by ibuziuk** [comment] 2017-11-07 18:46
@eivantsov any ideas about this issue. I believe `.vertx` folder is mainly used for hot deployment and should not be exposed to the end user on osio (smth. similar to `.git` folder) ? 

![image](https://user-images.githubusercontent.com/1461122/32511535-50db19be-c3f4-11e7-8a70-8c10ff831cf9.png)

**Comment by slemeur** [comment] 2017-11-10 12:19
+1. We should not show that folder. 

The project explorer show all the sub-folders of `/projects` - it does not take into account if the folder is hidden or not and I think that's the issue. 

Created the upstream issue: https://github.com/eclipse/che/issues/7302

**Comment by ibuziuk** [comment] 2018-04-23 09:44
In Che 6 vert.x folder is still shown, but there is no red-cross anymore. Also, the folder color is faded which probably means hidden (?) :
![image](https://user-images.githubusercontent.com/1461122/39118476-c8eaf276-46e9-11e8-9e8f-57bb261de0eb.png)

Technically speaking there are two `.vertx` folders one is in the root of the project and the second one is on the same level as a project. The one which is inside of the project is handled correctly and can be displayed / hidden via `Project` -> `Show/Hide hidden files` (by default it is hidden):

![image](https://user-images.githubusercontent.com/1461122/39118933-ef8bedd0-46ea-11e8-9ac9-3ae9741b88c3.png)

@slemeur It looks like in order to handle this particular vertx case there should be some property for showing / hiding hidden files on workspace level. Not sure if it is really crucial since there is no red cross on the folder anymore and in general behaviour looks consistent. WDYT can this one be closed ?

**Comment by eivantsov** [comment] 2018-04-23 12:02
A couple of related PRs https://github.com/eclipse/che/pull/9193 and https://github.com/eclipse/che/pull/8928

Looks like it happens only when the folder is actually created. Page refresh helps, but it is not an expected bahavior

**Comment by rhopp** [comment] 2018-08-31 11:39
The reopened issue is already resolved (by this PR https://github.com/eclipse/che/pull/9522). I've tried to reproduce this bug on che.openshift.io without any success. Closing this issue.

**Closed by rhopp** 2018-08-31 11:39 UTC
Labels: SEV4-low, area/che, priority/P4, team/che, team/che/ide1, type/bug
