### ISSUE TITLE
Errored maven pods preventing builds

### ISSUE THREAD

**Issue by pbergene** [openshiftio/openshift.io#2973] opened 2018-04-10 08:15 UTC
ppalaga 9:51 AM My pipeline waits for a Jenkins slave forever https://console.starter-us-east-2.openshift.com/console/project/ppalaga/browse/pipelines/wildfly-camel-example-camel-cdi/wildfly-camel-example-camel-cdi-13?tab=details

ppalaga: there is "INFO: Total container cap of 10 reached, not provisioning: 11 running or errored in namespace ppalaga-jenkins" in the stdout of jenkins

Looking in the namespace there are 11 errored maven pods: 
NAME                         READY     STATUS    RESTARTS   AGE
content-repository-1-z82n9   1/1       Running   0          10h
jenkins-1-8bxrh              1/1       Running   0          10h
maven-21t8s                  0/1       Error     0          11h
maven-4b4l2                  0/1       Error     0          11h
maven-4txkb                  0/1       Error     0          10h
maven-7fzl4                  0/1       Error     0          10h
maven-9vdpf                  0/1       Error     0          10h
maven-cbkxm                  0/1       Error     0          10h
maven-hhb0z                  0/1       Error     0          10h
maven-ndsmt                  0/1       Error     0          11h
maven-nkkjv                  0/1       Error     0          11h
maven-nm59q                  0/1       Error     0          10h
maven-q2bvr                  0/1       Error     0          10h

@ppalaga please supply any relevant additional information

/cc @rupalibehera

**Comment by pbergene** [comment] 2018-04-10 08:30
As a data point - after these were deleted there are only 3 errored pods on starter-us-east-2 total

**Comment by jaseemabid** [comment] 2018-04-10 09:37
@pbergene AFAIU, this is the k8s plugin not cleaning up the pods reliably all the time and we don't have any solution for this atm.

**Comment by ppalaga** [comment] 2018-04-10 09:50
I have no detailed steps to reproduce. I can only try to recollect what I did in recent days:

* On Friday Apr. 6th, I have reset my OSIO account
* Since then, I have worked on this single quickstart for wildfly-camel: https://github.com/ppalaga/wildfly-camel-example-camel-cdi
* I have changed the quickstart in various ways, incl. Jenkinsfile, and fabricate-maven-plugin. 
* At some point, I have stopped using OSIO in favor of minishift to get faster feedback. 
* I was force-pushing to the git repo often and I have not looked at the OSIO/OSO console at all. This is probably how the failed Jenkins slaves came to existence.
* I noticed the symptoms described above today Tue Apr. 10th when I returned to OSIO to see if my quickstart works there.

**Comment by piyush1594** [comment] 2018-06-20 06:14
@jaseemabid Is this possible to fix this in the current build.now and also is this important to fix this in build.now?

**Comment by piyush1594** [comment] 2018-07-30 07:07
@sthaha @hrishin This needs to be resolved.

**Comment by hrishin** [comment] 2018-07-30 07:47
@piyush1594 Yes, I would say. It could affect OSIO on OSIO as well if an issue still persists.

**Comment by sthaha** [comment] 2018-07-30 13:50
I am bumping up the priority of this bug since this can stop all builds to break for a user.

**Comment by Azulinho** [comment] 2018-08-14 09:04
same issue here, from the pod logs it looks the same as: https://issues.jenkins-ci.org/browse/JENKINS-45910 ?

**Comment by kishansagathiya** [comment] 2018-08-23 03:54
But https://issues.jenkins-ci.org/browse/JENKINS-45910 has been resolved. Were we able to reproduce this recently?

**Comment by kishansagathiya** [comment] 2018-10-09 04:16
Resolved with 
https://github.com/fabric8io/osio-pipeline/pull/50
https://github.com/fabric8io/fabric8-pipeline-library/pull/434
https://github.com/fabric8-jenkins/jenkins-openshift-base/pull/47

**Closed by kishansagathiya** 2018-10-09 04:16 UTC
Labels: SEV2-high, area/jenkins, area/pipelines, priority/P2, sprint/current, team/build-cd, type/bug
