### ISSUE TITLE
Run E2E tests against f8a deployments at OSIO

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1522] opened 2017-12-07 03:58 UTC
**# User story**

 For all F8 Analytics deployments, ensure the new changes are tested E2E and regression performed at OSIO (production cluster)

**# Description**

These E2E tests would need to touch/cover all the OSIO user facing components. 

**# Acceptance criteria**

These tests can be run at each production promotion / every 30 mins. Tests run with frequency need to be co-ordinated with @ldimaggi 's work on E2E tests at production.

**Comment by krishnapaparaju** [comment] 2017-12-07 11:41
Has dependency on creation / availability of UI integration test cases

**Comment by tisnik** [comment] 2018-01-03 09:39
The CI job to run EE tests has been setup:
https://ci.centos.org/job/devtools-test-end-to-end-prod-fabric8-analytics/

Now we are about to figure what caused the failures.

**Comment by pkajaba** [comment] 2018-01-04 10:53
@tisnik @krishnapaparaju the problem is an invalid token for API. I sent a request to insert valid one into centos CI. I thought that we could reuse existing ones at first, but it somehow did not work.

**Comment by GeorgeActon** [comment] 2018-08-12 01:48
Closing, no longer relevant. All this work is in planner

**Closed by GeorgeActon** 2018-08-12 01:48 UTC
Labels: area/analytics, area/tests, status/info-needed, team/analytics, type/user-story
