### ISSUE TITLE
BlueOcean is broken in latest Jenkins

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4012] opened 2018-07-17 16:06 UTC
I don't see any blueocean links anymore, and i see this in my logs  this may be specific to my environement but to test I have completely deleted my pvc (oc delete pvc -n $USER-jenkins) and ran it from scratch, which would be the experience of the new user . Here is the error in the logs about it : 

```
SEVERE: Failed Loading plugin Blue Ocean Core JS v1.6.2 (blueocean-core-js)
java.io.IOException: Blue Ocean Core JS v1.6.2 failed to load.
 - You must update Jenkins from v2.93 to v2.107.2 or later to run this plugin.
 - Jenkins Design Language v1.6.2 failed to load. Fix this plugin first.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Jul 17, 2018 3:00:15 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Web for Blue Ocean v1.5.0 (blueocean-web)
java.io.IOException: Web for Blue Ocean v1.5.0 failed to load.
 - Blue Ocean Core JS v1.6.2 failed to load. Fix this plugin first.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Jul 17, 2018 3:00:15 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin REST Implementation for Blue Ocean v1.5.0 (blueocean-rest-impl)
java.io.IOException: REST Implementation for Blue Ocean v1.5.0 failed to load.
 - Web for Blue Ocean v1.5.0 failed to load. Fix this plugin first.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ldimaggi** [comment] 2018-07-17 16:30
Duplicate of: https://github.com/openshiftio/openshift.io/issues/4006

**Closed** 2018-07-18 12:22 UTC
Labels: SEV2-high, team/build-cd, type/bug
