### ISSUE TITLE
Can't start che workspace via che.openshift.io, getting osoproxy error

### ISSUE THREAD

**Issue by skryzhny** [openshiftio/openshift.io#3884] opened 2018-06-29 15:39 UTC
I'm trying to start my che workspace at https://che.openshift.io/ but getting this error:
![osio che start error 2018-6-29 18-21](https://user-images.githubusercontent.com/1636620/42101335-84084354-7bcb-11e8-9404-298de3926a25.jpg)
I tried to create new workspace but got similar error.

**Comment by skryzhny** [comment] 2018-06-29 15:43
Text from new workspace:
`
Could not start workspace wksp-oidg. Reason: Failure executing: GET at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/skryzhni-che/persistentvolumeclaims. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
`

**Comment by ibuziuk** [comment] 2018-06-29 15:45
very likely related to https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844#note_359943

@skryzhny please provide your osio username
@aslakknutsen @nurali-techie any ideas ?

**Comment by skryzhny** [comment] 2018-06-29 15:48
My OSIO account is `skryzhni@redhat.com`

**Comment by nurali-techie** [comment] 2018-07-02 05:28
@ibuziuk can you please summarize the issue and your investigation in one comment.
Have you able to re-produce the issue or you got any logs on server for the issue faced by @skryzhny ?
Cc: @aslakknutsen

**Comment by ibuziuk** [comment] 2018-07-02 18:56
@nurali-techie could you please take a look at my comments in  https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844#note_359943 I guess more logs could be retrieved from kibana

**Comment by nurali-techie** [comment] 2018-07-03 03:57
@ibuziuk as I told you previously (twice - here as well on mattermost), either you should re-produce the issue and share steps or share the logs of the occurrence of original issue which will be having timestamp on when the issue happened.  You comment https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844#note_359943 just give the error message and no idea of when it happened.  If this is re-prodcuable then I want steps.

**Comment by ibuziuk** [comment] 2018-07-03 08:45
@rhopp is going to provide more details soon, he is also having this problem. Sorry, I can not look at this issue right-away. I think it is pretty easy to repro by just adding `identity_id` to toggle [1]  and starting the workspace

[1] https://admin-dsaas-production.09b5.dsaas.openshiftapps.com/toggles/#/features/strategies/che.serviceaccount.lockdown

**Comment by rhopp** [comment] 2018-07-03 12:03
@nurali-techie We (rh-che QE team) have few accounts with `che.serviceaccount.lockdown` toggle enabled and none of them is able to start workspace. Those accounts have also revoked admin access to `*-che` namespace in their OSO.
If you want to search kibana for logs, I've generated few of these failures in last few minutes. One of them can be found in this search: https://logs.dsaas.openshift.com/goto/dfee6f741f3919e3cf839a1a00a6afa8
(These are the logs from `f8osoproxy`, but from there you can see the time, when it happened)
If you add `AND rhopp` to the search query in kibana, it should filter it to logs of this issue only.
For the reproduction steps:
1) Have account with `che.serviceaccount.lockdown` toggle enabled (Ilya can help you with this, if you provide him your identity_id)
2) Have admin access revoked in your OSO `*-che` namespace (I don't know if this is required)
3) Try to start a workspace  (for example using che dashboard - che.openshift.io) - this should fail.

If you don't want to bother with the toggles, get in contact with me - I can either generate the issue on demand for you to observe logs, or I can give you access to one of our testing accounts.

**Comment by ibuziuk** [comment] 2018-07-03 13:00
> Have admin access revoked in your OSO *-che namespace (I don't know if this is required)

2. is not required ;)

**Comment by ibuziuk** [comment] 2018-07-10 15:29
@nurali-techie thanks for investigation. I wanted to test if header approach works with oso-proxy on preview in the meantime but unfortunately prod-preview is down due to cluster update. Will try and let you know tomorrow

**Comment by ibuziuk** [comment] 2018-07-11 06:29
on prod-preview (identity_id is passed via header there) I got the very same issue:

![image](https://user-images.githubusercontent.com/1461122/42553941-4336a1ba-84e3-11e8-9e89-3625a9d25321.png)

if oso-proxy is functioning as expected it looks like the problem with the auth token. need to investigate a bit more

**Comment by ibuziuk** [comment] 2018-07-11 08:57
just checked the che sa token and it seems to be valid on prod preview - oso proxy understand it and returns 200 when it passed via curl / REST client

**Comment by nurali-techie** [comment] 2018-07-11 10:07
@ibuziuk It means things are working fine on prod-preview when call made from curl to oso-proxy.  So, I will pause debugging at oso-proxy side.
Cc: @aslakknutsen

**Comment by ibuziuk** [comment] 2018-07-11 10:47
@nurali-techie @aslakknutsen the problem might be more subtle than incorrect processing / missing `identity_id`. in oso-proxy logs when error occurs there is a message when auth error occurs:

`time="2018-07-11T08:58:59Z" level=error msg="Token not found, Missing auth"`

For some reason it says `Token not found` which is super strange. I mean what would be expected if there would be smth. like `Token is invalid` / `missing identity_id header` or smth. else more meaningful that would clearly point to the root cause

**Comment by ibuziuk** [comment] 2018-07-12 06:04
@rhopp the issue seems to be not reproducible anymore on prod. Will you be able to verify that now it is possible to create a workspace without problems on prod when the user is added to the lockdown toggle ?

**Comment by skryzhny** [comment] 2018-07-12 07:38
I still have problem starting workspace, tried few minutes ago and got:
```
Failure executing: GET at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/skryzhni-che/persistentvolumeclaims. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
```

**Comment by skryzhny** [comment] 2018-07-12 07:51
I finally got my workspace running after visiting https://openshift.io  
It was showing that I'm not logged in, which is strange, cause I already logged in to https://che.openshift.io  
Anyway after login in to https://openshift.io I'm able to run workspace at https://che.openshift.io

**Comment by ibuziuk** [comment] 2018-07-12 09:45
@skryzhny yeah, that's strange but probably when you logged in via openshift.io some init tenant script was executed that fixed configuration problems in your *-che namespace.
@rhopp yeah, I see a bunch of `401 Unauthorized` for your user in oso-proxy logs. Could you please check if che sa exists in your namespace ?

**Comment by rhopp** [comment] 2018-07-12 10:37
@ibuziuk `che` SA is present in my `-che` namespace:
![image](https://user-images.githubusercontent.com/1215011/42628380-3fb4cdda-85d0-11e8-8694-b388b193731f.png)

**Comment by amisevsk** [comment] 2018-07-12 13:16
To add onto the above comment, I was having the same issue until my account was removed from the lockdown feature toggle by @ibuziuk.

- `4ede3680-42b9-461b-b9bb-362bc04745f0 / amisevsk / us-east-2`

**Comment by ibuziuk** [comment] 2018-07-30 09:15
@rhopp che has been updated on prod / prod-preview and usage of che SA token should technically work. Could we start with testing the lockdown again on prod & prod-preview in order to finish with - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844
That's a pity though that it is not clear why it stopped working on prod out of the blue - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844#note_359792

**Comment by rhopp** [comment] 2018-08-09 08:37
I've verified that users in the `che.serviceaccount.lockdown` toggle can start&operate workspaces (I didn't find any issues). I've tried this with user with AND without `user-edit` role in `-che` namepsace. Closing.

**Closed by rhopp** 2018-08-09 08:37 UTC
Labels: SEV2-high, area/che, priority/P4, status/pending-qa-verification, type/bug
