### ISSUE TITLE
Header menu randomly repeats multiple times

### ISSUE THREAD

**Issue by c-koehler** [openshiftio/openshift.io#1362] opened 2017-11-14 22:45 UTC
At the top, the buttons on the header are repeated 4x. I'm not sure what is causing this to happen, it's random. A pre-requisite _may_ be that the repository for the space has to be deleted on github (manually) without any action being done through openshift.io to cause it to get deleted. However, due to the random nature of this, I'm not sure if that is a pre-requisite to trigger this or it just randomly happens.

This is also an operational menu, so clicking on any of the repeated buttons does take you to where it is routed.

An example of this occurring (see the very top):

![multiple](https://user-images.githubusercontent.com/33262856/32808962-0b207134-c963-11e7-91ae-e6de12878806.png)

**Comment by joshuawilson** [comment] 2017-11-14 22:56
This was fixed in #1128 
@dlabrecq can you please take a look again.

**Comment by dlabrecq** [comment] 2017-11-14 23:47
I cannot reproduce. Even after deleting my GitHub repo, the navigation appears to work fine. It would be helpful to note any errors logged in the browser console?

FYI, the issue for #1128 was related to an error in the page, caused by a patternfly-ng component. That error has since been fixed; however, any JS error in platform, planner, etc. can prevent the page from working properly.

**Comment by joshuawilson** [comment] 2017-11-15 03:08
@c-koehler can you please try to figure out the steps to reproduce this.

**Comment by qodfathr** [comment] 2018-01-23 17:51
No one seems to be able to reproduce this. Closing but feel free to reopen if reproducible steps can be identified.

**Closed by qodfathr** 2018-01-23 17:51 UTC
Labels: SEV3-medium, area/navigation, team/platform, type/bug
