### ISSUE TITLE
UI does not refresh when adding a codebase

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#2092] opened 2018-01-29 13:37 UTC
There are several workflows in the UI where actions affect areas of the screen which then don't get updated until a full reload of the page is triggered. For example.

1. As newly provisioned user log into openshift.io 
1. Create your initial space
1. Choose to create a sample pipeline (using the wizard)
1. Follow the steps of the wizard
1. Once complete you can close the wizard and you can see your pipeline in the _pipelines_ box. You also get a notifier that a new codebase has been created. The _codebases_ box of the UI stays empty, however, and one needs to do a full reload of the page at which point the codebase becomes visible. 

Note, this is just an example workflow. There are several other workflows leading to a non refreshed view of the application.

**Comment by qodfathr** [comment] 2018-01-30 17:00
Closing as dupe of #1252

**Closed by qodfathr** 2018-01-30 17:00 UTC
Labels: SEV2-high, area/app-wizard, area/dashboard, team/platform, train/heather, type/bug
