### ISSUE TITLE
Sporadic errors from OSO api

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#2381] opened 2018-02-27 14:54 UTC
I am seeing about 30 jenkins namespaces which are missing a "jenkins-git-ssh" secret.

The jenkins slaves are crashlooping because they are trying to mount that secret as a volume.

Can we re-create this secret? What should it contain?

```
  1m		1m		1	kubelet, ip-172-31-67-252.us-east-2.compute.internal			Warning		FailedMount		Unable to mount volumes for pod "jenkins-slave-ttj2g-9mrcz_shermans-1-jenkins(99101743-1bcb-11e8-a099-02d7377a4b17)": timeout expired waiting for volumes to attach/mount for pod "shermans-1-jenkins"/"jenkins-slave-ttj2g-9mrcz". list of unattached/unmounted volumes=[volume-1 volume-5]
  3m		1m		9	kubelet, ip-172-31-67-252.us-east-2.compute.internal			Warning		FailedMount		MountVolume.SetUp failed for volume "volume-5" : secrets "jenkins-git-ssh" not found
```

@rupalibehera @chmouel @jaseemabid @pradeepto

**Comment by jfchevrette** [comment] 2018-02-27 14:57
In the other namespaces the secret content is:

```yaml
data:
  ssh-key: null
  ssh-key.pub: null
```

**Comment by jfchevrette** [comment] 2018-02-27 21:14
It looks like the following secrets are missing from some namespaces, even newer namespaces initialized a few days ago
- jenkins-git-ssh
- jenkins-hub-api-token

This causes jenkins-slave pods to fail and crashloop.

Moving this to SEV1

**Comment by stevengutz** [comment] 2018-02-28 13:56
@pradeepto who should be looking at this?

**Comment by aslakknutsen** [comment] 2018-02-28 14:09
@jfchevrette What tenant version are these running? see labels

**Comment by pbergene** [comment] 2018-02-28 14:14
Set up by tenant service. Templates are in place, but not applied for some.  Will get a list and compare notes with @aslakknutsen - also check for versions / labels.

**Comment by rupalibehera** [comment] 2018-02-28 14:20
@pbergene , as we discussed on the triage call can we remove team/build-cd label from the issue

**Comment by pbergene** [comment] 2018-02-28 14:25
@rupalibehera yeah, we'll loop you in as required :)

**Comment by jfchevrette** [comment] 2018-02-28 14:29
@aslakknutsen one tenant which was initialized 44 hours ago is missing jenkins-git-ssh. The other one (jenkins-hub-api-token) is present. dc/jenkins is at version 4.0.56

Could it be that the quota update is applied later in the process? I noticed one of them (only one) still had a secrets limit of 20 (should be 40) and there is a total of 21 secrets once a tenant is fully provisioned (including dockercfg and token secrets).

**Comment by pbergene** [comment] 2018-02-28 16:13
@aslakknutsen To clarify the secrets were added to these namespaces manually.  I was busy investigating when @jfchevrette mentioned this. He has a list of the namespaces that *were* affected if you want to compare notes.

**Comment by aslakknutsen** [comment] 2018-02-28 19:14
@jfchevrette  4.0.56 was the mass update v.

**Comment by aslakknutsen** [comment] 2018-03-01 03:02
Tenant Service is seeming getting 'random' 403 Forbidden response from OSO when attempting to provision new users. This happens mostly on the Jenkins namespace as the other namespaces are rather empty, but type of resource seems irrelevant; secrets, volums, resource limits, etc

Cause: Unknown

**Comment by aslakknutsen** [comment] 2018-03-01 22:28
All found effected namespace has been updated. 

Cause: Unknown

**Comment by aslakknutsen** [comment] 2018-03-03 00:18
OSO is returning the following on the 403 errors:

```
message: 'secrets "jenkins-docker-cfg" is forbidden: status unknown for quota: object-counts'
```

Which seems to imply some kinda async behavior around the update of the ResourceQuota "object-counts" which we update as part of the init. It takes a certain time before it's 'ready/applied' 100%.

**Comment by aslakknutsen** [comment] 2018-03-05 10:15
Seeing 3 different cases around this:

* Getting 403 from OSO to apply 'any' object; secrets, pvc, service etc due to Quota issue. OSO got slow to apply ResourceQuota objects and should have been fixed by adding a retry loop: https://github.com/fabric8-services/fabric8-tenant/pull/546
* Getting 403 from OSO to apply ResourceQuota/LimitRanges after ProjectRequest, seemingly slow to apply general auth. A wait period from ProjectRequest to first apply increased to 5s. Still seeing the issue. Monitoring
* Getting 500 from OSO on ProjectRequest, no known fix /cause atm

**Comment by jfchevrette** [comment] 2018-03-05 15:34
> Getting 403 from OSO to apply 'any' object; secrets, pvc, service etc due to Quota issue. OSO got slow to apply ResourceQuota objects and should have been fixed by adding a retry loop: fabric8-services/fabric8-tenant#546
> Getting 403 from OSO to apply ResourceQuota/LimitRanges after ProjectRequest, seemingly slow to apply general auth. A wait period from ProjectRequest to first apply increased to 5s. Still seeing the issue. Monitoring

We should open a BZ and track this upstream even though we have a workaround now. Do you have an easy way to reproduce so I can provide that in the upstream issue?

> Getting 500 from OSO on ProjectRequest, no known fix /cause atm

Did we have an issue for this one?

**Comment by aslakknutsen** [comment] 2018-03-05 23:02
```
Tenant Init:
ProjectRequest: March 5th 2018, 20:45:58.976
LimitRange: March 5th 2018, 20:45:59.344  <-- fail 403

Tenant Update:
March 5th 2018, 20:47:38.522 <-- fail 403

March 5th 2018, 21:16:33.499 <-- ok
```

**Comment by jfchevrette** [comment] 2018-03-06 15:44
I've been able to reproduce using this reproducer script: https://gist.github.com/jfchevrette/c65d16e45993133c3537b2a0c16968f6

I've reached out upstream to see how we can address this.

**Comment by jfchevrette** [comment] 2018-03-08 14:04
Fix found and addressed upstream. Waiting for it to be deployed to both clusters hopefully today.

**Comment by jfchevrette** [comment] 2018-03-12 18:52
With the recent fixes I am not able to reproduce this anymore.

**Comment by jfchevrette** [comment] 2018-03-12 20:53
A permanent fix has been deployed upstream to adress this. Basically now our provisioning user will have permissions at the cluster level to update quotas, limits, etc... instead of relying on a separate async process to do this.

I've done some testing and were not able to reproduce this.

**Comment by aslakknutsen** [comment] 2018-03-12 21:15
The fix seems ok as far I can see atm as well.

Follow up task:
* https://github.com/openshiftio/openshift.io/issues/2547
* Manually update users that failed to provision over the last couple of days

**Comment by pbergene** [comment] 2018-03-14 14:43
Reducing this to Sev-2 - please let me know if we should raise it again

**Comment by aslakknutsen** [comment] 2018-03-25 11:32
Root cause identified and fixed, closing. Other improvements in the work.

**Closed by aslakknutsen** 2018-03-25 11:32 UTC
Labels: SEV2-high, area/user/tenant, team/platform, type/bug
