### ISSUE TITLE
Tasks in 'Board' view do not show any relationship to their parent Feature/Story

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#273] opened 2017-06-21 07:25 UTC
Task details must show the relationship with their parent WI, or else it becomes extremely difficult to map/identify tasks for a story/feature.

Two features/stories in an iteration may have similar tasks with identical names e.g. 'Write Unit Tests'. A user currently has no way to identify the story the task belongs to.

**Comment by joshuawilson** [comment] 2017-06-21 12:51
This issue was moved to fabric8io/fabric8-planner#2034

**Comment by michaelkleinhenz** [comment] 2017-09-20 11:05
Dupe of #325.

**Closed by michaelkleinhenz** 2017-09-20 11:05 UTC
Labels: area/planner, area/UX, team/planner
