### ISSUE TITLE
Different response for same pom.xml on prod and prod-preview

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4266] opened 2018-08-29 09:01 UTC
## Issue Overview
Different response for same pom on prod and prod-preview. In response from prod there is stack level license but on prod-preview it's showing one of the license as unknown.

prod-preview response - https://gist.github.com/sunilk747/d134b3ef6992bc4600fa029d9a3e0bcb

prod response - https://gist.github.com/sunilk747/2b4beca149811452d453ee7a1c26c739

### Steps to reproduce
Perform stack analyses call on this pom :- https://github.com/iluwatar/java-design-patterns/blob/master/strategy/pom.xml

cc @miteshvp

**Comment by stevengutz** [comment] 2018-08-29 11:12
This looks like a duplicate of https://github.com/openshiftio/openshift.io/issues/4265

**Comment by sunilk747** [comment] 2018-08-30 08:55
@stevengutz No. Both the issues are different.

**Comment by msrb** [comment] 2018-09-05 22:12
I think this could be because the environments don't share data and staging is basically a subset of prod?

**Comment by miteshvp** [comment] 2018-09-06 06:04
@sunilk747 License in prod-preview has a `white-space`. Maybe license analysis code should strip the license fields while evaluating the license. Plus, this looks to be a case where data needs correction in staging. 
On prod-preview
```
"distinct_licenses": [
                    " GNU Lesser General Public License",
                    "MIT License",
                    "Eclipse Public License - v 1.0"
                ]
```
On Prod
```
"distinct_licenses": [
                    "GNU Lesser General Public License",
                    "MIT License",
                    "Eclipse Public License - v 1.0"
                ]
```

**Comment by miteshvp** [comment] 2018-09-10 09:18
Data corruption is fixed in staging. @sunilk747 please make sure to handle such whitespaces at the code level

**Closed by miteshvp** 2018-09-10 09:18 UTC
Labels: SEV4-low, area/analytics, priority/P4, team/analytics, type/bug

**Comment by sunilk747** [comment] 2018-09-10 09:20
Thanks @miteshvp . I will do the required changes to handle such cases in future.
