### ISSUE TITLE
In launcher - selecting runtime before mission results in 400 error (bad request) fails to create new app

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3418] opened 2018-05-02 13:59 UTC
The following sequence of user actions results in a 400 (bad request) error in the launcher. The error is logged in the browser console. The "Set up Application" button appears to be unresponsive. An error message is not displayed in the OSIO UI.

Steps to recreate - in this precise order
* Open Chrome browser console
* Reset user env
* Set feature level to beta
* Create a new space
* Create new app
* Select runtime (Vert.x)
* Select misson (REST)
* Select release strategy (release, stage, run)
* Select github repo
* Press "Set Up Application"

Observe 400 (bad request):
```
Bad Request [{"message":"java.lang.IllegalStateException: 
Error while preparing projectile"}]
```

**Comment by ldimaggi** [comment] 2018-05-02 14:00
The error is not seen if the user selects app options in this order:
* Select misson (REST)
* Select runtime (Vert.x)

**Comment by gastaldi** [comment] 2018-05-02 17:33
This is a frontend bug, the `current-redhat` version does not exist in the Vert.x runtime (it should have been `redhat`). See the backend output: 

`http https://forge.api.openshift.io/api/booster-catalog/runtimes\?runsOn\=osio`

@invincibleJai can you verify this?

**Comment by invincibleJai** [comment] 2018-05-02 17:37
@gastaldi yes it's an issue from UI, we will put a fix for this soon.

**Comment by gastaldi** [comment] 2018-05-09 18:15
It looks like this is still happening in production: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/4009/ 

@bmicklea do you confirm this? Feel free to reopen this issue

**Comment by gastaldi** [comment] 2018-05-17 19:34
As of https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/4009/ this is not fixed yet. Reopening

**Comment by invincibleJai** [comment] 2018-05-18 05:16
As stated by @gastaldi om MM

> `current-osio` exists only for Spring Boot Configmap, not `rest-http`

**Comment by gastaldi** [comment] 2018-05-18 05:33
@invincibleJai I have only noticed that there are three events in Sentry with this error, I don't know exactly how to reproduce it.

https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/4009/events/

Do you see any error in the console while trying the steps in this issue description?

**Comment by invincibleJai** [comment] 2018-05-18 06:17
ah @gastaldi no console looks good. I saw these events in Sentry we need to figure out what is the pattern.  I am not sure if it can be dude to cache issue for those users and two out of three events were fired on 9th May around same time i.e same user on Mac. On 15th may it's a diff user in fedora.

**Comment by arunkumars08** [comment] 2018-05-28 06:49
@gastaldi Are you able to reproduce the issue?

**Comment by gastaldi** [comment] 2018-05-28 14:02
@arunkumars08 no, I am not able to reproduce it, maybe it was fixed in the recent changes in ngx-launcher. Feel free to close this issue for now if you can't reproduce it either.

**Closed** 2018-05-29 06:00 UTC
Labels: SEV2-high, area/launcher, priority/P0, status/completed, team/analytics, team/analytics/wizard, type/bug
