### ISSUE TITLE
Option to edit a repo on a Pipeline page results in a 404 error

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#519] opened 2017-08-09 13:13 UTC
Browse to the pipeline page and select the kebab menu next to the repository listed. Select 'Edit' option from the drop-down menu and observe that the user is taken to a 404 error page.

Video reference is attached.

**Comment by rgarg1** [comment] 2017-08-09 13:15
https://drive.google.com/open?id=0BwLIZeed5jyKMl9pNjdjUW5HUlU

**Comment by qodfathr** [comment] 2018-01-17 17:51
@catrobson did we decide if the Edit kabob option on the Pipelines screen was going to stay? If yes, where is it supposed to go / can you link the design here? If not, @joshuawilson do we have a plan to remove which we can reference here?

**Comment by joshuawilson** [comment] 2018-01-17 19:13
I do not recall, I think @catrobson has the notes on it.

**Comment by catrobson** [comment] 2018-01-17 19:56
Yes, we agreed that we wanted to remove "edit" from the pipeline kabob.  https://docs.google.com/spreadsheets/d/1Tmsh3bfzShNLoOYZQAsFdNxXdkqeiV6bwIvgxg_cXBw/edit

**Comment by joshuawilson** [comment] 2018-01-18 02:36
@chrislessard when you have some time, here is something to fix.

**Comment by chrislessard** [comment] 2018-01-26 17:59
On it

**Comment by chrislessard** [comment] 2018-01-26 19:37
@rgarg1 I'm unable to reproduce, and unfortunately your video refuses to load :/ Is it possible someone addressed this elsewhere ? 

<img width="1437" alt="screen shot 2018-01-26 at 2 36 19 pm" src="https://user-images.githubusercontent.com/17230733/35457271-5214ba1a-02a6-11e8-9f6a-a6e9211a58c4.png">
<img width="1440" alt="screen shot 2018-01-26 at 2 36 24 pm" src="https://user-images.githubusercontent.com/17230733/35457272-523c4184-02a6-11e8-9790-df10799b99bc.png">

**Comment by chrislessard** [comment] 2018-01-26 19:46
Fixed by https://github.com/fabric8-ui/fabric8-ui/commit/bcdd362ffd979a0ddb48e6eb35f59e92f0a1d516

**Closed by chrislessard** 2018-01-26 19:46 UTC
Labels: SEV3-medium, area/pipelines, team/build-cd, team/platform, type/bug
