### ISSUE TITLE
An immortal space in my OSIO account

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#537] opened 2017-08-10 07:21 UTC
I've a space showing up in my test OSIO account that was created on Aug2, but I cannot delete it anymore. It does not shows-up in the All Spaces page.

But this space is real as I can actually open it and view its contents too.

Weird! See the screen.

**Comment by rgarg1** [comment] 2017-08-10 07:22
![inaccessible space in my account](https://user-images.githubusercontent.com/28748448/29158970-8f8bc6fc-7d9c-11e7-84d4-7df22ad2cdb9.png)
The immortal 'Aug2' showing up in the drop-down

**Comment by rgarg1** [comment] 2017-08-10 07:22
![inaccessible space actually exists](https://user-images.githubusercontent.com/28748448/29159010-ac9a58da-7d9c-11e7-9bc3-d6713af5a5c1.png)
Proof that the immortal actually exists

**Comment by rgarg1** [comment] 2017-08-10 09:04
Its gone! Once I cleaned up my account.

**Comment by rgarg1** [comment] 2017-08-10 10:05
Its back again :(
![immortal space is back](https://user-images.githubusercontent.com/28748448/29165770-726528a4-7db3-11e7-8b14-a348516cd46d.png)

**Comment by joshuawilson** [comment] 2017-08-14 01:40
This is not a bug. The Context menu shows you the spaces you recently visited. That space is not one of yours so you can't delete it. If you view 5 other spaces it will push it out. Or if you wait a few days it will time out and not be displayed, at least until you visit it again. 

Closing as this works as designed.

**Closed by joshuawilson** 2017-08-14 01:40 UTC
