### ISSUE TITLE
Avoid horizontal scrollbar by default when creating a scenario

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#3084] opened 2018-04-12 15:02 UTC
![horizontalscrollbarbydefaultalthouttherearelotofspace](https://user-images.githubusercontent.com/1105127/38685892-524e69c8-3e73-11e8-8e27-26c9536057bc.png)

**Comment by ldimaggi** [comment] 2018-04-12 17:39
Can you provide some context here? What is the bug? Thx!

**Comment by apupier** [comment] 2018-04-13 06:54
the problem is that there is an horizontal scrollbar  (and so some information is hidden) although there is a lot of blank space.

**Comment by ppitonak** [comment] 2018-04-16 14:02
duplicate of #2296

**Closed** 2018-04-17 00:34 UTC
Labels: SEV4-low, area/UI, area/planner, team/planner
