### ISSUE TITLE
[Che] Can't push commit in amend mode

### ISSUE THREAD

**Issue by jeffmaury** [openshiftio/openshift.io#2576] opened 2018-03-14 15:22 UTC
I followed the workshop but when I commited I forgot the select the push option. Then I reran the git commit command and as nothing changed, the UI proposed the amend mode but I can't select the push option then

**Comment by eivantsov** [comment] 2018-03-31 09:09
@jeffmaury You can push at Git > Remotes > Push.

**Comment by RanjithRV** [comment] 2018-08-06 09:55
@jeffmaury @eivantsov Can we close this issue? Is the proposed solution a workaround or expected behaviour?

**Comment by gorkem** [comment] 2018-08-19 01:41
closed, it looks like an acceptable solution and there was no further activity.

**Closed** 2018-08-19 01:40 UTC
Labels: area/che, team/che/osio, type/question
