### ISSUE TITLE
Quickstart "Vert.x - HTTP & Config Map" runs in Che workspace, generates non-fatal (SEVERE) error messges

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1061] opened 2017-10-05 16:58 UTC
Steps to recreate:
* Create new space
* Create new "Vert.x - HTTP & Config Map" quickstart
* Create Che workspace
* Run app in Che workspace - observe that the app is reachable at URL similar to:
http://vertx-wvrfv4s0qmr7lz4a-[username]-che.8a09.starter-us-east-2.openshiftapps.com

But - observe repeated errors in run log/window in Che workspace:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building vertx-http-configmap 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-version) @ oct5testb ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ oct5testb ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ oct5testb ---
[INFO] Executing: /bin/sh -c cd '/projects/oct5testb' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /projects/oct5testb
[INFO] Storing buildNumber: 52d1b9ed04523402714b4a4f8472903abc61a046 at timestamp: 1507221458165
[INFO] Storing buildScmBranch: master
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.8:initialize (vmp) @ oct5testb ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ oct5testb ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ oct5testb ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /projects/oct5testb/target/classes
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.8:run (default-cli) @ oct5testb ---
[INFO] Launching Vert.x Application
[INFO] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[INFO] SLF4J: Defaulting to no-operation (NOP) logger implementation
[INFO] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
[INFO] Oct 05, 2017 4:37:41 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
[INFO] INFO: Succeeded in deploying verticle
[INFO] Oct 05, 2017 4:37:41 PM io.netty.util.internal.MacAddressUtil defaultMachineId
[INFO] WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 8a:ba:b3:7f:fd:40:c7:a3
[INFO] Oct 05, 2017 4:37:46 PM io.vertx.config.impl.ConfigRetrieverImpl
[INFO] SEVERE: Error while scanning configuration
[INFO] io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/default/configmaps/app-config. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:319)
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266)
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:226)
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:686)
[INFO] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:187)
[INFO] 	at io.vertx.config.kubernetes.ConfigMapStore.lambda$null$2(ConfigMapStore.java:132)
[INFO] 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
[INFO] 	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ibuziuk** [comment] 2017-10-05 19:10
@ldimaggi does the app functionality is broken, or everything works fine from the user perspective ?

**Comment by ldimaggi** [comment] 2017-10-05 19:32
The app runs. The SEVERE level log message is odd - and will be alarming to users. Can we remove the cause of the ERROR?

**Comment by ibuziuk** [comment] 2017-10-05 19:45
@ldimaggi I haven't tried it yet, so do not really know what is causing it. Does the same logs are traced when this quickstart project is run on local machine, or is it che spesific issue ?

**Comment by ibuziuk** [comment] 2017-10-06 14:09
@ldimaggi the whole point of `Vert.x - HTTP & Config Map` is deploying the project to minishift / OpenShift online via:
` mvn clean fabric8:deploy -Popenshift`

More details can be found in the docs[1]
It is similar to what I wrote about `OpenShiftIt` [2] tests for vertx / spring boot quickstarts.

> However, I do not think that this scenario is smth. that is supposed to be demoed with osio. Technically, it should be possible to deploy this app from che on osio to some other csuster and execute this test, but I'm not sure this is a osio use-case where deployments to stage / run is powered by jenkins pipelines

IMO, `Vert.x - HTTP & Config Map` project should not be listed in quickstarts, because there is no meaningful use-case for it on osio
@gorkem @l0rd WDYT ?

[1] https://appdev.openshift.io/docs/vertx-runtime.html
[2] https://github.com/redhat-developer/rh-che/issues/365#issuecomment-333776130

**Comment by slemeur** [comment] 2017-10-12 17:41
Removing the label `kind/bug` as the product is behaving correctly, but it is more an open question about the quick start it self.

@ibuziuk : About the validity of the use case. I agree that the logical flow on osio should be to go over a jenkins pipeline to handle this step. But it should still remain possible to execute that action from Che - exactly as you would be able to do it from your local environment.

**Comment by l0rd** [comment] 2017-10-13 17:40
@slemeur @ibuziuk an initial requirement for Che on OSIO was to block access to the OpenShift API from within a Che workspace. We didn't want users to be able to call the API directly to create pods, services routes etc...This requirement was particularly important for the service delivery team (cc @kbsingh). That explains why this quickstart should not work in Che by design.

This makes sense from a security perspective but I do think that is a serious UX limitation. A Che user that is used to run his applications on k8s won't never understand why he cannot run his application on a k8s pod from within Che.

This is an important topic and deserves to be discussed with PMs, fabric8-cd and Service Delivery team.

**Comment by ibuziuk** [comment] 2017-10-13 19:55
> But it should still remain possible to execute that action from Che - exactly as you would be able to do it from your local environment.
I believe it is still possible to deploy the app from workspace on osio to some other cluster by executing oc commands from the terminal. Just saying that for now there is no meaningful use-case for it

**Comment by eivantsov** [comment] 2017-10-18 13:37
I have got the same error when the app runs in stage namespace.

**Comment by cescoffier** [comment] 2017-10-18 20:07
The config map is not created because it must be created explicitly. The config map is not created by default as it may use a different deployment cycle.

**Comment by rbaumgar** [comment] 2017-11-23 21:21
I have created the configmap in my stage project, but I am not able to add the view role, so the vertx example is still not able read the configmap...

$ oc whoami -c
rbaumgar-stage/api-starter-us-east-2-openshift-com:443/rbaumgar
$ oc get configmap app-config -o yaml
apiVersion: v1
data:
  app-config.yml: |
    message : "Hello, %s from a ConfigMap !"
    level : INFO
kind: ConfigMap
...
$ oc policy add-role-to-user view -n $(oc project -q) -z default
Error from server (Forbidden): User "rbaumgar" cannot list rolebindings in project "rbaumgar-stage"

**Comment by cescoffier** [comment] 2017-11-24 06:45
The last line is annoying because you can't grant the `view` permission - to you would not be able to view the config map.

**Comment by rbaumgar** [comment] 2017-11-24 10:03
I can read it, but the vertx cann't!

**Comment by cescoffier** [comment] 2017-11-24 13:33
Basically, your application cannot read the config map. So, you will have to switch to another way to read the config map (volume or system properties)

**Comment by rbaumgar** [comment] 2017-11-25 07:34
Agree! But this is the example which is provided in OpenShift.io with the name "Vert.x HTTP & Config Map". And I assume an example should work OOTB. 
BTW this example shows dynamic config update and I am not sure the other ways do work...

**Comment by l0rd** [comment] 2017-11-27 09:24
@rbaumgar @cescoffier for the namespace <username>-che namespace we had taken the decision to avoid any access to the OpenShift API by design. This is from the terminal within a Che workspace:

```
[user@che-ws-cz72tpyqm6yf947x-2692580209-5zzg0 projects]$ oc get all
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list buildconfigs in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list builds in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list imagestreams in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list deploymentconfigs in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list deployments.extensions in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list horizontalpodautoscalers.autoscaling in project "mloried
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list replicationcontrollers in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list routes in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list services in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list statefulsets.apps in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list jobs.batch in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list replicasets.extensions in project "mloriedo-che"
Error from server (Forbidden): User "system:serviceaccount:mloriedo-che:default" cannot list pods in project "mloriedo-che"
[user@che-ws-cz72tpyqm6yf947x-2692580209-5zzg0 projects]$
``` 

But @rbaumgar I agree with you that we need to take a decision: either we provide sufficient privileges to run the booster or we need to remove the booster from the quickstart. cc @kbsingh @joshuawilson

**Comment by joshuawilson** [comment] 2017-12-07 20:47
Has Anything been decided or done on this?

My first thought is to remove the booster or at least filter it from the ones you can use in the wizard.
cc @gastaldi @edewit @krishnapaparaju @corinnekrych

**Comment by gastaldi** [comment] 2018-01-22 16:00
Booster was removed. Closing. Reopen if the problem persists

**Closed by gastaldi** 2018-01-22 16:00 UTC
Labels: area/che, team/che, type/question
