### ISSUE TITLE
404 when clicking on a work item link from my profile page

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3568] opened 2018-05-16 06:37 UTC
I have assigned a feature to myself in Planner. As expected, I can see the work item on my profile page now [1]. However when I click on it, I get 404 [2].

1:
![screenshot from 2018-05-16 08-32-14](https://user-images.githubusercontent.com/3759039/40100316-d8123096-58e3-11e8-9f20-070d7834be96.png)

2:
![screenshot from 2018-05-16 08-32-32](https://user-images.githubusercontent.com/3759039/40100322-dd2881ac-58e3-11e8-9044-c6b9fceb5b9e.png)

**Comment by msrb** [comment] 2018-05-16 06:39
The link on my profile page points to https://openshift.io/msrb@redhat.com/openshiftio/plan/detail/2273

While the correct one would be https://openshift.io/openshiftio/openshiftio/plan/detail/2273.

**Comment by joshuawilson** [comment] 2018-05-17 05:08
duplicate of #3462

**Closed by joshuawilson** 2018-05-17 05:08 UTC
Labels: SEV2-high, area/planner, area/spaces, area/work-item-tracker, env/prod, type/bug
