### ISSUE TITLE
Build pipelines fail in production - Jenkins slaves are not starting - they are stuck in a suspended/state

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2341] opened 2018-02-22 17:32 UTC
Started seeing this problem on Feb 22 - am currently seeing this for 2 separate user accounts. Resetting the users' envs is not resolving the issue.

Steps to recreate:
* Reset a user's environment - confirm that Jenkins and Content Repo pods are up and running.
* Create a new space and quickstart
* Observe that the build pipeline cannot build

In the Jenkins pod log observe:
```
Feb 22, 2018 5:16:50 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Waiting for Pod to be scheduled (40/100): jenkins-slave-9qjzf-l9wz9
Feb 22, 2018 5:16:56 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Container is waiting jenkins-slave-9qjzf-l9wz9 [jnlp]: ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={})
```

Observe the state of the Jenkins slave:

![screenshot from 2018-02-22 12-17-03](https://user-images.githubusercontent.com/642621/36554097-28399ee6-17cc-11e8-9e66-fae9df8c5519.png)

![screenshot from 2018-02-22 12-17-14](https://user-images.githubusercontent.com/642621/36554096-2823123e-17cc-11e8-84ef-1ab0ebe0ce2d.png)

![screenshot from 2018-02-22 12-17-27](https://user-images.githubusercontent.com/642621/36554095-28143354-17cc-11e8-81de-62f6c3b4a45d.png)

![screenshot from 2018-02-22 12-17-51](https://user-images.githubusercontent.com/642621/36554094-27fe093a-17cc-11e8-9895-0b4c1790fc72.png)

**Comment by ldimaggi** [comment] 2018-02-22 17:38
Seeing this on production on users configured on the old/original cluster. Trying w/ user on the new cluster now.

**Comment by chmouel** [comment] 2018-02-22 17:42
Not sure if it's a network issue but the services are not talking to each others : 

```
$ oc logs jenkins-slave-p520q-80mc3 -c jnlp                                                                                                     Using 64 bit Java since OPENSHIFT_JENKINS_JVM_ARCH is not set
Downloading http://jenkins//jnlpJars/remoting.jar ...
curl: (7) Failed connect to jenkins:80; No route to host
```

and : 

```
desktop$ oc rsh content-repository-1-lckbs
sh-4.2$ curl -vv http://jenkins
* About to connect() to jenkins port 80 (#0)
*   Trying 172.30.202.237...
* No route to host
* Failed connect to jenkins:80; No route to host
* Closing connection 0
curl: (7) Failed connect to jenkins:80; No route to host
sh-4.2$curl http://$JENKINS_SERVICE_HOST
curl: (7) Failed connect to 172.30.202.237:80; No route to host
```

**Comment by ldimaggi** [comment] 2018-02-22 19:34
Closing - now it's working again. Can we have a post-mortem on happened?

**Comment by mmclanerh** [comment] 2018-02-22 22:07
also, reproduced.  pinging ops on this.

```
### Jenkins, before
NAME                         READY     STATUS      RESTARTS   AGE
content-repository-1-b2mjk   1/1       Running     0          6h
feb22-testx-s2i-1-build      0/1       Completed   0          3h

NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
content-repository   1          1         1         config
jenkins              1          0         0         config
```
```
## jenkins, after reset

Thu Feb 22 14:55:21 MST 2018
NAME                         READY     STATUS    RESTARTS   AGE
content-repository-1-6nx92   1/1       Running   0          7m
jenkins-1-wbgl8              1/1       Running   0          6m

NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
content-repository   1          1         1         config
jenkins              1          1         1         config
```
```
## jenkins, after submitting quickstart
Thu Feb 22 15:03:55 MST 2018
NAME                         READY     STATUS    RESTARTS   AGE
content-repository-1-6nx92   1/1       Running   0          16m
jenkins-1-wbgl8              1/1       Running   0          15m
jenkins-slave-nb2p7-nvgk4    1/2       Error     0          2m
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
content-repository   1          1         1         config
jenkins              1          1         1         config

$ oc logs jenkins-slave-nb2p7-nvgk4 -c jnlp
Using 64 bit Java since OPENSHIFT_JENKINS_JVM_ARCH is not set
Downloading http://jenkins//jnlpJars/remoting.jar ...
curl: (7) Failed connect to jenkins:80; No route to host
```

**Comment by ldimaggi** [comment] 2018-02-22 22:23
Seeing this pattern:

```

[ldimaggi@ldimaggi ~]$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
content-repository-1-6lfff   1/1       Running   0          6m
jenkins-1-l9rmf              1/1       Running   0          7m


[ldimaggi@ldimaggi ~]$ oc get pods
NAME                         READY     STATUS              RESTARTS   AGE
content-repository-1-6lfff   1/1       Running             0          7m
jenkins-1-l9rmf              1/1       Running             0          7m
jenkins-slave-wsktj-59r34    0/2       ContainerCreating   0          21s


oc get pods
NAME                         READY     STATUS              RESTARTS   AGE
content-repository-1-6lfff   1/1       Running             0          9m
jenkins-1-l9rmf              1/1       Running             0          9m
jenkins-slave-wsktj-59r34    1/2       Error               0          2m
jenkins-slave-wsktj-lwclf    0/2       ContainerCreating   0          22s


[ldimaggi@ldimaggi ~]$ oc get pods
NAME                         READY     STATUS              RESTARTS   AGE
content-repository-1-6lfff   1/1       Running             0          15m
jenkins-1-l9rmf              1/1       Running             0          16m
jenkins-slave-wsktj-59r34    1/2       Error               0          9m
jenkins-slave-wsktj-zdlpl    0/2       ContainerCreating   0          7s

```

**Comment by mmclanerh** [comment] 2018-02-22 22:26
tracking in hk #1367

**Comment by ldimaggi** [comment] 2018-02-23 03:11
This issue is being seen on production only - not on prod-preview.

**Comment by mmclanerh** [comment] 2018-02-23 03:31
@vpavlin @hferentschik  some speculation:  is it possible for a race condition to be happening here, with regard to volume leases, idling, and resets?  

today has seen a few examples of two issues.  issue a,  lack of network access from pod to service. that seems to no longer be an issue.  issue b, i believe, may be a race condition around idler and environment resets.  here's how to trigger that condition:
- start with an idle jenkins
- reset your env
- kick off a new quickstart

this creates the state in production, but not in prod-preview. prod preview seems fine.

it looks like through the confluence of this, the jenkins-slave is attempting to use a volume that is already claimed and set as in-use..  and gets into a stuck state -- and then we see a new jenkins slave attempt about every hour..?

```
$ oc get pods
NAME                         READY     STATUS              RESTARTS   AGE
content-repository-1-6nx92   1/1       Running             0          3h
jenkins-1-wbgl8              1/1       Running             0          3h
jenkins-slave-nb2p7-4h2z3    2/2       Running             0          59m
jenkins-slave-nb2p7-fvqbd    0/2       ContainerCreating   0          1m
jenkins-slave-nb2p7-nvgk4    0/2       DeadlineExceeded    0          2h
jenkins-slave-nb2p7-pmfp8    0/2       DeadlineExceeded    0          1h
```

**Comment by chmouel** [comment] 2018-02-23 04:19
I definitely can see this bug in prod when getting Jenkins unidled but could it be because we have a Limit reached ? 

```
$ oc get ev
[....]
 kubelet, ip-172-31-70-109.us-east-2.compute.internal   Unable to mount volumes for pod "jenkins-2-kn6cc_cboudjna-jenkins(1f535457-1850-11e8-a099-02d7377a4b17)": timeout expired waiting for volumes to attach/mount for pod "cboudjna-jenkins"/"jenkins-2-kn6cc". list of unattached/unmounted volumes=[jenkins-home]
2018-02-23 05:17:21 +0100 CET   2018-02-23 05:17:21 +0100 CET   1         jenkins-2-kn6cc   Pod                 Warning   FailedMount   attachdetach   AttachVolume.Attach failed for volume "pvc-ac54dfc7-17f3-11e8-ae91-0233cba325d9" : Error attaching EBS volume "vol-032369e5b00e74cc5" to instance "i-074d2651995f355b8": "RequestLimitExceeded: Request limit exceeded.\n\tstatus code: 503, request id: ffe327b5-5f54-4254-a8bb-7140e986a5d9"
```

**Comment by aditya-konarde** [comment] 2018-02-23 12:09
We've added in a Bugzilla ticket, and working with Ops on getting this resolved.

**Comment by maxandersen** [comment] 2018-02-23 18:21
@aditya-konarde got a link to the bz issue ?

**Comment by aditya-konarde** [comment] 2018-02-23 18:34
@maxandersen https://bugzilla.redhat.com/show_bug.cgi?id=1548384

**Comment by mmclanerh** [comment] 2018-02-23 21:35
@ldimaggi good to close this?

**Comment by ldimaggi** [comment] 2018-02-24 02:28
I'm not seeing the problem now - do we believe that this issue was caused by the Jenkins idler problems? The linked bz is not yet closed.

**Comment by pbergene** [comment] 2018-02-26 12:41
Yeah, idler is disabled on prod for now and this behaviour is no longer observed. Closing this one.  Would expect an idler specific one to appear.

**Closed by pbergene** 2018-02-26 12:41 UTC
Labels: SEV1-urgent, area/jenkins, area/pipelines, team/build-cd, team/service-delivery, type/bug

**Comment by ldimaggi** [comment] 2018-02-27 13:03
Issue found/encountered by EE tests.
