### ISSUE TITLE
Feature Flag Indicator breaks the feature level setting

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3867] opened 2018-06-26 12:52 UTC
Steps:
1. Set the feature level to 'Production' and Feature Flag Indicator as OFF
2. Go to Account home and check that it is the 'old' dashboard
3. Change the feature level to 'Internal'
4. Go to Account home and check that it is the 'new' dashboard
5. Change Feature Flag Indicator to ON
6. Go to Account home 
RESULT: There is 'old' account home page

**Comment by aptmac** [comment] 2018-06-26 19:56
There seems to be a weird disconnect between the feature level values.

For example, I put a logging line in the `analyze-overview.component` to display `UserService.loggedInUser.featureLevel` (showing internal) [0], and another one for the `FeatureTogglesService.getFeature().attributes['enablement-level']` (showing beta) [1], and they're different. They're also different from what I have currently selected on my settings page (experimental).

Here's console output when viewing my analyze page:
![2018-06-26-154629_283x223_scrot](https://user-images.githubusercontent.com/10425301/41935703-9a41df6a-7958-11e8-8dca-2234db361bc1.png)

And here's my settings page
![2018-06-26-154645_814x414_scrot](https://user-images.githubusercontent.com/10425301/41935712-a4a58e52-7958-11e8-8ddd-726bccde014d.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.ts#L39
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.ts#L42

**Comment by corinnekrych** [comment] 2018-06-29 12:00
👀 let me look...

**Comment by corinnekrych** [comment] 2018-06-29 12:45
@aptmac my user is experimental on prod-preview.
in line 39 if I dump `user`:
```
{"attributes":{
  "bio":"ewewewe",
 ...
  "featureLevel":"experimental"
}
```
in line 42 if I dump `feature`:
```
{"attributes":{"description":"The My Work Items card on the Home Dashboard","enabled":true,"enablement-level":"beta","user-enabled":true},"id":"MyWorkItemsCard","type":"features"}
```
here `enablement-level` refer to the level of enablement of the feature itself which is `beta`, since I've accepted `experimental` features i can also see beta features therefore `"user-enabled":true`:
![screenshot 2018-06-29 14 32 06_preview](https://user-images.githubusercontent.com/1395710/42092857-bf66b24e-7baa-11e8-8f8c-cf7838993268.png)

This looks ok to me. 
I'm still 👀 for the 🐛

**Comment by aptmac** [comment] 2018-06-29 13:36
@corinnekrych 

> here enablement-level refer to the level of enablement of the feature itself which is beta

Ah I had overlooked that, thanks for clarifying.

There's still something fishy going on with my feature-flags though, it seems to be stemming from the toggle to show/hide the indicator. I ran into it again right now, I had:

1. Started with feature level `beta` with showing indicator `on`
2. I went to a space analyze page, and confirmed that I was correctly seeing `beta` features
3. I went back to the settings page, and turned the indicator `off`, but kept feature level `beta`
4. I went back to the same space analyze page, and I'm currently seeing `experimental/internal` features

**Comment by corinnekrych** [comment] 2018-06-29 13:36
I dont' reproduce the issue. Ive added a log in html in [new component](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.html#L2) and [old component](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/analyze/analyze-overview/analyze-overview.component.html#L36), and here is what i get from your 6 steps:
* step1
![step1](https://user-images.githubusercontent.com/1395710/42095098-f4a5f558-7bb1-11e8-9f13-102ea9e29cac.png)
* step2
![step2](https://user-images.githubusercontent.com/1395710/42095108-fe044550-7bb1-11e8-85f8-3a9b2a031698.png)
* step3
![step3](https://user-images.githubusercontent.com/1395710/42095119-0437291a-7bb2-11e8-81fd-b581046787d4.png)
* step4
![step4](https://user-images.githubusercontent.com/1395710/42095127-09c8580e-7bb2-11e8-87a1-7471771ee952.png)
* step5
![step5](https://user-images.githubusercontent.com/1395710/42095136-0f12ce3e-7bb2-11e8-8615-de4c31340bda.png)
* step6
![spep6](https://user-images.githubusercontent.com/1395710/42095140-145d6368-7bb2-11e8-8b21-050c04acd741.png)

=> in step 6 i still have the new dashboard as expected.

**Comment by aptmac** [comment] 2018-06-29 13:41
Here I started on the analyze page for a space, with settings `beta` and indicator `on`. I went to the settings page and toggled the indicator `off` keeping `beta`, but when going back to the analyze page I'm seeing `internal` features.

![feature-indicator-toggle](https://user-images.githubusercontent.com/10425301/42095345-5bd54a58-7b80-11e8-8a83-635ccaa35866.gif)

**Comment by aptmac** [comment] 2018-06-29 14:37
After retracing my steps and checking out the network response from `user`, here's what I found:

EXPERIMENTAL & ON
"featureAcknowledgement":true
"featureLevel":"experimental"

BETA & ON
"featureAcknowledgement":true
"featureLevel":"beta"

BETA & OFF
"featureAcknowledgement":false
"featureLevel":"experimental"

It would appear that the act of updating the indicator true/false is causing my featureLevel to revert to whatever I had it set to before (experimental).

**Comment by aptmac** [comment] 2018-06-29 17:05
Does `UserService.loggedInUser` and `User.currentLoggedInUser` reference the same object? I'm trying to poke around to see if I can get a better understanding of what's going on, and I've noticed [0] and [1] currently use `currentLoggedInUser` and `loggedInUser` respectively, but if they are change to use the same then I stop seeing the issue where the feature level isn't updated properly. I still see an issue with the way the indicator shows & hides, but it seems to make the feature level persist a hard refresh from my initial digging.

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts#L66
[1] https://github.com/fabric8-ui/fabric8-ui/blob/arunkumars08-patch-1/src/app/getting-started/services/getting-started.service.ts#L49

**Comment by bmicklea** [comment] 2018-07-05 17:48
@corinnekrych could you add a severity level label please? It's difficult for me to ascertain what the right level here is...

**Comment by corinnekrych** [comment] 2018-07-06 06:41
fixed in https://github.com/fabric8-ui/fabric8-ui/pull/3098

**Closed by corinnekrych** 2018-07-06 06:41 UTC
Labels: area/feature flags, team/platform, type/bug
