### ISSUE TITLE
In Planner, work items that do not contain children display icon implying children

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3926] opened 2018-07-05 13:09 UTC
In Planner, workitems that contain child work items are displayed with a ">" symbol/link that expands the child list.

Workitems that do not contain child workitems are also displayed with the same symbol, but the link is not active and hovering over the link results in an indication that the link is not enabled.

![untitled](https://user-images.githubusercontent.com/642621/42325086-2560ec22-8033-11e8-8f8f-bc611ccbbe40.png)

Question - Can't we just not display the ">" link for workitems that do not contain child workitems?

**Comment by joshuawilson** [comment] 2018-11-01 04:32
Duplicate of #3052

**Closed by joshuawilson** 2018-11-01 04:32 UTC
Labels: area/planner, team/planner, type/feature-request
