### ISSUE TITLE
Performance Enhancements to the PGM

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#1474] opened 2017-11-29 09:26 UTC
### Description

This task is a part of story #1471. Currently the Kronos service takes about 40 seconds to respond to each request. By the way of parallelizing the probability calculation at the time of scoring and implementing the post-processing filters in a more efficient way we aim to bring down this response time.

### Task List
- [x] Decrease the post filter validation time.
- [ ] ~~Parallelize the execution of PGM scoring.~~

**Comment by msrb** [comment] 2017-11-30 07:51
This is great, thanks for looking into this. It will also help with https://github.com/openshiftio/openshift.io/issues/1144.

👍 

You guys rock 😉

**Comment by abs51295** [comment] 2017-12-07 17:30
For optimizing the post filter PTAL at the following https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/139.

**Comment by abs51295** [comment] 2017-12-07 17:31
For parallel execution of PGM PTAL at the following https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/140.

**Comment by miteshvp** [comment] 2017-12-13 04:22
@abs51295 - can we close this?

**Comment by abs51295** [comment] 2017-12-13 11:36
@miteshvp The PR for parallel execution of PGM was [reverted](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/146) because e2e tests were failing on the staging cluster. So, I think we need to figure out the root cause of why this is happening on the staging and not on dev cluster even though both have the same configuration. The problem happened when [this](https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/integration-tests/data/pom-effective.xml) pom-effective.xml was used as input manifest to the PGM. The dev cluster responds in ~50 seconds, but the same thing timeouts on staging.

**Comment by msrb** [comment] 2017-12-13 20:21
@abs51295 do you still have, by any chance, links to the e2e test failures that occurred on staging? the cluster was broken for couple days last week, no new deployments and so on... so maybe that was the reason for the failures?

**Comment by abs51295** [comment] 2017-12-15 06:49
@msrb I am not sure about the build number, but the logs were same as this: https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/448/console

**Comment by abs51295** [comment] 2018-01-10 06:17
I think PGM doesn't need parallel execution anymore since only companion packages are being fetched from PGM. The outlier logic has been already pulled out of PGM which can be tracked here #1429. Closing the issue. Thanks.

**Closed by abs51295** 2018-01-10 06:17 UTC
Labels: area/analytics, team/analytics, team/analytics/insights, type/task
