### ISSUE TITLE
For user provisioned on starter-us-east-2, environment reset fails with server (500) error

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4708] opened 2019-01-14 18:20 UTC
##### Issue Overview
Trying to reset the user env is failing for (at least 2) user accounts on the starter-us-east-2 cluster.

##### Expected Behaviour
Environment reset should be successful.

##### Current Behaviour
The reset is failing. 

##### Steps To Reproduce

1. Log onto https://openshift.io using an account provisioned on starter-us-east-2
2. In the browser, open the Developer Tools browser console
3. Attempt to reset the user environment
4. Observe that the environment is not reset - observe a server (500) error is written to the browser console log

##### Additional Information

![screenshot from 2019-01-14 13-13-31](https://user-images.githubusercontent.com/642621/51131974-1bae0700-17ff-11e9-8e24-b0f0a3238556.png)

**Comment by ldimaggi** [comment] 2019-01-14 18:24
In trying to start the Jenkins pod that is idles - seeing this error:

An error occurred scaling deployment config jenkins.
 Reason: deploymentconfigs "jenkins" is forbidden: User "osio-ci-preboost1" cannot update deploymentconfigs/scale in the namespace "osio-ci-preboost1-jenkins": no RBAC policy matched

![screenshot from 2019-01-14 13-07-18](https://user-images.githubusercontent.com/642621/51132243-bdcdef00-17ff-11e9-98a1-e106039c00e6.png)

**Comment by ljelinkova** [comment] 2019-01-15 07:09
I can confirm that the reset does not work for e2e tests on cluster 2 too. I can see the following in the broser logs:
```
WARNING https://openshift.io/osio-ci-e2e-005/_cleanup - Form submission canceled because the form is not connected
[18:21:42.880] SEVERE https://openshift.io/api/user/services - Failed to load resource: the server responded with a status of 500 (Internal Server Error)
[18:21:42.891] SEVERE https://openshift.io/_static/js/28.4b3e1ca0.chunk.js 0:3089067 e
[18:22:43.097] INFO https://openshift.io/_static/js/28.4b3e1ca0.chunk.js 0:3089067 "Refreshing token in: 540000 milliseconds."
[18:22:43.100] INFO https://openshift.io/_static/js/28.4b3e1ca0.chunk.js 0:3089067 "token refreshed at:1547490107162"
[18:22:46.984] WARNING https://openshift.io/osio-ci-e2e-005/_cleanup - Form submission canceled because the form is not connected
[18:22:47.985] SEVERE https://openshift.io/api/user/services - Failed to load resource: the server responded with a status of 500 (Internal Server Error)
[18:22:47.996] SEVERE https://openshift.io/_static/js/28.4b3e1ca0.chunk.js 0:3089067 e

```

**Comment by MatousJobanek** [comment] 2019-01-15 10:01
This was caused by the expired token for east-2 cluster. The token was updated, so this issue should be fixed.

**Comment by riuvshin** [comment] 2019-01-15 10:09
@MatousJobanek yeah this is woking now. Closing.

**Closed by riuvshin** 2019-01-15 10:09 UTC
Labels: SEV2-high, env/prod, priority/P1, team/service-delivery, type/bug

**Comment by ldimaggi** [comment] 2019-01-15 13:13
This should have been a SEV1 as there was no workaround for those users - thanks for the rapid response in getting it fixed!
