### ISSUE TITLE
"Community warnings" adding up when switching between runtimes

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#4110] opened 2018-08-01 10:07 UTC
Start switching back and forth between the runtimes (Thorntail - Vertx) to see that community warnings are getting stacked up.

![image](https://user-images.githubusercontent.com/719616/43515632-4639136a-9583-11e8-96f1-b1f5e8775482.png)

Side note: warning from using community versions contradicts with "open source way".

**Comment by ia3andy** [comment] 2018-08-01 14:48
Would you mind adding a copy of the dom?

In the dev console, you should see something like this: 
```
LaunchConfig is: {"origin":"launcher","commit_hash":"fe2af2e5c18aa7c1d30d16b4504ef328d2337558","backend_url":"https://forge.api.prod-preview.openshift.io/api/launchpad","keycloak_url":"https://sso.openshift.io/auth","keycloak_realm":"rh-developers-launch","keycloak_client_id":"openshiftio-public","backend_api_url":"https://forge.api.prod-preview.openshift.io/api","backend_websocket_url":"wss://forge.api.prod-preview.openshift.io"} 
```
Could you add this as well.

Cheers,

**Comment by ia3andy** [comment] 2018-08-01 14:53
@bartoszmajsak about the LaunchConfig, my bad, it's only present in the standalone Launcher.

Do you know if there is a way to find which osio ui version you are using so we can deduce the ngx-launcher version?

**Comment by bartoszmajsak** [comment] 2018-08-01 15:18
Coming from this : 

https://github.com/openshiftio/saas-openshiftio/blob/fe2f5b3b9b9da37a42b6043c80b9fd74c37d1464/dsaas-services/fabric8-ui.yaml#L2

Getting this answer:

https://github.com/fabric8-ui/fabric8-ui/blob/656d47a544a7ec56dbaa34ea769cb0f44c7f7021/package.json#L145

=> `1.0.3`

**Comment by ia3andy** [comment] 2018-08-01 16:10
@bartoszmajsak there are some errors (linked to the dependency editor) in the log when I am switching missions/runtimes in the osio flow which I don't have in the launcher flow.

```
ERROR TypeError: Cannot read property 'getCoreDependencies' of null
    at DependencyEditorCreateappStepComponent.handleBlankMissionFlow (eval at ./src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts (app.js:2870), <anonymous>:199:49)
    at DependencyEditorCreateappStepComponent.listenForChanges (eval at ./src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts (app.js:2870), <anonymous>:176:26)
    at eval (eval at ./src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts (app.js:2870), <anonymous>:81:23)
    at DefaultKeyValueDiffer.forEachChangedItem (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:7825:13)
    at DependencyEditorCreateappStepComponent.ngDoCheck (eval at ./src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts (app.js:2870), <anonymous>:80:21)
    at checkAndUpdateDirectiveInline (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:11050:19)
    at checkAndUpdateNodeInline (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12545:20)
    at checkAndUpdateNode (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12488:16)
    at debugCheckAndUpdateNode (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:13345:59)
    at debugCheckDirectivesFn (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:13286:13)
    at Object.eval [as updateDirectives] (LauncherComponent.html:26)
    at Object.debugUpdateDirectives [as updateDirectives] (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:13271:21)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12455:14)
    at callViewAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12803:21)
    at execEmbeddedViewsAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12761:17)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12456:5)
    at callViewAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12803:21)
    at execEmbeddedViewsAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12761:17)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12456:5)
    at callViewAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12803:21)
    at execComponentViewsAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12735:13)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12461:5)
    at callViewAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12803:21)
    at execComponentViewsAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12735:13)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12461:5)
    at callViewAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12803:21)
    at execEmbeddedViewsAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12761:17)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12456:5)
    at callViewAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12803:21)
    at execComponentViewsAction (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12735:13)
    at checkAndUpdateView (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:12461:5)
    at callWithDebugContext (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:13671:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:13211:12)
    at ViewRef_.detectChanges (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:10378:18)
    at eval (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:5016:63)
    at Array.forEach (<anonymous>)
    at ApplicationRef_.tick (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:5016:25)
    at eval (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4888:106)
    at ZoneDelegate.invoke (eval at ./node_modules/zone.js/dist/zone.js (polyfills.js:2596), <anonymous>:365:26)
    at Object.onInvoke (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4094:33)
    at ZoneDelegate.invoke (eval at ./node_modules/zone.js/dist/zone.js (polyfills.js:2596), <anonymous>:364:32)
    at Zone.run (eval at ./node_modules/zone.js/dist/zone.js (polyfills.js:2596), <anonymous>:125:43)
    at NgZone.run (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4025:69)
    at Object.next (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4888:82)
    at SafeSubscriber.schedulerFn [as _next] (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:3839:52)
    at SafeSubscriber.__tryOrUnsub (eval at ./node_modules/rxjs/Subscriber.js (vendor.js:195), <anonymous>:238:16)
    at SafeSubscriber.next (eval at ./node_modules/rxjs/Subscriber.js (vendor.js:195), <anonymous>:185:22)
    at Subscriber._next (eval at ./node_modules/rxjs/Subscriber.js (vendor.js:195), <anonymous>:125:26)
    at Subscriber.next (eval at ./node_modules/rxjs/Subscriber.js (vendor.js:195), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at ./node_modules/rxjs/Subject.js (vendor.js:179), <anonymous>:55:25)
    at EventEmitter.emit (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:3825:76)
    at checkStable (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4059:35)
    at onLeave (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4138:5)
    at Object.onInvokeTask (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.js:30), <anonymous>:4088:17)
    at ZoneDelegate.invokeTask (eval at ./node_modules/zone.js/dist/zone.js (polyfills.js:2596), <anonymous>:397:36)
    at Zone.runTask (eval at ./node_modules/zone.js/dist/zone.js (polyfills.js:2596), <anonymous>:165:47)
    at HTMLDivElement.ZoneTask.invoke (eval at ./node_modules/zone.js/dist/zone.js (polyfills.js:2596), <anonymous>:460:38)
```
I suspect it to be messing with angular rendering... 

I am going to investigate it further tomorrow.

**Comment by bartoszmajsak** [comment] 2018-08-01 17:31
Thanks a lot @ia3andy. I think it might have something to do with backend not handling properly rename of WildFly to Thorntail. But I guess in order to reproduce you can just stub that service with `500` :) Let me know if you need any help.

**Comment by bartoszmajsak** [comment] 2018-08-01 18:33
It seems to be fine in prod so I guess the analytics backend has been fixed. @miteshvp can you confirm that?

**Comment by ia3andy** [comment] 2018-08-02 09:10
@bartoszmajsak I fixed the bug in this PR:
https://github.com/fabric8-launcher/ngx-launcher/pull/341

**Comment by sanketpathak** [comment] 2018-08-09 11:42
@bartoszmajsak I'm not able to reproduce it, so closing the issue.

**Closed by sanketpathak** 2018-08-09 11:42 UTC
Labels: SEV3-medium, area/launcher, priority/P4, team/app-creation, type/bug
