### ISSUE TITLE
Cannot create new quickstarts on https://openshift.io

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2127] opened 2018-01-31 15:26 UTC
This issue just started in the past 20 min - attempts to create new quickstarts are failing:

![screenshot from 2018-01-31 10-20-26](https://user-images.githubusercontent.com/642621/35631113-0ec9ae04-0671-11e8-956a-856e47450896.png)

**Comment by ldimaggi** [comment] 2018-01-31 15:26
The problem seems to be limited to production, prod-preview is not showing this error.

**Comment by gastaldi** [comment] 2018-01-31 15:50
That's weird, I can create quickstarts in Production perfectly. Is there something wrong with your user? Can anyone else confirm that?

**Comment by gastaldi** [comment] 2018-01-31 15:51
Ah wait, I thought you were referring to the Wizard screen, that happens when the Finish button is pressed, right?

**Comment by gastaldi** [comment] 2018-01-31 15:53
The error in the log is: `
Caused by: java.nio.file.FileSystemException: /tmp/projectDir1105022648082137236: No space left on device
`

Can someone restart the pod please? This is another bug caused by the legacy forked code

**Comment by gastaldi** [comment] 2018-01-31 15:57
Also, can we have a Liveness Probe configured to automatically discard the pod if the space is near full? That would be a decent workaround until we finish migration

**Comment by gastaldi** [comment] 2018-01-31 16:23
After the pod was restarted, it works now. This should no longer happen once we get rid of the legacy code (being worked as part of the backend migration). Closing this issue

**Closed by gastaldi** 2018-01-31 16:23 UTC
Labels: SEV1-urgent, area/app-wizard, area/quickstarts, team/platform, type/bug
