### ISSUE TITLE
Vert.x Health Check quickstart - corrupted text in deployed app on stage and run 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3118] opened 2018-04-13 13:42 UTC
Steps to recreate:
* Create the new app in the launcher
* Upon successful completion of the build pipeline, access the deployed app at the OSIO stage and run endpoints
* See attached screenshot of deployed app:

![screenshot from 2018-04-13 09-36-18](https://user-images.githubusercontent.com/642621/38737955-dc0a7c02-3efe-11e8-8312-0b95800442cf.png)

**Comment by ldimaggi** [comment] 2018-04-13 14:00
Note that the error is not encountered if the app is run in Che and accessed at http://localhost:8080, per the quickstart's README file:

![screenshot from 2018-04-13 09-50-30](https://user-images.githubusercontent.com/642621/38738533-5d6dc2b2-3f00-11e8-9ebf-92539dab4b03.png)

**Comment by bartoszmajsak** [comment] 2018-08-12 08:55
Duplicate of https://github.com/openshiftio/openshift.io/issues/4016

**Closed by bartoszmajsak** 2018-08-12 08:55 UTC
Labels: SEV3-medium, area/quickstarts, priority/P4, team/launcher, type/bug
