### ISSUE TITLE
Import Wizard Caching Projects

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#534] opened 2017-08-09 20:36 UTC
If you add a new project to your github repo AFTER importing one previously, it does not show up in the list.

Steps to reproduce:
1) fork https://github.com/burrsutter/vertx-eventbus
2) Import the project from github 
3) let its pipeline run
4) fork https://github.com/burrsutter/vertx-paint
5) Import the project from github (it does not show up in the list)
https://screencast.com/t/Yh6jkm6y
https://screencast.com/t/GNwFJ7NV

**Comment by burrsutter** [comment] 2017-08-09 20:52
Workaround, wait a few minutes and it seems to timeout.

**Comment by qodfathr** [comment] 2018-01-17 18:50
I actually was able to reproduce this when importing the first project (on step # 2). There seems to be a issue whereby the Import Wizard is not seeing recently added stuff to GitHub. Maybe a GitHub API issue?

I canceled the Import Wizard and tried again, and it worked fine on the 2nd attempt. Moreover, when I got to step # 5, it works on the first try (and I did not delay between steps 4 and 5).

**Comment by qodfathr** [comment] 2018-01-30 16:00
Related: #1360

**Comment by animuk** [comment] 2018-06-05 06:42
Duplicate Issue : #1360. Hence Closing this.

**Closed by animuk** 2018-06-05 06:42 UTC
Labels: SEV3-medium, area/app-wizard, team/analytics/wizard, team/launcher, type/bug
