### ISSUE TITLE
Unable to create a Health Check Vert.x application

### ISSUE THREAD

**Issue by concaf** [openshiftio/openshift.io#3464] opened 2018-05-04 16:22 UTC
I go through the normal flow of creating an application on OSIO, but nothing happens when I click on "Set Up Application" and my console logs show -
`
400 - Bad Request [{"message":"java.lang.IllegalStateException: Error while preparing projectile: Booster not found in catalog: Mission [id=health-check, name=Health Check, description=Monitor an application's ability to service requests, metadata={level=foundational}]-Runtime [id=vert.x, name=Eclipse Vert.x, description=A tool-kit for building reactive applications on the JVM., metadata={pipelinePlatform=maven}]-Version [id=current-redhat, name=current-redhat, description=null, metadata={}] "}]
`

Here are the relevant screenshots -

![screenshot from 2018-05-04 21-51-26](https://user-images.githubusercontent.com/9133660/39638913-5d813dd8-4fe5-11e8-8d60-57e146a5fb2a.png)
![screenshot from 2018-05-04 21-51-15](https://user-images.githubusercontent.com/9133660/39638915-5dcac5ca-4fe5-11e8-8ce7-9416a7919183.png)
![screenshot from 2018-05-04 21-51-00](https://user-images.githubusercontent.com/9133660/39638916-5dfff0f6-4fe5-11e8-85f8-959c4432f0b1.png)

**Comment by containscafeine** [comment] 2018-05-04 16:30
Wait, that breaks the UI? :open_mouth: 
Yes, I did I guess, but then I deselected and selected all the other possible options as well.

**Comment by arunkumars08** [comment] 2018-05-04 16:33
@containscafeine Just to test, could you refresh and try once by selecting mission first and then runtime and see if the issue is still there?

**Comment by ldimaggi** [comment] 2018-05-04 17:05
I think that this is a duplicate of:  https://github.com/openshiftio/openshift.io/issues/3418

**Closed as completed** 2018-05-04 17:18 UTC
Labels: SEV1-urgent, type/bug, team/analytics/wizard, area/launcher, priority/P1
