### ISSUE TITLE
Few times, OSIO quick start builds are failing

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2522] opened 2018-03-09 11:53 UTC
Few times , OSIO builds are failing. Build for a quick start would go OK few times, so other times fail with this error:  https://gist.github.com/krishnapaparaju/79c550eac1b2eb8aba437d449e73f337

cc @chmouel @kbsingh @pradeepto

**Comment by chmouel** [comment] 2018-03-09 12:05
is sporadic service issues SEV1 ?

**Comment by chmouel** [comment] 2018-03-09 12:07
and we would need more details, please.

**Comment by piyush1594** [comment] 2018-03-09 12:14
Hey @krishnapaparaju 

Can you provide the details like,  which project you are building, which Openshift version you are using and command to reproduce this?

From logs, FMP 3.5.28 is getting used there.

Thanks

**Comment by chmouel** [comment] 2018-03-09 12:17
I am dropping the SEV1 until we get more infos

**Comment by krishnapaparaju** [comment] 2018-03-09 12:38
This problem happening at least 1 out of 3 times at starter-2 cluster. This I guess happening with all the quick starts.  Steps followed: Select a OSIO quick start after creating new space, this has triggered build. I have tried multiple builds. Some of them were successful. Other times, builds were failing with this error: https://gist.github.com/krishnapaparaju/79c550eac1b2eb8aba437d449e73f337

 Please see this screenshot of my pipelines screens for three OSIO spaces:
<img width="1406" alt="screen shot 2018-03-09 at 6 06 25 pm" src="https://user-images.githubusercontent.com/15967765/37207822-bf5b3c9a-23c4-11e8-9eed-0a78a07fc2df.png">

<img width="1412" alt="screen shot 2018-03-09 at 6 06 10 pm" src="https://user-images.githubusercontent.com/15967765/37207830-c827505c-23c4-11e8-8a2a-837352462f5d.png">

<img width="1413" alt="screen shot 2018-03-09 at 6 05 54 pm" src="https://user-images.githubusercontent.com/15967765/37207842-d11e569c-23c4-11e8-82c6-906c3411da81.png">

**Comment by hrishin** [comment] 2018-03-09 14:59
Hi @krishnapaparaju 
Thanks for reporting this issue. On which cluster you are running these builds?

**Comment by joshuawilson** [comment] 2018-03-10 14:28
@krishnapaparaju what `type` is this?

**Comment by hrishin** [comment] 2018-03-15 08:07
@krishnapaparaju could you provide more updates, please?

**Comment by chmouel** [comment] 2018-03-15 08:57
Let's close this and reopen if it's happen again,

**Comment by krishnapaparaju** [comment] 2018-03-15 16:20
This is happening at OSIO (starter-2 cluster). This is a bug with a timeout error. Please check the comments above. 

3 Consecutive VertX http booster builds now, please see this new screen shot..

<img width="1389" alt="screen shot 2018-03-15 at 9 47 30 pm" src="https://user-images.githubusercontent.com/15967765/37476315-db7ade50-289a-11e8-8e76-373be342290c.png">

**Comment by chmouel** [comment] 2018-03-15 16:22
Since we cannot reproduce (it's an intermittent error) can you copy paste the developper console network information and see which service fails, pleae

**Comment by ldimaggi** [comment] 2018-03-15 16:51
Is this the same problem as:  https://github.com/openshiftio/openshift.io/issues/2427

What do you see in the Jenkins pod log?

**Comment by chmouel** [comment] 2018-03-15 17:00
Ah yeah right @ldimaggi thanks for pointing this out,

**Comment by ldimaggi** [comment] 2018-03-15 17:07
The interesting thing is that this problem is now being seen intermittently by multiple people.

**Comment by chmouel** [comment] 2018-03-16 07:04
This is the related issue we are working on https://github.com/openshiftio/openshift.io/issues/2427 let's close this and work on this one instead,

**Closed by chmouel** 2018-03-16 07:04 UTC
Labels: SEV2-high, team/build-cd
