### ISSUE TITLE
"Recent spaces" in user account home page shows deleted spaces

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3783] opened 2018-06-13 14:34 UTC
Steps to recreate this issue:
* Create and delete the same space multiple times
* Observe multiple instances of the name of the deleted space listed in the user account home page:

![screenshot from 2018-06-13 10-14-05](https://user-images.githubusercontent.com/642621/41357904-3096b01c-6ef5-11e8-8965-a501f1feee8c.png)

**Comment by joshuawilson** [comment] 2018-06-13 15:49
If you refresh do they go away?

**Comment by ldimaggi** [comment] 2018-06-13 17:31
Before browser refresh:
![screenshot from 2018-06-13 13-29-20](https://user-images.githubusercontent.com/642621/41367773-fe489f94-6f0d-11e8-8d00-4dcdde22f6f0.png)

After browser refresh:
![screenshot from 2018-06-13 13-30-25](https://user-images.githubusercontent.com/642621/41367786-090b0c28-6f0e-11e8-9a25-2d60b9ec387f.png)

**Comment by joshuawilson** [comment] 2018-06-13 17:39
This is part of the old issue about needing to refresh. Once we get the smart components and state in place we can look at fixing this.

**Comment by aptmac** [comment] 2018-06-20 19:01
duplicate of: https://github.com/openshiftio/openshift.io/issues/2196

**Closed by aptmac** 2018-06-20 19:01 UTC
Labels: SEV3-medium, area/spaces, team/platform, type/bug
