### ISSUE TITLE
Cancel [X] button does not work in 'Create an Application' launcher in production

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#3646] opened 2018-05-25 09:14 UTC

**Comment by pmacik** [comment] 2018-05-25 09:14
Kind of duplicate of https://github.com/openshiftio/openshift.io/issues/3586, but on production (https://openshift/io)

**Comment by pmacik** [comment] 2018-05-25 09:19
The cancel button does not work only when the app launcher is opened by the create-a-space wizard.
It works when the launcher is opened manually by clicking on [Add to space] button from a space dashboard.

**Comment by jyasveer** [comment] 2018-05-25 18:06
@pmacik I tried just now with production. Cancel button is working for me for both the cases
- one which is opened from by the create space wizard
- other one which opened by the create application button from a space
Tested in Chrome 66

Could you tell me some more details of the issue so that i can reproduce it.

**Comment by ldimaggi** [comment] 2018-05-25 18:21
This consistently fails for me if I start by performing a reset of the user env.

See: https://github.com/openshiftio/openshift.io/issues/3657

**Comment by joshuawilson** [comment] 2018-05-25 23:09
duplicate of #3657

**Closed** 2018-05-25 23:09 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, env/prod, status/info-needed, team/analytics/wizard, type/bug
