### ISSUE TITLE
Planner : creating new label closes the tree heirarachy

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2468] opened 2018-03-06 12:20 UTC
Steps:

- Click on Scenario work item type group.
- Click on show child of a work item
- Now click on work item to open quick preview.
- Click 'Add Label' and create a new label
Tree heirarachy is collapsed

**Comment by joshuawilson** [comment] 2018-03-07 14:09
What `severity` is this?

**Comment by sanbornsen** [comment] 2018-03-13 17:09
This issue is fixed in following PR  - https://github.com/fabric8-ui/fabric8-planner/pull/2488

**Comment by rgarg1** [comment] 2018-03-15 05:03
Cannot reproduce this issue with https://fabric8-ui-fabric8-ui-pr-2488-fabric8-planner.badger.fabric8.io

**Closed** 2018-03-23 05:30 UTC
Labels: area/planner, team/planner, type/task
