### ISSUE TITLE
Description can't be added in analyze

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3342] opened 2018-04-27 12:43 UTC
![desc](https://user-images.githubusercontent.com/34271052/39363095-acf2f0c2-4a46-11e8-862b-cd3f355ad865.gif)

**Comment by aptmac** [comment] 2018-04-27 13:55
duplicate of https://github.com/openshiftio/openshift.io/issues/2879

**Closed by aptmac** 2018-04-27 13:55 UTC
Labels: SEV2-high, area/dashboard, team/platform, type/bug
