### ISSUE TITLE
stage and run links are not showing on pipeline for import flow (if repo name and artifact id do not match)

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3003] opened 2018-04-11 12:28 UTC
![screen](https://user-images.githubusercontent.com/11839674/38616427-a1916408-3db1-11e8-969b-d565b4d97bb0.png)
deployed application links for the stage and run on pipeline screen is missing for new launcher import flow.

**Comment by joshuawilson** [comment] 2018-04-11 13:00
Please add team and type labels. (area is nice too)

**Comment by ldimaggi** [comment] 2018-04-11 13:04
Duplicate of:  https://github.com/openshiftio/openshift.io/issues/2920

**Comment by invincibleJai** [comment] 2018-04-11 14:10
@ldimaggi I don't think it's duplicate of #2920 as this talks specifically about "import flow" in new launcher. 

let me know your thoughts, I feel we should have it open to track.
CC @joshuawilson

**Comment by ravsa** [comment] 2018-04-11 15:46
I tried new launcher create flow  and deployed application links are coming for stage and run. This issue specifically talk about import flow. I am working  with @edewit to fix this issue soon.
cc @gastaldi

**Comment by animuk** [comment] 2018-04-12 20:14
I would say this is an existing bug which is there in the legacy flow itself. trick to reproduce is choose a repository to import that has the repo name and artifact id different. then also, you can not see pipleline links in the pipeline UI.

**Comment by animuk** [comment] 2018-04-13 03:25
cc @krishnapaparaju @ravsa

**Comment by ravsa** [comment] 2018-04-13 03:53
@animuk I found the same. If artifact id is same as project name in new import flow links are coming.

**Comment by invincibleJai** [comment] 2018-04-13 05:15
@animuk @ravsa nice, but in legacy wizard user is not supposed to enter app name so it's not a problem for end-user but in new launcher flow user needs to enter app name so it won't be a good user experience as we can't expect user to user same app name as is artifact id in import application

**Comment by invincibleJai** [comment] 2018-04-13 05:30
@gastaldi am not sure, could be. What is the need to have app name same as artifact ID am not able to understand? 

As for legacy wizard pipelines is working fine, not sure if pipelines UI is making use of App name to get routes for stage and prod, which API/sockets it's consuming. I tried debugging couldn't make out completely.

@joshuawilson any help how it works for maybe the right person to reach out to.

**Comment by maxandersen** [comment] 2018-04-24 22:31
> @joshuawilson any help how it works or maybe the right person to reach out to.

@invincibleJai are you still awaiting input here or is it fixed in the #2754 merge ? 

if questions around how pipelines UI/backend work that is for team/build-cd; possibly @chmouel or @rupalibehera  are best candidates.

**Comment by invincibleJai** [comment] 2018-04-25 05:15
> @invincibleJai are you still awaiting input here or is it fixed in the #2754 merge ?

@maxandersen Thanks Max, it's fixed now. Changes are in prod. Didn't closed it as changes were not promoted to prod earlier.

**Closed by invincibleJai** 2018-04-25 05:15 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, priority/P0, status/completed, team/analytics/wizard, team/build-cd, type/bug
