### ISSUE TITLE
Tests fail at Che for WF-Swarm -- HTTP (Community)

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3434] opened 2018-05-03 16:11 UTC
In the Che editor, booster builds are failing. Tests has been failing.
But, We can build the booster at Che by invoking command : mvn install -DskipTests
![today1](https://user-images.githubusercontent.com/11207106/39589050-be76afae-4f1a-11e8-80c9-bc5b557b4a2e.png)

**Comment by animuk** [comment] 2018-05-04 07:00
Here is the complete stacktrace:
https://gist.github.com/animuk/fa4b27dd71172ba0400c73b80221d99d

**Comment by ibuziuk** [comment] 2018-05-04 09:42
@animuk several questions:
- does community version is used on osio ?
- isn't it a duplicate of https://github.com/openshiftio/openshift.io/issues/2152 ?

**Comment by animuk** [comment] 2018-05-04 10:48
@ibuziuk yes, community version of wildflyswarm is used. and It looks to be duplicate.

**Comment by ibuziuk** [comment] 2018-05-04 11:44
@animuk thanks for the info. Closing as a duplicate of https://github.com/openshiftio/openshift.io/issues/2152

**Closed by ibuziuk** 2018-05-04 11:44 UTC
Labels: SEV2-high, area/che, area/launcher, priority/P0, team/test
