### ISSUE TITLE
Misleading API response

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#834] opened 2017-09-18 19:10 UTC
_From @pkajaba on June 12, 2017 10:1_

When I try to create an analysis for one component for the first time I got this response:
```
$ curl  http://localhost:32000/api/v1/component-analyses/maven/io.vertx:vertx-core/3.4.1
{
  "error": "No data found for maven Package io.vertx:vertx-core/3.4.1"
}
```
I believe it's not an error that there are no data and I think that when there is analysis in progress for this package there could be information about it instead of this "error" message.

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#23_

**Comment by samuzzal-choudhury** [comment] 2017-09-18 19:10
_From @pkajaba on June 12, 2017 10:1_

@samuzzal-choudhury What do you think about it?

**Comment by samuzzal-choudhury** [comment] 2017-09-18 19:10
_From @fridex on June 12, 2017 10:35_

> I believe it's not an error that there are no data and I think that when there is analysis in progress for this package there could be information about it instead of this "error" message.

+1 for a more descriptive message.

**Comment by samuzzal-choudhury** [comment] 2017-09-18 19:10
@pkajaba sorry for the long delay. +1.

**Comment by qodfathr** [comment] 2018-01-19 18:15
Since the message returned is, in fact, wrong (it's more than misleading, IMHO), I'm reclassifying as a bug.

**Comment by krishnapaparaju** [comment] 2018-01-23 02:08
@samuzzal-choudhury please check if this issue is reproducible..

**Comment by samuzzal-choudhury** [comment] 2018-01-23 09:07
@pkajaba After putting some more thought on this, I feel that this is appropriately reported as an HTTP error 404 (not found) and hence the response comes with the key "error". As we always (and will always) integrate this endpoint with OSIO/IDE, this is not going to have any user impact. Can we close this?

**Comment by pkajaba** [comment] 2018-01-24 08:05
@samuzzal-choudhury your representation seems correct to me. I am closing it

**Closed by pkajaba** 2018-01-24 08:05 UTC
Labels: SEV3-medium, area/analytics/core-api, team/analytics, team/analytics/integration, type/bug
