### ISSUE TITLE
Booster jenkins job fails: Unable to build the image using the OpenShift build service: An error has occurred. timeout: Socket closed

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2984] opened 2018-04-10 15:45 UTC
Jenkins job for a new quickstart created by the launcher fails to build:
```
OpenShift Build osio-ci-ee2/booster-che-workspace-0-0-1523373928585-1 from https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git
Connecting to https://api.github.com using osioperftest/****** (cd-github)
Obtained Jenkinsfile from f31b487472db9b03097ac5633d1075b580d53906
Loading library github.com/fabric8io/fabric8-pipeline-library@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git ls-remote -h -t https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Found match: refs/heads/master revision 8f9a039c3d1c2962d1a5b874592b7aa277140972
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/fabric8io/fabric8-pipeline-library.git
 > git init /var/lib/jenkins/jobs/osioperftest/jobs/booster-che.3j66leb.523373928585/branches/master/workspace@libs/github.com/fabric8io/fabric8-pipeline-library # timeout=10
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > git fetch --no-tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 8f9a039c3d1c2962d1a5b874592b7aa277140972 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 8f9a039c3d1c2962d1a5b874592b7aa277140972
Commit message: "Auto format code with Intellij"
First time build. Skipping changelog.
[Pipeline] echo
WARNING: Failed to invoke Environments.namespaceForEnvironment(environment) probably due to API whitelisting: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [fabric8-environments]  in namespace: [osio-ci-ee2-jenkins]  failed.
[Pipeline] echo
WARNING: Failed to invoke Environments.namespaceForEnvironment(environment) probably due to API whitelisting: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [fabric8-environments]  in namespace: [osio-ci-ee2-jenkins]  failed.
[Pipeline] echo
WARNING: Failed to invoke Environments.loadPipelineConfiguration() probably due to API whitelisting: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [fabric8-pipelines]  in namespace: [osio-ci-ee2]  failed.
[Pipeline] echo
Loaded PipelineConfiguration null
[Pipeline] echo
WARNING: Failed to find the getUseDockerSocketFlag() flag on the PipelineConfiguration object - probably due to the jenkins plugin `kubernetes-pipeline-plugin` version: java.lang.NullPointerException: Cannot invoke method getUseDockerSocketFlag() on null object
[Pipeline] echo
WARNING: Failed to use the OpenShiftClient.supportsOpenShiftAPIGroup() API: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
jenkins-slave-rzq66-xwg8v is offline
Running on jenkins-slave-rzq66-xwg8v in /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ
[Pipeline] {
[Pipeline] checkout
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git
 > git init /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ # timeout=10
Fetching upstream changes from https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git
using GIT_ASKPASS to set credentials cd-github
 > git fetch --no-tags --progress https://github.com/osioperftest/booster-che-workspace-0-0-1523373928585.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision f31b487472db9b03097ac5633d1075b580d53906 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f31b487472db9b03097ac5633d1075b580d53906
Commit message: "Initial commit"
First time build. Skipping changelog.
fatal: bad object 8f9a039c3d1c2962d1a5b874592b7aa277140972
[Pipeline] echo
Using branch master
[Pipeline] echo
Using branch master
[Pipeline] pwd
[Pipeline] load
[Pipeline] // load
[Pipeline] echo
Jenkinsfile.setup.groovy not found
[Pipeline] echo
NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] sh
[ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ] Running shell script
+ git checkout -b osioperftest/booster-che-workspace-0-0-1523373928585/master-1.0.1
Switched to a new branch 'osioperftest/booster-che-workspace-0-0-1523373928585/master-1.0.1'
[Pipeline] readMavenPom
[Pipeline] sh
[ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ] Running shell script
+ mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -U -DnewVersion=1.0.1
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ
[INFO] Processing change of io.openshift.booster:booster-resthttp-vertx-1523373937754:1.0.0 -> 1.0.1
[INFO] Processing io.openshift.booster:booster-resthttp-vertx-1523373937754
[INFO]     Updating project io.openshift.booster:booster-resthttp-vertx-1523373937754
[INFO]         from version 1.0.0 to 1.0.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.595 s
[INFO] Finished at: 2018-04-10T15:31:04+00:00
EXITCODE   0[INFO] Final Memory: 10M/14M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ] Running shell script
+ mvn clean -B -e -U deploy -Dmaven.test.skip=false -P openshift
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ booster-resthttp-vertx-1523373937754 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java-version) @ booster-resthttp-vertx-1523373937754 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven-version) @ booster-resthttp-vertx-1523373937754 ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Executing: /bin/sh -c cd '/home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ
[INFO] Storing buildNumber: f31b487472db9b03097ac5633d1075b580d53906 at timestamp: 1523374303642
[INFO] Storing buildScmBranch: osioperftest/booster-che-workspace-0-0-1523373928585/master-1.0.1
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.13:initialize (vmp) @ booster-resthttp-vertx-1523373937754 ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.38:resource (fmp) @ booster-resthttp-vertx-1523373937754 ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using docker image name of namespace: osio-ci-ee2-jenkins
[INFO] F8: Running generator vertx
[INFO] F8: vertx: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2 as base / builder
[INFO] F8: using resource templates from /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/src/main/fabric8
[INFO] F8: fmp-controller: Adding a default Deployment
[INFO] F8: fmp-service: Adding a default service 'booster-resthttp-vertx-1523373937754' with ports [8080]
[INFO] F8: vertx-health-check: Adding readiness probe on port 8080, path='/', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: vertx-health-check: Adding liveness probe on port 8080, path='/', scheme='HTTP', with initial delay 180 seconds
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: f8-icon: Adding icon for deployment
[INFO] F8: f8-icon: Adding icon for service
[INFO] F8: validating /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/classes/META-INF/fabric8/openshift/booster-resthttp-vertx-1523373937754-svc.yml resource
[INFO] F8: validating /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/classes/META-INF/fabric8/openshift/booster-resthttp-vertx-1523373937754-deploymentconfig.yml resource
[INFO] F8: validating /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/classes/META-INF/fabric8/openshift/booster-resthttp-vertx-1523373937754-route.yml resource
[INFO] F8: validating /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/classes/META-INF/fabric8/kubernetes/booster-resthttp-vertx-1523373937754-svc.yml resource
[INFO] F8: validating /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/classes/META-INF/fabric8/kubernetes/booster-resthttp-vertx-1523373937754-deployment.yml resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Surefire report directory: /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/surefire-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.openshift.booster.HttpApplicationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 10, 2018 3:32:18 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 06:26:9a:03:8f:cf:ca:c3
Server started on port 8081
Server started on port 8081
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.409 s - in io.openshift.booster.HttpApplicationTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Building jar: /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/booster-resthttp-vertx-1523373937754-1.0.1.jar
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.13:package (vmp) @ booster-resthttp-vertx-1523373937754 ---
[INFO] Executing: /bin/sh -c cd '/home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ' && 'git' 'whatchanged' '--until=2018-04-10 15:32:22 +0000' '--date=iso' '--' '/home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ'
[INFO] Working directory: /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.38:build (fmp) @ booster-resthttp-vertx-1523373937754 ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator vertx
[INFO] F8: vertx: Using Docker image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2 as base / builder
[INFO] Copying files to /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/docker/booster-resthttp-vertx-1523373937754/1.0.1/build/maven
[INFO] Building tar: /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/docker/booster-resthttp-vertx-1523373937754/1.0.1/tmp/docker-build.tar
[INFO] F8: [booster-resthttp-vertx-1523373937754:1.0.1] "vertx": Created docker source tar /home/jenkins/workspace/ce-0-0-1523373928585_master-M5UWLRNXFZAJ6C7VRT3WCPUNH4KWQ4FOA4AMO66XEUC65XUA6FGQ/target/docker/booster-resthttp-vertx-1523373937754/1.0.1/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig booster-resthttp-vertx-1523373937754-s2i for Source build
[INFO] F8: Creating ImageStream booster-resthttp-vertx-1523373937754
[INFO] F8: Starting Build booster-resthttp-vertx-1523373937754-s2i
EXITCODE   0[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:47 min
[INFO] Finished at: 2018-04-10T15:37:55+00:00
[INFO] Final Memory: 36M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project booster-resthttp-vertx-1523373937754: Failed to execute the build: Unable to build the image using the OpenShift build service: An error has occurred. timeout: Socket closed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project booster-resthttp-vertx-1523373937754: Failed to execute the build
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute the build
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:270)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.executeInternal(BuildMojo.java:228)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute(BuildMojo.java:199)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:121)
	at io.fabric8.maven.plugin.mojo.build.BuildMojo.buildAndTag(BuildMojo.java:267)
	... 26 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:276)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:231)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:68)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.startBuild(OpenshiftBuildService.java:361)
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildService.build(OpenshiftBuildService.java:111)
	... 27 more
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:359)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:274)
	... 31 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 56 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by pmacik** [comment] 2018-04-10 16:25
@ldimaggi It is on `starter-us-east-2a` cluster... So, it is likely.

**Comment by mmclanerh** [comment] 2018-06-26 05:50
this is a bit old -- is this still an issue?

**Comment by piyush1594** [comment] 2018-06-26 06:00
Duplicate of #3058

**Comment by piyush1594** [comment] 2018-06-26 06:01
Closin this.

**Closed by piyush1594** 2018-06-26 06:01 UTC
Labels: area/jenkins, area/quickstarts, env/prod, team/service-delivery, type/incident-report
