### ISSUE TITLE
Mercator worker returns empty results

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#3182] opened 2018-04-18 07:31 UTC
Package `io.vertx:vertx-web::3.5.1` analyzed in prod-preview:

```
{
  "_audit": {
    "ended_at": "2018-04-17T19:15:31.430022",
    "started_at": "2018-04-17T19:15:02.672841",
    "version": "v1"
  },
  "_release": "maven:io.vertx:vertx-web:3.5.1",
  "details": [
    {
      "ecosystem": "java-pom"
    }
  ],
  "schema": {
    "name": "metadata",
    "version": "3-3-0"
  },
  "status": "success",
  "summary": []
}
```

That's not correct as the package has dependencies: http://central.maven.org/maven2/io/vertx/vertx-web/3.5.1/vertx-web-3.5.1.pom

This problem must have been introduced recently.

**Comment by msrb** [comment] 2018-04-18 07:32
Recently=last month or so

**Comment by tuxdna** [comment] 2018-04-18 10:48
Running ingestion for this package on local machine gives 

```
{
  "_audit": {
    "ended_at": "2018-04-18T10:11:18.521700",
    "started_at": "2018-04-18T10:09:01.544437",
    "version": "v1"
  },
  "_release": "maven:io.vertx:vertx-web:3.5.1",
  "details": [
    {
      "ecosystem": "java-pom"
    }
  ],
  "schema": {
    "name": "metadata",
    "version": "3-3-0"
  },
  "status": "success",
  "summary": []
}
```

So it looks like the issue is reproduced.

**Comment by tuxdna** [comment] 2018-04-19 10:30
This is the output I get from `mercator` present in worker-ingestion container:

```
$ mercator t/vertx-web-3.5.1.pom 
{
   "versions": {},
   "items": null
}

```

With mercator compiled from master branch and additional debug statements uncommented I still get this output:

```
$  MERCATOR_JAVA_RESOLVE_POMS=TRUE mercator t/vertx-web-3.5.1.pom  
{
   "versions": {},
   "items": null
}

```

It appears to be that there is a bug in Mercator.

**Comment by pkajaba** [comment] 2018-04-19 11:04
@tuxdna rename `vertx-web-3.5.1.pom` to `pom.xml` and it will work.

it's because of this https://github.com/fabric8-analytics/mercator-go/blob/master/handlers/java_handler/src/main/java/mercator/MercatorJava.java#L47

**Comment by tuxdna** [comment] 2018-04-20 10:25
We should have used pom.xml instead. So after renaming `t/vertx-web-3.5.1.pom` to `t/pom.xml` we get following output in current steup:

```
bash-4.2# mercator /tmp/t/pom.xml 
{
   "versions": {
      "Java-POM": "899ed7f8dff79625fbb39699ff4bcdb488d1fb86"
   },
   "items": [
      {
         "time": "2018-04-20T10:20:58.398662706Z",
         "path": "/tmp/t/pom.xml",
         "ecosystem": "Java-POM",
         "result": {
            "pom.xml": {
               "artifactId": "vertx-web",
               "dependencies": {
                  "compile": {
                     "io.vertx:vertx-auth-common::": "",
                     "io.vertx:vertx-auth-htdigest::": "",
                     "io.vertx:vertx-auth-jwt::": "",
                     "io.vertx:vertx-auth-oauth2::": "",
                     "io.vertx:vertx-bridge-common::": ""
                  },
                  "test": {
                     "io.vertx:vertx-auth-shiro::": "",
                     "io.vertx:vertx-unit::": "",
                     "io.vertx:vertx-web-client::": "",
                     "org.mockito:mockito-core::": "2.7.22",
                     "org.slf4j:slf4j-api::": "1.7.21"
                  }
               },
               "licenses": []
            }
         },
         "digests": {
            "manifest": "8c3992ced279b1081a9e86c58fae242e75a9f864"
         }
      }
   ]
}

```


However with resolve pom flag set to true, the dependency output is empty:

```
bash-4.2# MERCATOR_JAVA_RESOLVE_POMS=TRUE mercator /tmp/t/pom.xml 
{
   "versions": {
      "Java-POM": "899ed7f8dff79625fbb39699ff4bcdb488d1fb86"
   },
   "items": [
      {
         "time": "2018-04-20T10:19:16.682987601Z",
         "path": "/tmp/t/pom.xml",
         "ecosystem": "Java-POM",
         "digests": {
            "manifest": "8c3992ced279b1081a9e86c58fae242e75a9f864"
         }
      }
   ]
}

```

The above outputs are from the `mercator` present in the container image.

Next is the output from `mercator` built from latest master:


```
$ mercator t2/pom.xml 
{
   "versions": {
      "Java-POM": "c3c8f96877329eb83a5da880044c00511919a84d"
   },
   "items": [
      {
         "time": "2018-04-20T15:10:11.224530049+05:30",
         "path": "/home/tuxdna/Downloads/t2/pom.xml",
         "ecosystem": "Java-POM",
         "result": {
            "pom.xml": {
               "artifactId": "vertx-web",
               "dependencies": {
                  "compile": {
                     "io.vertx:vertx-auth-common::": "",
                     "io.vertx:vertx-auth-htdigest::": "",
                     "io.vertx:vertx-auth-jwt::": "",
                     "io.vertx:vertx-auth-oauth2::": "",
                     "io.vertx:vertx-bridge-common::": ""
                  },
                  "test": {
                     "io.vertx:vertx-auth-shiro::": "",
                     "io.vertx:vertx-unit::": "",
                     "io.vertx:vertx-web-client::": "",
                     "org.mockito:mockito-core::": "2.7.22",
                     "org.slf4j:slf4j-api::": "1.7.21"
                  }
               },
               "licenses": []
            }
         },
         "digests": {
            "manifest": "8c3992ced279b1081a9e86c58fae242e75a9f864"
         }
      }
   ]
}

```

and with resolve poms flag set to true

```
$ MERCATOR_JAVA_RESOLVE_POMS=TRUE mercator t2/pom.xml 
{
   "versions": {
      "Java-POM": "c3c8f96877329eb83a5da880044c00511919a84d"
   },
   "items": [
      {
         "time": "2018-04-20T15:49:26.457040654+05:30",
         "path": "/home/tuxdna/Downloads/t2/pom.xml",
         "ecosystem": "Java-POM",
         "result": {
            "pom.xml": {
               "artifactId": "vertx-web",
               "dependencies": {
                  "compile": {
                     "io.vertx:vertx-auth-common::": "3.5.1",
                     "io.vertx:vertx-auth-htdigest::": "3.5.1",
                     "io.vertx:vertx-auth-jwt::": "3.5.1",
                     "io.vertx:vertx-auth-oauth2::": "3.5.1",
                     "io.vertx:vertx-bridge-common::": "3.5.1",
                     "io.vertx:vertx-core::": "3.5.1",
                     "io.vertx:vertx-lang-groovy::": "3.5.1",
                     "io.vertx:vertx-lang-js::": "3.5.1",
                     "io.vertx:vertx-lang-kotlin::": "3.5.1",
                     "io.vertx:vertx-lang-ruby::": "3.5.1",
                     "io.vertx:vertx-rx-java2::": "3.5.1",
                     "io.vertx:vertx-rx-java::": "3.5.1"
                  },
                  "provided": {
                     "io.vertx:vertx-codegen::": "3.5.1",
                     "io.vertx:vertx-codetrans::": "3.5.1",
                     "io.vertx:vertx-docgen::": "3.5.1"
                  },
                  "test": {
                     "io.netty:netty-tcnative-boringssl-static::": "2.0.7.Final",
                     "io.vertx:vertx-auth-shiro::": "3.5.1",
                     "io.vertx:vertx-core:test-jar:": "3.5.1",
                     "io.vertx:vertx-unit::": "3.5.1",
                     "io.vertx:vertx-web-client::": "3.5.1",
                     "junit:junit::": "4.12",
                     "org.mockito:mockito-core::": "2.7.22",
                     "org.slf4j:slf4j-api::": "1.7.21"
                  }
               },
               "groupId": "io.vertx",
               "licenses": [
                  "The Apache Software License, Version 2.0",
                  "Eclipse Public License - v 1.0"
               ],
               "scm_url": "git@github.com:vert-x3/vertx-ext-parent.git/vertx-ext-parent/vertx-web-parent/vertx-web",
               "url": "http://nexus.sonatype.org/oss-repository-hosting.html/vertx-parent/vertx-ext/vertx-ext-parent/vertx-web-parent/vertx-web",
               "version": "3.5.1"
            }
         },
         "digests": {
            "manifest": "8c3992ced279b1081a9e86c58fae242e75a9f864"
         }
      }
   ]
}

```

**Comment by pkajaba** [comment] 2018-04-20 12:05
@tuxdna it works for me either way (with/without flag and in/out container)

**Comment by tuxdna** [comment] 2018-04-20 13:14
This is what I get from mercator.py worker


```
worker-api_1            | 2018-04-20 13:06:03,622 [INFO] MercatorTask: Data: {'items': [{'time': '2018-04-20T13:03:49.854801209Z', 'digests': {'manifest': '8c3992ced279b1081a9e86c58fae242e75a9f864'}, 'ecosystem': 'Java-POM', 'path': '/var/lib/f8a_worker/worker_data/maven/io.vertx:vertx-web/3.5.1/pom.xml'}], 'versions': {'Java-POM': '899ed7f8dff79625fbb39699ff4bcdb488d1fb86'}}
```

This corresponds to following JSON data:

```
{
	"items": [{
		"time": "2018-04-20T13:03:49.854801209Z",
		"digests": {
			"manifest": "8c3992ced279b1081a9e86c58fae242e75a9f864"
		},
		"ecosystem": "Java-POM",
		"path": "/var/lib/f8a_worker/worker_data/maven/io.vertx:vertx-web/3.5.1/pom.xml"
	}],
	"versions": {
		"Java-POM": "899ed7f8dff79625fbb39699ff4bcdb488d1fb86"
	}
}
```

Clearly, no dependencies are being listed.

**Comment by tuxdna** [comment] 2018-04-20 13:14
@pkajaba What output do you get?

**Comment by tuxdna** [comment] 2018-04-23 08:44
Inside container:

```
bash-4.2# MERCATOR_JAVA_RESOLVE_POMS=TRUE java -jar /usr/share/mercator/java pom.xml
Processing file: pom.xml
NOTICE: Resolving POMs is enabled.
Attempting expansion of POM: pom.xml
[Fatal Error] resolvedpom5476296891468109575.xml:15:6: The processing instruction target matching "[xX][mM][lL]" is not allowed.
org.xml.sax.SAXParseException; systemId: file:/tmp/resolvedpom5476296891468109575.xml; lineNumber: 15; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at mercator.MavenUtils.readFileAsDocument(MavenUtils.java:91)
	at mercator.MavenUtils.getParsedExpandedPom(MavenUtils.java:82)
	at mercator.MavenUtils.getPomXmlEntries(MavenUtils.java:196)
	at mercator.MercatorJava.handlePomFile(MercatorJava.java:146)
	at mercator.MercatorJava.main(MercatorJava.java:49)
{}

```

**Comment by pkajaba** [comment] 2018-04-23 09:47
Great findings @tuxdna. However, I am not sure how to tackle this problem, since we can't easily update version of maven.

**Comment by tuxdna** [comment] 2018-04-23 10:24
Setting up Maven 3.5.3 inside the container using instructions [here](https://www.vultr.com/docs/how-to-install-apache-maven-3-5-on-centos-7) still has same bug. 

As noted earlier bot inside and outside the container the `effective-pom` plugin version used is same. So there must be some other dependency that is causing this behavior.

**Comment by tuxdna** [comment] 2018-04-23 10:34
I also tried 3.0.1 version of effective pom plugin inside the container, but still same behavior. 

```
bash-4.2# mvn org.apache.maven.plugins:maven-help-plugin:3.0.1:effective-pom -f pom.xml
```

This means there is some other dependency that is causing this behavior. Perhaps some component that generates XML documents.

**Comment by tuxdna** [comment] 2018-04-23 11:01
Highlighting the issue below ( extra XML tag ):

```patch
 <?xml version="1.0" encoding="UTF-8"?>
 <!-- ====================================================================== -->
 <!--                                                                        -->
 <!-- Generated by Maven Help Plugin on 2018-04-23T02:35:56                  -->
 <!-- See: http://maven.apache.org/plugins/maven-help-plugin/                -->
 <!--                                                                        -->
 <!-- ====================================================================== -->
@@ -12,7 +12,7 @@
 <!--                                                                        -->
 <!-- ====================================================================== -->
 
-
+<?xml version="1.0" encoding="UTF-8"?>
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

```

**Comment by pkajaba** [comment] 2018-04-23 11:55
I haven't encountered extra tag, but I am having this problem: https://github.com/trustin/os-maven-plugin/issues/21

And it seems that `vertx-web` package has a dependency on os-maven-plugin

**Comment by tuxdna** [comment] 2018-04-23 14:10
I also observe the warning:

```
[WARNING] Failed to inject repository session properties.
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
        at kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjector.java:22)
        at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:148)
        at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:107)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

```

I guess this is probably due to absence of `.m2` folder where the maven cache is stored. I need to verify this

**Comment by tuxdna** [comment] 2018-04-23 16:32
`effective-pom` plugin uses `plexus-utils` for generating POM XML files

https://github.com/apache/maven-help-plugin/blob/maven-help-plugin-2.2/src/main/java/org/apache/maven/plugins/help/EffectivePomMojo.java#L84


Via the constructor, the first xml tag is printed here:

https://github.com/codehaus-plexus/plexus-utils/blob/plexus-utils-1.5.7/src/main/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriter.java#L155


https://github.com/codehaus-plexus/plexus-utils/blob/plexus-utils-1.5.7/src/main/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriter.java#L368


Thereafter again once header comments are printed, xml tag is printed again:


https://github.com/codehaus-plexus/plexus-utils/blob/plexus-utils-1.5.7/src/main/java/org/codehaus/plexus/util/xml/pull/MXSerializer.java#L366


Esssentially `MavenXpp3Writer.java` again prints the xml tag. ( this is a generated file and is not present in the maven sources )

With that being the description, I haven't managed to figure out a working set of dependencies for container image yet. I think that the solution is between `plexus-utils`, `maven-model` and `maven` to be updated to working versions.

**Comment by tuxdna** [comment] 2018-04-24 11:10
I tried setting different versions of JAR files in `/usr/share/java/maven` and `/usr/share/java/plexus/` but this ended up in all different kinds of issues with missing methods and so on. So to figure out which versions will work is a no go.

Instead we can workaround by removing the extra xml tag in our code, rather than depending on updates to Maven in yum repo.

**Comment by pkajaba** [comment] 2018-04-25 08:13
I have tinkered with it even further and I was not able to get it working. I agree that we should strip comments from the beginning of the XML.

**Comment by tuxdna** [comment] 2018-04-25 08:25
There is one more bug in the generated XML that I found after implementing code to strip extra XML tag.


Following part of the generated XML is incorrect, due to which we get subsequent error in XML parsing.


```
XMLTag found
XMLTag found
[Fatal Error] resolvedpom-fixed8169430257397321725.xml:90:31: Element type "os.detected.release.like." must be followed by either attribute specifications, ">" or "/>".
org.xml.sax.SAXParseException; systemId: file:/tmp/resolvedpom-fixed8169430257397321725.xml; lineNumber: 90; columnNumber: 31; Element type "os.detected.release.like." must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at mercator.MavenUtils.readFileAsDocument(MavenUtils.java:127)
	at Main$.main(Script.scala:8)
	at Main.main(Script.scala)
```

Offending XML lines below. Notice the quotes inside xml tags:

```
90:    <os.detected.release.like."centos">true</os.detected.release.like."centos">
91:    <os.detected.release.like."rhel>true</os.detected.release.like."rhel>
92:    <os.detected.release.like.fedora">true</os.detected.release.like.fedora">
```

The above indicates more bugs in the container image.

**Comment by tuxdna** [comment] 2018-04-25 08:54
Atleast one person has reported same behavior here - https://stackoverflow.com/questions/38253619/maven-shade-plugin-detects-os-release-with-wrong-output-format-os-detected-rel

**Comment by tuxdna** [comment] 2018-04-25 08:59
Okay, figured out why this behavior ( quotes in xml ) is happening:

```
bash-4.2# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


```

In the above file `ID` and `ID_LIKE` values are provided with qoutes, which is not being interpolated by some Java library inside the container.

```
ID="centos"
ID_LIKE="rhel fedora"
```

Not sure which Java library needs to be patched to fix this.

**Comment by tuxdna** [comment] 2018-04-25 10:25
```
yum install java-1.8.0-openjdk-src
cd /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/
mkdir source/
cd source
unzip ../src.zip
```

Made changes to `java/io/File.java` class as in this [changes.diff.zip](https://github.com/openshiftio/openshift.io/files/1946548/changes.diff.zip) patch file. 


Updated bootclasspath in Maven 

```patch
--- /usr/share/maven/bin/mvn	2018-04-25 10:09:50.674542255 +0000
+++ /usr/share/maven/bin/mvn.old	2018-04-25 10:20:01.777714803 +0000
@@ -165,7 +165,6 @@
 fi
 
 exec "$JAVACMD" \
-  -Xbootclasspath/p:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/source \
   $MAVEN_OPTS \
   -classpath "${M2_HOME}"/boot/plexus-classworlds.jar \
   "-Dclassworlds.conf=${M2_HOME}/bin/m2.conf" \
```

And then figured out the offending Java module i.e. `os-maven-plugin` as below:

```
bash-4.2# mvn org.apache.maven.plugins:maven-help-plugin:2.2:effective-pom -Doutput=pom-expanded.xml -f /workdir/pom.xml
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
java.lang.RuntimeException: Found /etc/os-release here
	at java.io.File.<init>(File.java:284)
	at kr.motd.maven.os.Detector.getLinuxRelease(Detector.java:207)
	at kr.motd.maven.os.Detector.detect(Detector.java:81)
	at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:90)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

```

The resolve the latest issue, we can either fix `/etc/os-release` or update the `os-maven-plugin` to interpolate the values correctly.

**Comment by tuxdna** [comment] 2018-04-25 11:30
The above bug was fixed in this commit - https://github.com/trustin/os-maven-plugin/commit/28a9b45b8bf7c271e118a2c6f3113c6e852a9528

Now, need to figure out how to force effective-pom plugin to use `os-maven-plugin-1.6.0`

**Comment by tuxdna** [comment] 2018-04-26 10:32
The latest version of `maven-help-plugin` uses `os-maven-plugin-1.4.0.Final`, so essentially we cannot update that dependency anyway.

I have made required fixes to make the effective pom parsing work in mercator's java_handler - https://github.com/fabric8-analytics/mercator-go/pull/44/files

**Comment by tuxdna** [comment] 2018-05-02 06:12
The PR fix for this issue is pending review: https://github.com/fabric8-analytics/mercator-go/pull/44/

**Comment by tuxdna** [comment] 2018-05-02 17:50
Following PRs are now merged:

 * https://github.com/fabric8-analytics/fabric8-analytics-worker-base/pull/40
 * https://github.com/fabric8-analytics/mercator-go/pull/44

**Comment by tuxdna** [comment] 2018-05-06 19:27
Closing this issue as the fix has been promoted to production:
 
 - https://github.com/openshiftio/saas-analytics/pull/355

**Closed by tuxdna** 2018-05-06 19:27 UTC
Labels: SEV2-high, area/analytics/ingestion, team/analytics, team/analytics/core, type/bug
