### ISSUE TITLE
Can't create a new app using New Space wizard

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#3890] opened 2018-07-02 15:50 UTC
I'm trying to create a new Space & App:

1. Create new Space
2. Select Agile as template
3. Click OK. And now I see New Application page/wizard:
4. Problem: I try to click on the Cancel button but it doesn't do anything
5. Enter the app name
6. Problem: Continue button doesn't do anything.

I see that UI is trying to get the github token but it doesn't include Authorization header into the request, so, the backend returns 401.

It's broken in both preview and prod.

**Comment by sbose78** [comment] 2018-07-02 15:53
Same as this https://github.com/openshiftio/openshift.io/issues/3743

**Comment by alexeykazakov** [comment] 2018-07-02 15:56
> Same as this #3743

Not sure if it's the same. My account is connected to GitHub.

**Comment by invincibleJai** [comment] 2018-07-02 16:56
@alexeykazakov have tried in both prod/prod-preview could not reproduce it, I was able to create an app along with new space with Agile template. I even tried disconnecting GitHub from settings and that as well worked. 

Am I missing something here?

**Comment by joshuawilson** [comment] 2018-07-02 16:57
I can not reproduce this. Was the issue on prod?

**Comment by abs51295** [comment] 2018-07-02 17:04
I am able to reproduce this on prod. I am using Firefox.

**Comment by msrb** [comment] 2018-07-02 17:08
I am not able to reproduce this issue on prod (chrome).

**Comment by joshuawilson** [comment] 2018-07-02 17:09
I was NOT able to reproduce it on FF.

**Comment by alexeykazakov** [comment] 2018-07-02 17:10
It’s reproducible in both preview and prod for me. I’m using Chrome. I also tried incognito. Still can reproduce.

**Comment by abs51295** [comment] 2018-07-02 17:12
Well, I did a hard refresh and wasn't able to reproduce it anymore. Thanks.

**Comment by alexeykazakov** [comment] 2018-07-02 18:00
I tried many things (incognito mode, GitHub settings, etc) nothing helped.
But I tried to create spaces with "2018-07-02-01", "2018-07-02-02", "2018-07-02-03", etc names and could reproduce the issue. But then I tried to create a space with "abs" name and it worked! I couldn't reproduce the issue again. I tried it in preview and it helped as well. After that it worked even with "2018-N" names. And then it stopped. Then started to work again.

Not sure if it's really the space names like "2018-07-02-01" may trigger the problem (but not always).

**Comment by invincibleJai** [comment] 2018-07-03 05:09
IMO it shouldn't be SEV1 as for may it works as expected, we need to diagnose why it's happening intermittently for few.

**Comment by sivaavkd** [comment] 2018-07-03 05:13
I am not able to reproduce this, tested in Firefox and Chrome.

**Comment by animuk** [comment] 2018-07-03 10:00
@ldimaggi and @pmacik Can you test the scenario whther you can replicate this at the moment.

**Comment by pmacik** [comment] 2018-07-03 12:29
I just tried it on prod with Chrome and I wasn't able to reproduce it.

**Comment by animuk** [comment] 2018-07-23 06:19
since this is not reproducible anymore.closing this,

**Closed by animuk** 2018-07-23 06:19 UTC
Labels: SEV3-medium, area/app-wizard, area/space-wizard, team/analytics/wizard, type/bug
