### ISSUE TITLE
No way to remove a codebase from a space

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1344] opened 2017-11-13 20:55 UTC
Once you've added a codebase to a space. There is no way to remove it as far as I can find

Going to https://openshift.io/user/myspace/create

I can view information about the codebase, but not change anything.

**Comment by joshuawilson** [comment] 2017-11-14 03:32
This is a duplicate of #192 
cc @ashumilova

**Comment by qodfathr** [comment] 2018-01-20 19:28
Closed as dupe AND fixed.

**Closed by qodfathr** 2018-01-20 19:28 UTC
Labels: SEV3-medium, area/codebases, level/intermediate, team/che, team/che/plugins, type/bug
