### ISSUE TITLE
Sort filter values in alphabetical order

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3169] opened 2018-04-17 08:22 UTC
Area/Assignee/Creator/Label names listed in the Planner's filter toolbar are not sorted in any order and looking up an area in a big list could be user unfriendly.

The lists should be sorted in an alphabetical order for easy accessibility.

**Comment by debloper** [comment] 2018-04-17 14:49
Duplicate of #2604

**Comment by debloper** [comment] 2018-04-17 14:50
Can you please verify the PR https://github.com/fabric8-ui/fabric8-planner/pull/2524
If this works for you for the WI types, I can just extend it for other filters and update the PR.

**Comment by jarifibrahim** [comment] 2018-05-07 06:25
Fixed via https://github.com/fabric8-ui/fabric8-planner/pull/2524

**Closed by jarifibrahim** 2018-05-07 06:25 UTC
Labels: SEV3-medium, area/planner, team/planner, type/bug
