### ISSUE TITLE
on latest firefox spaces don't load and top navigation bar is missing

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#1064] opened 2017-10-06 08:35 UTC
when I try load https://openshift.io/openshiftio/openshiftio in latest firefox (beta) the spaces don't load (just gives error page) and top navigation bar is missing on openshift.io/_home too.

 https://v.usetapes.com/4Pebyoyjyh

the errors I see when loading openshiftio:

![error_-_openshift_io_and_analyze_-_openshift_io](https://user-images.githubusercontent.com/54129/31269778-ffccb702-aa81-11e7-8cd3-e3bae9bf7263.png)

**Comment by maxandersen** [comment] 2017-10-06 08:36
note: ffox beta works perfectly fine with all other major pages so we must have some bug or non-resilient code that gets triggered somehow.

**Comment by alexeykazakov** [comment] 2017-10-06 23:23
This is a duplicate of https://github.com/openshiftio/openshift.io/issues/1053
Ajax in Firefox doesn't follow 307 redirects for some reason. Maybe because it's CORS redirects: wit.osio -> auth.osio.
https://github.com/fabric8-services/fabric8-wit/pull/1694 should fix it.

**Closed by alexeykazakov** 2017-10-06 23:23 UTC
