### ISSUE TITLE
[Planner] Problem editing work item title

### ISSUE THREAD

**Issue by nimishamukherjee** [openshiftio/openshift.io#3776] opened 2018-06-13 10:45 UTC
In quick preview use the mouse and click on title, you cannot edit it.

**Comment by divyanshiGupta** [comment] 2018-07-11 12:22
@nimishamukherjee @rgarg1 can you please confirm if this issue still exists as I couldn't reproduce it.

**Comment by divyanshiGupta** [comment] 2018-07-12 06:12
Closing this issue since it is fixed now.

**Closed by divyanshiGupta** 2018-07-12 06:12 UTC
Labels: SEV3-medium, area/planner, team/planner, type/bug
