### ISSUE TITLE
Issue with Stack Report Recommendations and Pipelines

### ISSUE THREAD

**Issue by nelmax1** [openshiftio/openshift.io#714] opened 2017-08-30 16:23 UTC
Hello,

Stack Report Recommendations is keep on adding pom.xml tabs every second on both the Spaces. if I refresh the browser all those pom.xml tabs go away attached is what I see when I try to select the Pipeline for test "myspacebugtest" 

Also, when I switch space a new pom.xml tab is created in the Stack Report Recommendations section.

My OS is Sierra 10.12.6
I am using Chrome Version 60.0.3112.101 (Official Build) (64-bit) in incognito/private mode

![screen shot 2017-08-30 at 10 45 20 am](https://user-images.githubusercontent.com/31449686/29883140-474625f4-8d7d-11e7-9fc1-590f670f8ecd.png)

Thanks,
Massimo

**Comment by ldimaggi** [comment] 2017-08-30 17:05
I am seeing this too - the browser eventually reports that "analyze" is failing to respond. This should be blocker as it can render analytics (and the browser) unusable.

**Comment by ldimaggi** [comment] 2017-08-30 17:12
See screencast:

https://drive.google.com/a/redhat.com/file/d/0B1s-ZoxD8FjUdG5Fc2xkNWlPTFU/view?usp=sharing

**Comment by ldimaggi** [comment] 2017-08-30 17:13
![screenshot from 2017-08-30 13-00-40](https://user-images.githubusercontent.com/642621/29885458-f246b872-8d84-11e7-9687-be027c9fbb26.png)

**Comment by ldimaggi** [comment] 2017-08-30 17:20
The loop of creating more and more pom.xml entries seems to stop when the build pipeline completes.

**Comment by alexeykazakov** [comment] 2017-08-30 18:57
It's not a blocker just for Annalists. It blocks the entire space dashboard page. This bug overloads the browser and kills the space dashboard page eventually.

**Comment by arunkumars08** [comment] 2017-08-30 21:16
Bug that created multiple pushes of the same file has been fixed and is in prod. Please review and let me know if you can still see multiple push behaviour.

**Comment by arunkumars08** [comment] 2017-08-31 16:30
@nelmax1 @ldimaggi Please let me know if this issue still appears. This has been fixed already and is in production.

**Comment by nelmax1** [comment] 2017-08-31 19:31
Looks better now, thank you

**Comment by arunkumars08** [comment] 2017-09-01 06:18
@nelmax1 If things are fine, I think you can close it.

**Comment by GeorgeActon** [comment] 2017-09-06 12:44
@nelmax1  Am closing this issue now since you confirmed the fix above

**Comment by GeorgeActon** [comment] 2017-09-06 12:45
Closing as per @nelmax1 confirmation.

**Closed by GeorgeActon** 2017-09-06 12:44 UTC
Labels: area/analytics, kind/bug, severity/blocker, team/analytics

**Comment by bartoszmajsak** [comment] 2017-09-06 12:48
Could be good to refer PR bringing the fix to this issue.

**Comment by GeorgeActon** [comment] 2017-09-06 12:55
@arunkumars08 Please add reference to PR

**Comment by invincibleJai** [comment] 2017-09-06 16:19
@GeorgeActon reference PR : https://github.com/fabric8-ui/fabric8-recommender/pull/288
