### ISSUE TITLE
New app creation failing in launcher

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3639] opened 2018-05-24 23:06 UTC
Steps to recreate:
* Login to https://openshift.io
* Create a new space
* Attempt to create a new app/quickstart
* Observe that after entering the quickstart name and clicking 'Continue' - the new app launcher exits

![myimage](https://user-images.githubusercontent.com/642621/40517787-23cec132-5f85-11e8-998b-f08eb7beddf9.gif)

**Comment by joshuawilson** [comment] 2018-05-25 01:15
Confirmed, I get the same.

**Comment by animuk** [comment] 2018-05-25 03:44
I have tried with the steps described above by creating a new space. I could not able to reproduce it.

**Comment by joshuawilson** [comment] 2018-05-25 03:48
did you try a hard refresh

**Comment by animuk** [comment] 2018-05-25 03:51
Yes. @joshuawilson . I did the hard refresh. Created a new space. Then, proceeds on creating a new application in the launcher

**Comment by invincibleJai** [comment] 2018-05-25 04:17
I confirm issue is there, it's bit tricky. Thanks @ldimaggi @joshuawilson 

Steps:
* Go to cognito
* Login to https://openshift.io
* Create a new space
* Attempt to create a new app/quickstart
* Observe that after entering the quickstart name and clicking 'Continue' - the new app launcher exits
* it'll work if you try after that 

for first time i see below in screen, than click 'Continue' - the new app launcher exits

<img width="1671" alt="screen shot 2018-05-25 at 9 21 10 am" src="https://user-images.githubusercontent.com/5129024/40525876-946ccf76-6000-11e8-9f4d-9d2f24890789.png">

**Comment by jyasveer** [comment] 2018-05-25 05:18
Anyway this was intermittent. Now i think i have fixed it permanently

**Comment by jyasveer** [comment] 2018-05-25 05:48
@ldimaggi @joshuawilson  can you please verify and close this ?

**Comment by jyasveer** [comment] 2018-05-25 07:10
@ldimaggi @joshuawilson fix is in prod-preview now. can you please verify ?

**Comment by ldimaggi** [comment] 2018-05-25 11:05
Just tried on prod-preview - seeing these results:
* Log on to https://prod-preview.openshift.io
* Create a new space
* Observe this syntax error displayed while creating the space:
![screenshot from 2018-05-25 07-00-33](https://user-images.githubusercontent.com/642621/40541422-b5b1a2ea-5fe9-11e8-9c3f-bf80c3c2a4e0.png)
* Attempt to create a new app - observe that after pressing 'continue' the user is returned to the space home/dashboard page
* Create another new space - observe the syntax error displayed previously is not displayed
* Attempt to create a new app - observe that the app launcher is now able to create a new app

**Comment by ldimaggi** [comment] 2018-05-25 14:29
It;s fixed in production. Thx!

**Closed** 2018-05-25 14:29 UTC
Labels: SEV1-urgent, area/launcher, status/completed, team/launcher, type/bug

**Comment by ldimaggi** [comment] 2018-05-29 15:04
This problem is not being seen on prod-preview.

**Comment by ldimaggi** [comment] 2018-05-29 18:52
Steps to recreate:
* Login to https://openshift.io
* Create a new space
* Attempt to create a new app/quickstart
* Observe that after entering the quickstart name and clicking 'Continue' - the new app launcher exits

**Comment by jyasveer** [comment] 2018-05-30 10:48
@joshuawilson can you please confirm if this https://github.com/fabric8-ui/fabric8-ui/pull/2945 is in prod now ?
@ldimaggi the above PR changes should move to prod to solve this issue.

**Comment by ldimaggi** [comment] 2018-05-30 11:46
The fix is not yet in production - it is still failing.

**Comment by joshuawilson** [comment] 2018-05-30 13:30
This is now in Prod, please try again.
