### ISSUE TITLE
Jenkins excessive CPU usage

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#3442] opened 2018-05-03 18:16 UTC
It looks like jenkins often uses 50% of a cpu core (up to 1 full cpu core) from startup up to when the pod is idled/scaled down.

This has been observed across multiple tenants namespaces and jenkins deployments.

Could there be a bad plugin consuming a lot of CPU for some reason?

I've sampled logs from a couple of jenkins pods which were showing high CPU utilization and I did not notice any repeated logs or errors that may indicate a bad state looping or something similar. The logs looked normal.

Here we see a single tenant spinning up his jenkins pod every 10 minutes or so. We can see jenkins using ~50% of CPU for about 10 minutes before it is shutdown/idled.
![jenkins3](https://user-images.githubusercontent.com/3001/39594937-0a10f076-4edc-11e8-9ffd-0e616034a39d.png)

Here each color represent a different tenant jenkins starting up and eventually shutting down (idled or else). The "bumps" span about 10-15 minutes on average. The biggest one spans about 1 hour where it's using 1 full cpu core.
![jenkins2](https://user-images.githubusercontent.com/3001/39594949-123fa2f6-4edc-11e8-9569-ae45513420de.png)

**Comment by jfchevrette** [comment] 2018-05-03 18:17
Raising this as a SEV-2. If this is widespread across all jenkins this will affect our ability to scale and may cause cluster performance issues.

**Comment by jfchevrette** [comment] 2018-05-03 19:52
Bumped to SEV1 because we can't meet the scale goals and concurrency expectations if jenkins is using so much CPU for log periods of time. This may even be the reason why we're seeing a lot of slowdowns in jenkins & builds lately.

**Comment by maxandersen** [comment] 2018-05-03 21:27
trying to reproduce it and use jstack to locate the problematic code.

**Comment by maxandersen** [comment] 2018-05-03 22:48
I haven't been able to catch the issue yet but if anyone does see high cpu usage then please do this within your jenkins namespace:

` oc rsh dc/jenkins jstack 1` a few times (with 5-10 s) between and attach the output here.

then we should be able to spot where the "hotspot" is.

**Comment by pradeepto** [comment] 2018-05-04 06:58
@maxandersen @jfchevrette 

![jenkins-monitoring-osio](https://user-images.githubusercontent.com/59771/39615947-8b6f8186-4f96-11e8-92e3-95d4ce8a4d3e.png)

The logs that go with this nice picture.

[jstack01.txt](https://github.com/openshiftio/openshift.io/files/1973473/jstack01.txt)
[jstack02.txt](https://github.com/openshiftio/openshift.io/files/1973474/jstack02.txt)
[jstack03.txt](https://github.com/openshiftio/openshift.io/files/1973475/jstack03.txt)
[jstack04.txt](https://github.com/openshiftio/openshift.io/files/1973476/jstack04.txt)
[jstack05.txt](https://github.com/openshiftio/openshift.io/files/1973477/jstack05.txt)
[jstack06.txt](https://github.com/openshiftio/openshift.io/files/1973478/jstack06.txt)
[jstack07.txt](https://github.com/openshiftio/openshift.io/files/1973479/jstack07.txt)
[jstack08.txt](https://github.com/openshiftio/openshift.io/files/1973480/jstack08.txt)
[jstack09.txt](https://github.com/openshiftio/openshift.io/files/1973481/jstack09.txt)
[jstack10.txt](https://github.com/openshiftio/openshift.io/files/1973482/jstack10.txt)
[jstack11.txt](https://github.com/openshiftio/openshift.io/files/1973483/jstack11.txt)
[jstack12.txt](https://github.com/openshiftio/openshift.io/files/1973484/jstack12.txt)

**Comment by maxandersen** [comment] 2018-05-04 11:32
thanks @pradeepto - with only the jstack dumps i can just see there is activtiy and where ; but not how much. having the matching ps dumps would be really useful

**Comment by mmclanerh** [comment] 2018-05-10 21:05
can we get an update on this sev-1?  thanks.

**Comment by lordofthejars** [comment] 2018-05-14 15:50
Ok after trying several things, it has happened to me the described behavior. Still not sure if it is reproducible or not, but I have tried next thing (which is somehow slow).

1) Unidle Jenkins, create a new project and run the build.
2) Wait until you need to push if Promote or Abort the build. Just wait there for one day (until the build expires)
3) After this day and having Jenkins idled, try to unidle.
4) After that I noticed that even I have not pushed anything the CPU was at 1 all the time, even after the unidle process.
5) Push promote button (build fail because it has expired that's ok9
6) After 30 sec or so the CPU usage drops to 0.0X

I don't know if this is reproducible or not but tomorrow I will be able to do another try.

**Comment by pbergene** [comment] 2018-05-15 12:51
It doesn't look like it's hitting us very widely, I am removing the Sev-1 and will re-escalate if it becomes common and causing serious resource contention.

**Comment by lordofthejars** [comment] 2018-05-15 13:35
ok, thanks :)

**Comment by joshuawilson** [comment] 2018-05-16 12:53
Is this still a P0? If so, who is working on it?

**Comment by krishnapaparaju** [comment] 2018-05-29 12:21
Could not reproduce. Removing P0 label. @lordofthejars can you please close this if not reproducible ?

**Comment by lordofthejars** [comment] 2018-05-30 07:56
I couldn't reproduce it. In my case, it happened one time, but then doing the same process didn't reproduce it, and tried multiple times but no luck. So it happens but no idea in which circumstance.

**Comment by krishnapaparaju** [comment] 2018-06-19 12:39
closing as its not reproducible..

**Closed by krishnapaparaju** 2018-06-19 12:39 UTC
Labels: SEV2-high, area/architecture/performance, team/build-cd, type/bug

**Comment by hrishin** [comment] 2018-08-07 05:11
@jfchevrette may be this was related issue  #https://github.com/openshiftio/openshift.io/issues/3956 and fix is in production.
