### ISSUE TITLE
In Planner child workitem shows link - parent workitem does not

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3810] opened 2018-06-15 18:43 UTC
In the Planner:
* I created a parent workitem - https://openshift.io/openshiftio/openshiftio/plan/detail/2504
* Over the past few weeks, this parent workitem acquired 2 child workitems - both of these workitems are correctly displayed in the links
* On June 15, I created a new workitem - https://openshift.io/openshiftio/openshiftio/plan/detail/2616 and linked it as a child to the parent workitem
* The linked child workitem correctly shows the link to its parent.
* The parent displays the correct total number of links (4) - but does not show https://openshift.io/openshiftio/openshiftio/plan/detail/2616 among the linked child workitems

The parent workitem:
![screenshot from 2018-06-15 12-17-42](https://user-images.githubusercontent.com/642621/41484266-27e8548c-70aa-11e8-85e6-ec0ecb55d81a.png)

And the new linked child workitem:
![screenshot from 2018-06-15 12-19-18](https://user-images.githubusercontent.com/642621/41484338-7429c13c-70aa-11e8-82e1-c4307191cef5.png)

**Comment by stevengutz** [comment] 2018-06-18 10:18
First I think this is a SEV3 rather than SEV2.

However when I look at the parent: https://openshift.io/openshiftio/openshiftio/plan/detail/2504 Is the child work item you recreate listed there.  Perhaps there is just latency that delays it appearing in the parent's link.  In fact, even in your screen cap for the parent's link I see the work 2616.

I don't think there's a bug here.

**Comment by ldimaggi** [comment] 2018-06-18 19:48
In this case - the lack of the link to the 4th work item is persistent. Is this evidence of some DB corruption?

**Comment by nimishamukherjee** [comment] 2018-06-19 06:29
@ldimaggi I see all the three child links including https://openshift.io/openshiftio/openshiftio/plan/detail/2616
![alllinks](https://user-images.githubusercontent.com/1892722/41580336-2f5e1740-73b8-11e8-8ebf-1acdd998734a.png)

**Comment by nimishamukherjee** [comment] 2018-06-19 06:34
I also tried the steps mentioned by you and could not reproduce the issue.

**Comment by nimishamukherjee** [comment] 2018-06-19 06:34
@rgarg1 can you reproduce this issue?

**Comment by nimishamukherjee** [comment] 2018-11-19 16:23
Closing this issue as it cannot be reproduced.

**Closed by nimishamukherjee** 2018-11-19 16:23 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
