### ISSUE TITLE
when clicking cancel on labels (and possible others) the workitem is updated

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2969] opened 2018-04-10 07:05 UTC
when I open labels and my edits result in zero changes (i.e. just click cancel) the workitem seem to still be updated. 

It should not as it is slow and the database will list and notify about changes even though nothing changed.

**Comment by joshuawilson** [comment] 2018-04-10 20:59
I noticed this in other fields too.

**Comment by debloper** [comment] 2018-04-11 12:17
Duplicate of #2736

**Comment by catrobson** [comment] 2018-08-06 00:12
Should this be closed @debloper since it is a duplicate?

**Comment by debloper** [comment] 2018-08-11 23:41
@catrobson ideally GitHub will close this automatically once the duplicate has been resolved, but feel free to do so if you think it's necessary.

**Comment by nimishamukherjee** [comment] 2018-11-21 05:18
#2736 fixes this issue.

**Closed by nimishamukherjee** 2018-11-21 05:18 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
