### ISSUE TITLE
Cannot add application in local f8-ui instance

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3779] opened 2018-06-13 13:46 UTC
When adding an application in a local f8-ui instance via `$ npm start`, the 'Select Dependencies' process is blocked due to:

```
Failed to load http://recommender.api.localhost:3000/api/v1/stack-analyses: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
09:41:59.128 
```

![add-application](https://user-images.githubusercontent.com/5430520/41355045-8bbe4a06-6eee-11e8-88e3-cddb6896e5ff.png)

Edit: And the widgets? stay in the loading state forever, as seen in the image above.

**Comment by arunkumars08** [comment] 2018-07-02 04:49
@jiekang The reason is you need to set environment variables for them to be accessed in local. https://github.com/fabric8-ui/fabric8-ui/blob/master/config/webpack.dev.js#L43-L44
I will ping you the values you have to set in direct chat.

**Comment by arunkumars08** [comment] 2018-07-04 04:19
Closing this as it is not a bug.

**Closed by arunkumars08** 2018-07-04 04:19 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, team/analytics, team/analytics/wizard, type/bug

**Comment by jiekang** [comment] 2018-07-04 12:36
@arunkumars08 The repository contains scripts to set the required environment variables for various environments [1], for example to target openshift.io (production) [2]

[1] https://github.com/fabric8-ui/fabric8-ui/tree/master/environments
[2] https://github.com/fabric8-ui/fabric8-ui/blob/master/environments/openshift-prod-cluster.sh

Can the proper defaults be added to at least production and prod-preview scripts?
