### ISSUE TITLE
Cannot find Task Working Item after creating it using 'Add Working Item' form

### ISSUE THREAD

**Issue by dgolovin** [openshiftio/openshift.io#2638] opened 2018-03-15 22:49 UTC
It seems Task working item can be seen only if it created as a child working item. In scenario below I can create it when I select Iteration on Plan/Backlog page:

![image](https://user-images.githubusercontent.com/620330/37494871-ec134e4c-2867-11e8-8832-0fcd66c2ed1f.png)

Then it appears on the page after add button pressed

![image](https://user-images.githubusercontent.com/620330/37494894-073a86fe-2868-11e8-8232-5edc9280a338.png)

Then I cannot find it anywhere:

![image](https://user-images.githubusercontent.com/620330/37494925-25ef62e0-2868-11e8-91f0-9663780c7112.png)

Even if I get back to iteration where it was created

![image](https://user-images.githubusercontent.com/620330/37494974-61733ca6-2868-11e8-88b4-2f339163cbc2.png)

**Comment by michaelkleinhenz** [comment] 2018-03-23 09:56
Found the cause for this: the new Task is not created with iteration set to the iteration context. Example: the user goes to "Root Iteration/Iteration 1" and creates a Task. The new Task will be set "Root Iteration" as the iteration value (expected would be "Root Iteration/Iteration 1"). 

The result is that the Task will not show up in the execution level (iteration view). 

We need to set the iteration correctly here as new Tasks not created with an iteration value AND are not parented are "lost" and can not be retrieved with the current navigation setup.

@nimishamukherjee @vikram-raj @sanbornsen

**Comment by michaelkleinhenz** [comment] 2018-03-23 10:26
Update: this has been fixed with the ngrx/store update currently in the pipeline for deployment to prod.

**Comment by nimishamukherjee** [comment] 2018-04-03 06:17
@sanbornsen can you confirm if this has been fixed on prod.

**Comment by nimishamukherjee** [comment] 2018-04-05 06:48
@dgolovin please verify on production. This has been fixed.
Note: Tasks are available only under iterations.
If a feature has a task, then the task will be displayed as a child of the feature under requirements.

**Comment by nimishamukherjee** [comment] 2018-04-13 07:36
Fix is in prod.

**Closed by nimishamukherjee** 2018-04-13 07:36 UTC
Labels: SEV2-high, area/planner, team/planner, type/bug, verified-fix-in-prod
