### ISSUE TITLE
Direct Bug Reporting Form for OSIO (and other Spaces) for anonymous users

### ISSUE THREAD

**Issue by luebken** [openshiftio/openshift.io#235] opened 2017-06-16 06:45 UTC
How to redo: Go to https://openshift.io/_error and click the"I'm felling helpful, let's report the issue" button. No errors in the console.
![screen shot 2017-06-16 at 08 45 09](https://user-images.githubusercontent.com/53055/27215115-1d1adbbe-5270-11e7-9f68-4e4b0c0af50d.png)

**Comment by joshuawilson** [comment] 2017-06-16 15:41
This issue was moved to fabric8io/fabric8-ui#1531

**Comment by michaelkleinhenz** [comment] 2017-09-20 11:13
Not a Planner issue imo.

**Comment by joshuawilson** [comment] 2017-09-21 03:06
@michaelkleinhenz There is a button on the Error page that links to the Planner to file an issue. If this is not a Planner task/issue, who does it belong to?

**Comment by michaelkleinhenz** [comment] 2017-09-21 08:28
Then this should be a story that describes the req's for this feature, not a bug report. And: the link is not even there anymore.

**Comment by joshuawilson** [comment] 2017-09-21 13:09
@michaelkleinhenz I'll leave it to you to change it or reference a user-story.

**Comment by nimishamukherjee** [comment] 2018-11-19 16:43
Closing this issue as the "Report issue" button is no longer available.

**Closed by nimishamukherjee** 2018-11-19 16:43 UTC
Labels: area/UX, level/intermediate, status/analyzing, team/ux, type/user-story
