### ISSUE TITLE
Unable to create a quickstart application on prod-preview.openshift.io

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#1634] opened 2017-12-12 08:18 UTC
* Create a space
* Add a quickstart project to the codebase. At the first step when the quickstart wizard launches I see the following error
`HTTP 500 Internal Server Error`

![screenshot from 2017-12-12 13-36-48](https://user-images.githubusercontent.com/7047079/33873964-07424768-df43-11e7-84a0-0520f3644b27.png)

**Comment by sara-02** [comment] 2017-12-12 08:18
Adding a codebase via Github import worked.

**Comment by sbose78** [comment] 2017-12-12 08:25
```
2017-12-12 08:16:04,028 SEVERE [org.obsidiantoaster.generator.rest.ObsidianResource] (default task-43) Error while moving to the next wizard step: java.lang.IllegalStateException: Error while moving to the next wizard step
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:107)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.canExecute(WizardCommandControllerImpl.java:319)
  | at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.canExecute(NoUIWizardControllerDecorator.java:236)
  | at sun.reflect.GeneratedMethodAccessor346.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
  | at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_b402caaf-a3b7-4fb5-a5ba-0b5b92c593a4.canExecute(CommandController_$$_javassist_b402caaf-a3b7-4fb5-a5ba-0b5b92c593a4.java)
  | at org.jboss.forge.service.util.UICommandHelper.describeCurrentState(UICommandHelper.java:84)
  | at org.jboss.forge.service.util.UICommandHelper.describeController(UICommandHelper.java:76)
  | at org.obsidiantoaster.generator.rest.ObsidianResource.getCommandInfo(ObsidianResource.java:236)
  | at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.getCommandInfo(Unknown Source)
  | at sun.reflect.GeneratedMethodAccessor359.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
  | at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  | at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
  | at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  | at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  | at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
  | at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
  | at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
  | at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
  | at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
  | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
  | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
  | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:209)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:473)
  | at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:165)
  | at io.fabric8.forge.generator.tenant.Tenants.loadTenant(Tenants.java:47)
  | at io.fabric8.forge.generator.tenant.Tenants.loadNamespaces(Tenants.java:56)
  | at io.fabric8.forge.generator.github.GitHubImportPickRepositoriesStep.lambda$initializeUI$0(GitHubImportPickRepositoriesStep.java:67)
  | at org.infinispan.cache.impl.TypeConverterDelegatingAdvancedCache.lambda$convertFunction$1(TypeConverterDelegatingAdvancedCache.java:101)
  | at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
  | at org.infinispan.cache.impl.AbstractDelegatingCache.computeIfAbsent(AbstractDelegatingCache.java:343)
  | at org.infinispan.cache.impl.TypeConverterDelegatingAdvancedCache.computeIfAbsent(TypeConverterDelegatingAdvancedCache.java:157)
  | at io.fabric8.forge.generator.github.GitHubImportPickRepositoriesStep.initializeUI(GitHubImportPickRepositoriesStep.java:67)
  | at sun.reflect.GeneratedMethodAccessor399.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
  | at io.fabric8.forge.generator.github.GitHubImportPickRepositoriesStep_$$_javassist_f563a0b9-ea6d-4e84-89d8-6e33c4745d68.initializeUI(GitHubImportPickRepositoriesStep_$$_javassist_f563a0b9-ea6d-4e84-89d8-6e33c4745d68.java)
  | at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.initialize(WizardCommandControllerImpl.java:121)
  | at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
  | ... 64 more
  |  
```

**Comment by sbose78** [comment] 2017-12-12 08:25
@corinnekrych @arunkumars08 any clue how to proceed with this? :)

**Comment by arunkumars08** [comment] 2017-12-12 09:01
@sara-02 I just tried creating a quick start project in prod-preview, and I was able to complete the flow. Could you logout, login and try again?

**Comment by sara-02** [comment] 2017-12-12 09:04
@arunkumars08 Tried that as well, still the same error.

**Comment by sara-02** [comment] 2017-12-12 09:21
On the URL : `https://console.free-int.openshift.com/console/` I got the following error `You do not have access to OpenShift Online`, when I click on `Login wih Keyclock`. Upon Signup I end up with the following screen
![screenshot from 2017-12-12 14-45-30](https://user-images.githubusercontent.com/7047079/33876532-d6833462-df4b-11e7-9fec-afea8786af46.png)

**Comment by sara-02** [comment] 2017-12-12 09:23
Upon logging in again at `https://console.free-int.openshift.com/console/` I am directed to `https://manage.stg.openshift.com/`. When I click on `Open Web Console` I am redirected to `https://api.free-stg.openshift.com/` which on clicking `Login With Keycloak`automatically logs me this page `https://console.free-stg.openshift.com/console/`
![screenshot from 2017-12-12 14-53-28](https://user-images.githubusercontent.com/7047079/33876700-3a2b1ade-df4c-11e7-987f-81c07b81b5c7.png)

**Comment by pbergene** [comment] 2017-12-12 09:38
Following up on this.  Just to be sure, have you tried https://sso.prod-preview.openshift.io/auth/realms/fabric8/account/identity and relinking openshift? - not entirely confident that it's not a regression, but worth a try :)

**Comment by sara-02** [comment] 2017-12-12 09:54
@pbergene  tried that as well.

**Comment by sbose78** [comment] 2017-12-12 17:03
OpenShift Online team has acknowledged the issue - and they are working on a PR to resolve this.

CC: @alexeykazakov .

**Comment by sara-02** [comment] 2017-12-13 15:09
@alexeykazakov I am still am redirected from the `api.free-int.openshift.com` to `manage.stg.openshift.com` while trying to connect my OS account to OSIO.

**Comment by sara-02** [comment] 2017-12-13 15:10
![screenshot from 2017-12-13 20-39-38](https://user-images.githubusercontent.com/7047079/33945702-c1d81f1e-e045-11e7-81b3-82f4a7fc1e69.png)
![screenshot from 2017-12-13 20-39-29](https://user-images.githubusercontent.com/7047079/33945703-c21f523a-e045-11e7-8077-6f41a7a7c7b0.png)

**Comment by alexeykazakov** [comment] 2017-12-13 18:22
We just have switched to free-stg (from free-int) again. So, OSO login should work now.

**Comment by joshuawilson** [comment] 2017-12-21 16:16
What is the status on this?

**Comment by gastaldi** [comment] 2018-01-10 14:16
Closing as we believe this was caused by the cluster instabilities. Reopen if the problem persists

**Closed by gastaldi** 2018-01-10 14:16 UTC
Labels: SEV2-high, area/app-wizard, area/quickstarts, team/analytics/wizard, team/launcher, team/platform, team/service-delivery, type/bug
