### ISSUE TITLE
New launcher not rendered correctly in Firefox 

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3273] opened 2018-04-24 08:20 UTC
1. open space dashboard in Firefox 59
2. click "Create an Application"
3. click "Try our new Getting Started experience"
4. choose some name and click "Create a new codebase", click Continue

result:
* page is not rendered correctly
* 

![osio_new_launcher](https://user-images.githubusercontent.com/445100/39174799-f4396d44-47a8-11e8-9c74-0eb4426f3134.png)

**Comment by invincibleJai** [comment] 2018-04-25 09:30
@ppitonak this is duplicate of https://github.com/openshiftio/openshift.io/issues/2944, can we close it.

am not sure if Firefox is a priority for the summit. 
CC @GeorgeActon

**Comment by joshuawilson** [comment] 2018-04-26 02:02
It is supposed to run on the latest 2 versions of all browsers. If you have compatibility issues you can check with @mindreeper2420. He has been helping in this area.

**Comment by animuk** [comment] 2018-04-26 05:59
@jyasveer Please reach out to https://github.com/openshiftio/openshift.io/issues/2944 for this.It may help you. closing this as this is duplicate.

**Closed by animuk** 2018-04-26 05:59 UTC
Labels: SEV2-high, area/browser-compatibility, area/launcher, team/analytics, team/analytics/wizard, type/bug
