### ISSUE TITLE
Stuck with "Migrating workspaces to the new version of Che..."

### ISSUE THREAD

**Issue by InfoSec812** [openshiftio/openshift.io#3232] opened 2018-04-21 13:07 UTC
My old (~2 mos) and new projects in OSIO are stuck, unable to open a workspace. I only see a message as indicated in the title of this issue. Screenshot attached.
![bug report - screenshot_2018-04-21_08-59-41](https://user-images.githubusercontent.com/99691/39084410-6cbe9dce-4543-11e8-987d-8d480e9aeac6.png)

**Comment by ibuziuk** [comment] 2018-04-23 07:49
@riuvshin the user `rhn-gps-josphill` is listed in `Che 6 Migration Errors` doc, with description - `Timeout while waiting for container creation or command execution` - recommended action `Rerun the migration`.
Not sure this would help though since migration via codebase is also failing. 

@InfoSec812 could you please provide openshift events from your *-che namespace ?

**Comment by InfoSec812** [comment] 2018-04-23 11:55
It shows "No Events"

**Comment by InfoSec812** [comment] 2018-04-23 11:57
Ooooh... I just switched over to my Jenkins Project in the OpenShift console and I see that Jenkins failed to deploy. Unfortunately, the logs are no longer available.

**Comment by ibuziuk** [comment] 2018-04-23 11:59
@InfoSec812 could you please navigate to codebase UI again, wait till migration spinner would appear and than go back to *-che namespaces and see what happens in namespace (maybe there would be some new events) ?

**Comment by InfoSec812** [comment] 2018-04-23 12:01
And of course, it's not happening now... :(

**Comment by ibuziuk** [comment] 2018-04-23 12:04
> Ooooh... I just switched over to my Jenkins Project in the OpenShift console and I see that Jenkins failed to deploy. Unfortunately, the logs are no longer available.
Sorry, not following how jenkins is related to this problem ? have you deployed smth. to your che namespace manually ?

**Comment by InfoSec812** [comment] 2018-04-23 12:10
Now, instead of getting the "Migrating" message, Che just fails to start with errors about mounting volumes. See attach screenshot.

![bug report - che fails to start - 2018-04-23](https://user-images.githubusercontent.com/99691/39125669-c4eb17bc-46cd-11e8-84f3-78470e40db14.png)

**Comment by InfoSec812** [comment] 2018-04-23 12:14
@ibuziuk I'm not sure Jenkins has ANYTHING to do with the problem reported. I was just providing as much detail as possible of what I am seeing.

**Comment by InfoSec812** [comment] 2018-04-23 12:43
@ibuziuk I see a single bound PVC:


claim-che-workspace | Bound to volume 7aaf13b6-5b17-463a-a83b-9af2efde7b19-00-14 | 1 GiB | RWO (Read-Write-Once) | 20 days
-- | -- | -- | -- | --

**Comment by ibuziuk** [comment] 2018-04-23 12:49
@InfoSec812 all looks correct, just for some reason "Failed Mount" is keep happening...

@riuvshin  do you happen to know if prod oso clusters have already switched to Gluster storage backend

**Comment by riuvshin** [comment] 2018-04-24 15:26
@ibuziuk ` us-east-2a, 1a, 1b = gluster.  us-east-2 (the original) = ebs.  `

**Comment by ibuziuk** [comment] 2018-04-24 16:10
Thanks for the info, @l0rd I believe we need to come up with a clear plan of how we are going to proceed with `Che 6 Migration Errors`

**Comment by l0rd** [comment] 2018-04-24 16:27
@ibuziuk looks like @InfoSec812 account is provisioned on cluster 2a that uses gluster.

**Comment by ibuziuk** [comment] 2018-04-24 16:32
yeah, I see a ref to `starter-us-east-2a`, so we can not blame ebs here

**Comment by l0rd** [comment] 2018-04-25 11:04
Related to https://github.com/openshiftio/openshift.io/issues/2154. @jfchevrette @riuvshin it looks like we have some `Timeout expired waiting for volumes to attach/mount to pod` on cluster `starter-us-east-2a` too. Were you aware of that?

**Comment by jfchevrette** [comment] 2018-04-25 12:46
@l0rd I was not. I'm investigating this now.

**Comment by jfchevrette** [comment] 2018-04-25 12:54
When I opened the "Create" tab and it began migrating my che workspace the migration pod failed and I saw the following event:

```
 	Error: cannot create directory /var/lib/origin/openshift.local.volumes/pods/1f43f0fe-4887-11e8-8539-02074d91bc8a/volumes/rht~glfs-subvol/60e14bb9-4116-4295-a6a1-7024c82669ce-02-c9/benchapp4-yrgmd: disk quota exceeded
```

**Comment by jfchevrette** [comment] 2018-04-25 12:58
I've gathered more data and engaging with the storage team to troubleshoot this

**Comment by jfchevrette** [comment] 2018-04-25 13:04
My account is stuck at attempting to migrate my che workspace. As such I am unable to create/open a workspace at all. I believe we have seen this on a few accounts now. Should we bump this to SEV-1?

**Comment by l0rd** [comment] 2018-04-25 13:29
@jfchevrette yours is a different issue (your disk space is full). There may be many reasons why a user fill his 1GB PV but in your case I suspect that's related to https://github.com/openshiftio/openshift.io/issues/1614. I don't think it's a SEV1 but should be a P0.

**Comment by jfchevrette** [comment] 2018-04-25 20:05
I wonder if this may be a case of trying to start a 2nd workspace while another workspace pod (or the migration pod) has the PV attached?

**Comment by ibuziuk** [comment] 2018-05-01 13:06
@riuvshin could you please help @jfchevrette to reproduce this migration failure for user `rhn-gps-josphill` ?

**Comment by ibuziuk** [comment] 2018-05-02 11:01
@slemeur @qodfathr @bmicklea assuming that this PV mounting problem during che 5 -> che 6 migration only affects insufficient % of  user base and does not affect new users could we remove `P0` label ?

**Comment by ibuziuk** [comment] 2018-05-02 14:55
@bmicklea it was a question indeed, but I got some clarifications from your last comment ;-)

> if it only applies to Che 5 or Che 6 single tenant
Correct the issue is only about workspace migration failure from che v5 to v6 (both multi-tenant )

> remove the P0 label of it applies to current Che implementation but affects less than 10% of users.

In terms of figures there are 9 users a part from `rhn-gps-josphill` for whom the migration from che 5 to che 6 also failed with the same error message so it is less than 1 % userbase - removing  P0 label

**Comment by mmclanerh** [comment] 2018-06-25 21:04
@InfoSec812 is this still an issue or can this be closed?

**Comment by slemeur** [comment] 2018-06-27 17:00
We can close this issue as the migration has been handled now.

**Closed by slemeur** 2018-06-27 17:00 UTC
Labels: SEV2-high, area/che, area/codebases, team/che/osio, team/service-delivery, type/bug
