### ISSUE TITLE
User is not able to navigate to linked workitems from Planner workitem 'full details' view

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3624] opened 2018-05-23 14:53 UTC
Steps to recreate:
* Create a workitem and link it to other workitems
* Observe that from the summary view, the user can navigate to the linked workitems:
![screenshot from 2018-05-23 10-42-06](https://user-images.githubusercontent.com/642621/40432265-47fde24a-5e77-11e8-83b9-b9b3062ae93a.png)

* Observe that from the detailed view, the user cannot navigate to the linked workitems - clicking on the linked workitems has no effect - no errors are raised in the OSIO UI or the browser console:
![screenshot from 2018-05-23 10-35-34](https://user-images.githubusercontent.com/642621/40432334-70f1a308-5e77-11e8-9f73-8c7a0bef5607.png)

**Comment by nimishamukherjee** [comment] 2018-05-28 03:31
Closing as duplicate of #3620

**Closed** 2018-05-28 03:31 UTC
Labels: SEV2-high, area/planner, team/planner, type/bug
