### ISSUE TITLE
Stack analyses report insights are blank for some stacks

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4178] opened 2018-08-16 10:23 UTC
##### Issue Overview

If stack analysis is triggered on a Maven repository through the IDE extension where the number of pom.xml files is greater than 3, because of possibly Kronos response taking too long, the recommendations are "null" for a long time and so nothing shows up in the UI.

##### Expected Behaviour

To be discussed, should we handle all multi-pom cases through hpf-insights model instead of Kronos, show a spinner while Kronos result loads, or something else entirely?

##### Current Behaviour

Insights card is blank for about a minute before they load.

##### Steps To Reproduce

1. Download and install the IDE extensions
2. Trigger stack analysis on any vertx/springboot/wildfly repository containing 3 or more than 3 pom.xml files repository like the launcher-backend.

/cc @samuzzal-choudhury @miteshvp

**Comment by samuzzal-choudhury** [comment] 2018-08-30 12:26
The root cause was found to be related to the unexpected cooccurrance_probability associated with the recommended companion component which looks something like the one follows -
```
        "companion_packages": [
            {
                "cooccurrence_probability": NaN,
                "package_name": "io.fabric8.funktion.connector:connector-smpp",
                "topic_list": []
            },
```

This in turn, causes the RDS operation to insert the recommendation into the database table `worker_results` to fail. 
```
DataError('(psycopg2.DataError) invalid input syntax for type json\nLINE 1: ..., NULL, \'880de4e7bd7d41e4b08d8864dc5dadb2\', NULL, \'{"_audit"...\n                                                             ^\nDETAIL:  Token "NaN" is invalid.\nCONTEXT:  JSON data, line 1: ...rrence_count": 0, "cooccurrence_probability": NaN...\n',)
```
Because of this exception, no recommendation data could be fetched for the stack during the `stack-analyses [GET]`.

**Comment by samuzzal-choudhury** [comment] 2018-08-30 12:33
@rootAvish can you please investigate and propose a fix on hpf-insights why a `cooccurrence_probability` value for `NaN` is returned?

In the meanwhile, additionally, I will handle this on the server-backbone side by replacing `NaN` with `100.0` so that the database operation never fails.

cc: @miteshvp

**Comment by rootAvish** [comment] 2018-08-30 12:59
@samuzzal-choudhury The NaN values are due to the way the current fold-in logic is implemented. If we don't recommend it as a companion, I double we would be able to recommend companions at all in most cases. I would vote to keep it as-is and show the recommendations with the "99.999%" confidence score (which these companions turn into) before I pick up the ticket item of the fold-in logic re-implementation next week.

**Comment by rootAvish** [comment] 2018-08-30 12:59
Is that what's causing this issue?

**Comment by samuzzal-choudhury** [comment] 2018-08-30 13:47
@rootAvish as mentioned, cooccurrence_probability is breaking the RDS insert step for recommendations. I am currently preventing those companion components from appearing in the recommendations with a log message and making sure that the DB insert goes on successfully.

**Comment by miteshvp** [comment] 2018-08-30 13:51
@samuzzal-choudhury - rather than filtering out those dependencies altogether, assign a value of `1.0` where we get `NaN` value. Because all of those requests served from hpf will give value `NaN`.

**Comment by rootAvish** [comment] 2018-08-31 06:11
@samuzzal-choudhury Sorry, did not read the earlier comment. Yes, I think it's best to proceed with the approach suggested by @miteshvp momentarily till the fold-in is fixed.

**Comment by samuzzal-choudhury** [comment] 2018-08-31 19:55
It was found that the issue mentioned here are caused by:
1. hpf insights recommendation engine: When that returns a list of companion components with cooccurrence probability `NaN`. This has been fixed on server backbone in the PR fabric8-analytics/f8a-server-backbone#100.
2. A bug in the f8a-server-backbone code when that calls the kronos-maven insights engine for multiple manifests with a cumulative list of dependency packages from the previous pom.xml that at one point becomes too big to be handled within the configured timeout for the server and hence no recommendations are displayed.

**Comment by samuzzal-choudhury** [comment] 2018-09-03 17:07
This issue has been fixed and the changes are in production. Hence, closing this. Please reopen if found otherwise.

**Closed by samuzzal-choudhury** 2018-09-03 17:07 UTC
Labels: SEV3-medium, area/analytics, priority/P2, status/in-progress, team/analytics, team/analytics/insights, team/analytics/integration, type/bug
