### ISSUE TITLE
Prod: cannot create an application

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3833] opened 2018-06-20 06:17 UTC
The E2E tests started to fail on prod-preview.

Steps:
1. Start Create a new space wizard and fill the values
2. Fill the values on Create an Application screen (Select create a new codebase) and press Continue 
3. Result: 404: You've found something, but not the page you're looking for.

The reason why I am reporting this on prod-preview is to prevent it from getting to the production

**Comment by piyush1594** [comment] 2018-06-20 06:22
@ljelinkova Please add labels.

**Comment by ljelinkova** [comment] 2018-06-20 06:51
@piyush1594 Sorry, I do not have permissions to do that.

**Comment by piyush1594** [comment] 2018-06-20 09:40
@ljelinkova I have added the labels which look relevant to me.  As this is in prod-preview, I have added SEV-2, but if it gets promoted to prod, then it's a potential SEV-1.

**Comment by piyush1594** [comment] 2018-06-20 09:45
Steps to reproduce 

1. Go to a `space` in `prod-preview`. Click `Create Application`. Enter all the details.

![create-1](https://user-images.githubusercontent.com/19270240/41650835-9326014a-749c-11e8-9ba5-7f40c2174162.png)

2. Now clicking on `Continue` will result to

![create-2](https://user-images.githubusercontent.com/19270240/41650874-b39c0b04-749c-11e8-820c-3d311f4738d5.png)

**Comment by ljelinkova** [comment] 2018-06-20 10:08
@piyush1594 Thanks

**Comment by arunkumars08** [comment] 2018-06-20 16:44
I think this PR https://github.com/fabric8-ui/fabric8-ui/pull/3019 from @edewit fixes this issue

**Comment by piyush1594** [comment] 2018-06-21 02:52
This is in PROD right now and you can not create an application.

**Comment by jmelis** [comment] 2018-06-21 06:18
https://github.com/openshiftio/saas-openshiftio/pull/941 was rolled back, so for the moment we are good in prod

**Comment by jmelis** [comment] 2018-06-21 06:44
removing SEV-1 label as the PR roll back restored the functionality back to normal

**Comment by pbergene** [comment] 2018-06-21 07:57
What part of the process is failing here?  How is an issue which breaks the happy path discovered in preview and then promoted to production?

**Comment by ppitonak** [comment] 2018-06-21 08:00
@arunkumars08 https://github.com/fabric8-ui/fabric8-ui/pull/3019 was merge but the issue is still reproducible in prod-preview

**Comment by ppitonak** [comment] 2018-06-21 08:11
@pbergene There are two Jenkins jobs for prod-preview running every hour, one tests happy path with released features, the second one tests beta features.
* https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/
* https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/

Both of them are failing, when you open Jenkins log, it's not very clear why the test failed but there is a link to artifacts.ci.centos.org containing screenshots and it's relatively easy identify this issue, e.g. [this one](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/235/03-01-afterEach.png).

The problem of our process is that promotion of a release/commit to production is done manually and nobody checks the status of above-listed Jenkins jobs before merging it.

**Comment by arunkumars08** [comment] 2018-06-21 10:47
@ppitonak Yes, I tried things with that PR in local yesterday. Things worked fine and still work fine. That gave me the confidence to say it will work in prod-preview as well. Also, without this PR things were failing in local yesterday as mentioned in the running issue.

Reasons could be:

1. Recently patternfly-ng was updated across fabric8-ui and the same had to be done in ngx-forge.
2. To address this, this is the PR https://github.com/fabric8-ui/fabric8-ui/pull/3043 raised by Dan.
3. After addressing the above point, things were working fine in local of ngx-forge and also in local of fabric8-ui with this PR - https://github.com/fabric8-ui/fabric8-ui/pull/3019 raised by Eric.
4. We still are figuring out the reasons for things not working in Prod-preview and I think Dan can help us a little here.
5. The main problem currently is we can see things working fine in local environments as seen by sourcing prod-preview and prod, the same happens fine even running prod build. Hence it is hard to reproduce the scenario.

cc: @invincibleJai @jyasveer @edewit @dlabrecq

**Comment by dlabrecq** [comment] 2018-06-21 13:11
I believe we need to update ngx-forge so it uses the same package version as fabric8-ui. The current ngx-forge version in fabric8-ui is 0.2.34, but the latest is 0.3.8.

**Comment by invincibleJai** [comment] 2018-06-21 13:13
@dlabrecq it's latest there https://github.com/fabric8-ui/fabric8-ui/blob/master/package.json#L144

**Comment by dlabrecq** [comment] 2018-06-21 13:32
Sorry, I didn't update my local workspace. After pulling the latest, I'm able to navigate through the app-launcher and create an application successfully.

**Comment by dlabrecq** [comment] 2018-06-21 14:08
Looking at the errors with prod-preview, it appears as if that does not have the latest ngx-forge package. Is that possible? I encountered the same errors until I updated that package locally.

**Comment by invincibleJai** [comment] 2018-06-21 14:24
@dlabrecq not sure , we tried with all possible ways we could i.e build:prod, docker build but no luck in reproducing it. :|

**Comment by dlabrecq** [comment] 2018-06-21 14:32
Wondering if it's an issue with package-lock?

**Comment by dlabrecq** [comment] 2018-06-21 16:06
I see that fabric8-ui is still using fabric8-planner v0.50.4, dated 6/20. That could be installing an older version of patternfly-ng? I'm thinking we should update fabric8-planner next.

**Comment by dlabrecq** [comment] 2018-06-21 21:49
FYI, I regenerated the package-lock for ngx-forge and fabric8-planner using the latest patternfly-ng. After planner has merged the PR, I'll update fabric8-ui.

**Comment by invincibleJai** [comment] 2018-06-22 09:18
Thanks @dlabrecq , let us know if any changes are needed in ngx-forge.

As this issue looks related to patternfly-ng version in fabric8-ui so unassigning myself and @jyasveer as we not looking actively into it.

**Closed** 2018-06-22 19:28 UTC
Labels: SEV2-high, area/app-wizard, area/applications, area/launcher, env/prod, team/analytics/wizard, team/launcher

**Comment by dlabrecq** [comment] 2018-06-22 20:11
Tested the latest prod-preview and I was able to create an application successfully.

**Comment by joshuawilson** [comment] 2018-06-23 02:28
nice work @dlabrecq :)
