### ISSUE TITLE
Stack report:  Not displaying  recommendations for companion components

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1450] opened 2017-11-23 05:07 UTC
Start with VertX/ConfigMap starter application, generate stack report, no additional, companion components been recommended. This is OK as the quick starter application got all the right, needed packages.

After this, remove a package from pom.xml (vertx-web-client) and this removed package (commonly used package in the vertx world) is not showing up as part of recommended companion components.

**Comment by miteshvp** [comment] 2017-11-29 05:22
@krishnapaparaju - this looks to be an expected behavior where-in a single component removal from a perfect stack-1 does not guarantee a companion recommendations since present stack-2 itself maybe a perfect stack. Closing this issue but please re-open if you think otherwise.

**Comment by krishnapaparaju** [comment] 2017-12-04 14:40
If a package been removed from a well-crafted quick start application, that package would need to be showing up as 'companion package'. For example: if a user manually adds packages to pom.xml and misses out a package (that is a critical part of that intent), that would need to be showing up in the list of companion packages...

**Comment by miteshvp** [comment] 2017-12-05 03:21
@krishnapaparaju - let's say we have two quick-start application with packages as below
```
1. {"A", "B", "C", "D"}
2. {"A", "B", "C"}
```
If you remove `D` from the first application-stack, the remaining packages still form a complete stack. Hence removal of any package from a stack is no guarantee that it will show as companion in the next iteration. cc @rootAvish . Hence, I feel this is an expected behavior in general, unless you have some specific application stack that makes you feel otherwise

**Comment by krishnapaparaju** [comment] 2017-12-05 03:56
Will include this at today's cabal..

**Comment by rootAvish** [comment] 2017-12-12 08:10
@sivaavkd Spill over to 142, part of #1471.

**Comment by rootAvish** [comment] 2018-01-08 09:08
Solved by https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/163.

**Closed by rootAvish** 2018-01-08 09:08 UTC
Labels: SEV2-high, team/analytics, team/analytics/insights, type/bug
