### ISSUE TITLE
User's profile pull down contains only logout option in the new launcher

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2820] opened 2018-03-28 20:07 UTC
Steps to recreate:
* Open the new launcher
* Observe the pull down menu that should contain the "profile" option - the only option in the pulldown is logout

![capture1](https://user-images.githubusercontent.com/642621/38053403-05fdb3e4-32a2-11e8-84f3-c4d938ddebab.PNG)

**Comment by invincibleJai** [comment] 2018-04-10 07:31
@catrobson @mindreeper2420 needed your inputs with this, header is different in case of Getting started experience compared to OSIO header as below 

<img width="1676" alt="screen shot 2018-04-10 at 12 58 35 pm" src="https://user-images.githubusercontent.com/5129024/38542256-093c8d42-3cbf-11e8-8cce-5a21324030dd.png">

As @ldimaggi  have pointed out "Profile" is not there in dropdown, even "Chat" is not there. Just wanted to be sure if is it by design or we need to bring in both Profile and Chat options here?

**Comment by invincibleJai** [comment] 2018-04-10 10:58
Thanks @mindreeper2420 for inputs. @ldimaggi can we close it?

**Comment by invincibleJai** [comment] 2018-04-13 08:15
Closing it, as it's the current way by design.

**Closed by invincibleJai** 2018-04-13 08:15 UTC
Labels: SEV3-medium, area/app-wizard, team/analytics, team/analytics/wizard, team/launcher, type/bug
