### ISSUE TITLE
Project tree loses selection

### ISSUE THREAD

**Issue by Swannie007** [openshiftio/openshift.io#1454] opened 2017-11-24 03:21 UTC
scl enable rh-maven33 'mvn compile vertx:run -f 'preview:http://vertx-5tll0myenn1er1jy-rhn-sa-jswanepo-che.8a09.starter-us-east-2.openshiftapps.com
Unable to parse command line options: Missing argument for option: f

**Comment by sbose78** [comment] 2017-11-24 06:18
@l0rd Could you have a look at this ?
Please feel free to update the triaging as necessary.

**Comment by eivantsov** [comment] 2017-11-24 07:05
The problem is with project selection in project tree. For some reason the IDE thinks that no project is selected. As a result, current.project.path macro is translated into nothing, hence `-f <null>`

**Comment by l0rd** [comment] 2017-11-24 08:46
@eivantsov is there an upstream issue about that?

**Comment by eivantsov** [comment] 2017-11-24 08:51
https://github.com/eclipse/che/issues/7143

**Comment by eivantsov** [comment] 2018-04-12 15:01
@mattd72 do you have any additional steps to reproduce? Like clicking on not clicking on project explorer space etc.

**Comment by mattd72** [comment] 2018-04-15 11:04
Just following the steps listed here: https://docs.google.com/document/d/1KDx05WAk5omKXi7OosRfDTMRDorOt1k6iJrozWWRKZ4/edit
Only one project in the explorer space.

**Comment by ibuziuk** [comment] 2018-11-27 12:21
Upstream issue has been fixed [1]. Closing

[1] https://github.com/eclipse/che/issues/7143

**Closed by ibuziuk** 2018-11-27 12:21 UTC
Labels: SEV2-high, area/che, priority/P3, team/che, team/che/ide1, type/bug
