### ISSUE TITLE
Cannot create a new application using new launcher

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3044] opened 2018-04-12 09:41 UTC
Received an error message that states that there was a problem with config.xml and as a result, my pipeline was not triggered. All other steps were complete while creating the application.

Snapshot:
![config xml does not contain valid xml](https://user-images.githubusercontent.com/28748448/38668995-da0df9d4-3e62-11e8-841a-711321d7caff.png)

Steps: 
1) Updated tenant
2) Using the new launcher, selected REST API mission and the Vert/x runtime
3) Selected all defaults and clicked the button to create an application, then I observe the error in the snapshot above.

This caused my pipeline to never trigger and all I could see was this:
![pipeline not triggered](https://user-images.githubusercontent.com/28748448/38669314-a9c7733a-3e63-11e8-94db-a1fcd393d361.png)

**Comment by jyasveer** [comment] 2018-04-18 18:54
@animuk @ravsa can you please have a look at this. This is something to do with the server side calls. Thanks

**Comment by sunilk747** [comment] 2018-04-23 06:02
@rgarg1 I couldn't reproduce the issue. Can you please provide me all the related inputs to reproduce this issue. Did you tried again with the same input?

**Comment by sunilk747** [comment] 2018-04-23 06:04
@rgarg Can you share your config.xml from openshift console? DM me.

**Comment by sunilk747** [comment] 2018-04-23 08:33
Closing this issue as I am not able to reproduce this. Please feel free to reopen this if you again encounter this issue.

**Closed by sunilk747** 2018-04-23 08:33 UTC
Labels: SEV2-high, area/app-wizard, area/launcher, team/analytics, team/analytics/wizard, type/bug
