### ISSUE TITLE
Che in OSIO displays review link to deployed app before that app can be reached

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2907] opened 2018-04-05 17:40 UTC
Steps to recreate:
* Create a new project in OpenShift.io
* Create a new Che workspace for the project
* Execute the run option (from the run button at the top of the Che display)
* Observe the preview link URL is displayed before the app is fully built

![screenshot from 2018-04-05 12-51-38](https://user-images.githubusercontent.com/642621/38382037-afcf3e8a-38d6-11e8-837d-bbbab28bd94e.png)

* Click on the link - observe that the app endpoint is not (yet) reachable:
![screenshot from 2018-04-05 12-51-54](https://user-images.githubusercontent.com/642621/38382105-dfc36dd2-38d6-11e8-83c7-21402adcb631.png)

**Comment by qodfathr** [comment] 2018-04-23 17:57
@ldimaggi  I assume if you just keep hitting refresh, the app eventually displays? If yes, please drop to SEV-3.

**Comment by ibuziuk** [comment] 2018-12-03 09:30
@ldimaggi I do not think that this issue is related to #2113, the route is unreachable due to the fact that preview url is displayed before the app is started, but I do not think we can do much about it, since currently it is expected behaviour in the upstream project. What UX are you expecting to have for the run commands ?

**Comment by rhopp** [comment] 2018-12-03 11:19
Just to put it in comparison with devstudio: 
In devstudio, the browser is opened automatically once the deployment finishes successfully.

But now, I don't see anything wrong with displaying preview URL even when the build didn't finish... Developer can see the console output, and he can determine from the output, whether the app should be already running or not.

**Comment by ibuziuk** [comment] 2018-12-03 16:23
@rhopp exactly, that's why I opt for close it as won't fix / expected behaviour. 
@ldimaggi if you think that UX should be improved please open relevant issue with details in upstream che, reopen this issue and link both.

**Closed by ibuziuk** 2018-12-03 16:23 UTC
Labels: SEV3-medium, area/che, priority/P4, team/che/osio, type/bug
