### ISSUE TITLE
Workshop issue: Pipeline failed to rollout to Stage

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1254] opened 2017-10-31 17:39 UTC
Error on Jenkins console:

> [Pipeline] End of Pipeline

Could not update commit status. Message: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/rafabene/myvertxhello/statuses/c6bda09a0aea605e9d8c060384f0f235beed933a

ERROR: Error during kubernetes apply: java.lang.RuntimeException: Failed to create ImageStream from pipeline.json. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://kubernetes.default/apis/image.openshift.io/v1/namespaces/rbenevid-stage/imagestreams/myvertxhello. Message: ImageStream in version "v1" cannot be handled as a ImageStream: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=ImageStream in version "v1" cannot be handled as a ImageStream: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.api.Controller.onApplyError(Controller.java:1459)
	at io.fabric8.kubernetes.api.Controller.applyImageStream(Controller.java:940)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:268)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:227)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.run(ApplyStepExecution.java:248)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.run(ApplyStepExecution.java:102)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:224)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:150)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:123)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:110)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:153)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:157)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor340.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:173)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:162)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:162)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://kubernetes.default/apis/image.openshift.io/v1/namespaces/rbenevid-stage/imagestreams/myvertxhello. Message: ImageStream in version "v1" cannot be handled as a ImageStream: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=ImageStream in version "v1" cannot be handled as a ImageStream: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:260)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:242)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:778)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:109)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:104)
	at io.fabric8.openshift.api.model.DoneableImageStream.done(DoneableImageStream.java:27)
	at io.fabric8.openshift.api.model.DoneableImageStream.done(DoneableImageStream.java:6)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:116)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:37)
	at io.fabric8.kubernetes.api.Controller.applyImageStream(Controller.java:936)
	... 68 more

Finished: FAILURE

**Comment by joshuawilson** [comment] 2017-11-01 02:15
@jstrachan @rawlingsj can you take a look please.

**Comment by rawlingsj** [comment] 2017-11-01 12:24
Is this reproducible every time and on new reset environments?  I think that error might be coming back from openshift but the year 2006 does look odd still, that said if it's not reproducible or happening every build it isn't a severity 1 / blocker.

**Comment by rupalibehera** [comment] 2017-11-01 13:31
@rawlingsj , I was not able to reproduce this issue, 
@rafabene it would be nice if you could share more details about it. It would help reproducing the issue. what was jenkins version (the jenkins image being used)
Did you try a 'reset environment' after you faced this issue  ?

**Comment by aslakknutsen** [comment] 2017-11-01 13:33
@rawlingsj 2006 is the Format, not the date. https://stackoverflow.com/questions/20530327/origin-of-mon-jan-2-150405-mst-2006-in-golang It's trying to parse an empty string into that format.

**Comment by jstrachan** [comment] 2017-11-01 15:23
the 2006 issue is due to this https://github.com/fabric8io/kubernetes-model/issues/241 PR and fix on the way - its a regression in the kubernetes-model

**Comment by joshuawilson** [comment] 2017-11-01 15:38
@rafabene can you please try to reproduce this.

**Comment by ldimaggi** [comment] 2017-11-01 19:38
I'm not able to reproduce this problem - is anyone still seeing it?

**Comment by pbergene** [comment] 2017-11-02 12:42
I just got it on my space.  Couldn't reproduce it earlier, but logged in and hit 'start pipeline' on the pipeline screen and it failed to rollout to stage.

**Comment by joshuawilson** [comment] 2017-11-02 12:59
Are you able to reproduce? Were you in incognito?

**Comment by pbergene** [comment] 2017-11-02 13:15
Did it from the top now, could reproduce a second time by resetting environment, wait for everything to come up, run vertx quickstart, wait for initial build to finish, promote to run and then hit 'run pipeline' on the pipeline screen.  You may end up with the same thing following other paths like triggering a build from somewhere else.
I was not in incognito mode, but I have a chrome I only use for osio which has worked well up until now.  Doing it in incognito too now for good measure.

**Comment by pbergene** [comment] 2017-11-02 15:04
Also applies to builds triggered by git commit from che, effectively breaking the workshop flow.

**Comment by ldimaggi** [comment] 2017-11-02 15:30
I was able to recreate the problem - the key is to re-run an existing pipeline. The first run is successful - the re-run fails.

**Comment by vpavlin** [comment] 2017-11-02 16:19
The supposed fix is merged, so maybe this is an issue with pipelines not being triggered automatically somewhere? @jstrachan @rajdavies @rawlingsj ?

**Comment by rafabene** [comment] 2017-11-02 17:50
Yes. It always happens on the second run.

**Comment by joshuawilson** [comment] 2017-11-03 05:44
We now know this is due to a something in Jenkins 4.0.42. If you manually change to 4.0.41, the pipeline runs. @rawlingsj @jstrachan

**Comment by aslakknutsen** [comment] 2017-11-03 08:42
Rollbacked to Jenkins 4.0.41 https://github.com/fabric8-services/fabric8-tenant/commit/1cc44c645dae1f64843923863698bdb4a0c94861

**Comment by joshuawilson** [comment] 2017-11-03 15:41
Closing and we'll let the next fix come when it does.

**Closed by joshuawilson** 2017-11-03 15:41 UTC
Labels: area/pipelines, kind/bug, severity/blocker, team/build-cd
