### ISSUE TITLE
[Launcher] build failure with timeout: Socket closed ERROR

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3023] opened 2018-04-12 05:34 UTC
Steps : 
- Create a new space
- Select new launcher flow
- Create codebase
- go through all steps
- trigger build

Build failed , logs : https://gist.github.com/invincibleJai/ef40904a8cac2bd5166ca087727cbc45

In second attempt build passed.

<img width="1680" alt="screen shot 2018-04-12 at 10 55 37 am" src="https://user-images.githubusercontent.com/5129024/38658046-f9217b42-3e40-11e8-9ef9-926ae377c7eb.png">

**Comment by quintesse** [comment] 2018-04-23 13:43
We're experiencing the very same thing (in openshift.io) and it prevents us from doing proper testing. @krishnapaparaju , @gastaldi told me you could perhaps assign someone of your team to help us with this?

**Comment by invincibleJai** [comment] 2018-04-23 14:04
@quintesse it's related to second part of the this issue https://github.com/openshiftio/openshift.io/issues/2833 i.e FMP timeout error

@hrishin from build was looking into it. 
@animuk PTAL

**Comment by rohanKanojia** [comment] 2018-04-24 11:09
Duplicate of #3058

**Comment by joshuawilson** [comment] 2018-04-25 02:53
closing duplicate

**Closed by joshuawilson** 2018-04-25 02:53 UTC
Labels: SEV2-high, area/app-wizard, env/prod, issue/intermittent, team/build-cd, type/bug
