### ISSUE TITLE
Environments page's Experimental features has a lot of odd bugs

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#1929] opened 2018-01-19 05:11 UTC
I'm just logging a bunch of smaller issues here since they all pertain to the same task: enabling experimental features from the Environments page.

* Typo: "Use *theses* at your own risk" should be "Use these at your own risk".
* Changing the Chrome window/tab size makes things disappear. See this example:
  * First, we have the normal smaller sized tab with nothing wrong:
![okay](https://user-images.githubusercontent.com/926572/35135631-2dac38dc-fd2a-11e7-8179-a943617719fb.png)

  * Then, we make the window a bit narrower and the "Got It" banner disappears:
![bar_disappears](https://user-images.githubusercontent.com/926572/35135642-3ffb8d94-fd2a-11e7-8d67-66e4d2f77724.png)

  * Then we make it a bit less narrow again and the submenu bar disappears:
![menu_disappears](https://user-images.githubusercontent.com/926572/35135674-785121d6-fd2a-11e7-96e9-b01aefbdc41d.png)

* Finally, when we click *Opt-in to Experimental Features* (this takes two clicks to do anything, but that issue is already logged), we get this page with some weird options at the bottom. I couldn't replicate this error but mentioned it because it happened once and I'm not sure why or where it came from.
![broken](https://user-images.githubusercontent.com/926572/35135759-0bd86766-fd2b-11e7-8af2-92f28c520e88.png)

**Comment by mishaone** [comment] 2018-01-19 05:20
Also, I'd suggest that clicking Update should take us back to the Environment page instead of the Profile page.

**Comment by joshuawilson** [comment] 2018-01-19 05:43
Some of this is a duplicate of #1921 and #1922. But the typo is new. Can you please clean this up to be just one issue or close it and make an individual bug for each issue found. It is easier to track and fix when each issue is for just one thing.

**Comment by mishaone** [comment] 2018-01-19 05:54
No problem, @joshuawilson. Created https://github.com/openshiftio/openshift.io/issues/1930 for the typo. If the rest aren't new (admittedly I don't know how to replicate that last one), please feel free to close this one.

**Closed** 2018-01-19 06:10 UTC
Labels: area/feature flags, team/platform, type/bug
