### ISSUE TITLE
Codebases and Pipelines are not connected

### ISSUE THREAD

**Issue by hferentschik** [openshiftio/openshift.io#1707] opened 2017-12-18 11:06 UTC
I started with a full reset of my environment. I then add a new codebase - https://github.com/hferentschik/openshift.io-demo.git. 

The codebase appears in the "Codebases" section. The Pipelines stay empty. I then select to add create a pipeline. Naturally, I would expect that I primarily get asked to select the configured codebase for which I want to create a pipeline. Instead, I have to select a GitHub repository again. 

Now my minimum expectation is that the system matches up codebase and pipeline. No such luck, I end up with to codebases against the same repository. 

![mismtach](https://user-images.githubusercontent.com/296354/34103130-e8a1468a-e3eb-11e7-9f8e-102aa6bb1786.png)

**Comment by joshuawilson** [comment] 2017-12-20 03:14
I'm not sure if this is a bug or a question about the user flow.
@catrobson can you please have someone look into this?

**Comment by hferentschik** [comment] 2017-12-20 08:29
IMO it is both. In its current form, it is a bug. However, I also think the overall flow is not quite right.

**Comment by catrobson** [comment] 2017-12-20 13:25
+1 that this is confusing right now.  I don't think there is a bug here actually, I think this is as designed currently.  We'll work on improving this as we update the space dashboard designs.

**Comment by joshuawilson** [comment] 2018-01-19 05:36
So the simple solution would be to have the pipeline default to use the codebase listed if there is one. Do you agree?

**Comment by catrobson** [comment] 2018-01-19 14:10
@joshuawilson I think we shouldn't have an "add" on the pipeline widget at all probably, since really all you can add are applications, which consist of codebases + pipelines.  The application wizard should be the only way I can add a pipeline.

**Comment by joshuawilson** [comment] 2018-01-19 14:51
I think this is one for further discussion.

**Comment by qodfathr** [comment] 2018-01-27 15:45
We've got this oddity right now -- we have "Wizard Import," which lets you import a codebase **and** have a version of the App Wizard help you set up a pipeline, etc., and we also have "Add Codebase" (see #1576 ) which is just a quick-and-dirty way to add a codebase to the codebase list. I do not think this method will even establish a pipeline if a Jenkinsfile currently exists in the added repo. Unfortunately, it is a very prominiate option on the Codebases screen, and I think it's sending users to a place where most of them do not want to be.

IMHO, "Add Codebase" needs a lot of work. I'd personally be okay with instead having the common "Add to Space" on the Codebases screen which uses the Wizard, because the Wizard seems to be the best way to get a clean set-up across OSIO.

The Wizard may need some additional options on import. e.g. use my existing Jenkinsfile, create a new Jenkinsfile, **I don't want a Jenkinsfile**. I think that last option is missing -- let me import, I do not currently have a Jenkinsfile, and I do not want one (and, as such, I don't want a pipeline). We may even need "I have a Jenkinsfile, I do not want a new one, and I also do **not** want an OSIO pipeline added to my Space."

If people think I'm on the right track with these thoughts, and we do not already have a plan for these options, I'll create a new issue.

**Comment by qodfathr** [comment] 2018-01-27 20:23
Se also #1848

**Comment by catrobson** [comment] 2018-01-28 18:15
Agreed we need to clean up these flows, and agree with a "I don't want a Jenkinsfile" option."   We'll probably want to call this "pipeline" and get into the details of the jenkinsfile as a definition of your pipeline in the advanced cases for a user's perspective.

**Comment by jiekang** [comment] 2018-06-20 16:25
The Add Codebase action described here is no longer accessible. All the buttons now open the wizard instead, forcing users to add a codebase and pipeline combination. Closing this issue.

**Closed by jiekang** 2018-06-20 16:25 UTC
Labels: area/UX, area/codebases, area/dashboard, area/pipelines, team/platform, team/ux, type/question
