### ISSUE TITLE
Importing a new project starts 2 builds

### ISSUE THREAD

**Issue by sthaha** [openshiftio/openshift.io#3854] opened 2018-06-26 03:10 UTC
I see two builds (instead of one) being started in openshift console  when a new codebase is added 

#### Steps to reproduce

1. create a new workspace 
1. Add an new codebase (didn't try with import codebase)
1. Select REST 0, and vertx-booster ( I don't think it matters what you choose)
1. Select the default release workflow (build -> stage -> approve -> run)
1. Wait for the pipeline to start 

##### Actual result

1. Pipeline starts with `Build - 2` instead of `Build - 1`
1. The `Build - 2` fails and then `Build - 1` starts 

OSO pipeline view looks a below: 
![2-pipelines](https://user-images.githubusercontent.com/3005132/41886566-3d89a1b2-7940-11e8-9ec7-2a8ed1e57ff3.png)

Pipeline History on OSIO looks like
![2-build-osio](https://user-images.githubusercontent.com/3005132/41886730-03a10836-7941-11e8-89ce-5169daaef5c9.png)

Build - 2 fails with the following error
```
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[WARNING] Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager@1c4dcd0
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:47 min
[INFO] Finished at: 2018-06-26T02:54:38+00:00
[INFO] Final Memory: 42M/78M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project st-vertx-booster-j26: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build st-vertx-booster-j26-s2i-1: Failed: PullBuilderImageFailed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:build (fmp) on project st-vertx-booster-j26: Failed to execute the build
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

#### Observation 

It seems to me that launcher is starting two pipelines instead of one which can be verified by going to openshift console and starting two pipelines.

**Comment by piyush1594** [comment] 2018-06-26 05:09
Duplicate of #3742

**Closed** 2018-06-26 05:11 UTC
Labels: SEV3-medium, area/launcher, team/launcher, type/bug
