### ISSUE TITLE
Finding WIs by ID on the Link Panel

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#3666] opened 2018-05-29 10:16 UTC
Finding Work Items to link to using the search input on the link panel is not working as it should. I couldn't figure out how it actually does searches. Exact titles of WIs don't match, but single words are. Also (and that is a severe issue) IDs don't match.

We should make sure the user can at least just input a WI ID and gets the WI in the result list.

**Comment by michaelkleinhenz** [comment] 2018-05-29 15:05
This needs confirmation. It looks like it works sometimes.

**Comment by rgarg1** [comment] 2018-05-30 06:44
Steps that I figured can reproduce the issue:

1) Have a few work items in the list view
2) Open a work item quick-preview > Link
3) Select link type = Relates to
4) Type the work item ID of the work item just above the selected. The planner should be able to successfully search and suggest the WI to be added
5) Don't create the link, but just close the quick preview window with the link type set to "Relates to"
6) Repeat steps 2 through 4. Observe that this time, typing the WI ID does **not** search the work item.\

Gif:
![link issue](https://user-images.githubusercontent.com/28748448/40703483-e8e3c9be-6402-11e8-8b0e-26cd08efd5be.gif)

**Comment by michaelkleinhenz** [comment] 2018-05-30 10:46
This has a workaround, setting it to SEV-3.

**Comment by divyanshiGupta** [comment] 2018-07-03 08:10
@rgarg1 can you confirm if the issue is still present as I was not able to reproduce the issue following the above steps.

**Comment by divyanshiGupta** [comment] 2018-07-31 07:45
@rgarg1 this issue is not reproducible, probably the issue is fixed.

**Comment by divyanshiGupta** [comment] 2018-08-17 11:03
Still cannot reproduce this issue and hence closing it. Feel free to open the issue if the issue is seen again.

**Closed by divyanshiGupta** 2018-08-17 11:03 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
