### ISSUE TITLE
Openshift.io integration with GH didn't allow me to specify which GH organizations can be connected

### ISSUE THREAD

**Issue by rsvoboda** [openshiftio/openshift.io#1813] opened 2018-01-10 11:56 UTC
Openshift.io integration with GH didn't allow me to specify which GH organizations can or cannot be also connected.

Of course this can be prevented by GH organization configuration, but I don't have control over them.

Now I must be extra careful because I have one private organization connected to openshift.io.
I can't do any fine-tuning, I looked at https://github.com/settings/applications and my profile => My Connected Accounts at https://openshift.io/

**Comment by camilamacedo86** [comment] 2018-01-10 12:14
I could not face the same issue:

It is showing for me all organizations:

<img width="911" alt="screen shot 2018-01-10 at 12 12 40 pm" src="https://user-images.githubusercontent.com/7708031/34772367-a5c2615c-f5ff-11e7-8164-b19558699c82.png">

My GitHub account is associated with the profile:

<img width="965" alt="screen shot 2018-01-10 at 12 18 04 pm" src="https://user-images.githubusercontent.com/7708031/34772440-d6307d9c-f5ff-11e7-8311-51f53ea2b18c.png">

**Comment by rsvoboda** [comment] 2018-01-10 13:21
This is about GitHub.com Authorization described on page 6 of getting started pdf.

**Comment by qodfathr** [comment] 2018-01-10 13:44
This is definitely a bug; it makes it impossible for a user to safely proceed through the application wizard as there is no way to know in which org the codebase is going to be created.

**Comment by pbergene** [comment] 2018-01-10 14:16
@gastaldi something for you? It came up on the issue triage that you had worked a related or similar issue.

**Comment by gastaldi** [comment] 2018-01-10 14:18
@pbergene I'll have a look at it.

**Comment by gastaldi** [comment] 2018-01-10 14:19
Why is this SEV1? Is this happening in production?

**Comment by qodfathr** [comment] 2018-01-10 14:49
@gastaldi as this is essentially blocking *all* updates/pushes to prod, I'm labeling as a SEV1.

**Comment by gastaldi** [comment] 2018-01-10 14:54
@qodfathr ok, just wanted to understand if that was happening in production too. I'm working in this right now

**Comment by gastaldi** [comment] 2018-01-10 14:56
Also, it was my understanding that issues labeled as SEV1 impacts customer-facing in production only

**Comment by qodfathr** [comment] 2018-01-10 14:58
@gastaldi a fair point, but I needed a way to get this moved to the top of the fix queue immediately. Plus, although I observed in prod-preview, I'm curious if @rsvoboda observed in production.

**Comment by maxandersen** [comment] 2018-01-10 15:03
for what it is worth - I just tried in both prod-preview and production and I see an organization drop down in both cases.

![2018-01-10_15-59-21](https://user-images.githubusercontent.com/54129/34779001-405a9dc8-f61f-11e7-8051-29e9cb437642.png)

Thus I'm not sure what issue is being reported here ? 

from @rsvoboda it feels like his issue is with how github today don't allow fine grained permissions -  it an all or nothing afaik. 

@rsvoboda  is that your issue ?

**Comment by qodfathr** [comment] 2018-01-10 15:06
@maxandersen agreed, it seems to be working now. Can anyone confirm that there was a change made to address this?

**Comment by gastaldi** [comment] 2018-01-10 15:09
I have only pushed the visibility for the Runtime Version field yesterday. Now, comparing the boosters in production, I see that there are more boosters than in production. I'll fix it in a different issue

**Comment by rsvoboda** [comment] 2018-01-10 16:07
This issue is intended to be about initial GitHub.com Authorization when new user comes. Sorry if I didn't provide enough details, I tried to add some clarification in my comment https://github.com/openshiftio/openshift.io/issues/1813#issuecomment-356600233

I'm member of 5 organizations, some were "blocked" when I was authorizing OpenShift.io to consume my GH stuff, 2 organizations were checked, I had no way to say that I don't want content of one organization to be seen by OpenShift.io.

I wanted to replicate the problem, so I revoked Opensift.io from https://github.com/settings/applications. Looking at https://openshift.io/rsvoboda@redhat.com I still see "GitHub - Connected", I tried to log out & log in again. Still see "GitHub - Connected". Probably bug candidate.
"Import existing code" sees no organization / repository. Is there a way to force GitHub Authorization again ?

**Comment by qodfathr** [comment] 2018-01-10 16:09
Thanks, @rsvoboda -- there are two issues then that had a similar context but I probably conflated the two of them. Thanks for the clarification.

**Comment by joshuawilson** [comment] 2018-01-10 18:12
@qodfathr can we change the severity?

**Comment by gastaldi** [comment] 2018-01-10 18:20
Is this issue specific related to wizard? According to @rsvoboda's comment, it seems to be in the initial Github authorization screen?

**Comment by qodfathr** [comment] 2018-01-10 19:49
@joshuawilson actually, this now feels more like a real SEV1 issue, as it is impacting first time users on prod.

@gastaldi yes, the original intent of this issue was to report an Auth issue, but I confused it with an app wizard issue. The app wizard issue has gone away, so we can drop that label, but the auth issue (I assume) still remains.

**Comment by joshuawilson** [comment] 2018-01-10 19:51
cc @alexeykazakov @sbose78

**Comment by alexeykazakov** [comment] 2018-01-10 20:42
Here are two issues:

1. GitHub does not support fine grained permissions in terms of choosing what org can be accessible by the app (OSIO) and what can't when we requesting GitHub authorization. There is nothing we can do about this. And it's not a Sev1.

2. Currently users can't re-connect GitHub in OSIO UI in prod. It's available in preview but we are still waiting for the latest UI to be rolled out to prod. It's possible to re-connect via REST API in prod though (I can provide details if needed).

So, I'm going to remove team/auth from this issue and assign it to team/platform because #2 will be fixed when platform UI is updated in prod.

**Comment by qodfathr** [comment] 2018-01-10 20:50
@alexeykazakov thank you for your analysis. Now that I fully grok the issue, I agree with you. The behavior that is being seen is as designed. Furthermore, it's a limitation imposed by GitHub's APIs. This is not a regression.

We'll work on a plan to get the latest fixes pushed to prod.

**Comment by alexeykazakov** [comment] 2018-01-11 07:54
Let’s not mix up the new app/import wizards with connecting GitHub and OSIO accounts. They are related but different features/areas. We already are talking about a few different issues here. Let’s track them separately in dedicated issues.

Regarding the re-connection API:

Step 1:  Disconnect Github.
curl -i -H "Authorization: Bearer $AUTH_TOKEN" -X DELETE https://auth.openshift.io/api/token?for=https://github.com
Step 2:  Re-login and you would be asked to connect your github account.

**Comment by alexeykazakov** [comment] 2018-01-11 07:55
$AUTH_TOKEN is your token from the profile page.

**Comment by rsvoboda** [comment] 2018-01-11 08:03
Thanks, asked to connect GH account.

**Comment by adisakala** [comment] 2018-01-11 15:50
@alexeykazakov should area/auth label be removed from this as well?

**Comment by joshuawilson** [comment] 2018-01-11 17:08
We've gotten the UI updated with the fix listed above.
Is there something else that needs fixing or can we close this?

**Comment by qodfathr** [comment] 2018-01-11 17:18
I'm ready to close; @alexeykazakov / @rsvoboda can you please cast a vote?

**Comment by sbose78** [comment] 2018-01-11 17:19
> I'm member of 5 organizations, some were "blocked" when I was authorizing OpenShift.io to consume my GH stuff, 2 organizations were checked, I had no way to say that I don't want content of one organization to be seen by OpenShift.io.

There's nothing we can fix here since Github doesn't support granular permissions, unfortunately. 


> I wanted to replicate the problem, so I revoked Opensift.io from https://github.com/settings/applications. Looking at https://openshift.io/rsvoboda@redhat.com I still see "GitHub - Connected", I tried to log out & log in again. Still see "GitHub - Connected". Probably bug candidate.
> "Import existing code" sees no organization / repository. Is there a way to force GitHub Authorization again ?

This has been addressed by the UI promotion-to-prod.

Therefore, we could close this issue.

**Comment by sbose78** [comment] 2018-01-11 17:28
@adisakala  `area/auth` seems OK for the second part of the issue.

**Comment by joshuawilson** [comment] 2018-01-11 17:56
reopen if needed

**Closed** 2018-01-11 17:56 UTC
Labels: SEV1-urgent, area/auth, team/platform, type/bug

**Comment by rsvoboda** [comment] 2018-01-12 08:14
+1 for close. I'm in Europe so I saw https://github.com/openshiftio/openshift.io/issues/1813#issuecomment-356997962 after this was closed :)
