### ISSUE TITLE
[prod-preview] Unable to successfully create quick start projects

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1782] opened 2018-01-05 06:08 UTC
I have tried creating a new quick start application in **prod-preview** (**vert.x booster**)

I was able to select Vert.x Booster but was unable to proceed beyond that.

Here is what I get, (
<img width="1437" alt="screen shot 2018-01-05 at 11 11 22 am" src="https://user-images.githubusercontent.com/7880465/34597016-211901ac-f20a-11e7-90ea-3c3d65e6bf65.png">
PFA)

**Comment by joshuawilson** [comment] 2018-01-05 07:39
Is this a duplicate of #1503 and #1634?

**Comment by gastaldi** [comment] 2018-01-10 13:01
Is this still happening? This seems to be caused by the cluster issues last week?

**Comment by gastaldi** [comment] 2018-01-10 14:15
Closing as we believe this was caused by the cluster instabilities. Reopen if the problem persists

**Closed by gastaldi** 2018-01-10 14:15 UTC
Labels: SEV2-high, area/app-wizard, area/quickstarts, team/analytics/wizard, team/che/platform, team/launcher, type/bug
