### ISSUE TITLE
Few times, OSIO build pipelines never get a start

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2756] opened 2018-03-24 17:46 UTC
I have initiated a build three hours back, its never got started.

Need to address these challenges:

1) Fix this problem

2) If OSIO users get into same problem, how does build developer team get to know the stats. to work towards better user experience ?

<img width="1433" alt="screen shot 2018-03-24 at 11 13 14 pm" src="https://user-images.githubusercontent.com/15967765/37867063-48c85b5c-2fb9-11e8-83d8-84e190e7386c.png">

**Comment by joshuawilson** [comment] 2018-03-25 03:00
I think there are several issues that report this.

**Comment by ldimaggi** [comment] 2018-03-25 04:01
When you see this problem - what is the state of the Jenkins pod? It's difficult to make a determination on this bug without additional information.

The problem might be this issue:  https://github.com/openshiftio/openshift.io/issues/2427

**Comment by krishnapaparaju** [comment] 2018-03-26 04:27
I still see the problem, attaching screens : OSIO pipelines, pods at Jenkins project..

<img width="484" alt="screen shot 2018-03-26 at 9 56 26 am" src="https://user-images.githubusercontent.com/15967765/37886908-1930141a-30dc-11e8-8a3f-104529df5d84.png">
<img width="515" alt="screen shot 2018-03-26 at 9 56 54 am" src="https://user-images.githubusercontent.com/15967765/37886919-236a09a4-30dc-11e8-89b7-35908aeee63f.png">

**Comment by krishnapaparaju** [comment] 2018-03-26 04:32
Attaching 
[jenkins-logs.txt](https://github.com/openshiftio/openshift.io/files/1846319/jenkins-logs.txt)
Log content from Jenkins pod

**Comment by chmouel** [comment] 2018-03-26 04:47
@krishnapaparaju this is a dupe of https://github.com/openshiftio/openshift.io/issues/2427 where it's investigated

**Closed by chmouel** 2018-03-26 04:47 UTC
Labels: SEV2-high, team/build-cd, type/bug
