### ISSUE TITLE
Cannot delete space and API response makes a reference to my another account on OSIO

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3932] opened 2018-07-06 12:24 UTC
**Space created using user ID:** rgarg-osiotest1
**Space being deleted using user ID:** rgarg-osiotest1

**Request made:**
Request URL: https://api.openshift.io/api/spaces/17c1e9de-a89a-494b-91c4-819a013cb3b9
Request Method: DELETE
Status Code: 500 Internal Server Error

**Response from server:**
{"errors":[{"code":"internal_error","detail":"failed to GET url http://f8osoproxy/oapi/v1/namespaces/rgarg-osiotest1/buildconfigs?labelSelector=space%!D(MISSING)rgarg-osiotest1-AGILE-space-2018-07-02T05-00-57 due to status code 403: buildconfigs is forbidden: User \"rgarg-1\" cannot list buildconfigs in the namespace \"rgarg-osiotest1\": User \"rgarg-1\" cannot list buildconfigs in project \"rgarg-osiotest1\": buildconfigs is forbidden: User \"rgarg-1\" cannot list buildconfigs in the namespace \"rgarg-osiotest1\": User \"rgarg-1\" cannot list buildconfigs in project \"rgarg-osiotest1\"","status":"500","title":"Internal error"}]}

Observe the reference to my other account _rgarg-1_

**Comment by sbose78** [comment] 2018-07-11 04:52
Ruchir, does this happen in incognito as well?

**Comment by rgarg1** [comment] 2018-07-11 06:19
I can confirm that this problem happens even without the browser being involved. Just using APIs to create and delete the space is enough to see this problem.

**Comment by stooke** [comment] 2018-07-12 15:20
@rgarg1 what is the output when you try to GET
https://api.openshift.io/api/deployments/spaces/17c1e9de-a89a-494b-91c4-819a013cb3b9 ?
(please ensure you are using the appropriate auth token)

**Comment by stooke** [comment] 2018-07-13 14:21
@rgarg1, are both accounts linked to the same GitHub account?

**Comment by notfred** [comment] 2018-07-13 19:42
@rgarg1 I am trying to reproduce your issue but have failed so far. Is it ongoing? Also can you give me the exact steps you used to reproduce this?

**Comment by stooke** [comment] 2018-07-13 19:44
@rgarg1 I am trying to reproduce your issue but have failed so far. Is it ongoing? Also can you give me the exact steps you used to reproduce this?

**Comment by rgarg1** [comment] 2018-07-16 07:06
@stooke 

GET https://api.openshift.io/api/deployments/spaces/17c1e9de-a89a-494b-91c4-819a013cb3b9

**Using rgarg-osiotest1 account:**
{
    "errors": [
        {
            "code": "internal_error",
            "detail": "failed to GET url http://f8osoproxy/oapi/v1/namespaces/rgarg-osiotest1/buildconfigs?labelSelector=space%3Drgarg-osiotest1-AGILE-space-2018-07-02T05-00-57 due to status code 403: buildconfigs is forbidden: User \"rgarg-1\" cannot list buildconfigs in the namespace \"rgarg-osiotest1\": User \"rgarg-1\" cannot list buildconfigs in project \"rgarg-osiotest1\": buildconfigs is forbidden: User \"rgarg-1\" cannot list buildconfigs in the namespace \"rgarg-osiotest1\": User \"rgarg-1\" cannot list buildconfigs in project \"rgarg-osiotest1\"",
            "status": "500",
            "title": "Internal error"
        }
    ]
}

**Using rgarg1 account:**
{
    "data": {
        "attributes": {
            "applications": [],
            "name": "rgarg-osiotest1-AGILE-space-2018-07-02T05-00-57"
        },
        "id": "17c1e9de-a89a-494b-91c4-819a013cb3b9",
        "type": "space"
    }
}
++++++++++++++++++++++++++++++++++++++++++++++=
Also,

Request URL: https://api.openshift.io/api/namedspaces/rgarg-osiotest1/rgarg-osiotest1-AGILE-space-2018-07-02T05-00-57
Request Method: GET
Status Code: 200 OK

"owned-by": {
        "data": {
          "id": "02227dc6-f4fe-451b-9549-4c5b7becc5e7",
          "type": "identities"
        }

Request URL: https://auth.openshift.io/api/users/02227dc6-f4fe-451b-9549-4c5b7becc5e7
Request Method: GET
Status Code: 200 OK

**Response:**
{
      "email": "rgarg+osiotest1@redhat.com",
      "fullName": "Ruchir Garg",
      "identityID": "02227dc6-f4fe-451b-9549-4c5b7becc5e7",
      "providerType": "kc",
      "username": "rgarg-osiotest1"
}

The above experiment confirms that though space is owned by _rgarg-osiotest1_, the system believes its owned by _rgarg1_.

**Comment by rgarg1** [comment] 2018-07-16 07:14
**UPDATE**

The problem is now solved.

Reason: 
My account rgarg-osiotest1 was linked to Openshift account of rgarg1. I saw this in the settings page of my profile. Once I clicked the refresh link next to that, its auto fixed itself and started to show rgarg-osiotest1.

If you can figure and fix the root cause of the problem, its would be great.

**Comment by stooke** [comment] 2018-08-23 18:45
Closing this issue now, as there is no evidence of a root cause affecting other users, and this hasn't reoccurred.

**Closed by stooke** 2018-08-23 18:45 UTC
Labels: SEV2-high, area/deployments, priority/P4, team/platform, type/bug
