### ISSUE TITLE
Intermittent issue - Che workspace creation fails in OSIO - Exception while obtaining OSO token

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#827] opened 2017-09-15 19:29 UTC
This issue has occurred in the past and is being seen today - is there a KeyCloak outage/issue?

```
Could not start workspace bgoja. Reason: Start of environment 'default' failed. Error: Fail launching agent Terminal. Workspace ID:workspacejs7ibamsp4oo7mn3

2017-09-15 19:16:18,895[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 40534 ms
--
  | 2017-09-15 19:17:11,596[nio-8080-exec-6]  [ERROR] [.k.t.p.u.KeycloakUserValidator 220]  - Exception while obtaining OSO token:
  | java.io.IOException: Failed access: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token, method: GET, response code: 400, message: {"errorMessage":"Invalid token."}
```

[che2log.txt](https://github.com/openshiftio/openshift.io/files/1307560/che2log.txt)

![screenshot from 2017-09-15 15-22-11](https://user-images.githubusercontent.com/642621/30499994-98f1c66a-9a2a-11e7-8685-a33311fd1e19.png)

**Comment by alexeykazakov** [comment] 2017-09-15 23:25
It can be anything.. Keycloak problem or something wrong with the token passed by Che.

**Comment by ibuziuk** [comment] 2017-09-16 06:48
If the problem was on Che side the issue would be persisted and not Intermittent IMO

**Comment by alexeykazakov** [comment] 2017-09-16 07:24
How does Che get the token?

**Comment by alexeykazakov** [comment] 2017-09-16 21:22
No, I mean how do you get the Keycloak token? This error also returned if Keycloak session used to get the KC token has been closed. For example if you logout from OSIO/KC. Closing session invalidates the token. I ran the OSO token endpoint test a few hundred times. All passed. So, this endpoint seems to be stable, at least right now.

@ldimaggi do you reproduce it manually or it's some automated test? It's prod right?

**Comment by ldimaggi** [comment] 2017-09-17 22:55
The problem is beeing seen both with manual and automated tests - in production. Thx!

**Comment by ibuziuk** [comment] 2017-09-18 07:36
> Closing session invalidates the token
Hmm.. but I thought that tokens are not expired once the session is invalidated (as I recall KC token invalidation was time based, and the token were invalidated after 1 month)
@davidfestal could you please clarify how we obtain keycloak token in rh-che (I think it is managed by tomcat valve)

**Comment by davidfestal** [comment] 2017-09-18 12:22
> @davidfestal could you please clarify how we obtain keycloak token in rh-che (I think it is managed by tomcat valve)

No currently on `rh-che`, the valve or tomcat adapter are *only used for checking the received token*.
The token is retrieved/refreshed *from the client-side* (either the dashboard of the GWT application).
And, afair, each time a request comes from the GWT application to the wsmaster with the Keycloak token, the token value is updated in a cache and available for OSO token retrieval.

In the specific case of this issue, the Keycloak token is refreshed regularly by a timer in the GWT application here:
https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-ide-war/src/main/patches/src/main/webapp/IDE.jsp.patch#L26

However this timer-based implementation is not very robust.
Additionally, if no request is sent from the GWT application to the wsmaster API, the Keycloak token will not be updated on the wsmaster side.

So yes, there might be some use-cases, when the wsmaster would have an obsolete Keycloak token for some time.

#### IMO the real fix is on upstream

And I've made a simplification of the overal Keycloak token management in Che the last month, and this now allows managing token retrieval / refreshing on-the-fly when building async requests inside the GWT application also (through promises). But this has only been merged in the upstream multi-user branch. Not in `rh-che` for now.

As for maintaining an up-to-date  Keycloak token available in the wsmaster, this is also something we've discussed with @skabashnyuk, since it's a need he has in his work on generic OAuth token retrieval implementation. I'm expected to work on a POC for a wsmaster up-to-date Keycloak token cache very soon.

To summarize, IMO this issue should be fixed when switching `rh-che` to use the `multi-user` branch of the upstream Che that will include the reworked Keycloak integration and a generic implementation of OAuth token retrieval (which @s).

Fixing this is also something mandatory for the work I'm currently doing on multi-tenancy supoort.

#### Temporary possible Fix

In the meantime a simple way to fix this would be:
- to adjust the interval defined in line:

https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-ide-war/src/main/patches/src/main/webapp/IDE.jsp.patch#L34

and the `minValidatity` in the `updateToken` request here:
https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-ide-war/src/main/patches/src/main/webapp/IDE.jsp.patch#L27

Until now the default value of 5 seconds is used. Which is not consistent with the interval of 5 minutes.

- to call a wsmaster endpoint when the then token is refreshed here:
https://github.com/redhat-developer/rh-che/blob/master/builds/fabric8-che/assembly/assembly-ide-war/src/main/patches/src/main/webapp/IDE.jsp.patch#L27
This will update the keycloak token in the wsmaster token cache.

**Comment by alexeykazakov** [comment] 2017-09-18 17:44
> Hmm.. but I thought that tokens are not expired once the session is invalidated (as I recall KC token invalidation was time based, and the token were invalidated after 1 month)

Killing a session (when user logs out for example) doesn't expire the token. But it does invalidate it. So the token is not valid (and rejected by Keycloak) even if the expiration date is still good.

**Comment by alexeykazakov** [comment] 2017-09-18 17:51
@davidfestal this particular issue doesn't seem to be related to the fact that you refresh tokens every 5 minutes instead of every 5 seconds :) The tokens used in OSIO get expired in 30 days after issuing.

**Comment by ibuziuk** [comment] 2017-09-18 18:07
@alexeykazakov hmm.. a bit lost in process of how keycloak check if the token is valid or not. So, it uses expiration date +  tracks all the sessions and invalidate token*s* (token refresh happens every 30 seconds or so) issued for particular session when the session is invalidated ?

**Comment by alexeykazakov** [comment] 2017-09-18 18:25
@ibuziuk by session I mean the Keycloak session. Sorry for the confusion if it wasn't clear. When user logs in to OSIO/Keycloak a new session is created and a set of tokens are issued (access, refresh, and identity token). When you refresh the token then the new tokens are assigned to the same Keycloak session. Keycloak store this session and check if it's still active when validating the token. One login - one session. But if session is not active anymore (user was logged out or the session was killed manually in the admin console) then Keycloak will reject such token as invalid. The reference to the corresponding session is stored in browser cookies, in token itself and in Keycloak.

**Comment by ibuziuk** [comment] 2017-09-18 18:35
@alexeykazakov great, thanks for clarifications. In any case this issue does not seem to be connected keycloak session invalidation (this looks like manual process - log out / killing from admin console)

**Comment by alexeykazakov** [comment] 2017-09-18 18:57
Yeah, but this is why it's important to know what @ldimaggi did to reproduce it :) For example if he tried to open che in one browser tab and did logout in another then it will kill the token.

**Comment by ldimaggi** [comment] 2017-09-19 02:16
The steps to recreate this issue are:
* Reset user environment
* Create new space
* Create new quickstart
* And - the issue presents itself - on an intermittent basis

**Comment by ibuziuk** [comment] 2017-10-23 10:34
@ldimaggi is it still reproducible ?

**Comment by ldimaggi** [comment] 2017-10-23 12:02
I have not seen this issue for a while - we should close this - I will re-open if it re-appears.

**Comment by ibuziuk** [comment] 2017-10-23 12:04
thanks @ldimaggi. Closing

**Closed by ibuziuk** 2017-10-23 12:04 UTC
Labels: area/che, kind/bug, severity/P1, team/auth, team/che
