### ISSUE TITLE
Pipeline build image timer resets to zero seconds if user leaves/returns to page

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#4688] opened 2019-01-07 21:04 UTC
##### Issue Overview
If, while a pipeline build is running, the user leaves the pipeline page, and then navigates back to that page, the timer displayed for the build resets to zer.

##### Expected Behaviour
I expected that the timer would continue to be incremented even if the user leaves the pipeline page.

##### Current Behaviour
The timer resets to zero.

##### Steps To Reproduce

1. Start a pipeline build.

2. Navigate to the pipeline page. Observe the pipeline timer counter increment. For example:
![screenshot from 2019-01-07 15-47-26](https://user-images.githubusercontent.com/642621/50793082-06802800-1295-11e9-9aa5-a5f30253d5bb.png)

3. Navigate to a different page. For example, the codebases page:
![screenshot from 2019-01-07 15-47-37](https://user-images.githubusercontent.com/642621/50793196-62e34780-1295-11e9-8d26-d90d4adee870.png)

4. Navigate back to the build pipeline page. Observe that the build timer counter has reset to zero and has started incrementing again:
![screenshot from 2019-01-07 15-47-48](https://user-images.githubusercontent.com/642621/50793238-83130680-1295-11e9-96f9-dc4b7381fb54.png)

**Comment by piyush-garg** [comment] 2019-01-08 05:17
Duplicate of #4662

**Closed** 2019-01-08 12:44 UTC
Labels: SEV2-high, area/UI, area/pipelines, priority/P3, team/ui, type/bug
