### ISSUE TITLE
Tenant Pods fail to start if AWS API limit gets exceeded.

### ISSUE THREAD

**Issue by aditya-konarde** [openshiftio/openshift.io#1538] opened 2017-12-08 08:15 UTC
Ref: https://github.com/openshiftio/openshift.io/issues/1520

After troubleshooting on #1520, we found out that `attachvolume` requests were being blocked as `Client.RequestLimitExceeded`

We need to investigate what is causing the API usage, and what API limits per region are. 

This issue isn't causing any problems in prod as of now, but is a high-risk to prod. 

> Meta:
> Kind: Risk
> Team: Service Delivery

**Comment by aditya-konarde** [comment] 2017-12-08 08:16
CC: @pbergene

**Comment by mmclanerh** [comment] 2017-12-09 02:14
INC0651432 opened

**Comment by mmclanerh** [comment] 2017-12-09 02:30
shipped notice to oncall with inc and issue details. hoping a bump in the aws limits will resolve this issue.

**Comment by mmclanerh** [comment] 2017-12-09 03:27
was able to get ahold of someone.  known, ongoing issue.  afraid i dont have much to provide at this time other than: retry, and see if the limit is back down under threshold.

**Comment by fche** [comment] 2017-12-09 17:44
For reference, AWS' documentation on API rate limits doesn't disclose the actual limits.
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html

**Comment by l0rd** [comment] 2017-12-11 13:25
Another PVC related issue we spotted last week and related to #666: https://github.com/redhat-developer/rh-che/issues/467

**Comment by mmclanerh** [comment] 2017-12-11 21:03
* Some clean up was done of pending pods, the reduce API calls
* An upgrade of starter clusters is happening today, which is believed will reduce overall API call volume

**Comment by pbergene** [comment] 2017-12-12 10:10
Upgrade was stopped and rolled back to 3.6.  We are currently awaiting a new time slot for this.  In the mean time there has been identified a fair amount of stuck pods in osio namespaces which are the cause.  A workaround in form of a script that clears these pods has been implemented, which reduces the amount of calls to an acceptable amount.  This is being automated and in the meanwhile SRE will be provided with a script that can run this cleanup as required.

**Comment by pbergene** [comment] 2017-12-12 10:24
Downgrading this to Sev2 assuming workaround continues to be efficient.

**Comment by jfchevrette** [comment] 2017-12-18 14:06
Cluster has been upgraded to OpenShift 3.7. There are a couple of key changes in 3.7 to reduce the # of AWS API calls. Hopefully this means we won't hit the limit again.

I suggest that we close this issue as we have not observed any aws api errors in the past week since the workaround & cluster upgrade.

**Comment by aditya-konarde** [comment] 2017-12-18 16:36
+1 to @jfchevrette .

I think this issue can be closed now, and another one created if we can reproduce the AWS API limits blockers.

**Comment by mmclanerh** [comment] 2018-01-03 18:20
+1 on closing, not a current issue.

**Closed by mmclanerh** 2018-01-03 18:20 UTC
Labels: SEV2-high, team/service-delivery, type/bug
