### ISSUE TITLE
Che fails to start on some clusters (1a / 2 / 2a) due to infrastructure issues related to long route exposure and route flapping

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4695] opened 2019-01-09 09:44 UTC
Related HK issue - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2520
When I create a new booster in OSIO and open it in Che, Che is started properly but no projects are loaded and no error message is displayed to the user (wait timeout is 10 minutes). 

![Che](http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2134/04-01-che-failed.png)

E2E tests encountered this several times, so far only on clusters 1a and 2. 

I can see this errors in browser log:
```
[08:39:30.879] SEVERE _app-0.js 17981 WebSocket connection to 'wss://route458cf5up-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/wsagent?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlZTNza2c1ZXVyNm1sMHgxMyJ9.eyJ3c2lkIjoid29ya3NwYWNlZTNza2c1ZXVyNm1sMHgxMyIsInVpZCI6ImI1MzczNGFlLTNiNTMtNDU5Yi1iNjQwLWU1MzQwYjMzZjIwOSIsImF1ZCI6IndvcmtzcGFjZWUzc2tnNWV1cjZtbDB4MTMiLCJuYmYiOi0xLCJ1bmFtZSI6Im9zaW8tY2ktZTJlLTAwMiIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNTc4NTU5MTQxLCJpYXQiOjE1NDcwMjMxNDEsImp0aSI6ImJmNWEyNmI2LTA4ZWMtNDEyYS04MjE0LTNlNTgxZDc1N2Q2MyJ9.kYjpti7wP-2-htZBryuQQqETyYRFhN77pLHi4I2mSd6n04dhsengKNXPS3xqntLcYwfQQDHSWwtvzWDPb5zWglC4S6ppmOYIqCcVTuwvnEN1qJldPmtMgvfTFc5neg8f765zzrkCGvgsi5wZGgKbueCMelZAZqrMHMVkwAunKXq2kLjeEd2QVCiznXtB7tOHxD2yHjQzoUNGBflXt1OO9Ve0vNsXElMHkshkGxDaQDV5ouJRCQPAKjRHALRMCATDDLSpomHdwTybV8gvibTGBA8xQB1dp8qb92PL_izfiKreOpP9EDXMN_vkq7976jCk2zY9hoi26La7V0a8UmqNsw&clientId=992733577' failed: Error during WebSocket handshake: Unexpected response code: 503
[08:39:30.880] WARNING _app-0.js 17908:125 "WARNING (org.eclipse.che.ide.websocket.impl.BasicWebSocketEndpoint): Error occurred for endpoint wss://route458cf5up-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/wsagent?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlZTNza2c1ZXVyNm1sMHgxMyJ9.eyJ3c2lkIjoid29ya3NwYWNlZTNza2c1ZXVyNm1sMHgxMyIsInVpZCI6ImI1MzczNGFlLTNiNTMtNDU5Yi1iNjQwLWU1MzQwYjMzZjIwOSIsImF1ZCI6IndvcmtzcGFjZWUzc2tnNWV1cjZtbDB4MTMiLCJuYmYiOi0xLCJ1bmFtZSI6Im9zaW8tY2ktZTJlLTAwMiIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNTc4NTU5MTQxLCJpYXQiOjE1NDcwMjMxNDEsImp0aSI6ImJmNWEyNmI2LTA4ZWMtNDEyYS04MjE0LTNlNTgxZDc1N2Q2MyJ9.kYjpti7wP-2-htZBryuQQqETyYRFhN77pLHi4I2mSd6n04dhsengKNXPS3xqntLcYwfQQDHSWwtvzWDPb5zWglC4S6ppmOYIqCcVTuwvnEN1qJldPmtMgvfTFc5neg8f765zzrkCGvgsi5wZGgKbueCMelZAZqrMHMVkwAunKXq2kLjeEd2QVCiznXtB7tOHxD2yHjQzoUNGBflXt1OO9Ve0vNsXElMHkshkGxDaQDV5ouJRCQPAKjRHALRMCATDDLSpomHdwTybV8gvibTGBA8xQB1dp8qb92PL_izfiKreOpP9EDXMN_vkq7976jCk2zY9hoi26La7V0a8UmqNsw&clientId=992733577"
[08:39:30.975] SEVERE _app-0.js 16432 WebSocket connection to 'wss://route2yt5yxcj-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/pty?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlZTNza2c1ZXVyNm1sMHgxMyJ9.eyJ3c2lkIjoid29ya3NwYWNlZTNza2c1ZXVyNm1sMHgxMyIsInVpZCI6ImI1MzczNGFlLTNiNTMtNDU5Yi1iNjQwLWU1MzQwYjMzZjIwOSIsImF1ZCI6IndvcmtzcGFjZWUzc2tnNWV1cjZtbDB4MTMiLCJuYmYiOi0xLCJ1bmFtZSI6Im9zaW8tY2ktZTJlLTAwMiIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNTc4NTU5MTQxLCJpYXQiOjE1NDcwMjMxNDEsImp0aSI6ImJmNWEyNmI2LTA4ZWMtNDEyYS04MjE0LTNlNTgxZDc1N2Q2MyJ9.kYjpti7wP-2-htZBryuQQqETyYRFhN77pLHi4I2mSd6n04dhsengKNXPS3xqntLcYwfQQDHSWwtvzWDPb5zWglC4S6ppmOYIqCcVTuwvnEN1qJldPmtMgvfTFc5neg8f765zzrkCGvgsi5wZGgKbueCMelZAZqrMHMVkwAunKXq2kLjeEd2QVCiznXtB7tOHxD2yHjQzoUNGBflXt1OO9Ve0vNsXElMHkshkGxDaQDV5ouJRCQPAKjRHALRMCATDDLSpomHdwTybV8gvibTGBA8xQB1dp8qb92PL_izfiKreOpP9EDXMN_vkq7976jCk2zY9hoi26La7V0a8UmqNsw' failed: Error during WebSocket handshake: Unexpected response code: 503
[08:39:30.976] SEVERE https://route458cf5up-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/api/project-type - Failed to load resource: the server responded with a status of 503 (Service Unavailable)
[08:39:30.977] SEVERE https://route458cf5up-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/api/project-type - Failed to load resource: the server responded with a status of 503 (Service Unavailable)
[08:39:30.977] SEVERE https://che.openshift.io/osio-ci-e2e-002/e2e-0109-0837-5795-eoclc - Access to XMLHttpRequest at 'https://route458cf5up-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/api/project-type' from origin 'https://che.openshift.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
[08:39:30.977] SEVERE _app-0.js 17908:125 "ERROR (org.eclipse.che.ide.projecttype.ProjectTypeRegistryImpl): Can't load project types: org.eclipse.che.ide.commons.exception.ServerDisconnectedException"

```

**Comment by ljelinkova** [comment] 2019-01-09 09:47
It may be related to https://github.com/openshiftio/openshift.io/issues/4511

**Comment by ibuziuk** [comment] 2019-01-10 09:12
@ljelinkova could you provide `identity_id` of e2e users against which accounts this problem is reproducible ?

**Comment by ibuziuk** [comment] 2019-01-10 09:13
also, please provide links to jobs where the problem was caught

**Comment by ljelinkova** [comment] 2019-01-10 10:21
This is the last failed job: https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2143/console
User: osio-ci-e2e-002

I am not sure what you mean by `identity_id` - is it something you get from
```
curl -X GET "https://auth.openshift.io/api/users?filter[username]=osio-ci-e2e-002" |jq .
```

**Comment by ibuziuk** [comment] 2019-01-10 11:00
@jmelis @aditya-konarde @pbergene are there any known infrastructure issues on starter clusters ? Che currently fails to start for me on 2 cluster due to networking issues. Are we positive that https://redhat.service-now.com/help?id=rh_ticket&table=incident&sys_id=b173eceedb36a7c01e48cae3b9961912&view=ess has been fully resolved and not affect other clusters ? As I understand currently it is not possible to obtain any cluster specific health metrics ?

**Comment by ibuziuk** [comment] 2019-01-10 14:40
@rhopp @Katka92 @ScrewTSW could you please confirm that this problem only persists on particular clusters while not being reproducible on others cc: @ppitonak @ldimaggi

**Comment by Katka92** [comment] 2019-01-10 16:57
@ibuziuk I have run tests many times and the only failure it discovered is bayesian (known issue). I created new workspace from OSIO from the space that I created some time ago with vertx-http-booster from my repo and works fine. 
I'll investigate further tomorrow by manual testing directly from OSIO - I'll try reset environment and try it again.

**Comment by Katka92** [comment] 2019-01-11 07:49
Today I tried to reset environment and create new space + new workspaces and works fine. I've run tests with that account several times and haven't reproduced this issue. @rhopp @ScrewTSW could you give it a try please?

**Comment by rhopp** [comment] 2019-01-11 08:07
I'm not observing any troubles starting workspaces with my accounts on 2, 2a and 1a

**Comment by ibuziuk** [comment] 2019-01-11 08:19
@Katka92 @rhopp thanks for verification. Indeed, it looks like temp infra related issue.
@ljelinkova I see that the job has been stabilized, so please close the issue if the problem is no longer reproducible.

I have raised concerns about oso starter cluster health monitoring in the mailing thread and would probably raise it again on the next IC. The fact that we do not control cluster(s) state affects us dramatically in many cases

**Comment by ljelinkova** [comment] 2019-01-11 08:40
I've found one failed job on cluster 2 

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1392/console

User osio-ci-e2e-005

I agree that this is infrastructure problem but I'd like to have this issue open in case anybody else encounters it.

**Comment by ibuziuk** [comment] 2019-01-11 08:42
@ljelinkova please remove P1 label in this case

**Comment by ljelinkova** [comment] 2019-01-11 08:48
Done.

**Comment by pbergene** [comment] 2019-01-11 09:12
Note a tenant update was running on 2 in this timeframe, might be good for @MatousJobanek to know

**Comment by ljelinkova** [comment] 2019-01-14 07:59
We had more issues since yesterday morning, both on 1a and 2 clusters. Especially worrying is the cluster 2 since the tests failed 4 out of 6 last runs on this Che problem. 

1a
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2182/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/2183/console

2
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1408/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1409/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1411/console
https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1413/console

**Comment by ljelinkova** [comment] 2019-01-14 08:13
I am putting P1 label back since the errors are quite frequent.

**Comment by MatousJobanek** [comment] 2019-01-14 08:21
> Note a tenant update was running on 2 in this timeframe

that's true, however, the update was triggered only for `jenkins` namespaces, so it shouldn't influence che anyhow.

**Comment by jmelis** [comment] 2019-01-14 10:32
Since Jan 12, 15 jobs have run in starter-2 out of which 12 have failed.

- 7 failed because: git clone failed (import project): #1414, #1413, #1411, #1408, #1404, #1403, #1401
- 4 failed because: Build job did not run: #1412, #1410, #1405, #1400
- 1 failed because: Workspace failed to start (FailedMount): #1409

**Comment by ljelinkova** [comment] 2019-01-14 11:04
@jmelis For example for 1413, where do you see that git clone failed?

**Comment by Katka92** [comment] 2019-01-14 14:51
Today I was finally able to reproduce this issue. I saw some errors in logs which are probably related with flapping route issue. I've tested some cluster I have accounts on.

**starter-us-east-2** is probably hardly affected cluster, the flapping happened in 3/4 runs of the test and took a long time (it swapped many times between 503 and 401 response). You can see one example report at pastebin [1].

**starter-us-east-2a** is probably affected too but this issue was seen only 2/6 tests. Flapping lasted short time - it got back to 503 only once, then only 401 was returned.

**starter-us-east-1a** is probably in the same state as cluster 2. Flapping was seen every test run 4/4 even it's intense changed.

Currently I don't have any testing account on ```b``` clusters, so I can not verify the status here.

There is a script I wrote to test this flapping route issue [2]. If you want to try that and have some issues with this script, please let me know. Please notice that url is hardcoded to che.openshift.io (production env).

If you want me to test something more deeply or to test something else, please let me know.

[1] https://pastebin.com/1z5QmuRD
[2] https://github.com/Katka92/rh-che/blob/test_flapping_route/test.sh

**Comment by jmelis** [comment] 2019-01-14 15:39
@ljelinkova if you look at this screenshot, you will see that the workspace pod is running, but that there are no imported projects. I'm assuming that is because the git clone failed, or wasn't even called, but I could be wrong about what exactly happened. What I believe is certain though is that the pod is running and that this has nothing to do with route flapping.

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-2-released/1413/04-01-che-failed.png

**Comment by jmelis** [comment] 2019-01-14 15:41
@Katka92 did the report you labeled as [1] never return 200?

**Comment by riuvshin** [comment] 2019-01-14 15:41
@Katka92 I can't reproduce this on 1a and 2 with this:
https://gist.githubusercontent.com/jfchevrette/fdbd7dd2ec34130b91cb0af51baab5ee/raw/5787223884278bd25f079deb37bc90f9c75b698a/test-oso-route.sh

and from what I've seen is that test starting to receive 200s not right after route is published
but in some time, which I think is fine
but once it is set it was always giving me 200s

**Comment by jmelis** [comment] 2019-01-14 15:42
@Katka92 also, the report you labeled as [1], does it correspond to a specific jenkins job? If so, which one?

**Comment by ibuziuk** [comment] 2019-01-14 15:47
@jmelis @riuvshin guys, don't you think we need to raise the route flapping issue with ops and get clarifications about the cluster(s) health at the point of time? AFAIK those kind of issues should be caught by monitoring not QAs - https://github.com/openshiftio/openshift.io/issues/4511#issuecomment-434693373

**Comment by jmelis** [comment] 2019-01-14 16:14
@ibuziuk we totally would raise this with ops, but @riuvshin tried to reproduce it himself and he couldn't. We are working on it still, though.

**Comment by ibuziuk** [comment] 2019-01-14 16:22
@Katka92 I believe you have used che specific samples for reproducing the problem. Are you able to reproduce it on some synthetic sample as it was done before -  https://github.com/openshiftio/openshift.io/issues/4511#issuecomment-434633713

**Comment by ibuziuk** [comment] 2019-01-14 16:36
@jmelis @riuvshin FYI I was able to repro route flapping on `us-east-2` via https://github.com/ibuziuk/route-flapping/tree/master/resources 
Also, noticed that it takes ~ 30 second for route to become accessible after pod  startup which does not look normal IMO

**Comment by Katka92** [comment] 2019-01-15 06:46
@jmelis I don't think this issue is related with git clone at all. Yesterday I was able to reproduce that issue (that project was not cloned to workspace) and I found this error in logs [1].

The script returns only 401 (not authorized) but I don't think it is problem. Even if it would return 200, it would jump between 200 and 503. If you think this is somehow affecting test, I can rework it. I'm not sure if it will bring some value.

I've shared the script I've used for testing that. I've run it from my local computer, so it is not related with any jenkins job. 

@riuvshin Yes, today I tried it three times against 2 and it fails once. There is output from the test [2]. But as you can see - this issue is quite intermittent, even @ljelinkova wrote that the situation got better and few days after it got back.

[1] https://pastebin.com/9SnE3Ui5
[2] https://pastebin.com/rDsNPuik

**Comment by ljelinkova** [comment] 2019-01-15 06:48
@jmelis If you look into the original bug description, you can see in attached browser logs this line:

`https://route458cf5up-osio-ci-e2e-002-che.9a6d.starter-us-east-1a.openshiftapps.com/api/project-type - Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

So for me it looks as a pretty good evidence that the problem is with route.

**Comment by ljelinkova** [comment] 2019-01-15 07:03
BTW, we have one failed e2e run on 1b cluster too:

https://ci.centos.org/job/devtools-test-e2e-openshift.io-smoketest-us-east-1b-released/1417/console

**Comment by Katka92** [comment] 2019-01-16 13:17
@jmelis @riuvshin @pbergene Today I've tried to verify other issue and I needed to start workspace 5 times on prod cluster 2 to have the project imported and shown. Is there some progress with that issue please? It is quite slowing me down.

**Comment by Katka92** [comment] 2019-01-16 13:33
This search in kibana [1] shows all occurrences of "Application not available" which is contained in log when project is not loaded into workspace. This search is for last 24 hours. Maybe it can help you somehow.

[1] https://logs.dsaas.openshift.com/goto/3c08ed5a51c28b753b4669a08db1ae82

**Comment by ibuziuk** [comment] 2019-01-16 19:44
@pbergene @jmelis @riuvshin related HK issue - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2520 
Long route expose is the reason of the problem

**Comment by ibuziuk** [comment] 2019-01-22 12:08
@ljelinkova could you possibly provide info about time required for route to be accessible after exposure with some synthetic sample e.g.  [1] for each oso cluster (last time I tried it on `2a` it was just a couple of seconds and more than a minute on `2`, but the situation might have changed)


[1] https://github.com/ibuziuk/route-flapping/tree/master/resources

**Comment by ljelinkova** [comment] 2019-01-23 13:06
@ibuziuk I'll look into that

**Comment by ibuziuk** [comment] 2019-01-23 13:14
@ljelinkova thanks, I did a quick tests today.  Route flapping is detected on us-east-2 - first time route becomes accessible in 37 seconds after pod starup. us-east-2a no route flapping but route becomes accessible in 18 seconds. Would be interesting to get data from another account and from `1a` cluster (I do not have account to this cluster)

**Comment by ibuziuk** [comment] 2019-01-23 13:31
should be pretty easy to do:
```
oc apply -f route.yaml
./curl.sh
```

**Comment by ljelinkova** [comment] 2019-01-23 14:10
What exactly do I need to run this? Simply cloning your repo and running the commands did not work, I got  `error: the path "route.yaml" does not exist`

**Comment by ljelinkova** [comment] 2019-01-23 14:45
Sorry, typo :-)

**Comment by ibuziuk** [comment] 2019-01-23 15:30
yeah, you would need to change the curl code [1] a bit based on namespace where route is created

[1] https://github.com/ibuziuk/route-flapping/blob/master/resources/curl.sh#L2

**Comment by ibuziuk** [comment] 2019-01-24 12:05
@rhopp btw, this might super useful for status page - https://github.com/openshiftio/openshift.io/issues/4695#issuecomment-456800940 maybe need to sync with e2e QA in order to avoid duplicate effort ?

**Comment by ljelinkova** [comment] 2019-01-25 13:38
We added the following script into our smoketest

https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/scripts/routes/test-routes.sh

You can now see the output of the script in job's artifacts under the name `test-routes.txt`, e.g

http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/5469/test-routes.txt

Note that `real` entry at the end of the script - that is how long it took to access the route (measured uning `time`)

This is simple output that enables to see how long it took to access the route. If you'd like to change the output or to report the results somewhere, we can do it.

**Comment by riuvshin** [comment] 2019-01-28 08:44
@ljelinkova @Katka92 can you please rerun tests? ticket now is closed so let's make sure we can confirm that issue is gone.

**Comment by ibuziuk** [comment] 2019-01-28 10:45
@riuvshin I will let QA to provide statistics from periodic jobs, but according to manual tests we failure rate is still very high on 2 / 2a.

**Comment by ibuziuk** [comment] 2019-01-28 10:56
Some quick tests against 2 cluster:
1. There are quite a few `ErrImagePull` but eventually image is pulled and container started

![image](https://user-images.githubusercontent.com/1461122/51831677-f89d5000-22f2-11e9-902b-24a636a9ce67.png)
![image](https://user-images.githubusercontent.com/1461122/51831737-2d110c00-22f3-11e9-845f-c0ebc87d65a4.png)

2. It takes ~35 seconds for route to be accessible after container startup. Route flapping is not detected

**Comment by ibuziuk** [comment] 2019-01-30 10:59
2a startup failures related to - https://github.com/openshiftio/openshift.io/issues/4735

**Comment by ibuziuk** [comment] 2019-01-31 12:42
2a issue was closed, but:

- There is still route flapping
- first time route becomes accessible after ~1 minute (route becomes stable after 70 - 80 secs)

So, in reality infra issues are still there

**Comment by garagatyi** [comment] 2019-02-05 09:13
Starting Che workspaces on prod-preview against 2a cluster. Workspace starts, but the route is not available, so here is what shown:
![image](https://user-images.githubusercontent.com/1851863/52263119-fbbdbf00-2936-11e9-8a68-3eab21b948bb.png)

**Comment by ibuziuk** [comment] 2019-02-05 09:49
just tested and nothing have changed since my last on 2a cluster [1]
@pbergene any updates on that ? 

[1] commenthttps://github.com/openshiftio/openshift.io/issues/4695#issuecomment-459330261

**Comment by ScrewTSW** [comment] 2019-02-13 16:27
This error has surfaced again.
https://github.com/redhat-developer/rh-che/issues/1248

**Comment by ljelinkova** [comment] 2019-02-21 11:56
@ibuziuk  This issue has been open for over a month and it is still occurring.  Have you considered to (maybe temporarily) accept the fact that the route takes long to create and modify Che to wait for a longer time?

**Comment by ibuziuk** [comment] 2019-02-21 12:01
@ljelinkova e2e tests should not be affected by routes as long as timeout is 10 minutes. My opinion is that is infrastructure is not good enough for users but good enough for tests to pass and I told about that on IC to @ppitonak @rhopp . Basically, I do not understand why e2e tests are failing on che if manually I can not reproduce this issue

**Comment by ljelinkova** [comment] 2019-02-21 12:10
@ibuziuk Tests wait until the project is shown but it is never shown. I guess it would be possible to reload page after 5 minutes and it should work - but that is not something a user would do. 

The tests always fail during detecting the project type so I think that it would be worth to try to fix that part of the code to wait / retry the API call. 

```
[06:45:19.135]   req_id:1000000459.1471   [RESPONSE]   503   Service Unavailable   https://route0r63fdqz-osio-ci-e2e-002-preview-che.b542.starter-us-east-2a.openshiftapps.com/api/project-type
```

As for why you was not able to reproduce - the tests run 20x per day on production in different times so they are more probable to catch any infra glitch as any manual tests. Besides, I guess @rhopp  was able to reproduce manually and @ppitonak saw that issue also manually.

**Comment by ppitonak** [comment] 2019-02-21 12:14
@ibuziuk I'm able to reproduce it manually every time

1. open https://prod-preview.openshift.io
2. log in
3. create a new space
4. create a new codebase
5. select mission `REST API Level 0` and runtime `Spring Boot`
6. select whatever pipeline you like (I recommend the shortest one)
7. on last screen of Launcher, clikc "Return to your Dashboard"
8. open Codebases page
9. click `Create workspace`
10. click `Open`
11. wait for workspace to start

![che_workspace](https://user-images.githubusercontent.com/445100/53168158-52372880-35da-11e9-893a-78ec92373547.gif)

**Comment by ibuziuk** [comment] 2019-02-21 12:15
@ppitonak against which cluster(s) are you able to reproduce it ?

**Comment by ppitonak** [comment] 2019-02-21 12:18
@ibuziuk see the steps in my last coment... I reproduced it 2 minutes ago on prod-preview, i.e. us-east-2a

**Comment by Katka92** [comment] 2019-02-21 13:29
Hi guys, there is another way how it can be reproduced:
- create workspace via dashboard but don't start it
- open workspace via direct link ( https://che.prod-preview.openshift.io/user/workspace_name )

I was able to reproduce it on prod-preview now 4/5 times.
I am able to reproduce it on 2a almost every try. It happens on cluster 2 too - today my PR failed on that [1]. But I was not able to reproduce it manually. There is a screenshot showing that project is not imported [2].

One more thing I would like to say is that it is not affecting only e2e tests - our periodic tests on 2a cluster are failing too. You can see log here [3] and screenshots here [4].

[1] https://ci.centos.org/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1169/console
[2] https://ci.centos.org/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1169/console
[3] https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/194/console
[4] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/194/screenshots/

**Comment by ibuziuk** [comment] 2019-02-22 08:37
@Katka92 thanks for details, so far I was not able to reproduce manually against `us-east-2`, but I was able to repro against `2a`
@ppitonak @ljelinkova until infrastructure is fixed could we add workaround with page refresh on e2e side ?

**Comment by ppitonak** [comment] 2019-02-25 09:41
@ibuziuk after discussion with @ljelinkova we decided not to implement a workaround in e2e test. This is a production service and we cannot require our users to refresh the page.

There are two possible ways how to deal with this issue:
1. (preferred) you fix the issue in Che
2. we completely delete the che test from e2e smoketest if you don't care about it

@rhopp could this affect CRW customers if their infra had similar problems?

**Comment by ibuziuk** [comment] 2019-02-25 09:47
@ppitonak this issue only occurs when infrastructure is not in a proper state (e.g. route issue). We have no capacity to fix this for che 6 and add some re-try logic, since che 6 is going to be deprecated in a short run (che 7 beta is released this week). Taken into account that this problem is not reproducible on clusters which are in a proper state, adding workaround with page refresh sounds like a relevant trade-off until infra is fixed [1]. 

[1] https://redhat.service-now.com/help?id=rh_ticket&table=incident&sys_id=03c4c19cdbe36780981c8a7239961936&view=ess

**Comment by ibuziuk** [comment] 2019-02-25 10:06
> 2. we completely delete the che test from e2e smoketest if you don't care about it

@ppitonak and please do not say that I do not care, since I do. The situation with infrastructure affects pretty much every single service and, we trying to bring it and resolve with to ops + find some SLA based solution. Util this is resolved, I hope we could be more flexible with the decisions regarding support of the existing codebase. In the current situation I do believe the page refresh could be treated as a know issue.

**Comment by ibuziuk** [comment] 2019-03-04 14:20
@ppitonak @ljelinkova FYI the following workaround has been applied on rh-che funtional test side - https://github.com/redhat-developer/rh-che/pull/1273 
Please, consider adding it to e2e side until infra is fixed

**Comment by Katka92** [comment] 2019-04-23 06:50
I can see this happening again. E.g. https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/508/console on 20th April.

**Comment by Katka92** [comment] 2019-04-29 05:29
Seen again https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/333/console on 26th April.

**Comment by ibuziuk** [comment] 2019-08-01 07:40
Closing, since currently there is no route flapping / long exposure for quite a long period of time:

![image](https://user-images.githubusercontent.com/1461122/62274526-57798880-b440-11e9-85b7-65a7ab43b4b3.png)

**Closed by ibuziuk** 2019-08-01 07:40 UTC
Labels: SEV1-urgent, area/che, area/e2e-tests, priority/P1, team/service-delivery, type/bug
