### ISSUE TITLE
Unidling jenkins sometimes do not unidle content-repository

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#3469] opened 2018-05-05 15:57 UTC
If I hit jenkins through the cluster route (ex: jenkins-tenantname-jenkins.8a09.starter-us-east-2.openshiftapps.com)
- Jenkins is unidled, content-repo does NOT
    - Openshift wakes up the idled DC behind the route, which is jenkins in this case
    - Openshift doesn't know that the content-repo DC should also unidle, content-repo DC has no relation to the jenkins route.
- Once jenkins is up, content-repo is still not running
- Once a build is started, jenkins spins up a slave which then eventually try to hit http://content-repository toward the end of the build process which THEN causes openshift to wake up the content-repo DC (because we're trying to reach the content-repo app through it's service endpoint)
- content-repo take about 10s to start and get to a Running state, this may however be still too long for the build

- If I connect to jenkins through the proxy at 'jenkins.openshift.io', both jenkins and content-repository are unidled :+1: 

```
# oc -n tenantname-jenkins rsh po/jenkins-1-z8pfz curl http://content-repository/
curl: (56) Recv failure: Connection reset by peer
```

**Comment by containscafeine** [comment] 2018-05-06 17:16
Hey @jfchevrette, thanks for all the information, very helpful :+1: 

So, IIUC, here's what happening underneath -
- hitting `jenkins.openshift.io` talks to jenkins-proxy which talks to jenkins-idler, which unidles both jenkins and content repo
- hitting jenkins directly via route/service without going through jenkins-proxy (and hence skipping jenkins-idler), causes OpenShift (and not jenkins-idler) to unidle only the jenkins DC.
- content repo is only unidled by OpenShift when it receives traffic, which is later via slave

So, if we want both, Jenkins and Content repository to be up at the same time, then we can take the following approaches -
1. All the requests for Jenkins must go via jenkins-proxy (and not directly), this will make sure that both, jenkins and content repo, are up and running
2. We serialize the execution of jenkins and content repo by adding a hard dependency on jenkins to _only_ start once content repo is up and running (via adding an init container to jenkins DC)
3. When we send requests directly to Jenkins, we simultaneously send a ping to content repository so both of them are unidled at the same time

I think 1. would be the ideal solution, but 2. should work for now.
I'll send a PR for 2.

WDYT @kbsingh @jfchevrette @maxandersen @sthaha @kishansagathiya?

**Comment by containscafeine** [comment] 2018-05-06 18:55
I've sent a PR to update the Jenkins' Kubernetes deployments to include an init container that waits for content-repository to be up - https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/91. This _should_ send traffic to the content-repository pod and OpenShift should unidle it.

I don't understand how half of this works, so I'll need help reviewing the PR and checking if it solves the problem, if at all.

**Comment by containscafeine** [comment] 2018-05-06 19:41
I can confirm that the fix at https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/91 works for me -

Steps to test -
1. Idle both content-repository and jenkins
`oc idle jenkins content-repository`
2. Send a request to Jenkins route -
`curl -L jenkins-username-jenkins.xyz.openshiftapps.com`
3. Wait for the :tada:, Jenkins pod will start the init container which will generate traffic to content-repository which will be unidled. Once content-repository is up, the init container will go down and Jenkins will be started.

**Comment by piyush1594** [comment] 2018-05-07 10:00
Hey,

I tried doing the following steps (without the concaf's patch) - 

1. Idle both content-repository and jenkins
`oc idle jenkins content-repository`
2. Send a request to Jenkins route -
`curl -L jenkins-username-jenkins.xyz.openshiftapps.com`

What i have observed is content repository sometimes get unidled and sometimes not. I tried it without concaf's patch

**Comment by containscafeine** [comment] 2018-05-07 10:03
I was testing this out with @piyush1594 and looking at logs from prod, so this is what's happening.
Idler _is_ trying to un-idle content-repository when Jenkins comes up from the request to the route, but it's not un-idling reliably. The un-idle request to content-repository fails about 50 % of the times with errors saying - `"msg":"Skipping un-idle request since max retry count has been reached.","time":"2018-05-07T09:53:55Z","username":"pgarg-1"`.
So, for now, as a hack, we need the fix at https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/91 for content-repository to get un-idled reliably.

When Idler decides to work, I get the following logs when Jenkins is un-idled from the traffic at the route -
```
{"attempt":"(3/3)","component":"user-idler","id":"redacted","level":"info","msg":"About to un-idle jenkins, Reason: DoneBuild BuildName:test-tenant-again-3 Last:2018-05-05 18:54:27 +0000 UTC","time":"2018-05-07T09:53:55Z","username":"pgarg-1"}
{"component":"openshift-client","level":"info","msg":"Un-idling jenkins in pgarg-1-jenkins","time":"2018-05-07T09:53:55Z"}
{"attempt":"(3/3)","component":"user-idler","id":"redacted","level":"info","msg":"About to un-idle content-repository, Reason: DoneBuild BuildName:test-tenant-again-3 Last:2018-05-05 18:54:27 +0000 UTC","time":"2018-05-07T09:53:55Z","username":"pgarg-1"}
{"component":"openshift-client","level":"info","msg":"Un-idling content-repository in pgarg-1-jenkins","time":"2018-05-07T09:53:55Z"}
```

**Comment by rupalibehera** [comment] 2018-05-07 13:28
Hey @containscafeine , 
I tested this out few more times and this looks good to me.
- `oc idle Jenkins content-repository`
- created a quickstart
- and checked logs `oc logs jenkins-8-fv2gg -c content-repository-init` 
- Jenkins and content-repository both un-idled properly.
This PR https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/91 is good to go.

**Comment by rupalibehera** [comment] 2018-05-07 15:45
https://github.com/openshiftio/saas-openshiftio/pull/874

**Comment by pradeepto** [comment] 2018-05-08 03:09
We should close this now?

**Comment by pradeepto** [comment] 2018-05-08 03:09
Closing as this is in prod now.

**Closed by pradeepto** 2018-05-08 03:09 UTC
Labels: SEV2-high, area/architecture/build, priority/P0, team/build-cd, type/bug

**Comment by containscafeine** [comment] 2018-05-28 10:46
@jfchevrette what is the use case where we're having to hit the route directly and not go via the proxy? That would be ideal approach and changing the implementation there would be the right way forward.
