### ISSUE TITLE
500 error while retrieving spaces

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2546] opened 2018-03-12 16:49 UTC
<img width="1427" alt="screen shot 2018-03-12 at 10 16 55 pm" src="https://user-images.githubusercontent.com/15967765/37297302-4e512ff6-2643-11e8-866a-1cc57ae14704.png">
<img width="1241" alt="screen shot 2018-03-12 at 10 16 41 pm" src="https://user-images.githubusercontent.com/15967765/37297307-57123ed2-2643-11e8-8667-8252c11571ce.png">

**Comment by andrewazores** [comment] 2018-03-12 17:04
Looks like a probable duplicate of https://github.com/openshiftio/openshift.io/issues/2360

**Comment by joshuawilson** [comment] 2018-03-12 19:19
@krishnapaparaju what are the steps to reproduce this?

**Comment by aslakknutsen** [comment] 2018-03-25 11:29
Duplicate https://github.com/openshiftio/openshift.io/issues/2724

**Closed by aslakknutsen** 2018-03-25 11:29 UTC
Labels: SEV2-high, area/deployments, area/notifications, team/platform, type/bug
