### ISSUE TITLE
Unauthorized to promote build

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4455] opened 2018-10-18 06:43 UTC
Promote build throws 401
![screenshot from 2018-10-18 12-15-09](https://user-images.githubusercontent.com/10185999/47135853-7e126c80-d2cf-11e8-9602-5e530623eb52.png)

**Comment by piyush-garg** [comment] 2018-11-19 12:39
Adding team UI here as seems like there. Feel free to remove the label if its not that. Thanks

**Comment by joshuawilson** [comment] 2018-11-19 13:49
I just tried it and it works with not error. I would expect that you were logged out (timed out) and didn't know it. That makes this more of a "did you tell the user they were logged out instead of silently throwing a 401?" kind of issue.

@sbose78 @alexeykazakov do you know if we have something that is currently tracking this?

**Comment by alexeykazakov** [comment] 2018-11-19 23:38
I don't know why forge threw 401 here. Maybe the token was expired maybe something else. Something for the build team to investigate. If the token was expired then it's the end service responsibility to handle it gracefully and pop it up to UI properly. There is nothing Auth can help with.

**Comment by joshuawilson** [comment] 2018-11-25 01:36
If you can reproduce it then we might find a way to insulate the user. I'm removing UI and waiting for Build.

**Comment by sthaha** [comment] 2018-11-27 12:59
Seems more like a platform issue that anything build related hence tagging `team/platform`

**Comment by alexeykazakov** [comment] 2018-12-03 23:39
If 401 is returned by auth service it doesn't mean it's a bug in Auth service. Please investigate this issue on the build side (since it's reproducible in build) and add more details to the issue. I'm closing it until further details are provided.

**Comment by alexeykazakov** [comment] 2018-12-03 23:39
If 401 is returned by auth service it doesn't mean it's a bug in Auth service. Please investigate this issue on the build side (since it's reproducible in build) and add more details to the issue. I'm closing it until further details are provided.

**Closed by alexeykazakov** 2018-12-03 23:39 UTC
Labels: SEV3-medium, area/auth, priority/P4, team/build-cd, type/bug
