### ISSUE TITLE
Planner - display format is gone

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#3650] opened 2018-05-25 11:44 UTC
I wanted to move Label column to the right most because it is occupying a lot of prime space.  
Here is what I did - 
1.  Clicked on little settings icon, next to "Add and Open" button
2.  Moved Label from right to left and clicked on X icon.
3.  Then, the page refreshed and Label column is gone.
4.  Again clicked on Settings icon and moved Label from left to right - and clicked on X icon.
5.  Screen shot of what I see is here -- 
<img width="1276" alt="screen shot 2018-05-25 at 5 09 58 pm" src="https://user-images.githubusercontent.com/32661994/40542628-8054ea80-603e-11e8-97f2-fc0446322573.png">

**Comment by joshuawilson** [comment] 2018-05-25 20:37
I can't reproduce this.

**Comment by aptmac** [comment] 2018-05-25 20:52
Neat! Here's a reproducer that seems to work:

1. Open the settings panel, and move the label attribute to the left.
2. Refresh the page.
3. Open the settings panel, and move the Label attribute back to the right.

And the planner now looks like:
![table-format](https://user-images.githubusercontent.com/10425301/40565613-3f89ada4-603b-11e8-9a36-f6144c2008ab.png)

Here's a gif of it happening:
![broken-planner-table](https://user-images.githubusercontent.com/10425301/40565819-0625e46e-603c-11e8-834b-92905234c493.gif)

**Comment by rgarg1** [comment] 2018-05-28 04:02
The issue is reproducible using the steps provided by @aptmac.

**Comment by bartoszmajsak** [comment] 2018-08-10 20:27
For me that's now permanent view

**Comment by rgarg1** [comment] 2018-08-13 05:59
@stevengutz @nimishamukherjee Would this still be a P4?

**Comment by stevengutz** [comment] 2018-08-13 10:28
Yeah, I think it's still P4.  This doesn't mean we can ignore, only that it is normal priority.

**Comment by nimishamukherjee** [comment] 2018-08-21 06:43
@Veethika note how @sivaavkd is using select/deselect column to order the table...interesting

**Comment by SMahil** [comment] 2018-08-21 07:54
Closing as this issue has been fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2759

**Closed by SMahil** 2018-08-21 07:54 UTC
Labels: SEV3-medium, area/planner, priority/P4, team/planner, type/bug
