### ISSUE TITLE
Aw, snap! Performance issues ...

### ISSUE THREAD

**Issue by tinakurian** [openshiftio/openshift.io#4060] opened 2018-07-24 04:32 UTC
It is possible to get planner into an "Aw, snap!" situation. This can be done by spamming the business value field with a ton of text. 

At first, the performance starts to take a hit. When more text is added performance will grind to a halt and the page will eventually crash when attempting to view/edit in full detail view. 

The business value field is where performance issues are easily exposed. However, with a bit more effort, the same issues can be seen by spamming the description field as well. When spamming the description field with text, the performance degradation can be only seen when attempting to add more text to the description. 

Ideally, all text fields should contain a maximum length. It Github, a comment can be no larger than 65536 characters. Planner should implement a maximum as well. 

![unresponsive](https://user-images.githubusercontent.com/40298444/43117068-e66cb4d8-8ed8-11e8-8653-f772f0884c06.png)

![awsnap](https://user-images.githubusercontent.com/40298444/43117072-eb23e92e-8ed8-11e8-8b78-967acd05a71a.png)

![githubmaxlength](https://user-images.githubusercontent.com/40298444/43117073-ef521084-8ed8-11e8-9a31-2760c052fb34.png)

**Comment by nimishamukherjee** [comment] 2018-07-25 05:18
There is a larger discussion around character restrictions for various planner fields #1595 . This defect would get fixed when 1595 is taken up.

**Comment by tinakurian** [comment] 2018-07-25 18:14
Thanks @nimishamukherjee & @rgarg1 

I had a look at  #1595 and noticed this document which seems to indicate that we don't plan to put a limit for the description field: https://docs.google.com/presentation/d/1x1iJyuqbqPedxhnduUASiJkRogh1RA8qVLIcJEGFjM0/edit#slide=id.g35442f53a6_1_86

I think for the performance reasons outlined in this defect we should implement some sort of a large character limit (similar to what github does).

**Comment by rgarg1** [comment] 2018-07-26 06:08
I agree with @tinakurian here. The limit could be large enough to not cause a constraint to the user, but we need definitely need one. In the absence of a limit, we run a risk of a DoS attack too.

**Comment by joshuawilson** [comment] 2018-10-31 16:34
That is not how a DoS attack works. 

However it does make for a poor user experience and should be fixed. 

Closing, please add more anything missing to the:
Duplicate of  #1595

**Comment by joshuawilson** [comment] 2018-10-31 16:34
Duplicate of #1595

**Closed by joshuawilson** 2018-10-31 16:34 UTC
Labels: SEV3-medium, area/planner, priority/P3, team/planner, type/bug
