### ISSUE TITLE
Planner work items trees are not properly shown

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#2582] opened 2018-03-14 15:40 UTC
I created at least 3 level work items trees for several Scenarios, Experiences and Requirements and selected "Show tree" option. Then I went over these 3 categories and the behaviour was following: a) for Requirements there are all WI levels shown, b) for Experiences there are only 2 levels displayed c) for Scenarios there is no tree shown. I had to manualy unfold each tree.

Expected behaviour: All WI trees shall be shown with "Show tree" option selected.

See below:
![wi-req](https://user-images.githubusercontent.com/26871874/37412984-4ba82930-27a6-11e8-8467-760298749d0f.png)
![wi-exp](https://user-images.githubusercontent.com/26871874/37412992-4f906a76-27a6-11e8-81ff-36f7dfc0588c.png)
![wi-scen](https://user-images.githubusercontent.com/26871874/37412999-5351e914-27a6-11e8-90b5-5750266f5e9d.png)

**Comment by Veethika** [comment] 2018-10-05 07:46
@pkettman This is an intended behavior. Only all the parents of a matching work-item are shown expanded. If all the trees are expanded all the time a lot of screen space would be wasted on non-meaningful data. And at any point of time, the user can expand a tree manually to view.
Please close the issue as this is an intended UX behaviour.

**Comment by pkettman** [comment] 2018-10-05 09:00
@Veethika It's quite confusing behavior, especially as the Show Tree checkbox is share for all 3 WI types and folding unfolding is different per each. Is there a requirement/user story/design document requiring such a behavior? Thanks

**Comment by Veethika** [comment] 2018-10-05 11:10
@pkettman I'll find the issue and get back, since this work was done before I started to work with planner.
IMO this approach takes care of 2 situation:
1) There could be multiple branches to the children of a work-item for multiple levels, but only one way up to the parent list. Hence displaying all the parents is possible, but displaying all the child items might bring in many more discrepancies and incoherency. 
2) When a user queries for a work item, and opts to look at the result in tree-view, they should be able to see maximum meaningful results on the screen
@sahil143 please verify

**Comment by sahil143** [comment] 2018-10-08 11:51
> There could be multiple branches to the children of a work-item for multiple levels, but only one way up to the parent list. Hence displaying all the parents is possible, but displaying all the child items might bring in many more discrepancies and incoherency.
When a user queries for a work item, and opts to look at the result in tree-view, they should be able to see maximum meaningful results on the screen

@Veethika I agree with both of your points. And to add more,  we dont show all the children expanded because for an applied filter user might want to see only the matching item and track its parent. A workitem can have multiple children which might not match the current filter and as @Veethika said showing might lead to more discrepencies and incoherency.

**Comment by Veethika** [comment] 2018-10-08 11:52
@pkettman ^does this answer your query?

**Comment by pkettman** [comment] 2018-10-08 12:06
@Veethika on first experience it looked to me as confusing and not intuitive, but I could imagine situations with many children work-items it could be beneficial. So I am going to close this ticket. Thanks for your replies.

**Closed** 2018-10-08 12:07 UTC
Labels: SEV3-medium, area/UX, area/planner, priority/P4, team/planner, type/bug
