### ISSUE TITLE
[Che-MT] Workspaces are not deleted when cleaning account (profile -> update profile -> reset env)

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#1614] opened 2017-12-11 11:06 UTC
### Description
After reset osio account and delete the spaces - the workspaces are not deleted.

### Steps to repoduce
1. Create a space, go to codebase and open workspace
2. Go to your profile, and reset your environment - all spaces will be deleted
3. Create a new space, go to codebase and open the che workspace
4. Go to Che dashboard to see the list of workspaces you have

### Expected behaviour
User should see only the workspace for the latest space he created.

### Current behaviour
User can see all previously created workspace, including the ones from the deleted spaces.

**Comment by ashumilova** [comment] 2017-12-11 12:07
Could be related with https://github.com/fabric8-services/fabric8-wit/issues/1749

**Comment by ldimaggi** [comment] 2017-12-11 12:53
Is the Che ppod actually being dropped/restarted by the env reset?

**Comment by ibuziuk** [comment] 2017-12-11 13:40
@ldimaggi single-tenant  - yes, multi-tenant no

**Comment by davidfestal** [comment] 2018-04-06 12:10
The implementation on the Che-OSIO side has been done and explained in issue https://github.com/redhat-developer/rh-che/issues/481.

The new `cleanWorkspaces` REST endpoint of the `che-tenant-maintainer` dsaas service should now be called by the `reset environment` action of the tenant service, as described with details in [this comment](https://github.com/redhat-developer/rh-che/issues/481#issuecomment-379233302)

**Comment by l0rd** [comment] 2018-04-25 14:58
I am raising this one as a `priority/P0` and adding `team/platform`. As @davidfestal explained in the previous comment we have setup a `che-tenant-maintainer` endpoint to clean workspaces data. So now it's just a matter to call this API when resetting a user osio account.

**Comment by xcoulon** [comment] 2018-04-26 08:00
thanks @davidfestal and @l0rd, I'm going to take care of the call to the new endpoint, now :)

**Comment by davidfestal** [comment] 2018-04-26 08:38
Great @xcoulon !

Just my 2 cents about this:

When starting playing with it locally, I had added the following comments at the line where I would have inserted the call to the endpoint, which is [__just after line 28 in `clean_tenant.go`__](https://github.com/fabric8-services/fabric8-tenant/blob/936dfcf58a0d634c1c66a0898b131a37f084fc02/openshift/clean_tenant.go#L28):

```
                ....
		go func(namespace string, objects []map[interface{}]interface{}, opts ApplyOptions, remove bool) {
			defer wg.Done()

			// if namespace ends with "che"
			// then
			//     get the OSIO token
			//     get the Identity Id
			//     get the request Id
			//     call the REST endpoint and wait for the result

			var clean cleanFunc = executeCleanNamespaceCMD
                ....
```

Just in case it helps...

**Comment by l0rd** [comment] 2018-04-26 15:56
@xcoulon makes sense and should address #3004 too.

**Comment by ibuziuk** [comment] 2018-04-27 14:43
@l0rd @xcoulon the problem is that when workspace is deleted pvc with project file is not cleaned.
@davidfestal do you think it will be possible to expose endpoint on che-maintainer side that would allow to clean workspace by `name` / `id` - e.g.`http://che-tenant-maintainer:8080/cleanWorkspace/{workspaceName} ` 

It could be called by che-started asyncronously after workspace deletion than

**Comment by ibuziuk** [comment] 2018-04-28 08:06
@l0rd yeah, good point, I'm not sure this is done on wsmaster side - need to check

**Comment by joshuawilson** [comment] 2018-04-30 14:44
@l0rd is your team working on this? I don't think Plaform will get it finished this week.

**Comment by ibuziuk** [comment] 2018-04-30 14:55
@joshuawilson it looks like the only thing left is to check if pvc is cleaned after workspace deletion and afaik @davidfestal is checking this currently.

**Comment by davidfestal** [comment] 2018-04-30 14:56
I'm testing a fix

**Comment by davidfestal** [comment] 2018-04-30 16:56
> the problem is that when workspace is deleted pvc with project file is not cleaned.

PR https://github.com/redhat-developer/rh-che/pull/660 fixed this OSIO problem and the fix is available on prod-preview. I just tested it with the removal of 30 workspaces in a single operation: the PVC-cleaning PODs were correctly started asynchronously and ran sequentially in my `prod-preview` user account. Finally no error was visible in the Che server logs.

**Comment by joshuawilson** [comment] 2018-04-30 17:58
Nice work guys!

**Comment by ibuziuk** [comment] 2018-05-04 16:13
@ldimaggi @slemeur fix is on prod. Could you please verify & close

**Comment by ibuziuk** [comment] 2018-05-04 17:00
@ScrewTSW if you have sometime would be nice to verify ;-)

**Comment by slemeur** [comment] 2018-05-06 07:01
@davidfestal : I tested on prod and it did not work for me.

2 things I tested:
- The scenario descride in the issue
- Deletion of a single space from "My Spaces" page.

In both cases, the workspaces were not cleanup on my side

**Comment by davidfestal** [comment] 2018-05-07 09:36
@slemeur 

I just tested on prod from the dashboard (to create / open a workspace and then delete it), and it appears that the PVC cleaning is tried but fails since the PVC cleaning POD cannot be created.
I get the following events in the Openshift monitoring of my Che account:
```

11:29:30 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Warning | Failed Create Pod Sand Box | Failed  create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni  failed to set up pod "rm-workspacefzm5nlaebepwgrm2_dfestal-che" network:  CNI request failed with status 400: 'pods  "rm-workspacefzm5nlaebepwgrm2" not found '
-- | -- | -- | -- | -- | --
11:29:29 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Sandbox Changed | Pod sandbox changed, it will be killed and re-created.
11:29:27 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Started | Started container
11:29:27 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Created | Created container
11:29:27 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Pulled | Successfully pulled image "centos:centos7"
11:29:26 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Pulling | pulling image "centos:centos7"
11:29:24 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "pvc-ecba7ab9-d6c6-11e7-8191-0233cba325d9"
11:28:51 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "default-token-xrz80"
11:28:51 AM | rm-workspacefzm5nlaebepwgrm2 | Pod | Normal | Scheduled | Successfully assigned rm-workspacefzm5nlaebepwgrm2 to ip-172-31-64-37.us-east-2.compute.internal
```

I have no idea what the last error means, but I assume it might be an infrastructure problem, since the same test was working correctly on prod-preview last week.

@jfchevrette any idea ?

**Comment by davidfestal** [comment] 2018-05-07 10:12
cc @pbergene

**Comment by jfchevrette** [comment] 2018-05-07 13:59
@davidfestal what cluster & namespace? Was this tested on another cluster? Prod-preview or prod?

**Comment by davidfestal** [comment] 2018-05-07 15:03
@jfchevrette on OSIO prod it fails though it worked without any problem on prod-preview when I tested it some days ago.

FTR : 
- my OSIO prod Che namespace in which it failed is at:
```
https://console.starter-us-east-2.openshift.com/console/project/dfestal-che/
```
- while my OSIO prod-preview Che namespace (in which it succeeded) is:
```
https://console.starter-us-east-2a.openshift.com/console/project/dfestal-preview-che/
```

> The CNI/network error only seem to indicate it could not setup networking for the pod because the pod could not be found. Maybe the pod died early?

I wonder if this could be related to the following error found in the logs by @pbergene :
```
May 07 09:29:29 ip-172-31-64-37.us-east-2.compute.internal atomic-openshift-node[10115]: W0507 09:29:29.882234   10115 kubelet_pods.go:875] Unable to retrieve pull secret dfestal-che/default-dockercfg-twt97 for dfestal-che/rm-workspacefzm5nlaebepwgrm2 due to secret "dfestal-che"/"default-dockercfg-twt97" not registered.  The image pull may not succeed.
```

the logs shared by @pbergene can be found here:

http://pastebin.test.redhat.com/586920

**Comment by joshuawilson** [comment] 2018-05-08 05:30
I think @xcoulon made a fix for this. Can you please check if it worked. I'm just not 100% his fixed covered this or not.

**Comment by jfchevrette** [comment] 2018-05-09 13:51
The errors are caused by the very short lived container terminating before Openshift has the time to finish the pod bringup (networking, mounting secrets, etc...)

As a quick workaround we can add a sleep in there after the rm (`sleep 5` should do)

As a long term solution, it is probably worth looking into creating a [Job](https://docs.openshift.com/container-platform/3.9/dev_guide/jobs.html) which is designed to run this sort of short lived/one-off tasks.

**Comment by davidfestal** [comment] 2018-05-09 15:05
So to summarize, looking directly into the PV with a test POD showed that, in fact, all the tests I did today were successful: the corresponding workspace folders were correctly removed from the PV when deleting a workspace from the dashboard.
The warning shown in the events related to the cleaning POD finally doesn't seem to be a problem.

As for adding a `sleep 5` in the cleaning command, I'm not sure it would be a good thing since it would increase the time during which the cleaning POD is locking the PV, which would finally reduce performance. And this, just to avoid a non-critical warning in the events.

@slemeur could you confirm that it also works in your tests ?

**Comment by slemeur** [comment] 2018-05-16 08:09
It works for me. Thanks @davidfestal

**Comment by xcoulon** [comment] 2018-05-18 07:56
I also ran a quick test on prod-preview with a new space and a new workspace, and when deleting the space, the associated workspace was also deleted.
@slemeur can you confirm this issue is resolved and can be closed, now?

**Comment by xcoulon** [comment] 2018-05-18 12:48
thanks for the confirmation, @slemeur. Closing the issue now :)

**Closed by xcoulon** 2018-05-18 12:48 UTC
Labels: SEV2-high, area/che, priority/P0, status/pending-qa-verification, team/che/osio, team/platform, type/bug
