### ISSUE TITLE
Build log produces messages that seem alarming (but maybe shouldn't be)

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#3098] opened 2018-04-12 15:40 UTC
Watching the build log, the viewer will see messages similar to these.
Given that the process does not smoothly transition to the next step (which it may eventually), these messages seem alarming.  (Maybe we could provide additional explanatory text?)

  "Still waiting to schedule task
  Jenkins doesn’t have label mavenclickparty1_1"

**Comment by piyush1594** [comment] 2018-06-25 03:50
Duplicate of #3797

**Comment by piyush1594** [comment] 2018-06-25 03:50
Closing this @RickJWagner as other has more visibility. Thanks

**Closed by piyush1594** 2018-06-25 03:50 UTC
Labels: SEV3-medium, area/jenkins, area/pipelines, team/build-cd, type/bug
