### ISSUE TITLE
Account home / Recent Active Pipelines does not show successful pipelines

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#3416] opened 2018-05-02 12:39 UTC
I can't see any successfully finished pipelines on Account home / Recent Active Pipelines, only failed ones. Is that a feature or  a bug?

![account-home](https://user-images.githubusercontent.com/2078072/39523557-5bb2e0e0-4e16-11e8-9ff4-f6ab2f15fec4.png)

**Comment by ljelinkova** [comment] 2018-06-13 08:34
Could anybody answer my question?

**Comment by jiekang** [comment] 2018-06-13 12:38
The 'recent' filter has always been a mystery to me. It will show any pipelines, successful or failed ones, however I think it's filter for what's 'recent' or not, may be a bit off.

**Comment by jiekang** [comment] 2018-06-13 12:39
I'll try to investigate a little more... but really I hope the Pipelines related code can receive an update similar to how the Applications/Environments pages were transformed into the Deployments page.

**Comment by jiekang** [comment] 2018-06-13 12:47
Okay, it looks like it does filter out completed builds. @ljelinkova

Code snippet of 'recent' filter (2018-06-13):

```
function filterByMostRecent(buildConfigs: BuildConfigs, builds: Builds): BuildConfigs {
  let pipelines = combineBuildConfigAndBuilds(buildConfigs, builds);
  let sortedPipelines = orderBy(pipelines, (pipeline) => {
    if (pipeline && pipeline.lastBuild) {
      return new Date(pipeline.lastBuild.creationTimestamp);
    }
    return new Date(0);
  }, ['desc']);

  let answer = new BuildConfigs();
  sortedPipelines.forEach(bc => {
    if (bc.statusPhase !== 'Complete' && bc.labels['space']) {
      answer.push(bc);
    }
  });
  return take(answer, 4);
}
```

**Comment by ldimaggi** [comment] 2018-06-13 12:52
So - it filters out *successfully* completed builds.  ;-)

**Comment by ljelinkova** [comment] 2018-06-13 12:53
Still, it is very confusing. The title says Recent with no implication that successful builds are left out.

**Comment by jiekang** [comment] 2018-06-13 13:10
I'm not sure how useful it is. For what it's worth, it does say 'Recent **Active** Pipelines' so I guess the definition of Active does not include Completed builds. Also I wonder if the inclusion of failed builds, which aren't 'Complete' was intended or if it was an oversight. I don't know the history here...

**Comment by ljelinkova** [comment] 2018-06-19 08:08
For me the "Recent Active" is contradiction - as recent should be finished and active still running :-) Is there anybody who knows how this "Recent Active Pipelines" are supposed to work?

I personally would prefer the simplest approach - title just Recent pipelines and it would contain the list of pipelines without any filtering.

**Comment by jiekang** [comment] 2018-06-19 13:07
Agree on confusing and I'd be fine changing it to just `Recent` instead of `Recent Active` and showing the last 4-5 pipelines based on date only. The change in the filter is easy, just remove the condition for `bc.statusPhase !== 'Complete'`

The thing is, I am not up to date on the UX work being done in this area. Is this widget already being reworked? Or will it be dropped? Is it okay to make this change? @openshiftio/uxd-team

**Comment by joshuawilson** [comment] 2018-06-20 01:45
@openshiftio/uxd-team please advise.

**Comment by ppitonak** [comment] 2018-07-25 10:05
@openshiftio/uxd-team any updates?

**Comment by catrobson** [comment] 2018-07-25 21:05
Hi all - sorry for the non-response on this issue.

+1 that we can change this to just be "Recent pipelines" and show the last (5?) pipelines that have had activity happening in the system in this widget, completed or not.  I'm not sure what the number limit is on how many we show today, so maybe we need to see how it looks with 4 or 5 to make sure we avoid scrolling in the widget if possible.

**Comment by jiekang** [comment] 2018-08-30 12:17
Fix has been merged. Closing.

**Closed by jiekang** 2018-08-30 12:17 UTC
Labels: area/UX, area/dashboard, area/pipelines, team/build-cd, team/ux, type/question
