### ISSUE TITLE
Clicking BuildNo. in home page redirect to home page not to build pipeline

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3020] opened 2018-04-12 05:21 UTC
![buildpipeline](https://user-images.githubusercontent.com/34271052/38657725-6975ec54-3e3f-11e8-9e24-6638b07734e3.gif)

**Comment by rootAvish** [comment] 2018-04-12 05:57
+1 also facing the same issue.

**Comment by aptmac** [comment] 2018-04-17 19:49
@RanjithRV & @rootAvish is this an issue that you're seeing frequently? I was having a hard time reproducing this.
I did however notice that if I logged out, cleared my cache, then logged back in, I would encounter this error on the first instance of going to a space -> analyze page. After a refresh or reload of the page, I am unable to see this - so it only occurs on the first instance of viewing the page, can you confirm?

Either way, it looks like a potential source of the error is [0], where the openshiftConsoleUrl initialization line is commented out. In the instances where this issue occurs, the openshiftConsoleUrl is undefined, and if I uncomment [0] I cannot reproduce this issue.

[0] https://github.com/fabric8-ui/fabric8-ui/commit/6fbc694fc1518ac5d4dea184c52916174734f626#diff-13f35d0c0ec39d5a57b45100421c2cceR43

**Comment by jiekang** [comment] 2018-04-19 16:35
This is a duplicate of https://github.com/openshiftio/openshift.io/issues/2744

**Closed by jiekang** 2018-04-19 16:35 UTC
Labels: SEV2-high, area/dashboard, area/navigation, team/platform
