### ISSUE TITLE
Navigating to view Build Pipeline can result in circular navigation

### ISSUE THREAD

**Issue by RickJWagner** [openshiftio/openshift.io#3097] opened 2018-04-12 15:38 UTC
Going to look at the build pipeline was not intuitive.  The links led to some circular navigation.

**Comment by joshuawilson** [comment] 2018-04-12 17:16
What did you click on? where did you expect it to take you and where did you end up?

**Comment by RickJWagner** [comment] 2018-04-12 18:14
I clicked on the blue 'Buildx' link, it brought me to a screen that seemed more like an overview than something specific to a particular Build.  Screenshots below.

![build1](https://user-images.githubusercontent.com/524520/38695949-61279eda-3e53-11e8-9013-76f9cf321a0d.png)
![afterbuildclick](https://user-images.githubusercontent.com/524520/38695952-64be9bfc-3e53-11e8-86e9-1c5370bf2b91.png)

**Comment by jiekang** [comment] 2018-04-19 16:32
This is a duplicate of https://github.com/openshiftio/openshift.io/issues/2744

**Closed by jiekang** 2018-04-19 16:32 UTC
Labels: SEV3-medium, area/navigation, team/build-cd, team/platform, type/bug
