### ISSUE TITLE
POC - Handling API Logic for logging of UI Incidents

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#998] opened 2017-09-21 11:27 UTC
## Description

This sub task will store the information received from the UI layer in regards to error logging and store in some space.

## Why

This could, in a way, help us identify the issues if any from the frontend that are gone unnoticed.

## How

As we get the model from the UI layer, to begin with we can store that in a flat file just to track the progress and eventually move it to S3 buckets for better usage.

- [ ] Create an exposable API [Get and Post methods]
- [ ] Write to file the model that is received
- [ ] If things are so far great, write to S3 buckets.
- [ ] Also, provide a mechanism to read the written logs regardless of where it is stored. [ GET call ]

**Comment by joshuawilson** [comment] 2017-09-21 12:42
This is a duplicate of https://github.com/openshiftio/openshift.io/issues/863 
If you have time to work on it let me know and we can plan it.

**Comment by arunkumars08** [comment] 2017-09-21 13:30
@joshuawilson Sure Joshua. I will update you on this. We have taken this as a stretch goal. Thanks

**Comment by samuzzal-choudhury** [comment] 2017-09-21 15:06
@arunkumars08 @joshuawilson This work was scoped for logging only the recommender UI exceptions/incidents ATM

**Comment by joshuawilson** [comment] 2017-09-21 15:11
This type of thing should be done at a broader level. All of the UI needs it. If it is done for one, all benefit. 

If you don't have the time, then wait. If you do have the time then we should work through the architecture and concerns.

**Comment by samuzzal-choudhury** [comment] 2017-09-21 16:18
@joshuawilson I was not aware that the platform team is already taking a lead on this. I totally agree to your point that the work should benefit all.

@GeorgeActon @krishnapaparaju, I added the user story (as a stretch goal) https://github.com/openshiftio/openshift.io/issues/754 address logging of recommender UI incidents in the server and was scoped accordingly. 

But, apparently we are looking at a generic solution and that will require architectural discussions with a broader audience and @joshuawilson had already opened an issue https://github.com/openshiftio/openshift.io/issues/863 for that.

I moving the user story and it's related tasks (https://github.com/openshiftio/openshift.io/issues/754, 
https://github.com/openshiftio/openshift.io/issues/997, https://github.com/openshiftio/openshift.io/issues/998) back to the "Analytics Backlog" as we will not have the bandwidth to cover those at their broader scope in this sprint.

CC: @arunkumars08 @invincibleJai

**Comment by joshuawilson** [comment] 2017-09-21 16:20
If you do get some bandwidth for this, ping me and we can collaborate on it.

**Comment by joshuawilson** [comment] 2018-01-22 18:59
Yes, it's a dup. We have Sentry.io set up and once we get the UI to start logging errors there, you can write up an issue to use it.

**Closed by joshuawilson** 2018-01-22 18:59 UTC
Labels: area/logging, team/analytics, team/platform, type/feature
