### ISSUE TITLE
Updated container image is not pushed to stage

### ISSUE THREAD

**Issue by gtema** [openshiftio/openshift.io#2193] opened 2018-02-06 17:07 UTC
When doing everything according to the getting started guide the first (initial) project version get's deployed correctly. After implementing a code change new build is triggered, new version tag is deployed, but it contain the original version (without implemented code changes). In the jenkins project of the openshift.io a new image is generated, but in the stage new revision with the same sha256 is placed.
The result is tested to be same for Vert.x and Springboot

**Comment by gtema** [comment] 2018-02-06 17:10
![jenkins_project](https://user-images.githubusercontent.com/16461884/35873086-fe59bb3e-0b68-11e8-9838-46bef4eeb541.png)
![stage_project](https://user-images.githubusercontent.com/16461884/35873087-011513d2-0b69-11e8-93f1-61c0e07495f4.png)

**Comment by qodfathr** [comment] 2018-03-01 13:22
@joshuawilson can you help identify the right team to investigate this? Thanks.

**Comment by rupalibehera** [comment] 2018-04-24 13:39
@sthaha @hrishin , I think we solved this one like a month back ?

**Comment by rohanKanojia** [comment] 2018-04-24 14:15
@rupalibehera : Could you please link the pr that fixed this issue here? If it is resolved, I think we can close this issue.

**Comment by rohanKanojia** [comment] 2018-04-24 14:39
I think we fixed it recently in #2505 
cc @rupalibehera @sthaha

**Comment by rohanKanojia** [comment] 2018-04-30 06:56
@gtema @jmelis : Did you get time to reply here with your Jenkins logs? We are on a tight deadline here and can only move forward with your feedback.

**Comment by gtema** [comment] 2018-04-30 08:36
[openshift-booster-build.log](https://github.com/openshiftio/openshift.io/files/1959880/openshift-booster-build.log)
[openshift-spring-build.log](https://github.com/openshiftio/openshift.io/files/1959881/openshift-spring-build.log)

Sorry that after 3 month of silence I am not available over the weekend upon your request. Please find the logs.
fabric8-maven-plugin 3.5.38 referred in 2505 seems still not being available, and for springboot app it is not being used anyway.

**Comment by rohanKanojia** [comment] 2018-05-02 10:05
Hi, I tried reproducing it few times but I could not. I made this change : [0dcc0b83](https://github.com/rohanKanojia/vertx-http-booster-test-updated-container/commit/0dcc0b83882ed004da37f4136dbd0ec68b36b09c) in vertx-http-booster, but I was able to see the change:
![screenshot from 2018-05-02 15-32-21](https://user-images.githubusercontent.com/13834498/39517721-51224cb2-4e1e-11e8-970d-118f45ebb139.png)

**Comment by lordofthejars** [comment] 2018-05-02 11:16
I have tried to reproduce as well with several changes, but no luck to reproduce it.

**Comment by rohanKanojia** [comment] 2018-05-02 12:07
Closing as not reproducible. Since it got fixed in #2505 . Please feel free to reopen, if anyone is able to reproduce it.

**Closed by rohanKanojia** 2018-05-02 12:07 UTC
Labels: SEV2-high, area/jenkins, area/pipelines, priority/P0, team/build-cd, train/heather, type/bug
