### ISSUE TITLE
Displays encoded characters for special symbol in "My Work Items" section

### ISSUE THREAD

**Issue by hrishin** [openshiftio/openshift.io#4173] opened 2018-08-15 14:02 UTC
##### Issue Overview

Work item title shows encoded characters for special symbols like `"` in "My Work Items" section. On work item detail page it appears correctly. 

##### Expected Behaviour
Show normal symbol insted of encoded one
##### Current Behaviour
Shows encoded one 
##### Steps To Reproduce

1. Add work a title having special symbol e.g. `Build jenkinsfile for "deploy to the stage and run environment" option`

##### Additional Information
![planner-workitem](https://user-images.githubusercontent.com/28615674/44151831-53652a9e-a0c1-11e8-8b3b-fc7a04ffca9b.png)

**Comment by aptmac** [comment] 2018-08-20 14:19
Duplicate of https://github.com/openshiftio/openshift.io/issues/3484 ?

**Comment by joshuawilson** [comment] 2018-10-30 18:32
looks like it is

**Closed by joshuawilson** 2018-10-30 18:32 UTC
Labels: SEV3-medium, area/UI, area/dashboard, area/planner, priority/P4, team/planner, type/bug
