### ISSUE TITLE
Deleting a space leaves a pipeline running on Recent Active Pipelines

### ISSUE THREAD

**Issue by gbaufake** [openshiftio/openshift.io#1820] opened 2018-01-10 12:14 UTC
On Openshift.io, 
After creating a space with a pipeline then deleting it leaves a recent pipeline running on Recent Active Pipelines 

![image](https://user-images.githubusercontent.com/2313749/34772158-3e43a5c4-f5ee-11e7-8f3e-77d3e87e7006.png)

Clicking on Recent Pipeline page, it redirects to 404 Page

![image](https://user-images.githubusercontent.com/2313749/34772331-c8907d60-f5ee-11e7-9a0f-e9fc6dfe2137.png)

After a page refresh on home, the Recent Pipeline message stays with some flash messages.

![image](https://user-images.githubusercontent.com/2313749/34772534-618c8658-f5ef-11e7-8b73-8b05c0abea7c.png)

**Comment by qodfathr** [comment] 2018-01-27 19:52
Closing as a dupe of #1604

**Closed by qodfathr** 2018-01-27 19:52 UTC
Labels: SEV2-high, area/pipelines, area/spaces, team/build-cd, team/platform, train/heather, type/bug
