### ISSUE TITLE
Wrong organization map and string validation in "Application Wizard"

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1805] opened 2018-01-10 06:48 UTC
In "Application Wizard", the organization show "OpenShift Origin, https://www.openshift.com", which is not the correct map between product and website.
OpenShift Origin should link to https://www.openshift.org, while
OpenShift Online should link to https://www.openshift.com.

![screenshot from 2018-01-10 14-42-28](https://user-images.githubusercontent.com/4716987/34759098-e910a2c4-f614-11e7-9bec-0d37d879bcbd.png)

**Comment by liangxia** [comment] 2018-01-10 07:14
Also wrong validation after the first character typed in "Goup Id" field.

![screenshot from 2018-01-10 15-12-42](https://user-images.githubusercontent.com/4716987/34759951-bf47911a-f618-11e7-9046-efdce9fa784d.png)

**Comment by GeorgeActon** [comment] 2018-01-11 13:29
@gastaldi I assigned this a Sev2. Please assess

**Comment by gastaldi** [comment] 2018-01-11 19:20
Where is this happening? prod-preview? prod?

**Comment by joshuawilson** [comment] 2018-01-11 20:15
If you see this in prod, please try a refresh and see if that clears it up.

**Comment by liangxia** [comment] 2018-01-12 06:42
I can still see that in prod.

**Comment by gastaldi** [comment] 2018-01-12 08:40
@liangxia this data is taken from Github: https://github.com/openshift which is the org you belong to displays the same thing.

Closing this issue as it is not a bug. Do you mind opening a new issue regarding the groupId validation?

Thank you!

**Closed by gastaldi** 2018-01-12 08:40 UTC
Labels: SEV2-high, area/app-wizard, status/info-needed, team/launcher, type/bug

**Comment by liangxia** [comment] 2018-01-12 09:24
GoupId validation is tracked in https://github.com/openshiftio/openshift.io/issues/1807
