### ISSUE TITLE
Vert.X icons missing on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2549] opened 2018-03-13 02:44 UTC
This is only an issue on prod-preview:

![screenshot from 2018-03-12 22-42-58](https://user-images.githubusercontent.com/642621/37319775-dc21a24a-2646-11e8-8b7e-66d9a3e10b31.png)

**Comment by joshuawilson** [comment] 2018-03-13 03:05
Closing as a duplicate of #2531

**Closed by joshuawilson** 2018-03-13 03:05 UTC
Labels: area/quickstarts, env/prod-preview, team/che/platform, type/bug
