### ISSUE TITLE
Unable to create new app (Could not get webhooks for repository) 

### ISSUE THREAD

**Issue by fbricon** [openshiftio/openshift.io#3350] opened 2018-04-29 01:31 UTC
I tried to create a new Vert.x app from scratch, but it failed with an error: "Could not get webhooks for repository fbricon/simplytics"

The setup page spinners seem to be waiting endlessly, https://github.com/fbricon/simplytics is empty.

<img width="998" alt="screen shot 2018-04-28 at 9 24 15 pm" src="https://user-images.githubusercontent.com/148698/39402370-5da7108a-4b2b-11e8-812a-a78e79726420.png">

**Comment by ldimaggi** [comment] 2018-04-29 03:08
What are you seeing in the Chrome console?

I am seeing a constant stream of these errors:

```
_scrollbars.less:6 WebSocket connection to 
'wss://openshift.io/oapi/v1/namespaces/username/builds?
watch=true&access_token=.....' failed: Error during 
WebSocket handshake: Unexpected response
 code: 200
```

**Comment by ldimaggi** [comment] 2018-04-29 13:47
What's happening is that after a login, and before any other user actions are taken, this error is raised:
```
GET https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com
/oapi/v1/namespaces/osousername/buildconfigs 401 (Unauthorized)
```
followed by a constant stream of these errors:
```
_scrollbars.less:6 WebSocket connection to 'wss://f8osoproxy-test-dsaas-
production.09b5.dsaas.openshiftapps.com/oapi/v1/namespaces/osousername/builds?
watch=true&access_token=.' failed: HTTP Authentication failed; no valid credentials available
```

**Comment by rgarg1** [comment] 2018-04-30 06:39
I was able to reproduce this issue today by following the simple steps:
1) Log into OSIO prod
2) Create a new space (used Scrum) using the new wizard (sapce name: apr30space1)
3) Created a new application (Health check + VertX)
4) Used all defaults
5) Saw the error (could not get webhooks). I observed some websocket error in the console and the github repo (https://github.com/rgarg1/apr30space1) was empty

![could not get webhooks](https://user-images.githubusercontent.com/28748448/39417040-2b11f92e-4c6f-11e8-9276-61fcd4a8a93d.png)

**Comment by rgarg1** [comment] 2018-04-30 06:40
Forgot to add that there are no failures observed in the network tab.

**Comment by ldimaggi** [comment] 2018-04-30 12:35
Moving to SEV1 as multiple users are unable to create new quickstarts.

**Comment by ldimaggi** [comment] 2018-04-30 13:31
Changing back to SEV2 - Fred was able to resolve the issue he found by performing an env reset. I will log a separate issue for the problem that I encountered.

**Comment by bmicklea** [comment] 2018-04-30 20:30
FWIW, I can't reproduce following @rgarg1 steps...maybe I'm just lucky?

**Comment by ldimaggi** [comment] 2018-05-01 14:58
Not able to reproduce this issue either.

**Comment by jiekang** [comment] 2018-05-01 19:00
The buildconfig http request and websocket failures are unrelated to this launcher flow. They are from the pipelines widget.

The warning from @rgarg1 screenshot 'Form submission cancelled because the form is not connected' could be something to further investigate.

**Comment by jiekang** [comment] 2018-05-01 19:01
@ldimaggi did you create an issue for the unauth requests?

**Comment by ldimaggi** [comment] 2018-05-01 19:07
The unauth issue is:  https://github.com/openshiftio/openshift.io/issues/3377

**Comment by jiekang** [comment] 2018-05-01 19:09
Ah awesome thanks!

**Comment by invincibleJai** [comment] 2018-05-02 06:44
@fbricon I tried but am not able to reproduce it.

As @jiekang stated

> The buildconfig http request and websocket failures are unrelated to this launcher flow. They are from the pipelines widget.

am not sure if it should have label `team/analytics/launcher` @animuk  WDYT?

**Comment by animuk** [comment] 2018-05-02 06:52
@fbricon we are closing this issue as @ldimaggi created a unauth issue above. you can reopen if required.

**Closed by animuk** 2018-05-02 06:52 UTC
Labels: SEV2-high, area/launcher, priority/P0, type/bug
