### ISSUE TITLE
[Bug]Error page is Dead 

### ISSUE THREAD

**Issue by naina-verma** [openshiftio/openshift.io#226] opened 2017-06-13 07:05 UTC
User redirected to Error page https://openshift.io/_error
Video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COUGcwVGhXclVoaWs/view?usp=sharing

**Comment by jstrachan** [comment] 2017-06-14 08:33
this is a duplicate of https://github.com/openshiftio/openshift.io/issues/224 so gonna close - should have a fix soon!

**Closed by jstrachan** 2017-06-14 08:33 UTC
