### ISSUE TITLE
no pipelines in pipeline view when there haven't been builds for a while - data get pruned ? 

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#1913] opened 2018-01-18 08:35 UTC
I keep seeing this and forgetting to report it - when you add an app to  a space the codebase gets setup and pipelines are running.

if you wait a few days the codebase is still visible (as expected), but now pipelines are gone - its as if pipelines only is a view into the *active* pipelines recorded by openshift objects but if I recall those get pruned and thus the pipeline info is lost.

I haven't found a way to get the pipelines "back again" beyond doing a push to the repo; but this can't be the right way to keep track.

**Comment by joshuawilson** [comment] 2018-01-19 04:06
I think this is something for the build team to look into. Or maybe someone on the SD team knows what is happening.
cc @chmouel @pradeepto @jfchevrette @vpavlin

**Comment by chmouel** [comment] 2018-01-19 06:35
I have some pipelines dating back from a month ago, are you talking somewhere else in the UI ? 
![image](https://user-images.githubusercontent.com/98980/35137779-5e9018fe-fceb-11e7-98b5-b1340255c02e.png)

**Comment by ldimaggi** [comment] 2018-01-19 13:09
I'm watching pipelines too - these seem OK after almost 1 day:

![screenshot from 2018-01-19 08-02-12](https://user-images.githubusercontent.com/642621/35152354-1be1131e-fcf0-11e7-84b5-260240b395a8.png)

**Comment by maxandersen** [comment] 2018-01-22 11:55
Here is what I see in openshift console:
![2018-01-22_12-52-50](https://user-images.githubusercontent.com/54129/35219506-37f2a31c-ff73-11e7-975d-bef8f3183ed1.png)

Notice there are both test3 and test4.

In openshift.io I see this:
![2018-01-22_12-54-18](https://user-images.githubusercontent.com/54129/35219549-5f10a430-ff73-11e7-97d3-2a46dbd6aea3.png)

notice how only test4 shows up.


when I committed stuff to `test3` a pipeline did show up but in both places - but before the commit there was no trace in either console.

**Comment by maxandersen** [comment] 2018-01-22 11:56
My question is from *where*  are the list of pipelines fetched ? if in openshift resources - what is the age limit on those ?

**Comment by chmouel** [comment] 2018-01-22 11:57
No idea, let's see if @rupalibehera or @sthaha would know

**Comment by ldimaggi** [comment] 2018-01-22 12:13
I have seen problems like this - but they were due to an account env being reset - I've been watching some pipelines in my account since last week and they are still there:

![screenshot from 2018-01-22 07-11-37](https://user-images.githubusercontent.com/642621/35220276-b901a1cc-ff43-11e7-8a0c-d27aee60e6eb.png)

**Comment by rupalibehera** [comment] 2018-04-24 13:36
We need to check this issue, include in the sprint.
cc: @pradeepto

**Comment by bmicklea** [comment] 2018-04-30 21:06
FWIW I have multiple old pipelines in old spaces that still show up when I go back to them.

I would vote to either:
- Remove the `p0` label
- Close the issue as fixed

**Comment by maxandersen** [comment] 2018-05-01 07:47
I unfortunately do not think the underlying issue is fixed but I do agree it is not a p0 in the current timeline.

propsed to remove p0 but do investigate how long we actually keep pipeline data in OpenShift since it does seem to dissapear but still be visible in jenkins.

**Comment by jiekang** [comment] 2018-05-03 14:10
My understanding of the pipelines component in fabric8-ui is it's pulling BuildConfigs straight from OpenShift API. It's strange that it would be missing some. Maybe my assumption is wrong then.

**Comment by hrishin** [comment] 2018-05-16 09:47
> My question is from where are the list of pipelines fetched ? if in openshift resources - are there any limits to them ? as afaics they 'disaappear' eventually.

Its OpenShift resource 
pipeline -> `buildconfig`, running build -> `build`. As far as looking the OSO quota page I dot think there is limit.

cc: @chmouel

**Comment by chmouel** [comment] 2018-05-17 11:59
I have been investigating the issue and can't reproduce.

Looking at the obvious culpurit openshift-sync-plugin, it seems that this commit would address it : 

https://github.com/fabric8io/jenkins-sync-plugin/commit/ff752044ad2024c11535f61e037429673988a681

I am trying to reproduce this issue and see if I can add some debug,

**Comment by krishnapaparaju** [comment] 2018-05-24 05:43
@chmouel could not reproduce this problem. Guess we can close this , can reopen if this issue shows up again.

**Closed** 2018-05-24 11:57 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug
