### ISSUE TITLE
When a pipeline stage fails, the time is shown as 0s, not the real run-time so far

### ISSUE THREAD

**Issue by pilhuhn** [openshiftio/openshift.io#587] opened 2017-08-16 09:47 UTC
This build was running for more than 39s (after it took quite a while until it started).

Once the result flipped to error, the time went to 0s.
I find this is confusing, as 0s is normally an indicator that the git clone failed long before the build even started. I think it would be better to leave the run-time.

![bildschirmfoto 2017-08-16 um 11 44 11](https://user-images.githubusercontent.com/208246/29357580-580be820-8278-11e7-8854-c5bb20122786.png)

**Comment by pilhuhn** [comment] 2017-08-16 10:06
Looks like this is an issue in Jenkins, as Jenkins sets them to 0 :-(
![bildschirmfoto 2017-08-16 um 12 06 00](https://user-images.githubusercontent.com/208246/29358430-4f6c9b76-827b-11e7-92e6-171ffd2afed9.png)

**Comment by qodfathr** [comment] 2018-01-17 21:54
As this is how Jenkins behaves, closing by design.

**Closed by qodfathr** 2018-01-17 21:54 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug
