### ISSUE TITLE
Running tests in Che workspace for project created from "Vert.X HealthCheck" workspace = file not found error

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#408] opened 2017-07-24 20:58 UTC
_From @ldimaggi on July 10, 2017 21:42_

_Copied from original issue: fabric8-ui/fabric8-ui#1706_

**Comment by joshuawilson** [comment] 2017-07-24 20:58
_From @ldimaggi on July 10, 2017 21:43_

The same exception is raised as is documented here:
https://github.com/fabric8-ui/fabric8-ui/issues/1694

**Comment by joshuawilson** [comment] 2017-07-24 20:58
_From @ldimaggi on July 12, 2017 17:47_

Tests were run in the UI, from the Run->Test menu.

**Comment by l0rd** [comment] 2017-07-25 10:57
@joshuawilson I'm removing label `area/che` because it doesn't look Che related. I can reproduce that from my local shell:
```bash
git clone https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster
cd vertx-configmap-booster
mvn -Dtest=OpenShiftIT test
```
The output:
```
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openshift.booster.OpenShiftIT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.48 sec <<< FAILURE! - in io.openshift.booster.OpenShiftIT
io.openshift.booster.OpenShiftIT  Time elapsed: 2.48 sec  <<< ERROR!
java.io.FileNotFoundException: target/classes/META-INF/fabric8/openshift.yml (No such file or directory)
	at io.openshift.booster.OpenShiftIT.prepare(OpenShiftIT.java:31)
```

**Comment by joshuawilson** [comment] 2017-11-19 22:41
@krishnapaparaju can you work with @gastaldi to get the quickstarts fixed?

**Comment by cescoffier** [comment] 2017-11-22 11:31
Is this affecting all vert.x boosters, all boosters, or only the config map one?

**Comment by cescoffier** [comment] 2017-11-22 11:32
OH BTW, you forgot the `-Popenshift`

**Comment by cescoffier** [comment] 2017-11-22 11:33
`mvn -Dtest=OpenShiftIT test -Popenshift, openshift-it` is the right command

**Comment by gastaldi** [comment] 2017-11-22 15:39
You need the `openshift` maven profile enabled for that to work correctly

**Comment by gastaldi** [comment] 2017-12-13 13:44
Can someone please retest this issue and close if it works with the instructions provided above?

**Comment by joshuawilson** [comment] 2017-12-15 15:16
@ldimaggi please verify

**Comment by ldimaggi** [comment] 2017-12-18 17:10
I was able to run the tests for the project outside of OSIO/Che:
```
git clone https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster
cd vertx-configmap-booster
mvn test

[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ configmap-vertx ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.858 s
[INFO] Finished at: 2017-12-18T12:04:20-05:00
[INFO] Final Memory: 18M/359M
[INFO] ------------------------------------------------------------------------
```

But - performing the same steps in Che fails:

```

Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.885 sec <<< FAILURE! - in io.openshift.booster.HttpApplicationTest
callGreetingTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 0.755 sec  <<< ERROR!
java.net.BindException: Address already in use

callHealthCheck(io.openshift.booster.HttpApplicationTest)  Time elapsed: 0.026 sec  <<< ERROR!
java.net.BindException: Address already in use

callKillMe(io.openshift.booster.HttpApplicationTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.net.BindException: Address already in use

callGreetingWithParamTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.net.BindException: Address already in use


Results :

Tests in error:
  HttpApplicationTest.callGreetingTest » Bind Address already in use
  HttpApplicationTest.callGreetingWithParamTest » Bind Address already in use
  HttpApplicationTest.callHealthCheck » Bind Address already in use
  HttpApplicationTest.callKillMe » Bind Address already in use

Tests run: 4, Failures: 0, Errors: 4, Skipped: 0

```

**Comment by l0rd** [comment] 2017-12-18 17:42
Running the HealthCheck tests from within Che console won't work because the OpenShift API is not accessible. That is by design (c.f. https://github.com/openshiftio/openshift.io/issues/1061#issuecomment-347123769).

**Comment by rkratky** [comment] 2017-12-23 10:19
@ldimaggi, @l0rd, is that a known issue that will be fixed eventually, or is that expected behaviour? If it is expected (which I assume it is when Mario says it's "by design"), shouldn't the UI be updated/modified to make it clear to users?

**Comment by ldimaggi** [comment] 2018-01-02 19:01
+1 is there any way to shield the users from this error? Or - can we simply document this?

**Comment by l0rd** [comment] 2018-01-08 14:20
@rkratky that is expected behaviour and yes I believe that the "health check" quickstarts don't make sense if user cannot even test it in Che.

**Comment by gastaldi** [comment] 2018-01-10 21:38
It's not clear what the action item for this issue is. Will the docs be updated? Should the booster be removed from the list of boosters? Let me know how we should proceed with this

**Comment by qodfathr** [comment] 2018-01-16 15:48
cc: @slemeur

**Comment by ldimaggi** [comment] 2018-04-24 16:01
I recommend closing this issue in favor of the quickstart/documentation issue logged here: https://github.com/openshiftio/openshift.io/issues/3120

Also - there are more recent (April 2018) quickstart issues that supercede this issue.

**Closed by ldimaggi** 2018-04-24 16:01 UTC
Labels: SEV2-high, area/quickstarts, priority/P0, team/launcher, type/bug
