### ISSUE TITLE
Can't loggout from prod preview.

### ISSUE THREAD

**Issue by sanketpathak** [openshiftio/openshift.io#4757] opened 2019-02-13 11:15 UTC
##### Issue Overview

I'm not able to logout  from my prod-preview account.
##### Expected Behaviour
One should logout from https://prod-preview.openshift.io
##### Current Behaviour
Not able to logout, error 404 is shown

![err01](https://user-images.githubusercontent.com/10252230/52707274-53020600-2fad-11e9-9726-19b6cca268db.png)

##### Steps To Reproduce

1. [step 1] Go to https://prod-preview.openshift.io.
2. [step 2] Login if you aren't already logged in.
3. [step 3] Logout.

##### Additional Information

The network tab in inspect window shows error as : 
`
errors: [{code: "not_found", detail: "/api/logout/v2", id: "RR+e9Jwe", status: "404", title: "Not Found"}]`

**Comment by jarifibrahim** [comment] 2019-02-13 12:38
Logout v2 was added to Auth via https://github.com/fabric8-services/fabric8-auth/pull/746 and in UI via https://github.com/fabric8-ui/fabric8-ui/pull/3513 . 

The login/logout requests are proxied through WIT but WIT wasn't updated.
The `/logout/v2` endpoint should be added to https://github.com/fabric8-services/fabric8-wit/blob/master/design/auth.go#L43

**Comment by alexeykazakov** [comment] 2019-02-13 16:49
@rohitkrai03 @sbryzak hm.. how did you test this guys? :)

**Comment by rohitkrai03** [comment] 2019-02-13 17:59
@alexeykazakov  For me, logout is not working only if you have enabled `internal` feature flag and are running the new navigation which is in react and has a different way of setting env variables for URLs.
So, the problem is in the angular part `AUTH_API_URL` is `https://auth.prod-preview.openshift.io/api/logout/v2` and in react part it is coming as `https://prod-preview.openshift.io/api/logout/v2`.  While testing it in dev environment it worked fine because the env vars were getting set properly. Not sure why it is happening on prod-preview though.

**Comment by jarifibrahim** [comment] 2019-02-13 18:05
> @alexeykazakov For me, logout is not working only if you have enabled `internal` feature flag and are running the new navigation which is in react and has a different way of setting env variables for URLs.
> So, the problem is in the angular part `AUTH_API_URL` is `https://auth.prod-preview.openshift.io/api/logout/v2` and in react part it is coming as `https://prod-preview.openshift.io/api/logout/v2`. While testing it in dev environment it worked fine because the env vars were getting set properly. Not sure why it is happening on prod-preview though.

Wouldn't `apiUrl` always point to WIT irrespective of angular/react being used?
https://github.com/fabric8-ui/fabric8-ui/pull/3513/files#diff-735652f39dbcfbb2d5d95c1f508c9287R77

**Comment by rohitkrai03** [comment] 2019-02-13 18:11
@jarifibrahim No, so value of `apiUrl` is being injected using `AUTH_API_URL` and that is being built from https://github.com/fabric8-ui/fabric8-ui/blob/master/packages/fabric8-ui/src/app/shared/auth-api.provider.ts#L8. In react the api url is being injected in a different way using env config https://github.com/fabric8-ui/fabric8-ui/blob/master/packages/toolchain/src/app/api/internal/api.config.ts#L5.

So, there are two different config variables one for `authApiUrl` and one for `witApiUrl`.

**Comment by jarifibrahim** [comment] 2019-02-13 18:12
> @jarifibrahim No, so value of `apiUrl` is being injected using `AUTH_API_URL` and that is being built from https://github.com/fabric8-ui/fabric8-ui/blob/master/packages/fabric8-ui/src/app/shared/auth-api.provider.ts#L8.

Ah, right.

**Comment by rohitkrai03** [comment] 2019-02-13 18:19
So, i think know why the URL for react is not setting up properly. There is no config map for setting `authApiUrl` in prod-preview deployment, so this line  `export const AUTH_API_URL = config.authApiUrl || FABRIC8_AUTH_API_URL || DEFAULT_URL;` evaluates to `/api/` and it becomes https://prod-preview.openshift.io/api/logout/v2

**Comment by rohitkrai03** [comment] 2019-02-13 18:33
@alexeykazakov Since this is only happening under `internal` feature flag can we remove the `Sev-1`?. And for the quick fix i can add the config map value for auth url in `dsaas-stg` but we would still need to update the config map for prod or add the proxy in WIT.

**Comment by alexeykazakov** [comment] 2019-02-13 19:04
@rohitkrai03 I agree. It's not Sev-1. It will if we promote Internal to Released without fixing it :) I also suspect that other things can fail too. We do not proxy everything from wit to Auth. There are plenty of new API which we introduced in Auth and use from UI directly (not through WIT). So we need to fix the CM in UI. I'm assigning the issue to the UI team.

**Comment by rohitkrai03** [comment] 2019-02-13 19:35
@alexeykazakov I have updated the config maps for `dsaas-stg` and this issue is resolved for prod-preview. I have also raised an issue to update config for `dsaas` - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2560. Once that is closed we can push new changes to prod. I think we can close the current issue since it only mentions prod-preview and its resolved.

**Closed** 2019-02-14 04:14 UTC
Labels: SEV2-high, area/auth, priority/P1, team/ui, type/bug
