### ISSUE TITLE
Add the remaining build notifications to MatterMost to complement the existing ones.

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#557] opened 2017-08-11 18:48 UTC
We need an ongoing/real-time "report" of changes happening to the production environment.  This would allow end-users (those watching MM) to know that elements A, B or C have been updated recently, they might wish to close and re-open their incognito browser session and likely clean/Update Tenant depending on what changed.  They also know to quickly report issues related to the component that was updated.  For instance, today, we have noticed the Applications Tab stopped responding and that the Create Space dialog box has trouble closing.

**Comment by cctrieloff** [comment] 2017-08-11 18:50
showing out update stream to production would be a great transparency feature.

**Comment by bmicklea** [comment] 2017-08-11 18:53
I expect there's a bot / API that we could use from CI to automatically publish the information. Ideally we'd have something like:

`production updated with <asset-version> please [additional instructions like update tenant, reload browser, etc...]`

**Comment by rafabene** [comment] 2017-08-11 18:56
We need to be more DevOps oriented and everytime that there is a new version of a new component we should see it. Each new version should have:

- Version number
- Release Date/time
- Changelog (New features / Bug fixes)

**Comment by bmicklea** [comment] 2017-08-11 18:59
There should also be an indication as to whether tenant update or browser refresh / clear is required (or any other manual user action).

**Comment by rawlingsj** [comment] 2017-08-11 19:00
We currently have hubot slack notifications in the fabric8 pipelines which send updates / requests for interaction during releases.  I added a [hubot mattermost image](https://github.com/fabric8io/hubot-mattermost) a little while back which in theory can be switched in place of our slack one but I've not tested it yet.

One issue would be that fabric8 pipelines do everything apart from the actual production tenant deployment ATM but this is something I'm sure we can figure out.  In short this shouldn't be too hard to do.

**Comment by ldimaggi** [comment] 2017-08-11 23:03
+1 to notifications of when the user should perform a tenant update, or browser refresh. Maybe something along the lines of how eclipse informs users that updates are available?

**Comment by joshuawilson** [comment] 2017-08-14 20:43
@rawlingsj you want me to set up a MM channel for it? I don't know that we want it in the main channel.

**Comment by rawlingsj** [comment] 2017-08-14 20:59
@joshuawilson thanks, we can hold off setting up the MM channel until ready to try it out which is unlikely to be this week.

**Comment by rawlingsj** [comment] 2017-08-14 20:59
Just another thought on this; I wonder if there's two things here, one short term another which might be more involved but could be a great feature...

1. __short term__ send chat (mattermost) notifications when new tenant updates are available
2. __long term__ have a more advanced info messaging feature, maybe like a stackoverflow type thing where folks can asynchronously get updates about new releases / features + notifications

Does that sound useful?

**Comment by bmicklea** [comment] 2017-08-15 14:45
@rawlingsj +1. For #2 some kind of automated message that explains the release version and includes a link to release notes and changelog would be idea.

**Comment by rawlingsj** [comment] 2017-08-15 14:54
> some kind of automated message that explains the release version and includes a link to release notes and changelog would be idea.

Yeah exactly that!  It would also be a pretty nice way to let folks know about experimental features, how to toggle them on/off etc.

**Comment by joshuawilson** [comment] 2017-08-15 18:12
The problem is this is a SaaS not a product that lives by a release schedule. The best you can do is compile a list of the commits as they happen across all the repos that are brought together to form the service.

**Comment by bmicklea** [comment] 2017-09-10 23:52
What happened with this?  Was it completed?  If so what's the MM channel name?

**Comment by joshuawilson** [comment] 2017-09-11 03:04
@bmicklea last week @rawlingsj was working on getting it set up on MM. I believe he needed a few things set in place and it should be working early this week.

**Comment by rawlingsj** [comment] 2017-09-11 08:43
@joshuawilson @bmicklea last week I validated we can receive the existing hubot pipeline notifications in mattermost (we currently get them in slack).  I now have an internal issue requesting MM config changes which we need to enable these notifications https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/524.

FWIW this doesn't include notifications when new tenant versions are available for the tenant service to deploy.  This will require a bit more work and until the internal issue above is resolved I'm not planning on doing anything more with our chatops features.

**Comment by joshuawilson** [comment] 2017-09-27 05:27
What needs to be done next? Is what we have enough?

**Comment by kbsingh** [comment] 2017-09-27 07:19
the push-to-prod has been reported to mattermost for the last 8 months or so.

**Comment by rawlingsj** [comment] 2017-09-27 12:15
reassigning back to you @kbsingh as I'm still waiting for the token as per the email :)

**Comment by kbsingh** [comment] 2017-09-27 12:27
unsure why we need the user-token, the other 40 odd integrations have not needed it. There is no schedule to get user-tokens onboarded, so we should block / close this issue for now.

**Comment by rawlingsj** [comment] 2017-09-27 12:48
we use [hubot](https://hubot.github.com/) as the integration which requires a personal access token so notifications can be sent from the fabric8 bot.

**Comment by rawlingsj** [comment] 2017-09-27 13:02
Is this issue a severity P1? as @kbsingh mentions its just the pipeline notifications that aren't going to MM yet, prod deployments done by centos ci are being done.

**Comment by joshuawilson** [comment] 2017-09-27 19:08
The severity/priority was set by @burrsutter. If he doesn't respond, then maybe @rafabene or @qodfathr can comment.

**Comment by rafabene** [comment] 2017-09-28 01:16
I don't think it should be P1, but I'll defer to @burrsutter

**Comment by rawlingsj** [comment] 2017-09-28 06:53
As it happens I think this is still pretty important. We really do need to have the pipeline notifications in mattermost.

**Comment by joshuawilson** [comment] 2017-10-11 06:06
@rawlingsj based on your demo this appears done. Is there something else that needs to be done or can we close this?

**Comment by rawlingsj** [comment] 2017-10-11 12:49
@kbsingh which mattermost channel are the prod deployment events being sent to?  I've had a little look but cant find them, once we know that yeah I think this issue can be closed.

**Comment by qodfathr** [comment] 2018-01-17 01:06
@kbsingh looks like the last question before we can close was directed at you.

**Comment by kbsingh** [comment] 2018-01-18 02:53
content is reported to the servicedel channel

**Closed by kbsingh** 2018-01-18 02:53 UTC
Labels: SEV2-high, status/blocked, team/service-delivery, type/task
