### ISSUE TITLE
Authorization: Avoid somes users to change deployment resources

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#1442] opened 2017-11-22 12:47 UTC
Some users should not be allowed to change the memory limit or other deployment resources like number of replicas, etc.

We should also be able to limit users who can promote an app to a specific environment

**Comment by joshuawilson** [comment] 2017-11-22 20:47
Can you please be more clear in how to reproduce this?

**Comment by kbsingh** [comment] 2017-11-24 11:16
this would be smething for the platform team, and the tenant service sine thats where the role bindings are setup - but i would like to see, as @joshuawilson said, a reproducer and specifics around which part of a tenant service is the user able to edit quotas for.

**Comment by qodfathr** [comment] 2018-01-23 20:58
Is this still a valid issue?

**Comment by joshuawilson** [comment] 2018-01-23 23:16
@qodfathr do you want this? 
cc @aslakknutsen

**Comment by aslakknutsen** [comment] 2018-01-24 18:07
We can't support this in OSO Free, as only 1 user can have access to a namespace. This would be part of the general 'Collaboration' model.

**Comment by qodfathr** [comment] 2018-01-31 23:05
This does not really apply to OSIO in its current incarnation. If we end up scoping out work for other environments (OSO Pro, OSD, etc.), we'll likely end up specifying features similar to this one, but I'll keep this on the backlog for now.

**Comment by mmclanerh** [comment] 2018-06-26 05:58
this has been untouched since jan and there are significant limits on oso (Free). closing.

**Closed by mmclanerh** 2018-06-26 05:58 UTC
Labels: area/user/tenant, team/platform, team/service-delivery, type/SDD-feature
