### ISSUE TITLE
Can't create new space and quickstart

### ISSUE THREAD

**Issue by pbergene** [openshiftio/openshift.io#1507] opened 2017-12-05 11:48 UTC
I reset my space today, deleting from tenant database and doing re-init.  It seems I am unable to do the vertx quickstart.  The github repository is created, but subsequently fails.

Account: pbergene+osiotest1
GH: https://github.com/pbergeneOsiotest1

Reproduce: Reset account, create new space, add codebase, vertx quickstart, next, next, next, ok.
Hangs at loading wizard a little (page 3a summary) and then shows error: Error. Something went wrong while attempting to perform this operation ... "The repository absolutelyfreeandnottaken already exists!" 

Setting Sev1 - will be downgraded if impact is not service-wide.

**Comment by pbergene** [comment] 2017-12-05 11:51
Already reported at https://github.com/openshiftio/openshift.io/issues/1504

**Comment by ldimaggi** [comment] 2017-12-05 12:15
Actualy - it was first reported here:  https://github.com/openshiftio/openshift.io/issues/1503

**Comment by maxandersen** [comment] 2017-12-05 12:19
closing as duplicate of #1503

**Closed by maxandersen** 2017-12-05 12:19 UTC
Labels: SEV1-urgent
