### ISSUE TITLE
Can't see applications - pipelines are not visible in OSIO UI

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#3315] opened 2018-04-26 03:14 UTC
I have tried several scenarios
- In incognito, without incognito
- Tried reseting my environment
- Tried quickstart projects
- Tried adding importing the code
Nothing seems to show me my applications

![screenshot from 2018-04-26 08-40-56](https://user-images.githubusercontent.com/10185999/39283793-9de28a12-492d-11e8-9ed4-c1fdd9dbe1d4.png)

**Comment by ldimaggi** [comment] 2018-04-26 03:29
I am seeing the same thing. If you open the Chrome browser console - you see a stream of these errors:
```
_scrollbars.less:6 WebSocket connection to 
'wss://openshift.io/oapi/v1/namespaces/username/builds?
watch=true&access_token=.....' failed: Error during 
WebSocket handshake: Unexpected response
 code: 200
```

**Comment by ldimaggi** [comment] 2018-04-26 03:59
The problem is worse than originally logged.

If you set the Features Opt-In to 'Production' - and create a new space and quickstart - the quickstart pipeline is not created.

**Comment by joshuawilson** [comment] 2018-04-26 04:11
Is this a duplicate of #3291 or #3314

**Comment by joshuawilson** [comment] 2018-04-26 04:26
I'm setting this back to SEV1. I can't see anything for the pipeline/build.

I'm getting 
`Error retrieving list BuildConfigs: SyntaxError: Unexpected token < in JSON at position 0`

followed by a 500 on the deployments. 

@pradeepto @rupalibehera @chmouel @sthaha @jaseemabid can you take a look

**Comment by aslakknutsen** [comment] 2018-04-26 04:28
Probable root casue: https://github.com/openshiftio/openshift.io/issues/3290

**Comment by sthaha** [comment] 2018-04-26 05:24
Adding to @ldimaggi's observation that pipelines are created in openshift and the builds run in Jenkins but the UI seems to not reflect that.

**Comment by aslakknutsen** [comment] 2018-04-26 07:38
The reason the pipelines don't show up is that they use the wrong OSO URL, which is due to a UI Config Load order issue.

**Comment by jiekang** [comment] 2018-04-26 12:35
Len's error:
```
_scrollbars.less:6 WebSocket connection to 
'wss://openshift.io/oapi/v1/namespaces/username/builds?
watch=true&access_token=.....' failed: Error during 
WebSocket handshake: Unexpected response
 code: 200
```

is most likely: https://github.com/openshiftio/openshift.io/issues/2200

**Comment by jiekang** [comment] 2018-04-26 12:49
It's a little scary how consistent this is seen now compared to before though.

**Comment by jiekang** [comment] 2018-04-26 12:51
Actually it looks like some config on the production deployment changed.

@aslakknutsen @joshuawilson @ldimaggi 

The url is acquired from a request to `https://openshift.io/_config/oauth.json`


The response in production is now:
```
{
  "analytics_recommender_url": "https://recommender.api.openshift.io/",
  "analytics_license_url": "https://license-analysis.api.openshift.io/",
  "api_server": "",
  "api_server_base_path": "",
  "api_server_protocol": "https",
  "forge_api_url": "",
  "openshift_console_url": "https://console.starter-us-east-2.openshift.com/console/",
  "proxy_api_server": "",
  "recommender_api_url": "",
  "sso_api_url": "",
  "wit_api_url": "",
  "auth_api_url":"",
  "ws_api_server": "",
  "ws_api_server_base_path": "",
  "ws_api_server_protocol": "",
  "oauth": {
    "oauth_authorize_uri": "https://api.starter-us-east-2.openshift.com:443/oauth/authorize",
    "oauth_client_id": "fabric8",
    "oauth_issuer": "https://api.starter-us-east-2.openshift.com:443",
    "oauth_scope": "user:full",
    "logout_uri": ""
  }
}
```

These fields were not empty before. What changed?

Compare to a local deployment targeting production:

```
{
  "analytics_recommender_url": "",
  "analytics_license_url": "",
  "api_server": "f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com:443",
  "api_server_base_path": "",
  "api_server_protocol": "https",
  "forge_api_url": "https://forge.api.openshift.io",
  "openshift_console_url": "https://console.starter-us-east-2.openshift.com:443/console",
  "proxy_api_server": "f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com:443",
  "recommender_api_url": "undefined",
  "sso_api_url": "https://sso.openshift.io/",
  "wit_api_url": "https://api.openshift.io/api/",
  "auth_api_url":"https://auth.openshift.io/api/",
  "ws_api_server": "f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com:443",
  "ws_api_server_base_path": "",
  "ws_api_server_protocol": "wss",
  "oauth": {
    "oauth_authorize_uri": "https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com:443/oauth/authorize",
    "oauth_client_id": "fabric8",
    "oauth_issuer": "https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com:443",
    "oauth_scope": "user:full",
    "logout_uri": "https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com:443/connect/endsession?id_token={{id_token}}"
  }
}
```

**Comment by joshuawilson** [comment] 2018-04-26 12:58
those fields are filed in for local dev but are empty for prod so that they can be set via the Saashearder

**Comment by jiekang** [comment] 2018-04-26 13:02
The runtime-console code uses the fields from the response of `https://openshift.io/_config/oauth.json` directly. Would it be possible to revert them from being empty? They can be 'overwritten' either way, no?

**Comment by jiekang** [comment] 2018-04-26 13:05
The alternative is to rewrite the code to use whatever is available now to get the correct URL. If a function is already available that returns the correct URL, the fix would be straightforward.

**Comment by joshuawilson** [comment] 2018-04-26 16:53
What URL are you trying to return?

**Comment by jiekang** [comment] 2018-04-26 17:56
It should look like:

```
{
  "analytics_recommender_url": "https://recommender.api.openshift.io/",
  "analytics_license_url": "https://license-analysis.api.openshift.io/",
  "api_server": "f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com",
  "api_server_base_path": "/",
  "api_server_protocol": "https",
  "forge_api_url": "",
  "openshift_console_url": "https://console.starter-us-east-2.openshift.com/console/",
  "proxy_api_server": "",
  "recommender_api_url": "",
  "sso_api_url": "",
  "wit_api_url": "",
  "auth_api_url":"",
  "ws_api_server": "f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com",
  "ws_api_server_base_path": "",
  "ws_api_server_protocol": "",
  "oauth": {
    "oauth_authorize_uri": "https://api.starter-us-east-2.openshift.com:443/oauth/authorize",
    "oauth_client_id": "fabric8",
    "oauth_issuer": "https://api.starter-us-east-2.openshift.com:443",
    "oauth_scope": "user:full",
    "logout_uri": ""
  }
}
```

**Comment by joshuawilson** [comment] 2018-04-26 17:58
I think we found it. 
The new IMAGE env var setting does not read all the env var the system needs.

**Comment by joshuawilson** [comment] 2018-04-26 18:25
This change https://github.com/openshiftio/saas-openshiftio/pull/817 fixed the issue. The reason is being researched but everything should work now.

**Closed by joshuawilson** 2018-04-26 18:25 UTC
Labels: SEV1-urgent, area/deployments, area/pipelines, priority/P0, team/build-cd, team/platform, type/bug

**Comment by ldimaggi** [comment] 2018-04-26 18:42
The pipelines are visible again.

![screenshot from 2018-04-26 14-40-48](https://user-images.githubusercontent.com/642621/39325388-03ebc94a-4960-11e8-85c1-e95b58ab3db1.png)
