### ISSUE TITLE
GitHub connection - connect/disconnect UI problem

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2719] opened 2018-03-21 23:19 UTC
I'm testing the GitHub connect part by disconnecting my GitHub account and seeing what it lets me do without prompting for the GitHub connection. IMO, this should probably happen when we create the account as before because it's causing some weird issues to pop up. For example:

The disconnection part in the `Profile` page is displaying odd issues. The screenshot displays an isssue where I have a connect and disconnect button and my account is disconnected but also displays my GH username next to Disconnected and a blue icon which indicates connected, AFAIK. See below:

![weird](https://user-images.githubusercontent.com/926572/37742574-e4216ac6-2db1-11e8-96c6-d141f3383d66.png)

This went away after a refresh. I can try to replicate and post but IIRC, it happened after I created a space, disconnected GH and tried to create a second space, but it did work, so I looked into Profile to investigate what had happened.

**Comment by alexeykazakov** [comment] 2018-03-22 02:16
I can't reproduce it. Looks like the known refresh issue? @joshuawilson @dgutride?

**Comment by joshuawilson** [comment] 2018-03-22 05:34
that sounds right, though I haven't seen it either

**Comment by dgutride** [comment] 2018-03-22 12:04
haven't seen it either - please try to create a reproducible example with exact steps and any errors in the browser console @mishaone

**Comment by joshuawilson** [comment] 2018-10-23 21:03
closing as can't reproduce

**Closed by joshuawilson** 2018-10-23 21:03 UTC
Labels: SEV4-low, issue/intermittent, priority/P4, team/auth, type/bug
