### ISSUE TITLE
[RFE] [UX]: The info about the stack analysis is not prepared on the Pipeline view, but the Stack analysis link is displayed (w/o additioal icon)

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1808] opened 2018-01-10 11:39 UTC
Scenario:

1) new project is created
2) click on the Pipelines link from the Space
3) the pipeline is displayed (OK)
4) under the "Build Release" there's link to Stack analysis
5) click on the Stack analysis -> the info that the analysis is not yet done is printed

RFE: display some form of icon next to the Stack analysis link to display current status

**Comment by krishnapaparaju** [comment] 2018-01-12 06:10
@arunkumars08 @jyasveer please test this out as part of UX revamp work , due by end of sprint # 143.

**Comment by arunkumars08** [comment] 2018-01-31 06:28
@tisnik Currently, by design, we don't have any feature that shows the progress of the stack analysis report.

What happens when you **click** on stack report link as soon as build is done, may be one of the following

1. It can immediately give you the desired report if analysis had been faster.
2. It shows a message saying it is still generating report or some kind and asks the user to check back.
3. Error message in case there occurs some problem with the report.

Hope, I understood your question correctly.

**Comment by sunilk747** [comment] 2018-02-08 02:58
@tisnik  If you are clear with your doubts can you please close this issue.

**Comment by sunilk747** [comment] 2018-02-14 04:29
Closing this issue as this case is handled as part of UI revamp. Please reopen it if you find it otherwise.

**Closed by sunilk747** 2018-02-14 04:29 UTC
Labels: SEV4-low, area/UX, area/analytics, status/info-needed, team/analytics, type/bug
