### ISSUE TITLE
Space is not loaded in my browser

### ISSUE THREAD

**Issue by pkettman** [openshiftio/openshift.io#1053] opened 2017-10-04 13:08 UTC
After a week I've logged again to OSIO and can't get back to my space or account. 
I am getting 404 on https://openshift.io/pkettman/PKE_Space/ or https://openshift.io/pkettman/, my OSIO home looks like this:
![osio_oct4th](https://user-images.githubusercontent.com/26871874/31177145-533752c6-a915-11e7-8f1e-c02603794b15.png)
I am using Chrome 56.0.2924.87 Fedora Project (64-bit). SBose investigated it and can access https://openshift.io/pkettman/PKE_Space.

**Comment by alexeykazakov** [comment] 2017-10-04 21:43
I can reproduce it in my Firefox. It works fine in my chrome though.
The problem looks like in redirects. For some reason my Firefox doesn't follow 307 redirects. Maybe it's because we send these requests via Ajax.
Can someone from the UI team take a look?
There is a bunch of 307 responses (to AJAX requests) which redirect from api.openshift.io to auth.openshift.io But some browsers doesn't follow this redirects.

@joshuawilson ?

**Comment by pkettman** [comment] 2017-10-06 12:39
Additional info: the issue was detected on Chrome 56.0.2924.87 Fedora Project (64-bit) and Firefox 52.0 (64-bit), on another hand it works fine on Google Chrome Verze 61.0.3163.100 (64-bit).

**Comment by alexeykazakov** [comment] 2017-10-06 21:39
https://github.com/fabric8-services/fabric8-wit/pull/1694 should fix that

**Comment by alexeykazakov** [comment] 2017-10-07 19:03
It now works for me in prod-preview in my FF (after merging https://github.com/fabric8-services/fabric8-wit/pull/1694). But we haven't promoted it to prod yet.

**Comment by alexeykazakov** [comment] 2017-10-09 18:56
Should be fixed now in prod. It works in my FF now.

**Closed by alexeykazakov** 2017-10-09 18:56 UTC
Labels: team/auth, team/platform
