### ISSUE TITLE
Seeing this randomly today - stage icon is sometimes deleted from the UI display

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1894] opened 2018-01-16 20:58 UTC
Nothing in the logs - notice how the icon is not present on the first pipeline.

![screenshot 2](https://user-images.githubusercontent.com/642621/35011953-fe5844a0-fad5-11e7-86e4-c9526b6e6af0.png)

**Comment by qodfathr** [comment] 2018-01-17 13:50
Closing as dupe of #456.

**Closed by qodfathr** 2018-01-17 13:50 UTC
Labels: SEV3-medium, area/pipelines, team/build-cd, type/bug

**Comment by ldimaggi** [comment] 2018-02-01 20:14
Issue found/encountered by EE tests.
