### ISSUE TITLE
Jenkins login does not work reliably

### ISSUE THREAD

**Issue by mmatsuya** [openshiftio/openshift.io#3026] opened 2018-04-12 05:56 UTC
On the click party in Apr 12, I followed https://docs.openshift.io/getting-started-guide.html to run helloworldvertx. The build pipeline started. And it stuck in the Approve stage.
Even after the Promote button was clicked, it cannot go forward. It still stopped in the Approve stage.

This is similar to https://github.com/openshiftio/openshift.io/issues/2119.
But, a workaround (to click "View Log") in it didn't work. When I clicked "View Log", another tab was created on the browser with the following error text.

{"Errors":[{"code":"500","detail":"could not login to Jenkins in mmatsuya-jenkins namespace"}]}<a href="https://auth.openshift.io/api/login?redirect=https:%2F%2Fjenkins.openshift.io%2Fjob%2Fmmatsuya%2Fjob%2Fhelloworldvertx%2Fjob%2Fmaster%2F1%2Fconsole">Moved Permanently</a>.

After a while, when I click 'Input Required' again, the same error as above was output, not without any dialog to show Promote button any more.

Possible workaround (2018-05-02): If you see this error 5000 go to your Settings and reconnect openshift. If that fixes it for you please let us know.

**Comment by ldimaggi** [comment] 2018-04-12 18:56
Is this problem reproducible now? Thx!

**Comment by mmatsuya** [comment] 2018-04-13 03:42
Yes, it's still reproducible.

**Comment by ldimaggi** [comment] 2018-04-13 13:24
I have not been able to recreate this error:

![screenshot from 2018-04-13 09-23-46](https://user-images.githubusercontent.com/642621/38737170-67893e24-3efc-11e8-8dc8-a4ec5896a1d7.png)

Do you still see this error if you resent the environment from your profile? Thx!

**Comment by mmatsuya** [comment] 2018-04-17 05:03
What I did are..

1) go and login to https://openshift.io/_home
2) select a created space in "Recent spaces"
3) click "Add to space" in Pipelines.
4) click "import existing code"
5) select "helloworldvertx2" and click Next.
6) select "Release, stage, approve and promote", and click Next.
    NOTE: "Override jenkins and POM files" is selected by default. I didn't
change it.
7) just click Finish in the screen including Jenkins space, and so on.
8) click "OK"
9) select the running pipelines in Pipelines, wait until it reaches Approve
stage.
10) click "Input Required" and "Promote", and it cannot go to the next
stage.
11) click "View Log", and see the following error in a new tab.

{"Errors":[{"code":"500","detail":"could not login to Jenkins in
mmatsuya-jenkins namespace"}]}<a href="
https://auth.openshift.io/api/login?redirect=https:%2F%2Fjenkins.openshift.io%2Fjob%2Fmmatsuya%2Fjob%2Fhelloworldvertx2%2Fjob%2Fmaster%2F1%2Fconsole">Moved
Permanently</a>.

Thanks,
Masahiro

**Comment by kishansagathiya** [comment] 2018-04-20 06:00
I followed the exact steps as mentioned here, was not able to reproduce it. My build passed just fine. I didn't have to go to view logs to approve it. I did it all from OSIO. 

I think the real issue here is `could not login to Jenkins in
mmatsuya-jenkins namespace`, and couldn't have much to do with promote button. It could be because of RedHat Developer Login. 
Some Problems with RH-Dev Login
- I remember it automatically logging me out. At times it acts really weird. 
![screenshot from 2018-03-21 12-22-36](https://user-images.githubusercontent.com/10185999/39032974-89604290-448d-11e8-9d39-e8369a10f1bd.png)
I remember @Preeticp and @rgarg1 facing this as well. Can you confirm that here? Direct us to an issue if you have created.

- I logged in to OSIO using my RH-Dev Account. If I go to jenkins.openshift.io, it asks me to login again to RH-Dev, what's up with that?

- After providing login credentials and clicking on login button, it logs you in, but it doesn't redirect. It remains on the same page. Only thing you can do is manually go to OSIO home page. This one exists since as long as I can rememeber.

**Comment by kishansagathiya** [comment] 2018-04-20 06:58
{"Errors":[{"code":"500","detail":"could not login to Jenkins in
mmatsuya-jenkins namespace"}]}<a href="
It is genereated by the proxy.go: 278 ...

**Comment by sthaha** [comment] 2018-04-20 06:59
I tried the same steps as well and wasn't able to reproduce the issue.  @mmatsuya did you by any chance look at the state of your `jenkins` namespace in the openshift cluster? Specifically interested in the pods that were running and the state of jenkins master.

What I gather from the error message is that 

```
{"Errors":[{"code":"500","detail":"could not login to Jenkins in
mmatsuya-jenkins namespace"}]}<a href="
https://auth.openshift.io/api/login?redirect=https:%2F%2Fjenkins.openshift.io%2Fjob%2Fmmatsuya%2Fjob%2Fhelloworldvertx2%2Fjob%2Fmaster%2F1%2Fconsole">Moved
Permanently</a>.
```

Jenkins proxy failed to login to the underlying openshift cluster https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/b7717758591f6655ba07a23d280be2eca481d9be/internal/proxy/proxy.go#L278
 
I am not sure of the reason but my wild guess is that  if this would happen if the osioToken passed to jenkins-proxy just expired and needed a refresh. 

/cc @kishansagathiya @sbose78

**Comment by kishansagathiya** [comment] 2018-04-20 07:02
>I am not sure of the reason but my wild guess is that if this would happen if the osioToken passed to jenkins-proxy just expired and needed a refresh.

@sthaha osioToken takes 30 days to expire, so it is unlikely that it needed a refresh.

**Comment by kishansagathiya** [comment] 2018-04-20 07:05
If this is related to proxy and login, it could be because of https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/165

**Comment by sthaha** [comment] 2018-04-20 07:32
@kishansagathiya but we can be sure that from the error message it seems to a failure at - https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/b7717758591f6655ba07a23d280be2eca481d9be/internal/proxy/proxy.go#L254 , can't we?

**Comment by kishansagathiya** [comment] 2018-04-20 07:34
> but we can be sure that from the error message it seems to a failure at - https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/b7717758591f6655ba07a23d280be2eca481d9be/internal/proxy/proxy.go#L254 , can't we?

Yes

**Comment by kishansagathiya** [comment] 2018-04-20 08:10
@hrishin was also not able to reproduce this. I think it would safe to change it to SEV2, clearly this is intermittent.

**Comment by ldimaggi** [comment] 2018-04-20 13:08
Is this problem appearing to be intermittent because all promote requests are funneled through a single Jenkins service and a limit is hit?  If this is the case, the intermittent nature of the bug may make sense as the problem is dependent on multiple users all performing a promote operation at the same time?

**Comment by rgarg1** [comment] 2018-04-23 13:06
@kishansagathiya I can confirm that I've encountered this issue many times, but sadly this is very intermittent in nature and there are no steps to reproduce this issue consistently.

**Comment by rohanKanojia** [comment] 2018-04-23 13:52
Hi, I tried the above-mentioned steps but it seemed to be working fine in my case.
Build logs: https://pastebin.com/8Np5cqD5
Please find the screenshot attached also.
![screenshot from 2018-04-23 19-20-49](https://user-images.githubusercontent.com/13834498/39130779-94d4d47e-472b-11e8-8632-a076d156be78.png)

**Comment by kishansagathiya** [comment] 2018-04-23 14:32
I believe by now enough people ( 6 to be precise) have failed to reproduce this issue. Either this is intermittent or doesn't exist, but anyway we don't have a reason to work on this unless we see this again.

**Comment by kishansagathiya** [comment] 2018-04-24 03:44
@mmatsuya We are not closing it. Just parking it until we are able to reproduce it.

**Comment by ldimaggi** [comment] 2018-04-24 04:01
I did see a similar issue today: https://github.com/openshiftio/openshift.io/issues/3264

But - it turned out to be non-reproducible.

**Comment by kishansagathiya** [comment] 2018-04-24 04:13
@ldimaggi Could this have something to do with the region we are in? Because some RHD related issues which I (India) face are not seen by people in Australia.

**Comment by lordofthejars** [comment] 2018-04-24 07:33
In my case I have been able to reproduce it. Or at least it happens to me always.

**Comment by joshuawilson** [comment] 2018-04-24 13:47
@lordofthejars can you try in Released mode in incognito to make sure it isn't a cache issue.

**Comment by lordofthejars** [comment] 2018-04-24 14:14
@joshuawilson I tried in incognito window (Chrome) + Production Features and it worked to me perfectly.

**Comment by joshuawilson** [comment] 2018-04-24 20:16
I downgraded it since it can NOT be reliably reproduced.

**Comment by maxandersen** [comment] 2018-04-24 22:17
if the issue is not present anymore then lets close it; but if believed still present then its still open and we can state why we think it shouldn't be p0 anymore.

**Comment by joshuawilson** [comment] 2018-04-25 02:04
@chmouel @kishansagathiya do you want to keep this open?

**Comment by joshuawilson** [comment] 2018-04-25 02:48
it might be a race condition not a caching issue

**Comment by kishansagathiya** [comment] 2018-04-25 02:50
@maxandersen @joshuawilson There were several duplicate issues found during click party, so this definitely a valid issue. I think @joshuawilson has closed those duplicate issues. I think it needs little more investigation or we can keep this park until someone is able to reproduce it.

**Comment by joshuawilson** [comment] 2018-04-25 02:51
If this is reproducible then we need to set it back to SEV2 and maybe P0.

**Comment by kishansagathiya** [comment] 2018-04-25 02:53
> If this is reproducible then we need to set it back to SEV2 and maybe P0.

None of us(around 6 people) were able to reproduce it.

**Comment by joshuawilson** [comment] 2018-04-25 02:54
except all the duplicate issues I'm closing, they can do it

**Comment by kishansagathiya** [comment] 2018-04-25 02:58
> except all the duplicate issues I'm closing, they can do it
So it could be intermittent. Look at this click party issue (https://github.com/openshiftio/openshift.io/issues/3027#issue-313586765), logs are exactly same.
As @ldimaggi mentioned it could also be because of increase traffic.

**Comment by mattd72** [comment] 2018-04-25 12:00
Can confirm that https://github.com/openshiftio/openshift.io/issues/3056 is a duplicate of this issue.

**Comment by kishansagathiya** [comment] 2018-04-25 12:17
Thanks a lot @mattd72

**Comment by maxandersen** [comment] 2018-04-25 16:10
I just saw this issue in prod-preview.

incognito mode and all did and does not help.

Its on an account that probably haven't seen me log in for a while so could be a token expiry - its for account `manderse-madman` if anyone wants to go look closer to it.

**Comment by ldimaggi** [comment] 2018-04-25 17:16
I am not able to recreate this issue on prod-preview - but - my account is used almost daily.

**Comment by mmatsuya** [comment] 2018-04-26 02:35
I tried it in incognito mode, but now I cannot create an application at all.
I selected "mmatsu space" as a space, and clicked 'Create an application'.
Select 'Create a new Quickstart project'. Select 'Vert.x HTTP Booster'.
Changed into 'helloworldvertx4" in OpenShift Project name.
Selected 'Release, Stage, Approve and Remote'. And just clicked next or
finish without any change. And, I didn't see any application on the
Applications field. It just output "This space has no applications" even
after a few minutes and reloading the page. This may be another problem.
My test environment was CSB with RHEL7 and google-chrome-stable was used.

I tested it on another rhel7, which was created a kvm guest newly. And,
chromium in epel7 was used as browser. I logged into openshift.io with the
same account, and create a new space. and followed above steps except for
"helloworldvertx5 as the OpenShift Project name. And again, application is
not created, or it's not displayed on the Applications field. not sure how
I can help for this case now.

**Comment by joshuawilson** [comment] 2018-04-26 02:44
Is it possible this has to do with the issue where the new launcher wizard has a name and app name that don't match?

**Comment by maxandersen** [comment] 2018-04-26 06:25
renaming this issue since it seems to have very little if anything to do with the promote button but simply about jenkins auth/login issues when trying to get to it.

Also now observed in production by @aslakknutsen it seems.

**Comment by maxandersen** [comment] 2018-04-26 08:14
noticing that in prod-preview my user cannot see its jenkins namespace. I can see everything else.

**Comment by maxandersen** [comment] 2018-04-26 08:16
![2018-04-26_10-15-36](https://user-images.githubusercontent.com/54129/39294016-dabec6f0-493a-11e8-8205-920ff15a0602.png)

notice how `manderse-madman-jenkins` are missing

**Comment by aslakknutsen** [comment] 2018-04-26 13:24
Currently investigating a RoleBinding issue related to cluster: 2a

**Comment by ldimaggi** [comment] 2018-04-26 13:39
See this issue - https://github.com/openshiftio/openshift.io/issues/3322

Tako is seeing the same problem as Max is seeing in #3026

**Comment by kishansagathiya** [comment] 2018-04-27 02:37
@maxandersen 
> could anyone who see this error check if they can see their jenkins namespace or not ?

For prod, I can see my Jenkins namespace. 
For Prod-preview, Can't get to links to go to OSO, because of this https://github.com/openshiftio/openshift.io/issues/3335
Not sure if I can access OSO directly

**Comment by kishansagathiya** [comment] 2018-04-27 03:29
@maxandersen Shouldn't `not showing Jenkins namespace` be a separate issue?

**Comment by kishansagathiya** [comment] 2018-04-27 06:52
@mmatsuya  Can you check what is your openshift cluster? We would be able to check that based on the url you see when you move to openshfit from openshift.io

**Comment by kishansagathiya** [comment] 2018-04-27 08:32
Finally I was able to reproduce this issue. 
As @aslakknutsen  mentioned the view roles problem with 2a cluster, is what is causing us to not see our jenkins namespace. 
I think this `could not login to Jenkins in ksagathi-preview-jenkins namespace` problem is also because of thta
```
{"component":"tenant","id":"7219a11c-f86a-4db1-ab3e-83216ff53009","level":"info","msg":"Tenant by id","time":"2018-04-27T13:59:27+05:30","type":"id","url":"http://localhost:9002"}
{"level":"info","msg":"Jenkins is unidle, Yay!!","time":"2018-04-27T13:59:28+05:30"}
{"component":"proxy","level":"info","msg":"Jenkins login for https://jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/securityRealm/commenceLogin?from=%2F","ns":"ksagathi-preview-jenkins","request-hash":4016740955,"time":"2018-04-27T13:59:28+05:30"}
{"level":"info","msg":"StatusCodeƑ","time":"2018-04-27T13:59:29+05:30"}
{"component":"proxy","error":"could not login to Jenkins in ksagathi-preview-jenkins namespace","level":"error","location":" github.com/fabric8-services/fabric8-jenkins-proxy/internal/proxy.(*Proxy).handleJenkinsUIRequest[/home/ksagathi/golang/idler/src/github.com/fabric8-services/fabric8-jenkins-proxy/internal/proxy/proxy.go:309]","msg":"Error Handling proxy request request.","request-hash":4016740955,"time":"2018-04-27T13:59:29+05:30"}
2018/04/27 13:59:29 http: multiple response.WriteHeader calls
```

**Comment by aslakknutsen** [comment] 2018-04-28 00:28
The role view issue on 2a should now be resolved for all users.

**Comment by kishansagathiya** [comment] 2018-04-28 03:16
@mmatsuya 
> The role view issue on 2a should now be resolved for all users.

After this fix, I reset my environment (OSIO Homepage > Profile > Update Profile > Reset Environment )
Now I am able to see my Jenkins Namespace in OpenShift
And I don't see `could not login to Jenkins` anymore.

Can you try if you still face this issue?

**Comment by aslakknutsen** [comment] 2018-04-28 09:32
Fyi, a env reset is done automatically

**Comment by kishansagathiya** [comment] 2018-04-28 11:35
@aslakknutsen 
> Fyi, a env reset is done automatically

Hmm, but I had to reset it manually to see my namespace. But that's a good new.

**Comment by aslakknutsen** [comment] 2018-04-28 18:10
@kishansagathiya your prod or preview account?

**Comment by kishansagathiya** [comment] 2018-04-29 04:35
prod-preview

**Comment by lordofthejars** [comment] 2018-04-30 08:24
I opened this issue which might be related to promotion issue but not sure https://github.com/openshiftio/openshift.io/issues/3356 so we can close if it is the case.

**Comment by kishansagathiya** [comment] 2018-04-30 09:30
After https://github.com/openshiftio/openshift.io/issues/3322#event-1601145909 I think it would be safe to close this as well, 
just waiting for a confirmation from @mmatsuya to check if this issue is still faced?

**Comment by maxandersen** [comment] 2018-04-30 12:09
I had the same error today on prod: 

```{"Errors":[{"code":"500","detail":"could not login to Jenkins in manderse-jenkins namespace"}]}<a href="https://auth.openshift.io/api/login?redirect=https:%2F%2Fjenkins.openshift.io%2F">Moved Permanently</a>.
```

thus I think #3322 was another issue.

**Comment by maxandersen** [comment] 2018-04-30 12:10
> I opened this issue which might be related to promotion issue but not sure #3356 so we can close if it is the case.

#3356 is about promotion; this one is about auth/open jenkins failing somehow (independent of promotion workflow)

**Comment by kishansagathiya** [comment] 2018-04-30 13:38
@maxandersen 
> I had the same error today on prod:

Since, I am not able to reproduce it, can you provide me logs for this?

**Comment by kishansagathiya** [comment] 2018-05-01 04:27
@mmatsuya @maxandersen Also which cluster are you on?

**Comment by kishansagathiya** [comment] 2018-05-01 05:13
> ut, a workaround (to click "View Log") in it didn't work. When I clicked "View Log", another tab was created on the browser with the following error text.
{"Errors":[{"code":"500","detail":"could not login to Jenkins in mmatsuya-jenkins namespace"}]}Moved Permanently.

What is happening here is that for whatever reason login to Jenkins failed (which is why `could not login to Jenkins` ). Now since login failed it tries to redirect to auth service, but instead it shows me a link where we want it to redirect. It is very similar to what is happening here https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/235#issuecomment-384185148

Nothing wrong with proxy-logic, it's a weird UI thing. Let me figure out why it behaves this way.

cc/ @pradeepto @maxandersen @krishnapaparaju

**Comment by kishansagathiya** [comment] 2018-05-01 05:25
@mmatsuya @maxandersen by logs I mean network dump, if some request is failing
Also url in the browser while this happens would be helpful as well

**Comment by kishansagathiya** [comment] 2018-05-01 07:31
https://www.reddit.com/r/golang/comments/3loqtq/how_to_redirect_a_user_after_login/

**Comment by mmatsuya** [comment] 2018-05-01 07:53
@kishansagathiya 

> After this fix, I reset my environment (OSIO Homepage > Profile > Update Profile > Reset Environment )
> Now I am able to see my Jenkins Namespace in OpenShift
> And I don't see could not login to Jenkins anymore.
> 
> Can you try if you still face this issue?

I tested it just now, and the problem didn't happen.
After creating an application, it took a few minutes until the application appears on the Application field.
I wondered that the application was created properly since there is no way I can confirm it, but I just waited it for a while. After it appeared on the field. I could monitor the progress by clicking the application on that, and I could promote it on Approve phase without any error.
I can see Console log by clicking "Vlew Log". Looks great.

**Comment by pradeepto** [comment] 2018-05-01 09:08
@mmatsuya What is your recommendation here? Can we close this issue?

**Comment by kishansagathiya** [comment] 2018-05-01 11:28
@maxandersen The redirection has been changed from permanent to temporary with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/250

Do you face this issue on prod-preview?

**Comment by mmatsuya** [comment] 2018-05-02 01:09
> @mmatsuya What is your recommendation here? Can we close this issue?

Yes. closing this case is ok in my side. Now, I can promote in the Approve stage and I don't see the jenkins login error any more.

**Comment by rohanKanojia** [comment] 2018-05-02 20:10
Hi, I've been getting lots of `504 Gateway timeouts` errors all throughout this day which has made accessing Jenkins extremely painful. It's intermittent, but it comes a lot. I've been getting it on 2a cluster : 
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
Not sure what could be causing this issue I see my Jenkins instance running in my openshift console, but still I see this error
![screenshot from 2018-05-03 01-38-19](https://user-images.githubusercontent.com/13834498/39546686-e3708832-4e72-11e8-89cd-f64f7822e647.png)
![screenshot from 2018-05-03 01-38-45](https://user-images.githubusercontent.com/13834498/39546688-e3c47820-4e72-11e8-9d97-c9539c044c0f.png)

**Comment by kishansagathiya** [comment] 2018-05-03 05:10
@rohanKanojia The issue for 504 error https://github.com/openshiftio/openshift.io/issues/3390

**Comment by pradeepto** [comment] 2018-05-03 05:53
@maxandersen @pbergene  It was discussed that we would close this issue, right? Can we close this now?

**Comment by pbergene** [comment] 2018-05-04 08:03
Sounds good, we should also make sure we track the auth work on the older tokens which was one of the issues here.

**Comment by maxandersen** [comment] 2018-05-07 15:52
> Sounds good, we should also make sure we track the auth work on the older tokens which was one of the issues here.

@pbergene you mean the thought the issue could happen if over 30 days since you visited or ?

**Comment by pbergene** [comment] 2018-05-08 07:31
@maxandersen this was in relation to the older, expired tokens that people internal to the team were issued around this time - before we moved to shorter linked tokens.  I think a relink was needed, but I only got a very general picture of this.

**Comment by kishansagathiya** [comment] 2018-05-16 12:14
@krishnapaparaju The issue is not being faced anymore. Same was confirmed by @maxandersen 
We can close this. If we see this again we will reopen it.

**Closed by kishansagathiya** 2018-05-16 12:14 UTC
Labels: SEV2-high, area/jenkins, area/pipelines, issue/intermittent, priority/P0, team/build-cd, type/bug
