### ISSUE TITLE
Feature title - `let's` see translated to `let&#39;s` see

### ISSUE THREAD

**Issue by rsvoboda** [openshiftio/openshift.io#1841] opened 2018-01-10 13:04 UTC
Feature title - `let's` see translated to `let&#39;s` see

![screenshot from 2018-01-10 14-02-14](https://user-images.githubusercontent.com/925259/34774286-08acc104-f60f-11e7-9f19-5c2c93ab12a5.png)

**Comment by michaelkleinhenz** [comment] 2018-01-10 14:54
Dupe of https://github.com/openshiftio/openshift.io/issues/1814

**Closed by michaelkleinhenz** 2018-01-10 14:54 UTC
Labels: area/planner, team/planner, type/bug
