### ISSUE TITLE
Build Stalls at 'Approve' stage

### ISSUE THREAD

**Issue by sclarkso** [openshiftio/openshift.io#3027] opened 2018-04-12 05:56 UTC
Clicking promote doesn't seem to do anything.  Openshift logs showed:

```
Apr 12, 2018 4:08:29 AM io.vertx.core.net.impl.ConnectionBase
--
  | SEVERE: java.io.IOException: Connection reset by peer
```
Couldn't access jenkins logs recieved multiple errors about access jenkins logs:

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"ODUzZWRiOTctYmQ5Zi00"}
```

```
{"Errors":[{"code":"500","detail":"could not login to Jenkins in sclarkso-jenkins namespace"}]}<html><head><meta http-equiv='refresh' content='1;url=/securityRealm/commenceLogin?
```

```
{"Errors":[{"code":"500","detail":"could not login to Jenkins in sclarkso-jenkins namespace"}]}<a href="https://auth.openshift.io/api/login?redirect=https:%2F%2Fjenkins.openshift.io%2Fjob%2Fsclarkso%2Fjob%2Fhelloworldvertx3%2Fjob%2Fmaster%2F1%2Fconsole">Moved Permanently</a>.
```

```
{"Errors":[{"code":"500","detail":"could not login to Jenkins in sclarkso-jenkins namespace"}]}<html><head><meta http-equiv='refresh' content='1;url=/securityRealm/commenceLogin?from=%2Fjob%2Fsclarkso%2Fjob%2Fhelloworldvertx1%2Fjob%2Fmaster%2F1%2Fconsole%3Ftoken_json%3D%257B%2522access_token%2522%253A%2522eyJhbGcixXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX22%257D');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>
```

Tried multiple 'update tenant' and did multiple 'reset environments' (over the course of a few hours) as well.

**Comment by lordofthejars** [comment] 2018-04-24 11:11
I have tried to reproduce this issue under different circumstances and I have not been able to reproduce this issue, in all cases the built has been promoted and deployed correctly.

Probably the problem is related to some load problem. Also I think that this problem is a duplicated of #3026 

cc/ @pradeepto @krishnapaparaju

**Comment by kishansagathiya** [comment] 2018-04-24 11:17
@pradeepto @lordofthejars This issue exactly same as https://github.com/openshiftio/openshift.io/issues/3026
Look at https://github.com/openshiftio/openshift.io/issues/3026#issuecomment-383790928
We should close this one, since the other one has more visibility

**Comment by rohanKanojia** [comment] 2018-04-24 14:47
duplicate of #3026

**Comment by joshuawilson** [comment] 2018-04-25 02:36
closing duplicate

**Closed by joshuawilson** 2018-04-25 02:36 UTC
Labels: SEV2-high, area/pipelines, priority/P0, team/build-cd, type/bug
