### ISSUE TITLE
Che multi-cluster support

### ISSUE THREAD

**Issue by alexeykazakov** [openshiftio/openshift.io#1683] opened 2017-12-15 00:10 UTC
As part of our multi-cluster support we should start using OSO-Proxy for all communications with OSO instead of calling OSO API directly from Che.

- [x] Change OSO api URL to OSO-Proxy URL and use OSIO user token instead of OSO token
- [x] Remove OSO token lookup.

Part of https://github.com/openshiftio/openshift.io/issues/948

**Comment by l0rd** [comment] 2017-12-18 10:50
@ibuziuk will contact @alexeykazakov and @aslakknutsen for updates on che-starter and che-server side

**Comment by ibuziuk** [comment] 2017-12-18 11:05
created a separate issue for che-starter - https://github.com/redhat-developer/che-starter/issues/254

**Comment by ibuziuk** [comment] 2017-12-18 19:12
@l0rd one thing I want to clarify in terms of multi-cluster support - is it planned to have 1 multi-tenant che per cluster or 1 multi-tenant che for all clusters ?

**Comment by l0rd** [comment] 2017-12-19 11:57
@alexeykazakov @ibuziuk I had a discussion about that a few weeks earlier with @kbsingh and I thought it was already acked that we would have multiple Che servers, one for every cluster. I still believe that's the best configuration but I don't have a firm position so let me provide the pros and cons of multiple Che servers and we can discuss it here:

**Pros**
- It scales better. Even if we think Che server is already able to serve hundreds of concurrent users it may be more thoughtful to prevent problems.  
- If we change our mind it should be easier to move from multiple Che server to a single Che server than the contrary 

**Cons**
- Users on different cluster won't be able to share their Che workspaces (but that's a feature that we currently don't have on OSIO)
- It may be more complicated to manage multiple Che server than to manage a single one

**Comment by ibuziuk** [comment] 2017-12-19 19:29
I also do not have strong opinion on this - both approaches have its for and against. It sounds like workspace sharing feature is the only thing that affects UX  and by choosing `1 mt che-server per cluster` workspace sharing will be available only for users on the same cluster. I believe this requires some input from PM side. cc: @slemeur @bmicklea

**Comment by ibuziuk** [comment] 2017-12-19 20:39
`If I did need to have collaboration with someone from another cluster then I can simply invite them to create an account on my cluster. It's hacky but it would work, right?`
Not sure about that. As I understand multi-cluster is just impl. detail and user is not in charge of picking cluster while account creation.

**Comment by alexeykazakov** [comment] 2017-12-20 03:17
> It scales better.

One che server per cluster IMO scales worse. Maybe it's better performance wise but it makes any manipulations with clusters (new clusters, updates in existing ones) more complicated.

If talking about performance then shouldn't we move to support of multiple che-server replicas instead?

**Comment by l0rd** [comment] 2017-12-20 10:10
> One che server per cluster IMO scales worse. Maybe it's better performance wise but it makes any manipulations with clusters (new clusters, updates in existing ones) more complicated.

Agree. We need to decide between making something slightly more complicated vs having a little performance risk.

> If talking about performance then shouldn't we move to support of multiple che-server replicas instead?

We need to solve this before https://github.com/eclipse/che/issues/7662 but yes I agree with you.

**Comment by l0rd** [comment] 2017-12-20 11:06
After discussion with @ibuziuk we agreed that the best approach will be to have a single multi-cluster Che server. And to raise priority for https://github.com/eclipse/che/issues/7662 to beeing able to scale when needed.

**Comment by ibuziuk** [comment] 2018-01-09 12:18
@alexeykazakov @aslakknutsen does OSO-proxy already available on prod-preview ?

**Comment by alexeykazakov** [comment] 2018-01-09 23:57
Not yet. But should be soon.

**Comment by maxandersen** [comment] 2018-01-22 16:06
marking as crucial dependency for #948 as without it we can't complete multicluster support.

**Comment by ibuziuk** [comment] 2018-01-22 16:09
@maxandersen FYI, the fix on che / che-starter side is ready we just do not want to merge it till OSO proxy would be available on prod - https://github.com/redhat-developer/rh-che/pull/514#issuecomment-359378172

**Comment by ibuziuk** [comment] 2018-01-24 17:33
@alexeykazakov @aslakknutsen che with oso-proxy is deployed on prod-preview and quick start scenario seems to work just fine \o/

**Comment by qodfathr** [comment] 2018-01-28 16:16
Removing SEV2 because it's not a bug. `crucial-dep` now relates the importance of this issue.

**Comment by ibuziuk** [comment] 2018-01-29 18:08
Che OSO proxy support is now on prod. Once it will be confirmed that multi-cluster is working with che as expected the issue can be closed

**Comment by aslakknutsen** [comment] 2018-01-29 18:13
Verified in preview and prod on new cluster.

**Closed by aslakknutsen** 2018-01-29 18:13 UTC
Labels: area/che, crucial-dep, team/che/osio, type/feature
