### ISSUE TITLE
Pipelines UI missing builds when repo name different from project name

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3343] opened 2018-04-27 13:04 UTC
1. switch your account to 'beta' features
2. create a space, e.g. `testaaa`
3. create a new project, e.g. `testbbb`, name GitHub repo differently, e.g. `testccc`
4. build nr. 1 finished, promote it
5. go to GitHub and commit a change

result:
* build nr. 2 should be displayed in Pipelines page but it never shows up
* when you go to OpenShift console, you can see that a new pipeline was started but it has a different name

![osio_different_names_oso2](https://user-images.githubusercontent.com/445100/39363878-26e783fe-4a2c-11e8-8272-86608e669569.png)

Jenkins:
![osio_different_names_jenkins2](https://user-images.githubusercontent.com/445100/39363875-26a88938-4a2c-11e8-976f-71d216acd2b2.png)

OSIO
![osio_different_names_osio2](https://user-images.githubusercontent.com/445100/39363876-26c79850-4a2c-11e8-8163-4a44a26cbb0e.png)

**Comment by andrewazores** [comment] 2018-04-29 03:04
@ebaron this is the same or similar to something you're working on, isn't it?

**Comment by ebaron** [comment] 2018-04-30 14:06
@andrewazores I'm not working on it directly, but I did encounter this and reported it (also was a duplicate).

This seems to be a duplicate of https://github.com/openshiftio/openshift.io/issues/3095. Feel free to re-open if I'm mistaken.

**Closed by ebaron** 2018-04-30 14:06 UTC
Labels: SEV2-high, area/pipelines, team/build-cd, type/bug

**Comment by ppitonak** [comment] 2018-05-03 07:12
Yes, it is a duplicate.
